var pairs =
{
"jetson":{"tx1":1,"sdk":1,"developer":1,"platform":1,"system":1,"available":1,"tk1":1,"tx2":1,"target":1,"dev":1,"trademarks":1}
,"tx1":{"tx2":1,"developer":1,"fcc":1,"p3310":1,"7361a-p2180":1,"945-82371-0005-000":1,"jetson":1,"(ccaj15lp6160t6)":1,"cmiit":1}
,"tx2":{"developer":1,"compiling":1,"module":1,"download":1,"fcc":1,"jetson":1,"7361a-p3310":1,"945-82771-0005-000":1,"msip-crm-nva-p2180":1,"ccaj15lp6160t6":1,"(ccaj17lp1260t1)":1,"cmiit":1}
,"developer":{"kits":1,"tools":1,"kit":1,"sdk":1,"zone":1,"environment":1}
,"kits":{"da_07976_001_01":1,"jetson":1,"powering":1,"nvidia":1,"provide":1,"designed":1,"compliant":1}
,"da_07976_001_01":{"march":1,"da_07976_001_01":1,"table":1,"jetson":1,"carrier":1,"flashing":1,"<platform>":1,"<client":1,"target":1,"tegra":1,"jetpack":1,"select":1,"accept":1,"selected":1,"prompted":1,"compiling":1,"compliance":1,"radiation":1,"canada":1,"device":1,"5745":1,"south":1,"(id)":1,"environmental":1,"china":1,"taiwan":1,"note":1}
,"march":{"2018":1}
,"2018":{"user":1}
,"user":{"guide":1,"name":1,"space":1,"kernel":1,"encouraged":1,"authority":1}
,"guide":{"jetson":1}
,"table":{"contents":1,"(bct)":1,"hazardous":1,"according":1,"compliance":1,"\u201C-\u201D":1}
,"contents":{"jetson":1}
,"powering":{"force":1,"connect":1}
,"force":{"recovery":1,"usb":1,"button":1}
,"recovery":{"mode":1,"(usb":1,"force":1,"port":1,"button":1}
,"mode":{"flashing":1,"update":1,"(rcm)":1,"power":1,"follows":1,"flash":1}
,"flashing":{"boot":1,"booting":1,"procedure":1,"tools":1,"commands":1,"add":1,"connect":1,"pushing":1}
,"boot":{"loader":1,"configuration":1,"partition":1,"script":1}
,"loader":{"kernel":1,"boot":1,"flashing":1,"fastboot.bin":1}
,"kernel":{"flash":1,"topic":1,"optionally":1,"zimage":1,"modules":1,"loads":1,"command":1,"as-is":1,"partition":1,"command-line":1,"image":1}
,"flash":{"script":1,"root":1,"target":1,"application":1,"server":1,"jetson":1,"component":1}
,"script":{"usage":1,"flashing":1,"top-level":1,"supplied":1,"follows":1,"file":1,"adds":1}
,"usage":{"jetpack":1,"information":1,"detailed":1,"sudo":1}
,"jetpack":{"jetpack":1,"components":1,"installing":1,"jetson":1,"samples":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded-computing":1,"nvidia":1,"comprehensive":1,"includes":1,"enables":1,"latest":1,"version":1,"installer":1,"proceeds":1,"installs":1,"automatically":1,"built":1}
,"components":{"images":1,"jetpack":1,"install":1,"jetson":1,"component":1,"selected":1,"target":1,"specific":1,"selection":1,"cuda":1,"life":1}
,"images":{"libraries":1,"jetpack":1}
,"libraries":{"developer":1,"apis":1,"jetpack":1,"cuda":1}
,"tools":{"downloading":1,"supporting":1,"nvflash":1,"apis":1,"middleware":1,"jetpack":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fjetpack":1}
,"downloading":{"jetpack":1}
,"installing":{"jetpack":1}
,"compiling":{"running":1,"samples":1,"jetpack":1}
,"running":{"jetpack":1,"quickly":1,"flashing":1,"following":1,"sms=53":1}
,"samples":{"compliance":1,"help":1,"documentation":1,"using":1,"nvidia":1,"available":1,"post":1,"compile":1,"checked":1,"located":1,"running":1,"cuda":1,"directory":1,"command":1}
,"compliance":{"united":1,"nvidia":1,"marks":1,"rss":1,"european":1}
,"united":{"states":1}
,"states":{"canada":1,"federal":1,"countries":1}
,"canada":{"european":1,"industry":1,"(ic)":1,"applicables":1}
,"european":{"union":1,"conformity":1,"union\u2019s":1}
,"union":{"australia":1,"european":1}
,"australia":{"new":1}
,"new":{"zealand":1}
,"zealand":{"japan":1,"australian":1}
,"japan":{"south":1,"voluntary":1}
,"south":{"korea":1}
,"korea":{"taiwan":1,"radio":1}
,"taiwan":{"china":1,"rohs":1,"national":1}
,"china":{"singapore":1,"rohs":1,"state":1}
,"singapore":{"environmental":1,"info-communications":1,"jetson":1}
,"environmental":{"disclosures":1,"protection":1}
,"disclosures":{"china":1,"california":1}
,"rohs":{"material":1,"directive":1,"parts":1,"legislation":1}
,"material":{"content":1,"flux":1}
,"content":{"declaration":1,"required":1,"restricted":1}
,"declaration":{"taiwan":1,"nvidia":1,"conformity":1,"table":1,"declaration":1,"presence":1}
,"nvidia":{"confidential":1,"jetson":1,"development":1,"user":1,"tegra":1,"jetpack":1,"gameworks":1,"embedded":1,"accessories":1,"pour":1,"guarantis":1,"gmbh":1,"nvidia":1,"logo":1,"u.s":1,"design":1,"makes":1,"assumes":1,"specifications":1,"products":1,"trademarks":1,"united":1,"license":1}
,"confidential":{"jetson":1}
,"provide":{"full-featured":1,"reasonable":1}
,"full-featured":{"development":1}
,"development":{"platform":1,"toolchain":1,"efforts":1,"software":1,"environment":1,"kit":1,"authority":1}
,"platform":{"visual":1,"jetpack":1,"includes":1,"makes":1,"requirements":1,"information":1}
,"visual":{"computing":1}
,"computing":{"ideal":1,"automates":1,"applications":1}
,"ideal":{"applications":1}
,"applications":{"requiring":1,"additionally":1,"cuda":1,"visionworks":1,"developer":1}
,"requiring":{"high":1}
,"high":{"computational":1,"performance":1}
,"computational":{"performance":1}
,"performance":{"low":1,"deep":1,"information":1}
,"low":{"power":1}
,"power":{"envelope":1,"connector":1,"adapter":1,"button":1,"down":1,"board":1,"frequency":1,"supply":1}
,"envelope":{"jetson":1}
,"designed":{"running":1,"provide":1}
,"quickly":{"pre-flashed":1}
,"pre-flashed":{"linux":1}
,"linux":{"environment":1,"host":1,"x64":1}
,"environment":{"includes":1,"nvidia":1,"begin":1,"developers":1,"setup":1,"selected":1,"equipment":1,"used":1}
,"includes":{"support":1,"image":1,"host":1,"images":1,"sample":1,"following":1}
,"support":{"common":1,"cuda":1,"available":1,"devices":1}
,"common":{"apis":1}
,"apis":{"supports":1,"packages":1,"developer":1}
,"supports":{"nvidia":1,"jetson":1}
,"toolchain":{"developer":1}
,"kit":{"carrier":1,"host":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded-computing":1,"serial":1,"power":1,"connected":1,"hdmi":1,"developing":1,"jetson":1,"support":1,"target":1,"model":1,"tested":1,"ete":1,"antennas":1,"equipment":1,"parts":1,"trademarks":1}
,"carrier":{"board":1}
,"board":{"exposes":1,"cabled":1,"external":1,"usb":1,"boot":1,"reset\u002Frecovery":1,"hold":1,"(jetson-tx1":1}
,"exposes":{"standard":1}
,"standard":{"hardware":1}
,"hardware":{"interfaces":1,"version":1}
,"interfaces":{"enabling":1}
,"enabling":{"highly":1,"developers":1}
,"highly":{"flexible":1}
,"flexible":{"extensible":1}
,"extensible":{"platform":1}
,"sdk":{"supports":1,"documentation":1,"visual":1,"includes":1}
,"host":{"development":1,"desired":1,"directly":1,"connect":1,"target":1,"operating":1,"flashing":1,"installation":1,"access":1,"machine":1}
,"image":{"load":1,"zimage":1}
,"load":{"onto":1}
,"onto":{"device":1}
,"device":{"developer":1,"connect":1,"supplied":1,"plug":1,"prompted":1,"os-specific":1,"connected":1,"device":1,"powered":1,"end":1,"system":1,"usage":1,"put":1,"enumerates":1,"(such":1,"tree":1,"<flashapp>":1,"entering":1,"jetson":1,"access":1,"assigned":1,"force":1,"jetpack":1,"complies":1,"may":1,"accept":1,"equipment":1,"pursuant":1,"expressly":1,"underwriters":1,"operation":1,"note":1,"persons":1,"bears":1,"modifications":1}
,"supporting":{"documentation":1}
,"documentation":{"code":1,"place":1,"including":1,"information":1}
,"code":{"samples":1}
,"help":{"started":1,"compiling":1,"fcc":1}
,"started":{"individual":1}
,"individual":{"development":1}
,"efforts":{"vary":1}
,"vary":{"may":1}
,"may":{"result":1,"cause":1,"ensure":1,"obtained":1,"trademarks":1}
,"result":{"modifications":1,"license":1}
,"modifications":{"system":1,"device":1}
,"system":{"configuration":1,"operation":1,"powers":1,"force":1,"software":1,"powered":1,"download":1,"\u002Fnv_tegra":1,"$sudo":1,"usb":1,"card":1,"internal":1,"latest":1,"linux":1,"hdmi":1,"derived":1,"profiler":1,"trace":1,"module":1,"memory":1}
,"configuration":{"best":1,"shipped":1,"table":1,"device":1,"file":1}
,"best":{"results":1}
,"results":{"begin":1}
,"begin":{"basic":1,"developing":1}
,"basic":{"system":1}
,"shipped":{"ensure":1}
,"ensure":{"proper":1,"compliance":1}
,"proper":{"system":1}
,"operation":{"prior":1,"subject":1,"device":1,"band":1,"accessories":1,"5150":1}
,"prior":{"further":1,"running":1}
,"further":{"development":1}
,"software":{"updates":1,"jetson":1,"write":1}
,"updates":{"latest":1}
,"latest":{"jetpack":1,"images":1,"version":1}
,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded-computing":{"prerequisites":1,"jetson":1}
,"prerequisites":{"jetson":1,"following":1}
,"cabled":{"follows":1}
,"follows":{"ethernet":1,"power":1,"$sudo":1,"parameters":1,"usb":1}
,"ethernet":{"cable":1,"port":1,"interface":1}
,"cable":{"plugged":1,"connecting":1,"recovery":1,"required":1}
,"plugged":{"on-board":1,"serial":1,"jetson":1}
,"on-board":{"ethernet":1}
,"port":{"hdmi":1,"usb":1,"target":1,"device":1,"host":1,"prior":1,"(j1c2":1,"connected":1,"serial":1,"j1a2":1}
,"hdmi":{"cable":1,"display":1,"connector":1,"port":1}
,"connecting":{"carrier":1,"jetson":1}
,"external":{"hdmi":1,"sdcard":1,"usb":1}
,"display":{"connect":1,"hdmi":1,"ethernet":1}
,"connect":{"multiple":1,"usb":1,"hdmi-compatible":1,"adapter":1,"micro-b":1,"power":1,"equipment":1}
,"multiple":{"usb":1}
,"usb":{"peripherals":1,"hub":1,"port":1,"keyboard":1,"type":1,"recovery":1,"cable":1,"disk":1,"device":1,"memory":1,"ethernet":1,"micro-b":1}
,"peripherals":{"keyboard":1}
,"keyboard":{"mouse":1,"usb":1}
,"mouse":{"usb\u002Fethernet":1}
,"usb\u002Fethernet":{"adapter":1}
,"adapter":{"network":1,"supplied":1,"appropriately":1,"device":1,"camera":1}
,"network":{"connection":1,"assignments":1,"layout":1}
,"connection":{"usb":1,"target":1}
,"hub":{"connected":1,"provided":1,"included":1}
,"connected":{"carrier":1,"linux":1,"remove":1,"recovery":1,"device":1,"follows":1,"working":1,"external":1,"consult":1}
,"provided":{"part":1,"flash.sh":1,"california":1,"nvidia":1}
,"part":{"developer":1,"fcc":1,"below":1,"above":1}
,"serial":{"console":1,"cable":1,"port":1}
,"console":{"linux":1}
,"desired":{"serial":1}
,"target":{"connected":1,"tegra":1,"device":1,"board":1,"tools":1,"platform":1,"specific":1,"components":1,"corresponding":1,"de-selected":1,"interface":1,"machine":1}
,"directly":{"serial-to-usb":1,"nvidia":1}
,"serial-to-usb":{"converter":1}
,"converter":{"powering":1,"jetpack":1}
,"type":{"connector":1,"lesser\u002Fequal":1,"gain":1}
,"connector":{"device":1}
,"hdmi-compatible":{"display":1}
,"supplied":{"kit":1,"adapter":1,"target":1,"designated":1,"development":1,"nvidia":1}
,"appropriately":{"rated":1}
,"rated":{"device":1,"electrical":1}
,"plug":{"power":1,"usb":1}
,"electrical":{"outlet":1,"electronic":1}
,"outlet":{"system":1,"circuit":1}
,"powers":{"press":1}
,"press":{"release":1,"hold":1,"reset":1}
,"release":{"power":1,"reset":1,"recovery":1,"script":1}
,"button":{"device":1,"depressing":1,"press":1,"wait":1,"jetson":1,"run":1,"continue":1}
,"prompted":{"enter":1,"install":1}
,"enter":{"nvidia":1,"sudo":1,"address":1}
,"name":{"password":1,"valid":1,"jetson":1}
,"password":{"force":1,"component":1,"ssh":1}
,"update":{"system":1}
,"(rcm)":{"transfer":1,"product":1}
,"transfer":{"system":1}
,"module":{"force":1,"model":1,"antenna":1}
,"write":{"boot":1,"partition":1}
,"(bct)":{"write":1,"file":1}
,"partition":{"configuration":1,"updated":1,"size":1}
,"os-specific":{"instructions":1}
,"instructions":{"updating":1,"may":1}
,"updating":{"system":1}
,"place":{"system":1}
,"down":{"device":1}
,"remove":{"adapter":1}
,"powered":{"suspend":1,"press":1}
,"suspend":{"sleep":1}
,"sleep":{"state":1}
,"state":{"connect":1,"radio":1,"california":1}
,"micro-b":{"plug":1,"cable":1}
,"(usb":{"micro-b)":1}
,"micro-b)":{"port":1}
,"end":{"available":1}
,"available":{"usb":1,"running":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fgameworks-opengl-samples":1,"nvidia":1,"run":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fsupport":1}
,"hold":{"recovery":1}
,"depressing":{"recovery":1}
,"reset":{"button":1}
,"wait":{"seconds":1}
,"seconds":{"release":1}
,"topic":{"describes":1}
,"describes":{"steps":1}
,"steps":{"required":1,"completed":1}
,"required":{"flashing":1,"connected":1,"parameters":1,"complete":1,"information":1,"management":1}
,"booting":{"target":1,"script":1,"related":1}
,"tegra":{"device":1,"user":1,"graphics":1,"system":1}
,"information":{"provided":1,"u-boot":1,"available":1,"<bctfile>":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fjetpack":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Ftegra-graphics-debugger":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Ftegra-system-profiler":1,"click":1,"furnished":1,"infringement":1,"previously":1}
,"flash.sh":{"helper":1,"script":1,"usage":1}
,"helper":{"script":1}
,"procedure":{"flashes":1}
,"flashes":{"board":1}
,"optionally":{"flash":1,"specifies":1}
,"root":{"filesystem":1,"file":1}
,"filesystem":{"internal":1}
,"internal":{"emmc":1,"rootdev":1}
,"emmc":{"prerequisites":1,"execute":1,"mmcblk1p1":1,"size":1,"boot":1}
,"following":{"directories":1,"argument":1,"command":1,"mmcblk0p1":1,"libraries":1,"developer":1,"directory":1,"screen":1,"two":1,"measures":1,"directives":1,"frequency":1}
,"directories":{"present":1}
,"present":{"\u002Fbootloader":1}
,"\u002Fbootloader":{"boot":1}
,"nvflash":{"cfg":1,"boot":1,"configuration":1,"tegra-rcm":1}
,"cfg":{"bct":1}
,"bct":{"\u002Fkernel":1}
,"\u002Fkernel":{"kernel":1}
,"zimage":{"\u002Fvmlinux.uimg":1,"<bootloader>":1}
,"\u002Fvmlinux.uimg":{"dtb":1}
,"dtb":{"files":1}
,"files":{"kernel":1,"drawings":1}
,"modules":{"\u002Frootfs":1}
,"\u002Frootfs":{"root":1}
,"file":{"system":1,"<cfgfile>":1,"<dtbfile>":1,"instead":1,"u-boot":1,"null":1,"name":1,"browser":1}
,"download":{"directory":1,"latest":1}
,"directory":{"empty":1,"release":1,"<nfsroot>":1,"jetson":1,"copied":1,"device":1,"\u002Fhome\u002Fubuntu\u002Fnvidia_cuda-<version>_samples\u002Fbin\u002Farmv7l\u002Flinux\u002Frelease\u002Fgnueabihf\u002Frun":1}
,"empty":{"initially":1}
,"initially":{"populate":1}
,"populate":{"sample":1}
,"sample":{"file":1,"applications":1,"rootfs":1,"following":1}
,"\u002Fnv_tegra":{"nvidia":1}
,"space":{"binaries":1,"required":1}
,"binaries":{"sample":1,"following":1}
,"additionally":{"usb":1}
,"commands":{"flash":1}
,"put":{"target":1,"device":1}
,"reset\u002Frecovery":{"mode":1}
,"run":{"flash.sh":1,"jetpack-${version}":1,"standalone":1,"oceanfft":1}
,"top-level":{"directory":1}
,"(jetson-tx1":{"jetson-tx2)":1}
,"jetson-tx2)":{"root":1}
,"$sudo":{".\u002Fflash.sh":1}
,".\u002Fflash.sh":{"<platform>":1,"[options]":1}
,"<platform>":{"<rootdev>":1,"sda1":1,"mmcblk1p1":1,"mmcblk0p1":1,"jetson-tx1":1}
,"<rootdev>":{"root":1,"specify":1,"following":1}
,"disk":{"execute":1,"space":1}
,"execute":{"script":1,"permissions":1}
,"sda1":{"sata":1,"root":1,"specifies":1}
,"sata":{"device":1}
,"enumerates":{"sda1":1}
,"card":{"execute":1}
,"mmcblk1p1":{"root":1,"specifies":1}
,"mmcblk0p1":{"jetson":1,"specifies":1}
,"jetson-tx1":{"jetson-tx2":1}
,"jetson-tx2":{"above":1,"<rootdev>":1}
,"above":{"examples":1,"limit":1}
,"examples":{"u-boot":1}
,"u-boot":{"fastboot":1,"u-boot":1,"customization":1,"<cmdline>":1,"jetpack":1}
,"fastboot":{"flashing":1,"case":1}
,"add":{"following":1,"execute":1}
,"argument":{"<path_to_fastboot_bin_file>":1}
,"<path_to_fastboot_bin_file>":{"boot":1}
,"loads":{"information":1}
,"customization":{"flash":1}
,"detailed":{"usage":1}
,"command":{"flash.sh":1,"line":1}
,"sudo":{".\u002Fflash.sh":1,"permission":1,"password":1}
,"[options]":{"<platform>":1}
,"specify":{"required":1}
,"parameters":{"options":1,"description":1}
,"options":{"follows":1,"description":1}
,"description":{"<platform>":1,"specifies":1}
,"specifies":{"internal":1,"external":1,"nfsroot":1,"print":1,"nvflash":1,"device":1,"emmc":1,"path":1,"pass":1,"kernel":1,"static":1,"odm":1,"skip":1,"boot":1,"flash":1,"initrd":1,"full":1,"sum":1,"sample":1,"rootfs":1}
,"sdcard":{"sda1":1}
,"(such":{"usb":1}
,"memory":{"stick":1,"power":1}
,"stick":{"hdd)":1}
,"hdd)":{"eth0":1}
,"eth0":{"specifies":1}
,"nfsroot":{"via":1,"example":1}
,"via":{"external":1,"router\u002Fswitch":1,"host":1}
,"interface":{"options":1,"internet":1,"pop-up":1}
,"print":{"usage":1}
,"<bctfile>":{"specifies":1}
,"<cfgfile>":{"specifies":1}
,"<dtbfile>":{"optionally":1}
,"tree":{"file":1}
,"instead":{"default":1}
,"default":{"<emmc_file>":1,"<kernel>":1}
,"<emmc_file>":{"specifies":1}
,"size":{"target":1,"specifies":1,"ppt":1,"bytes":1}
,"<flashapp>":{"specifies":1}
,"path":{"flash":1,"boot":1}
,"application":{"nvflash":1,"performance":1}
,"tegra-rcm":{"specifies":1}
,"pass":{"user":1}
,"line":{"kernel":1,"warning":1,"double-clicking":1}
,"as-is":{"<partition":1}
,"<partition":{"id>":1}
,"id>":{"specifies":1}
,"updated":{"(minimum":1}
,"(minimum":{"=5)":1}
,"=5)":{"<nfs":1}
,"<nfs":{"args>":1}
,"args>":{"specifies":1}
,"static":{"nfs":1}
,"nfs":{"network":1,"booting":1}
,"assignments":{"file:\u002F\u002F\u002Fc:\u002Fsw\u002Fswdocs\u002Fmobile\u002Ftegra\u002Femb\u002Fl4t_uboot_guide_tx1.docx":1}
,"file:\u002F\u002F\u002Fc:\u002Fsw\u002Fswdocs\u002Fmobile\u002Ftegra\u002Femb\u002Fl4t_uboot_guide_tx1.docx":{"jetson":1}
,"<client":{"ip>":1}
,"ip>":{"<server":1,"<gateway":1,"<netmask>":1}
,"<server":{"ip>":1}
,"<gateway":{"ip>":1}
,"<netmask>":{"<odmdata>":1}
,"<odmdata>":{"specifies":1}
,"odm":{"data":1}
,"data":{"value":1,"helping":1}
,"value":{"total":1,"presence":1}
,"total":{"emmc":1}
,"skip":{"building":1}
,"building":{"reuse":1,"gpu-accelerated":1}
,"reuse":{"existing":1}
,"existing":{"system.img":1}
,"system.img":{"<ubootscript>":1}
,"<ubootscript>":{"specifies":1}
,"<cmdline>":{"specifies":1}
,"warning":{"option":1,"fcc":1,"operation":1,"california":1,"provided":1,"product":1}
,"option":{"kernel":1,"fastboot":1,"omitted":1}
,"command-line":{"gets":1}
,"gets":{"higher":1}
,"higher":{"precedence":1}
,"precedence":{"option":1}
,"case":{"nfs":1}
,"adds":{"nfs":1}
,"related":{"arguments":1}
,"arguments":{"option":1}
,"omitted":{"<flasher>":1}
,"<flasher>":{"specifies":1}
,"server":{"fastboot.bin":1,"host":1}
,"fastboot.bin":{"<initrd>":1,"u-boot.bin":1}
,"<initrd>":{"specifies":1}
,"initrd":{"file":1,"default":1}
,"null":{"initrd":1}
,"<kernel>":{"specifies":1}
,"<bootloader>":{"specifies":1}
,"full":{"path":1,"text":1}
,"u-boot.bin":{"<end_of_ppt_pl":1}
,"<end_of_ppt_pl":{"us_1>":1}
,"us_1>":{"specifies":1}
,"sum":{"primary":1}
,"primary":{"gpt":1,"users":1}
,"gpt":{"start":1}
,"start":{"address":1}
,"address":{"size":1,"user":1}
,"ppt":{"plus":1}
,"plus":{"<rootfs":1}
,"<rootfs":{"dir>":1}
,"dir>":{"specifies":1}
,"rootfs":{"directory":1,"size":1}
,"<nfsroot>":{"specifies":1}
,"example":{"<my":1,"1gib":1,"flashing":1,"run":1}
,"<my":{"addr>":1}
,"addr>":{":\u002Fmy\u002Fexported\u002Fnfs\u002Frootfs":1}
,":\u002Fmy\u002Fexported\u002Fnfs\u002Frootfs":{"<size>":1}
,"<size>":{"specifies":1}
,"bytes":{"valid":1,"<its":1}
,"valid":{"internal":1,"u-boot":1}
,"rootdev":{"kib":1}
,"kib":{"mib":1}
,"mib":{"gib":1}
,"gib":{"style":1}
,"style":{"shorthand":1}
,"shorthand":{"allowed":1}
,"allowed":{"example":1}
,"1gib":{"signifies":1}
,"signifies":{"1024":1}
,"1024":{"*1024":1}
,"*1024":{"*1024":1,"bytes":1}
,"<its":{"file>":1}
,"file>":{"file":1}
,"comprehensive":{"sdk":1,"development":1}
,"automates":{"installation":1}
,"installation":{"development":1,"jetpack":1,"directory":1,"process":1,"components":1,"once":1,"steps":1,"target":1,"tasks":1,"complete":1,"equipment":1}
,"makes":{"easy":1,"warranties":1}
,"easy":{"flash":1}
,"packages":{"middleware":1}
,"middleware":{"samples":1}
,"including":{"help":1,"fcc":1,"interference":1,"implied":1}
,"using":{"jetpack":1}
,"enables":{"jumpstart":1}
,"jumpstart":{"environment":1}
,"developing":{"supported":1,"customize":1}
,"supported":{"host":1}
,"operating":{"systems":1,"conditions":1}
,"systems":{"ubuntu":1,"antennas":1,"without":1}
,"ubuntu":{"linux":1,"libraries":1,"cross-development":1,"install":1}
,"x64":{"version":1}
,"version":{"14.04":1,"jetson":1,"jetpack-${version}":1,"string":1,"7.35.221.11":1}
,"14.04":{"least":1}
,"least":{"disk":1,"maintained":1,"homogeneous":1}
,"complete":{"installation":1,"jetson":1}
,"requirements":{"jetson":1,"separation":1,"class":1,"japan":1}
,"working":{"usb":1}
,"(j1c2":{"usb2)":1}
,"usb2)":{"jetson":1}
,"included":{"developer":1}
,"j1a2":{"uart4":1}
,"uart4":{"target":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fjetpack":{"images":1,"jetson":1,"installing":1}
,"derived":{"ubuntu":1}
,"cuda":{"toolkit":1,"components":1,"samples":1}
,"toolkit":{"provides":1,"ubuntu":1,"l4t":1}
,"provides":{"comprehensive":1,"interactive":1}
,"developers":{"building":1,"debug":1,"jetson":1}
,"gpu-accelerated":{"applications":1}
,"cross-development":{"support":1}
,"l4t":{"tensorrt":1}
,"tensorrt":{"cudnn":1}
,"cudnn":{"high":1}
,"deep":{"learning":1}
,"learning":{"applications":1}
,"visionworks":{"opencv":1}
,"opencv":{"visual":1}
,"graphics":{"debugger":1}
,"debugger":{"console-grade":1}
,"console-grade":{"tool":1}
,"tool":{"allows":1}
,"allows":{"developers":1}
,"debug":{"profile":1}
,"profile":{"opengl":1}
,"opengl":{"2.0":1,"4.3":1,"samples":1}
,"2.0":{"3.0":1}
,"3.0":{"3.1":1}
,"3.1":{"3.2":1}
,"3.2":{"opengl":1}
,"4.3":{"4.4":1}
,"4.4":{"4.5":1}
,"4.5":{"enabling":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Ftegra-graphics-debugger":{"tegra":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Ftegra-system-profiler":1}
,"profiler":{"system":1,"provides":1}
,"trace":{"multi-core":1}
,"multi-core":{"cpu":1}
,"cpu":{"sampling":1}
,"sampling":{"profiler":1}
,"interactive":{"view":1}
,"view":{"captured":1}
,"captured":{"profiling":1}
,"profiling":{"data":1}
,"helping":{"improve":1}
,"improve":{"overall":1}
,"overall":{"application":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Ftegra-system-profiler":{"samples":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fgameworks-opengl-samples":1}
,"gameworks":{"vulkan":1}
,"vulkan":{"opengl":1}
,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fgameworks-opengl-samples":{"downloading":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fjetpack":1}
,"embedded":{"developer":1,"system":1}
,"zone":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fjetpack":1}
,"jetpack-${version}":{".run":1}
,".run":{"${version}":1,"chmod":1,"run":1,"terminal":1}
,"${version}":{"refers":1}
,"refers":{"version":1}
,"string":{"installer":1}
,"installer":{"add":1,"indicates":1,"pop-up":1}
,"permissions":{"jetpack-${version}":1}
,"chmod":{"jetpack-${version}":1}
,"terminal":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Ftegra-graphics-debugger":1}
,"indicates":{"installation":1,"hazardous":1,"percentage":1,"restricted":1}
,"select":{"developer":1,"jetson":1,"network":1,"interface":1}
,"setup":{"jetpack":1}
,"pop-up":{"window":1}
,"window":{"displays":1}
,"displays":{"prompts":1,"instructing":1}
,"prompts":{"sudo":1}
,"permission":{"during":1}
,"during":{"installation":1,"components":1,"device":1}
,"process":{"enter":1}
,"component":{"manager":1,"logo":1}
,"manager":{"opens":1,"proceeds":1,"enter":1,"select":1}
,"opens":{"allowing":1}
,"allowing":{"customize":1}
,"customize":{"components":1,"installation":1}
,"install":{"jetson":1,"deselect":1,"components":1}
,"tk1":{"developer":1}
,"standalone":{"ubuntu":1}
,"deselect":{"jetson":1}
,"specific":{"entries":1,"environment":1,"target":1}
,"entries":{"jetson":1}
,"accept":{"license":1,"interference":1}
,"license":{"agreement":1,"granted":1}
,"agreement":{"selected":1}
,"selected":{"components":1,"example":1,"flash":1,"device":1,"cuda":1}
,"proceeds":{"installation":1,"setting":1}
,"once":{"host":1}
,"completed":{"click":1,"installation":1}
,"click":{"next":1}
,"next":{"button":1,"jetpack":1}
,"continue":{"installation":1}
,"setting":{"jetson":1}
,"corresponding":{"components":1}
,"pushing":{"components":1}
,"de-selected":{"flash":1}
,"ssh":{"connection":1}
,"entering":{"required":1}
,"installs":{"components":1}
,"layout":{"specific":1,"select":1}
,"access":{"internet":1,"jetson":1,"target":1}
,"internet":{"via":1,"access":1}
,"router\u002Fswitch":{"layout":1}
,"assigned":{"dhcp":1}
,"dhcp":{"server":1}
,"machine":{"layout":1,"compile":1}
,"instructing":{"put":1}
,"compile":{"samples":1}
,"post":{"installation":1}
,"tasks":{"completed":1}
,"automatically":{"compiles":1}
,"compiles":{"samples":1}
,"checked":{"during":1}
,"selection":{"selected":1}
,"located":{"<jetpack_install_dir>\u002Fnvidia_cuda-<version>_samples":1}
,"<jetpack_install_dir>\u002Fnvidia_cuda-<version>_samples":{"recompile":1}
,"recompile":{"samples":1}
,"sms=53":{"extra_ldflags=--unresolved-symbols=ignore-in-shared-libs":1}
,"extra_ldflags=--unresolved-symbols=ignore-in-shared-libs":{"target_arch=aarch64":1}
,"target_arch=aarch64":{"running":1}
,"copied":{"home":1}
,"home":{"directory":1}
,"built":{"binaries":1}
,"\u002Fhome\u002Fubuntu\u002Fnvidia_cuda-<version>_samples\u002Fbin\u002Farmv7l\u002Flinux\u002Frelease\u002Fgnueabihf\u002Frun":{"samples":1}
,"double-clicking":{"file":1}
,"browser":{"example":1}
,"oceanfft":{"sample":1}
,"screen":{"displayed":1}
,"displayed":{"jetson":1}
,"compliant":{"regulations":1}
,"regulations":{"listed":1,"committee":1}
,"listed":{"section":1,"product":1}
,"section":{"compliance":1}
,"marks":{"including":1,"nvidia":1}
,"fcc":{"numbers":1,"vob-p2180":1,"vob":1,"rules":1,"warning":1,"requires":1,"radiation":1,"number":1}
,"numbers":{"found":1,"p2180":1}
,"found":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fsupport":1,"comply":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fsupport":{"united":1,"jetson":1,"copy":1}
,"federal":{"communications":1}
,"communications":{"commission":1,"however":1,"media":1}
,"commission":{"(fcc)":1,"jetson":1}
,"(fcc)":{"jetson":1}
,"vob-p2180":{"jetson":1}
,"vob":{"p3310":1}
,"p3310":{"device":1,"jetson":1}
,"complies":{"part":1,"fcc":1,"industry":1,"ised":1,"following":1}
,"rules":{"operation":1,"limits":1}
,"subject":{"following":1,"change":1}
,"two":{"conditions":1}
,"conditions":{"(1)":1,"suivantes":1,"product":1,"representations":1}
,"(1)":{"device":1}
,"cause":{"harmful":1,"undesired":1,"interference":1,"cancer":1}
,"harmful":{"interference":1}
,"interference":{"(2)":1,"received":1,"may":1,"residential":1,"radio":1,"occur":1,"following":1,"including":1,"co-channel":1,"and\u002For":1,"(vcci)":1}
,"(2)":{"device":1}
,"received":{"including":1}
,"undesired":{"operation":1}
,"equipment":{"tested":1,"generates":1,"cause":1,"user":1,"receiver":1,"outlet":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fsupport":1,"complies":1,"installed":1,"directive":1,"hardware":1,"applicable":1,"requirements":1,"name":1}
,"tested":{"found":1,"complies":1}
,"comply":{"limits":1}
,"limits":{"class":1,"designed":1,"forth":1}
,"class":{"digital":1,"i.t.e":1}
,"digital":{"device":1}
,"pursuant":{"part":1}
,"reasonable":{"protection":1}
,"protection":{"against":1,"period":1}
,"against":{"harmful":1}
,"residential":{"installation":1}
,"generates":{"uses":1}
,"uses":{"radiate":1}
,"radiate":{"radio":1}
,"radio":{"frequency":1,"communications":1,"television":1,"exempts":1,"equipment":1,"research":1,"regulations":1}
,"frequency":{"energy":1,"bands":1,"band":1}
,"energy":{"installed":1}
,"installed":{"used":1,"operated":1}
,"used":{"accordance":1,"device":1,"nvidia":1,"part":1}
,"accordance":{"instructions":1,"directive":1}
,"however":{"guarantee":1,"nvidia":1}
,"guarantee":{"interference":1}
,"occur":{"particular":1}
,"particular":{"installation":1,"purpose":1}
,"television":{"reception":1}
,"reception":{"determined":1}
,"determined":{"turning":1,"according":1}
,"turning":{"equipment":1}
,"encouraged":{"try":1}
,"try":{"correct":1}
,"correct":{"interference":1}
,"measures":{"reorient":1}
,"reorient":{"relocate":1}
,"relocate":{"receiving":1}
,"receiving":{"antenna":1}
,"antenna":{"increase":1,"jetson":1,"mechanicals":1}
,"increase":{"separation":1}
,"separation":{"equipment":1,"distance":1}
,"receiver":{"connect":1,"connected":1}
,"circuit":{"different":1}
,"different":{"receiver":1}
,"consult":{"dealer":1}
,"dealer":{"experienced":1}
,"experienced":{"radio\u002Ftv":1}
,"radio\u002Ftv":{"technician":1}
,"technician":{"help":1}
,"requires":{"notified":1,"warning":1}
,"notified":{"changes":1}
,"changes":{"modifications":1}
,"expressly":{"approved":1}
,"approved":{"manufacturer":1}
,"manufacturer":{"void":1,"voids":1}
,"void":{"user\u2019s":1}
,"user\u2019s":{"authority":1}
,"authority":{"operate":1,"(rcm)":1,"singapore":1}
,"operate":{"equipment":1,"following":1}
,"radiation":{"exposure":1}
,"exposure":{"statement":1,"limits":1,"requirements":1,"guidelines":1}
,"statement":{"equipment":1,"jetson":1}
,"forth":{"uncontrolled":1}
,"uncontrolled":{"environment":1}
,"operated":{"minimum":1}
,"minimum":{"distance":1}
,"distance":{"centimeters":1,"least":1,"s\u00E9paration":1,"radiator":1}
,"centimeters":{"radiator":1}
,"radiator":{"body":1}
,"body":{"antennas":1,"pulse":1}
,"antennas":{"type":1,"supplied":1}
,"lesser\u002Fequal":{"gain":1}
,"gain":{"filed":1,"moindre":1,"used":1}
,"filed":{"fcc":1,"number":1}
,"number":{"used":1,"p2597":1}
,"underwriters":{"laboratories":1}
,"laboratories":{"(ul)":1}
,"(ul)":{"listed":1}
,"product":{"logo":1,"satisfy":1,"meets":1,"contains":1,"temperature":1,"names":1}
,"logo":{"jetson":1,"embedded":1,"trademarks":1}
,"model":{"number":1,"numbers":1}
,"p2597":{"i.t.e":1}
,"i.t.e":{"e204896":1,"equipment":1}
,"e204896":{"recognized":1}
,"recognized":{"component":1}
,"p2180":{"jetson":1}
,"industry":{"canada":1,"canada\u2019s":1}
,"(ic)":{"jetson":1}
,"7361a-p2180":{"jetson":1}
,"7361a-p3310":{"ices-3":1}
,"ices-3":{"(b)\u002Fnmb-3":1}
,"(b)\u002Fnmb-3":{"(b)":1}
,"(b)":{"device":1}
,"canada\u2019s":{"license-exempt":1}
,"license-exempt":{"rsss":1}
,"rsss":{"operation":1}
,"band":{"5150":1,"eirp":1,"restricted":1}
,"5150":{"5250":1,"-5350":1}
,"5250":{"mhz":1}
,"mhz":{"indoor":1,"5650-5850":1,"radars":1,"sont":1,"650":1,"ces":1,"(bluetooth)":1,"100":1,"200":1,"warning":1,"frequency":1}
,"indoor":{"reduce":1,"equipment":1}
,"reduce":{"potential":1}
,"potential":{"harmful":1}
,"co-channel":{"mobile":1}
,"mobile":{"satellite":1}
,"satellite":{"systems":1}
,"note":{"high-power":1,"referenced":1,"indicates":1,"\uFF1A-\uFF1A":1}
,"high-power":{"radars":1}
,"radars":{"allocated":1,"cause":1,"haute":1,"pourraient":1}
,"allocated":{"primary":1}
,"users":{"(i.e":1}
,"(i.e":{"priority":1}
,"priority":{"users)":1}
,"users)":{"bands":1}
,"bands":{"5250-5350":1,"maximum":1}
,"5250-5350":{"mhz":1}
,"5650-5850":{"mhz":1}
,"and\u002For":{"damage":1,"registered":1}
,"damage":{"le-lan":1}
,"le-lan":{"devices":1}
,"devices":{"pr\u00E9sent":1,"operate":1,"systems":1}
,"pr\u00E9sent":{"appareil":1}
,"appareil":{"est":1,"remarque":1,"des":1}
,"est":{"conforme":1,"autoris\u00E9e":1,"susceptible":1}
,"conforme":{"aux":1}
,"aux":{"cnr":1,"appareils":1,"deux":1,"syst\u00E8mes":1,"dispositifs":1,"radiations":1,"normes":1,"exigences":1}
,"cnr":{"d\u2019industrie":1}
,"d\u2019industrie":{"canada":1}
,"applicables":{"aux":1}
,"appareils":{"radio":1}
,"exempts":{"licence":1}
,"licence":{"l\u2019exploitation":1}
,"l\u2019exploitation":{"est":1}
,"autoris\u00E9e":{"aux":1}
,"deux":{"conditions":1}
,"suivantes":{"l\u2019appareil":1}
,"l\u2019appareil":{"doit":1}
,"doit":{"pas":1,"accepter":1,"\u00EAtre":1}
,"pas":{"produire":1,"compatibilite":1}
,"produire":{"brouillage":1}
,"brouillage":{"l\u2019appareil":1,"radio\u00E9lectrique":1,"est":1,"pr\u00E9judiciable":1,"et\u002Fou":1}
,"accepter":{"tout":1}
,"tout":{"brouillage":1}
,"radio\u00E9lectrique":{"subi":1}
,"subi":{"m\u00EAme":1}
,"m\u00EAme":{"brouillage":1,"type":1}
,"susceptible":{"d\u2019en":1}
,"d\u2019en":{"compromettre":1}
,"compromettre":{"fonctionnement":1}
,"fonctionnement":{"les":1,"l\u0027appareil":1}
,"les":{"dispositifs":1,"risques":1,"m\u00EAmes":1,"antennes":1,"utilisateurs":1,"accessoires":1,"normes":1}
,"dispositifs":{"fonctionnant":1,"rl-el":1}
,"fonctionnant":{"dans":1}
,"dans":{"bande":1}
,"bande":{"150":1}
,"150":{"250":1}
,"250":{"mhz":1,"350":1}
,"sont":{"r\u00E9serv\u00E9s":1,"d\u00E9sign\u00E9s":1}
,"r\u00E9serv\u00E9s":{"uniquement":1}
,"uniquement":{"pour":1}
,"pour":{"une":1,"environement":1,"satisfaire":1}
,"une":{"utilisation":1,"distance":1}
,"utilisation":{"l\u2019int\u00E9rieur":1}
,"l\u2019int\u00E9rieur":{"afin":1}
,"afin":{"r\u00E9duire":1}
,"r\u00E9duire":{"les":1}
,"risques":{"brouillage":1}
,"pr\u00E9judiciable":{"aux":1}
,"syst\u00E8mes":{"satellites":1}
,"satellites":{"mobiles":1}
,"mobiles":{"utilisant":1}
,"utilisant":{"les":1}
,"m\u00EAmes":{"canaux4":1}
,"canaux4":{"seules":1}
,"seules":{"les":1}
,"antennes":{"m\u00EAme":1}
,"moindre":{"\u002F\u00E9gal":1}
,"\u002F\u00E9gal":{"d\u00E9pos\u00E9":1}
,"d\u00E9pos\u00E9":{"sous":1}
,"sous":{"num\u00E9ro":1}
,"num\u00E9ro":{"d\u0027identification":1}
,"d\u0027identification":{"peuvent":1}
,"peuvent":{"\u00EAtre":1}
,"\u00EAtre":{"utilis\u00E9es":1,"maintenue":1}
,"utilis\u00E9es":{"avec":1}
,"avec":{"cet":1,"les":1}
,"cet":{"appareil":1}
,"remarque":{"les":1}
,"utilisateurs":{"radars":1,"principaux":1}
,"haute":{"puissance":1}
,"puissance":{"sont":1}
,"d\u00E9sign\u00E9s":{"utilisateurs":1}
,"principaux":{"(c.-\u00E0-d":1}
,"(c.-\u00E0-d":{"qu\u0027ils":1}
,"qu\u0027ils":{"ont":1}
,"ont":{"priorit\u00E9)":1}
,"priorit\u00E9)":{"des":1}
,"des":{"bandes":1,"dommages":1,"personnes":1}
,"bandes":{"250":1}
,"350":{"mhz":1}
,"650":{"850":1}
,"850":{"mhz":1}
,"ces":{"radars":1}
,"pourraient":{"causer":1}
,"causer":{"brouillage":1}
,"et\u002Fou":{"des":1}
,"dommages":{"aux":1}
,"rl-el":{"radiation":1}
,"dev":{"kit":1}
,"ised":{"rss":1}
,"rss":{"102":1,"102rf":1}
,"102":{"radiation":1,"pour":1,"european":1}
,"accessories":{"supplied":1,"may":1}
,"designated":{"product":1}
,"satisfy":{"exposure":1}
,"maintained":{"antenna":1}
,"persons":{"during":1}
,"102rf":{"exposure":1}
,"guidelines":{"d\u00E9claration":1}
,"d\u00E9claration":{"d\u0027exposition":1}
,"d\u0027exposition":{"aux":1,"une":1}
,"radiations":{"jetson":1}
,"ete":{"testee":1}
,"testee":{"conformemment":1}
,"conformemment":{"aux":1}
,"normes":{"d\u2019exposition":1,"d\u2019emission":1}
,"d\u2019exposition":{"d\u2019emission":1}
,"d\u2019emission":{"ised":1,"rss":1}
,"environement":{"non":1}
,"non":{"controle":1}
,"controle":{"lors":1}
,"lors":{"d\u2019utilisation":1}
,"d\u2019utilisation":{"avec":1}
,"accessoires":{"fournis":1}
,"fournis":{"recommendes":1}
,"recommendes":{"par":1}
,"par":{"nvidia":1}
,"satisfaire":{"aux":1}
,"exigences":{"d\u0027exposition":1}
,"s\u00E9paration":{"d\u0027au":1}
,"d\u0027au":{"moins":1}
,"moins":{"doit":1}
,"maintenue":{"entre":1}
,"entre":{"l\u0027antenne":1}
,"l\u0027antenne":{"cet":1}
,"personnes":{"pendant":1}
,"pendant":{"fonctionnement":1}
,"l\u0027appareil":{"l\u2019utilisation":1}
,"l\u2019utilisation":{"d\u2019accessoires":1}
,"d\u2019accessoires":{"autres":1}
,"autres":{"que":1}
,"que":{"ceux":1}
,"ceux":{"recommendes":1}
,"guarantis":{"pas":1}
,"compatibilite":{"avec":1}
,"conformity":{"conformit\u00E9":1,"available":1}
,"conformit\u00E9":{"europ\u00E9enne":1}
,"europ\u00E9enne":{"(ce)":1}
,"(ce)":{"device":1}
,"bears":{"mark":1}
,"mark":{"accordance":1,"logos":1}
,"directive":{"2014\u002F53\u002Feu":1,"2011.65.eu":1}
,"2014\u002F53\u002Feu":{"device":1,"rohs":1}
,"directives":{"radio":1}
,"2011.65.eu":{"full":1}
,"text":{"declaration":1}
,"copy":{"may":1}
,"obtained":{"directly":1}
,"gmbh":{"(floessergasse":1}
,"(floessergasse":{"81369":1}
,"81369":{"munich":1}
,"munich":{"germany)":1}
,"germany)":{"devices":1}
,"maximum":{"transmitted":1,"extent":1}
,"transmitted":{"power":1}
,"eirp":{"(dbm)":1,"(mw)":1}
,"(dbm)":{"eirp":1}
,"(mw)":{"2402":1}
,"2402":{"-2480":1}
,"-2480":{"mhz":1}
,"(bluetooth)":{"2412":1,"australia":1}
,"2412":{"-2472":1}
,"-2472":{"mhz":1}
,"100":{"5180":1}
,"5180":{"-5320":1}
,"-5320":{"mhz":1}
,"200":{"5500":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fsupport":1}
,"5500":{"-5700":1}
,"-5700":{"mhz":1}
,"5745":{"-5825":1}
,"-5825":{"mhz":1}
,"-5350":{"mhz":1}
,"restricted":{"indoor":1,"hazardous":1,"substances":1,"substance":1}
,"pulse":{"w1043":1}
,"w1043":{"antennas":1}
,"voids":{"user":1}
,"945-82371-0005-000":{"jetson":1}
,"945-82771-0005-000":{"firmware":1}
,"firmware":{"version":1}
,"7.35.221.11":{"(wlan)":1}
,"(wlan)":{"030a0525":1}
,"030a0525":{"(bluetooth)":1}
,"australian":{"communications":1}
,"media":{"authority":1}
,"meets":{"applicable":1}
,"applicable":{"emc":1,"radio":1}
,"emc":{"requirements":1}
,"voluntary":{"control":1}
,"control":{"council":1}
,"council":{"interference":1}
,"(vcci)":{"radio\u002Ftelecommunications":1}
,"radio\u002Ftelecommunications":{"certification":1}
,"certification":{"jetson":1}
,"research":{"agency":1}
,"agency":{"(rra)":1,"technology":1}
,"(rra)":{"korean":1}
,"korean":{"agency":1}
,"technology":{"standards":1}
,"standards":{"(kats)":1}
,"(kats)":{"jetson":1}
,"msip-crm-nva-p2180":{"msip-rmm-nva-p2597":1}
,"msip-rmm-nva-p2597":{"msip-crm-nva-p3310":1,"\uAE30\uAE30\uB294":1}
,"msip-crm-nva-p3310":{"msip-rmm-nva-p2597":1}
,"\uAE30\uAE30\uB294":{"\uAC00\uC815\uC6A9":1}
,"\uAC00\uC815\uC6A9":{"\uC804\uC790\uD30C\uC801\uD569\uAE30\uAE30\uB85C\uC11C":1,"\uD1B5\uC2E0\uAE30\uC790\uC7AC)":1}
,"\uC804\uC790\uD30C\uC801\uD569\uAE30\uAE30\uB85C\uC11C":{"\uAC00\uC815\uC6A9":1}
,"\uD1B5\uC2E0\uAE30\uC790\uC7AC)":{"\uAC00\uC815\uC5D0\uC11C":1}
,"\uAC00\uC815\uC5D0\uC11C":{"\uC0AC\uC6A9\uD558\uB294":1}
,"\uC0AC\uC6A9\uD558\uB294":{"\uBAA9\uC801\uC73C\uB85C":1}
,"\uBAA9\uC801\uC73C\uB85C":{"\uC9C0\uC5ED\uC5D0\uC11C":1}
,"\uC9C0\uC5ED\uC5D0\uC11C":{"\uC0AC\uC6A9\uD560":1}
,"\uC0AC\uC6A9\uD560":{"\uC788\uC2B5\uB2C8\uB2E4":1}
,"\uC788\uC2B5\uB2C8\uB2E4":{"taiwan":1}
,"national":{"communications":1}
,"ccaj15lp6160t6":{"ccaj17lp1260t1":1}
,"ccaj17lp1260t1":{"jetson":1}
,"(id)":{"jetson":1}
,"(ccaj15lp6160t6)":{"jetson":1}
,"(ccaj17lp1260t1)":{"jetson":1,"mpe":1}
,"mpe":{"1mw\u002Fcm":1}
,"1mw\u002Fcm":{".109":1}
,".109":{"mw\u002Fcm":1}
,"mw\u002Fcm":{"china":1}
,"committee":{"jetson":1}
,"cmiit":{"2015aj7078":1,"2015aj6648":1,"2017aj1049":1}
,"2015aj7078":{"cmiit":1}
,"2015aj6648":{"(m)":1}
,"(m)":{"jetson":1,"singapore":1}
,"2017aj1049":{"(m)":1}
,"info-communications":{"development":1}
,"california":{"prop":1,"law":1,"customers":1,"cause":1}
,"prop":{"warning":1}
,"law":{"requires":1,"information":1}
,"customers":{"prop":1}
,"contains":{"chemicals":1}
,"chemicals":{"known":1}
,"known":{"state":1}
,"cancer":{"birth":1}
,"birth":{"defects":1}
,"defects":{"reproductive":1}
,"reproductive":{"harm":1}
,"harm":{"jetson":1}
,"hazardous":{"substances":1,"substance":1}
,"substances":{"content":1,"electrical":1,"(pb)":1,"marking":1,"chemical":1}
,"management":{"methods":1}
,"methods":{"restricted":1}
,"electronic":{"products":1}
,"products":{"parts":1,"authorized":1}
,"parts":{"hazardous":1,"named":1,"restricted":1}
,"(pb)":{"(hg)":1}
,"(hg)":{"(cd)":1}
,"(cd)":{"(cr":1}
,"(cr":{"(vi))":1}
,"(vi))":{"(pbb)":1}
,"(pbb)":{"(pbde)":1}
,"(pbde)":{"pca":1}
,"pca":{"processor":1}
,"processor":{"system":1}
,"supply":{"camera":1}
,"camera":{"module":1}
,"mechanicals":{"\u6750\u002F\u8FDE":1,"\u6750\u002F\u9023":1}
,"\u6750\u002F\u8FDE":{"cables\u002Fconnectors":1}
,"cables\u002Fconnectors":{"soldering":1}
,"soldering":{"material":1}
,"flux":{"solder":1}
,"solder":{"paste":1}
,"paste":{"label":1}
,"label":{"consumable":1}
,"consumable":{"materials":1}
,"materials":{"sj\u002Ft":1,"part":1,"used":1,"note":1,"provided":1,"express":1}
,"sj\u002Ft":{"11364-2014":1}
,"11364-2014":{"table":1,"gb\u002Ft":1}
,"according":{"sj\u002Ft":1,"normal":1}
,"gb\u002Ft":{"26572-2011":1}
,"26572-2011":{"indicates":1,"gb\u002Ft":1,"rohs":1}
,"substance":{"contained":1,"exceed":1,"corresponds":1}
,"contained":{"homogeneous":1,"least":1}
,"homogeneous":{"materials":1}
,"below":{"limit":1}
,"limit":{"requirement":1}
,"requirement":{"gb\u002Ft":1}
,"named":{"table":1}
,"union\u2019s":{"rohs":1}
,"legislation":{"note":1,"jetson":1}
,"referenced":{"environmental":1}
,"period":{"marking":1}
,"marking":{"determined":1,"jetson":1}
,"normal":{"operating":1}
,"temperature":{"humidity":1}
,"humidity":{"jetson":1,"www.nvidia.com":1}
,"presence":{"condition":1,"note":1}
,"condition":{"restricted":1,"title":1}
,"chemical":{"symbols":1}
,"symbols":{"(pb":1}
,"(pb":{"(hg)":1}
,"\u6750\u002F\u9023":{"cables\u002Fconnectors":1}
,"percentage":{"content":1,"reference":1}
,"exceed":{"percentage":1}
,"reference":{"value":1,"boards":1}
,"\uFF1A-\uFF1A":{"indicates":1}
,"corresponds":{"exemption":1}
,"exemption":{"\u201C-\u201D":1}
,"\u201C-\u201D":{"rohs":1,"compliance":1}
,"www.nvidia.com":{"notice":1}
,"notice":{"2017":1,"publication":1}
,"2017":{"nvidia":1}
,"trademarks":{"and\u002For":1,"nvidia":1,"respective":1,"registered":1,"owned":1}
,"registered":{"trademarks":1}
,"u.s":{"countries":1}
,"countries":{"company":1}
,"company":{"product":1}
,"names":{"may":1}
,"respective":{"companies":1}
,"companies":{"associated":1}
,"associated":{"2015":1,"nvidia":1,"bluetooth":1}
,"2015":{"nvidia":1}
,"design":{"specifications":1}
,"specifications":{"reference":1,"mentioned":1}
,"boards":{"files":1}
,"drawings":{"diagnostics":1}
,"diagnostics":{"lists":1}
,"lists":{"documents":1}
,"documents":{"(together":1}
,"(together":{"separately":1}
,"separately":{"materials":1}
,"warranties":{"express":1,"including":1}
,"express":{"implied":1,"written":1}
,"implied":{"statutory":1,"conditions":1,"warranty":1}
,"statutory":{"otherwise":1}
,"otherwise":{"respect":1,"patent":1}
,"respect":{"materials":1}
,"representations":{"warranties":1}
,"warranty":{"condition":1}
,"title":{"merchantability":1}
,"merchantability":{"satisfactory":1}
,"satisfactory":{"quality":1}
,"quality":{"fitness":1}
,"fitness":{"particular":1}
,"purpose":{"on-infringement":1}
,"on-infringement":{"hereby":1}
,"hereby":{"excluded":1}
,"excluded":{"maximum":1}
,"extent":{"permitted":1}
,"permitted":{"law":1}
,"furnished":{"believed":1}
,"believed":{"accurate":1}
,"accurate":{"reliable":1}
,"reliable":{"however":1}
,"assumes":{"responsibility":1}
,"responsibility":{"consequences":1}
,"consequences":{"information":1}
,"infringement":{"patents":1}
,"patents":{"third":1}
,"third":{"parties":1}
,"parties":{"may":1}
,"granted":{"implication":1}
,"implication":{"otherwise":1}
,"patent":{"patent":1,"nvidia":1}
,"mentioned":{"publication":1}
,"publication":{"subject":1,"supersedes":1}
,"change":{"without":1}
,"without":{"notice":1,"express":1}
,"supersedes":{"replaces":1}
,"replaces":{"information":1}
,"previously":{"supplied":1}
,"authorized":{"critical":1}
,"critical":{"components":1}
,"life":{"support":1}
,"written":{"approval":1}
,"approval":{"nvidia":1}
,"bluetooth":{"word":1,"sig":1}
,"word":{"mark":1}
,"logos":{"registered":1}
,"owned":{"bluetooth":1}
,"sig":{"marks":1}
}
;Search.control.loadWordPairs(pairs);
