var pairs =
{
"jetson":{"tx1":1,"module":1,"tx2":1}
,"tx1":{"tx2":1,"available":1,"powermon":1,"module":1,"developer":1}
,"tx2":{"voltage":1,"module":1,"available":1,"developer":1}
,"voltage":{"current":1,"comparator":1,"critical":1,"system":1,"example":1,"unless":1,"www.nvidia.com":1}
,"current":{"monitor":1,"load":1,"following":1,"limits":1,"limit":1,"lower":1}
,"monitor":{"configuration":1,"nvidia":1,"detect":1,"ina3221":1,"voltage":1,"power":1,"accepts":1,"jetson":1,"configured":1}
,"configuration":{"da_08564_001":1,"jetson":1,"application":1,"data":1}
,"da_08564_001":{"march":1,"document":1,"version":1,"voltage":1,"kernel\u002Farch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-platforms\u002Ftegra210-jetson-cv-powermon-p2180-1000-a00.dtsi":1,"current-critical-limit-ma":1}
,"march":{"2018":1}
,"2018":{"application":1,"hlang":1}
,"application":{"note":1}
,"note":{"release":1,"da_08564_001":1}
,"release":{"28.2":1,"v1.1":1,"date":1,"jetson":1}
,"28.2":{"jetson":1,"release":1}
,"document":{"change":1}
,"change":{"history":1,"v1.0":1,"without":1}
,"history":{"da_08564_001":1}
,"version":{"date":1}
,"date":{"authors":1,"28.2":1}
,"authors":{"description":1}
,"description":{"change":1}
,"v1.0":{"may":1}
,"may":{"2017":1,"occur":1,"result":1,"trademarks":1}
,"2017":{"rajkumar\u002Fhlang":1}
,"rajkumar\u002Fhlang":{"initial":1,"update":1}
,"initial":{"release":1}
,"v1.1":{"jun":1}
,"jun":{"2017":1}
,"update":{"hardware":1}
,"hardware":{"throttling":1,"implement":1,"quickly":1,"reacts":1}
,"throttling":{"vdd_in":1,"performance":1}
,"vdd_in":{"interrupt":1,"vdd_gpu":1,"shunt-resistor-mohm":1,"calculated":1,"=40,000":1,"unexpected":1,"maximum":1}
,"interrupt":{"28.1":1}
,"28.1":{"v1.2":1}
,"v1.2":{"feb":1}
,"feb":{"2018":1}
,"hlang":{"updates":1}
,"updates":{"last":1}
,"last":{"release":1}
,"nvidia":{"tegra":1,"tegra124-sysedp":1,"margin":1,"min_budget":1,"initial_budget":1,"design":1,"makes":1,"assumes":1,"specifications":1,"products":1,"trademarks":1,"nvidia":1,"logo":1,"united":1}
,"tegra":{"board":1,"hardware":1,"alert":1,"power":1}
,"board":{"support":1}
,"support":{"package":1,"devices":1}
,"package":{"jetson":1}
,"module":{"works":1,"includes":1,"input":1,"part":1}
,"works":{"together":1}
,"together":{"platform":1}
,"platform":{"hardware":1,"voltage":1}
,"implement":{"system":1}
,"system":{"electrical":1,"edp":1,"integrator":1}
,"electrical":{"design":1}
,"design":{"point":1,"specifications":1}
,"point":{"(edp)":1}
,"(edp)":{"management":1}
,"management":{"strategy":1}
,"strategy":{"maximize":1}
,"maximize":{"cpu":1}
,"cpu":{"gpu":1}
,"gpu":{"performance":1,"clocks":1}
,"performance":{"within":1,"slowdown":1}
,"within":{"system":1}
,"edp":{"constraints":1,"limit":1}
,"constraints":{"platform":1}
,"comparator":{"current":1}
,"detect":{"under-voltage":1}
,"under-voltage":{"over-current":1}
,"over-current":{"scenarios":1}
,"scenarios":{"outlined":1}
,"outlined":{"sensor":1}
,"sensor":{"outputs":1}
,"outputs":{"asserted":1,"ina3221":1}
,"asserted":{"tegra":1,"soc_therm":1}
,"quickly":{"throttles":1}
,"throttles":{"cpu":1}
,"clocks":{"configured":1}
,"configured":{"software":1,"19v":1}
,"software":{"reduce":1}
,"reduce":{"current":1,"tegra":1}
,"load":{"jetson":1}
,"includes":{"on-board":1}
,"on-board":{"power":1}
,"power":{"monitor":1,"rails":1,"consumption":1}
,"ina3221":{"monitor":1,"include":1}
,"following":{"power":1,"code":1}
,"rails":{"vdd_in":1}
,"vdd_gpu":{"vdd_gpu":1,"alert":1,"shunt-resistor-mohm":1}
,"alert":{"outputs":1,"crit":1}
,"include":{"alert":1}
,"crit":{"warn":1}
,"warn":{"fed":1}
,"fed":{"soc_therm":1}
,"soc_therm":{"input":1,"hardware":1}
,"input":{"tegra":1,"voltage":1,"less":1,"used":1}
,"reacts":{"reduce":1}
,"consumption":{"avoid":1}
,"avoid":{"violating":1}
,"violating":{"current":1}
,"limits":{"configuring":1}
,"configuring":{"voltage":1}
,"accepts":{"configuration":1}
,"data":{"powermon":1}
,"powermon":{"device":1,"dtsi":1}
,"device":{"tree":1}
,"tree":{"source":1}
,"source":{"file":1}
,"file":{"powermon":1,"jetson":1,"i2c@7000c400":1}
,"dtsi":{"file":1}
,"available":{"voltage":1,"hardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fcommon\u002Fkernel-dts\u002Ft18x-common-platforms\u002Ftegra186-quill-p3310-1000-a00-powermon.dtsi":1}
,"kernel\u002Farch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-platforms\u002Ftegra210-jetson-cv-powermon-p2180-1000-a00.dtsi":{"powermon":1}
,"hardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fcommon\u002Fkernel-dts\u002Ft18x-common-platforms\u002Ftegra186-quill-p3310-1000-a00-powermon.dtsi":{"following":1}
,"code":{"snippet":1,"follows":1}
,"snippet":{"tx1":1}
,"i2c@7000c400":{"{ina3221x":1}
,"{ina3221x":{"ina3221x@40":1}
,"ina3221x@40":{"{compatible":1}
,"{compatible":{"ina3221x":1,"nvidia":1}
,"ina3221x":{"reg":1}
,"reg":{"=<0x40>":1}
,"=<0x40>":{"trigger-config":1}
,"trigger-config":{"=<0x7003>":1}
,"=<0x7003>":{"continuous-config":1}
,"continuous-config":{"=<0x7607>":1}
,"=<0x7607>":{"enable-forced-continuous":1}
,"enable-forced-continuous":{"io-channel-cells":1}
,"io-channel-cells":{"=<1>":1}
,"=<1>":{"address-cells":1,"size-cells":1}
,"address-cells":{"=<1>":1}
,"size-cells":{"=<0>":1}
,"=<0>":{"status":1,"nvidia":1}
,"status":{"disabled":1}
,"disabled":{"channel@0":1}
,"channel@0":{"{reg":1}
,"{reg":{"=<0x0>":1,"=<0x1>":1,"=<0x2>":1}
,"=<0x0>":{"rail-name":1}
,"rail-name":{"vdd_in":1,"vdd_gpu":1,"vdd_cpu":1}
,"shunt-resistor-mohm":{"=<20>":1,"=<10>":1}
,"=<20>":{"current-critical-limit-ma":1}
,"current-critical-limit-ma":{"=<2105>":1,"channel":1}
,"=<2105>":{"shunt-volt-offset-uv":1}
,"shunt-volt-offset-uv":{"=<&p2180_shuntv_offset>":1}
,"=<&p2180_shuntv_offset>":{"channel@1":1,"channel@2":1,"voltage":1}
,"channel@1":{"{reg":1}
,"=<0x1>":{"rail-name":1}
,"=<10>":{"shunt-volt-offset-uv":1}
,"channel@2":{"{reg":1}
,"=<0x2>":{"rail-name":1}
,"vdd_cpu":{"shunt-resistor-mohm":1}
,"channel":{"vdd_in":1}
,"calculated":{"system":1,"follows":1}
,"limit":{"jetson":1,"=system":1,"\u002Fvdd_in":1,"19v":1,"based":1,"vdd_in":1,"specific":1}
,"critical":{"current":1,"components":1}
,"=system":{"edp":1}
,"\u002Fvdd_in":{"voltage":1}
,"part":{"jetson":1}
,"developer":{"kit":1}
,"kit":{"defined":1,"voltage":1,"critical":1}
,"defined":{"kernel\u002Farch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-jetson-cv-base-p2597-2180-a00.dts":1}
,"kernel\u002Farch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-jetson-cv-base-p2597-2180-a00.dts":{"code":1}
,"follows":{"sysedp":1,"19v":1,"critical":1}
,"sysedp":{"{compatible":1}
,"tegra124-sysedp":{"nvidia":1}
,"margin":{"=<0>":1}
,"min_budget":{"=<0>":1}
,"initial_budget":{"=<40000>":1}
,"=<40000>":{"critical":1}
,"19v":{"vdd_in":1,"input":1}
,"=40,000":{"\u002F19":1,"5000ma":1}
,"\u002F19":{"2105ma":1}
,"2105ma":{"system":1}
,"integrator":{"configure":1}
,"configure":{"correct":1,"critical":1}
,"correct":{"critical":1}
,"based":{"module":1}
,"example":{"critical":1}
,"5000ma":{"default":1}
,"default":{"jetson":1}
,"less":{"19v":1}
,"used":{"user":1}
,"user":{"reconfigure":1,"wants":1}
,"reconfigure":{"critical":1}
,"unexpected":{"cpu\u002Fgpu":1}
,"cpu\u002Fgpu":{"throttling":1}
,"slowdown":{"may":1}
,"occur":{"default":1}
,"maximum":{"possible":1,"extent":1}
,"possible":{"value":1}
,"value":{"8190ma":1}
,"8190ma":{"therefore":1}
,"therefore":{"necessary":1}
,"necessary":{"modify":1}
,"modify":{"critical":1}
,"lower":{"input":1}
,"unless":{"user":1}
,"wants":{"configure":1}
,"specific":{"input":1}
,"www.nvidia.com":{"notice":1}
,"notice":{"nvidia":1,"publication":1}
,"specifications":{"reference":1,"mentioned":1}
,"reference":{"boards":1}
,"boards":{"files":1}
,"files":{"drawings":1}
,"drawings":{"diagnostics":1}
,"diagnostics":{"lists":1}
,"lists":{"documents":1}
,"documents":{"(together":1}
,"(together":{"separately":1}
,"separately":{"materials":1}
,"materials":{"provided":1,"express":1}
,"provided":{"nvidia":1}
,"makes":{"warranties":1}
,"warranties":{"express":1,"including":1}
,"express":{"implied":1,"written":1}
,"implied":{"statutory":1,"conditions":1,"warranty":1}
,"statutory":{"otherwise":1}
,"otherwise":{"respect":1,"patent":1}
,"respect":{"materials":1}
,"conditions":{"representations":1}
,"representations":{"warranties":1}
,"including":{"implied":1}
,"warranty":{"condition":1}
,"condition":{"title":1}
,"title":{"merchantability":1}
,"merchantability":{"satisfactory":1}
,"satisfactory":{"quality":1}
,"quality":{"fitness":1}
,"fitness":{"particular":1}
,"particular":{"purpose":1}
,"purpose":{"on-infringement":1}
,"on-infringement":{"hereby":1}
,"hereby":{"excluded":1}
,"excluded":{"maximum":1}
,"extent":{"permitted":1}
,"permitted":{"law":1}
,"law":{"information":1}
,"information":{"furnished":1,"infringement":1,"previously":1}
,"furnished":{"believed":1}
,"believed":{"accurate":1}
,"accurate":{"reliable":1}
,"reliable":{"however":1}
,"however":{"nvidia":1}
,"assumes":{"responsibility":1}
,"responsibility":{"consequences":1}
,"consequences":{"information":1}
,"infringement":{"patents":1}
,"patents":{"third":1}
,"third":{"parties":1}
,"parties":{"may":1}
,"result":{"license":1}
,"license":{"granted":1}
,"granted":{"implication":1}
,"implication":{"otherwise":1}
,"patent":{"patent":1,"nvidia":1}
,"mentioned":{"publication":1}
,"publication":{"subject":1,"supersedes":1}
,"subject":{"change":1}
,"without":{"notice":1,"express":1}
,"supersedes":{"replaces":1}
,"replaces":{"information":1}
,"previously":{"supplied":1}
,"supplied":{"nvidia":1}
,"products":{"authorized":1}
,"authorized":{"critical":1}
,"components":{"life":1}
,"life":{"support":1}
,"devices":{"systems":1}
,"systems":{"without":1}
,"written":{"approval":1}
,"approval":{"nvidia":1}
,"trademarks":{"nvidia":1,"registered":1,"respective":1}
,"logo":{"trademarks":1}
,"registered":{"trademarks":1}
,"united":{"states":1}
,"states":{"countries":1}
,"countries":{"company":1}
,"company":{"product":1}
,"product":{"names":1}
,"names":{"may":1}
,"respective":{"companies":1}
,"companies":{"associated":1}
,"associated":{"2014":1}
,"2014":{"nvidia":1}
}
;Search.control.loadWordPairs(pairs);
