var pairs =
{
"platform":{"adaptation":1,"configuration":1,"example":1,"supported":1,"modify":1,"hardware":1}
,"adaptation":{"bring-up":1}
,"bring-up":{"guide":1,"checklist":1,"hardware":1,"process":1}
,"guide":{"da_08477-001":1,"platform":1,"board":1,"document":1,"mb1":1,"display":1,"external":1,"available":1,"adjust":1,"details":1}
,"da_08477-001":{"march":1,"document":1,"version":1,"iii":1,"nvidia":1,"platform":1,"jetson-tx2":1,"mb1":1,"tegra":1,"porting":1,"port":1,"power":1,"usb":1,"compatibility":1,"lane":1,"power-on":1,"verify":1,"imager":1,"uart":1}
,"march":{"2018":1}
,"2018":{"tegra":1,"dliu\u002Fkstone":1}
,"tegra":{"linux":1,"gpio":1,"device":1,"soc":1,"lanes":1,"data":1,"usb":1,"hdmi":1,"tx\u002Frx\u002Fcts\u002Frts":1,"pins":1,"dsi":1,"jetson":1}
,"linux":{"driver":1,"kernel":1}
,"driver":{"package":1,"example":1,"enumeration":1,"connector\u002Ftest":1,"possible":1}
,"package":{"jetson":1,"u-boot":1,"development":1,"platform":1}
,"jetson":{"tx2":1,"p2597":1,"tx1":1,"trademarks":1}
,"tx2":{"platform":1,"v1.1":1,"developer":1,"module":1,"users":1,"pin":1,"usb":1,"depending":1,"designed":1,"configuration":1,"oem":1,"consulting":1,"lane":1,"connected":1}
,"document":{"change":1,"describes":1,"<board>":1,"<vendor>":1,"substitute":1}
,"change":{"history":1,"v1.0":1,"pinmux":1,"following":1,"supply":1,"lane":1,"usb":1,"without":1}
,"history":{"da_08477-001":1}
,"version":{"date":1,"number":1}
,"date":{"authors":1}
,"authors":{"description":1}
,"description":{"change":1}
,"v1.0":{"mar":1}
,"mar":{"2017":1}
,"2017":{"twarren\u002Fbbasu\u002Fsnath":1,"bbasu":1,"jerchang\u002Fmzensius":1}
,"twarren\u002Fbbasu\u002Fsnath":{"initial":1}
,"initial":{"release":1,"power-on":1,"software":1,"pmic":1}
,"release":{"jetson":1}
,"v1.1":{"mar":1}
,"bbasu":{"added":1,"board":1}
,"added":{"power":1}
,"power":{"tree":1,"power":1,"optimization":1,"clocks":1,"supply":1,"supplies":1,"turned":1,"verify":1,"rail":1,"mode":1,"system":1,"state":1,"reset":1,"lp0":1,"down":1}
,"tree":{"changes":1,"settings":1,"filenames":1,"spreadsheet":1,"schema":1,"properties":1,"modify":1,"mb1":1,"verify":1,"review":1}
,"changes":{"v1.2":1,"pinmux":1,"gpio":1,"pmic":1,"porting":1,"usb":1,"flashing":1,"mb1":1,"board":1,"designed":1,"include":1,"dtsi":1,"tegra186-quill-power-tree-p3310-1000-a00-00.dtsi":1,"tegra186-quill-spmic-p3310-1000-a00-00.dtsi":1,"refer":1,"best":1,"taken":1,"jetson":1,"following":1,"required":1}
,"v1.2":{"may":1}
,"may":{"2017":1,"power-tree":1,"need":1,"modified":1,"support":1,"result":1,"trademarks":1}
,"board":{"configuration":1,"naming":1,"sits":1,"complete":1,"used":1,"boards":1,"saved":1,"verify":1,"custom":1,"eeprom":1,"required":1,"l4t":1,"name":1,"board":1,"placeholders":1,"version":1,"<root>":1,"schematic":1,"change":1,"gpio":1,"translate":1,"configurations":1,"additionally":1,"copy":1,"example":1,"may":1,"edit":1,"note":1,"vdd_usb2_5v":1,"unused":1,"lane":1,"range":1,"power-on":1,"schematics":1,"review":1,"pinmux":1,"config\u002Fpmic":1}
,"configuration":{"updates":1,"board":1,"changes":1,"files":1,"configuring":1,"jetson":1,"modifications":1,"odm":1,"hardware":1,"tables":1,"applied":1,"file":1,"code":1,"bringup":1,"tegra186-odm-data-plugin-manager.dtsi":1,"update":1,"validated":1,"-odmdata=0x90000":1,"-odmdata=0x6090000":1,"cell":1,"pins":1,"available":1,"present":1,"replaced":1,"accordingly":1}
,"updates":{"v1.3":1,"v1.4":1}
,"v1.3":{"jun":1}
,"jun":{"2017":1}
,"jerchang\u002Fmzensius":{"gpio-related":1}
,"gpio-related":{"updates":1}
,"v1.4":{"jan":1}
,"jan":{"2018":1}
,"dliu\u002Fkstone":{"device":1}
,"device":{"tree":1,"tables":1,"holds":1,"registers":1,"tegra-gpio":1,"tegra-gpio-aon":1,"tree)":1,"connected":1,"mode":1,"rx\u002Ftx\u002Frts\u002Fcts":1,"similar":1,"look":1}
,"settings":{"qspi_io2":1,"define":1,"source":1,"p2597":1,"until":1}
,"qspi_io2":{"platform":1,"configured":1,"follows":1}
,"iii":{"table":1}
,"table":{"contents":1,"however":1,"ethernet":1,"cpu\u002Fcore":1}
,"contents":{"platform":1}
,"naming":{"placeholders":1,"support":1,"convention":1}
,"placeholders":{"porting":1,"used":1}
,"porting":{"instructions":1,"u-boot":1,"linux":1}
,"instructions":{"mb1":1,"placeholders":1}
,"mb1":{"configuration":1,"platform":1,"provides":1,"boot":1,"bct":1,"pmic":1,"pinmux":1}
,"pinmux":{"changes":1,"gpio":1,"sdmmc-drv":1,"configuration":1,"settings":1,"node":1,"spreadsheet":1,"modify":1,"pad":1}
,"gpio":{"changes":1,"pad":1,"numbers":1,"mapping":1,"number":1,"group":1,"allocation":1,"ports":1,"expander-based":1,"regulator":1,"irq":1,"expander":1,"information":1,"wake":1}
,"pmic":{"changes":1,"configuration":1,"p3310":1,"programming":1,"ddr":1,"pinmux":1}
,"u-boot":{"porting":1,"port":1,"bootloader":1,"linux":1,"command":1,"perform":1,"source":1,"rather":1,"run":1,"boot":1}
,"kernel":{"power":1,"peripherals":1,"device":1,"source":1,"proc":1,"messages":1,"always":1,"add":1,"assumed":1,"configuration":1,"phy-names":1,"boot":1,"command":1}
,"usb":{"lane":1,"2.0":1,"3.0":1,"type":1,"configuration":1,"phy":1,"recovery":1,"phys":1,"signals":1,"tuning":1,"card":1}
,"lane":{"mapping":1,"configuration":1,"sharing":1,"pex_rfu":1,"pex2":1,"usb_ss1":1,"pex0":1,"usb_ss0":1,"tegra":1,"allocation":1,"example":1,"usb3-0":1,"allocations":1}
,"mapping":{"required":1,"formula":1,"usb":1,"platform":1}
,"required":{"device":1,"board":1,"include":1,"porting":1,"xhci":1,"example":1,"usb2.0":1,"power-on":1,"rails":1}
,"flashing":{"build":1,"power":1,"de-configure":1,"jetson":1,"script":1,"process":1,"verify":1}
,"build":{"image":1}
,"image":{"hardware":1,"flashing":1,"specific":1,"execute":1}
,"hardware":{"bring-up":1,"validation":1,"platforms":1,"applied":1,"design":1,"control":1}
,"checklist":{"power-on":1,"preparation":1,"section":1,"platform":1,"software":1}
,"power-on":{"initial":1,"sure":1,"verify":1,"enabled":1,"sequence":1}
,"software":{"flashing":1,"bring-up":1,"configuration":1,"programming":1,"jetson-tx2-generic-customer-pinmux-template.xlsm":1,"may":1,"supports":1}
,"optimization":{"usb":1,"capture":1}
,"2.0":{"phy":1,"(dp":1,"compatibility":1,"usb":1}
,"phy":{"usb":1,"lane5":1,"lane4":1,"lane2":1,"lane1":1,"lane0":1,"verify":1}
,"3.0":{"hdmi":1,"super-speed":1,"follows":1,"pcie":1,"port":1,"sata":1,"ports":1,"lines":1,"verify":1,"host":1,"device":1,"interface":1}
,"hdmi":{"audio":1,"verify":1,"reads":1,"related":1,"signals":1,"tuning":1}
,"audio":{"uart":1,"verify":1,"codec":1}
,"uart":{"card":1,"verify":1,"used":1,"output":1}
,"card":{"(sdmmc1)":1,"insertion":1,"write":1,"low":1,"thermal":1}
,"(sdmmc1)":{"sensors":1,"verify":1}
,"sensors":{"i2c":1}
,"i2c":{"general":1,"touch":1,"controller":1,"type":1,"interface":1,"devices":1,"spi":1,"control":1}
,"general":{"sensors":1,"verify":1}
,"touch":{"screen":1}
,"screen":{"(optional)":1,"controller":1,"verify":1}
,"(optional)":{"pex":1,"sata":1,"embedded":1,"imager":1,"software":1,"verify":1,"cpu":1}
,"pex":{"(optional)":1,"interfaces":1}
,"sata":{"(optional)":1,"xusb":1,"lane":1,"1x1":1,"2*1":1,"3x1":1,"2x1":1,"*default":1,"**notes":1,"interfaces":1,"pcie":1}
,"embedded":{"display":1,"display\u2019s":1}
,"display":{"(s)":1,"panel":1,"configuration":1,"works":1,"detected":1,"using":1,"verify":1,"shows":1,"mode":1,"(and":1,"bridge)":1,"meets":1}
,"(s)":{"(optional)":1}
,"imager":{"(s)":1,"module":1}
,"preparation":{"bring-up":1,"replaced":1}
,"validation":{"u-boot":1,"kernel":1,"system":1,"power":1,"tegraflash":1,"device":1}
,"port":{"boot":1,"validation":1,"nvidia":1,"number":1,"*8)":1,"kernel":1,"usb_ss0":1,"xhci":1,"case":1}
,"boot":{"validation":1,"time":1,"configuration":1,"scripts":1,"u-boot":1,"kernel":1}
,"peripherals":{"port":1,"consequently":1,"present":1}
,"system":{"power":1,"platform":1,"solve":1,"enter":1,"flashed":1,"low":1,"deep":1,"enters":1,"supported":1,"state":1,"edp":1}
,"clocks":{"platform":1,"cpu\u002Fcore\u002Fgpu":1}
,"nvidia":{"confidential":1,"tegra":1,"jetson":1,"document":1,"<board>":1,"reference":1,"p2771-0000":1,"modified":1,"released":1,"lanes":1,"function":1,"port-cap":1,"design":1,"makes":1,"assumes":1,"specifications":1,"products":1,"trademarks":1,"nvidia":1,"logo":1,"united":1}
,"confidential":{"platform":1}
,"describes":{"port":1}
,"bootloader":{"nvidia":1,"mb1":1}
,"developer":{"kit":1}
,"kit":{"hardware":1,"(p2771)":1,"named":1,"p3310":1,"code":1,"board":1,"nvidia":1,"configurations":1}
,"platforms":{"examples":1,"required":1}
,"examples":{"described":1,"u-boot":1,"describe":1}
,"described":{"include":1}
,"include":{"code":1,"dashes":1,"version":1,"regulator":1,"statements":1,"types":1}
,"code":{"jetson":1,"user-visible":1,"without":1,"supports":1,"device":1,"add":1,"(the":1}
,"(p2771)":{"information":1}
,"information":{"customizing":1,"enable":1,"board":1,".dts":1,"pinctrl":1,"uphy":1,"furnished":1,"infringement":1,"previously":1}
,"customizing":{"configuration":1}
,"files":{"refer":1,"document":1,"nvidia":1,"customer":1,"board\u002F<vendor>\u002F<board>\u002Fto":1,"directory":1,"disabling\u002Fenabling":1,"describe":1,"available":1,"referenced":1,"may":1,"tegra\u002Fcommon\u002Fkernel-dts\u002Fpanels\u002Fverify":1,"overrides":1,"based":1,"already":1,"name":1,"drawings":1}
,"refer":{"tegra":1,"board":1,"documentation":1}
,"development":{"guide":1}
,"configuring":{"pinmux":1}
,"pad":{"topics":1,"configuration":1}
,"topics":{"board":1}
,"module":{"consists":1,"name":1,"provided":1,"selection":1,"meets":1}
,"consists":{"p3310":1}
,"p3310":{"main":1,"board":1}
,"main":{"board":1,"tegra":1}
,"sits":{"p2597":1}
,"p2597":{"base":1,"i\u002Fo":1,"board":1,"baseboard":1}
,"base":{"board":1}
,"complete":{"kit":1}
,"named":{"p2771":1}
,"p2771":{"jetson":1,"name":1}
,"used":{"without":1,"throughout":1,"tegra186-quill-p3310-1000-a00-00-base.dts":1,"gpio":1,"implementation":1,"pcie":1,"usb":1,"super-speed":1,"allocate":1,"system":1,"audio":1,"verify":1,"low":1}
,"without":{"software":1,"selecting":1,"notice":1,"express":1}
,"modifications":{"p3310":1,"making":1,"follows":1}
,"i\u002Fo":{"expansion":1}
,"expansion":{"base":1}
,"boards":{"eeprom":1,"include":1,"files":1}
,"eeprom":{"board":1,"custom":1}
,"saved":{"replacing":1}
,"replacing":{"p2597":1}
,"verify":{"software":1,"lane":1,"power":1,"vdd_in":1,"carrier_pwr_on":1,"system":1,"tegraboot":1,"runs":1,"uarts":1,"supplies":1,"controllable":1,"carrier":1,"rails":1,"required":1,"usb0":1,"usb":1,"avdd_usb":1,"signals":1,"hdmi-compatible":1,"display":1,"hdmi":1,"signal":1,"reads":1,"playback":1,"capture":1,"tones":1,"audio":1,"tegra":1,"proper":1,"basic":1,"card":1,"addresses":1,"reads\u002Fwrites":1,"interrupts":1,"functionality":1,"touch":1,"implemented":1,"i2c":1,"embedded":1,"power-on\u002Foff":1,"dsi":1,"preview":1,"video":1,"cameras":1,"replaced":1,"pmic":1,"operation":1,"support\u002Fconfig":1}
,"programming":{"kernel":1,"board":1}
,"tables":{"mb1":1,"available":1}
,"odm":{"data":1}
,"data":{"flashing":1,"follow":1,"based":1,"bit":1,"sheet":1,"sheets":1}
,"de-configure":{"p2597":1}
,"custom":{"configurations":1,"board":1,"baord":1,"desktop":1}
,"configurations":{"custom":1,"defined":1,"every":1,"released":1,"pcie":1}
,"support":{"board":1,"configurations":1,"devices":1}
,"l4t":{"select":1}
,"select":{"simple":1,"appears":1,"similarly-constructed":1}
,"simple":{"lower-case":1}
,"lower-case":{"alpha-numeric":1}
,"alpha-numeric":{"name":1}
,"name":{"board":1,"include":1,"select":1,"exposed":1,"character":1,"note":1,"obvious":1,"may":1,"selected":1,"jetson":1,"organization":1,"vendor":1,"edit":1,"rather":1,"anything":1,"flashing":1}
,"dashes":{"(-)":1}
,"(-)":{"underscores":1}
,"underscores":{"(_)":1}
,"(_)":{"cannot":1}
,"cannot":{"contain":1}
,"contain":{"spaces":1,"instances":1}
,"spaces":{"example":1}
,"example":{"platform":1,"nvidia":1,"p2771":1,"check":1,"remove":1,"change":1,"-odmdata=0x1090000":1,"configuration":1,"phys":1,"usb2.0":1,"xhci":1}
,"jetson-tx2":{"p2771-000-500":1}
,"p2771-000-500":{"myboard":1}
,"myboard":{"name":1}
,"appears":{"filenames":1}
,"filenames":{"pathnames":1,"additionally":1}
,"pathnames":{"u-boot":1}
,"source":{"code":1,"package":1}
,"user-visible":{"device":1}
,"additionally":{"name":1,"update":1}
,"exposed":{"user":1}
,"user":{"u-boot":1}
,"command":{"prompt":1,"resulting":1,"usage":1,"$sudo":1,"line":1}
,"prompt":{"various":1}
,"various":{"linux":1}
,"proc":{"files":1}
,"<board>":{"represents":1,"name":1,"names":1,"appropriate":1,".conf":1,"mmcblk0p1":1}
,"represents":{"board":1,"vendor":1}
,"similarly-constructed":{"vendor":1}
,"vendor":{"name":1,"board":1}
,"character":{"rules":1}
,"rules":{"apply":1}
,"apply":{"following":1}
,"following":{"example":1,"steps":1,"$dmesg":1,"formula":1,"section":1,"actions":1,"define":1,"node":1,"device":1,"examples":1,"command":1}
,"<vendor>":{"represents":1,"name":1}
,"note":{"re-use":1,"u-boot":1,"fdtdump":1,"sata":1,"designing":1}
,"re-use":{"modify":1}
,"modify":{"existing":1,".dts":1,"distributed":1,"device":1,"mb1":1}
,"existing":{"nvidia":1}
,"selecting":{"using":1}
,"using":{"board":1,"cvm":1,"vdd_usb2_5v":1,".dtsi":1,"usb-if":1,"ddc":1}
,"obvious":{"jetson":1}
,"users":{"whether":1}
,"whether":{"modified":1}
,"modified":{"source":1,"emmc":1,"reflect":1}
,"supports":{"original":1,"configurations":1,"usb":1}
,"original":{"jetson":1}
,"throughout":{"document":1}
,"substitute":{"appropriate":1}
,"appropriate":{"value":1,"board":1,"test":1}
,"value":{"placeholder":1,"emmc":1}
,"placeholder":{"executing":1}
,"executing":{"commands":1}
,"commands":{"<function>":1,"operate":1}
,"<function>":{"functional":1}
,"functional":{"module":1,"power":1,"(reading":1}
,"power-tree":{"pinmux":1}
,"sdmmc-drv":{"keys":1}
,"keys":{"comm":1}
,"comm":{"(wifi\u002Fbt)":1}
,"(wifi\u002Fbt)":{"camera":1}
,"camera":{"<board>":1}
,"selected":{"represent":1}
,"represent":{"platform":1,"data":1,"supported":1,"ball":1}
,"names":{"lower":1,"pex1":1,"ball":1,"represent":1,"used":1,"may":1}
,"lower":{"case":1}
,"case":{"letters":1,"xusb":1}
,"letters":{"<version>":1}
,"<version>":{"board":1}
,"number":{"a00":1,"files":1,"<vendor>":1,"gpio15\u002Fap2mdm_ready":1,"search":1,"define":1,"step":1,"tegra_main_gpio":1,"blocks":1,"entries":1}
,"a00":{"files":1}
,"reference":{"boards":1}
,"customer":{"platforms":1,"usage":1,"pinmux":1}
,"organization":{"name":1}
,"<root>":{"device":1}
,"holds":{"root":1}
,"root":{"file":1}
,"file":{"system":1,"configures":1,"replace":1,"example":1,"used":1,".dtsi":1,"including":1,"check":1,"located":1,"odm":1,"during":1}
,"supported":{"value":1,"validated":1,"verify":1}
,"emmc":{"platform":1,"pmic":1,"verify":1,"cpu":1}
,"provides":{"boot":1,"checklist":1}
,"time":{"configuration":1}
,"applied":{"bootloader":1,"software":1,"gpio3_pbb.00":1}
,"available":{"<l4t_top>\u002Fbootloader\u002Ft186ref\u002Fbct":1,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002F<top>\u002Fhardware_nvidia\u002Fsoc\u002Ft18x":1,"outputs":1,"jetson":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdlc\u002Fjetson-tx1-oem-product-design-guide":1}
,"<l4t_top>\u002Fbootloader\u002Ft186ref\u002Fbct":{"pinmux":1}
,"schematic":{"differs":1}
,"differs":{"jetson":1}
,"jetson-tx2-generic-customer-pinmux-template.xlsm":{"spreadsheet":1}
,"spreadsheet":{"provided":1,"available":1,"configuration":1,"contains":1}
,"provided":{"show":1,"nvidia":1}
,"show":{"locations":1}
,"locations":{"default":1}
,"default":{"pinmux":1,"alloted":1,"allocated":1}
,"define":{"pinmux":1,"tegra_main_gpio_port_bb":1,"config_tegra_board_string":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"customize":1,"platform":1}
,"customize":{"spreadsheet":1}
,"designed":{"carrier":1,"enable":1}
,"carrier":{"board":1}
,"translate":{"som-connector":1}
,"som-connector":{"pins":1}
,"pins":{"actual":1,"gpio":1,"usb":1,"jetson":1,"example":1,"gpios":1,"pmu":1}
,"actual":{"gpio":1}
,"numbers":{"understand":1,"controlled":1}
,"understand":{"gpio":1}
,"formula":{"below":1,"calculate":1}
,"below":{"translated":1}
,"translated":{"gpio":1}
,"controlled":{"driver":1,"qspi_io2":1}
,"check":{"gpio":1,"changes":1,"recovery":1,"u-boot":1}
,"gpio15\u002Fap2mdm_ready":{"perform":1,"(21*8)":1}
,"perform":{"following":1,"writes\u002Freads":1}
,"steps":{"check":1}
,"search":{"gpio15_ap2mdm_ready":1,"kernel":1}
,"gpio15_ap2mdm_ready":{"jetson_tx2_generic_customer_pinmux_release.xlsx":1}
,"jetson_tx2_generic_customer_pinmux_release.xlsx":{"confirm":1}
,"confirm":{"customer":1,"tegra186-gpio.h":1}
,"usage":{"field":1,"follows":1,"enable":1,"carrier":1}
,"field":{"applied":1}
,"gpio3_pbb.00":{"confirm":1,"belongs":1}
,"tegra186-gpio.h":{"gpio3_pbb.00":1}
,"belongs":{"main":1,"tegra-gpio":1}
,"group":{"port":1,"command":1}
,"tegra_main_gpio_port_bb":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
,"registers":{"gpios":1}
,"gpios":{"dynamically":1,"320":1,"256":1,"=<tegra_main_gpio":1,"necessary":1}
,"dynamically":{"search":1}
,"messages":{"check":1}
,"allocation":{"ranges":1,"performed":1}
,"ranges":{"gpio":1}
,"resulting":{"output":1}
,"output":{"similar":1,"verify":1,"recommended":1,"kbd":1}
,"similar":{"following":1,"register":1}
,"$dmesg":{"grep":1}
,"grep":{"gpiochip_add_data":1}
,"gpiochip_add_data":{"[1.247404]":1,"registered":1}
,"[1.247404]":{"gpiochip_add_data":1}
,"registered":{"gpios":1,"trademarks":1}
,"320":{"511":1,"following":1,"=488":1}
,"511":{"device":1}
,"tegra-gpio":{"[1.262595]":1,"offset":1,"group":1}
,"[1.262595]":{"gpiochip_add_data":1}
,"256":{"319":1}
,"319":{"device":1}
,"tegra-gpio-aon":{"shown":1,"offset=256":1}
,"shown":{"outpout":1}
,"outpout":{"above":1}
,"above":{"tegra":1,"file":1,"uphys":1,"allocations":1,"example":1}
,"ports":{"different":1,"used":1,"-three":1,"[2:0]":1}
,"different":{"offsets":1,"pcie":1,"voltage":1}
,"offsets":{"tegra-gpio":1}
,"offset":{"=320":1,"320":1}
,"=320":{"tegra-gpio-aon":1}
,"offset=256":{"pbb00":1}
,"pbb00":{"belongs":1}
,"step":{"offset":1}
,"calculate":{"gpio":1}
,"tegra_main_gpio":{"(port":1}
,"(port":{"offset)":1}
,"offset)":{"=((tegra_main_gpio_port_#":1,"hence":1}
,"=((tegra_main_gpio_port_#":{"port":1}
,"*8)":{"offset)":1}
,"hence":{"gpio":1}
,"(21*8)":{"320":1}
,"=488":{"pmic":1}
,"configures":{"initial":1}
,"expander-based":{"gpio":1}
,"regulator":{"settings":1,"information":1,"parameter":1,"usage":1,"custom":1,"config\u002Fpinmux\u002Freview":1,"drivers":1}
,"defined":{"review":1}
,"review":{"configuration":1,"board":1,"pinmux":1}
,"replace":{"references":1}
,"references":{"p2597":1}
,"baord":{"required":1}
,"enable":{"file":1,"vbus-2-supply":1,"usecases":1}
,"remove":{"following":1,"edit":1}
,"section":{"writing":1,"provides":1}
,"writing":{"slave":1}
,"slave":{"i2c":1}
,"controller":{"address":1,"state":1,"soc\u002Ft18x\u002Fkernel-dts\u002Ftegra186-soc\u002Fpanels":1,"usb":1,"functional":1,"lowest":1}
,"address":{"0x74":1}
,"0x74":{"p2597":1}
,"update":{"number":1,"following":1}
,"blocks":{"array":1}
,"array":{"number":1}
,"entries":{"block":1}
,"block":{"tegra186-mb1-bct-pmic-quill-p3310-1000-c04.cfg":1}
,"tegra186-mb1-bct-pmic-quill-p3310-1000-c04.cfg":{"5v0_hdmi_en":1}
,"5v0_hdmi_en":{"pmic.generic.1.block":1}
,"pmic.generic.1.block":{"[2]":1}
,"[2]":{".type":1,".i2c-controller-id":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".block-delay":1,".count":1,".commands":1}
,".type":{"i2c":1}
,"type":{"pmic.generic.1.block":1,"sata":1}
,".i2c-controller-id":{"pmic.generic.1.block":1}
,".slave-add":{"=0xe8":1}
,"=0xe8":{"7bit:0x74":1}
,"7bit:0x74":{"pmic.generic.1.block":1}
,".reg-data-size":{"pmic.generic.1.block":1}
,".reg-add-size":{"pmic.generic.1.block":1}
,".block-delay":{"=10":1}
,"=10":{"pmic.generic.1.block":1}
,".count":{"pmic.generic.1.block":1}
,".commands":{"[0]":1,"[1]":1}
,"[0]":{".0x07.0xff":1}
,".0x07.0xff":{"=0xef":1}
,"=0xef":{"pmic.generic.1.block":1}
,"[1]":{".0x03.0xff":1}
,".0x03.0xff":{"=0x10":1}
,"=0x10":{"platform":1}
,"actions":{"u-boot":1}
,"add":{"support":1,"remove":1,"tegra186-<board>":1,"target":1}
,"copy":{"include\u002Fconfigs\u002Fp2771-0000.h":1,"arch\u002Farm\u002Fdts\u002Ftegra186-p2771-0000-500.dts":1,"configs\u002Fp2771-0000-500_defconfig":1,"board\u002Fnvidia\u002Fp2771-0000\u002Fdirectory":1}
,"include\u002Fconfigs\u002Fp2771-0000.h":{"include\u002Fconfigs\u002F<board>":1}
,"include\u002Fconfigs\u002F<board>":{"edit":1}
,"edit":{"enabled":1,"nodes":1,"<board>_defconfig":1,"arch\u002Farm\u002Fmach-tegra\u002Ftegra186\u002Fkconfig":1,"files":1,"board\u002F<vendor>\u002F<board>\u002Fmaintainers":1,"board\u002F<vendor>\u002F<board>\u002F<board>":1}
,"enabled":{"devices":1,"functional":1,"appropriately":1,"initially":1,"disabled":1,"verify":1,"normal":1}
,"devices":{"features":1,"parameters":1,"appear":1,"sensors":1,"systems":1}
,"features":{"<board>":1}
,"config_tegra_board_string":{"nvidia":1}
,"p2771-0000":{"copy":1,"files":1,"board":1}
,"arch\u002Farm\u002Fdts\u002Ftegra186-p2771-0000-500.dts":{"arch\u002Farm\u002Fdts\u002Ftegra186-<board>":1}
,"arch\u002Farm\u002Fdts\u002Ftegra186-<board>":{".dts":1}
,".dts":{"edit":1,"appropriate":1,"files":1,".dtsi":1,"final":1}
,"parameters":{"(e.g":1}
,"(e.g":{"gpio":1}
,"irq":{"ids)":1}
,"ids)":{"tegra186-<board>":1}
,"tegra186-<board>":{".dts":1,".dtb":1}
,"need":{"add":1}
,"nodes":{"properties":1}
,"properties":{"note":1,"change":1,"nvidia":1,"per":1,"port_otg":1}
,"always":{"exact":1}
,"exact":{"device":1}
,"schema":{"(bindings)":1}
,"(bindings)":{"represent":1}
,"follow":{"examples":1}
,"rather":{"linux":1,"p2771-0000":1}
,".dtb":{"arch\u002Farm\u002Fdts\u002Fmakefile":1,"file":1}
,"arch\u002Farm\u002Fdts\u002Fmakefile":{"copy":1}
,"configs\u002Fp2771-0000-500_defconfig":{"configs\u002F<board>_defconfig":1}
,"configs\u002F<board>_defconfig":{"edit":1}
,"<board>_defconfig":{"refer":1}
,"arch\u002Farm\u002Fmach-tegra\u002Ftegra186\u002Fkconfig":{"add":1}
,"target":{"config":1,"system":1}
,"config":{"kconfig":1}
,"kconfig":{"copy":1}
,"board\u002Fnvidia\u002Fp2771-0000\u002Fdirectory":{"board\u002F<vendor>\u002F<board>\u002F":1}
,"board\u002F<vendor>\u002F<board>\u002F":{"edit":1}
,"board\u002F<vendor>\u002F<board>\u002Fto":{"refer":1}
,"directory":{"contain":1}
,"instances":{"p2771-0000":1}
,"board\u002F<vendor>\u002F<board>\u002Fmaintainers":{"provide":1}
,"provide":{"correct":1,"naming":1}
,"correct":{"maintainer":1,"pmic":1,"dtb":1,"voltage":1,"colors":1}
,"maintainer":{"contact":1}
,"contact":{"information":1}
,"board\u002F<vendor>\u002F<board>\u002F<board>":{"provide":1}
,"assumed":{"using":1}
,"cvm":{"module":1}
,"ddr":{"routing":1,"verify":1,"emmc":1}
,"routing":{"lines":1}
,"lines":{"modifications":1,"(tx":1,"require":1,"verify":1}
,"making":{"cvb":1}
,"cvb":{"baseboard":1}
,"baseboard":{"hosts":1,"modify":1,"gpio":1,"verify":1}
,"hosts":{"peripherals":1}
,"consequently":{"based":1}
,"based":{"peripherals":1,"feature":1,"quill":1}
,"present":{"baseboard":1,"rename":1,"<board>":1}
,"disabling\u002Fenabling":{"controllers":1}
,"controllers":{"changing":1}
,"changing":{"supplies":1}
,"supplies":{"platform":1,"shorted":1,"initial":1,"required":1}
,"(the":{"device":1}
,"tree)":{"platform":1}
,"distributed":{"configuration":1}
,"describe":{"design":1,"changes":1}
,"design":{"platform":1,"changes":1,"guide":1,"specifications":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002F<top>\u002Fhardware_nvidia\u002Fsoc\u002Ft18x":{"final":1}
,"final":{"dtb":1,".dtb":1}
,"dtb":{"file":1,"dts":1,"flash":1,"modifications":1}
,"tegra186-quill-p3310-1000-a00-00-base.dts":{"reading":1,"fdtdump":1,"platform":1}
,"reading":{"above":1}
,".dtsi":{"files":1,"file":1}
,"referenced":{"include":1}
,"statements":{"common":1}
,"common":{".dtsi":1}
,"reflect":{"hardware":1}
,"types":{"changes":1,"supported":1}
,"dtsi":{"filename":1}
,"filename":{"location":1}
,"location":{"power":1}
,"supply":{"changes":1,"xhci":1,"battery_reg":1,"enabled":1}
,"tegra186-quill-power-tree-p3310-1000-a00-00.dtsi":{"regulator":1}
,"parameter":{"changes":1}
,"tegra186-quill-spmic-p3310-1000-a00-00.dtsi":{"display":1}
,"panel":{"node":1,"driver":1}
,"node":{"changes":1,"xhci@3530000":1,"required":1,"list":1,"create":1,"uphy":1}
,"bringup":{"topic":1}
,"topic":{"details":1}
,"details":{"odm":1,"hdmi":1,"verify)":1}
,"feature":{"configuration":1}
,"tegra186-odm-data-plugin-manager.dtsi":{"tegra":1}
,"soc":{"controller":1}
,"state":{"enable\u002Fdisable":1,"verify":1,"pex":1,"deep":1}
,"enable\u002Fdisable":{"controller":1}
,"soc\u002Ft18x\u002Fkernel-dts\u002Ftegra186-soc\u002Fpanels":{"related":1}
,"related":{".dts":1,"rails":1,"circuitry":1}
,"tegra\u002Fcommon\u002Fkernel-dts\u002Fpanels\u002Fverify":{".dts":1}
,"including":{".dts":1,"rise":1,"implied":1}
,"overrides":{"changes":1}
,"best":{"practice":1}
,"practice":{"create":1}
,"create":{".dts":1,"node":1}
,"quill":{"files":1}
,"already":{"present":1}
,"rename":{"newly":1}
,"newly":{"created":1}
,"created":{"files":1}
,"fdtdump":{"dtc":1,"dts":1}
,"dtc":{"generate":1,"dtb":1}
,"generate":{".dts":1}
,"taken":{"effect":1}
,"effect":{"command":1}
,"follows":{"dtc":1,"pinctrl@3520000":1,"configs":1,"usb":1,"pcie0_lane2_mux":1}
,"dts":{"tegra186-quill-p3310-1000-a00-00-base.dtb":1}
,"tegra186-quill-p3310-1000-a00-00-base.dtb":{"tegra186-quill-p3310-1000-a00-00-base.dts":1}
,"expander":{"pins":1,"used":1}
,"vbus-2-supply":{"powered":1,"=<&battery_reg>":1}
,"powered":{"using":1,"used":1}
,"vdd_usb2_5v":{"gpio":1,"supply":1}
,"xhci":{"driver":1,"change":1,"controller":1,"node":1,"owned":1}
,"enumeration":{"fails":1}
,"fails":{"target":1}
,"solve":{"situation":1}
,"situation":{"change":1}
,"battery_reg":{"using":1}
,"located":{"hardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fcommon\u002Fkernel-dts\u002Ft18x-common-platforms\u002Ftegra186-quill-power-tree-p3310-1000-a00-00.dtsi":1}
,"hardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fcommon\u002Fkernel-dts\u002Ft18x-common-platforms\u002Ftegra186-quill-power-tree-p3310-1000-a00-00.dtsi":{"regenerate":1}
,"regenerate":{"dtb":1}
,"flash":{"correct":1,"build":1}
,"pinctrl@3520000":{"{vbus-0-supply":1}
,"{vbus-0-supply":{"=<&vdd_usb0_5v>":1}
,"=<&vdd_usb0_5v>":{"vbus-1-supply":1}
,"vbus-1-supply":{"=<&vdd_usb1_5v>":1}
,"=<&vdd_usb1_5v>":{"vbus-2-supply":1}
,"=<&battery_reg>":{"vbus-3-supply":1,"vddio-hsic-supply":1,"avdd_usb-supply":1}
,"vbus-3-supply":{"=<&battery_reg>":1}
,"vddio-hsic-supply":{"=<&battery_reg>":1}
,"avdd_usb-supply":{"=<&spmic_sd3>":1}
,"=<&spmic_sd3>":{"vclamp_usb-supply":1}
,"vclamp_usb-supply":{"=<&spmic_sd2>":1}
,"=<&spmic_sd2>":{"avdd_pll_erefeut-supply":1,"disable":1}
,"avdd_pll_erefeut-supply":{"=<&spmic_sd2>":1}
,"disable":{"xhci":1}
,"xhci@3530000":{"{status":1}
,"{status":{"disabled":1}
,"disabled":{"phys":1,"status":1,"different":1,"low":1}
,"phys":{"=<&tegra_xusb_padctl":1,"=<padctl_utmi":1,"lowest":1}
,"=<&tegra_xusb_padctl":{"tegra_padctl_phy_utmi_p":1}
,"tegra_padctl_phy_utmi_p":{"(0)>":1,"(1)>":1}
,"(0)>":{"<&tegra_xusb_padctl":1,"\u002F\u002Ffor":1}
,"<&tegra_xusb_padctl":{"tegra_padctl_phy_utmi_p":1,"tegra_padctl_phy_usb3_p":1}
,"(1)>":{"<&tegra_xusb_padctl":1,"phy-names":1}
,"tegra_padctl_phy_usb3_p":{"(1)>":1}
,"phy-names":{"utmi-0":1}
,"utmi-0":{"utmi-1":1,"usb3-0":1}
,"utmi-1":{"usb3-1":1}
,"usb3-1":{"information":1}
,"documentation":{"documentation\u002Fdevicetree\u002Fbindings":1,"function":1,"kernel\u002Ft18x\u002Fdocumentation\u002Fdevicetree\u002Fbindings\u002Fpinctrl\u002Fnvidia":1}
,"documentation\u002Fdevicetree\u002Fbindings":{"nvidia":1}
,"released":{"linux":1,"software":1}
,"super-speed":{"ports":1,"connector":1,"lines":1}
,"implementation":{"lane":1}
,"sharing":{"pcie":1}
,"pcie":{"sata":1,"2_0":1,"0_3":1,"0_2":1,"0_1":1,"0_0":1,"1_0":1,"connector":1,"interface":1,"usb":1,"interfaces":1,"odmdata=0x1090000":1,"system":1}
,"xusb":{"possible":1,"\u002F\u002Foptional":1,"nvidia":1}
,"possible":{"combinations":1,"exception":1,"verify":1}
,"combinations":{"usb":1}
,"configs":{"jetson":1}
,"pin":{"names":1}
,"pex1":{"lane":1,"pins":1,"configure":1}
,"pex_rfu":{"lane":1}
,"pex2":{"lane":1}
,"usb_ss1":{"lane":1}
,"pex0":{"lane":1}
,"usb_ss0":{"note":1,"pins":1,"pex1":1}
,"lanes":{"available":1,"required":1,"otg-0":1,"usb3-0":1,"owned":1,"lane3":1,"refer":1,"verify":1}
,"outputs":{"jetson":1}
,"1x1":{"1x4":1,"1x2":1}
,"1x4":{"pcie":1}
,"2_0":{"pcie":1,"usb_ss":1}
,"0_3":{"pcie":1}
,"0_2":{"pcie":1}
,"0_1":{"pcie":1}
,"0_0":{"sata":1,"usb_ss":1}
,"2*1":{"1x4":1}
,"usb_ss":{"sata":1,"pcie":1}
,"3x1":{"pcie":1}
,"1_0":{"usb_ss":1,"pcie":1}
,"2x1":{"usb_ss":1,"1x2":1}
,"1x2":{"pcie":1,"usb_ss":1}
,"*default":{"usage":1}
,"unused":{"pcie":1}
,"connector":{"usb":1,"pinmux":1,"possible":1,"correctly":1,"(using":1,"bidirectional":1,"devices":1}
,"**notes":{"pcie":1}
,"interface":{"brought":1,"lowest":1,"verify":1,"used":1,"able":1,"writes\u002Freads":1}
,"brought":{"pex1":1}
,"depending":{"setting":1}
,"setting":{"multiplexor":1,"tegra":1}
,"multiplexor":{"module":1}
,"selection":{"controlled":1}
,"configured":{"gpio":1}
,"pinctrl":{"pinmux":1}
,"usecases":{"listed":1}
,"listed":{"table":1}
,"however":{"released":1,"nvidia":1}
,"every":{"configuration":1}
,"validated":{"-configuration":1,"jetson":1}
,"-configuration":{"represent":1}
,"interfaces":{"verified":1,"[2:0]":1,"transition":1}
,"verified":{"carrier":1}
,"performed":{"either":1}
,"either":{"odmdata":1}
,"odmdata":{"p2771-0000.conf.common":1,"allotted":1}
,"p2771-0000.conf.common":{"default":1}
,"alloted":{"uphy":1}
,"uphy":{"client":1,"lanes":1,"lane":1}
,"client":{"bpmp-dtb":1,"(xhci\u002Fxudc\u002Fpcie":1}
,"bpmp-dtb":{"file":1}
,"-odmdata=0x1090000":{"flashing":1}
,"-odmdata=0x90000":{"configuration":1}
,"-odmdata=0x6090000":{"configuration":1}
,"cell":{"colors":1}
,"colors":{"highlight":1,"verify":1}
,"highlight":{"different":1}
,"-three":{"shades":1}
,"shades":{"green":1,"blue":1}
,"green":{"used":1}
,"[2:0]":{"-three":1,"-sata":1}
,"blue":{"used":1}
,"-sata":{"highlighted":1}
,"highlighted":{"orange":1}
,"orange":{"customer":1}
,"contains":{"jetson":1}
,"ball":{"names":1}
,"oem":{"product":1}
,"product":{"design":1,"names":1}
,"external":{"super-speed":1}
,"(dp":{"dn)":1}
,"dn)":{"usb":1}
,"(tx":{"linked":1}
,"linked":{"connector":1}
,"exception":{"fixed":1}
,"fixed":{"on-board":1}
,"on-board":{"device":1}
,"connected":{"super-speed":1,"btb":1}
,"require":{"usb":1}
,"compatibility":{"note":1,"jetson":1}
,"designing":{"custom":1}
,"tx1":{"tx2":1,"oem":1}
,"consulting":{"jetson":1}
,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdlc\u002Fjetson-tx1-oem-product-design-guide":{"required":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdlc\u002Fjetson-tx1-oem-product-design-guide":1,"platform":1}
,"list":{"uphy":1}
,"=<padctl_utmi":{"(0)>":1}
,"\u002F\u002Ffor":{"usb2.0":1,"usb3.0":1}
,"usb2.0":{"port0":1,"usb2-port0":1,"port":1}
,"port0":{"<padctl_usb3":1,"provide":1}
,"<padctl_usb3":{"(0)>":1}
,"usb3.0":{"port0":1,"usb3-port0":1}
,"convention":{"retrieve":1}
,"retrieve":{"above":1}
,"uphys":{"kernel":1}
,"usb3-0":{"pinctrl":1,"\u002F\u002Frequired":1,"above":1,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdlc\u002Fjetson-tx1-oem-product-design-guide":1}
,"usb2-port0":{"{\u002F\u002Fnode":1}
,"{\u002F\u002Fnode":{"name":1}
,"anything":{"nvidia":1}
,"otg-0":{"\u002F\u002Frequired":1}
,"\u002F\u002Frequired":{"properties":1,"property":1}
,"function":{"xusb":1,"property":1}
,"\u002F\u002Foptional":{"properties":1}
,"per":{"padctrl":1,"above":1}
,"padctrl":{"documentation":1}
,"property":{"required":1,"nvidia":1,"lane":1}
,"port-cap":{"port_host_only":1,"port_otg_cap":1}
,"port_host_only":{"\u002F\u002Foptional":1}
,"port_otg":{"usb3.0":1}
,"usb3-port0":{"nvidia":1}
,"port_otg_cap":{"\u002F\u002Frequired":1}
,"allocations":{"work":1,"follows":1}
,"work":{"uphy":1,"cameras":1}
,"owned":{"client":1,"lan0":1}
,"(xhci\u002Fxudc\u002Fpcie":{"per":1}
,"lan0":{"usb3-0":1}
,"allotted":{"uphy":1}
,"bit":{"used":1}
,"allocate":{"lanes":1}
,"lane3":{"default":1}
,"allocated":{"pcie":1}
,"odmdata=0x1090000":{"flashing":1}
,"lane5":{"usb":1}
,"lane4":{"usb":1}
,"lane2":{"usb":1}
,"lane1":{"usb":1}
,"lane0":{"detailed":1}
,"detailed":{"information":1}
,"kernel\u002Ft18x\u002Fdocumentation\u002Fdevicetree\u002Fbindings\u002Fpinctrl\u002Fnvidia":{"tegra186-padctl.txt":1}
,"tegra186-padctl.txt":{"switch":1}
,"switch":{"usb_ss0":1}
,"configure":{"qspi_io2":1}
,"pcie0_lane2_mux":{"{gpio-hog":1}
,"{gpio-hog":{"gpios":1}
,"=<tegra_main_gpio":{"output-low":1}
,"output-low":{"label":1}
,"label":{"pcie-lane2-mux":1}
,"pcie-lane2-mux":{"-status":1}
,"-status":{"disabled":1}
,"status":{"okay":1}
,"okay":{"flashing":1}
,"specific":{"board":1}
,"script":{"uses":1}
,"uses":{"configuration":1}
,".conf":{"file":1}
,"during":{"flashing":1,"deep":1}
,"process":{"flash":1,"platform":1,"preparation":1}
,"execute":{"following":1}
,"$sudo":{".\u002Fflash.sh":1}
,".\u002Fflash.sh":{"<board>":1}
,"mmcblk0p1":{"hardware":1}
,"sure":{"jetson":1}
,"btb":{"connector":1}
,"correctly":{"securely":1,"unknown":1}
,"securely":{"verify":1}
,"shorted":{"ground":1}
,"ground":{"power":1}
,"vdd_in":{"carrier":1}
,"range":{"verify":1}
,"carrier_pwr_on":{"high":1,"signal":1}
,"high":{"power":1}
,"turned":{"verify":1}
,"enter":{"force":1,"lowest":1}
,"force":{"recovery":1}
,"recovery":{"initial":1,"(device":1,"mode":1}
,"flashed":{"tegraflash":1}
,"tegraflash":{"verify":1,"platform":1}
,"tegraboot":{"u-boot":1}
,"run":{"completion":1}
,"completion":{"checking":1}
,"checking":{"log":1,"lanes":1,"diff":1}
,"log":{"output":1}
,"runs":{"desktop":1}
,"desktop":{"verify":1,"kernel":1}
,"uarts":{"intended":1}
,"intended":{"debugging":1,"peripheral":1}
,"debugging":{"enabled":1,"guide":1}
,"appropriately":{"verify":1}
,"initially":{"verify":1}
,"controllable":{"supply":1}
,"voltage":{"levels":1,"hardware":1}
,"levels":{"applicable":1}
,"applicable":{"verify":1}
,"sequence":{"starts":1,"meets":1,"power":1}
,"starts":{"carrier_pwr_on":1}
,"signal":{"asserted":1,"quality":1,"edges":1}
,"asserted":{"power":1}
,"capture":{"cpu_pwr_req":1,"usb0_d":1,"usb2_d":1,"hdmi":1,"works":1,"signals":1}
,"cpu_pwr_req":{"entering":1,"associated":1}
,"entering":{"exiting":1}
,"exiting":{"suspend":1,"deep":1}
,"suspend":{"(lp1)":1}
,"(lp1)":{"deep":1,"capture":1,"verify":1}
,"deep":{"sleep":1}
,"sleep":{"(lp0)":1}
,"(lp0)":{"ensure":1,"verify":1,"platform":1,"capture":1,"suspend":1}
,"ensure":{"cpu_pwr_req":1}
,"associated":{"power":1,"display":1,"imager":1,"2017-2018":1}
,"rail":{"sequence":1,"check":1}
,"meets":{"tegra":1,"manufacturer\u0027s":1}
,"sheet":{"requirements":1}
,"requirements":{"verify":1,"(correct":1,"tegra":1,"met":1,"probe":1}
,"rails":{"deep":1,"back":1,"powered":1,"associated":1}
,"back":{"correct":1}
,"control":{"exiting":1,"interface":1}
,"usb0":{"supports":1,"device":1,"usb1":1,"device\u002Fhost":1}
,"(device":{"mode)":1}
,"mode)":{"verify":1}
,"mode":{"works":1,"implemented":1,"used":1,"verify":1,"enabled":1,"hdmi":1,"system":1,"capture":1,"rails":1,"nvtest":1}
,"works":{"intended":1,"1080p":1,"properly":1,"wakes":1,"implemented":1,"cameras":1}
,"peripheral":{"types":1}
,"usb1":{"usb2":1}
,"usb2":{"host":1}
,"host":{"mode":1}
,"implemented":{"verify":1,"pex":1,"sata":1}
,"device\u002Fhost":{"detection":1}
,"detection":{"supported":1,"works":1}
,"lowest":{"power":1}
,"low":{"power":1}
,"avdd_usb":{"avdd_pll_utmip":1}
,"avdd_pll_utmip":{"during":1}
,"usb0_d":{"+\u002Fd-signals":1}
,"+\u002Fd-signals":{"ends":1}
,"ends":{"link":1}
,"link":{"(connector":1,"accessible":1,"near":1}
,"(connector":{"test":1}
,"test":{"points":1,"fixture":1}
,"points":{"near":1,"access":1,"verify":1}
,"near":{"tegra)":1,"btb":1,"tegra":1,"panel":1}
,"tegra)":{"capture":1,"using":1}
,"usb2_d":{"+\u002Fd-signals":1}
,"usb-if":{"procedures":1}
,"procedures":{"verify":1}
,"signals":{"meet":1,"connector":1,"receiver":1,"probed":1,"near":1}
,"meet":{"requirements":1}
,"(correct":{"eye":1}
,"eye":{"height\u002Fwidth":1,"diagram":1}
,"height\u002Fwidth":{"etc.)":1}
,"etc.)":{"usb":1,"consult":1}
,"tuning":{"guide":1}
,"adjust":{"settings":1}
,"until":{"requirements":1}
,"met":{"usb":1,"audio":1}
,"hdmi-compatible":{"display":1}
,"1080p":{"verify":1}
,"detected":{"properly":1}
,"properly":{"(hpd)":1,"speakers":1,"sound":1,"verify":1,"cameras":1}
,"(hpd)":{"verify":1}
,"reads":{"writes":1}
,"writes":{"display":1,"i2c":1,"variety":1}
,"ddc":{"interface":1}
,"(using":{"appropriate":1}
,"fixture":{"termination)":1}
,"termination)":{"verify":1}
,"quality":{"acceptable":1,"fitness":1}
,"acceptable":{"(meets":1,"look":1,"probed":1,"including":1}
,"(meets":{"eye":1}
,"diagram":{"etc.)":1}
,"consult":{"tegra":1}
,"codec":{"platform":1,"lowest":1,"microphone":1}
,"playback":{"works":1}
,"speakers":{"headphones":1,"headphones\u002Fheadset":1}
,"headphones":{"headset":1}
,"headset":{"verify":1}
,"sound":{"recorded":1}
,"recorded":{"microphone\u002Fheadset":1}
,"microphone\u002Fheadset":{"supported":1}
,"tones":{"voice":1}
,"voice":{"heard":1}
,"heard":{"speakers":1}
,"headphones\u002Fheadset":{"verify":1}
,"enters":{"low":1}
,"receiver":{"end":1}
,"end":{"link":1,"(socket":1}
,"accessible":{"i2s":1}
,"i2s":{"i\u002Fft":1}
,"i\u002Fft":{"used":1}
,"look":{"excessive":1}
,"excessive":{"over\u002Fundershoot":1}
,"over\u002Fundershoot":{"glitches":1}
,"glitches":{"signal":1}
,"edges":{"uart":1,"card":1,"abnormal":1,"sata":1,"embedded":1,"platform":1,"look":1,"software":1}
,"tx\u002Frx\u002Fcts\u002Frts":{"connects":1}
,"connects":{"device":1}
,"rx\u002Ftx\u002Frts\u002Fcts":{"uart":1}
,"proper":{"connectivity":1}
,"connectivity":{"setting":1,"checking":1}
,"necessary":{"debug":1}
,"debug":{"verify":1}
,"basic":{"commands":1}
,"operate":{"properly":1}
,"variety":{"cards":1}
,"cards":{"verify":1}
,"insertion":{"detection":1}
,"wakes":{"system":1}
,"write":{"protect":1}
,"protect":{"works":1}
,"probed":{"receiver":1,"btb":1}
,"(socket":{"test":1}
,"bidirectional":{"signals)":1}
,"signals)":{"look":1}
,"abnormal":{"clock":1}
,"clock":{"duty":1}
,"duty":{"cycle":1}
,"cycle":{"sensors":1}
,"addresses":{"i2c":1}
,"appear":{"correctly":1,"verify":1}
,"unknown":{"ghost":1}
,"ghost":{"devices":1}
,"rise":{"times":1}
,"times":{"signals":1}
,"reads\u002Fwrites":{"i2c":1}
,"spi":{"touch":1}
,"(reading":{"device":1}
,"register":{"successful)":1}
,"successful)":{"platform":1}
,"interrupts":{"generated":1}
,"generated":{"properly":1}
,"functionality":{"touch":1}
,"transition":{"lowest":1}
,"diff":{"lines":1}
,"able":{"perform":1}
,"writes\u002Freads":{"display":1,"work":1}
,"shows":{"correct":1}
,"display\u2019s":{"backlight":1}
,"backlight":{"enabled":1,"brightness":1,"disabled":1}
,"normal":{"display":1}
,"brightness":{"adjusted":1}
,"adjusted":{"properly":1}
,"(and":{"display":1}
,"bridge)":{"transitions":1}
,"transitions":{"lowest":1}
,"power-on\u002Foff":{"sequencing":1}
,"sequencing":{"rails":1}
,"manufacturer\u0027s":{"requirements":1}
,"dsi":{"lvds":1,"debugging":1}
,"lvds":{"edp":1}
,"edp":{"timing":1,"signals":1,"gpu":1,"system":1,"(contain":1}
,"timing":{"(see":1}
,"(see":{"tegra":1}
,"verify)":{"probe":1}
,"probe":{"dsi":1,"mclk":1}
,"connector\u002Ftest":{"points":1}
,"access":{"driver":1}
,"cameras":{"verify":1,"related":1}
,"preview":{"displays":1}
,"displays":{"properly":1}
,"video":{"capture":1}
,"circuitry":{"enter":1}
,"mclk":{"output":1}
,"recommended":{"test":1}
,"replaced":{"sdram":1,"baseboard":1,"emmc":1}
,"sdram":{"mb1":1}
,"bct":{"new":1,"full-speed":1}
,"new":{"ddr":1}
,"operation":{"obtain":1}
,"obtain":{"board":1}
,"schematics":{"component":1}
,"component":{"data":1}
,"sheets":{"verify":1}
,"accordingly":{"base":1,"bring-up":1}
,"reset":{"sequence":1}
,"nvtest":{"(tegra":1}
,"(tegra":{"mods)":1}
,"mods)":{"ddr":1}
,"cpu":{"jtag":1,"power":1}
,"jtag":{"connection":1}
,"connection":{"check":1,"board":1}
,"kbd":{"connection":1}
,"config\u002Fpmic":{"regulator":1}
,"config\u002Fpinmux\u002Freview":{"device":1}
,"support\u002Fconfig":{"boot":1}
,"scripts":{"(bootcmd)":1}
,"(bootcmd)":{"boot":1}
,"line":{"custom":1}
,"wake":{"pins":1}
,"pmu":{"regulator":1}
,"drivers":{"display\u002Fhdmi":1}
,"display\u002Fhdmi":{"audio":1}
,"microphone":{"speaker":1}
,"speaker":{"usb":1}
,"thermal":{"sensor":1}
,"sensor":{"emc":1}
,"emc":{"dfs":1}
,"dfs":{"table":1}
,"ethernet":{"sata":1}
,"cpu\u002Fcore\u002Fgpu":{"dvfs":1}
,"dvfs":{"emc":1}
,"cpu\u002Fcore":{"edp":1}
,"gpu":{"edp":1}
,"(contain":{"current":1}
,"current":{"monitor":1}
,"monitor":{"&voltage":1}
,"&voltage":{"comparator)":1}
,"comparator)":{"power":1}
,"lp0":{"(optional)":1}
,"down":{"bct":1}
,"full-speed":{"www.nvidia.com":1}
,"www.nvidia.com":{"notice":1}
,"notice":{"nvidia":1,"publication":1}
,"specifications":{"reference":1,"mentioned":1}
,"drawings":{"diagnostics":1}
,"diagnostics":{"lists":1}
,"lists":{"documents":1}
,"documents":{"(together":1}
,"(together":{"separately":1}
,"separately":{"materials":1}
,"materials":{"provided":1,"express":1}
,"makes":{"warranties":1}
,"warranties":{"express":1,"including":1}
,"express":{"implied":1,"written":1}
,"implied":{"statutory":1,"conditions":1,"warranty":1}
,"statutory":{"otherwise":1}
,"otherwise":{"respect":1,"patent":1}
,"respect":{"materials":1}
,"conditions":{"representations":1}
,"representations":{"warranties":1}
,"warranty":{"condition":1}
,"condition":{"title":1}
,"title":{"merchantability":1}
,"merchantability":{"satisfactory":1}
,"satisfactory":{"quality":1}
,"fitness":{"particular":1}
,"particular":{"purpose":1}
,"purpose":{"on-infringement":1}
,"on-infringement":{"hereby":1}
,"hereby":{"excluded":1}
,"excluded":{"maximum":1}
,"maximum":{"extent":1}
,"extent":{"permitted":1}
,"permitted":{"law":1}
,"law":{"information":1}
,"furnished":{"believed":1}
,"believed":{"accurate":1}
,"accurate":{"reliable":1}
,"reliable":{"however":1}
,"assumes":{"responsibility":1}
,"responsibility":{"consequences":1}
,"consequences":{"information":1}
,"infringement":{"patents":1}
,"patents":{"third":1}
,"third":{"parties":1}
,"parties":{"may":1}
,"result":{"license":1}
,"license":{"granted":1}
,"granted":{"implication":1}
,"implication":{"otherwise":1}
,"patent":{"patent":1,"nvidia":1}
,"mentioned":{"publication":1}
,"publication":{"subject":1,"supersedes":1}
,"subject":{"change":1}
,"supersedes":{"replaces":1}
,"replaces":{"information":1}
,"previously":{"supplied":1}
,"supplied":{"nvidia":1}
,"products":{"authorized":1}
,"authorized":{"critical":1}
,"critical":{"components":1}
,"components":{"life":1}
,"life":{"support":1}
,"systems":{"without":1}
,"written":{"approval":1}
,"approval":{"nvidia":1}
,"trademarks":{"nvidia":1,"registered":1,"respective":1}
,"logo":{"tegra":1}
,"united":{"states":1}
,"states":{"countries":1}
,"countries":{"company":1}
,"company":{"product":1}
,"respective":{"companies":1}
,"companies":{"associated":1}
,"2017-2018":{"nvidia":1}
}
;Search.control.loadWordPairs(pairs);
