var pairs =
{
"platform":{"adaptation":1,"example":1,"modify":1,"copies":1,"circuit":1,"hardware":1}
,"adaptation":{"bring-up":1}
,"bring-up":{"guide":1,"checklist":1,"board":1,"hardware":1,"document":1,"platform":1,"process":1}
,"guide":{"da_07839-001":1,"platform":1,"process":1,"external":1,"adjust":1,"details":1}
,"da_07839-001":{"march":1,"document":1,"version":1,"iii":1,"u-boot":1,"platform":1,"right-click":1,"save":1,"porting":1,"configuration":1,"copy":1,"regulator":1,"example":1,"usb":1,"r24":1,"2.0":1,"-nvidia":1,"sequence":1,"property":1,"<&tegra_padctl_uphy":1,"usb3-standalone":1,"flashing":1,"power-on":1,"verify":1,"imager":1}
,"march":{"2018":1}
,"2018":{"tegra":1}
,"tegra":{"linux":1,"platform":1,"models":1,"lanes":1,"pin":1,"board":1,"data":1,"usb":1,"hdmi":1,"tx\u002Frx\u002Fcts\u002Frts":1,"pins":1,"device":1,"dsi":1,"jetson":1}
,"linux":{"driver":1,"kernel":1,"system":1,"code":1}
,"driver":{"package":1,"connector\u002Ftest":1,"possible":1}
,"package":{"tegra":1,"u-boot":1,"release":1,"platform":1}
,"document":{"change":1,"software":1,"nvidia":1,"<board>":1,"<vendor>":1}
,"change":{"history":1,"v1.0":1,"pinmux":1,"local":1,"following":1,"power":1,"gpio":1,"setting":1,"usb":1,"nvidia":1,"create":1,"uart":1,"without":1}
,"history":{"da_07839-001":1}
,"version":{"date":1,"number":1,"pinmux":1,"changes":1,"3.10":1,"4.4":1}
,"date":{"authors":1}
,"authors":{"description":1}
,"description":{"change":1,"xhci":1,"pinctrl@7009f000\u002Fpinmux":1}
,"v1.0":{"mar":1}
,"mar":{"2016":1,"2017":1}
,"2016":{"msum":1,"mzensius":1}
,"msum":{"jsachs":1}
,"jsachs":{"initial":1}
,"initial":{"release":1,"power-on":1,"software":1}
,"release":{"v1.1":1,"v1.4":1,"includes":1,"24.x":1,"28.x":1}
,"v1.1":{"aug":1}
,"aug":{"2016":1}
,"mzensius":{"adds":1}
,"adds":{"usb":1,"camera":1}
,"usb":{"lane":1,"2.0":1,"3.0":1,"configuration":1,"platform":1,"example":1,"following":1,"3.0\u002Fpcie\u002Fsata":1,"2.0\u002F3.0":1,"connector":1,"recovery":1,"phys":1,"signals":1,"tuning":1,"card":1}
,"lane":{"mapping":1,"sharing":1,"lane":1,"sata":1,"number":1,"mapped":1,"(usb_ss1":1,"usb":1,"owner":1,"xusb":1,"(pex1)":1,"map":1,"assign":1,"matches":1,"(pex1":1,"usb_ss1":1,"used":1,"nvidia":1}
,"mapping":{"section":1,"sections":1,"r24":1,"usb":1,"required":1,"ssport0-usb2port0":1,"pex\u002Fhsio":1,"ssport0-lane6":1,"indicate":1,"indicates":1}
,"section":{"v1.2":1,"looks":1,"5.1":1,"provides":1}
,"v1.2":{"mar":1}
,"2017":{"mzensius":1,"hlang":1,"hlang\u002Fvsagar\u002Fdanel":1,"hlang\u002Fdanel":1,"nvidia":1}
,"camera":{"sensor":1,"<board>":1}
,"sensor":{"bring-up":1,"emc":1}
,"checklist":{"v1.3":1,"power-on":1,"preparation":1,"section":1,"platform":1,"software":1}
,"v1.3":{"june":1}
,"june":{"2017":1}
,"hlang":{"generate":1}
,"generate":{"final":1,"u-boot":1,"directly":1,"device":1,"answer":1,"files":1}
,"final":{"pdf":1}
,"pdf":{"28.1":1}
,"28.1":{"release":1}
,"v1.4":{"oct":1}
,"oct":{"2017":1}
,"hlang\u002Fvsagar\u002Fdanel":{"update":1}
,"update":{"porting":1,"r28":1}
,"porting":{"linux":1,"instructions":1,"u-boot":1,"hardware":1,"considerations":1,"follows":1}
,"kernel":{"usb":1,"porting":1,"pad":1,"peripherals":1,"source":1,"\u002Fproc":1,"exporting":1,"linux":1,"uses":1,"code":1,"always":1,"add":1,"port":1,"configuration":1,"work":1,"rather":1,"pinmux":1,"dtb":1,"image":1,"without":1,"copy":1,"version":1,"modify":1,"boot":1,"command":1}
,"sections":{"v1.5":1,"refer":1}
,"v1.5":{"nov":1}
,"nov":{"2017":1}
,"hlang\u002Fdanel":{"update":1}
,"r28":{"device":1,"required":1,"example":1}
,"device":{"tree":1,"holds":1,"tree)":1,"connected":1,"mode":1,"rx\u002Ftx\u002Frts\u002Fcts":1,"similar":1,"look":1}
,"tree":{"changes":1,"file":1,"exporting":1,"files":1,"platform":1,"schema":1,"reference":1,"item":1,"module":1,"properties":1,"review":1,"verify":1}
,"changes":{"example":1,"exporting":1,"r24":1,"r28":1,"board":1,"new":1,"csv-to-board.py":1,"due":1,"release":1,"following":1,"property":1,"<0x7721>":1,"1x1":1}
,"example":{"topics":1,"r24":1,"r28":1,"considerations":1,"board":1,"nvidia":1,"p2597":1,"<board>":1,"change":1,"vdd":1,"file":1,"meant":1,"configuration":1,"<0x0e02>":1,"<0x7730>":1,"<0xff56>":1,"case":1,"following":1,"usb":1,"pci@1,0":1,"controller-0":1}
,"topics":{"updates":1}
,"updates":{"pcie":1}
,"pcie":{"platform":1,"sata":1,"1_0":1,"0_3":1,"0_2":1,"0_1":1,"0_0":1,"disabled":1,"module":1,"configuration":1,"indicates":1,"controller":1,"port":1,"m2.key":1,"nvidia":1,"lanes":1,"{-nvidia":1,"system":1}
,"iii":{"table":1}
,"table":{"contents":1,"ethernet":1,"cpu\u002Fcore":1}
,"contents":{"platform":1}
,"board":{"naming":1,"l4t":1,"possibly":1,"name":1,"board":1,"placeholders":1,"note":1,"version":1,"schematic":1,"change":1,"using":1,"platform":1,"based":1,"obtain":1,"supported_boards":1,"prompted":1,"copy":1,"example":1,"nodes":1,"edit":1,"required":1,"p2597":1,"may":1,"modeled":1,"following":1,"matches":1,"info":1,"(type=\u0022":1,"tag\u2019s":1,"range":1,"power-on":1,"bct":1,"schematics":1,"pinmux":1,"config\u002Fpmic":1}
,"naming":{"placeholders":1,"support":1}
,"placeholders":{"porting":1,"substitute":1}
,"instructions":{"pinmux":1,"following":1}
,"pinmux":{"changes":1,"u-boot":1,"l4t":1,"sdmmc-drv":1,"configuration":1,"spreadsheet":1,"header":1,"files":1,"pcie-m2":1,"pcie":1,"bring-up":1,"gpio":1}
,"exporting":{"pinmux":1}
,"u-boot":{"exporting":1,"porting":1,"port":1,"boot":1,"linux":1,"command":1,"u-boot":1,"uses":1,"pinmux":1,"source":1,"perform":1,"rather":1,"replace":1,"run":1}
,"l4t":{"linux":1,"choose":1}
,"pad":{"power":1}
,"power":{"detection":1,"power":1,"optimization":1,"clocks":1,"tree":1,"t210":1,"detect":1,"key":1,"{label":1,"gpios":1,"management":1,"supplies":1,"turned":1,"verify":1,"rail":1,"mode":1,"system":1,"state":1,"reset":1,"lp0":1,"down":1}
,"detection":{"usb":1,"pad":1,"supported":1,"works":1}
,"r24":{"required":1,"example":1,"device":1}
,"required":{"device":1,"pinmux":1,"copy":1,"power-on":1,"rails":1}
,"considerations":{"porting":1,"recommendations":1}
,"hardware":{"bring-up":1,"validation":1,"platforms":1,"configure":1,"modules":1,"control":1}
,"power-on":{"initial":1,"sure":1,"verify":1,"enabled":1,"sequence":1}
,"software":{"flashing":1,"bring-up":1,"developers":1,"define":1,"uses":1}
,"flashing":{"power":1,"linux_for_tegra\u002Fkernel\u002Fdtb\u002Ffor":1,"build":1,"read":1,"software":1,"config":1,"verify":1}
,"optimization":{"usb":1,"capture":1}
,"2.0":{"phy":1,"(dp":1,"compatibility":1,"3.0":1,"ports":1,"port":1,"usb":1,"lines":1,"standalone":1,"controller":1}
,"phy":{"usb":1,"handles":1,"names":1,"verify":1}
,"3.0":{"hdmi":1,"superspeed":1,"shown":1,"pcie":1,"lines":1,"available":1,"ports":1,"port":1,"por":1,"standalone":1,"usb":1,"controller":1,"connector":1,"phys":1,"verify":1,"host":1,"device":1,"interface":1}
,"hdmi":{"audio":1,"verify":1,"reads":1,"related":1,"signals":1,"tuning":1}
,"audio":{"uart":1,"verify":1,"codec":1}
,"uart":{"card":1,"port":1,"verify":1,"used":1,"output":1}
,"card":{"(sdmmc1)":1,"insertion":1,"write":1,"low":1,"thermal":1}
,"(sdmmc1)":{"sensors":1,"verify":1}
,"sensors":{"i2c":1}
,"i2c":{"general":1,"touch":1,"interface":1,"devices":1,"spi":1,"control":1}
,"general":{"sensors":1,"verify":1}
,"touch":{"screen":1}
,"screen":{"(optional)":1,"controller":1,"verify":1}
,"(optional)":{"pex":1,"sata":1,"embedded":1,"imager":1,"software":1,"verify":1,"cpu":1}
,"pex":{"(optional)":1,"lanes":1,"interfaces":1}
,"sata":{"(optional)":1,"xusb":1,"tegra":1,"(carrier)":1,"pcie":1,"interfaces":1}
,"embedded":{"display":1,"display\u2019s":1}
,"display":{"(s)":1,"id=\u0022":1,"board":1,"power":1,"works":1,"detected":1,"using":1,"verify":1,"shows":1,"mode":1,"(and":1,"bridge)":1,"meets":1}
,"(s)":{"(optional)":1}
,"imager":{"(s)":1,"module":1}
,"preparation":{"bring-up":1,"verify":1}
,"validation":{"platform":1,"kernel":1,"system":1,"power":1,"tegraflash":1,"device":1}
,"port":{"boot":1,"validation":1,"nvidia":1,"kernel":1,"bit":1,"lsb":1,"usb":1,"enabled":1,"lines":1,"starting":1,"entered":1,"available":1,"require":1,"valid":1,"standalone":1,"role":1,"lane":1,"linked":1,"using":1,"ball":1,"sufficient":1,"matched":1,"value":1,"xhci":1,"property":1,"used":1,"specify":1,"case":1,"matches":1,"possible":1,"supports":1,"specifies":1,"bound":1,"sub-node":1,"example":1,"(ball":1,"usb3-m2":1,"following":1,"<&tegra_padctl_uphy":1,"usb3-2":1,"overall":1,"usb3-standalone":1,"uarta":1}
,"boot":{"validation":1,"loader":1,"directory":1,"partition":1,"scripts":1,"u-boot":1,"kernel":1}
,"peripherals":{"port":1}
,"system":{"power":1,"module":1,"present":1,"$git":1,"generate":1,"wish":1,"along":1,"reboot":1,"enter":1,"flashed":1,"low":1,"deep":1,"enters":1,"supported":1,"state":1,"edp":1}
,"clocks":{"platform":1,"cpu\u002Fcore\u002Fgpu":1}
,"developers":{"whose":1}
,"whose":{"target":1,"name":1}
,"target":{"nvidia":1,"config":1,"system":1}
,"nvidia":{"jetson":1,"tegra":1,"platform":1,"<board>":1,"reference":1,"customize":1,"p2371-2180":1,"recommends":1,"released":1,"portmap":1,"ss_portmap":1,"lane_owner":1,"lane-map":1,"common_padctl":1,"lanes":1,"function":1,"port-cap":1,"usb3-port":1,"usb2-map":1,"pcie-lane-select":1,"num-lanes":1,"usb2-mapportmap":1,"pcie-controller":1,"diagnostic":1,"design":1,"makes":1,"assumes":1,"specifications":1,"products":1,"trademarks":1,"nvidia":1,"logo":1,"united":1}
,"jetson":{"module":1,"tx1":1,"developer":1,"trademarks":1}
,"module":{"describes":1,"name":1,"(som)":1,"definition":1,"key":1,"configured":1,"(type=\u0022":1,"development":1,"meets":1}
,"describes":{"port":1,"device":1,"wifi":1,"configured":1}
,"loader":{"nvidia":1,"locate":1}
,"tx1":{"developer":1,"users":1,"configuration":1,"entry":1,"pin":1,"lan":1,"usb":1,"oem":1,"connected":1}
,"developer":{"kit":1}
,"kit":{"hardware":1,"(p2371-2180)":1,"code":1,"carrier":1,"add":1}
,"platforms":{"procedures":1,"need":1}
,"procedures":{"document":1,"customize":1,"verify":1}
,"includes":{"code":1,".dtsi":1}
,"code":{"jetson":1,"user-visible":1,"without":1,"supports":1,"correct":1,"add":1,"(the":1,"=<key_power>":1}
,"(p2371-2180)":{"serve":1}
,"serve":{"example":1}
,"support":{"board":1,"<board>":1,"kernel":1,"devices":1}
,"choose":{"simple":1,"appear":1,"similarly-constructed":1,"csv":1}
,"simple":{"lower-case":1}
,"lower-case":{"alpha-numeric":1}
,"alpha-numeric":{"name":1}
,"name":{"board":1,"choose":1,"character":1,"note":1,"obvious":1,"may":1,"chosen":1,"jetson":1,"2180":1,"name":1,"board\u2019s":1,"based":1,"e.g":1,"tab":1,"ends":1,"changes":1,"matches":1,"mismatch":1,"edit":1,"rather":1,"form":1,"$sudo":1,"xml":1}
,"possibly":{"including":1}
,"including":{"dashes":1,"rise":1,"implied":1}
,"dashes":{"(-)":1}
,"(-)":{"underscores":1}
,"underscores":{"(_)":1}
,"(_)":{"containing":1}
,"containing":{"spaces":1}
,"spaces":{"following":1}
,"following":{"examples":1,"example":1,"sections":1,"procedures":1,"commands":1,"command":1,"actions":1,"define":1,"procedure":1,"directory":1,"r24":1,"mapping":1,"device":1,"r28":1,"properties":1,"lines":1}
,"examples":{"jetson-tx1":1,"u-boot":1,"linux":1,"modifications":1}
,"jetson-tx1":{"p2371-2180":1}
,"p2371-2180":{"beaver":1,"copy":1,"files":1,"board":1}
,"beaver":{"name":1}
,"appear":{"file":1,"correctly":1,"verify":1}
,"file":{"names":1,"system":1,"name":1,"writable":1,"microsoft":1,"rename":1,"define":1,"may":1,"exit":1,"tab":1,"csv\u002Fdirectory":1,"enter":1,"import":1,"arbitrary":1,"$.\u002Fboard-to-uboot.py":1,"generated":1,"files":1,"includes":1,".dtsi":1,"chosen":1,"whose":1,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-platforms\u002Ftegra210-<board>-<function>":1,"refer":1,"appropriate":1,"nodes":1,"linux_for_tegra\u002Fbootloader\u002Ft210ref\u002Fp2371-2180\u002Fextlinux.conf.emmc":1,"example":1,"platform":1,"tegra210-platforms\u002Ftegra210-comms-p2530-0930.dtsi":1,"\u0027power":1,"during":1,"provided":1,"board_config_p2597-devkit.xml":1,"format":1,"-->":1,"p2371-2180-devkit.conf":1,"option":1,"contains":1}
,"names":{"path":1,"u-boot":1,"exposed":1,"lower":1,"form":1,"pex1":1,"ball":1,"determining":1,"used":1,"e41":1,"b42":1,"g42":1,"usb":1,"may":1}
,"path":{"names":1}
,"source":{"code":1,"tree":1,"package":1}
,"user-visible":{"device":1}
,"exposed":{"user":1}
,"user":{"via":1}
,"via":{"u-boot":1}
,"command":{"prompt":1,"tegra-pinnmux-scripts":1,"line":1,"generate":1,"sudo":1}
,"prompt":{"various":1,"asking":1}
,"various":{"linux":1,"types":1}
,"\u002Fproc":{"files":1}
,"files":{"document":1,"nvidia":1,"customer":1,"define":1,"pinmux":1,"provide":1,"saved":1,"linux":1,"board\u002F<vendor>\u002F<board>\u002Fto":1,"directory":1,"describe":1,"arch\u002Farm64\u002Fboot\u002Fdts\u002F":1,"included":1,"various":1,"references":1,"edit":1,"earlier":1,"refer":1,"drawings":1}
,"<board>":{"represents":1,"name":1,"names":1,"<board>_pinmux.xlsm":1,"\u0027filename":1,"tegra-pinmux-scripts":1,"optionally":1,"pinmux-config-<board>":1,"appropriate":1,"refers":1,".conf":1}
,"represents":{"board":1,"vendor":1,"port":1,"usb":1,"following":1}
,"similarly-constructed":{"vendor":1}
,"vendor":{"name":1,"<root>":1}
,"character":{"rules":1}
,"rules":{"apply":1}
,"apply":{"following":1}
,"<vendor>":{"represents":1,"organization\u2019s":1}
,"note":{"simply":1,"nvidia":1,"u-boot":1,"example":1}
,"simply":{"re-use":1}
,"re-use":{"modify":1}
,"modify":{"existing":1,"columns":1,"distributed":1,"copies":1,"odmdata":1,"lines":1,"debug_uartport":1}
,"existing":{"nvidia":1,"jetson":1}
,"without":{"choosing":1,"diluting":1,"usb":1,"notice":1,"express":1}
,"choosing":{"using":1}
,"using":{"board":1,"following":1,"tegra-pinmux-scripts":1,"lane":1,"xml":1,"usb-if":1,"ddc":1}
,"obvious":{"jetson":1}
,"users":{"whether":1}
,"whether":{"modified":1,"wish":1}
,"modified":{"source":1,"cboot":1,"<0x14>":1}
,"supports":{"original":1,"host":1,"xusb@70090000":1,"usb":1}
,"original":{"jetson":1}
,"carrier":{"board":1}
,"refer":{"filenames":1,"board":1,"copies":1,"documentation":1}
,"filenames":{"pathnames":1}
,"pathnames":{"contain":1}
,"contain":{"placeholders":1,"instances":1}
,"substitute":{"appropriate":1}
,"appropriate":{"value":1,"board":1,"test":1}
,"value":{"placeholder":1,"emmc":1,"changes":1,"<0xff56>":1,"nvidia":1,"file":1}
,"placeholder":{"enter":1}
,"enter":{"commands":1,"modify":1,"following":1,"superspeed":1,"0xf":1,"force":1,"lowest":1}
,"commands":{"<function>":1,"linux":1,"operate":1}
,"<function>":{"functional":1}
,"functional":{"module":1,"power":1,"(reading":1}
,"may":{"power-tree":1,"generated":1,"rename":1,"need":1,"platform":1,"represent":1,"result":1,"trademarks":1}
,"power-tree":{"pinmux":1}
,"sdmmc-drv":{"keys":1}
,"keys":{"comm":1}
,"comm":{"(wifi\u002Fbt)":1}
,"(wifi\u002Fbt)":{"camera":1}
,"chosen":{"represent":1,"location":1}
,"represent":{"platform":1,"data":1,"usb":1,"hsic":1,"end-connector":1}
,"p2597":{"name":1,"nvidia":1,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-jetson-cv-base-p2597-2180-a00.dts":1}
,"lower":{"case":1}
,"case":{"letters":1,"available":1,"usb":1,"usb_ss":1,"follows":1,"possible":1,"4\u002F5":1,"look":1}
,"letters":{"<som>":1}
,"<som>":{"system":1}
,"(som)":{"board":1}
,"2180":{"<version>":1,"sku=\u0022":1}
,"<version>":{"board":1}
,"number":{"a00":1,"files":1,"entered":1,"usb":1,"port":1}
,"a00":{"files":1}
,"reference":{"boards":1,"board":1}
,"boards":{"include":1,"p2597":1,"files":1}
,"include":{"version":1,"<vendor>":1,"xusb":1}
,"customer":{"platforms":1,"pinmux":1}
,"need":{"include":1,"added":1,"add":1}
,"organization\u2019s":{"name":1}
,"board\u2019s":{"vendor":1,"pinmux":1}
,"<root>":{"device":1}
,"holds":{"platform\u2019s":1}
,"platform\u2019s":{"root":1,"design":1}
,"root":{"file":1,"port":1}
,"present":{"supported":1,"root":1}
,"supported":{"value":1,"r28":1,"verify":1}
,"emmc":{"pinmux":1,"nvidia":1,"cpu":1}
,"schematic":{"differs":1,"once":1}
,"differs":{"jetson":1}
,"configuration":{"applied":1,"obtain":1,"board":1,"tab":1,"want":1,"data":1,"header":1,"generate":1,"spreadsheet":1,"code":1,"files":1,"pins":1,"given":1,"changes":1,"uses":1,"file":1}
,"applied":{"software":1}
,"define":{"board\u2019s":1,"pinmux":1,"config_tegra_board_string":1,"key":1,"config_tegra_enable_uartd":1,"config_sys_ns16550_com1":1,"config_tegra_enable_uarta":1}
,"obtain":{"jetson_tx1_customer_pinmux_release.xlsm":1,"tegra-pinmux-scripts":1,"board":1}
,"jetson_tx1_customer_pinmux_release.xlsm":{"nvidia":1}
,"customize":{"configuration":1,"pinmux":1,"tegra-pinmux-scripts":1}
,"spreadsheet":{"create":1,"required":1,"reflects":1,"input":1,"csv":1,"generate":1,"click":1,"file":1,"contains":1}
,"create":{"copy":1,"two":1}
,"copy":{"file":1,"csv":1,"pinmux-config-<board>":1,"device":1,"include\u002Fconfigs\u002Fjetson-p2371-2180.h":1,"arch\u002Farm\u002Fdts\u002Ftegra210-p2371-2180.dts":1,"configs\u002Fp2371-2180_defconfig":1,"board\u002Fnvidia\u002Fp2371-2180\u002Fdirectory":1,"pinmux":1,".dts":1,"generated":1,"kernel":1,"copy":1,"linux_for_tegra\u002Fjetson-tx1.conf":1}
,"based":{"board":1,"name":1,"schematic":1}
,"e.g":{"<board>_pinmux.xlsm":1}
,"<board>_pinmux.xlsm":{"ensure":1,"worksheet":1}
,"ensure":{"new":1,"cpu":1}
,"new":{"file":1,"sub-nodes":1,"values":1}
,"writable":{"windows":1}
,"windows":{"open":1}
,"open":{"new":1,"csv-to-board.py":1}
,"microsoft":{"excel":1}
,"excel":{"microsoft":1,"displays":1,"click":1,"spreadsheet":1}
,"displays":{"warnings":1,"properly":1}
,"warnings":{"protected":1}
,"protected":{"view":1}
,"view":{"security":1}
,"security":{"warning":1}
,"warning":{"click":1}
,"click":{"enable":1,"rename":1,"file":1,"save":1,"generate":1}
,"enable":{"editing":1,"content":1}
,"editing":{"enable":1}
,"content":{"save":1,"tegra210-<board>-gpio.dtsi":1,"generated":1}
,"save":{"changes":1,"file":1,"spreadsheet":1,"save":1,"type":1,"copy":1}
,"rename":{"jetson":1,"menu":1,"copies":1}
,"tab":{"based":1,"bottom":1,"press":1,"file":1,"click":1}
,"right-click":{"jetson":1}
,"bottom":{"window":1}
,"window":{"click":1}
,"menu":{"option":1}
,"option":{"type":1,"specify":1,"bcffile=\u0022":1}
,"type":{"board":1,"choose":1}
,"press":{"enter":1}
,"columns":{"spreadsheet":1}
,"once":{"spreadsheet":1}
,"reflects":{"configuration":1}
,"want":{"export":1}
,"export":{"configuration":1}
,"data":{"format":1,"structure":1,"tegra-pinmux-script":1,"follow":1,"flash":1,"sheet":1,"sheets":1}
,"format":{"u-boot":1,"microsoft":1,"$.\u002Fcsv-to-board.py":1,"xml":1}
,"uses":{"header":1,"device":1,"lines":1,"boardid":1,"eeprom":1}
,"header":{"file":1,"generated":1}
,"generated":{"using":1,"sure":1,"(pinmux-config-<board>":1,"kernel":1,"dtb":1,"properly":1}
,"tegra-pinmux-scripts":{"tool":1,"board":1,"running":1,"tegra-pinmux-scripts":1,"directory":1,"read":1,"linux":1}
,"tool":{"customize":1,"obtain":1}
,"running":{"following":1,"port":1}
,"$git":{"clone":1,"commit":1}
,"clone":{"https:\u002F\u002Fgithub.com\u002Fnvidia\u002Ftegra-pinmux-scripts.git":1}
,"https:\u002F\u002Fgithub.com\u002Fnvidia\u002Ftegra-pinmux-scripts.git":{"$cd":1}
,"$cd":{"tegra-pinmux-scripts":1}
,"directory":{"open":1,"import":1,"contain":1,"flashing":1,"instead":1,"linux_for_tegra\u002Fkernel\u002F2":1}
,"csv-to-board.py":{"text":1,"click":1}
,"text":{"editor":1}
,"editor":{"locate":1,"commit":1}
,"locate":{"definition":1,"following":1}
,"definition":{"supported_boards":1,"part":1}
,"supported_boards":{"data":1}
,"structure":{"approximately":1,"following":1}
,"approximately":{"line":1}
,"line":{"add":1,"option":1,"custom":1}
,"add":{"entry":1,"support":1,"tegra210-<board>":1,"target":1,"remove":1,"<&tegra_padctl_uphy":1,"utmi-3":1,"new":1,"list":1}
,"entry":{"board":1,"platform":1}
,"worksheet":{"<board>":1}
,"\u0027filename":{"\u0027csv\u002F<board>":1}
,"\u0027csv\u002F<board>":{".csv":1}
,".csv":{"\u0027rsvd_0based":1}
,"\u0027rsvd_0based":{"false":1}
,"false":{"save":1}
,"exit":{"editor":1}
,"commit":{"change":1,"add":1}
,"local":{"git":1}
,"git":{"repository":1}
,"repository":{"$git":1}
,"read":{"csv":1,"eeprom":1}
,"csv":{"(comma":1,"format":1,"(ms-doc)":1,"file":1}
,"(comma":{"separated":1}
,"separated":{"values)":1}
,"values)":{"version":1}
,"input":{"platform":1}
,"(ms-doc)":{"(*.csv)":1}
,"(*.csv)":{"verify":1}
,"verify":{"file":1,"power":1,"vdd_in":1,"carrier_wr_on":1,"system":1,"tegraboot":1,"runs":1,"uarts":1,"supplies":1,"controllable":1,"carrier":1,"rails":1,"required":1,"usb0":1,"usb":1,"avdd_usb":1,"signals":1,"hdmi-compatible":1,"display":1,"hdmi":1,"signal":1,"reads":1,"playback":1,"capture":1,"tones":1,"audio":1,"tegra":1,"proper":1,"basic":1,"card":1,"addresses":1,"reads\u002Fwrites":1,"interrupts":1,"functionality":1,"touch":1,"implemented":1,"i2c":1,"embedded":1,"power-on\u002Foff":1,"dsi":1,"preview":1,"video":1,"flashes":1,"available":1,"privacy":1,"cameras":1,"board":1,"operation":1,"support\u002Fconfig":1}
,"ends":{"in.csv":1,"link":1}
,"in.csv":{"otherwise":1}
,"otherwise":{"matches":1,"uses":1,"respect":1,"patent":1}
,"matches":{"file":1,"kernel":1,"usecase":1,"valid":1,"case":1}
,"csv\u002Fdirectory":{"tegra-pinmux-scripts":1}
,"tegra-pinnmux-scripts":{"directory":1}
,"import":{"data":1,"allows":1}
,"tegra-pinmux-script":{"internal":1}
,"internal":{"format":1}
,"$.\u002Fcsv-to-board.py":{"<board>":1}
,"optionally":{"--csv":1,"perform":1}
,"--csv":{"<csv_file_name>":1}
,"<csv_file_name>":{"command":1}
,"specify":{"csv":1,"valid":1,"uarta":1}
,"allows":{"copy":1}
,"arbitrary":{"location":1}
,"location":{"linux":1,"excel":1,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-<board>":1,"linux_for_tegra\u002Fbootloader\u002Ft210ref\u002F<board>-<som>\u002Fextlinux.conf.emmc":1}
,"wish":{"enter":1,"generate":1}
,"$.\u002Fboard-to-uboot.py":{"<board>":1}
,"pinmux-config-<board>":{"later":1,"u-boot":1}
,"later":{"copy":1}
,"directly":{"excel":1}
,"answer":{"prompt":1}
,"asking":{"whether":1}
,"provide":{"name":1,"correct":1,"plugin":1}
,"prompted":{"device":1}
,"saved":{"location":1}
,"sure":{"file":1,"jetson":1}
,"correct":{"file":1,"maintainer":1,"pmic":1,"voltage":1,"colors":1}
,"mismatch":{"later":1}
,"perform":{"following":1,"secure":1,"writes\u002Freads":1}
,"actions":{"u-boot":1}
,"include\u002Fconfigs\u002Fjetson-p2371-2180.h":{"include\u002Fconfigs\u002F<board>":1}
,"include\u002Fconfigs\u002F<board>":{"edit":1}
,"edit":{"enabled":1,"<board>_defconfig":1,"arch\u002Farm\u002Fmach-tegra\u002Ftegra210\u002Fkconfig":1,"files":1,"board\u002F<vendor>\u002F<board>\u002Fmaintainers":1,"board\u002F<vendor>\u002F<board>\u002F<board>":1,"copy":1,".dtsi":1,"arch\u002Farm64\u002Fboot\u002Fdts\u002Fmakefile":1,"sysbootfile":1}
,"enabled":{"devices":1,"padctl":1,"lane":1,"portmap":1,"functional":1,"appropriately":1,"initially":1,"disabled":1,"verify":1,"normal":1}
,"devices":{"features":1,"parameters":1,"appear":1,"sensors":1,"systems":1}
,"features":{"<board>":1}
,"config_tegra_board_string":{"nvidia":1}
,"arch\u002Farm\u002Fdts\u002Ftegra210-p2371-2180.dts":{"arch\u002Farm\u002Fdts\u002Ftegra210-<board>":1}
,"arch\u002Farm\u002Fdts\u002Ftegra210-<board>":{".dts":1}
,".dts":{"edit":1,"appropriate":1,"<board>":1,"file":1,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-platforms\u002Fdirectory":1,"files":1}
,"parameters":{"(e.g":1}
,"(e.g":{"gpio":1}
,"gpio":{"irq":1,"{nvidia":1,"gpio":1,"configurations":1,"setting":1,"pin":1,"wake":1}
,"irq":{"ids)":1}
,"ids)":{"tegra210-<board>":1,"copied":1}
,"tegra210-<board>":{".dts":1,".dtb":1}
,"nodes":{"properties":1,"indicates":1}
,"properties":{"need":1,"note":1,"change":1,"changed":1,"patch":1,"nvidia":1}
,"added":{"removed":1}
,"removed":{"edited":1}
,"edited":{"note":1}
,"always":{"exact":1,"<tegra_padctl_pcie_lane_x4>":1}
,"exact":{"device":1}
,"schema":{"(bindings)":1}
,"(bindings)":{"represent":1}
,"follow":{"examples":1}
,"rather":{"linux":1,"p2371-2180":1,"u-boot":1}
,".dtb":{"arch\u002Farm\u002Fdts\u002Fmakefile":1}
,"arch\u002Farm\u002Fdts\u002Fmakefile":{"copy":1}
,"configs\u002Fp2371-2180_defconfig":{"configs\u002F<board>_defconfig":1}
,"configs\u002F<board>_defconfig":{"edit":1}
,"<board>_defconfig":{"refer":1}
,"arch\u002Farm\u002Fmach-tegra\u002Ftegra210\u002Fkconfig":{"add":1}
,"config":{"kconfig":1,"*\u002F[":1,"file":1}
,"kconfig":{"copy":1}
,"board\u002Fnvidia\u002Fp2371-2180\u002Fdirectory":{"board\u002F<vendor>\u002F<board>\u002F":1}
,"board\u002F<vendor>\u002F<board>\u002F":{"edit":1}
,"board\u002F<vendor>\u002F<board>\u002Fto":{"refer":1}
,"instances":{"p2371-2180":1}
,"board\u002F<vendor>\u002F<board>\u002Fmaintainers":{"provide":1}
,"maintainer":{"contact":1}
,"contact":{"information":1}
,"information":{"board":1,".dts":1,"furnished":1,"infringement":1,"previously":1}
,"board\u002F<vendor>\u002F<board>\u002F<board>":{"provide":1}
,"pmic":{"programming":1}
,"programming":{"board":1}
,"(pinmux-config-<board>":{".h)":1}
,".h)":{"board\u002F<vendor>\u002F<board>\u002Fdirectory":1}
,"board\u002F<vendor>\u002F<board>\u002Fdirectory":{"porting":1}
,"(the":{"device":1,"default":1}
,"tree)":{"platform":1}
,"distributed":{"configuration":1}
,"describe":{"platform\u2019s":1}
,"design":{"platform":1,"following":1,"guide":1,"eeprom":1,"specifications":1}
,"arch\u002Farm64\u002Fboot\u002Fdts\u002F":{"names":1}
,"form":{"tegra210-jetson-cv-base-<board>-<som>":1,"tegra210-jetson-cv-<function>-<board>-<som>-<version>":1}
,"tegra210-jetson-cv-base-<board>-<som>":{".dts":1}
,"refers":{"nvidia":1}
,"recommends":{"file":1}
,"included":{"describes":1,"file":1}
,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-jetson-cv-base-p2597-2180-a00.dts":{"device":1}
,".dtsi":{"files":1,"copy":1,"may":1,"file":1}
,"types":{"hardware":1,"supported":1}
,"configure":{"kernel":1}
,"work":{"platform":1,"easier":1,"cameras":1}
,"copies":{".dts":1,"correspond":1,"makes":1,".dtsi":1}
,"references":{"modify":1}
,"correspond":{"platform\u2019s":1}
,"procedure":{"guide":1}
,"process":{"copy":1,"platform":1,"preparation":1}
,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-<board>":{".dts":1}
,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-platforms\u002Fdirectory":{"copy":1}
,"tegra210-jetson-cv-<function>-<board>-<som>-<version>":{".dtsi":1}
,"arch\u002Farm64\u002Fboot\u002Fdts\u002Ftegra210-platforms\u002Ftegra210-<board>-<function>":{".dtsi":1}
,"makes":{"work":1,"warranties":1}
,"easier":{"edit":1}
,"copied":{"file":1}
,"remove":{"edit":1}
,"replace":{"content":1}
,"tegra210-<board>-gpio.dtsi":{"tegra210-<board>-pinmux.dtsi":1}
,"tegra210-<board>-pinmux.dtsi":{"content":1}
,"earlier":{"edit":1}
,"arch\u002Farm64\u002Fboot\u002Fdts\u002Fmakefile":{"add":1}
,"modeled":{"existing":1}
,"linux_for_tegra\u002Fbootloader\u002Ft210ref\u002Fp2371-2180\u002Fextlinux.conf.emmc":{"location":1}
,"linux_for_tegra\u002Fbootloader\u002Ft210ref\u002F<board>-<som>\u002Fextlinux.conf.emmc":{"copy":1}
,"dtb":{"following":1,"included":1,"selected":1,"partition":1,"execute":1,"<platform>":1}
,"linux_for_tegra\u002Fkernel\u002Fdtb\u002Ffor":{"rel-28":1}
,"rel-28":{"releases":1}
,"releases":{"provide":1}
,"plugin":{"manager":1}
,"manager":{"support":1}
,"along":{"kernel":1}
,"image":{"boot":1,"following":1,"flashing":1,"specific":1}
,"instead":{"kernel":1}
,"selected":{"dtb":1}
,"partition":{"modified":1,"target":1}
,"cboot":{"cboot":1,"passes":1}
,"passes":{"uboot":1,"kernel":1,"name":1}
,"uboot":{"turn":1,"execute":1}
,"turn":{"passes":1}
,"diluting":{"data":1}
,"flash":{"dtb":1,"uboot":1,"kernel":1,"build":1,"boardid":1}
,"execute":{"command":1}
,"sudo":{".\u002Fflash.sh":1}
,".\u002Fflash.sh":{"dtb":1,"lnx":1,"<platform>":1,"<board>-<som>":1}
,"<platform>":{"mmcblk0p1":1}
,"mmcblk0p1":{"flash":1,"optionally":1}
,"lnx":{"<platform>":1}
,"linux_for_tegra\u002Fkernel\u002F2":{"execute":1}
,"secure":{"copy":1}
,"reboot":{"copy":1}
,"linux_for_tegra\u002Fjetson-tx1.conf":{"linux_for_tegra\u002F<board>":1}
,"linux_for_tegra\u002F<board>":{".conf":1}
,".conf":{"edit":1,"refer":1,"modify":1}
,"sysbootfile":{"dtb_file":1}
,"dtb_file":{"<board>":1}
,"modifications":{"may":1}
,"regulator":{"vddio":1,"config\u002Fpinmux\u002Freview":1,"drivers":1}
,"vddio":{"sdmmc1":1}
,"sdmmc1":{"comes":1}
,"comes":{"pmu":1}
,"pmu":{"ldo2":1,"id=\u0022":1,"processor":1,"module":1,"regulator":1}
,"ldo2":{"section":1}
,"looks":{"regulators":1,"en_vdd_sd":1}
,"regulators":{"{ldo2":1}
,"{ldo2":{"{regulator-name":1}
,"{regulator-name":{"vddio-sdmmc1":1}
,"vddio-sdmmc1":{"change":1}
,"item":{"changed":1}
,"changed":{"pad":1,"detailed":1,"nvidia":1,"disable":1}
,"t210":{"defaults":1,"auto":1}
,"defaults":{"3.3":1}
,"3.3":{"unlike":1}
,"unlike":{"tegra":1}
,"models":{"t210":1}
,"auto":{"power":1}
,"detect":{"cells":1}
,"cells":{"i\u002Fo":1}
,"i\u002Fo":{"pads":1}
,"pads":{"powered":1}
,"powered":{"1.8":1,"used":1}
,"1.8":{"manually":1,"gpio":1}
,"manually":{"dts":1}
,"dts":{"1.8":1}
,"{nvidia":{"io-pad-init-voltage":1,"lanes":1}
,"io-pad-init-voltage":{"=<io_pad_voltage_1_8v>":1}
,"=<io_pad_voltage_1_8v>":{"gpio":1}
,"configurations":{"different":1}
,"different":{"hardware":1,"voltage":1}
,"modules":{"change":1,"interrupt":1}
,"setting":{"check":1,"according":1,"tegra":1}
,"check":{"related":1,"recovery":1,"platform":1}
,"related":{"device":1,"rails":1,"circuitry":1}
,"vdd":{"sdmmc":1}
,"sdmmc":{"controlled":1}
,"controlled":{"gpio":1,"xusb":1}
,"pin":{"(gpio_pz3)":1,"wifi_wake_ap)":1,"wifi":1,"names":1}
,"(gpio_pz3)":{"power":1}
,"part":{"tegra210-platforms\u002Ftegra210-jetson-cv-power-tree-p2597-2180-a00.dtsi":1}
,"tegra210-platforms\u002Ftegra210-jetson-cv-power-tree-p2597-2180-a00.dtsi":{"looks":1}
,"en_vdd_sd":{"regulator@4":1}
,"regulator@4":{"{gpio":1}
,"{gpio":{"=<&gpio":1}
,"=<&gpio":{"tegra_gpio":1}
,"tegra_gpio":{"change":1,"status":1,"gpio_active_low>":1}
,"according":{"platform":1}
,"circuit":{"interrupt":1}
,"interrupt":{"modules":1,"requests":1,"bcmdhd_wlan":1,"request":1}
,"requests":{"interrupt":1,"declared":1}
,"declared":{".dts":1}
,"tegra210-platforms\u002Ftegra210-comms-p2530-0930.dtsi":{"describes":1}
,"wifi":{"interrupt":1,"module":1}
,"bcmdhd_wlan":{"{compatible":1,"interrupt-parent":1}
,"{compatible":{"android":1}
,"android":{"bcmdhd_wlan":1}
,"interrupt-parent":{"=<&gpio>":1}
,"=<&gpio>":{"interrupts":1}
,"interrupts":{"=<tegra_gpio":1,"generated":1}
,"=<tegra_gpio":{"0x14>":1}
,"0x14>":{"wlan-pwr-gpio":1}
,"wlan-pwr-gpio":{"=<&gpio":1}
,"status":{"okay":1,"disabled":1}
,"okay":{"specifies":1}
,"specifies":{"gpio_ph02":1,"function":1,"usb":1,"pcie":1}
,"gpio_ph02":{"(same":1}
,"(same":{"pin":1}
,"wifi_wake_ap)":{"interrupt":1}
,"request":{"pin":1,"entering":1,"associated":1}
,"key":{"key":1,"defined":1,".dts":1,"special":1,"cannot":1}
,"defined":{"tegra210-platforms\u002Ftegra210-keys-p2530-0930.dtsi":1,"power":1}
,"tegra210-platforms\u002Ftegra210-keys-p2530-0930.dtsi":{"power":1}
,"{label":{"power":1}
,"gpios":{"=<&gpio":1,"necessary":1}
,"gpio_active_low>":{"linux":1}
,"=<key_power>":{"gpio-key":1}
,"gpio-key":{"wakeup":1}
,"wakeup":{"note":1}
,"meant":{"show":1}
,"show":{"define":1}
,"\u0027power":{"key":1}
,"special":{"key":1}
,"cannot":{"changed":1}
,"detailed":{"information":1}
,"documentation":{"documentation\u002Fdevicetree\u002Fbindings":1}
,"documentation\u002Fdevicetree\u002Fbindings":{"nvidia":1}
,"released":{"linux":1}
,"due":{"kernel":1}
,"24.x":{"(r24)":1}
,"(r24)":{"kernel":1}
,"3.10":{"release":1}
,"28.x":{"(r28)":1}
,"(r28)":{"kernel":1}
,"4.4":{"usb":1}
,"superspeed":{"ports":1,"port":1}
,"ports":{"used":1,"2.0":1,"controlled":1,"port":1,"without":1,"two":1,"mapped":1,"nvidia":1,"case":1,"usb_ss":1,"property":1}
,"used":{"implementation":1,"super-speed":1,"usb3.0":1,"standalone":1,"superspeed":1,"port":1,"usb":1,"pcie":1,"xusb":1,"m2.key":1,"system":1,"audio":1,"verify":1,"low":1}
,"implementation":{"lane":1}
,"sharing":{"pcie":1}
,"xusb":{"possible":1,"controller":1,"bits":1,"used":1,"indicates":1,"usb2-m2":1,"nvidia":1,"usb2-standalone":1}
,"possible":{"combinations":1,"exception":1,"mappings":1,"values":1,"verify":1}
,"combinations":{"usb":1}
,"shown":{"tables":1,"below":1}
,"tables":{"below":1}
,"below":{"jetson":1,"illustrates":1}
,"pex1":{"pex_r":1}
,"pex_r":{"pex2":1}
,"pex2":{"usb_s":1}
,"usb_s":{"pex0":1,"sata":1}
,"pex0":{"usb_s":1}
,"lanes":{"lane":1,"used":1,"available":1,"identifies":1,"property":1,"case":1,"uphy-lane-0":1,"otg-3":1,"uphy-lane-3":1,"sub-node":1,"uphy-lane-1":1,"uphy-lane-4":1,"verify":1}
,"(carrier)":{"pcie":1,"1x1":1}
,"1_0":{"pcie":1,"--usb_ss":1}
,"0_3":{"pcie":1}
,"0_2":{"pcie":1}
,"0_1":{"pcie":1}
,"0_0":{"usb_ss":1}
,"usb_ss":{"usb_ss":1,"on-jetson":1,"pcie":1,"sata":1,"case":1,"port":1,"enabled":1}
,"on-jetson":{"tx1":1}
,"lan":{"sata":1}
,"--usb_ss":{"pcie":1}
,"available":{"outputs":1,"xusb":1,"single":1,"example":1,"pcie":1,"autofocus":1}
,"outputs":{"jetson":1}
,"1x1":{"1x4":1,"1x1":1,"usb_ss":1,"change":1,"always":1}
,"1x4":{"1x1":1,"1x4":1,"2x1":1}
,"2x1":{"2x1":1,"customer":1}
,"contains":{"tegra":1,"processor":1}
,"ball":{"names":1}
,"determining":{"ball":1}
,"super-speed":{"connector":1,"lines":1,"port":1,"ports":1}
,"connector":{"pinmux":1,"usb":1,"possible":1,"nibble":1,"carrier":1,"default":1,"standalone":1,"nvidia":1,"(the":1,"m2.key":1,"usb3-m2":1,"supports":1,"usb3-m2standalone":1,"correctly":1,"(using":1,"bidirectional":1,"devices":1}
,"pins":{"example":1,"ball":1,"gpios":1,"pmu":1}
,"given":{"section":1}
,"5.1":{"jetson":1}
,"oem":{"product":1}
,"product":{"design":1,"names":1}
,"external":{"super-speed":1,"connector":1}
,"(dp":{"dn)":1}
,"dn)":{"usb":1}
,"lines":{"(tx":1,"require":1,"usb":1,"available":1,"m2.key":1,"connector":1,"m2.key)":1,"\u002Finclude\u002Fconfigs\u002Fjetson-tx1.h":1,"specify":1,"verify":1}
,"(tx":{"+-)":1}
,"+-)":{"linked":1}
,"linked":{"connector":1,"external":1}
,"exception":{"fixed":1}
,"fixed":{"on-board":1}
,"on-board":{"device":1}
,"connected":{"super-speed":1,"btb":1}
,"require":{"usb":1,"mapping":1}
,"compatibility":{"platform":1}
,"property":{"description":1,"value":1,"indicates":1,"otg-<n>":1,"uphy-lane-<n>":1,"<tegra_padctl_port_host_only>":1,"usb":1,"nvidia":1,"present":1,"usb3-m2":1,"usb3-standalone":1,"add":1}
,"xhci":{"nvidia":1,"replacing":1}
,"portmap":{"lists":1,"match":1,"control":1,"=<0x0e03>":1,"=<0x0e07>":1}
,"lists":{"ports":1,"documents":1}
,"controller":{"bit":1,"usb3":1,"pcie":1,"nvidia":1,"phy-names":1,"platform":1,"parent":1,"phys":1,"functional":1,"lowest":1}
,"bit":{"represents":1,"ports":1,"bits":1,"example":1}
,"bits":{"0-7":1,"8-15":1,"16-23":1}
,"0-7":{"represent":1}
,"lsb":{"bits":1,"matching":1}
,"8-15":{"represent":1}
,"16-23":{"represent":1}
,"hsic":{"ports":1}
,"<0x0e02>":{"represents":1}
,"padctl":{"nvidia":1}
,"ss_portmap":{"mapping":1,"super-speed":1,"=<0x21>":1,"=<0x321>":1,"superspeed":1,"=<0x7721>":1,"=<0x7221>":1,"nvidia":1}
,"por":{"lines":1}
,"single":{"connector":1,"usb":1}
,"nibble":{"represents":1}
,"starting":{"lsb":1}
,"matching":{"usb":1,"lane":1}
,"entered":{"enter":1}
,"<0x7730>":{"represents":1}
,"ssport0-usb2port0":{"ssport1-usb2port3":1}
,"ssport1-usb2port3":{"ssport2-disabled":1}
,"ssport2-disabled":{"ssport3-disabled":1}
,"ssport3-disabled":{"usb":1}
,"standalone":{"ports":1,"usb":1,"port":1}
,"valid":{"host":1,"usb":1,"values":1}
,"host":{"port":1,"mode":1}
,"two":{"usb":1,"new":1,"sub-nodes":1}
,"mapped":{"single":1,"example":1,"external":1}
,"role":{"may":1}
,"end-connector":{"mapping":1}
,"pex\u002Fhsio":{"pex\u002Fhsio":1,"lanes":1}
,"usb3.0":{"ports":1,"port":1,"port2":1}
,"lane_owner":{"nibble":1,"lane":1,"=<0xff56>":1,"=<0xf056>":1,"=<0xf356>":1}
,"0xf":{"port":1,"disable":1}
,"<0xff56>":{"represents":1,"becomes":1}
,"ssport0-lane6":{"ssport1-lane5":1}
,"ssport1-lane5":{"ssport2-not":1}
,"ssport2-not":{"ssport3-not":1}
,"ssport3-not":{"r24":1}
,"usecase":{"possible":1,"4\u002F5":1}
,"mappings":{"superspeed":1,"super-speed":1,"super":1}
,"(usb_ss1":{"pins":1}
,"e41":{"e42":1}
,"e42":{"h41":1}
,"h41":{"h42)":1}
,"h42)":{"usb":1}
,"b42":{"b43":1,"b43)":1}
,"b43":{"mapped":1}
,"default":{"configuration":1}
,"m2.key":{"pcie":1,"adding":1,"nvidia":1,"supports":1}
,"disabled":{"usb_ss":1,"pinctrl@7009f000\u002Fpinmux\u002Fpcie-m2":1,"usb2-m2":1,"usb2-standalone":1,"different":1,"low":1}
,"indicate":{"lane":1,"usb":1}
,"match":{"usb":1,"pcie-controller@1003000":1}
,"sufficient":{"case":1}
,"matched":{"usb":1}
,"<0x7721>":{"<0x7321>":1,"<0x7221>":1}
,"<0x7321>":{"nvidia":1}
,"control":{"super-speed":1,"config":1,"superspeed":1,"exiting":1,"interface":1}
,"replacing":{"<0x0e03>":1}
,"<0x0e03>":{"<0x0e07>":1}
,"<0x0e07>":{"nvidia":1}
,"owner":{"lane":1}
,"becomes":{"<0xf056>":1,"<0xf356>":1}
,"<0xf056>":{"nvidia":1}
,"lane-map":{"property":1,"=<0x14>":1,"=<0x4>":1,"=<0x12>":1,"=<0x11>":1}
,"indicates":{"pex":1,"lane":1,"port":1,"maximum":1}
,"configured":{"lane":1}
,"(pex1)":{"usb":1}
,"map":{"modified":1}
,"<0x14>":{"<0x4>":1,"<0x11>":1}
,"<0x4>":{"overall":1}
,"overall":{"device":1}
,"patch":{"case":1,"above":1}
,"follows":{"pcie-controller":1,"pinctrl@7009f000":1,"flash":1}
,"pcie-controller":{"-nvidia":1,"{-nvidia":1,"=<1>":1,"=<0>":1}
,"-nvidia":{"lane-map":1,"ss_portmap":1,"lane_owner":1,"portmap":1}
,"=<0x14>":{"nvidia":1}
,"=<0x4>":{"xusb_pad_ctl":1,"xusb@70090000":1}
,"xusb_pad_ctl":{"xusb_padctl":1}
,"xusb_padctl":{"{\u002F*put":1}
,"{\u002F*put":{"common":1}
,"common":{"control":1}
,"*\u002F[":{"-nvidia":1}
,"=<0x21>":{"-nvidia":1}
,"=<0xff56>":{"\u002F*use":1}
,"\u002F*use":{"0xf":1}
,"disable":{"lane":1,"pcie-m2":1,"pcie":1}
,"assign":{"*\u002F-nvidia":1,"*\u002F+":1,"*\u002Fplatform":1}
,"*\u002F-nvidia":{"lane-map":1}
,"=<0x321>":{"nvidia":1}
,"=<0xf056>":{"\u002F*use":1}
,"*\u002F+":{"nvidia":1}
,"xusb@70090000":{"{platform":1,"-nvidia":1,"phys":1}
,"{platform":{"adaptation":1}
,"=<0x0e03>":{"nvidia":1}
,"=<0x0e07>":{"r24":1,"nvidia":1}
,"4\u002F5":{"possible":1}
,"(pex1":{"pins":1}
,"g42":{"g43":1}
,"g43":{"d42":1}
,"d42":{"d43)":1}
,"d43)":{"pcie":1}
,"<0x7221>":{"nvidia":1}
,"<0xf356>":{"nvidia":1}
,"usb_ss1":{"usb":1}
,"<0x11>":{"overall":1}
,"{-nvidia":{"lane-map":1,"lanes":1}
,"=<0x12>":{"xusb_pad_ctl":1}
,"=<0x7721>":{"-nvidia":1}
,"*\u002Fplatform":{"adaptation":1}
,"=<0x7221>":{"nvidia":1}
,"=<0xf356>":{"\u002F*use":1}
,"=<0x11>":{"xusb@70090000":1}
,"common_padctl":{"=<&xusb_pad_ctl>":1}
,"=<&xusb_pad_ctl>":{"r28":1}
,"pinctrl@7009f000\u002Fpinmux":{"nvidia":1,"create":1}
,"identifies":{"lane":1,"phy":1}
,"otg-<n>":{"<n>":1}
,"<n>":{"number":1,"lane":1}
,"3.0\u002Fpcie\u002Fsata":{"ports":1}
,"uphy-lane-<n>":{"<n>":1}
,"function":{"specifies":1,"running":1,"nvidia":1,"xusb":1,"usb3":1,"pcie":1}
,"values":{"include":1,"board":1,"nvtboot":1}
,"usb3":{"indicates":1,"usb3-m2":1,"nvidia":1,"usb3-standalone":1}
,"port-cap":{"usb":1,"nvidia":1,"=<tegra_padctl_port_host_only>":1}
,"2.0\u002F3.0":{"port":1}
,"mode":{"property":1,"nvidia":1,"works":1,"implemented":1,"used":1,"verify":1,"enabled":1,"hdmi":1,"system":1,"capture":1,"rails":1,"nvtest":1}
,"<tegra_padctl_port_host_only>":{"nvidia":1}
,"usb3-port":{"property":1,"platform":1,"=<2>":1}
,"bound":{"lane":1}
,"usb2-map":{"property":1,"nvidia":1,"=<3>":1,"match":1}
,"pcie-lane-select":{"specifies":1,"=<tegra_padctl_pcie_lane_x1>":1,"pcie":1,"=<tegra_padctl_pcie_lane_x4>":1}
,"phys":{"identifies":1,"used":1,"phy-names":1,"add":1,"=<&tegra_padctl_uphy":1,"lowest":1}
,"handles":{"usb":1}
,"phy-names":{"identifies":1,"match":1,"add":1,"utmi-2":1}
,"sequence":{"phys":1,"starts":1,"meets":1,"power":1}
,"pcie-controller@1003000":{"nvidia":1}
,"num-lanes":{"property":1}
,"sub-node":{"pcie":1,"usb":1,"nvidia":1,"standalone":1,"case":1}
,"parent":{"node":1}
,"node":{"example":1,"disable":1,"create":1,"pcie":1}
,"pci@1,0":{"pci@2,0":1}
,"pci@2,0":{"pci@3,0":1}
,"pci@3,0":{"nodes":1}
,"maximum":{"link":1,"extent":1}
,"link":{"width":1,"(connector":1,"accessible":1,"near":1}
,"width":{"root":1}
,"controller-0":{"0x4for":1}
,"0x4for":{"cases":1}
,"cases":{"controller-1":1}
,"controller-1":{"0x1":1}
,"0x1":{"supported":1}
,"(ball":{"names":1}
,"b43)":{"mapped":1}
,"m2.key)":{"pcie":1}
,"pcie-m2":{"sub":1,"{nvidia":1}
,"sub":{"node":1}
,"adding":{"status":1}
,"pinctrl@7009f000\u002Fpinmux\u002Fpcie-m2":{"sub":1}
,"sub-nodes":{"pinctrl@7009f000\u002Fpinmux":1,"usb2-m2":1,"usb":1,"usb2-standalone":1}
,"usb2-m2":{"represent":1,"sub-node":1,"nvidia":1,"usb3-m2":1}
,"usb3-m2":{"instance":1,"sub-node":1,"nvidia":1,"sub-nodes":1,"indicate":1}
,"instance":{"usb3.0":1}
,"uphy-lane-0":{"usb3-m2":1,"nvidia":1}
,"otg-3":{"usb2-m2":1,"nvidia":1,"usb2-standalone":1}
,"=<tegra_padctl_port_host_only>":{"usb2-m2":1,"usb3-m2":1,"xusb@70090000":1,"usb2-standalone":1,"platform":1}
,"=<2>":{"usb3-m2.nvidia":1,"nvidia":1,"usb3-standalone":1}
,"usb3-m2.nvidia":{"ss_portmap":1}
,"usb2-mapportmap":{"match":1}
,"=<3>":{"phys":1,"nvidia":1}
,"<&tegra_padctl_uphy":{"tegra_padctl_uphy_utmi_p":1,"tegra_padctl_uphy_usb3_p":1}
,"tegra_padctl_uphy_utmi_p":{"(3)>":1,"(2)>":1,"(1)>":1,"(0)>":1}
,"(3)>":{"usb":1,"<&tegra_padctl_uphy":1}
,"tegra_padctl_uphy_usb3_p":{"(2)>":1,"(1)>":1,"(0)>":1}
,"(2)>":{"usb3.0":1,"platform":1,"phy-names":1,"<&tegra_padctl_uphy":1}
,"port2":{"phy-names":1}
,"utmi-3":{"usb":1,"usb3-2":1}
,"usb3-2":{"usb":1,"r28":1,"considerations":1}
,"pinctrl@7009f000":{"pinmux":1}
,"=<1>":{"nvidia":1}
,"=<tegra_padctl_pcie_lane_x1>":{"status":1}
,"=<&tegra_padctl_uphy":{"tegra_padctl_uphy_utmi_p":1}
,"(1)>":{"<&tegra_padctl_uphy":1}
,"(0)>":{"<&tegra_padctl_uphy":1}
,"utmi-2":{"usb3-1":1}
,"usb3-1":{"utmi-1":1}
,"utmi-1":{"usb3-0":1}
,"usb3-0":{"utmi-0":1}
,"utmi-0":{"utmi-3":1}
,"super":{"speed":1}
,"speed":{"ports":1}
,"usb2-standalone":{"represent":1,"sub":1,"nvidia":1,"usb3-standalone":1}
,"usb3-standalone":{"instance":1,"sub-node":1,"nvidia":1,"sub-nodes":1,"indicate":1}
,"uphy-lane-3":{"usb3-standalone":1,"uphy-lane-4":1,"nvidia":1}
,"uphy-lane-1":{"uphy-lane-2":1}
,"uphy-lane-2":{"uphy-lane-3":1}
,"uphy-lane-4":{"uphy-lane-4":1,"nvidia":1}
,"usb3-m2standalone":{"sub-node":1}
,"<tegra_padctl_pcie_lane_x4>":{"controller":1}
,"above":{"case":1}
,"look":{"pinctrl@7009f000":1,"excessive":1}
,"=<0>":{"nvidia":1}
,"=<tegra_padctl_pcie_lane_x4>":{"pcie-m2":1}
,"recommendations":{"consider":1}
,"consider":{"porting":1}
,"build":{"image":1}
,"specific":{"board":1}
,"$sudo":{".\u002Fflash.sh":1}
,"<board>-<som>":{"mmcblk0p1":1}
,"boardid":{"design":1,"either":1,"xml":1}
,"eeprom":{"boardid":1,"flashing":1,"value":1}
,"either":{"passed":1}
,"passed":{"using":1}
,"xml":{"file":1,"version=\u0022":1}
,"during":{"flashing":1,"deep":1}
,"provided":{"otherwise":1,"nvidia":1}
,"board_config_p2597-devkit.xml":{"shown":1}
,"illustrates":{"xml":1}
,"version=\u0022":{"1.0":1}
,"1.0":{"<!--nvidia":1}
,"<!--nvidia":{"tegra":1}
,"info":{"configuration":1}
,"-->":{"<board_configs>":1}
,"<board_configs>":{"<board":1}
,"<board":{"type=\u0022":1}
,"type=\u0022":{"proc":1,"display":1,"pmu":1}
,"proc":{"id=\u0022":1,"display":1}
,"id=\u0022":{"2180":1,"0000":1}
,"sku=\u0022":{"1000":1,"0000":1}
,"1000":{"fab=\u0022":1}
,"fab=\u0022":{"<board":1}
,"0000":{"sku=\u0022":1,"\u0022\u002F>":1,"<\u002Fboard_configs>":1}
,"\u0022\u002F>":{"<board":1}
,"<\u002Fboard_configs>":{"platform":1}
,"p2371-2180-devkit.conf":{"passes":1}
,"bcffile=\u0022":{"bootloader\u002F${target_board}\u002Fcfg\u002Fboard_config_p2597-devkit.xml":1}
,"bootloader\u002F${target_board}\u002Fcfg\u002Fboard_config_p2597-devkit.xml":{"file":1}
,"processor":{"module":1,"pmu":1}
,"(type=\u0022":{"proc":1,"display":1,"pmu":1}
,"management":{"unit":1}
,"unit":{"(type=\u0022":1}
,"development":{"kit":1}
,"tag\u2019s":{"property":1}
,"list":{"valid":1}
,"nvtboot":{"change":1}
,"uarta":{"linux_for_tegra\u002F<board>":1,"define":1}
,"odmdata":{"assignment":1}
,"assignment":{"odmdata=0x60084000":1,"debug_uartport=lsport":1}
,"odmdata=0x60084000":{"u-boot":1}
,"\u002Finclude\u002Fconfigs\u002Fjetson-tx1.h":{"define":1}
,"config_tegra_enable_uartd":{"define":1}
,"config_sys_ns16550_com1":{"nv_pa_apb_uartd_base":1,"nv_pa_apb_uarta_base":1}
,"nv_pa_apb_uartd_base":{"modify":1}
,"config_tegra_enable_uarta":{"define":1}
,"nv_pa_apb_uarta_base":{"kernel":1}
,"debug_uartport":{"assignment":1}
,"debug_uartport=lsport":{"hardware":1}
,"provides":{"checklist":1}
,"btb":{"connector":1}
,"correctly":{"securely":1,"unknown":1}
,"securely":{"verify":1}
,"supplies":{"shorted":1,"initial":1,"required":1}
,"shorted":{"ground":1}
,"ground":{"power":1}
,"vdd_in":{"carrier":1}
,"range":{"verify":1}
,"carrier_wr_on":{"high":1}
,"high":{"power":1}
,"turned":{"verify":1}
,"force":{"recovery":1}
,"recovery":{"initial":1,"(device":1,"mode":1}
,"flashed":{"tegraflash":1}
,"tegraflash":{"verify":1,"uart":1}
,"tegraboot":{"u-boot":1}
,"run":{"completion":1}
,"completion":{"checking":1}
,"checking":{"log":1,"lanes":1,"diff":1}
,"log":{"output":1}
,"output":{"verify":1,"recommended":1,"kbd":1}
,"runs":{"desktop":1}
,"desktop":{"verify":1,"kernel":1}
,"uarts":{"intended":1}
,"intended":{"debugging":1,"peripheral":1}
,"debugging":{"enabled":1,"guide":1}
,"appropriately":{"verify":1}
,"initially":{"verify":1}
,"controllable":{"supply":1}
,"supply":{"enabled":1}
,"voltage":{"levels":1,"hardware":1}
,"levels":{"applicable":1}
,"applicable":{"verify":1}
,"starts":{"carrier_pwr_on":1}
,"carrier_pwr_on":{"signal":1}
,"signal":{"asserted":1,"quality":1,"edges":1}
,"asserted":{"power":1}
,"capture":{"cpu":1,"usb0_d":1,"usb2_d":1,"hdmi":1,"works":1,"signals":1}
,"cpu":{"pwr":1,"jtag":1,"power":1}
,"pwr":{"request":1}
,"entering":{"exiting":1}
,"exiting":{"suspend":1,"deep":1}
,"suspend":{"(lp1)":1}
,"(lp1)":{"deep":1,"capture":1,"verify":1}
,"deep":{"sleep":1}
,"sleep":{"(lp0)":1}
,"(lp0)":{"ensure":1,"verify":1,"platform":1,"capture":1,"suspend":1}
,"associated":{"power":1,"display":1,"imager":1,"2017":1}
,"rail":{"sequence":1,"check":1}
,"meets":{"tegra":1,"manufacturer\u0027s":1}
,"sheet":{"requirements":1}
,"requirements":{"verify":1,"(correct":1,"tegra":1,"met":1,"probe":1}
,"rails":{"deep":1,"back":1,"powered":1,"associated":1}
,"back":{"correct":1}
,"usb0":{"supports":1,"device":1,"usb1":1,"device\u002Fhost":1}
,"(device":{"mode)":1}
,"mode)":{"verify":1}
,"works":{"intended":1,"1080p":1,"properly":1,"wakes":1,"implemented":1,"cameras":1}
,"peripheral":{"types":1}
,"usb1":{"usb2":1}
,"usb2":{"host":1}
,"implemented":{"verify":1,"pex":1,"sata":1}
,"device\u002Fhost":{"detection":1}
,"lowest":{"power":1}
,"low":{"power":1}
,"avdd_usb":{"avdd_pll_utmip":1}
,"avdd_pll_utmip":{"during":1}
,"usb0_d":{"+\u002Fd-signals":1}
,"+\u002Fd-signals":{"ends":1}
,"(connector":{"test":1}
,"test":{"points":1,"fixture":1}
,"points":{"near":1,"access":1,"verify":1}
,"near":{"tegra)":1,"btb":1,"tegra":1,"panel":1}
,"tegra)":{"capture":1,"using":1}
,"usb2_d":{"+\u002Fd-signals":1}
,"usb-if":{"procedures":1}
,"signals":{"meet":1,"connector":1,"receiver":1,"probed":1,"near":1}
,"meet":{"requirements":1}
,"(correct":{"eye":1}
,"eye":{"height\u002Fwidth":1,"diagram":1}
,"height\u002Fwidth":{"etc.)":1}
,"etc.)":{"usb":1,"consult":1}
,"tuning":{"guide":1}
,"adjust":{"settings":1}
,"settings":{"until":1}
,"until":{"requirements":1}
,"met":{"usb":1,"audio":1}
,"interface":{"lowest":1,"verify":1,"used":1,"able":1,"writes\u002Freads":1}
,"hdmi-compatible":{"display":1}
,"1080p":{"verify":1}
,"detected":{"properly":1}
,"properly":{"(hpd)":1,"speakers":1,"sound":1,"verify":1,"cameras":1,"implemented":1}
,"(hpd)":{"verify":1}
,"reads":{"writes":1}
,"writes":{"display":1,"i2c":1,"variety":1}
,"ddc":{"interface":1}
,"(using":{"appropriate":1}
,"fixture":{"termination)":1}
,"termination)":{"verify":1}
,"quality":{"acceptable":1,"fitness":1}
,"acceptable":{"(meets":1,"look":1,"probed":1,"including":1}
,"(meets":{"eye":1}
,"diagram":{"etc.)":1}
,"consult":{"tegra":1}
,"details":{"hdmi":1,"verify)":1}
,"codec":{"platform":1,"lowest":1,"microphone":1}
,"playback":{"works":1}
,"speakers":{"headphones":1,"headphones\u002Fheadset":1}
,"headphones":{"headset":1}
,"headset":{"verify":1}
,"sound":{"recorded":1}
,"recorded":{"microphone\u002Fheadset":1}
,"microphone\u002Fheadset":{"supported":1}
,"tones":{"voice":1}
,"voice":{"heard":1}
,"heard":{"speakers":1}
,"headphones\u002Fheadset":{"verify":1}
,"enters":{"low":1}
,"receiver":{"end":1}
,"end":{"link":1,"(socket":1}
,"accessible":{"i2s":1}
,"i2s":{"i\u002Fft":1}
,"i\u002Fft":{"used":1}
,"excessive":{"over\u002Fundershoot":1}
,"over\u002Fundershoot":{"glitches":1}
,"glitches":{"signal":1}
,"edges":{"uart":1,"card":1,"abnormal":1,"sata":1,"embedded":1,"platform":1,"look":1,"software":1}
,"tx\u002Frx\u002Fcts\u002Frts":{"connects":1}
,"connects":{"device":1}
,"rx\u002Ftx\u002Frts\u002Fcts":{"uart":1}
,"proper":{"connectivity":1}
,"connectivity":{"setting":1,"checking":1}
,"necessary":{"debug":1}
,"debug":{"verify":1}
,"basic":{"commands":1}
,"operate":{"properly":1}
,"variety":{"cards":1}
,"cards":{"verify":1}
,"insertion":{"detection":1}
,"wakes":{"system":1}
,"write":{"protect":1}
,"protect":{"works":1}
,"state":{"verify":1,"pex":1,"deep":1}
,"probed":{"receiver":1,"btb":1}
,"(socket":{"test":1}
,"bidirectional":{"signals)":1}
,"signals)":{"look":1}
,"abnormal":{"clock":1}
,"clock":{"duty":1}
,"duty":{"cycle":1}
,"cycle":{"sensors":1}
,"addresses":{"i2c":1}
,"unknown":{"ghost":1}
,"ghost":{"devices":1}
,"rise":{"times":1}
,"times":{"signals":1}
,"reads\u002Fwrites":{"i2c":1}
,"spi":{"touch":1}
,"(reading":{"device":1}
,"similar":{"register":1}
,"register":{"successful)":1}
,"successful)":{"platform":1}
,"functionality":{"touch":1}
,"interfaces":{"transition":1}
,"transition":{"lowest":1}
,"diff":{"lines":1}
,"able":{"perform":1}
,"writes\u002Freads":{"display":1,"work":1}
,"shows":{"correct":1}
,"colors":{"verify":1}
,"display\u2019s":{"backlight":1}
,"backlight":{"enabled":1,"brightness":1,"disabled":1}
,"normal":{"display":1}
,"brightness":{"adjusted":1}
,"adjusted":{"properly":1}
,"(and":{"display":1}
,"bridge)":{"transitions":1}
,"transitions":{"lowest":1}
,"power-on\u002Foff":{"sequencing":1}
,"sequencing":{"rails":1}
,"manufacturer\u0027s":{"requirements":1}
,"dsi":{"lvds":1,"debugging":1}
,"lvds":{"edp":1}
,"edp":{"timing":1,"signals":1,"gpu":1,"system":1,"(contain":1}
,"timing":{"(see":1}
,"(see":{"tegra":1}
,"verify)":{"probe":1}
,"probe":{"dsi":1,"mclk":1}
,"panel":{"driver":1}
,"connector\u002Ftest":{"points":1}
,"access":{"driver":1}
,"cameras":{"verify":1,"related":1}
,"preview":{"displays":1}
,"video":{"capture":1}
,"flashes":{"operate":1}
,"autofocus":{"mechanism":1}
,"mechanism":{"functions":1}
,"functions":{"properly":1}
,"privacy":{"led":1}
,"led":{"operates":1}
,"operates":{"properly":1}
,"circuitry":{"enter":1}
,"mclk":{"output":1}
,"recommended":{"test":1}
,"bct":{"verify":1,"full-speed":1}
,"operation":{"emmc":1}
,"diagnostic":{"tool":1}
,"schematics":{"component":1}
,"component":{"data":1}
,"sheets":{"verify":1}
,"review":{"board":1,"pinmux":1}
,"reset":{"sequence":1}
,"nvtest":{"(tegra":1}
,"(tegra":{"mods)":1}
,"mods)":{"ddr":1}
,"ddr":{"emmc":1}
,"jtag":{"connection":1}
,"connection":{"check":1,"board":1}
,"kbd":{"connection":1}
,"config\u002Fpmic":{"regulator":1}
,"config\u002Fpinmux\u002Freview":{"device":1}
,"support\u002Fconfig":{"boot":1}
,"scripts":{"(bootcmd)":1}
,"(bootcmd)":{"boot":1}
,"custom":{"desktop":1}
,"wake":{"pins":1}
,"drivers":{"display\u002Fhdmi":1}
,"display\u002Fhdmi":{"audio":1}
,"microphone":{"speaker":1}
,"speaker":{"usb":1}
,"thermal":{"sensor":1}
,"emc":{"dfs":1}
,"dfs":{"table":1}
,"ethernet":{"sata":1}
,"cpu\u002Fcore\u002Fgpu":{"dvfs":1}
,"dvfs":{"emc":1}
,"cpu\u002Fcore":{"edp":1}
,"gpu":{"edp":1}
,"(contain":{"current":1}
,"current":{"monitor":1}
,"monitor":{"&voltage":1}
,"&voltage":{"comparator)":1}
,"comparator)":{"power":1}
,"lp0":{"(optional)":1}
,"down":{"(lp2)":1}
,"(lp2)":{"bct":1}
,"full-speed":{"www.nvidia.com":1}
,"www.nvidia.com":{"notice":1}
,"notice":{"nvidia":1,"publication":1}
,"specifications":{"reference":1,"mentioned":1}
,"drawings":{"diagnostics":1}
,"diagnostics":{"lists":1}
,"documents":{"(together":1}
,"(together":{"separately":1}
,"separately":{"materials":1}
,"materials":{"provided":1,"express":1}
,"warranties":{"express":1,"including":1}
,"express":{"implied":1,"written":1}
,"implied":{"statutory":1,"conditions":1,"warranty":1}
,"statutory":{"otherwise":1}
,"respect":{"materials":1}
,"conditions":{"representations":1}
,"representations":{"warranties":1}
,"warranty":{"condition":1}
,"condition":{"title":1}
,"title":{"merchantability":1}
,"merchantability":{"satisfactory":1}
,"satisfactory":{"quality":1}
,"fitness":{"particular":1}
,"particular":{"purpose":1}
,"purpose":{"on-infringement":1}
,"on-infringement":{"hereby":1}
,"hereby":{"excluded":1}
,"excluded":{"maximum":1}
,"extent":{"permitted":1}
,"permitted":{"law":1}
,"law":{"information":1}
,"furnished":{"believed":1}
,"believed":{"accurate":1}
,"accurate":{"reliable":1}
,"reliable":{"however":1}
,"however":{"nvidia":1}
,"assumes":{"responsibility":1}
,"responsibility":{"consequences":1}
,"consequences":{"information":1}
,"infringement":{"patents":1}
,"patents":{"third":1}
,"third":{"parties":1}
,"parties":{"may":1}
,"result":{"license":1}
,"license":{"granted":1}
,"granted":{"implication":1}
,"implication":{"otherwise":1}
,"patent":{"patent":1,"nvidia":1}
,"mentioned":{"publication":1}
,"publication":{"subject":1,"supersedes":1}
,"subject":{"change":1}
,"supersedes":{"replaces":1}
,"replaces":{"information":1}
,"previously":{"supplied":1}
,"supplied":{"nvidia":1}
,"products":{"authorized":1}
,"authorized":{"critical":1}
,"critical":{"components":1}
,"components":{"life":1}
,"life":{"support":1}
,"systems":{"without":1}
,"written":{"approval":1}
,"approval":{"nvidia":1}
,"trademarks":{"nvidia":1,"registered":1,"respective":1}
,"logo":{"tegra":1}
,"registered":{"trademarks":1}
,"united":{"states":1}
,"states":{"countries":1}
,"countries":{"company":1}
,"company":{"product":1}
,"respective":{"companies":1}
,"companies":{"associated":1}
}
;Search.control.loadWordPairs(pairs);
