var pairs =
{
"tx2":{"gcc":1,"cpu":1}
,"gcc":{"compile":1}
,"compile":{"time":1}
,"time":{"optimization":1}
,"optimization":{"best":1,"options":1}
,"best":{"practices":1}
,"practices":{"additional":1}
,"additional":{"compilation":1}
,"compilation":{"flags":1}
,"flags":{"needed":1}
,"needed":{"produce":1}
,"produce":{"optimized":1}
,"optimized":{"code":1}
,"code":{"jetson":1}
,"jetson":{"tx2":1}
,"cpu":{"rchitecture":1}
,"rchitecture":{"cortex-a57":1}
,"cortex-a57":{"denver":1}
,"denver":{"include":1}
,"include":{"-ffast-math":1}
,"-ffast-math":{"-flto":1}
,"-flto":{"-march=armv8-a":1}
,"-march=armv8-a":{"crypto":1}
,"crypto":{"-mcpu=cortex-a57":1,"application":1}
,"-mcpu=cortex-a57":{"crypto":1}
,"application":{"dependent":1}
,"dependent":{"optimization":1}
,"options":{"nclud":1}
,"nclud":{"-funroll-loops":1}
,"-funroll-loops":{"-fvect-cost-model=unlimited":1}
}
;Search.control.loadWordPairs(pairs);
