var pairs =
{
"tx2":{"configuring":1,"devices":1,"pinmux":1,"developer":1}
,"configuring":{"pinmux":1}
,"pinmux":{"gpio":1,"pad":1,"spreadsheet":1,"settings":1,"configuration":1,"compatibility":1,"table":1,"dts2cfg":1,"arguments":1,"unless":1,"values":1,"gpio_dts":1}
,"gpio":{"pad":1,"files":1,"address":1,"version":1}
,"pad":{"pinmux":1,"configuration":1,"nfiguration":1,"dts":1,"file":1,"attributes":1,"info":1}
,"configuration":{"file":1,"information":1,"pinmux":1,"tx2":1,"process":1,"jetson":1}
,"file":{"provide":1,"dsheet":1,"file":1,"generate":1,"open":1,"button":1,"pinmux":1,"using":1,"readable":1,".cfg":1,"gpio_address_file":1,"por_val_file":1,"mandatory_pinmux_file":1,"pinmux_dts":1,"gpio":1,"printed":1,"redirect":1,"example":1,"default":1,"cfg":1,"pad_dts":1,"pads":1}
,"provide":{"pinmux":1}
,"information":{"jetson":1,"pinmux":1,"--pinmux":1,"--pad":1}
,"jetson":{"tx2":1,"release":1,"developer":1,"tx1\u002Ftx2":1}
,"devices":{"board":1}
,"board":{"chip":1,"name":1}
,"chip":{"configuration":1}
,"spreadsheet":{"provided":1,"available":1,"changes":1,"microsoft":1,"uses":1}
,"provided":{"show":1}
,"show":{"locations":1}
,"locations":{"default":1}
,"default":{"pinmux":1,"value":1,"script":1,"locatio":1}
,"settings":{"efine":1,"source":1,"perform":1}
,"efine":{"pinmux":1}
,"source":{"code":1,"file":1}
,"code":{"device":1}
,"device":{"tree":1}
,"tree":{"spreadsheet":1,"file":1,"source":1}
,"available":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1,"linux_for_tegra\u002Fkernel\u002Fpinmux\u002Fto":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"information":1}
,"nfiguration":{"files":1}
,"files":{"refer":1,"current":1,"windows":1,"cfg":1}
,"refer":{"mb1":1}
,"mb1":{"platform":1}
,"platform":{"configuration":1}
,"process":{"pinmux":1}
,"developer":{"kit":1}
,"kit":{"baseboard":1,"pinmux":1}
,"baseboard":{"expansion":1,"configure":1}
,"expansion":{"header":1,"module":1}
,"header":{"config":1}
,"config":{"ured":1}
,"ured":{"special-function":1}
,"special-function":{"i\u002Fo":1}
,"i\u002Fo":{"jetson":1}
,"release":{"onfigures":1}
,"onfigures":{"pins":1}
,"pins":{"differently":1}
,"differently":{"primarily":1}
,"primarily":{"gpi":1}
,"gpi":{"using":1}
,"using":{"jetson":1,"dts2cfg":1,"command":1}
,"module":{"attac":1}
,"attac":{"hed":1}
,"hed":{"review":1}
,"review":{"jetson":1}
,"tx1\u002Ftx2":{"developer":1}
,"compatibility":{"baseboard":1}
,"configure":{"pinmux":1}
,"perform":{"followin":1}
,"followin":{"tasks":1}
,"tasks":{"modify":1}
,"modify":{"pinmu":1}
,"pinmu":{"spreadsheet":1}
,"changes":{"configurable":1}
,"configurable":{"fields":1}
,"fields":{"generate":1,"error":1}
,"generate":{"file":1,"cfg":1,"dev":1}
,"dsheet":{"generate":1}
,"cfg":{"file":1,"format":1}
,"open":{"pinmux":1}
,"microsoft":{"excel":1}
,"excel":{"click":1}
,"click":{"generate":1,"response":1}
,"button":{"response":1}
,"response":{"generate":1,"board":1}
,"dev":{"ice":1}
,"ice":{"tree":1}
,"table":{"prompt":1}
,"prompt":{"click":1,"specify":1}
,"name":{"prompt":1,"board":1,"specified":1}
,"specify":{"board":1}
,"specified":{"spreadsheet":1}
,"uses":{"default":1}
,"value":{"fields":1}
,"error":{"free":1}
,"free":{"script":1}
,"script":{"displays":1,"verify":1,"assumes":1}
,"displays":{"message":1}
,"message":{"indicating":1}
,"indicating":{"uccess":1}
,"uccess":{"creates":1}
,"creates":{"dtsi":1}
,"dtsi":{"files":1}
,"current":{"working":1}
,"working":{"directory":1}
,"directory":{"example":1}
,"example":{"tegra18x-p3310-1000-a03-cvm-config-pinmux.dtsi":1,"python":1}
,"tegra18x-p3310-1000-a03-cvm-config-pinmux.dtsi":{"tegra18x-p3310-1000-a03-cvm-config-gpio-default.dt":1}
,"tegra18x-p3310-1000-a03-cvm-config-gpio-default.dt":{"tegra18x-p3310-1000-a03-cvm-config-padvoltage-defa":1}
,"tegra18x-p3310-1000-a03-cvm-config-padvoltage-defa":{"ult.dtsi":1}
,"ult.dtsi":{"copy":1,"\u005C1.0":1}
,"copy":{"files":1,"configuration":1}
,"windows":{"linux":1}
,"linux":{"system":1}
,"system":{"generat":1}
,"generat":{"ing":1}
,"ing":{"onfig":1,"output":1}
,"onfig":{"uration":1}
,"uration":{"file":1}
,"dts2cfg":{"note":1,"tool":1}
,"note":{"dos2unix":1}
,"dos2unix":{"command":1}
,"command":{"convert":1,"following":1,"line":1,"options":1}
,"convert":{".dts":1,"pinmux":1,"pad":1}
,".dts":{"file":1}
,"readable":{"script":1}
,"verify":{"blank":1}
,"blank":{"lines":1}
,"lines":{"end":1}
,"end":{"addres":1}
,"addres":{"info":1}
,"info":{"file":1}
,"tool":{"converts":1,"available":1,"convert":1}
,"converts":{"pinmux":1}
,"dts":{"file":1}
,".cfg":{"format":1,"file":1}
,"format":{"tool":1,"command":1,"pinmux-dts2cfg.py":1,"using":1}
,"linux_for_tegra\u002Fkernel\u002Fpinmux\u002Fto":{"convert":1}
,"following":{"options":1}
,"options":{"python":1,"follows":1,"description":1,"arguments":1}
,"python":{"pinmux-dts2cfg.py":1}
,"pinmux-dts2cfg.py":{"[--pinmux]":1,"\u005C--pinmux":1,"tool":1,"--pad":1,"\u005C--pad":1}
,"[--pinmux]":{"<address_file":1}
,"<address_file":{"<gpio_address_file":1}
,"<gpio_address_file":{"<por_val_file":1}
,"<por_val_file":{"<mandatory_pinmux_file":1}
,"<mandatory_pinmux_file":{"<pinmux_dts":1}
,"<pinmux_dts":{"_file>":1}
,"_file>":{"<gpio_dts":1,"<version":1,"<version>":1}
,"<gpio_dts":{"_file>":1}
,"<version":{"[--help]":1}
,"[--help]":{"supported":1}
,"supported":{"options":1}
,"follows":{"options":1,"--pinmux":1,"python":1,"--pad":1}
,"description":{"--pinmux":1,"address_file":1,"--help":1,"pad_file":1}
,"--pinmux":{"<arguments>":1,"arguments":1}
,"<arguments>":{"ptional":1,"specifies":1}
,"ptional":{"specifies":1}
,"specifies":{"pinmux":1,"output":1,"address":1,"gpio":1,"por":1,"mandatory":1,"device":1,"numeric":1,"pad":1}
,"arguments":{"default":1,"follows":1,"description":1}
,"assumes":{"data":1}
,"data":{"pinmux":1}
,"unless":{"command":1}
,"line":{"includes":1}
,"includes":{"--pad":1}
,"--pad":{"option":1,"<pad_file":1,"<arguments>":1,"arguments":1}
,"option":{"--mask":1,"arguments":1}
,"--mask":{"ptional":1,"controls":1}
,"output":{"(useful":1,"ave":1,"file":1,"redirect":1}
,"(useful":{"build":1}
,"build":{"sheets)":1}
,"sheets)":{"--help":1,"--pad":1}
,"--help":{"prints":1}
,"prints":{"usage":1}
,"usage":{"information":1}
,"address_file":{"specifies":1}
,"address":{"info":1}
,"gpio_address_file":{"specifies":1}
,"por_val_file":{"specifies":1}
,"por":{"val":1}
,"val":{"pair":1}
,"pair":{"info":1}
,"mandatory_pinmux_file":{"specifies":1}
,"mandatory":{"pinmux":1}
,"values":{"info":1}
,"pinmux_dts":{"_file":1}
,"_file":{"specifies":1}
,"gpio_dts":{"_file":1}
,"version":{"specifies":1,"1.0":1}
,"numeric":{"version":1}
,"1.0":{"resulting":1}
,"resulting":{".cfg":1,"cfg":1}
,"printed":{"standard":1,"stand":1}
,"standard":{"output":1}
,"ave":{"file":1}
,"redirect":{"ing":1,"output":1}
,"\u005C--pinmux":{"\u005Caddr_info.txt":1}
,"\u005Caddr_info.txt":{"gpio_addr_info.txt":1}
,"gpio_addr_info.txt":{"por_val.txt":1}
,"por_val.txt":{"\u005Cmandatory_pinmux.txt":1}
,"\u005Cmandatory_pinmux.txt":{"\u005Ctegra186-quill-p3310-1000-a00-pinmux.dtsi":1}
,"\u005Ctegra186-quill-p3310-1000-a00-pinmux.dtsi":{"\u005Ctegra186-quill-p3310-1000-a00-gpio-default.dts":1}
,"\u005Ctegra186-quill-p3310-1000-a00-gpio-default.dts":{"\u005C1.0":1}
,"\u005C1.0":{"tegra186-quill-p3310-1000-a00-pinmux-gpio.cfg":1,"tegra186-mb1-bct-pad-quill-char-e3301-1080-a00.c":1}
,"tegra186-quill-p3310-1000-a00-pinmux-gpio.cfg":{"copy":1}
,"locatio":{"<top>\u002Fbootloader\u002Ft186ref\u002Fbct\u002Fto":1,"<top>\u002Fbootloader\u002Ft186ref\u002Fbct\u002F":1}
,"<top>\u002Fbootloader\u002Ft186ref\u002Fbct\u002Fto":{"conve":1}
,"conve":{"pad":1}
,"<pad_file":{"<pad_dts":1}
,"<pad_dts":{"_file>":1}
,"<version>":{"[--mask]":1}
,"[--mask]":{"[--help]":1}
,"attributes":{"--mask":1}
,"controls":{"output":1}
,"pad_file":{"specifies":1}
,"pad_dts":{"_file":1}
,"pads":{"version":1}
,"stand":{"output":1}
,"\u005C--pad":{"pad_info.txt":1}
,"pad_info.txt":{"\u005Ctegra186-quill-char-e3301-1080-a00-padvoltage-defa":1}
,"\u005Ctegra186-quill-char-e3301-1080-a00-padvoltage-defa":{"ult.dtsi":1}
,"tegra186-mb1-bct-pad-quill-char-e3301-1080-a00.c":{"copy":1}
}
;Search.control.loadWordPairs(pairs);
