var pairs =
{
"glossary":{"topic":1}
,"topic":{"provides":1}
,"provides":{"alphabetized":1}
,"alphabetized":{"list":1}
,"list":{"specia":1}
,"specia":{"lized":1}
,"lized":{"terms":1}
,"terms":{"used":1}
,"used":{"development":1,"during":1,"efficien":1}
,"development":{"guide":1}
,"guide":{"eir":1}
,"eir":{"definitons":1}
,"definitons":{"boot":1}
,"boot":{"configuration":1,"device":1,"loader":1,"power":1,"execute":1,"rom":1,"configurat":1}
,"configuration":{"able":1}
,"able":{"(bct)":1}
,"(bct)":{"nvidia":1}
,"nvidia":{"platform-specific":1,"created":1}
,"platform-specific":{"static":1}
,"static":{"binary":1}
,"binary":{"file":1,"(dtb)":1}
,"file":{"flashing":1}
,"flashing":{"updating":1}
,"updating":{"device":1}
,"device":{"sto":1,"emmc":1,"initialize":1,"tree":1}
,"sto":{"red":1}
,"red":{"secondary":1}
,"secondary":{"boot":1}
,"emmc":{"tore":1}
,"tore":{"information":1}
,"information":{"required":1}
,"required":{"initialize":1}
,"initialize":{"configure":1}
,"configure":{"secondary":1,"sdram":1}
,"sdram":{"locate":1,"based":1}
,"locate":{"verify":1}
,"verify":{"boot":1}
,"loader":{"boot":1,"(mb2)":1}
,"power":{"management":1,"graphics":1}
,"management":{"processor":1,"functions":1}
,"processor":{"(bpmp)":1}
,"(bpmp)":{"firmware":1}
,"firmware":{"runs":1,"initializes":1}
,"runs":{"cortex":1,"power":1,"boot":1,"bpmp":1,"mb1":1}
,"cortex":{"used":1}
,"during":{"boot":1}
,"execute":{"boot":1}
,"rom":{"code":1,"performs":1,"security":1,"microboot":1}
,"code":{"control":1,"architecture":1}
,"control":{"system":1}
,"system":{"-on-a-chip":1,"example":1,"(tos)":1}
,"-on-a-chip":{"(soc)":1}
,"(soc)":{"sequence":1}
,"sequence":{"booting":1,"image":1}
,"booting":{"bpmp":1}
,"bpmp":{"runs":1,"considered":1}
,"functions":{"compute":1}
,"compute":{"unified":1}
,"unified":{"code":1}
,"architecture":{"(cuda)":1}
,"(cuda)":{"nvidia":1}
,"created":{"parallel":1}
,"parallel":{"computing":1}
,"computing":{"platform":1,"performance":1}
,"platform":{"programming":1,"windowing":1}
,"programming":{"model":1,"interfaces":1}
,"model":{"increases":1}
,"increases":{"computing":1}
,"performance":{"harnessin":1}
,"harnessin":{"power":1}
,"graphics":{"processing":1,"library":1}
,"processing":{"unit":1}
,"unit":{"(gpu)":1}
,"(gpu)":{"embedded":1}
,"embedded":{"graphics":1}
,"library":{"(egl)":1}
,"(egl)":{"interface":1}
,"interface":{"khronos":1}
,"khronos":{"rendering":1}
,"rendering":{"application":1}
,"application":{"programming":1}
,"interfaces":{"(apis)":1}
,"(apis)":{"underlying":1}
,"underlying":{"native":1}
,"native":{"platform":1}
,"windowing":{"system":1}
,"example":{"egls":1}
,"egls":{"tream":1}
,"tream":{"extension":1}
,"extension":{"used":1}
,"efficien":{"tly":1}
,"tly":{"transfer":1}
,"transfer":{"sequence":1}
,"image":{"frames":1}
,"frames":{"microboot":1}
,"microboot":{"(mb1)":1,"bootloader":1,"(mb2)":1,"runs":1}
,"(mb1)":{"microboot":1}
,"bootloader":{"runs":1,"performs":1}
,"performs":{"tasks":1}
,"tasks":{"initializes":1,"load":1}
,"initializes":{"sdram":1,"cpu":1}
,"based":{"mb1":1}
,"mb1":{"boot":1,"runs":1,"bootloader":1}
,"configurat":{"ion":1}
,"ion":{"table":1}
,"table":{"(mb1-bct)":1}
,"(mb1-bct)":{"loads":1}
,"loads":{"firmware":1,"next":1}
,"cpu":{"comple":1}
,"comple":{"sets":1}
,"sets":{"security":1}
,"security":{"settings":1,"level":1}
,"settings":{"configures":1}
,"configures":{"pinmux\u002Fgpio":1}
,"pinmux\u002Fgpio":{"soc":1}
,"soc":{"programs":1}
,"programs":{"pmic":1}
,"pmic":{"vdd_cpu":1}
,"vdd_cpu":{"vdd_ddr":1}
,"vdd_ddr":{"rail":1}
,"rail":{"loads":1}
,"next":{"stage":1}
,"stage":{"boot":1}
,"(mb2)":{"mb1":1,"microboot":1}
,"considered":{"extended":1}
,"extended":{"boot":1}
,"level":{"mb1":1}
,"load":{"cpu_bl":1,"bpmp-fw":1,"trusted":1}
,"cpu_bl":{"load":1}
,"bpmp-fw":{"device":1}
,"tree":{"binary":1}
,"(dtb)":{"load":1}
,"trusted":{"operating":1}
,"operating":{"system":1}
,"(tos)":{"secureos":1}
,"secureos":{"mb2":1}
,"mb2":{"runs":1}
}
;Search.control.loadWordPairs(pairs);
