var pairs =
{
"architecture":{"linux":1,"follows":1}
,"linux":{"tegra":1,"kernel":1}
,"tegra":{"board":1,"user":1,"provides":1,"platform":1,"system":1,"graphics":1}
,"board":{"support":1}
,"support":{"package":1,"scripts":1,"cuda":1,"flex":1}
,"package":{"architecture":1,"linux":1,"computer":1}
,"follows":{"components":1}
,"components":{"module":1,"description":1}
,"module":{"explained":1}
,"explained":{"follows":1}
,"description":{"linux":1}
,"kernel":{"unix-like":1,"mostl":1,"multimedia":1}
,"unix-like":{"computer":1}
,"computer":{"operating":1,"vision":1}
,"operating":{"system":1}
,"system":{"kernel":1,"chip":1,"sample":1,"vulkan":1,"profiler":1}
,"mostl":{"used":1}
,"used":{"mobile":1,"optimize":1}
,"mobile":{"devices":1}
,"devices":{"sample":1}
,"sample":{"root":1,"source":1}
,"root":{"ilesystem":1,"filesystem":1,"filesystems":1}
,"ilesystem":{"derived":1}
,"derived":{"ubuntu":1}
,"ubuntu":{"sample":1,"distributio":1,"cross":1}
,"filesystem":{"ubuntu":1}
,"distributio":{"helps":1}
,"helps":{"create":1}
,"create":{"root":1}
,"filesystems":{"different":1}
,"different":{"configurations":1}
,"configurations":{"toolchain":1}
,"toolchain":{"development":1}
,"development":{"tools":1,"package":1,"better":1,"multimedia":1,"jetso":1,"platform":1}
,"tools":{"chained":1,"scripts":1,"assist":1,"tegra":1,"help":1}
,"chained":{"together":1}
,"together":{"sta":1}
,"sta":{"ges":1}
,"ges":{"runs":1}
,"runs":{"various":1}
,"various":{"architectures":1}
,"architectures":{"bootloader":1}
,"bootloader":{"boot":1}
,"boot":{"software":1,"initializing":1}
,"software":{"boot":1,"development":1}
,"initializing":{"system":1}
,"chip":{"sources":1}
,"sources":{"source":1}
,"source":{"code":1}
,"code":{"kernel":1,"applications":1,"developing":1}
,"multimedia":{"applications":1,"api":1,"multimedia":1}
,"applications":{"nvidia":1,"ample":1,"used":1,"buffer":1,"perfkit":1,"jetpack":1}
,"nvidia":{"tegra":1,"drivers":1,"tensorrt":1,"jetpack":1,"cuda":1,"visionworks":1,"optimized":1,"userspace":1,"jetson":1}
,"user":{"space":1}
,"space":{"drivers":1}
,"drivers":{"provides":1,"run":1}
,"provides":{"nvidia":1,"high-performance":1,"samples":1,"opencv":1,"collection":1,"higher-level":1,"parallel":1,"interactive":1,"details":1}
,"run":{"userspace":1,"faster":1}
,"userspace":{"flashing":1,"driver":1}
,"flashing":{"support":1,"system":1}
,"scripts":{"tools":1,"associated":1}
,"associated":{"tools":1}
,"assist":{"flashing":1}
,"ample":{"source":1}
,"developing":{"embedded":1}
,"embedded":{"applicat":1,"systems":1}
,"applicat":{"ions":1}
,"ions":{"jetson":1}
,"jetson":{"platform":1,"develop":1,"developer":1,"download":1,"driver":1,"development":1}
,"platform":{"artificial":1,"multimedia":1,"contains":1,"samples":1}
,"artificial":{"intelligence":1}
,"intelligence":{"nvidia":1}
,"tensorrt":{"provides":1,"opencv4tegra":1}
,"high-performance":{"neural":1}
,"neural":{"network":1}
,"network":{"inference":1,"library":1}
,"inference":{"engine":1,"jetson":1}
,"engine":{"oduction":1,"nvidia":1}
,"oduction":{"deployment":1}
,"deployment":{"deep":1,"support":1}
,"deep":{"learning":1,"neural":1}
,"learning":{"applications":1}
,"optimize":{"validate":1}
,"validate":{"deploy":1}
,"deploy":{"train":1}
,"train":{"neural":1}
,"api":{"provides":1,"cudnn":1,"based":1,"rendering":1,"full-function":1,"gives":1,"(mmapi)":1,"inclu":1,"extensions":1,"framework":1,"gstreamer":1,"developer":1}
,"samples":{"engine":1,"demonstrate":1,"designed":1}
,"jetpack":{"installs":1,"framework":1,"sdk":1}
,"installs":{"component":1}
,"component":{"part":1}
,"part":{"w-level":1,"multimedia":1}
,"w-level":{"multimedia":1}
,"cudnn":{"nvidia":1,"tensorrt":1}
,"cuda":{"deep":1,"toolkit":1,"object":1}
,"library":{"computer":1,"api":1}
,"vision":{"visionworks":1,"(cv)":1}
,"visionworks":{"nvidia":1,"software":1}
,"(cv)":{"image":1}
,"image":{"processing":1}
,"processing":{"opencv4":1,"cuda":1}
,"opencv4":{"tegra":1}
,"opencv":{"nvidia":1,"implementation":1}
,"optimized":{"specifically":1}
,"specifically":{"tegra":1}
,"contains":{"tegra-specific":1}
,"tegra-specific":{"optimizations":1}
,"optimizations":{"enab":1}
,"enab":{"run":1}
,"faster":{"opencv":1}
,"implementation":{"camera":1}
,"camera":{"lib":1,"core":1}
,"lib":{"rgus":1}
,"rgus":{"low-level":1}
,"low-level":{"api":1}
,"based":{"camera":1}
,"core":{"stack":1}
,"stack":{"jetpack":1}
,"collection":{"apis":1,"lower-level":1}
,"apis":{"supports":1,"engl":1,"support":1,"lower-leve":1}
,"supports":{"flexib":1}
,"flexib":{"application":1}
,"application":{"development":1,"framework":1,"performance":1}
,"better":{"control":1}
,"control":{"ove":1}
,"ove":{"underlying":1}
,"underlying":{"hardware":1,"native":1}
,"hardware":{"blocks":1}
,"blocks":{"display":1}
,"display":{"nvdc-drm":1,"cuda":1,"v4l2":1}
,"nvdc-drm":{"nvidia":1}
,"driver":{"display":1,"gstreamer":1,"installed":1}
,"toolkit":{"host":1,"jetson":1}
,"host":{"ubuntu":1,"jetson":1}
,"cross":{"deployment":1}
,"develop":{"kit":1}
,"kit":{"running":1,"graphics":1}
,"running":{"l4t":1}
,"l4t":{"bsp":1}
,"bsp":{"cuda":1}
,"developer":{"kit":1,"multimedia":1,"tools":1}
,"graphics":{"opengl":1,"library":1,"debugger":1}
,"opengl":{"open":1,"ross-platform":1,"opengl":1,"applications":1,"direct3d":1}
,"open":{"graphics":1}
,"rendering":{"vector":1,"apis":1}
,"vector":{"gra":1}
,"gra":{"phics":1}
,"phics":{"opengl":1}
,"ross-platform":{"api":1}
,"full-function":{"grap":1}
,"grap":{"hics":1}
,"hics":{"embedded":1}
,"systems":{"egl":1}
,"egl":{"nterface":1}
,"nterface":{"khronos":1}
,"khronos":{"rendering":1}
,"engl":{"openvg":1}
,"openvg":{"underlying":1}
,"native":{"platfo":1}
,"platfo":{"window":1}
,"window":{"system":1}
,"vulkan":{"low":1}
,"low":{"level":1}
,"level":{"api":1}
,"gives":{"direct":1}
,"direct":{"access":1}
,"access":{"gpu":1}
,"gpu":{"developer":1}
,"(mmapi)":{"collection":1}
,"lower-level":{"apis":1}
,"flex":{"ible":1}
,"ible":{"application":1}
,"inclu":{"des":1}
,"des":{"libargus":1}
,"libargus":{"imaging":1}
,"imaging":{"applications":1}
,"buffer":{"utility":1,"allocation":1}
,"utility":{"buffer":1}
,"allocation":{"management":1}
,"management":{"sharing":1}
,"sharing":{"nvosd":1}
,"nvosd":{"on-screen":1}
,"on-screen":{"display":1}
,"v4l2":{"api":1}
,"extensions":{"video":1}
,"video":{"converter":1}
,"converter":{"decode":1}
,"decode":{"encoder":1}
,"encoder":{"application":1}
,"framework":{"(optional)":1,"wish":1,"gstreamer":1,"provides":1,"installed":1,"alternative":1}
,"(optional)":{"mmapi":1}
,"mmapi":{"includes":1,"developers":1,"separately":1}
,"includes":{"samples":1}
,"demonstrate":{"image":1}
,"object":{"detection":1}
,"detection":{"assification":1}
,"assification":{"cudnn":1}
,"opencv4tegra":{"usage":1}
,"usage":{"mmapi":1}
,"developers":{"custom":1}
,"custom":{"framework":1}
,"wish":{"avoid":1}
,"avoid":{"framework":1}
,"gstreamer":{"mmapi":1,"provides":1,"framework":1}
,"separately":{"wnloaded":1}
,"wnloaded":{"nvidia":1}
,"download":{"center":1}
,"center":{"included":1}
,"included":{"downlo":1}
,"downlo":{"jetson":1}
,"higher-level":{"ultimedia":1}
,"ultimedia":{"api":1}
,"parallel":{"capability":1}
,"capability":{"collection":1}
,"lower-leve":{"multimedia":1}
,"installed":{"down":1,"nvidia":1}
,"down":{"load":1}
,"load":{"jetson":1}
,"alternative":{"multimedia":1}
,"profiler":{"multi-core":1,"provides":1}
,"multi-core":{"cpu":1}
,"cpu":{"sampling":1}
,"sampling":{"profiler":1}
,"interactive":{"view":1}
,"view":{"captured":1}
,"captured":{"profiling":1}
,"profiling":{"data":1}
,"data":{"help":1}
,"help":{"ing":1,"debug":1}
,"ing":{"improve":1}
,"improve":{"overall":1}
,"overall":{"application":1}
,"performance":{"tegra":1,"tools":1}
,"debugger":{"console-grade":1}
,"console-grade":{"tool":1}
,"tool":{"allows":1}
,"allows":{"debug":1}
,"debug":{"ptimize":1,"profile":1}
,"ptimize":{"opengl":1}
,"perfkit":{"comprehensive":1}
,"comprehensive":{"suite":1}
,"suite":{"performance":1}
,"profile":{"opengl":1}
,"direct3d":{"applications":1}
,"sdk":{"documentation":1}
,"documentation":{"provides":1}
,"details":{"development":1}
,"jetso":{"platform":1}
,"designed":{"give":1}
,"give":{"hands-on":1}
,"hands-on":{"practical":1}
,"practical":{"examples":1}
,"examples":{"using":1}
,"using":{"nvidia":1}
}
;Search.control.loadWordPairs(pairs);
