var pairs =
{
"tx2":{"mb1":1,"boot":1,"pinmux":1,"prod":1,"pad":1,"pins":1,"pmic":1}
,"mb1":{"platform":1,"uses":1,"bct":1,"executes":1,"stage":1,"allows":1,"reads":1,"enables":1,"device":1,"device-side":1,"contain":1,"cfg":1,"code":1,"enable":1,"control":1,"wai":1,"resumes":1,"wait":1,"programs":1,"field":1,"once":1}
,"platform":{"configuration":1,"-specific":1,"calls":1,"specif":1,"prod":1,"software":1,"*\u002Fsource-frq-hz":1,"specific":1,"data":1,"feature":1}
,"configuration":{"boo":1,"files":1,"prod":1,"configuration":1,"jetson":1,"file":1,"information":1,"system":1,"tuple":1,"tegra":1,"identified":1,"rail":1,"without":1,"default":1,"required":1,"devices":1,"p3310":1,"p2597":1,"register":1,"uses":1,"example":1,"ile":1}
,"boo":{"sequence":1}
,"sequence":{"jetson":1,"i2c":1,"may":1,"rail":1,"commands":1,"startin":1,"beginn":1,"voltage":1,"recommendation":1,"delay":1,"elay":1}
,"jetson":{"tx2":1,"tx1\u002Ftx2":1}
,"uses":{"mb1":1,"following":1}
,"bct":{"configure":1,"mb1":1,"specifies":1,"uses":1,"required":1,"configuration":1,"binary":1,"cold":1,"allows":1,"flag":1}
,"configure":{"platform":1,"*\u002Ffor":1,"devices":1}
,"-specific":{"static":1,"data":1}
,"static":{"settings":1}
,"settings":{"mb1":1,"required":1,"contain":1,"passed":1,"field":1,"cluster":1,"fields":1,"specify":1,"used":1}
,"executes":{"cpus":1}
,"cpus":{"enabled":1}
,"enabled":{"mb1":1,"disabled":1}
,"stage":{"owned":1,"signed":1,"offers":1,"list":1}
,"owned":{"nvidia":1}
,"nvidia":{"signed":1,"oem":1}
,"signed":{"nvidia":1,"mb1":1}
,"oem":{"information":1}
,"information":{"tx2":1,"typical":1,"mb1-cfg":1,"format":1,"commands":1,"generic":1,"collected":1,"flashing":1}
,"boot":{"flow":1,"jetson":1,"stored":1,"exclude":1,"exc":1,"mb1":1,"done":1,"temperature":1,"temp":1,"cpu":1,"sequence":1,"loader":1}
,"flow":{"mb1":1}
,"specifies":{"platform":1,"block":1,"command":1,"delay":1,"number":1}
,"data":{"tegraflash":1,"platform":1,"register":1,"pai":1,"<address>":1,"value":1,"address":1,"size":1,"pmic.generic.1.block-count":1,"pmic.core.3.block-count":1,"scr":1,"cannot":1,"cfg":1,"bct":1}
,"tegraflash":{"invoked":1}
,"invoked":{"flash":1}
,"flash":{"platform":1}
,"calls":{"tegrabct_v2":1}
,"tegrabct_v2":{"tool":1}
,"tool":{"create":1}
,"create":{"mb1":1,"configuration":1,"onfig":1}
,"following":{"data":1,"parameter":1,"format":1,"code":1,"correcting":1,"values":1}
,"files":{"tegrabl_mb1_bct.h":1,"specify":1,"<top":1}
,"tegrabl_mb1_bct.h":{"header":1}
,"header":{"file":1}
,"file":{"bct":1,"provides":1,"<top":1,"located":1,"provide":1,"configured":1,"sequence":1,"load":1,"created":1,"based":1}
,"required":{"stage":1,"interface":1,"based":1,"mb1":1,"commands":1,"multiple":1,"mmio":1,"split":1,"however":1,"configure":1,"rite":1,"reset":1}
,"offers":{"perform":1}
,"perform":{"platform":1,"configur":1,"recommended":1}
,"specif":{"initialization":1}
,"initialization":{"sets":1,"enable":1,"spe-can":1}
,"sets":{"secure":1,"commands":1}
,"secure":{"cont":1,"register":1,"start":1}
,"cont":{"rol":1}
,"rol":{"register":1}
,"register":{"(scr)":1,"configuration":1,"address":1,"data":1,"size":1,"jetson":1,"addresses":1,"absolute":1,"configurations":1,"programmed":1,"clock.bpmp_cpu_nic_divider":1,"clock.bpmp_apb_divider":1,"clock.axi_cbb_divider":1,"clock.se_divider":1,"clock.aon_cpu_nic_divider":1,"clock.aon_apb_divider":1,"clock.aon_can0_divider":1,"clock.aon_can1_divider":1,"clock.pllaon_divp":1,"clock.pllaon_divn":1,"clock.pllaon_divm":1,"pllp_out0":1,"value":1,"enable":1}
,"(scr)":{"platform-specific":1}
,"platform-specific":{"configuration":1,"mb1":1}
,"specify":{"pinmux":1,"boot":1,"address":1,"operating":1,"clock":1,"width":1,"dma":1,"mode":1,"watchdog":1}
,"pinmux":{"gpios":1,"gpio":1,"configuration":1,"<address>":1,"domain":1,"configurat":1,"used":1,"unused":1}
,"gpios":{"configuration":1}
,"prod":{"setting":1,"configuration":1,"<address>":1,"domain":1}
,"setting":{"pad":1,"pmic":1,"secure":1,"configuration":1,"ontroller":1,"<address>":1,"rail":1,"voltages":1,"<reg_index>":1,"initializing":1,"various":1,"voltage":1,"required":1}
,"pad":{"voltage":1,"control":1,"configuration":1}
,"voltage":{"setting":1,"configuration":1,"pads":1,"higher":1,"lower":1,"required":1,"pmic.core.3.block":1,"rail":1,"repr":1,"register":1}
,"pmic":{"setting":1,"onfiguration":1,"configurations":1,"command":1,"configuration":1,"<parameter>":1,"<rail-names>":1,"<rail-name>":1,"mbldp":1,"consider":1,"default":1,"p3310":1,"pmic":1}
,"<top":{">\u002Fbootloader\u002F<platform":1}
,">\u002Fbootloader\u002F<platform":{"ver>\u002Fbct\u002Ftx2":1,"ver>\u002Fbct\u002Ftegra":1,"ver>\u002Fbct":1,"ver>\u002Fbct\u002Fauto_scr.cfg":1,"ver>\u002Fbct\u002Ftegra186-mb1-bct-misc-quill":1}
,"ver>\u002Fbct\u002Ftx2":{"pinmux":1}
,"gpio":{"configuration":1,"dress":1,"pinmux":1}
,"provides":{"pinmux":1}
,"typical":{"format":1,"rail\u002Fconfigurations":1}
,"format":{"data":1,"configuration":1,"supports":1,"suppo":1,"i2c":1,"pwm":1,"rail":1,"<address":1,"commands":1,"following":1,"ommon":1,"follows":1}
,"address":{"data":1,"<value>":1,"mask":1,"modifies":1,"prod":1,"<mask":1,"device":1,"register":1,"size":1,"reg-data-size":1,"based":1,"bpmp-fw":1,"mb2-fw":1,"sce-fw":1,"audio-protected":1,"ape-fw":1}
,"pai":{"mb1":1}
,"allows":{"writes":1,"scr":1}
,"writes":{"pinmux":1}
,"dress":{"range":1}
,"range":{"table":1}
,"table":{"pinmux":1}
,"ver>\u002Fbct\u002Ftegra":{"<t-arch":1,"<186":1}
,"<t-arch":{">-mb1-bct-pinmux-gpio-<board":1,"-mb1-bct-pad-quill-<board":1,"-mb1-bct-pmic":1}
,">-mb1-bct-pinmux-gpio-<board":{"-<board_revision>":1}
,"-<board_revision>":{".cfg":1}
,".cfg":{"usage":1,"note":1}
,"usage":{"pinmux":1,"prod":1,"pmc":1,"common":1,"pmic.command-retries-count":1,"scr":1}
,"<address>":{"=<value>":1,"absolute":1,"<mask>":1,"pad":1}
,"=<value>":{"pinmux":1,"prod":1,"pmc":1,"rail-specific":1,"common":1,"pmic.wait-before-start-bus-clear-us":1,"pmic.rail-count":1,"<value>":1}
,"domain":{"name":1}
,"name":{"gpio":1,"prefix":1,"generic":1}
,"configurat":{"ion":1}
,"ion":{"data":1}
,"absolute":{"register":1,"addresses":1}
,"<value>":{"32-bit":1,"data":1,"block-count":1}
,"32-bit":{"data":1}
,"value":{"device-side":1,"mb1":1,"write":1,"bytes":1,"type":1,"description":1,"less":1,"field":1,"pll-aon":1,"ios":1,"wdt.bpmp_wdtcr":1,"wdt.sce_wdtcr":1,"wdt.aon_wdtcr":1,"wdt.rtc2_ao_wdtcr":1,"wdt.top_wdt0_wdtcr":1,"wdt.top_wdt1_wdtcr":1,"wdt.top_wdt2_wdtcr":1}
,"device-side":{"implementation":1,"code":1}
,"implementation":{"write":1,"val":1}
,"write":{"(value":1,"back":1,"(val":1,"correct":1,"commands":1}
,"(value":{"address)":1,"&mask)":1}
,"address)":{"example":1}
,"example":{"pinmux":1,"prod.0x02436010.0x00006000":1,"pmc.0x0c36003c":1,"pmic.command-retries-count":1,"950mv":1,"usage":1,"pmic.core.3.block-count":1,"scr":1,"enable_can_boot":1,"boot_temp_threshold":1,"bpmp_cpu_nic_divider":1,"ootcpu":1,"bpmp_fw_va":1,"cpubl_carveout_addr":1,"uart_instance":1,"specify":1,"qspi.clk_src":1,"bpmp_wdtcr":1}
,"used":{"pins":1,"pmic":1,"eliminate":1,"ape-fw":1,"mb1\u002Fmb2":1,"gpc-dma":1,"different":1}
,"pins":{"pinmux.0x02434060":1,"low-power":1,"pads":1}
,"pinmux.0x02434060":{"=<value1>":1}
,"=<value1>":{"gen1_i2c_scl_pc5.p":1,"gen1_i2c_sda_pc6.p":1,"gpio_wan4_ph0.padc":1,"gpio_wan3_ph1.padc":1}
,"gen1_i2c_scl_pc5.p":{"adctl_conn_gen1_i2c_scl_0":1,"adctl_conn_cfg2tmc_gen1_i2c_scl_0":1}
,"adctl_conn_gen1_i2c_scl_0":{"pinmux.0x02434064":1}
,"pinmux.0x02434064":{"=<value2>":1}
,"=<value2>":{"gen1_i2c_scl_pc5.p":1,"gen1_i2c_sda_pc6.p":1,"gpio_wan4_ph0.padc":1,"gpio_wan3_ph1.padc":1}
,"adctl_conn_cfg2tmc_gen1_i2c_scl_0":{"pinmux.0x02434068":1}
,"pinmux.0x02434068":{"=<value1>":1}
,"gen1_i2c_sda_pc6.p":{"adctl_conn_gen1_i2c_sda_0":1,"adctl_conn_cfg2tmc_gen1_i2c_da_0":1}
,"adctl_conn_gen1_i2c_sda_0":{"pinmux.0x0243406c":1}
,"pinmux.0x0243406c":{"=<value2>":1}
,"adctl_conn_cfg2tmc_gen1_i2c_da_0":{"pinmux":1}
,"unused":{"pins":1,"-pllaon_divp":1,"-i2c":1}
,"low-power":{"configur":1}
,"configur":{"ation":1}
,"ation":{"pinmux.0x02434040":1,"baseboard":1,"system":1}
,"pinmux.0x02434040":{"=<value1>":1}
,"gpio_wan4_ph0.padc":{"tl_conn_gpio_wan4_0":1,"tl_conn_cfg2tmc_gpio_wan4_0":1}
,"tl_conn_gpio_wan4_0":{"pinmux.0x02434044":1}
,"pinmux.0x02434044":{"=<value2>":1}
,"tl_conn_cfg2tmc_gpio_wan4_0":{"pinmux.0x02434048":1}
,"pinmux.0x02434048":{"=<value1>":1}
,"gpio_wan3_ph1.padc":{"tl_conn_gpio_wan3_0":1,"tl_conn_cfg2tmc_gpio_wan3_0":1}
,"tl_conn_gpio_wan3_0":{"pinmux.0x0243404c":1}
,"pinmux.0x0243404c":{"=<value2>":1}
,"tl_conn_cfg2tmc_gpio_wan3_0":{"tx2":1}
,"system":{"characterization":1,"boot":1,"power":1,"pmic":1,"using":1,"tempe":1,"team":1}
,"characterization":{"inter":1}
,"inter":{"face":1}
,"face":{"controller":1,"pad":1}
,"controller":{"settings":1,"instance":1,"i2c":1,"egister":1}
,"interface":{"work":1,"operate":1}
,"work":{"reliably":1,"level":1}
,"reliably":{"given":1}
,"given":{"platform":1,"interface":1,"rail":1,"rails":1,"blocks":1,"blo":1,"block":1}
,"ontroller":{"level":1,"ettings":1}
,"level":{"separately":1,"format":1,"pad":1}
,"separately":{"inmux":1}
,"inmux":{"level":1}
,"tuple":{"register":1}
,"mask":{"data":1,"value":1}
,"reads":{"data":1}
,"modifies":{"based":1}
,"based":{"mask":1,"terface":1,"power":1,"location":1,"above":1}
,"back":{"address":1}
,"<186":{"210>":1}
,"210>":{"-mb1-bct-prod":1}
,"-mb1-bct-prod":{"-<board":1}
,"-<board":{"-<board_revision>":1}
,"<mask>":{"=<value>":1,"=<data>":1,"=<data0>":1}
,"prefix":{"setting":1}
,"control":{"register":1,"max":1,"fields":1,"bpmp":1,"apb":1,"axi-cbb":1,"controlle":1,"aon":1,"can0":1,"can1":1}
,"<mask":{"mask":1,"=<data>":1}
,"bytes":{"unsigned)":1,"unsigned":1}
,"unsigned)":{"<value>":1}
,"unsigned":{"device-side":1}
,"val":{"=read":1,"=(val":1}
,"=read":{"(address)":1}
,"(address)":{"val":1}
,"=(val":{"mask)":1}
,"mask)":{"(value":1}
,"&mask)":{"write":1}
,"(val":{"address)":1}
,"prod.0x02436010.0x00006000":{"=0x00002000":1}
,"=0x00002000":{"sdmmc4_dat7":1,"sdmmc4_dat6":1,"sdmmc4_dat5":1,"sdmmc4_dat4":1,"sdmmc4_dat3":1}
,"sdmmc4_dat7":{"drv_type":1}
,"drv_type":{"drive_2x":1}
,"drive_2x":{"prod.0x02436014.0x00006000":1,"prod.0x02436018.0x00006000":1,"prod.0x0243601c.0x00006000":1,"prod.0x02436020.0x00006000":1,"tx2":1}
,"prod.0x02436014.0x00006000":{"=0x00002000":1}
,"sdmmc4_dat6":{"drv_type":1}
,"prod.0x02436018.0x00006000":{"=0x00002000":1}
,"sdmmc4_dat5":{"drv_type":1}
,"prod.0x0243601c.0x00006000":{"=0x00002000":1}
,"sdmmc4_dat4":{"drv_type":1}
,"prod.0x02436020.0x00006000":{"=0x00002000":1}
,"sdmmc4_dat3":{"drv_type":1}
,"tegra":{"jetson":1,"registers":1}
,"pads":{"designed":1,"enable":1,"consequently":1}
,"designed":{"support":1}
,"support":{"multiple":1,"read-modify-write":1}
,"multiple":{"vol":1,"blocks":1,"devices":1,"ommands":1,"commands":1}
,"vol":{"tage":1}
,"tage":{"levels":1}
,"levels":{"given":1}
,"operate":{"1.2":1,"temperature":1}
,"1.2":{"volts":1}
,"volts":{"(v)":1}
,"(v)":{"1.8":1}
,"1.8":{"3.3":1}
,"3.3":{"based":1}
,"terface":{"power":1}
,"power":{"tree":1,"rail":1,"rails":1,"down":1}
,"tree":{"given":1,"pad":1}
,"software":{"write":1}
,"correct":{"voltage":1,"pad":1}
,"enable":{"inter":1,"<1\u002F0>":1,"ecc":1,"sc7":1,"fuse":1,"shutdown":1,"log":1,"rails":1}
,"higher":{"power":1,"temperature":1}
,"rail":{"pin":1,"damage":1,"voltages":1,"command":1,"required":1,"rail":1,"defined":1,"name":1,"customizing":1,"spe":1,"blocks":1,"specific":1,"block":1,"(id":1,"otp":1,"per":1,"list":1}
,"pin":{"work":1}
,"lower":{"han":1}
,"han":{"power":1}
,"damage":{"soc":1}
,"soc":{"pads":1}
,"consequently":{"configuring":1}
,"configuring":{"correct":1,"pwm":1,"generic":1,"security":1,"bridge":1}
,"located":{"<top":1}
,"-mb1-bct-pad-quill-<board":{"-<board_revision>":1}
,"pmc":{"<address>":1,"domain":1}
,"pmc.0x0c36003c":{"=0x0000003e":1}
,"=0x0000003e":{"pmc_impl_e_18v_pwr_0":1}
,"pmc_impl_e_18v_pwr_0":{"pmc.0x0c360040":1}
,"pmc.0x0c360040":{"=0x00000079":1}
,"=0x00000079":{"pmc_impl_e_33v_pwr_0":1}
,"pmc_impl_e_33v_pwr_0":{"tx2":1}
,"onfiguration":{"during":1,"egisters":1}
,"during":{"system":1,"transfer":1,"dummy":1}
,"enables":{"system":1}
,"rails":{"cpu":1,"setting":1,"may":1,"gpu":1,"configuration":1,"indexed":1,"configuring":1,"pmic":1,"brou":1,"perform":1}
,"cpu":{"sram":1,"rails":1,"core":1,"nic":1,"frequency":1,"parameters":1,"means":1}
,"sram":{"core":1,"commands":1,"gpu":1}
,"core":{"system":1,"commands":1,"mem":1,"sram":1,"rail":1}
,"configurations":{"ypical":1,"enabling":1,"i2c":1,"command":1,"shutdown":1,"configuration":1,"pmic":1,"p3310":1,"scr.134.1":1,"misc":1}
,"ypical":{"configurations":1}
,"enabling":{"rails":1,"setting":1,"configuring":1}
,"voltages":{"fps":1,"rails":1}
,"fps":{"configurations":1}
,"may":{"requ":1,"mmio":1,"high":1}
,"requ":{"ire":1}
,"ire":{"i2c":1}
,"i2c":{"command":1,"commands":1,"pulse":1,"\u002Fpwm":1,"i2c":1,"mmio":1,"typical":1,"type":1,"(1)":1,"ype-s":1,"slave-add":1,"information":1,"specific":1,"mmios":1,"pmic":1,"platform":1,"bus":1,"controller":1}
,"command":{"devices":1,"400khz":1,"domains":1,"related":1,"sequence":1,"attempts":1,"wait":1,"commands":1,"given":1,"type":1,"value":1,"reset":1}
,"devices":{"mmio":1,"split":1,"system":1,"pmic":1,"ensures":1,"separate":1}
,"mmio":{"access":1,"commands":1,"i2c":1,"mmio":1,"(0)":1,"i2c>":1,"delay":1}
,"access":{"tegra":1,"delays":1}
,"registers":{"either":1,"address":1,"configuring":1,"scr":1}
,"either":{"read-modify":1,"mmio":1,"configured":1}
,"read-modify":{"-write":1}
,"-write":{"write-only":1}
,"write-only":{"delay":1}
,"delay":{"commands":1,"required":1,"specifies":1,"microseconds":1,"comm":1,"ommunicat":1,"communicate":1}
,"commands":{"rail-specific":1,"mmio":1,"sequence":1,"read-modify-write":1,"enabling":1,"write":1,"pwm\u002Fi2c\u002Fmmio":1,"i2c":1,"related":1,"thermal":1,"shutdown":1,"required":1,"broken":1,"commands":1,"sent":1,"given":1,"iven":1,"type":1,"different":1,"block":1,"ommands":1,"indexed":1,"[command-index]":1,"follows":1,"enabl":1,"per":1,"send":1,"used":1,"blocks":1}
,"rail-specific":{"configurations":1,"parameters":1}
,"delays":{"platform-specific":1}
,"provide":{"config":1}
,"config":{"uration":1}
,"uration":{"information":1,"file":1}
,"mb1-cfg":{"format":1}
,"supports":{"i2c":1}
,"pulse":{"width":1}
,"width":{"modulation":1,"qspi":1}
,"modulation":{"(pwm":1}
,"(pwm":{"commands":1}
,"\u002Fpwm":{"controller":1}
,"instance":{"7-bit":1,"console":1,"i2c.0":1,"i2c.4":1}
,"7-bit":{"slave":1}
,"slave":{"address":1}
,"device":{"mmio":1,"registers":1,"side":1,"i2c":1,"address":1,"sequence":1,"aotag.boot_temp_threshold":1,"cooled":1,"settings":1,"internal":1,"anything":1,"different":1,"thing":1}
,"read-modify-write":{"format":1,"sequence":1}
,"suppo":{"read":1}
,"read":{"read-modify-write":1,"written":1}
,"pwm":{"commands":1,"amount":1,"pecific":1,"specific":1,"=2)":1,"regulator":1,"just":1,"type":1}
,"amount":{"delay":1}
,"pwm\u002Fi2c\u002Fmmio":{"size":1}
,"size":{"device":1,"i2c":1,"register":1,"parameters":1,"bits":1,"carveout":1,"cpu-bl":1,"mb2":1}
,"400khz":{"sequence":1}
,"rail\u002Fconfigurations":{"divided":1}
,"divided":{"ollowing":1,"blocks":1}
,"ollowing":{"pmic":1}
,"domains":{"generic":1}
,"generic":{"general":1,"cpu":1,"format":1,"rail":1,"rails":1,"setting":1}
,"general":{"pmic":1}
,"related":{"cpu":1,"gpu":1,"sram":1,"core":1,"memory":1,"configurations":1}
,"gpu":{"commands":1,"sram":1,"mem":1}
,"mem":{"commands":1,"thermal":1}
,"memory":{"thermal":1}
,"thermal":{"commands":1,"configurations":1,"shutdown":1}
,"shutdown":{"commands":1,"related":1,"pmic":1,"using":1}
,"identified":{"given":1}
,"side":{"code":1}
,"code":{"ignores":1,"snippets":1,"platform":1,"lists":1}
,"ignores":{"configuration":1}
,"defined":{"unique":1}
,"unique":{"parsing":1,"ids":1}
,"parsing":{"bct":1}
,"binary":{"easie":1}
,"easie":{"unique":1}
,"ids":{"follows":1}
,"follows":{"rail":1,"parameter":1,"command":1,"block":1,"field":1,"information":1}
,"ver>\u002Fbct":{"\u002Ftegra":1}
,"\u002Ftegra":{"<t-arch":1}
,"-mb1-bct-pmic":{"-quill":1}
,"-quill":{"-<board":1}
,"note":{"eview":1}
,"eview":{"rail":1}
,"customizing":{"carrier":1}
,"carrier":{"board":1}
,"board":{"usage":1,"fields":1}
,"common":{"parameters":1,"<parameters>":1,"rail":1}
,"parameters":{"pmic":1,"following":1,"required":1,"prefixed":1,"follows":1,"generic":1,"pmic.command-retries-count":1,"settings":1}
,"<parameter>":{"=<value>":1}
,"<rail-names>":{"<rail-id>":1}
,"<rail-id>":{"<parameters>":1,"parameter":1,".block-count":1,".block":1}
,"<parameters>":{"=<value>":1,"following":1}
,"parameter":{"description":1,"rail-count":1,"blocks":1}
,"description":{"command-retries-count":1,"block-count":1,"i2c-controller-id":1,"include":1,"configuration":1}
,"command-retries-count":{"number":1}
,"number":{"allowed":1,"rails":1,"ommand":1,"commands":1}
,"allowed":{"command":1,"operate":1}
,"attempts":{"wait-before-start-bus-clear-us":1}
,"wait-before-start-bus-clear-us":{"wait":1}
,"wait":{"timeout":1,"time":1,"system":1}
,"timeout":{"microseconds":1}
,"microseconds":{"issuing":1,"provided":1,"ommand":1}
,"issuing":{"clear":1}
,"clear":{"command":1}
,"time":{"calculated":1,"mb1":1,"accessing":1}
,"calculated":{"<<n":1}
,"<<n":{"microseconds":1}
,"provided":{"parameter":1,"command":1}
,"rail-count":{"number":1}
,"configured":{"example":1,"nvi":1,"mb1":1}
,"pmic.command-retries-count":{"=<value>":1,"=<u32>":1,"pmic.wait-before-start-bus-clear-us":1}
,"pmic.wait-before-start-bus-clear-us":{"=<value>":1,"=<u32>":1,"pmic.rail-count":1}
,"pmic.rail-count":{"=<value>":1,"=<u32>":1,"generic":1}
,"spe":{"ific":1}
,"ific":{"mmands":1}
,"mmands":{"divided":1}
,"blocks":{"rail":1,"block":1,"commands":1,"i2c":1,"given":1,"indexed":1,"module":1,"blocks":1,"contain":1,"create":1,"put":1,"aoblocks":1}
,"block":{"given":1,"contains":1,"contain":1,"count":1,"specifies":1,"identification":1,"i2c":1,"commands":1,"pmic":1,"follow":1}
,"indexed":{"starting":1,"facilitate":1,"list":1}
,"starting":{"block":1,"pmic":1}
,"contains":{"either":1,"i2c":1,"max":1,"setting":1,"bpmp":1,"sce":1,"aon\u2019s":1,"rtc2_ao":1,"top_wdt0":1,"top_wdt1":1,"top_wdt2":1}
,"broken":{"multiple":1}
,"type":{"commands":1,"device":1,"elay":1,"specifies":1,"either":1,"specific":1,"(for":1,"pmic.core.3.block":1,"pmic.generic.1.block":1,"mmio":1,"i2c":1}
,"sent":{"device":1}
,"split":{"multiple":1,"commands":1}
,"iven":{"block":1}
,"contain":{"command":1,"data":1,"initial":1,"mult":1,"multiple":1}
,"elay":{"provided":1,"commands":1}
,"blo":{"delay":1}
,"different":{"delay":1,"configurations":1,"different":1,"blocks":1,"reset":1}
,"specific":{"parameters":1,"commands":1,"pmic":1,"example":1,"configuration":1}
,"prefixed":{"follo":1}
,"follo":{"wing":1}
,"wing":{"pmic":1}
,"<rail-name>":{"<rail-id>":1,".block-count":1}
,"block-count":{"specifies":1,"number":1}
,"count":{"pmic":1,"specifies":1}
,".block-count":{"=<value>":1,"generic":1}
,"ommand":{"blocks":1,"given":1}
,"identification":{"parameter":1}
,".block":{"[index]":1,"[0]":1,"[1]":1}
,"[index]":{"type":1}
,"(0)":{"i2c":1}
,"(1)":{"delay":1}
,"ype-s":{"pecific":1}
,"pecific":{"arameters":1,"ommands":1}
,"arameters":{"i2c":1}
,"i2c-controller-id":{"controller":1}
,"slave-add":{"7-bit":1}
,"reg-data-size":{"register":1}
,"bits":{"8:1":1}
,"8:1":{"byte":1}
,"byte":{"byte":1,"reg-add-size":1,"commands":1}
,"reg-add-size":{"register":1}
,"ommands":{"either":1,"given":1,"pwm":1}
,"<address":{"<mask":1}
,"=<data>":{"support":1,"pwm":1,"pmic":1}
,"facilitate":{"multiple":1}
,"startin":{"index":1}
,"index":{"following":1}
,"[command-index]":{"<addr>":1}
,"<addr>":{"<mask>":1}
,"(for":{"pwm":1}
,"=2)":{"controller-id":1}
,"controller-id":{"\u002F*based":1}
,"\u002F*based":{"platform":1}
,"*\u002Fsource-frq-hz":{"<pwm":1}
,"<pwm":{"clock":1}
,"clock":{"source":1,"clock":1,"control":1,"divider":1,"i2c":1}
,"source":{"freq>":1,"alue":1}
,"freq>":{"\u002F*in":1}
,"\u002F*in":{"*\u002Fperiod-ns":1}
,"*\u002Fperiod-ns":{"<period":1}
,"<period":{"nano":1}
,"nano":{"seconds>":1}
,"seconds>":{"\u002F*pwm":1}
,"\u002F*pwm":{"periods":1}
,"periods":{"*\u002Fmin-microvolts":1}
,"*\u002Fmin-microvolts":{"<vout":1}
,"<vout":{"pwm":1}
,"regulator":{"duty":1,"initialization":1}
,"duty":{"cycle":1}
,"cycle":{"max-microvolts":1,"100>":1}
,"max-microvolts":{"<vout":1}
,"100>":{"init-microvolts":1}
,"init-microvolts":{"<vout":1}
,"<1\u002F0>":{"\u002F*enable":1}
,"\u002F*enable":{"pwm":1}
,"just":{"configure":1}
,"*\u002Ffor":{"example":1}
,"950mv":{"voltage":1}
,"pmic.core.3.block":{"[0]":1,"[1]":1}
,"[0]":{".type":1,".controller-id":1,".source-frq-hz":1,".period-ns":1,".min-microvolts":1,".max-microvolts":1,".init-microvolts":1,".enable":1,".delay":1,".count":1,".i2c-controller":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".commands":1,"ddr>":1,".i2c-controller-id":1,".0x00.0x40":1,".0x07.0xff":1}
,".type":{"pwm":1,"=<0":1,"i2c":1}
,".controller-id":{"gp_pwm6":1}
,"gp_pwm6":{"pmic.core.3.block":1}
,".source-frq-hz":{"=102000000":1}
,"=102000000":{"02mhz":1}
,"02mhz":{"pmic.core.3.block":1}
,".period-ns":{"=2600":1}
,"=2600":{"384k":1}
,"384k":{"eriod":1}
,"eriod":{"pmic.core.3.block":1}
,".min-microvolts":{"=600000":1}
,"=600000":{"pmic.core.3.block":1}
,".max-microvolts":{"=1200000":1}
,"=1200000":{"pmic.core.3.block":1}
,".init-microvolts":{"=950000":1}
,"=950000":{"pmic.core.3.block":1}
,".enable":{"generic":1,"configuring":1}
,"snippets":{"show":1}
,"show":{"common":1}
,"ommon":{"parameters":1}
,"=<u32>":{"pmic.wait-before-start-bus-clear-us":1,"pmic.rail-count":1,"rail-specific":1,"pmic":1,"i2c":1}
,"=<0":{"mmio":1}
,"i2c>":{"pmic":1}
,".delay":{"=<u32>":1,"=10":1,"=1000":1}
,".count":{"=<calc":1,"=<calcu":1,"pmic.generic.1.block":1,"pmic.core.3.block":1}
,"=<calc":{"ulated>":1}
,"ulated>":{"i2c":1}
,".i2c-controller":{"-id":1}
,"-id":{"=<u32>":1,"pmic":1}
,".slave-add":{"=<u":1,"pmic":1,"=0x78":1,"=0x70":1}
,"=<u":{"32>":1}
,"32>":{"pmic":1}
,".reg-data-size":{"=<u32>":1,"pmic":1,"pmic.generic.1.block":1,"pmic.core.3.block":1}
,".reg-add-size":{"=<u32>":1,"i2c":1,"pmic.generic.1.block":1,"pmic.core.3.block":1}
,"mmios":{"pmic":1}
,".commands":{"[0]":1,"[1]":1,"[2]":1,"[3]":1}
,"ddr>":{"<mask>":1}
,"[1]":{"ddr>":1,".type":1,".delay":1,".count":1,".i2c-controller":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".commands":1,".i2c-controller-id":1}
,"[2]":{"ddr>":1}
,"[3]":{"ddr>":1}
,"=<data0>":{"block":1,"example":1}
,"=<calcu":{"lated>":1}
,"lated>":{"i2c":1}
,"(id":{"=1)":1,"=3)":1}
,"=1)":{"data":1}
,"pmic.generic.1.block-count":{"pmic":1}
,"mbldp":{"cnfgglbl1":1}
,"cnfgglbl1":{"bit":1}
,"bit":{"pmic.generic.1.block":1,"expander":1,"value>":1,"(x1":1,"(x2":1,"(x4":1}
,"pmic.generic.1.block":{"[0]":1}
,".i2c-controller-id":{"pmic.generic.1.block":1,"pmic.core.3.block":1}
,"=0x78":{"7bit:0":1,"7bit:0x3c":1}
,"7bit:0":{"x3c":1}
,"x3c":{"pmic.generic.1.block":1}
,"=10":{"pmic.generic.1.block":1,"pwm":1,"dev":1}
,".0x00.0x40":{"=0x":1}
,"=0x":{"core":1}
,"=3)":{"data":1}
,"pmic.core.3.block-count":{"950mv":1}
,"=0x70":{"7bit:0x38":1}
,"7bit:0x38":{"pmic.core.3.block":1}
,"=1000":{"pmic.core.3.block":1}
,".0x07.0xff":{"=0x2e":1}
,"=0x2e":{"gpio3":1}
,"gpio3":{"power":1}
,"down":{"slot":1,"device":1,"temperature":1,"below":1}
,"slot":{"pmic.core.3.block":1}
,"7bit:0x3c":{"pmic.core.3.block":1}
,"consider":{"following":1}
,"correcting":{"pmic":1}
,"default":{"configuration":1,"otp":1,"visible":1}
,"without":{"otp":1}
,"otp":{"required":1,"reconfiguration":1,"values":1}
,"however":{"configuration":1}
,"reconfiguration":{"required":1}
,"using":{"i2c":1,"aotag":1}
,"rite":{"configuration":1}
,"p3310":{"perform":1,"performed":1,"module":1,"pmic":1}
,"baseboard":{"devices":1,"(p2597)":1}
,"ensures":{"setup":1}
,"setup":{"includes":1}
,"includes":{"different":1}
,"performed":{"successfully":1}
,"successfully":{"assist":1}
,"assist":{"removing":1}
,"removing":{"blocks":1}
,"module":{"property":1,"used":1}
,"property":{"comment":1}
,"comment":{"block":1}
,"follow":{"<module_name>":1}
,"<module_name>":{"<device>":1}
,"<device>":{"p3310":1}
,"expander":{"configuration":1,"5v0_hdmi_en":1}
,"p2597":{"baseboa":1}
,"baseboa":{"baseboard":1}
,"(p2597)":{"expander":1}
,"5v0_hdmi_en":{"configuring":1}
,"security":{"configuration":1,"bridge":1}
,"tx1\u002Ftx2":{"devices":1,"platforms":1,"systems":1}
,"separate":{"registers":1}
,"bridge":{"client":1,"firewalls":1}
,"client":{"security":1}
,"firewalls":{"known":1}
,"known":{"ecurity":1}
,"ecurity":{"onfiguration":1}
,"egisters":{"(scrs)":1}
,"(scrs)":{"scrs":1}
,"scrs":{"either":1,"re-configuration":1}
,"nvi":{"dia":1}
,"dia":{"jetson":1}
,"platforms":{"re-configured":1,"ustom":1}
,"re-configured":{"custom":1}
,"custom":{"platforms":1,"latforms":1}
,"ustom":{"configuration":1}
,"list":{"scrs":1,"example":1,"commands":1}
,"re-configuration":{"custom":1}
,"latforms":{"mb1":1}
,"scr":{"register":1,"configuration":1,"<reg_index>":1,"domain":1,"loaded":1,"program":1}
,"addresses":{"hard":1,"indexed":1,"firmware":1}
,"hard":{"coded":1}
,"coded":{"mb1":1}
,"cannot":{"masked":1,"read":1}
,"masked":{"written":1}
,"written":{"registers":1,"default":1,"register":1}
,"ver>\u002Fbct\u002Fauto_scr.cfg":{"usage":1}
,"<reg_index>":{"<exclusion-info>":1,"matching":1}
,"<exclusion-info>":{"=<32":1}
,"=<32":{"bit":1}
,"value>":{"<reg_name>":1}
,"<reg_name>":{"scr":1}
,"matching":{"mb1":1}
,"cfg":{"file":1}
,"beginn":{"ing":1}
,"ing":{"<exclusion-info":1,"bct":1}
,"<exclusion-info":{"following":1}
,"values":{"value":1,"values":1,"configured":1,"desired":1}
,"include":{"regular":1}
,"regular":{"scr":1}
,"loaded":{"bct":1,"mb1\u002Fmb2":1,"firmware":1}
,"cold":{"boot":1}
,"stored":{"context":1}
,"context":{"warm":1}
,"warm":{"boot":1}
,"exclude":{"present":1}
,"present":{"data":1}
,"load":{"data":1}
,"program":{"ming":1,"bct":1,"cpu":1,"apb":1,"axi_cbb":1,"divider":1,"cpu_nic":1,"can0":1,"can1":1,"value":1,"corresponding":1}
,"ming":{"mb2":1}
,"mb2":{"later":1,"carveout":1}
,"later":{"sc7":1}
,"sc7":{"resume":1,"state":1,"disable":1,"disable_sc7":1}
,"resume":{"program":1}
,"exc":{"lude":1}
,"lude":{"warm":1}
,"lists":{"scr":1}
,"scr.134.1":{"=0x20000000":1}
,"=0x20000000":{"gpio_m_scr_00_0":1,"gpio_m_scr_01_0":1}
,"gpio_m_scr_00_0":{"scr.135.1":1}
,"scr.135.1":{"=0x20000000":1}
,"gpio_m_scr_01_0":{"miscellaneous":1}
,"miscellaneous":{"configurations":1}
,"misc":{"ellaneous":1}
,"ellaneous":{"configuration":1}
,"ver>\u002Fbct\u002Ftegra186-mb1-bct-misc-quill":{"-p2382.cfg":1}
,"-p2382.cfg":{"note":1}
,"fields":{"misc.cfg":1,"description":1,"hold":1}
,"misc.cfg":{"follows":1}
,"field":{"description":1,"mb1":1,"directly":1,"dire":1}
,"enable_can_boot":{"ontrol":1,"enable_blacklisting":1}
,"ontrol":{"early":1}
,"early":{"initialization":1}
,"spe-can":{"firmware":1}
,"firmware":{"loading":1,"loaded":1,"b1\u002Fmb2":1,"emory":1}
,"loading":{"spe-r5":1}
,"spe-r5":{"processor":1}
,"processor":{"boot":1}
,"done":{"enable_can_boot":1}
,"enable_blacklisting":{"controls":1,"disable_sc7":1}
,"controls":{"dram":1,"sc7":1,"nable":1}
,"dram":{"ecc":1}
,"ecc":{"blacklisting":1}
,"blacklisting":{"disable":1,"enable":1,"enable_blacklisting":1}
,"disable":{"ecc":1,"sc7":1}
,"disable_sc7":{"controls":1,"fuse_visibility":1}
,"state":{"entry":1}
,"entry":{"enable":1}
,"fuse_visibility":{"certain":1,"enable_vpr_resize":1}
,"certain":{"fuses":1}
,"fuses":{"cannot":1,"fuse_visibility":1}
,"visible":{"field":1}
,"fuse":{"visibility":1}
,"visibility":{"fuses":1}
,"enable_vpr_resize":{"controls":1,"disable_el3_bl":1}
,"nable":{"ment":1,"s\u002Fdisable":1}
,"ment":{"vpr":1}
,"vpr":{"resize":1}
,"resize":{"functionality":1}
,"functionality":{"enable_vpr_resize":1,"enabled":1}
,"disable_el3_bl":{"used":1,"aotag":1}
,"eliminate":{"execution":1}
,"execution":{"el3":1}
,"el3":{"secure":1}
,"start":{"el2":1,"location":1}
,"el2":{"bootloader":1}
,"bootloader":{"disable_el3_bl":1}
,"aotag":{"ao-tag":1,"control":1,"temperature":1}
,"ao-tag":{"register":1}
,"programmed":{"mb1":1}
,"max":{"imum":1,"time":1}
,"imum":{"temperature":1}
,"temperature":{"jetson":1,"exceed":1,"threshold":1,"higher":1,"specified":1,"aotag.cooldown_temp_threshold":1,"above":1}
,"systems":{"allowed":1}
,"exceed":{"limit":1}
,"limit":{"auto-shutdown":1}
,"auto-shutdown":{"triggered":1}
,"triggered":{"aotag":1}
,"boot_temp_threshold":{"boot":1}
,"threshold":{"milli":1,"temperature":1,"aotag.enable_shutdown":1}
,"milli":{"centigrade":1}
,"centigrade":{"temperature":1,"mb1":1}
,"specified":{"fiel":1}
,"fiel":{"mb1":1}
,"wai":{"shut":1}
,"shut":{"down":1}
,"aotag.boot_temp_threshold":{"=105":1}
,"=105":{"000":1}
,"000":{"cooldown_temp_threshold":1}
,"cooldown_temp_threshold":{"cool":1,"cooldown_temp_timeout":1}
,"cool":{"down":1}
,"resumes":{"booting":1}
,"booting":{"device":1}
,"cooled":{"threshold":1}
,"aotag.cooldown_temp_threshold":{"=85000":1}
,"=85000":{"cooldown_temp_timeout":1}
,"cooldown_temp_timeout":{"contains":1,"=30000":1}
,"tempe":{"rature":1}
,"rature":{"down":1}
,"below":{"cooldown_temp_threshold":1}
,"=30000":{"enable_shutdown":1}
,"enable_shutdown":{"enable":1}
,"above":{"boot":1,"details":1}
,"temp":{"erature":1}
,"erature":{"threshold":1}
,"aotag.enable_shutdown":{"clock":1}
,"hold":{"clock":1}
,"divider":{"lues":1,"control":1}
,"lues":{"various":1}
,"various":{"modules":1,"firmware":1}
,"modules":{"mb1":1}
,"programs":{"clock":1}
,"bpmp_cpu_nic_divider":{"program":1}
,"nic":{"divider":1}
,"bpmp":{"frequency":1,"processer":1}
,"frequency":{"value":1,"i2c":1}
,"less":{"value":1}
,"directly":{"written":1}
,"clock.bpmp_cpu_nic_divider":{"bpmp_apb_divider":1}
,"bpmp_apb_divider":{"program":1}
,"apb":{"divider":1,"bus":1}
,"bus":{"fre":1,"frequency":1,"mb1\u002Fmb2":1,"during":1}
,"fre":{"quency":1}
,"quency":{"value":1}
,"dire":{"ctly":1}
,"ctly":{"written":1}
,"clock.bpmp_apb_divider":{"axi_cbb_divider":1}
,"axi_cbb_divider":{"program":1}
,"axi_cbb":{"divider":1}
,"axi-cbb":{"bus":1}
,"clock.axi_cbb_divider":{"se_divider":1}
,"se_divider":{"program":1}
,"controlle":{"frequency":1}
,"clock.se_divider":{"aon_cpu_nic_divider":1}
,"aon_cpu_nic_divider":{"program":1}
,"cpu_nic":{"divider":1}
,"aon":{"(spe":1,"(spe)":1}
,"(spe":{"cpu":1}
,"clock.aon_cpu_nic_divider":{"aon_apb_divider":1}
,"aon_apb_divider":{"program":1}
,"(spe)":{"frequency":1}
,"clock.aon_apb_divider":{"aon_can0_divider":1}
,"aon_can0_divider":{"program":1}
,"can0":{"divider":1,"contr":1}
,"contr":{"oller":1}
,"oller":{"frequency":1}
,"clock.aon_can0_divider":{"aon_can1_divider":1}
,"aon_can1_divider":{"program":1}
,"can1":{"divider":1,"contr":1}
,"clock.aon_can1_divider":{"osc_drive_strength":1}
,"osc_drive_strength":{"unused":1}
,"-pllaon_divp":{"program":1}
,"pll-aon":{"value":1}
,"clock.pllaon_divp":{"pllaon_divn":1}
,"pllaon_divn":{"program":1}
,"clock.pllaon_divn":{"=25":1}
,"=25":{"pllaon_divm":1}
,"pllaon_divm":{"program":1}
,"clock.pllaon_divm":{"cpu":1}
,"initial":{"settings":1,"nafll":1,"addres":1}
,"passed":{"cpu-init":1}
,"cpu-init":{"chang":1,"cpu.ccplex_platform_features":1}
,"chang":{"settings":1}
,"ootcpu":{"specify":1}
,"means":{"a57":1}
,"a57":{"cpu0":1,"cpu.nafll_b":1}
,"cpu0":{"mean":1}
,"mean":{"denv":1}
,"denv":{"er0":1}
,"er0":{"automotive":1}
,"automotive":{"applications":1}
,"applications":{"a57-cpu0":1}
,"a57-cpu0":{"cpu.bootcpu":1}
,"cpu.bootcpu":{"ccplex_platform_features":1}
,"ccplex_platform_features":{"platform":1}
,"feature":{"passed":1}
,"cpu.ccplex_platform_features":{"=0x581":1}
,"=0x581":{"lsr_dvcomp_params_b_cluster":1}
,"lsr_dvcomp_params_b_cluster":{"contains":1}
,"initializing":{"adc":1}
,"adc":{"dvc":1}
,"dvc":{"whi":1}
,"whi":{"need":1}
,"need":{"functional":1,"change":1}
,"functional":{"cpu":1}
,"brou":{"ght":1}
,"ght":{"cpu.lsr_dvcomp_params_b_cluster":1,"cpu.lsr_dvcomp_params_m":1}
,"cpu.lsr_dvcomp_params_b_cluster":{"=0xc0780f05c":1}
,"=0xc0780f05c":{"lsr_dvcomp_params_m":1,"nafll_m_cluster_data":1}
,"lsr_dvcomp_params_m":{"_cluster":1}
,"_cluster":{"contains":1,"=0xc0780f05c":1}
,"cpu.lsr_dvcomp_params_m":{"_cluster":1}
,"nafll_m_cluster_data":{"initial":1}
,"nafll":{"settings":1}
,"cluster":{"denver":1,"a57":1}
,"denver":{"cpu.nafll_m_cluster_data":1}
,"cpu.nafll_m_cluster_data":{"=0x11f04461":1}
,"=0x11f04461":{"nafll_b":1,"ast":1}
,"nafll_b":{"_cluster_data":1}
,"_cluster_data":{"initial":1,"=0x11f04461":1}
,"cpu.nafll_b":{"_cluster_data":1}
,"ast":{"etting":1,"setting":1}
,"etting":{"ast":1,"settings":1}
,"mb1\u002Fmb2":{"virtual":1,"(default":1,"field":1,"bpmp-dma":1}
,"virtual":{"addresses":1,"address":1}
,"b1\u002Fmb2":{"program":1}
,"corresponding":{"physical":1}
,"physical":{"address":1}
,"location":{"loaded":1,"cpu-bl":1,"during":1}
,"emory":{"(dram)":1}
,"(dram)":{"normally":1}
,"normally":{"need":1}
,"change":{"settings":1}
,"bpmp_fw_va":{"virtual":1}
,"bpmp-fw":{"ast.bpmp_fw_va":1}
,"ast.bpmp_fw_va":{"=0x50000000":1}
,"=0x50000000":{"mb2_va":1}
,"mb2_va":{"virtual":1}
,"mb2-fw":{"ast.mb2_va":1}
,"ast.mb2_va":{"=0x52000000":1}
,"=0x52000000":{"sce_fw_va":1}
,"sce_fw_va":{"virtual":1}
,"sce-fw":{"ast.sce_fw_va":1}
,"ast.sce_fw_va":{"=0x70000000":1}
,"=0x70000000":{"apr_va":1}
,"apr_va":{"virtual":1}
,"audio-protected":{"region":1}
,"region":{"used":1}
,"ape-fw":{"ast.apr_va":1,"ast.ape_fw_va":1}
,"ast.apr_va":{"=0xc0000000":1}
,"=0xc0000000":{"pe_fw_va":1}
,"pe_fw_va":{"virtual":1}
,"ast.ape_fw_va":{"=0x80000000":1}
,"=0x80000000":{"carveout":1}
,"carveout":{"settings":1,"field":1,"sw_carveout.cpubl_carveout_addr":1,"sw_carveout.cpubl_carveout_size":1,"sw_carveout.mb2_carveout_size":1}
,"cpubl_carveout_addr":{"start":1}
,"cpu-bl":{"carveout":1}
,"sw_carveout.cpubl_carveout_addr":{"=0x96000000":1}
,"=0x96000000":{"cpubl_carveout_size":1}
,"cpubl_carveout_size":{"size":1}
,"sw_carveout.cpubl_carveout_size":{"=0x02000000":1}
,"=0x02000000":{"mb2_carveout_size":1}
,"mb2_carveout_size":{"size":1}
,"sw_carveout.mb2_carveout_size":{"=0x00400000":1}
,"=0x00400000":{"debug":1}
,"debug":{"debug":1,"functionality":1,"control":1}
,"disabled":{"ing":1}
,"flag":{"debug":1}
,"uart_instance":{"onfigure":1}
,"onfigure":{"uart":1}
,"uart":{"instance":1}
,"console":{"prints":1,"logging":1}
,"prints":{"debug.uart_instance":1}
,"debug.uart_instance":{"enable":1}
,"log":{"nable":1}
,"s\u002Fdisable":{"console":1}
,"logging":{"debug.enable_log":1}
,"debug.enable_log":{"enable_secure_settings":1}
,"enable_secure_settings":{"unused":1}
,"-i2c":{"etting":1}
,"operating":{"frequency":1}
,"(default":{"100":1}
,"100":{"khz)":1}
,"khz)":{"field":1}
,"i2c.0":{"=400":1}
,"=400":{"specify":1}
,"i2c.4":{"=10":1}
,"dev":{"par":1}
,"par":{"eters":1}
,"eters":{"device":1}
,"qspi.clk_src":{"specify":1}
,"alue":{"correspond":1}
,"correspond":{"mention":1}
,"mention":{"qspi":1}
,"qspi":{"clk":1,"bus":1,"mb1\u002Fmb2":1,"devinfo.qspi.trimmer_val1":1,"devinfo.qspi.trimmer_val2":1}
,"clk":{"src":1}
,"src":{"register":1}
,"pllp_out0":{"pllc4_muxed":1}
,"pllc4_muxed":{"devinfo.qspi.clk_src":1}
,"devinfo.qspi.clk_src":{"qspi.clk_div":1}
,"qspi.clk_div":{"clk_div":1}
,"clk_div":{"hence":1}
,"hence":{"&clk_rate":1}
,"&clk_rate":{"=163.2":1}
,"=163.2":{"mhz":1}
,"mhz":{"=(408":1,"\u002F((n":1}
,"=(408":{"mhz":1}
,"\u002F((n":{"\u002F2)":1}
,"\u002F2)":{"1))":1}
,"1))":{"devinfo.qspi.clk_div":1}
,"devinfo.qspi.clk_div":{"qspi.width":1}
,"qspi.width":{"specify":1}
,"transfer":{"bit":1,"mode":1,"dma":1,"pio":1}
,"(x1":{"mode)":1}
,"mode)":{"bit":1,"devinfo.qspi.width":1}
,"(x2":{"mode)":1}
,"(x4":{"mode)":1}
,"devinfo.qspi.width":{"qspi.dma_type":1}
,"qspi.dma_type":{"specify":1}
,"dma":{"transfer":1,"qspi":1,"devinfo.qspi.xfer_mode":1}
,"mode":{"transfer":1}
,"bpmp-dma":{"used":1,"devinfo.qspi.dma_type":1}
,"gpc-dma":{"bpmp-dma":1}
,"devinfo.qspi.dma_type":{"qspi.xfer_mode":1}
,"qspi.xfer_mode":{"specify":1}
,"pio":{"dma":1}
,"devinfo.qspi.xfer_mode":{"qspi.read_dummy_cycles":1}
,"qspi.read_dummy_cycles":{"dummy":1}
,"dummy":{"cycles":1}
,"cycles":{"allow":1,"data":1}
,"allow":{"device":1}
,"internal":{"circuit":1}
,"circuit":{"additional":1}
,"additional":{"time":1}
,"accessing":{"initial":1}
,"addres":{"location":1}
,"ios":{"don\u2019t":1}
,"don\u2019t":{"care":1}
,"care":{"may":1}
,"high":{"impedanc":1}
,"impedanc":{"devinfo.qspi.read_dummy_cycles":1}
,"devinfo.qspi.read_dummy_cycles":{"qspi.trimmer_val1":1}
,"qspi.trimmer_val1":{"tx_clk_tap_delay":1}
,"tx_clk_tap_delay":{"qspi":1}
,"devinfo.qspi.trimmer_val1":{"qspi.trimmer_val2":1}
,"qspi.trimmer_val2":{"rx_clk_tap_delay":1}
,"rx_clk_tap_delay":{"qspi":1}
,"devinfo.qspi.trimmer_val2":{"watchdog":1}
,"watchdog":{"imer":1,"timer":1}
,"imer":{"ontroller":1}
,"ettings":{"settings":1}
,"timer":{"controller":1,"registe":1,"register":1}
,"egister":{"values":1}
,"bpmp_wdtcr":{"contains":1}
,"processer":{"watchdog":1}
,"registe":{"value":1}
,"wdt.bpmp_wdtcr":{"=0x710640":1}
,"=0x710640":{"configures":1,"top_wdt2_wdtcr":1}
,"configures":{"100sec":1}
,"100sec":{"sce_wdtcr":1}
,"sce_wdtcr":{"contains":1}
,"sce":{"processer":1}
,"wdt.sce_wdtcr":{"=0x707103":1}
,"=0x707103":{"aon_wdtcr":1,"pmic":1}
,"aon_wdtcr":{"contains":1}
,"aon\u2019s":{"watchdog":1}
,"wdt.aon_wdtcr":{"=0x700000":1}
,"=0x700000":{"rtc2_ao_wdtcr":1,"top_wdt0_wdtcr":1}
,"rtc2_ao_wdtcr":{"contains":1}
,"rtc2_ao":{"watchdog":1}
,"wdt.rtc2_ao_wdtcr":{"=0x700000":1}
,"top_wdt0_wdtcr":{"contains":1}
,"top_wdt0":{"watchdog":1}
,"wdt.top_wdt0_wdtcr":{"=0x715016":1}
,"=0x715016":{"top_wdt1_wdtcr":1}
,"top_wdt1_wdtcr":{"contains":1}
,"top_wdt1":{"watchdog":1}
,"wdt.top_wdt1_wdtcr":{"=0x710640":1}
,"top_wdt2_wdtcr":{"contains":1}
,"top_wdt2":{"watchdog":1}
,"wdt.top_wdt2_wdtcr":{"=0x707103":1}
,"created":{"manually":1}
,"manually":{"follows":1}
,"enabl":{"setting":1}
,"desired":{"voltage":1}
,"repr":{"ogram":1}
,"ogram":{"voltage":1}
,"recommended":{"boot":1}
,"per":{"boot":1,"rail":1}
,"recommendation":{"information":1}
,"once":{"information":1}
,"collected":{"split":1}
,"comm":{"ands":1}
,"ands":{"blocks":1}
,"mult":{"iple":1}
,"iple":{"commands":1}
,"ommunicat":{"device":1}
,"anything":{"different":1}
,"details":{"bootr":1,"ashing":1}
,"bootr":{"bootrom":1}
,"bootrom":{"configuration":1}
,"ile":{"created":1}
,"send":{"device":1}
,"reset":{"path":1,"paths":1}
,"path":{"possible":1,"independently":1,"ake":1,"aocommand":1}
,"possible":{"type":1}
,"paths":{"collect":1,"init":1}
,"collect":{"inform":1}
,"inform":{"ation":1}
,"team":{"sets":1}
,"independently":{"pickup":1}
,"pickup":{"command":1}
,"ake":{"list":1}
,"communicate":{"device":1}
,"thing":{"different":1}
,"put":{"blocks":1}
,"aoblocks":{"similarly":1,"reset":1}
,"similarly":{"aoblocks":1}
,"init":{"ialize":1}
,"ialize":{"different":1}
,"aocommand":{"aoblock":1}
,"aoblock":{"indexes":1}
,"indexes":{"create":1}
,"onfig":{"uration":1}
,"ashing":{"information":1}
,"flashing":{"refer":1,"boot":1}
,"refer":{"flashing":1}
,"loader":{"kernel":1}
}
;Search.control.loadWordPairs(pairs);
