var pairs =
{
"tx1":{"boot":1,"bootrom":1,"tegraboot":1,"cboot":1}
,"boot":{"flow":1,"software":1,"logo":1,"media":1,"configuration":1,"loader":1,"oader":1,"oftware":1,"ecovery":1,"\u002Fflashing":1,"responsible":1,"read":1,"stops":1,"path":1,"kernel":1}
,"flow":{"primary":1,"control":1,"follows":1}
,"primary":{"function":1,"cpu":1}
,"function":{"jetson":1}
,"jetson":{"tx1":1}
,"software":{"initialize":1,"performs":1,"fol":1}
,"initialize":{"soc":1}
,"soc":{"(system":1}
,"(system":{"chip)":1}
,"chip)":{"including":1}
,"including":{"initializing":1,"limi":1,"size":1}
,"initializing":{"mc\u002Femc\u002Fcpu":1,"firmware":1,"boot":1}
,"mc\u002Femc\u002Fcpu":{"setting":1}
,"setting":{"security":1,"memory":1}
,"security":{"parameters":1,"creating":1}
,"parameters":{"loading":1,"used":1,"initializing":1}
,"loading":{"different":1,"recovery":1}
,"different":{"firmware":1,"config":1}
,"firmware":{"maintaining":1,"flashing":1,"boot":1,"(fw)":1,"components":1}
,"maintaining":{"chain":1}
,"chain":{"trust":1}
,"trust":{"setting":1}
,"memory":{"carveouts":1}
,"carveouts":{"different":1,"completing":1}
,"flashing":{"device":1,"support":1}
,"device":{"booting":1,"tree":1,"trees":1}
,"booting":{"operating":1,"kernel":1}
,"operating":{"system":1}
,"system":{"additionally":1}
,"additionally":{"jetson":1}
,"performs":{"operations":1}
,"operations":{"defin":1}
,"defin":{"product":1}
,"product":{"requirements":1}
,"requirements":{"including":1}
,"limi":{"ted":1}
,"ted":{"initialization":1}
,"initialization":{"hdmi\u002Fdsi":1,"bct":1,"load":1,"passes":1}
,"hdmi\u002Fdsi":{"displaying":1}
,"displaying":{"boot":1}
,"logo":{"flow":1,"\u002Fbmp":1}
,"control":{"boot":1,"cboot":1}
,"fol":{"lows":1}
,"lows":{"bootrom":1}
,"bootrom":{"jetson":1,"(br)":1,"boot":1,"hardware":1,"uses":1}
,"(br)":{"hard-wired":1}
,"hard-wired":{"tegra":1}
,"tegra":{"chip":1}
,"chip":{"nitializes":1}
,"nitializes":{"boot":1}
,"media":{"loads":1,"multiple":1}
,"loads":{"bootloaders":1}
,"bootloaders":{"firmware":1}
,"multiple":{"copies":1}
,"copies":{"bootrom":1}
,"configuration":{"table":1,"parameters":1}
,"table":{"(bct":1}
,"(bct":{"may":1}
,"may":{"stored":1}
,"stored":{"start":1,"separate":1}
,"start":{"boot-media":1,"run":1}
,"boot-media":{"bct":1}
,"bct":{"con":1,"contains":1}
,"con":{"tains":1}
,"tains":{"configuration":1}
,"used":{"bootrom":1,"cold":1,"mobile":1}
,"hardware":{"initialization":1}
,"contains":{"information":1}
,"information":{"oot":1,"verify":1,"u-boot":1}
,"oot":{"loader":1,"u-boot":1,"follows":1}
,"loader":{"(bl)":1,"boot":1,"flash":1,"support":1,"used":1,"boots":1,"ses":1,"device":1,"nvidia":1}
,"(bl)":{"including":1}
,"size":{"entry":1}
,"entry":{"point":1}
,"point":{"load":1}
,"load":{"address":1,"ing":1}
,"address":{"hash":1,"boot":1}
,"hash":{"bootrom":1}
,"uses":{"information":1}
,"verify":{"boot":1}
,"follows":{"boot":1,"tegraboot":1,"oot":1}
,"oader":{"omponents":1}
,"omponents":{"jetson":1}
,"flash":{"components":1}
,"components":{"tegraboot":1,"security":1,"oot":1}
,"tegraboot":{"aka":1,"jetson":1,"(nvtboot)":1,"used":1,"follows":1,"cpu":1}
,"aka":{"tboot":1,"nvtboot-cpu":1}
,"tboot":{"just":1,"cpu-bl":1}
,"just":{"tboot":1}
,"cpu-bl":{"aka":1,"parameters":1}
,"nvtboot-cpu":{"oot":1}
,"u-boot":{"tegraboot":1,"boot":1,"default":1,"customization":1}
,"(nvtboot)":{"first":1}
,"first":{"boot":1}
,"oftware":{"component":1}
,"component":{"loaded":1,"tos":1}
,"loaded":{"sysram":1}
,"sysram":{"runs":1}
,"runs":{"bpmp":1}
,"bpmp":{"two":1,"bpmp-fw":1}
,"two":{"variants":1}
,"variants":{"tegraboot":1}
,"cold":{"boot":1}
,"ecovery":{"boot":1}
,"\u002Fflashing":{"generated":1}
,"generated":{"using":1}
,"using":{"different":1,"bootloader":1}
,"config":{"uration":1}
,"uration":{"file":1}
,"file":{"files":1}
,"files":{"egra":1}
,"egra":{"boot":1}
,"responsible":{"oading":1,"parsing":1}
,"oading":{"initializing":1}
,"(fw)":{"component":1}
,"tos":{"details":1,"tos":1,"completes":1}
,"details":{"firmware":1}
,"creating":{"carveouts":1}
,"completing":{"cpu":1}
,"cpu":{"initialization":1,"add":1,"boot":1,"starts":1}
,"ing":{"next":1,"flashing":1,"rcm":1,"pmic":1,"bootloader":1,"device":1}
,"next":{"stage":1}
,"stage":{"boot":1}
,"support":{"ing":1,"display":1}
,"rcm":{"boot":1}
,"read":{"ing":1}
,"pmic":{"reset":1}
,"reset":{"reason":1}
,"reason":{"load":1}
,"bootloader":{"device":1,"dtb":1}
,"tree":{"pass":1,"load":1,"booting":1}
,"pass":{"ing":1,"control":1}
,"stops":{"execution":1}
,"execution":{"ccplex":1}
,"ccplex":{"booted":1}
,"booted":{"components":1}
,"add":{"rollback":1}
,"rollback":{"prevention":1}
,"prevention":{"using":1}
,"dtb":{"perform":1,"training":1}
,"perform":{"emc":1}
,"emc":{"training":1}
,"training":{"upd":1,"results":1}
,"upd":{"ate":1}
,"ate":{"kernel":1}
,"kernel":{"dtb":1,"support":1,"(lk)":1,"chaining":1,"supporting":1,"unhalts":1}
,"results":{"pass":1}
,"cboot":{"cboot":1,"jetson":1,"primary":1,"feature-rich":1,"starts":1,"el2":1,"responsible":1}
,"mobile":{"platforms":1}
,"platforms":{"cold":1}
,"path":{"cboot":1}
,"feature-rich":{"boot":1}
,"boots":{"kernel":1}
,"display":{"boot":1}
,"\u002Fbmp":{"splash":1}
,"splash":{"based":1}
,"based":{"little":1}
,"little":{"kernel":1}
,"(lk)":{"open":1}
,"open":{"source":1}
,"source":{"boot":1}
,"ses":{"interrupt":1,"cdf":1}
,"interrupt":{"scheduling":1}
,"scheduling":{"frameworks":1}
,"frameworks":{"lkc":1}
,"lkc":{"ses":1}
,"cdf":{"fra":1}
,"fra":{"meworks":1}
,"meworks":{"drivers":1}
,"drivers":{"libraries":1}
,"libraries":{"soon":1}
,"soon":{"cpu":1}
,"starts":{"running":1,"el3":1}
,"running":{"cboot":1}
,"el3":{"mode":1}
,"mode":{"begins":1,"ernel":1}
,"begins":{"executing":1}
,"executing":{"tos":1}
,"completes":{"initialization":1}
,"passes":{"control":1}
,"el2":{"mode":1}
,"ernel":{"separate":1}
,"separate":{"device":1,"partitio":1}
,"trees":{"stored":1}
,"partitio":{"cboot":1}
,"parsing":{"cpu-bl":1}
,"chaining":{"u-boot":1}
,"supporting":{"update":1}
,"update":{"mechanism":1}
,"mechanism":{"loading":1}
,"recovery":{"kernel":1}
,"unhalts":{"bpmp":1}
,"bpmp-fw":{"start":1}
,"run":{"ning":1}
,"ning":{"components":1}
,"default":{"boot":1}
,"nvidia":{"tegr":1}
,"tegr":{"linux":1}
,"linux":{"driver":1}
,"driver":{"pac":1}
,"pac":{"kage":1}
,"kage":{"information":1}
}
;Search.control.loadWordPairs(pairs);
