var pairs =
{
"kernel":{"customization":1,"used":1,"sources":1,"source":1,"sou":1,"subdi":1,"follow":1,"prerequisites":1,"shell":1,"build":1,"including":1,"modules":1,"irectory":1,"headers":1,"sourc":1,"mod":1,"dules":1,"image":1,"execute":1,"modu":1,"module":1}
,"customization":{"manually":1}
,"manually":{"rebuild":1,"extract":1,"download":1,"built":1,"downloading":1}
,"rebuild":{"kernel":1}
,"used":{"package":1,"typical":1,"provide":1}
,"package":{"internet":1,"prior":1}
,"internet":{"access":1}
,"access":{"required":1}
,"required":{"obtaining":1,"ernel":1,"environment":1}
,"obtaining":{"kernel":1}
,"sources":{"git":1,"kernel":1,"source":1,"alternative":1,"browser":1,"relea":1,"$tar":1,"<defconfig>":1,"building":1}
,"git":{"prerequisites":1,"install":1,"follo":1,"port":1,"manually":1}
,"prerequisites":{"installed":1,"downloaded":1}
,"installed":{"git":1,"utilities":1,"kernel":1,"modules":1}
,"install":{"git":1,"git-core":1,"utilities":1,"build-essential":1,"kerne":1}
,"follo":{"wing":1}
,"wing":{"command":1}
,"command":{"$sudo":1,"$tegra":1,"$cd":1,"prepare":1}
,"$sudo":{"apt":1,"arch=arm64":1,"modules_prepare":1}
,"apt":{"install":1}
,"git-core":{"system":1}
,"system":{"default":1,"xport":1,"replace":1,"archive":1,"repare":1}
,"default":{"git":1}
,"port":{"9418":1}
,"9418":{"open":1}
,"open":{"outbound":1}
,"outbound":{"connections":1}
,"connections":{"sync":1}
,"sync":{"kernel":1,"linux":1,"sources":1}
,"source":{"running":1,"revision":1,"_release":1,"file":1,"extracted":1,"code":1,"tree":1,"source":1,"directory":1,"required":1}
,"running":{"source_sync.sh":1,"apply_binaries.sh":1}
,"source_sync.sh":{"script":1}
,"script":{"$.\u002Fsource_sync.sh":1}
,"$.\u002Fsource_sync.sh":{"prompted":1}
,"prompted":{"enter":1}
,"enter":{"tag":1}
,"tag":{"name":1,"however":1,"provided":1,"tegra-l4t*manually":1}
,"name":{"provided":1}
,"provided":{"release":1,"fol":1}
,"release":{"notes":1,"binary":1,"tags":1,"package":1}
,"notes":{"sync":1}
,"linux":{"tag":1}
,"however":{"tag":1}
,"revision":{"release":1}
,"binary":{"built":1,"cross":1}
,"built":{"list":1,"nvidia":1,"build":1}
,"list":{"available":1}
,"available":{"release":1}
,"tags":{"$git":1}
,"$git":{"tag":1}
,"tegra-l4t*manually":{"downloading":1}
,"downloading":{"expanding":1}
,"expanding":{"kernel":1}
,"alternative":{"download":1}
,"download":{"kernel":1,"expand":1,"l4t":1,"build":1}
,"sou":{"rce":1}
,"rce":{"files":1}
,"files":{"manually":1}
,"extract":{"possible":1,"tbz2":1,"kernel":1,"following":1}
,"possible":{"recommended":1}
,"recommended":{"instead":1}
,"instead":{"git":1}
,"expand":{"kernel":1}
,"browser":{"navigate":1}
,"navigate":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"locate":1}
,"locate":{"download":1}
,"l4t":{"sources":1,"kernel":1}
,"relea":{"extract":1}
,"tbz2":{"file":1}
,"file":{"$tar":1,"$cd":1,"follow":1}
,"$tar":{"xjf":1,"--owner":1,"-xjf":1}
,"xjf":{"source":1,"kernel_src-<board>":1}
,"_release":{".tbz2":1}
,".tbz2":{"extract":1,"<board>":1}
,"$cd":{"sources":1,"<kernel_source>":1,"<modules_install_path>":1,"\u002Fusr\u002Fsrc\u002Flinux-headers-$(uname":1,"<local_src_dir>":1,"<local":1,"<path_to_module_source>":1}
,"kernel_src-<board>":{".tbz2":1}
,"<board>":{"jetson":1}
,"jetson":{"tx1":1,"tx2":1}
,"tx1":{"tx1":1,"jetson":1,"tegra21_defconfig":1}
,"tx2":{"tx2":1,"kernel":1,"tegra18_defconfig":1}
,"extracted":{"kernel":1,"release":1}
,"subdi":{"rectory":1}
,"rectory":{"building":1}
,"building":{"nvidia":1,"aarch":1,"out-of-tree":1,"entire":1,"external":1}
,"nvidia":{"kernel":1}
,"follow":{"steps":1,"instructions":1}
,"steps":{"procedure":1}
,"procedure":{"build":1}
,"build":{"idia":1,"process":1,"tegra":1,"reference":1,"kernel":1,"external":1,"out-of-tree":1}
,"idia":{"kernel":1}
,"downloaded":{"kernel":1}
,"code":{"installed":1}
,"utilities":{"required":1,"command":1}
,"ernel":{"build":1}
,"process":{"install":1,"may":1}
,"build-essential":{"build":1}
,"tegra":{"kernel":1,"system":1}
,"shell":{"variable":1}
,"variable":{"command":1,"$export":1,"described":1}
,"$tegra":{"_kernel":1}
,"_kernel":{"_out=<outdir>":1}
,"_out=<outdir>":{"<outdir>":1}
,"<outdir>":{"desired":1,"contained":1}
,"desired":{"destination":1}
,"destination":{"compiled":1}
,"compiled":{"kerne":1}
,"kerne":{"kernel":1,"modules":1,"source":1}
,"may":{"create":1}
,"create":{"additional":1,".config":1}
,"additional":{"dir":1}
,"dir":{"ectories":1}
,"ectories":{"adjacent":1}
,"adjacent":{"directory":1}
,"directory":{"choose":1,"contains":1,"commands":1,"option":1}
,"choose":{"valu":1}
,"valu":{"<outdir>":1}
,"contained":{"within":1}
,"within":{"empty":1}
,"empty":{"parent":1}
,"parent":{"director":1}
,"director":{"example":1}
,"example":{"$home\u002Fkernel-out\u002Fkernel":1}
,"$home\u002Fkernel-out\u002Fkernel":{"cross-compiling":1}
,"cross-compiling":{"non-tegra":1,"ensure":1}
,"non-tegra":{"system":1,"stem":1}
,"xport":{"following":1}
,"following":{"environment":1,"commands":1,"command":1,"comma":1,"archive":1,"comm":1}
,"environment":{"variable":1,"variables":1}
,"$export":{"cross_compile=<crossbin>":1}
,"cross_compile=<crossbin>":{"<crossbin>":1}
,"<crossbin>":{"prefix":1}
,"prefix":{"applied":1}
,"applied":{"form":1}
,"form":{"path":1}
,"path":{"lchain":1,"tool":1}
,"lchain":{"cross":1}
,"cross":{"compilation":1}
,"compilation":{"targeting":1}
,"targeting":{"arm64":1}
,"arm64":{"e.g":1,"tool":1}
,"e.g":{"gcc":1}
,"gcc":{"reference":1}
,"reference":{"arm64":1,"toolchains":1,"toolchain":1}
,"tool":{"chain":1}
,"chain":{"<aarch64_toolchain_install":1,"binary":1}
,"<aarch64_toolchain_install":{">\u002Fbin\u002Faarch64-unknown-linux-gnu-see":1}
,">\u002Fbin\u002Faarch64-unknown-linux-gnu-see":{"building":1}
,"aarch":{"toolchain":1}
,"toolchain":{"glibc":1,"<aarch64_toolchain_install>\u002Fbin\u002Faarch64-unknown-li":1}
,"glibc":{"information":1}
,"information":{"download":1}
,"toolchains":{"execute":1,"prepare":1}
,"execute":{"following":1}
,"commands":{"create":1,"build":1,"install":1,"<top>\u002Flinux_for_tegra\u002Fkernel\u002Fkernel_headers.tbz2":1}
,".config":{"file":1}
,"<kernel_source>":{"$mkdir":1,"directory":1}
,"$mkdir":{"$tegra_kernel_out":1}
,"$tegra_kernel_out":{"$make":1,"o=option":1}
,"$make":{"arch=arm64":1}
,"arch=arm64":{"o=$tegra_kernel_out":1,"modules_prepare":1,"<kernel_source_directory>":1}
,"o=$tegra_kernel_out":{"<defconfig>":1,"<n>":1,"modules_insta":1}
,"<defconfig>":{"<kernel_source>":1,"jetson":1}
,"contains":{"kernel":1}
,"tegra21_defconfig":{"jetson":1}
,"tegra18_defconfig":{"execute":1}
,"including":{"dtbs":1}
,"dtbs":{"modules":1}
,"modules":{"$make":1,"$sudo":1,"using":1,"used":1,"procedures":1,"specify":1,"compatible":1,"cross-compiling":1}
,"<n>":{"<n>":1,"indicates":1,"modules_prepare":1}
,"indicates":{"number":1}
,"number":{"parallel":1,"cpus":1}
,"parallel":{"processes":1}
,"processes":{"used":1,"typical":1}
,"typical":{"value":1}
,"value":{"number":1,"$tegra_kernel_out":1,"preparing":1,"building":1}
,"cpus":{"system":1,"stem":1}
,"replace":{"linux_for_tera\u002Fkernel\u002Fimage":1,"contents":1,"kernel":1}
,"linux_for_tera\u002Fkernel\u002Fimage":{"$tegra_kernel_out\u002Farch\u002Farm64\u002Fboot\u002Fimage":1}
,"$tegra_kernel_out\u002Farch\u002Farm64\u002Fboot\u002Fimage":{"replace":1}
,"contents":{"linux_for_tegra\u002Fkernel\u002Fdtb\u002Fwith":1,"$tegra_kernel_out\u002Farch\u002Farm64\u002Fboot\u002Fdts\u002F7":1}
,"linux_for_tegra\u002Fkernel\u002Fdtb\u002Fwith":{"contents":1}
,"$tegra_kernel_out\u002Farch\u002Farm64\u002Fboot\u002Fdts\u002F7":{"xecute":1}
,"xecute":{"following":1}
,"modules_insta":{"\u005Cinstall_mod_path=linux_for_tegra\u002Frootfs\u002F8":1}
,"\u005Cinstall_mod_path=linux_for_tegra\u002Frootfs\u002F8":{"optionally":1}
,"optionally":{"rchive":1}
,"rchive":{"installed":1}
,"using":{"following":1,"manually":1}
,"<modules_install_path>":{"$tar":1}
,"--owner":{"root":1}
,"root":{"--group":1,"-cjf":1}
,"--group":{"root":1}
,"-cjf":{"kernel_suppleme":1}
,"kernel_suppleme":{"nts.tbz2":1}
,"nts.tbz2":{"\u005Clib\u002Fmodules":1}
,"\u005Clib\u002Fmodules":{"installed":1}
,"provide":{"ontents":1}
,"ontents":{"\u002Flib\u002Fmodules\u002F<kernel_version>":1}
,"\u002Flib\u002Fmodules\u002F<kernel_version>":{"target":1}
,"target":{"system":1}
,"archive":{"replace":1,"place":1}
,"irectory":{"extracted":1}
,"prior":{"running":1}
,"apply_binaries.sh":{"linux_for_tegra\u002Fkernel\u002Fkernel_supplements.tbz2":1}
,"linux_for_tegra\u002Fkernel\u002Fkernel_supplements.tbz2":{"preparing":1}
,"preparing":{"build":1,"l4t":1,"nvidia":1}
,"external":{"kernel":1}
,"procedures":{"describe":1}
,"describe":{"prepare":1}
,"prepare":{"kernel":1,"l4t":1,"kerne":1}
,"headers":{"kernel":1,"tegra":1,"following":1,"non-tegra":1}
,"sourc":{"tree":1}
,"tree":{"allow":1,"built":1,"building":1,"without":1}
,"allow":{"building":1}
,"out-of-tree":{"kernel":1,"modules":1}
,"mod":{"ule":1}
,"ule":{"prepare":1}
,"repare":{"kernel":1}
,"comma":{"nds":1}
,"nds":{"$cd":1}
,"\u002Fusr\u002Fsrc\u002Flinux-headers-$(uname":{"$sudo":1}
,"modules_prepare":{"building":1,"indicates":1}
,"specify":{"\u002Fusr\u002Fsrc\u002Flinux-headers-<kernel_version>":1,"<local":1,"kernel":1,"ker":1}
,"\u002Fusr\u002Fsrc\u002Flinux-headers-<kernel_version>":{"o=option":1}
,"o=option":{"values":1,"value":1}
,"values":{"preparing":1,"using":1}
,"stem":{"extract":1,"building":1}
,"place":{"cal":1}
,"cal":{"directory":1}
,"<top>\u002Flinux_for_tegra\u002Fkernel\u002Fkernel_headers.tbz2":{"$cd":1}
,"<local_src_dir>":{"$tar":1}
,"-xjf":{"<top>\u002Flinux_for_tegra\u002Fkernel\u002Fkernel_hea":1}
,"<top>\u002Flinux_for_tegra\u002Fkernel\u002Fkernel_hea":{"ders.tbz2":1}
,"ders.tbz2":{"export":1}
,"export":{"following":1}
,"<aarch64_toolchain_install>\u002Fbin\u002Faarch64-unknown-li":{"nux-gnu-see":1}
,"nux-gnu-see":{"building":1}
,"comm":{"ands":1}
,"ands":{"$cd":1}
,"<local":{"src":1}
,"src":{"dir>\u002Flinux-headers-<kernel":1}
,"dir>\u002Flinux-headers-<kernel":{"version":1,"version>":1}
,"version":{"$make":1}
,"version>":{"o=option":1}
,"dules":{"building":1}
,"option":{"value":1}
,"compatible":{"lin":1}
,"lin":{"kernel":1}
,"without":{"building":1}
,"entire":{"kernel":1}
,"image":{"extract":1}
,"variables":{"create":1}
,"instructions":{"provided":1}
,"fol":{"lowing":1}
,"lowing":{"topics":1}
,"topics":{"obtaining":1}
,"modu":{"les":1}
,"les":{"$make":1}
,"ker":{"nel":1}
,"nel":{"source":1}
,"ensure":{"cross_compile":1}
,"cross_compile":{"environment":1}
,"described":{"previ":1}
,"previ":{"ous":1}
,"ous":{"sections":1}
,"sections":{"execute":1}
,"module":{"$cd":1}
,"<path_to_module_source>":{"$make":1}
,"<kernel_source_directory>":{"\u005Co=<kernel_output_directory>":1}
,"\u005Co=<kernel_output_directory>":{"m=$(pwd)":1}
,"m=$(pwd)":{"modules":1}
}
;Search.control.loadWordPairs(pairs);
