var pairs =
{
"camera":{"software":1,"solution":1,"upport":1,"architecture":1,"core":1,"gstreamer":1,"partners":1,"api":1,"apis":1,"configuratio":1,"contain":1,"records":1,"features":1,"utput":1,"format":1,"work":1,"module":1,"modules":1}
,"software":{"development":1,"solution":1,"architecture":1,"releases":1,"stack":1,"converter)":1}
,"development":{"solution":1,"options":1,"process":1,"customization":1,"custom":1,"nvidia":1,"complete":1}
,"solution":{"document":1,"explains":1,"usb":1,"preferred":1}
,"document":{"describes":1}
,"describes":{"nvidia":1}
,"nvidia":{"jetson":1,"supported":1,"camera":1,"components":1,"provides":1,"tunes":1,"tegra":1,"write":1,"embedded":1,"multimedia":1,"jetpack":1}
,"jetson":{"tx1":1,"platform":1,"embedded":1,"devel":1,"multimedia":1,"ltimedia":1}
,"tx1":{"camera":1}
,"explains":{"nvidia":1}
,"supported":{"recommended":1,"using":1}
,"recommended":{"camera":1}
,"architecture":{"fast":1,"stack":1,"includes":1}
,"fast":{"optimal":1}
,"optimal":{"time":1}
,"time":{"market":1}
,"market":{"development":1}
,"options":{"outlined":1,"conrol":1,"control":1}
,"outlined":{"explained":1}
,"explained":{"customize":1}
,"customize":{"camera":1}
,"usb":{"yuv":1,"(uvc)":1,"libargus":1,"mera":1,"camera":1}
,"yuv":{"bayer":1,"sensor":1,"images":1,"sens":1}
,"bayer":{"camera":1,"sensor":1,"data":1,"sensors":1}
,"upport":{"additionally":1}
,"additionally":{"debugging":1}
,"debugging":{"approaches":1}
,"approaches":{"explored":1,"validating":1}
,"explored":{"aid":1}
,"aid":{"development":1}
,"process":{"camera":1}
,"stack":{"nvidia":1,"nvcamerasrc":1,"example":1}
,"includes":{"nvidia":1,"following":1,"sensor":1,"initial":1}
,"components":{"allow":1,"libargus":1}
,"allow":{"ease":1}
,"ease":{"development":1}
,"customization":{"camera":1}
,"following":{"nvidia":1}
,"libargus":{"rovides":1,"gstreamer":1,"perferred":1,"ow-level":1,"apis":1,"jetpack":1}
,"rovides":{"low-level":1}
,"low-level":{"api":1}
,"api":{"based":1,"v4l2src":1,"matrix":1,"libargus":1,"reference":1,"provides":1,"installed":1,"tab":1,"enable":1}
,"based":{"camera":1,"media":1}
,"core":{"stack":1,"release":1}
,"nvcamerasrc":{"nvidia":1,"plugin":1,"gstreamer":1,"num-buffers=200":1,"sensor-id=0":1}
,"gstreamer":{"plugin":1,"(gst-nvarguscamerasrc\u002Fnvcamerasrc":1,"multimedia":1,"nvcamerasrc":1,"nvarguscamer":1,"v4l2":1,"jetson":1}
,"plugin":{"ovides":1,"provides":1,"nvcamerasrc":1,"enable":1,"nvarguscamerasrc":1,"supporte":1}
,"ovides":{"options":1}
,"conrol":{"isp":1}
,"isp":{"properties":1,"(csi":1,"v4l2":1,"post-processing":1,"support":1,"configuration":1,"usb":1,"bypass":1}
,"properties":{"argus":1,"using":1}
,"argus":{"amera":1,"api":1,"libargus":1}
,"amera":{"src":1}
,"src":{"nvidia":1}
,"provides":{"options":1,"ov5693":1,"additional":1,"samples":1}
,"control":{"isp":1}
,"using":{"argus":1,"gstreamer":1,"v4l2":1,"third":1}
,"v4l2src":{"standard":1,"num-buffers=200":1,"device=\u002Fdev\u002Fvideo0":1}
,"standard":{"linux":1}
,"linux":{"v4l2":1}
,"v4l2":{"application":1,"functionality":1,"sensor":1,"v4l2":1,"*drivers":1,"api":1,"dri":1,"driver":1,"source":1,"ioctl":1,"gstreamer":1}
,"application":{"uses":1,"validate":1}
,"uses":{"direct":1,"tegra":1}
,"direct":{"kernel":1}
,"kernel":{"ioctl":1}
,"ioctl":{"call":1,"directly":1,"verify":1}
,"call":{"access":1}
,"access":{"v4l2":1,"note":1}
,"functionality":{"nvidia":1,"during":1}
,"ov5693":{"bayer":1,"camera":1}
,"sensor":{"sample":1,"jetson":1,"support":1,"tuning":1,"driver":1,"characterization":1,"stream":1,"usb":1,"format":1,"bring":1}
,"sample":{"nvidia":1}
,"tunes":{"sensor":1}
,"platform":{"drive":1,"(jep)":1}
,"drive":{"code":1}
,"code":{"based":1}
,"media":{"controller":1}
,"controller":{"framework":1}
,"framework":{"available":1}
,"available":{".\u002Fkernel\u002Fkernel4.4\u002Fdrivers\u002Fmedia\u002Fi2c\u002Fov5693.c":1,"camera":1,"nvidia":1,"download":1,"jetson":1}
,".\u002Fkernel\u002Fkernel4.4\u002Fdrivers\u002Fmedia\u002Fi2c\u002Fov5693.c":{"nvidia":1}
,"additional":{"sensor":1}
,"support":{"bsp":1,"work":1,"package":1,"peripheral":1,"enable":1,"built-in":1,"available":1,"camera":1}
,"bsp":{"software":1}
,"releases":{"developers":1}
,"developers":{"work":1}
,"work":{"nvidi":1,"involved":1,"isp":1}
,"nvidi":{"certified":1}
,"certified":{"camera":1}
,"partners":{"bayer":1,"symlinks":1,"community":1}
,"tuning":{"support":1,"tools":1}
,"involved":{"includes":1}
,"driver":{"development":1,"programming":1,"interface":1}
,"custom":{"tools":1,"camera":1}
,"tools":{"sensor":1,"operating":1,"application":1}
,"characterization":{"image":1}
,"image":{"quality":1}
,"quality":{"tuning":1}
,"operating":{"mechanisms":1,"remo":1}
,"mechanisms":{"part":1}
,"part":{"public":1}
,"public":{"jetson":1}
,"embedded":{"platform":1,"download":1}
,"(jep)":{"board":1}
,"board":{"support":1}
,"package":{"release":1,"jetpack":1}
,"release":{"information":1,"packag":1,"eglstreams":1,"symlink":1}
,"information":{"sensor":1}
,"tegra":{"v4l2":1,"isp":1}
,"programming":{"gui":1}
,"gui":{"camera":1}
,"matrix":{"matrix":1,"camera":1}
,"apis":{"available":1,"nvidia":1,"preview":1}
,"configuratio":{"follows":1}
,"follows":{"uses":1,"gst-launch-1.0":1,"(based":1,"\u002F\u002Fexport":1}
,"(csi":{"interface)":1}
,"interface)":{"tegra":1,"usb":1,"camera":1}
,"(uvc)":{"*(usb":1}
,"*(usb":{"interface)":1}
,"(gst-nvarguscamerasrc\u002Fnvcamerasrc":{"v4l2":1}
,"*drivers":{"provided":1}
,"provided":{"nvidia":1,"tools":1,"isp":1}
,"write":{"drivers":1}
,"drivers":{"customer":1}
,"customer":{"support":1}
,"peripheral":{"bus":1}
,"bus":{"device":1}
,"device":{"-ethernet":1}
,"-ethernet":{"-non-uvc":1}
,"-non-uvc":{"usb":1}
,"perferred":{"path":1}
,"path":{"access":1}
,"note":{"default":1,"csi":1}
,"default":{"ov5693":1}
,"contain":{"integrated":1}
,"integrated":{"isp":1}
,"reference":{"camera":1,"click":1,"sensors":1,"jetpack":1}
,"records":{"bayer":1}
,"data":{"approaches":1}
,"validating":{"testing":1}
,"testing":{"v4l2":1}
,"dri":{"ver":1}
,"ver":{"once":1}
,"once":{"driver":1}
,"complete":{"provided":1}
,"validate":{"test":1}
,"test":{"v4l2":1}
,"interface":{"general":1}
,"general":{"gstreamer":1}
,"multimedia":{"operations":1,"user":1,"api":1,"com":1}
,"operations":{"multimedia":1}
,"user":{"guide":1}
,"guide":{"available":1}
,"download":{"cente":1,"nvidia":1,"nter":1}
,"cente":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"applications":1,"view":1}
,"applications":{"sing":1,"using":1}
,"sing":{"libargus":1}
,"ow-level":{"apis":1}
,"samples":{"demonstrate":1}
,"demonstrate":{"libargus":1}
,"preview":{"capture":1,"file":1,"hdmi":1,"screen":1}
,"capture":{"record":1,"bayer":1}
,"record":{"sensor":1}
,"stream":{"multimedia":1}
,"installed":{"nvidia":1}
,"jetpack":{"cannot":1,"available":1,"details":1,"documentation":1}
,"cannot":{"insta":1}
,"insta":{"lled":1}
,"lled":{"standalone":1}
,"standalone":{"package":1}
,"nter":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
,"view":{"multimedia":1}
,"click":{"api":1}
,"tab":{"top":1}
,"top":{"page":1}
,"page":{"applications":1}
,"enable":{"isp":1}
,"post-processing":{"bayer":1,"nvidia":1}
,"sensors":{"perform":1,"note":1}
,"perform":{"format":1}
,"format":{"conversion":1,"1080p\u002F30\u002Fbggr":1,"80p\u002F30\u002Fbggr":1,"480p\u002F30\u002Fyuy2":1,"480p\u002F30\u002Fuyvy":1,"1080p\u002F30\u002Frg10":1}
,"conversion":{"generate":1}
,"generate":{"output":1}
,"output":{"directly":1}
,"directly":{"yuv":1,"v4l2":1}
,"mera":{"example":1}
,"example":{"ayer":1,"bayer":1,"usb":1,"capture":1}
,"ayer":{"senso":1}
,"senso":{"format":1}
,"1080p\u002F30\u002Fbggr":{"save":1}
,"save":{"preview":1}
,"file":{"follows":1}
,"gst-launch-1.0":{"nvcamerasrc":1,"nvarguscamerasrc":1,"v4l2src":1}
,"num-buffers=200":{"sensor-id=0":1,"\u0027video\u002Fx-raw":1,"device=\u002Fdev":1}
,"sensor-id=0":{"\u0027video\u002Fx-raw":1}
,"\u0027video\u002Fx-raw":{"(memory:nvmm)":1,"format=yuy2":1}
,"(memory:nvmm)":{"width=1920":1,"format=(string)":1}
,"width=1920":{"heigh":1,"height=1080":1}
,"heigh":{"t=1080":1,"t=(int)":1}
,"t=1080":{"framerate=30\u002F1":1}
,"framerate=30\u002F1":{"format=nv12":1,"videoconvert":1}
,"format=nv12":{"omxh264enc":1,"nvoverlaysink":1}
,"omxh264enc":{"qtmux":1,"mux":1}
,"qtmux":{"filesink":1}
,"filesink":{"location=test.mp4":1,"location=test.m":1}
,"location=test.mp4":{"render":1,"-ev":1}
,"render":{"preview":1}
,"hdmi":{"screen":1}
,"screen":{"follows":1}
,"height=1080":{"framerat":1,"framerate=30\u002F1":1,"format=(string":1,"xelformat=rg10":1}
,"framerat":{"e=30\u002F1":1}
,"e=30\u002F1":{"format=nv12":1}
,"nvoverlaysink":{"applications":1}
,"nvarguscamer":{"asrc":1}
,"asrc":{"plugin":1}
,"nvarguscamerasrc":{"gstreamer":1,"num-buffers=200":1,"video\u002Fx-raw":1}
,"supporte":{"camera":1}
,"features":{"argus":1}
,"80p\u002F30\u002Fbggr":{"save":1}
,"video\u002Fx-raw":{"(mem":1}
,"(mem":{"ory:nvmm)":1}
,"ory:nvmm)":{"width=1920":1}
,"format=(string":{"nv12":1}
,"nv12":{"framerate=(fraction)":1}
,"framerate=(fraction)":{"30\u002F1":1}
,"30\u002F1":{"nvoverlaysink":1,"nvvidco":1,"xvimagesin":1}
,"source":{"plug":1}
,"plug":{"ing":1}
,"ing":{"yuv":1}
,"utput":{"yuv":1}
,"images":{"without":1}
,"without":{"isp":1}
,"480p\u002F30\u002Fyuy2":{"save":1}
,"(based":{"software":1,"hardware":1}
,"converter)":{"gst-launch-1.0":1}
,"device=\u002Fdev":{"\u002Fvideo0":1}
,"\u002Fvideo0":{"\u0027video\u002Fx-raw":1}
,"format=yuy2":{"width=640":1}
,"width=640":{"height=480":1}
,"height=480":{"framerate=30\u002F1":1,"framer":1}
,"videoconvert":{"omxh264enc":1}
,"mux":{"filesink":1}
,"-ev":{"render":1,"yuv":1,"applications":1}
,"\u002F\u002Fexport":{"display=:0":1}
,"display=:0":{"operating":1}
,"remo":{"console":1}
,"console":{"gst-launch-1.0":1}
,"device=\u002Fdev\u002Fvideo0":{"\u0027video":1,"\u0027vi":1}
,"\u0027video":{"\u002Fx-raw":1}
,"\u002Fx-raw":{"format=yuy2":1,"format=(string)":1}
,"framer":{"ate=30\u002F1":1}
,"ate=30\u002F1":{"xvimagesink":1}
,"xvimagesink":{"-ev":1}
,"sens":{"format":1}
,"480p\u002F30\u002Fuyvy":{"save":1}
,"hardware":{"accelerated":1}
,"accelerated":{"converter)":1}
,"\u0027vi":{"deo\u002Fx-raw":1}
,"deo\u002Fx-raw":{"format=(string)":1}
,"format=(string)":{"uyvy":1,"nv1":1}
,"uyvy":{"width=(int)":1}
,"width=(int)":{"640":1}
,"640":{"ight=(int)":1,"heigh":1}
,"ight=(int)":{"480":1}
,"480":{"framerate=(fraction)":1}
,"nvvidco":{"\u0027video\u002Fx-raw":1}
,"nv1":{"omxh264enc":1}
,"location=test.m":{"-ev":1}
,"t=(int)":{"480":1}
,"xvimagesin":{"-ev":1}
,"verify":{"basic":1}
,"basic":{"functionality":1}
,"during":{"sensor":1}
,"bring":{"example":1}
,"1080p\u002F30\u002Frg10":{"v4l2-ctl":1}
,"v4l2-ctl":{"--set-fmt-video=width=1920":1}
,"--set-fmt-video=width=1920":{"height=1080":1}
,"xelformat=rg10":{"--stream-mmap":1}
,"--stream-mmap":{"--stream-count=1":1}
,"--stream-count=1":{"\u002Fdev\u002Fvideo0":1}
,"\u002Fdev\u002Fvideo0":{"--stream-to=ov5693.raw":1}
,"--stream-to=ov5693.raw":{"isp":1}
,"built-in":{"camera":1}
,"packag":{"includes":1}
,"initial":{"isp":1}
,"configuration":{"files":1}
,"files":{"reference":1}
,"csi":{"cameras":1}
,"cameras":{"integrated":1}
,"bypass":{"mode":1}
,"mode":{"provided":1}
,"devel":{"oper":1}
,"oper":{"kit":1}
,"kit":{"(ov5693)":1}
,"(ov5693)":{"raw":1}
,"raw":{"camera":1}
,"module":{"dditional":1}
,"dditional":{"isp":1}
,"modules":{"supported":1}
,"third":{"party":1}
,"party":{"partners":1}
,"symlinks":{"changed":1}
,"changed":{"mesa":1}
,"mesa":{"installation":1,"egl":1}
,"installation":{"installation":1,"mesa":1}
,"egl":{"may":1,"including":1}
,"may":{"create":1}
,"create":{"\u002Fusr\u002Flib":1}
,"\u002Fusr\u002Flib":{"\u002F<abi_directory":1,"\u002F<abi_directory>\u002Ftegra-egl\u002Flibegl.so":1}
,"\u002F<abi_directory":{">\u002Flibegl.so":1}
,">\u002Flibegl.so":{"symlink":1}
,"symlink":{"overwriting":1,"implement":1,"replaced":1}
,"overwriting":{"symlink":1}
,"implement":{"ation":1}
,"ation":{"library":1}
,"library":{"used":1}
,"used":{"instead":1}
,"instead":{"\u002Fusr\u002Flib":1}
,"\u002F<abi_directory>\u002Ftegra-egl\u002Flibegl.so":{"disrupts":1}
,"disrupts":{"client":1}
,"client":{"egl":1}
,"including":{"libra":1}
,"libra":{"ries":1}
,"ries":{"release":1}
,"eglstreams":{"release":1}
,"replaced":{"system":1}
,"system":{"rebooted":1}
,"rebooted":{"fixing":1}
,"fixing":{"issue":1}
,"issue":{"reboot":1}
,"reboot":{"imilar":1}
,"imilar":{"workarounds":1}
,"workarounds":{"applied":1}
,"applied":{"previous":1}
,"previous":{"eleases":1}
,"eleases":{"libraries":1}
,"libraries":{"libgl":1}
,"libgl":{"libg":1}
,"libg":{"references":1}
,"references":{"details":1}
,"details":{"integrating":1,"argus":1,"building":1}
,"integrating":{"jetson":1}
,"com":{"ponents":1}
,"ponents":{"using":1}
,"ltimedia":{"api":1}
,"documentation":{"details":1}
,"building":{"custom":1}
,"preferred":{"partners":1}
,"community":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fcommunity\u002Fpa":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fcommunity\u002Fpa":{"rtners":1}
}
;Search.control.loadWordPairs(pairs);
