var pairs =
{
"secure":{"pmc":1,"scratch":1}
,"pmc":{"scratch":1}
,"scratch":{"register":1,"setting":1,"trigger":1,"sc8":1,"context":1,"registers":1}
,"register":{"configurations":1,"size":1,"address":1,"onoffcnfg2":1,"onoffcnfg1":1}
,"configurations":{"boo":1}
,"boo":{"trom":1}
,"trom":{"note":1}
,"note":{"jetson":1}
,"jetson":{"tx1\u002Ftx2":1}
,"tx1\u002Ftx2":{"devices":1}
,"devices":{"cold":1}
,"cold":{"boot":1,"power":1,"boot)":1}
,"boot":{"path":1,"rom":1}
,"path":{"may":1}
,"may":{"required":1}
,"required":{"program":1,"trigger":1}
,"program":{"i2c":1}
,"i2c":{"mmio":1,"commands":1,"count":1,"type-specific":1,"type":1,"slave-add":1,"informatio":1}
,"mmio":{"commands":1,"i2c":1}
,"commands":{"bring":1,"provided":1,"includes":1,"block":1,"configuration":1,"prefixed":1,"commands":1,"either":1,"indexed":1,"given":1,"ent":1,"[command-index]":1,"case":1}
,"bring":{"pmic":1}
,"pmic":{"rai":1}
,"rai":{"otp":1}
,"otp":{"values":1}
,"values":{"ypical":1}
,"ypical":{"reset":1}
,"reset":{"levels":1,"cause":1,"level":1,"event":1,"logic":1,"paths":1,"cases":1,"sensor":1,"case":1,"conditions":1,"condition":1,"name":1,"soft":1,"commands":1}
,"levels":{"follows":1}
,"follows":{"reset":1,"parameter":1,"bootrom":1}
,"cause":{"reset":1}
,"level":{"context":1}
,"context":{"preservation":1,"i2c":1}
,"preservation":{"required":1}
,"trigger":{"new":1,"sensor\u002Fao":1,"shut":1,"l0\u002Fl1":1}
,"new":{"reset":1}
,"event":{"cold":1}
,"power":{"fifth":1,"cycling":1}
,"fifth":{"wdt":1}
,"wdt":{"expiration":1}
,"expiration":{"trigger":1,"dram":1}
,"sensor\u002Fao":{"tag":1}
,"tag":{"trigger":1}
,"shut":{"down":1}
,"down":{"boot":1}
,"rom":{"sensor":1,"usin":1,"issue":1,"commands":1}
,"sensor":{"sw_main":1,"hsm":1}
,"sw_main":{"depends":1}
,"depends":{"scratch":1}
,"setting":{"hsm":1}
,"hsm":{"scratch":1,"reset":1,"example":1}
,"l0\u002Fl1":{"mb1":1}
,"mb1":{"fourth":1,"device-side":1,"bct":1}
,"fourth":{"wdt":1}
,"dram":{"internal":1,"scratch":1}
,"internal":{"ram":1}
,"ram":{"reset":1}
,"logic":{"sc7":1}
,"sc7":{"warm":1,"exit":1,"sc8":1}
,"warm":{"dram":1,"scratch":1}
,"sc8":{"warm":1,"exit":1,"soft-reset":1}
,"provided":{"boot":1,"parameter":1}
,"usin":{"scratch":1}
,"registers":{"mb1":1,"based":1,"reset":1}
,"device-side":{"code":1}
,"code":{"confi":1}
,"confi":{"gures":1}
,"gures":{"scratch":1}
,"based":{"plat":1}
,"plat":{"form":1}
,"form":{"specific":1}
,"specific":{"information":1,"parameters":1}
,"information":{"bootrom":1}
,"bootrom":{"reset":1,"requires":1,"<reset-name>":1}
,"paths":{"mb1":1}
,"bct":{"bootrom":1}
,"requires":{"data":1}
,"data":{"secure":1,"treated":1,"follows":1}
,"cases":{"boot":1}
,"issue":{"commands":1}
,"includes":{"watchdog":1}
,"watchdog":{"expiry":1}
,"expiry":{"watchdog":1,"sc7":1}
,"exit":{"sc8":1,"sw-reset":1}
,"sw-reset":{"ao-tag\u002Fsensor":1}
,"ao-tag\u002Fsensor":{"reset":1}
,"case":{"three":1,"bootrom.sensor-aotag.aocommand":1}
,"three":{"sets":1,"blocks":1}
,"sets":{"blocks":1,"described":1}
,"blocks":{"commands":1,"block":1,"first":1,"boot":1,"called":1,"init":1}
,"block":{"multiple":1,"id>":1,"parameters":1,"configuration":1,"type":1,"i2c":1,"commands":1}
,"multiple":{"blocks":1,"commands":1}
,"configuration":{"format":1,"data":1}
,"format":{"blocks":1,"<address>":1,"commands":1}
,"first":{"reset":1}
,"conditions":{"initialized":1,"support":1}
,"initialized":{"blocks":1}
,"prefixed":{"bootrom":1}
,"condition":{"three":1,"block":1}
,"called":{"aocommand":1}
,"aocommand":{"bootrom":1,"reset":1}
,"<reset-name>":{".aocommand":1}
,".aocommand":{"[0]":1,"[1]":1,"[2]":1}
,"[0]":{"=<ao":1,".command-retries-count":1,".delay-between-commands-us":1,".wait-before-start-bus-clear-us":1,".block-count":1,".block":1,".type":1,".slave-add":1,".reg-data-size":1,".reg-add-size":1,".count":1,".commands":1,".0x42":1,"bootrom.soft-reset.aocommand":1}
,"=<ao":{"block":1}
,"id>":{"bootrom":1,"absence":1,"<reset_name>":1}
,"[1]":{"=<ao":1,".0x41":1,".command-retries-count":1,".delay-between-commands-us":1,".wait-before-start-bus-clear-us":1,".block-count":1,".block":1}
,"[2]":{"=<ao":1}
,"absence":{"aocommand":1}
,"name":{"configuration":1}
,"treated":{"command":1}
,"command":{"reset":1,"attempts":1,"wait":1,"block-count":1}
,"parameters":{"parameters":1,"used":1,"i2c":1,"follows":1}
,"used":{"block":1}
,"parameter":{"description":1,"wait-before-start-bus-clear-us":1}
,"description":{"aoblock-count":1,"i2c-controller-id":1}
,"aoblock-count":{"specifies":1}
,"specifies":{"number":1,"wait":1,"mand":1,"umber":1}
,"number":{"sets":1,"allowed":1,"blocks":1}
,"described":{"ile":1}
,"ile":{"command-retries-count":1}
,"command-retries-count":{"specifies":1}
,"allowed":{"command":1}
,"attempts":{"delay-between-commands-us":1}
,"delay-between-commands-us":{"specifies":1}
,"wait":{"timeout":1,"time":1}
,"timeout":{"microseconds":1}
,"microseconds":{"befor":1,"provided":1,"ssuing":1}
,"befor":{"issuing":1}
,"issuing":{"bus":1}
,"bus":{"clear":1}
,"clear":{"command":1}
,"time":{"calculated":1,"microseconds":1}
,"calculated":{"<<n":1}
,"<<n":{"microseconds":1}
,"wait-before-start-bus-clear-us":{"specifies":1}
,"ssuing":{"bus":1}
,"block-count":{"specifies":1}
,"type":{"specifies":1,"either":1,"specific":1,"bootrom.aoblock":1}
,"mand":{"type":1}
,"either":{"mmio":1}
,"count":{"specifies":1}
,"umber":{"commands":1}
,"type-specific":{"parameters":1}
,"i2c-controller-id":{"controller":1}
,"controller":{"i2c":1}
,"slave-add":{"7-bit":1}
,"7-bit":{"slave":1}
,"slave":{"address":1}
,"address":{"reg-data-size":1,"size":1}
,"reg-data-size":{"register":1}
,"size":{"bits":1}
,"bits":{"8:1":1}
,"8:1":{"byte":1}
,"byte":{"byte":1,"reg-add-size":1,"commands":1}
,"reg-add-size":{"register":1}
,"informatio":{"format":1}
,"<address>":{"=<data>":1}
,"=<data>":{"support":1,"reset":1}
,"support":{"write-only":1,"three":1}
,"write-only":{"sequence":1}
,"sequence":{"commands":1,"starting":1}
,"indexed":{"facilitate":1}
,"facilitate":{"multiple":1}
,"given":{"block":1}
,"ent":{"device":1}
,"device":{"sequence":1}
,"starting":{"dex":1}
,"dex":{"following":1}
,"following":{"format":1,"watchdog5":1}
,"[command-index]":{"<addr>":1}
,"<addr>":{"=<data>":1}
,"init":{"ialized":1}
,"ialized":{"follows":1}
,"<reset_name>":{"following":1}
,"watchdog5":{"watchdog4":1}
,"watchdog4":{"sc7":1}
,"soft-reset":{"sensor-aotag":1}
,"sensor-aotag":{"vfsensor":1}
,"vfsensor":{"hsm":1}
,"example":{"bootrom.aoblock-count":1}
,"bootrom.aoblock-count":{"automatic":1}
,"automatic":{"power":1}
,"cycling":{"max77620":1}
,"max77620":{"register":1}
,"onoffcnfg2":{"bit":1}
,"bit":{"sft_rst_wk":1,"sft_rst":1}
,"sft_rst_wk":{"(default":1,"register":1}
,"(default":{"cold":1}
,"boot)":{"register":1}
,"onoffcnfg1":{"bit":1}
,"sft_rst":{"bootrom.aoblock":1}
,"bootrom.aoblock":{"[0]":1,"[1]":1}
,".command-retries-count":{"bootrom.aoblock":1}
,".delay-between-commands-us":{"bootrom.aoblock":1}
,".wait-before-start-bus-clear-us":{"bootrom.aoblock":1}
,".block-count":{"bootrom.aoblock":1}
,".block":{"[0]":1}
,".type":{"i2c":1}
,".slave-add":{"=0x3c":1}
,"=0x3c":{"it:0x3c":1}
,"it:0x3c":{"bootrom.aoblock":1}
,".reg-data-size":{"bootrom.aoblock":1}
,".reg-add-size":{"bootrom.aoblock":1}
,".count":{"bootrom.aoblock":1}
,".commands":{"[0]":1,"[1]":1}
,".0x42":{"=0xd":1,"=0x5":1}
,"=0xd":{"bootrom.aoblock":1}
,".0x41":{"=0xf":1}
,"=0xf":{"shutdown":1}
,"shutdown":{"max77620":1,"sensor\u002Fao-tag":1}
,"=0x5":{"bootrom.aoblock":1}
,"sensor\u002Fao-tag":{"reset":1}
,"soft":{"reset":1}
,"bootrom.sensor-aotag.aocommand":{"[0]":1}
,"bootrom.soft-reset.aocommand":{"[0]":1}
}
;Search.control.loadWordPairs(pairs);
