var pairs =
{
"legal":{"information":1}
,"information":{"notice":1,"furnished":1,"infringement":1}
,"notice":{"nvidia":1}
,"nvidia":{"design":1,"makes":1,"assumes":1,"specifications":1,"products":1,"trademarks":1,"nvidia":1,"logo":1,"united":1}
,"design":{"specifications":1}
,"specifications":{"reference":1,"mentioned":1}
,"reference":{"boards":1}
,"boards":{"files":1}
,"files":{"drawings":1}
,"drawings":{"diagnostics":1}
,"diagnostics":{"lists":1}
,"lists":{"ocuments":1}
,"ocuments":{"(together":1}
,"(together":{"separately":1}
,"separately":{"materials":1}
,"materials":{"provided":1,"express":1}
,"provided":{"nvidia":1}
,"makes":{"warranties":1}
,"warranties":{"express":1,"including":1}
,"express":{"implied":1,"written":1}
,"implied":{"sta":1,"conditions":1,"warra":1}
,"sta":{"tutory":1}
,"tutory":{"otherwise":1}
,"otherwise":{"respect":1,"patent":1}
,"respect":{"materials":1}
,"conditions":{"represent":1}
,"represent":{"ations":1,"arm":1}
,"ations":{"warranties":1}
,"including":{"implied":1}
,"warra":{"nty":1}
,"nty":{"condition":1}
,"condition":{"title":1}
,"title":{"merchantability":1}
,"merchantability":{"satisf":1}
,"satisf":{"actory":1}
,"actory":{"quality":1}
,"quality":{"fitness":1}
,"fitness":{"particular":1}
,"particular":{"purpose":1}
,"purpose":{"on-infringement":1}
,"on-infringement":{"hereby":1}
,"hereby":{"excluded":1}
,"excluded":{"maximu":1}
,"maximu":{"extent":1}
,"extent":{"permitted":1}
,"permitted":{"law":1}
,"law":{"information":1}
,"furnished":{"believed":1}
,"believed":{"accurate":1}
,"accurate":{"reliable":1}
,"reliable":{"however":1}
,"however":{"nvidia":1}
,"assumes":{"responsibility":1}
,"responsibility":{"consequences":1}
,"consequences":{"information":1}
,"infringement":{"patents":1}
,"patents":{"third":1}
,"third":{"parties":1}
,"parties":{"may":1}
,"may":{"result":1,"tradem":1}
,"result":{"rom":1}
,"rom":{"license":1}
,"license":{"granted":1,"hdmi":1}
,"granted":{"implication":1}
,"implication":{"otherwise":1}
,"patent":{"patent":1,"nvidia":1}
,"mentioned":{"publication":1}
,"publication":{"subject":1,"supersedes":1}
,"subject":{"change":1}
,"change":{"without":1}
,"without":{"notic":1}
,"notic":{"publication":1}
,"supersedes":{"replaces":1}
,"replaces":{"formation":1}
,"formation":{"previously":1}
,"previously":{"supplied":1}
,"supplied":{"nvidia":1}
,"products":{"authorized":1}
,"authorized":{"critical":1}
,"critical":{"mponents":1}
,"mponents":{"life":1}
,"life":{"support":1}
,"support":{"devices":1}
,"devices":{"systems":1}
,"systems":{"withou":1}
,"withou":{"express":1}
,"written":{"approval":1}
,"approval":{"nvidia":1}
,"trademarks":{"nvidia":1,"registered":1,"arm":1}
,"logo":{"cuda":1,"high-definition":1}
,"cuda":{"jetson":1}
,"jetson":{"tegra":1}
,"tegra":{"tensorrt":1}
,"tensorrt":{"trademarks":1}
,"registered":{"trademarks":1,"trademark":1}
,"united":{"states":1}
,"states":{"countr":1}
,"countr":{"ies":1}
,"ies":{"company":1}
,"company":{"product":1,"arm":1}
,"product":{"names":1}
,"names":{"may":1,"property":1}
,"tradem":{"arks":1}
,"arks":{"respective":1}
,"respective":{"companies":1,"holders":1}
,"companies":{"associated":1}
,"associated":{"android":1}
,"android":{"robot":1}
,"robot":{"reproduced":1}
,"reproduced":{"modified":1}
,"modified":{"ork":1}
,"ork":{"created":1}
,"created":{"shared":1}
,"shared":{"google":1}
,"google":{"used":1}
,"used":{"according":1,"represent":1}
,"according":{"terms":1}
,"terms":{"described":1}
,"described":{"creative":1}
,"creative":{"ommons":1}
,"ommons":{"3.0":1}
,"3.0":{"attribution":1}
,"attribution":{"license":1}
,"hdmi":{"hdmi":1,"logo":1,"licensing":1}
,"high-definition":{"multimedi":1}
,"multimedi":{"interface":1}
,"interface":{"trademarks":1}
,"trademark":{"hdmi":1}
,"licensing":{"llc":1}
,"llc":{"arm":1}
,"arm":{"amba":1,"powered":1,"limited":1,"used":1,"holdings":1,"arm":1,"korea":1,"tai":1,"france":1,"consulting":1,"germany":1,"embedded":1,"norway":1,"sweden":1}
,"amba":{"arm":1}
,"powered":{"registered":1}
,"limited":{"cortex":1,"brands":1,"regional":1,"arm":1}
,"cortex":{"mpcore":1}
,"mpcore":{"mali":1}
,"mali":{"trademarks":1}
,"brands":{"product":1}
,"property":{"respective":1}
,"holders":{"arm":1}
,"holdings":{"plc":1}
,"plc":{"operat":1}
,"operat":{"ing":1}
,"ing":{"company":1}
,"regional":{"subsidia":1}
,"subsidia":{"ries":1}
,"ries":{"arm":1}
,"korea":{"limited":1}
,"tai":{"wan":1}
,"wan":{"limited":1}
,"france":{"sas":1}
,"sas":{"arm":1}
,"consulting":{"(shang":1}
,"(shang":{"hai)":1}
,"hai)":{"ltd":1}
,"ltd":{"arm":1}
,"germany":{"gmbh":1}
,"gmbh":{"arm":1}
,"embedded":{"tech":1}
,"tech":{"nologies":1}
,"nologies":{"pvt":1}
,"pvt":{"ltd":1}
,"norway":{"arm":1}
,"sweden":{"201":1}
,"201":{"nvidia":1}
}
;Search.control.loadWordPairs(pairs);
