var pairs =
{
"tx2":{"boot":1,"bootrom":1,"microboot1":1,"tegraboot":1,"tegraboot-cpu":1,"cboot":1,"mb1":1}
,"boot":{"flow":1,"software":1,"logo":1,"media":1,"configuration":1,"loader":1,"oader":1,"sequence":1,"rom":1,"downloading":1,"ecovery":1,"generated":1,"tegraboot-bpmp":1,"read":1,"similar":1,"except":1,"tegraboot-cpu":1,"integrating":1,"path":1,"based":1,"kernel":1,"components":1}
,"flow":{"primary":1,"control":1,"follows":1,"rcm":1}
,"primary":{"function":1,"cpu":1}
,"function":{"jetson":1}
,"jetson":{"tx2":1}
,"software":{"initialize":1,"performs":1,"fol":1,"support":1,"design":1,"libraries":1,"compon":1}
,"initialize":{"soc":1,"sdram":1}
,"soc":{"(system":1,"program":1}
,"(system":{"chip)":1}
,"chip)":{"including":1}
,"including":{"initializing":1,"limi":1,"size":1,"required":1}
,"initializing":{"mc\u002Femc\u002Fcpu":1,"rails":1,"firmware":1,"boot":1}
,"mc\u002Femc\u002Fcpu":{"setting":1}
,"setting":{"security":1,"memory":1}
,"security":{"parameters":1,"fabric":1,"settings":1,"creating":1}
,"parameters":{"loading":1,"used":1,"initializing":1}
,"loading":{"different":1,"binaries":1,"initializing":1,"recovery":1}
,"different":{"firmware":1,"mb1_recovery.bin":1,"config":1}
,"firmware":{"maintaining":1,"flashing":1,"initialization":1,"initializes":1,"(fw)":1}
,"maintaining":{"chain":1}
,"chain":{"trust":1}
,"trust":{"setting":1}
,"memory":{"carveouts":1,"allocation":1,"gpu":1}
,"carveouts":{"different":1,"support":1,"completing":1}
,"flashing":{"device":1,"support":1,"rcm":1,"tegraboot-cpu":1}
,"device":{"booting":1,"tree":1,"normal":1,"rcm":1,"tboot":1,"trees":1}
,"booting":{"operating":1,"kernel":1}
,"operating":{"system":1}
,"system":{"additionally":1}
,"additionally":{"jetson":1}
,"performs":{"operations":1}
,"operations":{"defin":1}
,"defin":{"product":1}
,"product":{"requirements":1}
,"requirements":{"including":1}
,"limi":{"ted":1}
,"ted":{"initialization":1}
,"initialization":{"hdmi\u002Fd":1,"bct":1,"security":1,"include":1,"load":1,"gives":1,"passes":1}
,"hdmi\u002Fd":{"displaying":1}
,"displaying":{"boot":1}
,"logo":{"flow":1,"erified":1}
,"control":{"boot":1,"mb1":1,"bpmp-fw":1,"tegraboot-cpu":1,"cboot":1}
,"fol":{"lows":1}
,"lows":{"bootrom":1}
,"bootrom":{"jetson":1,"(br)":1,"boot":1,"hardware":1,"uses":1,"sign":1}
,"(br)":{"hard-wired":1}
,"hard-wired":{"tegra":1}
,"tegra":{"chip":1}
,"chip":{"nitializes":1}
,"nitializes":{"boot":1}
,"media":{"loads":1,"multiple":1}
,"loads":{"microboot1":1}
,"microboot1":{"(mb1)":1,"(mb1":1}
,"(mb1)":{"boot":1,"first":1}
,"multiple":{"copies":1}
,"copies":{"bootrom":1}
,"configuration":{"table":1,"parameters":1,"includes":1,"tabl":1}
,"table":{"(br-bct":1,"b1-bct)":1}
,"(br-bct":{"may":1}
,"may":{"stored":1}
,"stored":{"start":1,"separate":1}
,"start":{"boot-media":1}
,"boot-media":{"-bct":1}
,"-bct":{"contains":1}
,"contains":{"configuration":1,"information":1,"binaries":1}
,"used":{"bootrom":1,"cold":1,"mobile":1}
,"hardware":{"initialization":1}
,"bct":{"contains":1,"tegraboot":1}
,"information":{"oot":1,"verify":1,"mb1":1,"u-boot":1}
,"oot":{"loader":1,"follows":1,"u-boot":1}
,"loader":{"(bl)":1,"boot":1,"flash":1,"components":1,"tboot":1,"component":1,"support":1,"used":1,"boots":1,"ses":1,"device":1,"nvidia":1}
,"(bl)":{"including":1}
,"size":{"entry":1}
,"entry":{"point":1}
,"point":{"load":1}
,"load":{"address":1,"firmware":1,"next":1,"ing":1}
,"address":{"hash":1,"cpu-bl":1}
,"hash":{"bootrom":1}
,"uses":{"information":1}
,"verify":{"boot":1}
,"follows":{"boot":1,"ommon":1,"tegraboot":1,"cboot":1,"oot":1}
,"oader":{"omponents":1}
,"omponents":{"jetson":1}
,"flash":{"components":1}
,"components":{"common":1,"instead":1,"tboot":1,"oot":1}
,"common":{"driver":1,"across":1,"pool":1}
,"driver":{"framework":1,"moreover":1,"pac":1}
,"framework":{"(cdf)":1,"mb1":1,"follows":1,"consists":1}
,"(cdf)":{"microboot1":1,"note":1}
,"(mb1":{"tboot":1}
,"tboot":{"-bpmp":1,"-cpu":1}
,"-bpmp":{"(mb2":1,"tegraboot":1,"(mb2)":1,"portion":1,"responsible":1,"follows":1}
,"(mb2":{"cpu-bl":1}
,"cpu-bl":{"tboot":1,"giv":1,"parameters":1}
,"-cpu":{"cboot":1,"processor":1,"jetson":1,"support":1,"tested":1,"follows":1}
,"cboot":{"u-boot":1,"jetson":1,"primary":1,"feature-rich":1,"el2":1,"responsible":1}
,"u-boot":{"common":1,"built":1,"boot":1,"default":1,"customization":1}
,"mb1":{"tegraboot":1,"considered":1,"provides":1,"extension":1,"mb1":1,"responsible":1,"boot":1,"owned":1,"reads":1,"bct":1,"component":1,"platform":1}
,"tegraboot":{"-bpmp":1,"-cpu\u002Fcboot":1,"jetson":1,"boot":1,"runs":1,"-cpu":1}
,"-cpu\u002Fcboot":{"needs":1}
,"needs":{"several":1}
,"several":{"driver":1}
,"moreover":{"libraries":1}
,"libraries":{"common":1,"binaries":1,"called":1,"modules":1,"cryptographic":1,"decompression":1,"linuxboot":1,"note":1}
,"across":{"boot":1}
,"instead":{"using":1}
,"using":{"separate":1,"common":1,"boot":1,"different":1}
,"separate":{"sets":1,"device":1,"partitio":1}
,"sets":{"drivers":1}
,"drivers":{"libraries":1,"emmc":1,"uart":1,"debug":1}
,"binaries":{"share":1,"loading":1,"blob":1,"transferre":1,"host":1,"flashed":1}
,"share":{"common":1}
,"pool":{"drivers":1}
,"called":{"common":1,"mb1-bct":1}
,"note":{"u-boot":1,"soon":1}
,"built":{"separately":1}
,"separately":{"nvidia-proprietary":1}
,"nvidia-proprietary":{"boo":1}
,"boo":{"tloader":1}
,"tloader":{"software":1}
,"support":{"cdf":1,"lashing":1,"rcm":1,"sc7":1,"ing":1,"cold":1,"display":1}
,"cdf":{"software":1,"provided":1,"fra":1}
,"design":{"architecture":1}
,"architecture":{"using":1}
,"ommon":{"driver":1}
,"consists":{"storage":1}
,"storage":{"drivers":1}
,"emmc":{"qspi":1}
,"qspi":{"sata":1}
,"sata":{"ufs":1}
,"ufs":{"host":1}
,"host":{"interface":1,"usb":1,"one-by-one":1}
,"interface":{"drivers":1}
,"uart":{"usb":1}
,"usb":{"display":1,"loaded":1,"starts":1}
,"display":{"drivers":1,"boot":1}
,"debug":{"onsole":1}
,"onsole":{"librar":1}
,"librar":{"libraries":1}
,"modules":{"clock":1}
,"clock":{"pmic":1}
,"pmic":{"timer":1,"commands":1,"vdd_cpu":1,"reset":1}
,"timer":{"fuse":1}
,"fuse":{"gpio":1}
,"gpio":{"pwm":1,"pad":1}
,"pwm":{"eeprom":1}
,"eeprom":{"keyboard":1}
,"keyboard":{"psci":1}
,"psci":{"software":1}
,"cryptographic":{"transport":1}
,"transport":{"partition":1,"libraries":1}
,"partition":{"manager":1}
,"manager":{"sparse":1}
,"sparse":{"transport":1}
,"decompression":{"library":1}
,"library":{"supports":1,"cache":1,"cdf":1}
,"supports":{"lzf":1}
,"lzf":{"zlib":1}
,"zlib":{"lz4":1}
,"lz4":{"lib":1}
,"lib":{"dynamic":1}
,"dynamic":{"memory":1}
,"allocation":{"library":1}
,"cache":{"library":1}
,"provided":{"<top":1,"nary":1,"binary":1}
,"<top":{">\u002Fvendor\u002Fnvidia\u002Ftegra\u002Fbootloader\u002Fpartner\u002Fcommon\u002F<top":1}
,">\u002Fvendor\u002Fnvidia\u002Ftegra\u002Fbootloader\u002Fpartner\u002Fcommon\u002F<top":{">\u002Fvendor\u002Fnvidia\u002Ftegra\u002Fbootloader\u002Fpartner\u002Ft18x\u002Fcomm":1}
,">\u002Fvendor\u002Fnvidia\u002Ftegra\u002Fbootloader\u002Fpartner\u002Ft18x\u002Fcomm":{"on\u002Fmicroboot1":1}
,"on\u002Fmicroboot1":{"jetson":1}
,"first":{"boot":1}
,"compon":{"ent":1}
,"ent":{"loaded":1}
,"loaded":{"sysram":1,"directly":1,"path":1}
,"sysram":{"runs":1}
,"runs":{"bpmp":1,"released":1}
,"bpmp":{"mb1":1,"(tboot-bpmp)":1}
,"considered":{"extension":1}
,"extension":{"mb1":1,"bootrom":1}
,"provides":{"extensive":1}
,"extensive":{"flexibility":1}
,"flexibility":{"alter":1}
,"alter":{"fix":1}
,"fix":{"boot":1}
,"sequence":{"component":1}
,"component":{"implements":1,"executes":1,"divided":1,"runs":1,"details":1}
,"implements":{"delicate":1}
,"delicate":{"functionality":1}
,"functionality":{"denver":1}
,"denver":{"initialization":1}
,"fabric":{"changes":1}
,"changes":{"mb1":1}
,"sign":{"encrypted":1}
,"encrypted":{"nvidia":1}
,"nvidia":{"owned":1,"provided":1,"tegr":1}
,"owned":{"key":1,"nvidia":1}
,"key":{"(separate":1}
,"(separate":{"keys":1}
,"keys":{"residing":1}
,"residing":{"boot":1}
,"rom":{"following":1}
,"following":{"diagram":1}
,"diagram":{"shows":1}
,"shows":{"flow":1}
,"responsible":{"firmware":1,"loading":1,"flashing":1,"parsing":1}
,"include":{"mts":1}
,"mts":{"preboot":1}
,"preboot":{"spe":1}
,"spe":{"platform":1}
,"platform":{"configuration":1,"using":1,"information":1}
,"includes":{"configuring":1}
,"configuring":{"pinmux":1,"gpio":1,"scr":1}
,"pinmux":{"configuring":1}
,"pad":{"settings":1}
,"settings":{"prod":1,"initializing":1,"configure":1}
,"prod":{"settings":1}
,"rails":{"including":1,"create":1}
,"required":{"cpu":1,"configuring":1}
,"cpu":{"memory":1,"complex":1,"initialization":1,"starts":1,"boot":1}
,"gpu":{"pmic":1}
,"commands":{"required":1}
,"scr":{"initialize":1}
,"sdram":{"based":1,"tos":1}
,"based":{"mb1":1,"little":1}
,"b1-bct)":{"load":1}
,"initializes":{"cpu":1}
,"complex":{"(ccplex)":1}
,"(ccplex)":{"security":1}
,"configure":{"inmux\u002Fgpio":1,"behavior":1,"platform":1}
,"inmux\u002Fgpio":{"soc":1}
,"program":{"pmic":1}
,"vdd_cpu":{"vdd_ddr":1}
,"vdd_ddr":{"rails":1}
,"create":{"carveouts":1}
,"lashing":{"available":1}
,"available":{"different":1}
,"mb1_recovery.bin":{"binary":1}
,"binary":{"support":1,"configure":1}
,"rcm":{"boot":1}
,"downloading":{"blob":1}
,"blob":{"contains":1,"load":1,"downloaded":1}
,"next":{"stage":1}
,"stage":{"boot":1}
,"(mb2)":{"support":1,"tboot":1,"used":1,"recovery":1}
,"sc7":{"mb1":1}
,"nary":{"bsp":1}
,"bsp":{"package":1}
,"package":{"although":1}
,"although":{"provided":1}
,"behavior":{"pecific":1}
,"pecific":{"platform":1}
,"tabl":{"called":1}
,"mb1-bct":{"mb1":1,"configure":1}
,"reads":{"mb1-bct":1}
,"executes":{"mb1":1}
,"divided":{"two":1}
,"two":{"portion":1,"variants":1}
,"portion":{"tboot":1,"jetson":1}
,"processor":{"executing":1}
,"executing":{"determines":1,"tos":1}
,"determines":{"component":1}
,"released":{"oem":1}
,"oem":{"source":1}
,"source":{"code":1,"boot":1}
,"code":{"reference":1,"completes":1}
,"reference":{"implementation":1}
,"implementation":{"tegraboot":1}
,"(tboot-bpmp)":{"two":1}
,"variants":{"tegraboot":1}
,"cold":{"boot":1}
,"ecovery":{"boot":1}
,"generated":{"using":1}
,"config":{"uration":1}
,"uration":{"file":1}
,"file":{"files":1}
,"files":{"tboot":1}
,"(fw)":{"component":1}
,"details":{"security":1}
,"creating":{"carveouts":1}
,"completing":{"cpu":1}
,"ing":{"next":1,"flashing":1,"rcm":1,"pmic":1,"bootloader":1,"device":1,"control":1}
,"tegraboot-bpmp":{"(mb2)":1}
,"recovery":{"boot":1,"kernel":1}
,"read":{"ing":1}
,"reset":{"reason":1}
,"reason":{"load":1}
,"bootloader":{"device":1}
,"tree":{"pass":1,"load":1,"booting":1}
,"pass":{"ing":1}
,"giv":{"ing":1}
,"bpmp-fw":{"components":1,"loaded":1}
,"tegraboot-cpu":{"responsible":1,"itializes":1,"takes":1}
,"similar":{"cold":1}
,"except":{"binaries":1}
,"transferre":{"host":1}
,"directly":{"sdram":1}
,"tos":{"bpmp-fw":1,"monitor":1,"tos":1,"completes":1}
,"path":{"note":1,"cboot":1}
,"soon":{"cpu":1}
,"starts":{"running":1,"mode":1,"protocol":1,"el3":1}
,"running":{"starts":1}
,"mode":{"tos":1,"begins":1,"kernel":1}
,"monitor":{"code":1}
,"completes":{"initialization":1}
,"gives":{"control":1}
,"itializes":{"usb":1}
,"protocol":{"ash":1}
,"ash":{"device":1}
,"normal":{"flashing":1}
,"takes":{"binaries":1}
,"one-by-one":{"flashes":1}
,"flashes":{"device":1}
,"downloaded":{"binaries":1}
,"flashed":{"device":1}
,"integrating":{"relevant":1}
,"relevant":{"libraries":1}
,"linuxboot":{"however":1}
,"however":{"version":1}
,"version":{"tboot":1}
,"tested":{"maintained":1}
,"maintained":{"compo":1}
,"compo":{"ents":1}
,"ents":{"tboot":1}
,"mobile":{"platforms":1}
,"platforms":{"cold":1}
,"feature-rich":{"boot":1}
,"boots":{"kernel":1}
,"kernel":{"support":1,"(lk)":1,"separate":1,"chaining":1,"supporting":1,"verified":1}
,"erified":{"boot":1}
,"little":{"kernel":1}
,"(lk)":{"open":1}
,"open":{"source":1}
,"ses":{"interrupt":1,"cdf":1}
,"interrupt":{"scheduling":1}
,"scheduling":{"frameworks":1}
,"frameworks":{"lkc":1}
,"lkc":{"ses":1}
,"fra":{"meworks":1}
,"meworks":{"drivers":1}
,"el3":{"mode":1}
,"begins":{"executing":1}
,"passes":{"control":1}
,"el2":{"mode":1}
,"trees":{"stored":1}
,"partitio":{"cboot":1}
,"parsing":{"cpu-bl":1}
,"chaining":{"u-boot":1}
,"supporting":{"update":1}
,"update":{"mechanism":1}
,"mechanism":{"loading":1}
,"verified":{"boot":1}
,"default":{"boot":1}
,"tegr":{"linux":1}
,"linux":{"driver":1}
,"pac":{"kage":1}
,"kage":{"information":1}
,"customization":{"tx2":1}
}
;Search.control.loadWordPairs(pairs);
