var pairs =
{
"tx1\u002Ftx2":{"mass":1}
,"mass":{"storage":1}
,"storage":{"partitions":1,"media":1,"devices":1,"medium":1}
,"partitions":{"configuration":1,"storing":1,"devi":1,"sub-devices":1,"element":1,"treated":1,"mandatory":1,"begin":1}
,"configuration":{"nvidia":1,"file":1,"fil":1,"table":1,"ble":1}
,"nvidia":{"linux":1,"signed":1}
,"linux":{"tegra":1,"kernel":1}
,"tegra":{"tx1":1,"releases":1,"partition":1}
,"tx1":{"tx2":1,"gnu_linux_tegraboot_emmc_full.xml":1,"partition":1,"device":1}
,"tx2":{"releases":1,"flash_l4t_t186.xml":1,"partition":1,"element":1,"rue":1}
,"releases":{"support":1,"default":1}
,"support":{"formatting":1}
,"formatting":{"mass":1}
,"media":{"multipl":1}
,"multipl":{"partitions":1}
,"storing":{"data":1}
,"data":{"device":1,"type":1,"written":1,"fbsign":1,"(mandatory)":1,"(optional)":1,"secondary_gpt":1}
,"device":{"image":1,"firmware":1,"elements":1,"element":1,"spans":1,"attributes":1,"type":1,"emmc":1,"instance":1,"jetson":1,"always":1,"follows":1,"usage":1,"partition":1,"\u002Fdev\u002Fmmcblk0p1":1,"tree":1,"loads":1,"except":1}
,"image":{"boot":1,"device":1}
,"boot":{"loader":1,"configuration":1,"pack":1,"stage":1,"binary":1}
,"loader":{"image":1,"splash":1}
,"firmware":{"boot":1,"secondary_gpt":1,"cpu-bootloade":1,"bpmp-fw-dtb":1,"device":1,"sc7":1}
,"splash":{"screens":1}
,"screens":{"partition":1}
,"partition":{"configuration":1,"nfiguration":1,"elements":1,"layout":1,"defi":1,"element":1,"name":1,"names":1,"type":1,"certain":1,"types":1,"(the":1,"bytes":1,"size":1,"defined":1,"extended":1,"immediately":1,"list":1,"overview":1,"sdmmc_boot":1,"sdmmc_user":1,"tools":1,"bootloader-dtb":1,"used":1,"contains":1,"allocation":1,"mounted":1}
,"file":{"partition":1,"describes":1,"directory":1,"translated":1,"hen":1,"perform":1,"details":1,"composed":1,"followin":1,"contain":1,"contai":1,"system":1,"written":1,"size":1,"write":1,"value":1,"name":1}
,"describes":{"entire":1}
,"entire":{"mass":1}
,"devices":{"partitions":1,"divided":1}
,"devi":{"ces":1}
,"ces":{"linux":1}
,"default":{"partition":1,"translated":1}
,"directory":{"availab":1,"u-boot":1}
,"availab":{"<top>\u002Flinux_for_t":1}
,"<top>\u002Flinux_for_t":{"egra\u002Fbootloader\u002F<board":1}
,"egra\u002Fbootloader\u002F<board":{"name>\u002Fcfg":1}
,"name>\u002Fcfg":{"\u002Fthe":1}
,"\u002Fthe":{"filename":1}
,"filename":{"specified":1,"<filename>":1,"empty":1}
,"specified":{"<device>":1,"bootloader\u002Fflash.xml":1,"partition":1,"less":1}
,"<device>":{".conf":1,".con":1}
,".conf":{"typica":1}
,"typica":{"values":1}
,"values":{"systems":1,"specified":1,"follows":1,"description":1,"valid":1}
,"systems":{"booting":1}
,"booting":{"emmc":1}
,"emmc":{"jetson":1,"user":1,"boot0":1,"partition":1}
,"jetson":{"tx1":1,"tx2":1,"usage":1}
,"gnu_linux_tegraboot_emmc_full.xml":{"jetson":1}
,"flash_l4t_t186.xml":{"during":1}
,"during":{"flashing":1,"sos":1}
,"flashing":{"procedure":1,"specified":1,"partition":1}
,"procedure":{"flash.sh":1}
,"flash.sh":{"read":1}
,"read":{"artition":1}
,"artition":{"configuration":1,"filename":1}
,"translated":{"keywords":1,"eywords":1,"keyword":1,"alue":1}
,"keywords":{"values":1,"table":1,"may":1}
,".con":{"option":1}
,"option":{"parameters":1}
,"parameters":{"save":1}
,"save":{"bootloader\u002Fflash.xml":1}
,"bootloader\u002Fflash.xml":{"file":1}
,"hen":{"bootloader\u002Ftegraflash.py":1}
,"bootloader\u002Ftegraflash.py":{"reads":1}
,"reads":{"bootloader\u002Fflash.xml":1}
,"perform":{"actual":1,"oem":1}
,"actual":{"flashing":1}
,"details":{"ist":1}
,"ist":{"translated":1,"types":1}
,"eywords":{"partition":1}
,"nfiguration":{"file":1}
,"composed":{"following":1}
,"following":{"xml":1,"syntax":1}
,"xml":{"format":1,"version=\u0022":1}
,"format":{"elements":1}
,"elements":{"root":1,"jetson":1,"-->":1,"partition":1,"legal":1,"supported":1}
,"root":{"element":1,"jetson":1,"device":1}
,"element":{"device":1,"root":1,"configuration":1,"jetson":1,"storage":1,"sub-device":1,"present":1,"following":1,"may":1,"attributes":1,"child":1,"values":1}
,"followin":{"syntax":1}
,"syntax":{"xml":1,"<device":1,"<partition":1}
,"version=\u0022":{"1.0":1,"01.00.0000":1}
,"1.0":{"<!--nvidia":1}
,"<!--nvidia":{"tegra":1}
,"layout":{"version":1}
,"version":{"1.0.0":1}
,"1.0.0":{"-->":1}
,"-->":{"<partition_layout":1,"<\u002Fpartition>":1,"<\u002Fdevice>":1}
,"<partition_layout":{"version=\u0022":1}
,"01.00.0000":{"<!--device":1}
,"<!--device":{"elements":1}
,"<\u002Fpartition>":{"device":1,"partition":1}
,"contain":{"device":1}
,"defi":{"nitions":1,"ned":1}
,"nitions":{"appear":1}
,"appear":{"directly":1,"partition":1}
,"directly":{"root":1}
,"medium":{"divided":1}
,"divided":{"multiple":1,"sub-devices":1}
,"multiple":{"sub-devices":1,"device":1,"partition":1}
,"sub-devices":{"example":1,"treated":1,"may":1}
,"example":{"emmc":1}
,"user":{"hardware":1,"defi":1,"specified":1,"data":1}
,"hardware":{"partitions":1}
,"treated":{"single":1}
,"single":{"linear":1,"sdmmc_boot":1}
,"linear":{"device":1}
,"spans":{"sub-dev":1}
,"sub-dev":{"ices":1}
,"ices":{"jetson":1}
,"contai":{"device":1}
,"sub-device":{"example":1}
,"present":{"even":1,"append":1}
,"even":{"devices":1}
,"may":{"multiple":1,"equal":1,"appear":1}
,"<device":{"type=\u0022":1,"type>":1}
,"type=\u0022":{"<device":1,"<type>":1}
,"type>":{"instance=\u0022":1}
,"instance=\u0022":{"<instance>":1}
,"<instance>":{"<!--partition":1}
,"<!--partition":{"elements":1}
,"<\u002Fdevice>":{"device":1}
,"attributes":{"table":1,"legal":1,"values":1,"supported":1,"partition":1}
,"table":{"supported":1,"(required)":1,"mb1":1}
,"supported":{"device":1,"attributes":1,"partition":1}
,"legal":{"values":1}
,"follows":{"device":1,"attribute":1,"element":1,"keyword":1,"name":1}
,"description":{"device":1,"name":1,"allocation_policy":1,"bct":1,"master_boot_record":1}
,"type":{"sdmmc_boot":1,"device":1,"user":1,"data":1,"complete":1,"partition":1,"allocation":1,"description":1}
,"sdmmc_boot":{"sdmmc_user":1,"entry":1,"device":1}
,"sdmmc_user":{"sata":1,"device":1}
,"sata":{"(required)":1,"typical":1}
,"(required)":{"specifies":1,"device":1}
,"specifies":{"type":1,"name":1,"raw":1,"size":1}
,"boot0":{"boot1":1}
,"boot1":{"hardware":1}
,"entry":{"instance":1,"configured":1}
,"instance":{"0-3":1,"sata":1}
,"0-3":{"(required)":1}
,"typical":{"emmc":1}
,"<partition":{"name=\u0022":1}
,"name=\u0022":{"<name>":1}
,"<name>":{"type=\u0022":1}
,"<type>":{"oem_sign=\u201D":1}
,"oem_sign=\u201D":{"rue":1}
,"rue":{"--partition":1,"false":1}
,"--partition":{"propertie":1}
,"propertie":{"-->":1}
,"attribute":{"values":1,"present":1}
,"name":{"complete":1,"partition":1,"maximum":1,"file":1,"tosname":1,"scename":1,"default":1,"type":1}
,"complete":{"list":1,"ist":1}
,"list":{"pre-defined":1,"translated":1,"keywords":1}
,"pre-defined":{"names":1}
,"names":{"keywords":1,"associated":1,"oem_sign":1}
,"maximum":{"characters":1}
,"characters":{"kind":1}
,"kind":{"partitions":1}
,"mandatory":{"optional":1}
,"optional":{"user":1,"partition":1}
,"ned":{"mandatory":1}
,"associated":{"specific":1,"partition":1}
,"specific":{"partition":1}
,"types":{"keyword":1,"valid":1}
,"keyword":{"table":1,"list":1,"follows":1,"default":1}
,"certain":{"partition":1}
,"valid":{"associated":1,"partition":1}
,"oem_sign":{"jetson":1}
,"false":{"attribute":1,"fbfile":1}
,"append":{"generic":1,"null":1}
,"generic":{"signature":1}
,"signature":{"header":1}
,"header":{"binary":1}
,"binary":{"perform":1,"per":1,"mb1_bct":1,"mb2":1,"mts-preboot":1,"oads":1,"kernel":1,"fbname":1}
,"oem":{"signing":1}
,"signing":{"hat":1,"partition":1}
,"hat":{"append":1}
,"null":{"signature":1,"signing":1}
,"per":{"form":1}
,"form":{"null":1}
,"child":{"elements":1}
,"allocation_policy":{"sequential":1}
,"sequential":{"specifies":1}
,"allocation":{"policy":1,"poli":1,"att":1}
,"policy":{"sequentia":1}
,"sequentia":{"partitions":1}
,"begin":{"immediately":1}
,"immediately":{"preceding":1,"preced":1}
,"preceding":{"partition":1}
,"(the":{"legacy":1}
,"legacy":{"absolute":1,"ext2":1}
,"absolute":{"allocation":1}
,"poli":{"deprecated.)":1}
,"deprecated.)":{"filesystem_type":1,"size":1}
,"filesystem_type":{"basic":1,"specifies":1}
,"basic":{"asic":1}
,"asic":{"filesystem_type":1}
,"raw":{"partition":1}
,"ext2":{"file":1}
,"system":{"deprecated.)":1}
,"size":{"<byte":1,"partition":1,"may":1,"file":1,"allows":1,"increase":1,"specified":1,"align":1,"property":1,"automatically":1}
,"<byte":{"size>":1}
,"size>":{"(required)":1}
,"bytes":{"decimal":1}
,"decimal":{"hexadecimal":1}
,"hexadecimal":{"values":1}
,"equal":{"larger":1}
,"larger":{"size":1}
,"written":{"partitio":1,"partition":1}
,"partitio":{"specifying":1}
,"specifying":{"larger":1}
,"allows":{"file":1}
,"increase":{"later":1}
,"later":{"without":1}
,"without":{"requiring":1}
,"requiring":{"partition":1}
,"fil":{"modified":1}
,"modified":{"partition":1}
,"less":{"ase":1}
,"ase":{"block":1}
,"block":{"size":1,"boundary":1}
,"align":{"itself":1}
,"itself":{"partit":1}
,"partit":{"ion":1}
,"ion":{"erase":1}
,"erase":{"block":1}
,"boundary":{"size":1}
,"property":{"secondary":1}
,"secondary":{"gpt":1,"bootloader":1}
,"gpt":{"partition":1,"file_system_attribute":1,"percent_reserved":1,"sdmmc_boot":1,"sdmmc_user":1,"accessed":1,"ace":1}
,"defined":{"end":1,"entry":1,"prima":1}
,"end":{"device":1}
,"always":{"0xffffffffffffffff":1}
,"0xffffffffffffffff":{"tegraflash":1}
,"tegraflash":{"cal":1}
,"cal":{"culates":1}
,"culates":{"size":1}
,"automatically":{"preceding":1,"rem":1}
,"extended":{"fill":1}
,"fill":{"ree":1}
,"ree":{"space":1}
,"space":{"secondary":1,"device":1}
,"file_system_attribute":{"implemented":1}
,"implemented":{"allocation_attribute":1}
,"allocation_attribute":{"0x8":1}
,"0x8":{"0x808":1}
,"0x808":{"0x808":1,"partition":1,"automatically":1}
,"preced":{"ing":1}
,"ing":{"secondary":1}
,"percent_reserved":{"future":1}
,"future":{"filename":1,"removable":1}
,"<filename>":{"empty":1}
,"empty":{"specifies":1,"data":1}
,"write":{"artition":1}
,"value":{"keyword":1}
,"alue":{"flash.xml":1}
,"flash.xml":{"mb1name":1}
,"mb1name":{"mb1":1}
,"mb1":{"mb1type":1,"mb1_bootloader":1,"binary":1,"boot":1}
,"mb1type":{"mb1_bootloader":1}
,"mb1_bootloader":{"spename":1,"(mandatory)":1}
,"spename":{"spe-fw":1}
,"spe-fw":{"spetype":1,"spe-fw":1,"contains":1,"binary":1}
,"spetype":{"spe_fw":1}
,"spe_fw":{"mb2name":1}
,"mb2name":{"mb2type":1}
,"mb2type":{"mb2_bootloader":1}
,"mb2_bootloader":{"mb2file":1,"contains":1}
,"mb2file":{"nvtboot.bin":1}
,"nvtboot.bin":{"mpbname":1}
,"mpbname":{"mts-preboot":1}
,"mts-preboot":{"mpbtype":1,"mts_preboot":1}
,"mpbtype":{"mts_preboot":1}
,"mts_preboot":{"mpbfile":1,"contains":1}
,"mpbfile":{"preboot_d15_prod_cr.bin":1}
,"preboot_d15_prod_cr.bin":{"appsize":1}
,"appsize":{"30064771072":1}
,"30064771072":{"appfile":1}
,"appfile":{"system.img":1}
,"system.img":{"mbpname":1}
,"mbpname":{"mts-bootpack":1}
,"mts-bootpack":{"mbptype":1,"mts_bootpack":1}
,"mbptype":{"mts_bootpack":1}
,"mts_bootpack":{"mbpfile":1,"(mandatory)":1}
,"mbpfile":{"mce_mts_d15_prod_cr.bin":1}
,"mce_mts_d15_prod_cr.bin":{"tbcname":1}
,"tbcname":{"cpu-bootloader":1}
,"cpu-bootloader":{"tbctype":1}
,"tbctype":{"bootloader":1}
,"bootloader":{"tbcfile":1,"dtb":1,"(mandatory)":1,"binary":1,"device":1,"defaul":1}
,"tbcfile":{"cboot.bin":1}
,"cboot.bin":{"tbcdtb-name":1}
,"tbcdtb-name":{"bootloader-dtb":1}
,"bootloader-dtb":{"tbcdtb-file":1,"data":1}
,"tbcdtb-file":{"appropriate":1}
,"appropriate":{"bootloader":1,"bpmp":1,"kernel":1}
,"dtb":{"file":1}
,"tosname":{"secure-os":1}
,"secure-os":{"tosfile":1,"data":1}
,"tosfile":{"tos.img":1}
,"tos.img":{"eksfile":1}
,"eksfile":{"eks.img":1}
,"eks.img":{"bpfname":1}
,"bpfname":{"bpmp-fw":1}
,"bpmp-fw":{"bpfsign":1,"data":1}
,"bpfsign":{"true":1}
,"true":{"bpffile":1,"bpfdtb-file":1,"scefile":1}
,"bpffile":{"bpmp.bin":1}
,"bpmp.bin":{"bpfdtb-name":1}
,"bpfdtb-name":{"bpmp-fw-dtb":1}
,"bpmp-fw-dtb":{"bpfdtb-sign":1,"data":1}
,"bpfdtb-sign":{"true":1}
,"bpfdtb-file":{"appropriate":1}
,"bpmp":{"dtb":1,"spe-fw":1,"firmware":1}
,"scename":{"sce-fw":1}
,"sce-fw":{"scesign":1,"data":1}
,"scesign":{"true":1}
,"scefile":{"camera-rtcpu-sce.bin":1}
,"camera-rtcpu-sce.bin":{"sc7name":1}
,"sc7name":{"sc7":1}
,"sc7":{"wb0type":1,"wb0":1}
,"wb0type":{"wb0":1}
,"wb0":{"wb0file":1,"(mandatory)":1}
,"wb0file":{"warmboot.bin":1}
,"warmboot.bin":{"fbname":1}
,"fbname":{"fbname":1,"(not":1,"data":1}
,"(not":{"used)":1}
,"used)":{"fbtype":1}
,"fbtype":{"data":1}
,"fbsign":{"false":1}
,"fbfile":{"removed\u002Funused":1}
,"removed\u002Funused":{"sosfile":1,"lnxname":1}
,"sosfile":{"removed\u002Funused":1}
,"lnxname":{"kernel":1}
,"kernel":{"lnxsize":1,"dtb":1,"acces":1,"partition":1,"data":1,"rootdev\u2019s":1,"kernel-dtb":1,"device":1}
,"lnxsize":{"67108864":1}
,"67108864":{"lnxfile":1}
,"lnxfile":{"boot.img":1}
,"boot.img":{"kerneldtb-name":1}
,"kerneldtb-name":{"kernel-dtb":1}
,"kernel-dtb":{"kerneldtb-file":1,"data":1}
,"kerneldtb-file":{"appropriate":1}
,"overview":{"jetson":1}
,"usage":{"partition":1}
,"bct":{"boot_config_table":1}
,"boot_config_table":{"(mandatory)":1}
,"(mandatory)":{"contains":1}
,"contains":{"boot":1,"nvidia":1,"mb1":1,"bpmp":1,"primary":1,"denver":1,"secondary":1,"protective":1,"rootfs":1,"final":1,"bootloader":1,"trusted":1,"encrypted":1,"adsp":1,"camera-rtcpu-sce":1,"warm":1,"bmp":1,"partition":1,"u-boot":1,"linux":1,"kernel":1}
,"signed":{"mb1":1}
,"mb1_bct":{"mb1_boot_config_table":1}
,"mb1_boot_config_table":{"(mandatory)":1}
,"ble":{"spe-fw":1}
,"mb2":{"mb2_bootloader":1}
,"primary":{"copy":1,"gpt":1}
,"copy":{"tegraboot":1}
,"tegraboot":{"binary":1}
,"denver":{"preboot":1,"boot":1}
,"preboot":{"firmware":1}
,"secondary_gpt":{"secondary_gpt":1,"contains":1,"(mandatory)":1}
,"master_boot_record":{"protective_master_boot_record":1}
,"protective_master_boot_record":{"(mandatory)":1}
,"protective":{"mbr":1}
,"mbr":{"primary_gpt":1}
,"primary_gpt":{"primary_gpt":1,"(mandatory)":1}
,"configured":{"kernel":1}
,"acces":{"sible":1}
,"sible":{"standard":1}
,"standard":{"partition":1}
,"tools":{"gdisk":1}
,"gdisk":{"parted":1}
,"parted":{"app":1}
,"app":{"data":1}
,"rootfs":{"partition":1}
,"prima":{"gpt":1}
,"accessed":{"fixed":1}
,"fixed":{"known":1}
,"known":{"special":1}
,"special":{"device":1}
,"\u002Fdev\u002Fmmcblk0p1":{"mts-bootpack":1}
,"pack":{"firmware":1}
,"cpu-bootloade":{"bootloader":1}
,"final":{"boot":1}
,"stage":{"cpu":1}
,"cpu":{"bootloader":1}
,"oads":{"binary":1}
,"tree":{"blob":1}
,"blob":{"(dtb)":1}
,"(dtb)":{"secure-os":1,"sce-fw":1,"cac":1}
,"trusted":{"eks":1}
,"eks":{"data":1}
,"(optional)":{"contains":1,"future":1,"partition":1}
,"encrypted":{"keys":1}
,"keys":{"adsp-fw":1}
,"adsp-fw":{"data":1}
,"adsp":{"software":1}
,"software":{"bpmp-fw":1}
,"camera-rtcpu-sce":{"firmware":1}
,"warm":{"boot":1}
,"removable":{"bmp":1,"kernel":1,"uda":1}
,"bmp":{"data":1,"images":1}
,"images":{"(if":1}
,"(if":{"any)":1}
,"any)":{"display":1}
,"display":{"during":1}
,"sos":{"data":1}
,"used":{"recovery":1,"sto":1}
,"recovery":{"removable":1}
,"u-boot":{"secondary":1,"searches":1,"selected":1}
,"defaul":{"u-boot":1}
,"searches":{"root":1}
,"loads":{"linux":1}
,"rootdev\u2019s":{"\u002Fboot":1}
,"\u002Fboot":{"directory":1}
,"selected":{"during":1}
,"cac":{"data":1}
,"uda":{"data":1}
,"att":{"ribute":1}
,"ribute":{"0x808":1}
,"rem":{"aining":1}
,"aining":{"space":1}
,"except":{"secondary":1}
,"ace":{"partition":1}
,"mounted":{"used":1}
,"sto":{"user":1}
}
;Search.control.loadWordPairs(pairs);
