var pairs =
{
"hardware":{"setup":1,"directly":1}
,"setup":{"procedure":1,"customiz":1,"refer":1}
,"procedure":{"required":1}
,"required":{"hardware":1}
,"customiz":{"ation":1}
,"ation":{"reference":1}
,"reference":{"platform":1,"board":1}
,"platform":{"reference":1,"nvidia":1,"board":1}
,"board":{"preparation":1,"using":1,"documentation":1,"although":1,"supports":1,"following":1,"recovery":1,"layout":1}
,"preparation":{"developing":1}
,"developing":{"systems":1,"l4t":1}
,"systems":{"application":1}
,"application":{"software":1}
,"software":{"ith":1,"simulato":1}
,"ith":{"l4t":1}
,"l4t":{"run":1,"onsult":1,"board":1}
,"run":{"test":1}
,"test":{"code":1}
,"code":{"actual":1,"targets":1}
,"actual":{"eference":1}
,"eference":{"platform":1}
,"nvidia":{"jetson":1}
,"jetson":{"tx1":1,"tx2":1}
,"tx1":{"tx2":1,"layout":1}
,"tx2":{"developer":1,"layout":1}
,"developer":{"kit":1}
,"kit":{"code":1}
,"targets":{"hardware":1}
,"directly":{"rather":1}
,"rather":{"software":1}
,"simulato":{"emulator":1}
,"emulator":{"accordingly":1}
,"accordingly":{"acquire":1}
,"acquire":{"setup":1}
,"refer":{"ence":1}
,"ence":{"board":1}
,"using":{"l4t":1}
,"onsult":{"board":1}
,"documentation":{"guidance":1}
,"guidance":{"setting":1}
,"setting":{"configuring":1}
,"configuring":{"board":1}
,"although":{"reference":1}
,"supports":{"variety":1}
,"variety":{"peripheral":1}
,"peripheral":{"devices":1}
,"devices":{"start":1,"specified":1}
,"start":{"developing":1}
,"following":{"storage":1}
,"storage":{"devices":1}
,"specified":{"boot":1}
,"boot":{"options":1}
,"options":{"topic":1}
,"topic":{"bsp":1}
,"bsp":{"customization":1}
,"customization":{"chapter":1}
,"chapter":{"usb":1}
,"usb":{"cable":1}
,"cable":{"plug":1}
,"plug":{"board":1}
,"recovery":{"port":1}
,"port":{"platform":1}
,"layout":{"l4t":1,"connections":1,"jetson":1}
,"connections":{"follow":1}
,"follow":{"jetson":1}
}
;Search.control.loadWordPairs(pairs);
