var pairs =
{
"design":{"debugging":1}
,"debugging":{"vidia":1,"(dfd)":1,"strategies":1}
,"vidia":{"tegra":1}
,"tegra":{"tx1":1,"board":1,"technical":1,"tegra":1,"tx2":1}
,"tx1":{"tx2":1}
,"tx2":{"devices":1,"processor":1,"improvements":1,"dfd":1}
,"devices":{"leverage":1,"follows":1,"cases":1}
,"leverage":{"enhancements":1}
,"enhancements":{"design":1}
,"(dfd)":{"ature":1}
,"ature":{"dfd":1}
,"dfd":{"enables":1,"impl":1,"improvements":1,"feature":1,"follows":1}
,"enables":{"development":1}
,"development":{"debu":1}
,"debu":{"gging":1}
,"gging":{"tools":1}
,"tools":{"allow":1}
,"allow":{"developers":1}
,"developers":{"tegra-based":1}
,"tegra-based":{"mplementations":1}
,"mplementations":{"place":1}
,"place":{"tegra":1}
,"processor":{"known":1,"tracing":1,"protocol":1}
,"known":{"states":1}
,"states":{"trace":1}
,"trace":{"behavior":1,"storage":1,"preserved":1,"sinks":1,"sink":1,"fifo":1,"watchdog":1,"information":1,"low":1,"avoid":1,"(atid)":1,"multiple":1,"data":1}
,"behavior":{"running":1}
,"running":{"benefits":1}
,"benefits":{"enhanced":1}
,"enhanced":{"dfd":1,"security":1}
,"impl":{"ementation":1}
,"ementation":{"include":1}
,"include":{"reduced":1}
,"reduced":{"power":1}
,"power":{"leakage":1}
,"leakage":{"enhanced":1}
,"security":{"availability":1}
,"availability":{"standard":1}
,"standard":{"interfaces":1}
,"interfaces":{"topic":1}
,"topic":{"describes":1}
,"describes":{"debuggable":1,"software":1}
,"debuggable":{"blocks":1}
,"blocks":{"debugging":1}
,"strategies":{"information":1}
,"information":{"help":1,"debuggi":1,"watchdog":1}
,"help":{"determine":1}
,"determine":{"somethi":1}
,"somethi":{"may":1}
,"may":{"working":1}
,"working":{"software":1}
,"software":{"dev":1,"implementation":1,"features":1}
,"dev":{"eloped":1}
,"eloped":{"using":1}
,"using":{"nvidia":1,"a57":1}
,"nvidia":{"tegra":1,"higher":1}
,"board":{"support":1}
,"support":{"package":1}
,"package":{"(bsp)":1}
,"(bsp)":{"topic":1}
,"implementation":{"hardware":1}
,"hardware":{"software":1,"dfd":1}
,"features":{"tegra":1}
,"technical":{"reference":1}
,"reference":{"manua":1}
,"manua":{"(trm)":1}
,"(trm)":{"primary":1}
,"primary":{"source":1}
,"source":{"information":1}
,"debuggi":{"dfd":1}
,"improvements":{"dfd":1,"tegra":1,"connection":1}
,"follows":{"hardware":1,"includes":1,"collecting":1}
,"feature":{"tegra":1}
,"connection":{"cpu":1,"axi-ap":1,"snic":1,"ape":1,"bpmp":1}
,"cpu":{"(jtag)":1,"frequency":1,"trace":1}
,"(jtag)":{"debug":1,"axi":1,"coresight":1}
,"debug":{"communication":1,"available":1}
,"communication":{"channel":1}
,"channel":{"memory":1}
,"memory":{"access":1}
,"access":{"mode":1,"mod":1,"complete":1,"system":1,"cpus":1}
,"mode":{"debug":1}
,"mod":{"faster":1}
,"faster":{"code":1}
,"code":{"download\u002Fupload":1,"optimiz":1,"optimization":1}
,"download\u002Fupload":{"via":1}
,"via":{"debugger":1,"etr":1}
,"debugger":{"connection":1}
,"axi-ap":{"(jtag)":1}
,"axi":{"-ap":1}
,"-ap":{"bit":1}
,"bit":{"address":1,"(contact":1}
,"address":{"access":1}
,"complete":{"mmio":1,"access":1,"system":1}
,"mmio":{"dram":1}
,"dram":{"without":1,"bandwidth":1}
,"without":{"requiring":1}
,"requiring":{"smmu":1}
,"smmu":{"connection":1}
,"snic":{"allowing":1}
,"allowing":{"complete":1}
,"system":{"complete":1,"access":1}
,"cpus":{"powered":1}
,"powered":{"down":1}
,"down":{"dead":1}
,"dead":{"reset":1}
,"reset":{"clock":1,"code":1}
,"clock":{"disabled":1}
,"disabled":{"unable":1}
,"unable":{"brea":1}
,"brea":{"connection":1}
,"ape":{"(jtag)":1,"trace":1,"cortex":1}
,"coresight":{"coresight":1,"change":1,"full":1,"debug":1,"trace":1,"amba":1}
,"change":{"connection":1}
,"bpmp":{"spe":1}
,"spe":{"sce":1}
,"sce":{"n\u002Fa":1,"available":1}
,"n\u002Fa":{"coresight":1}
,"full":{"coresight":1}
,"available":{"bpmp":1,"main":1,"commercial":1}
,"main":{"trace":1}
,"storage":{"etf":1}
,"etf":{"16kb":1,"32kb":1,"coresight":1,"(32":1}
,"16kb":{"circular":1}
,"circular":{"buffer":1}
,"buffer":{"etf":1,"larger":1,"longer":1}
,"32kb":{"circular":1}
,"larger":{"buffer":1}
,"longer":{"duration":1}
,"duration":{"trace":1}
,"preserved":{"wdt":1}
,"wdt":{"resets":1}
,"resets":{"core":1}
,"core":{"ight":1}
,"ight":{"trace":1}
,"sinks":{"etf":1,"(etf":1}
,"sink":{"characteristics":1}
,"characteristics":{"tegra":1}
,"includes":{"corresponding":1}
,"corresponding":{"embedded":1}
,"embedded":{"trace":1}
,"fifo":{"(etf)":1}
,"(etf)":{"etr":1}
,"etr":{"usb":1,"dma":1}
,"usb":{"limits":1,"throughput":1,"speeds":1}
,"limits":{"characteristic":1}
,"characteristic":{"etf":1}
,"(32":{"kb)":1}
,"kb)":{"ddr":1}
,"ddr":{"via":1,"=25":1}
,"dma":{"usb":1}
,"throughput":{"gbps":1}
,"gbps":{"@408":1,"real":1}
,"@408":{"mhz":1}
,"mhz":{"128":1}
,"128":{"bit":1}
,"(contact":{"nvidia":1}
,"higher":{"frequency":1}
,"frequency":{"requirements":1,"intrusive":1,"ape":1}
,"requirements":{"gbps":1}
,"real":{"time":1}
,"time":{"processor":1}
,"tracing":{"requires":1,"limited":1}
,"requires":{"reduction":1}
,"reduction":{"cpu":1}
,"intrusive":{"available":1}
,"commercial":{"devices":1}
,"cases":{"collect":1}
,"collect":{"trace":1}
,"watchdog":{"reset":1}
,"optimiz":{"ation":1}
,"ation":{"ccplex":1}
,"ccplex":{"collects":1,"(note":1}
,"collects":{"trace":1}
,"optimization":{"ccplex":1}
,"(note":{"high":1}
,"high":{"andwidth":1}
,"andwidth":{"requirement":1}
,"requirement":{"ddr":1}
,"=25":{"single":1}
,"single":{"cpu":1}
,"low":{"frequency":1}
,"avoid":{"saturation":1}
,"saturation":{"dram":1}
,"bandwidth":{"tracing":1,"coresight":1}
,"limited":{"usb":1}
,"speeds":{"single":1}
,"amba":{"trace":1}
,"(atid)":{"mapping":1,"follows":1}
,"mapping":{"mapping":1,"coresight":1}
,"collecting":{"trace":1}
,"multiple":{"sources":1}
,"sources":{"trace":1}
,"(etf":{"etr)":1}
,"etr)":{"atids":1}
,"atids":{"segregate":1}
,"segregate":{"trace":1}
,"data":{"bccplex":1}
,"bccplex":{"(also":1}
,"(also":{"called":1}
,"called":{"fast":1}
,"fast":{"cluster":1}
,"cluster":{"big":1}
,"big":{"cluster)":1}
,"cluster)":{"using":1}
,"a57":{"processors":1}
,"processors":{"atid":1}
,"atid":{"processor":1}
,"protocol":{"0x40":1,"0x20":1,"0x10":1}
,"0x40":{"cpu0":1}
,"cpu0":{"etmv4":1,"pft1.0":1}
,"etmv4":{"0x41":1,"0x42":1,"0x43":1,"ape":1}
,"0x41":{"cpu1":1}
,"cpu1":{"etmv4":1}
,"0x42":{"cpu2":1}
,"cpu2":{"etmv4":1}
,"0x43":{"cpu3":1}
,"cpu3":{"etmv4":1}
,"cortex":{"atid":1}
,"0x20":{"cpu0":1}
,"pft1.0":{"stm":1}
,"stm":{"atid":1}
,"0x10":{"mipi":1}
,"mipi":{"stp":1}
}
;Search.control.loadWordPairs(pairs);
