var pairs =
{
"bluetooth":{"device":1,"audio":1,"software":1,"profile":1,"speaker":1,"low-energy":1,"kernel==\u0022":1,"anager":1}
,"device":{"settings":1,"pair":1}
,"settings":{"enabling":1}
,"enabling":{"bluetooth":1}
,"audio":{"ensure":1,"disabled":1,"profiles":1,"a2dp":1,"devices":1}
,"ensure":{"bluetooth":1}
,"software":{"stack":1}
,"stack":{"conforman":1}
,"conforman":{"configuration":1}
,"configuration":{"bluetooth":1,"file":1}
,"disabled":{"default":1}
,"default":{"additional":1}
,"additional":{"bluetooth":1}
,"profiles":{"enabled":1}
,"enabled":{"product":1}
,"product":{"conformance":1}
,"conformance":{"may":1}
,"may":{"impacted":1}
,"impacted":{"enable":1}
,"enable":{"bluetooth":1,"a2dp":1}
,"a2dp":{"navigate":1,"bluetooth":1,"noplugin":1,"plugin":1,"avrcp":1}
,"navigate":{"following":1,"configuration":1}
,"following":{"files":1,"lines":1,"file":1,"line":1}
,"files":{"\u002Fetc\u002Fpulse\u002Fdefault.pa.hdmi":1}
,"\u002Fetc\u002Fpulse\u002Fdefault.pa.hdmi":{"\u002Fetc\u002Fpulse\u002Fdefault.pa.orig":1}
,"\u002Fetc\u002Fpulse\u002Fdefault.pa.orig":{"uncomment":1}
,"uncomment":{"following":1}
,"lines":{"load":1,"located":1,"action==\u0022":1}
,"load":{"modules":1}
,"modules":{"enable":1}
,"profile":{".ifexists":1}
,".ifexists":{"module-bluetooth-policy.so":1,"module-bluetooth-discover.so":1}
,"module-bluetooth-policy.so":{"load-module":1}
,"load-module":{"module-bluetooth-policy":1,"module-bluetooth-discover":1}
,"module-bluetooth-policy":{".endif":1}
,".endif":{".ifexists":1,"navigate":1}
,"module-bluetooth-discover.so":{"load-module":1}
,"module-bluetooth-discover":{".endif":1}
,"file":{"\u002Fetc\u002Fsystemd\u002Fsystem\u002Fbluetooth.target.wants\u002Fbluetoo":1,"\u002Fetc\u002Fbluetooth\u002Fmain.conf":1,"[policy]":1,"\u002Flib":1}
,"\u002Fetc\u002Fsystemd\u002Fsystem\u002Fbluetooth.target.wants\u002Fbluetoo":{"th.service":1}
,"th.service":{"remove":1}
,"remove":{"a2dp":1,"304":1}
,"noplugin":{"parameter":1}
,"parameter":{"list":1}
,"list":{"change":1}
,"change":{"allows":1,"following":1}
,"allows":{"a2dp":1}
,"plugin":{"loaded":1}
,"loaded":{"enables":1}
,"enables":{"bluetooth":1}
,"speaker":{"work":1}
,"work":{"expected":1}
,"expected":{"example":1}
,"example":{"change":1}
,"line":{"execstart=\u002Fusr\u002Flib\u002Fbluetooth\u002Fbluetoothd":1}
,"execstart=\u002Fusr\u002Flib\u002Fbluetooth\u002Fbluetoothd":{"--noplu":1}
,"--noplu":{"gin=audio":1}
,"gin=audio":{"a2dp":1,"avrcp":1}
,"avrcp":{"follows":1,"reboot":1}
,"follows":{"execstart=\u002Fusr\u002Flib\u002Fbluetooth\u002Fbluetoothd":1}
,"reboot":{"jetson":1}
,"jetson":{"target":1}
,"target":{"device":1}
,"pair":{"bluetooth":1,"ble":1,"device":1}
,"devices":{"pairing":1}
,"pairing":{"ble":1,"bluetooth":1}
,"ble":{"bluez":1,"install":1}
,"bluez":{"required":1,"using":1,"upon":1,"already":1}
,"required":{"pairing":1}
,"low-energy":{"(ble)":1}
,"(ble)":{"device":1}
,"install":{"bluez":1}
,"using":{"apt-get":1}
,"apt-get":{"ubuntu":1,"install":1}
,"ubuntu":{"version":1}
,"version":{"16.0":1,"(5.37-0ubuntu5":1}
,"16.0":{"execution":1}
,"execution":{"command":1}
,"command":{"sudo":1}
,"sudo":{"apt-get":1}
,"upon":{"successful":1}
,"successful":{"installation":1}
,"installation":{"system":1}
,"system":{"returns":1,"open":1}
,"returns":{"essages":1}
,"essages":{"similar":1}
,"similar":{"reading":1}
,"reading":{"package":1,"state":1}
,"package":{"lists":1}
,"lists":{"done":1}
,"done":{"building":1,"bluez":1}
,"building":{"dependency":1}
,"dependency":{"tree":1}
,"tree":{"reading":1}
,"state":{"information":1}
,"information":{"done":1}
,"already":{"newest":1}
,"newest":{"version":1}
,"(5.37-0ubuntu5":{".1)":1}
,".1)":{"upgraded":1}
,"upgraded":{"newly":1}
,"newly":{"installed":1}
,"installed":{"remove":1}
,"304":{"upgra":1}
,"upgra":{"ded":1}
,"ded":{"navigate":1}
,"\u002Fetc\u002Fbluetooth\u002Fmain.conf":{"add":1}
,"add":{"uncomment":1,"subsystem==\u0022":1}
,"located":{"towar":1}
,"towar":{"end":1}
,"end":{"file":1}
,"[policy]":{"autoenable=true":1}
,"autoenable=true":{"comment":1}
,"comment":{"adding":1}
,"adding":{"pound":1}
,"pound":{"(#)":1}
,"(#)":{"sign":1}
,"sign":{"lines":1}
,"action==\u0022":{"add":1}
,"subsystem==\u0022":{"bluetooth":1}
,"kernel==\u0022":{"[0-9]*\u0022":1}
,"[0-9]*\u0022":{"run":1}
,"run":{"+=\u0022\u002Fbin\u002Fhciconfig":1}
,"+=\u0022\u002Fbin\u002Fhciconfig":{"file":1}
,"\u002Flib":{"\u002Fudev\u002Frules.d\u002F50-bluetooth-hci-auto-poweron.rules":1}
,"\u002Fudev\u002Frules.d\u002F50-bluetooth-hci-auto-poweron.rules":{"restart":1}
,"restart":{"system":1}
,"open":{"bluetooth":1}
,"anager":{"pair":1}
}
;Search.control.loadWordPairs(pairs);
