var pairs =
{
"graphics":{"sample":1}
,"sample":{"application":1}
,"application":{"run":1,"install":1,"boot":1,"steps":1}
,"run":{"sample":1,"open-source":1,"gears":1}
,"open-source":{"ears":1}
,"ears":{"application":1}
,"install":{"run":1,"mesa-utils":1,"mesa-utils-extra":1}
,"gears":{"application":1}
,"boot":{"target":1}
,"target":{"system":1}
,"system":{"ethernet":1}
,"ethernet":{"connection":1}
,"connection":{"enable":1}
,"enable":{"package":1}
,"package":{"download":1}
,"download":{"universe":1}
,"universe":{"reposi":1,"update":1}
,"reposi":{"tory":1}
,"tory":{"editing":1}
,"editing":{"\u002Fetc\u002Fapt\u002Fsources.list":1}
,"\u002Fetc\u002Fapt\u002Fsources.list":{"root":1,"uncomment":1}
,"root":{"$sudo":1}
,"$sudo":{"\u002Fetc\u002Fapt\u002Fsources.list":1,"apt-get":1}
,"uncomment":{"following":1}
,"following":{"line":1}
,"line":{"file":1}
,"file":{"removi":1}
,"removi":{"leading":1}
,"leading":{"character":1}
,"character":{"deb":1}
,"deb":{"http:\u002F\u002Fports.ubuntu.com\u002Fubuntu-ports\u002Fxenial":1}
,"http:\u002F\u002Fports.ubuntu.com\u002Fubuntu-ports\u002Fxenial":{"universe":1}
,"update":{"repository":1,"install":1}
,"repository":{"$sudo":1}
,"apt-get":{"update":1,"install":1}
,"mesa-utils":{"mesa-utils-extra":1,"$sudo":1}
,"mesa-utils-extra":{"packages":1,"application":1}
,"packages":{"$sudo":1}
,"steps":{"$export":1}
,"$export":{"display=:0":1}
,"display=:0":{"$x&$\u002Fusr\u002Fbin\u002Fes2gears":1}
,"$x&$\u002Fusr\u002Fbin\u002Fes2gears":{"$\u002Fusr\u002Fbin\u002Fglxgears":1}
}
;Search.control.loadWordPairs(pairs);
