var pairs =
{
"power":{"management":1,"thermal":1,"gate":1,"state":1,"performance":1,"saving":1,"extend":1,"states":1,"aud":1,"rails":1,"rail":1,"tree":1,"efficiency":1,"effici":1,"consumption":1,"limited":1,"budget":1,"cycle":1,"(tdp)":1,"domain":1,"delivery":1,"livery":1,"monitors":1,"<n>":1,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0040\u002Fiio:device0":1,"input":1,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0042\u002Fiio:device2":1,"execut":1,"requency":1}
,"management":{"tx2":1,"thermal":1,"electrical":1,"features":1,"however":1,"frequency":1,"(bpmp)":1,"firmware":1,"tegra":1,"strategy":1,"tuned":1,"cpufreq":1,"cpuidle":1,"per-core":1,"essential":1,"provides":1,"performed":1,"processor":1,"clock":1,"requires":1,"bpmp":1,"eatures":1,"using":1,"fan":1,"uses":1,"reporting":1,"host":1,"ntegrated":1}
,"tx2":{"\u002Ftx2i":1,"mode":1,"module":1,"developer":1,"performance":1}
,"\u002Ftx2i":{"devices":1}
,"devices":{"nvidia":1,"comprising":1,"within":1,"additionally":1,"correctly":1,"measure":1,"used":1,"cooling":1,"nct1008":1,"sense":1,"gpu_balanced":1,"provides":1}
,"nvidia":{"tegra":1,"tegra18x-cpuidle":1,"follows":1}
,"tegra":{"system-on-a-chip":1,"board":1,"imple":1,"dram":1,"maintains":1,"exiting":1,"bsp":1,"may":1,"uses":1,"ndled":1,"devices":1,"core":1,"cpu":1,"architecture":1,"hardware":1,"cpuidle":1,"chipsets":1,"ermal":1,"thermal":1,"performed":1,"sensing":1,"several":1,"platform":1,"platforms":1,"enters":1,"exits":1,"soctherm":1,"platfor":1,"four":1,"ensure":1,"aotag":1,"sys":1,"systems":1,"stem":1}
,"system-on-a-chip":{"nvidia":1}
,"board":{"support":1,"configuration":1,"design":1,"power":1,"information":1,"tegra":1,"3-c":1,"supply":1,"3.3":1,"1.8":1}
,"support":{"package":1,"firmware":1,"idle":1}
,"package":{"(bsp)":1}
,"(bsp)":{"provides":1}
,"provides":{"feature":1,"uniformly":1,"abstract":1,"mechanism":1,"regula":1,"tegra-specific":1,"following":1,"generic":1,"knobs":1,"several":1,"example":1,"different":1,"simple":1,"thermal":1,"fan":1,"veral":1,"aotag":1,"trip":1,"certain":1,"har":1,"jetson_clocks.sh":1}
,"feature":{"related":1,"example":1,"requires":1}
,"related":{"power":1,"techniques":1,"frequ":1,"tools":1}
,"thermal":{"management":1,"elect":1,"electrical":1,"throttli":1,"reset":1,"manageme":1,"sensors":1,"manage":1,"action":1,"framework":1,"zone":1,"sensor":1,"zones":1,"rformance":1,"knobs":1,"sensing":1,"shutd":1,"constraints":1,"capabilities":1,"events":1,"shutdown":1,"fram":1,"trips":1,"zon":1,"mess":1,"cooling":1,"thrott":1,"throttling":1,"event":1,"act":1,"trip":1,"alert":1,"mrq":1,"amework":1}
,"electrical":{"management":1,"problems":1,"limits":1}
,"features":{"deliver":1,"visible":1,"power":1,"dynamically":1,"present":1,"topic":1,"tegra":1,"implemented":1,"whose":1,"statically":1,"part":1}
,"deliver":{"best":1,"equested":1}
,"best":{"user":1,"rformance":1,"possible":1}
,"user":{"experience":1,"example":1,"subject":1}
,"experience":{"possible":1,"ensures":1,"tegra":1,"device":1,"minimally":1,"similarly":1}
,"possible":{"given":1,"capping":1,"performance":1}
,"given":{"constraints":1,"abi":1,"tem":1,"group":1,"sensor":1,"trip":1}
,"constraints":{"particular":1,"vice":1}
,"particular":{"platform":1,"task":1,"sensor":1}
,"platform":{"target":1,"nitialization":1,"power":1,"ensure":1,"avoids":1,"drivers":1,"driver":1,"bpmp":1,"specific":1,"includes":1}
,"target":{"user":1,"frequency":1,"mode":1}
,"ensures":{"perception":1,"cpu":1,"hat":1}
,"perception":{"device":1}
,"device":{"provides":1,"tree":1,"cat":1,"trees":1,"drivers":1,"trip":1,"configuring":1,"becomes":1,"passive":1,"associated":1,"actually":1,"remove":1,"clock":1,"classified":1,"information":1,"within":1,"driver":1,"pwm-fan":1,"maps":1,"attached":1,"feels":1,"heats":1,"sc7":1,"events":1,"jetson":1}
,"uniformly":{"high":1}
,"high":{"performance":1,"temperature":1}
,"performance":{"excellent":1,"thermal":1,"encompasses":1,"scenarios":1,"governor":1,"ecause":1,"given":1,"however":1,"manage":1,"tegra":1,"sett":1,"execute":1}
,"excellent":{"battery":1}
,"battery":{"life":1,"supplies":1,"voltage":1,"controll":1}
,"life":{"perfect":1,"features":1}
,"perfect":{"stability":1}
,"stability":{"comfortable":1}
,"comfortable":{"cool":1}
,"cool":{"touch":1}
,"touch":{"topic":1}
,"topic":{"describes":1,"introduces":1}
,"describes":{"power":1,"features":1,"supported":1,"tools":1}
,"elect":{"rical":1}
,"rical":{"management":1}
,"visible":{"software":1}
,"software":{"tools":1,"select":1,"actively":1,"initiate":1,"choose":1,"main":1,"run":1,"clock":1,"shutdown":1,"cooldown":1,"throttling":1,"pwm_fan.c":1,"slowdown":1,"hardware":1,"program":1,"thermal":1,"programmed":1,"becomes":1}
,"tools":{"related":1,"sample":1,"techniques":1}
,"techniques":{"interacting":1,"section":1,"manage":1}
,"interacting":{"features":1}
,"dynamically":{"constrain":1,"imposed":1}
,"constrain":{"knobs":1}
,"knobs":{"clock":1,"constrained":1,"tune":1,"available":1}
,"clock":{"gate":1,"frequencies":1,"voltage":1,"register":1,"tree":1,"domains":1,"source":1,"adjustment":1,"speed":1,"cpu":1,"halted":1,"configuration":1,"settings":1,"throttling":1,"lowered":1,"frequency":1,"throttled":1,"information":1,"script":1}
,"gate":{"settings":1,"(or":1}
,"settings":{"clock":1,"voltages":1,"boot":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu1\u002Fonline":1,"a57":1,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevfreq\u002F17000000.gp10b":1,"\u002Fsys\u002Fkernel\u002Fnvpmodel_emc_cap\u002Femc_iso_cap":1,"govern":1,"system":1,"store":1,"file":1,"--store":1,"execute":1}
,"frequencies":{"power":1,"require":1,"idle":1,"number":1,"pre-qualified":1,"cpu":1,"frequencies":1,"selected":1,"optimized":1,"following":1,"report":1}
,"(or":{"regulator":1}
,"regulator":{"enable)":1,"framework":1,"consumer":1,"provider":1,"consumers":1,"provides":1,"may":1,"supply":1}
,"enable)":{"settings":1}
,"voltages":{"processor":1,"vice":1}
,"processor":{"power":1,"(bpmp)":1}
,"state":{"(i.e":1,"elected":1,"selected":1,"availability":1,"extraordinarily":1,"range":1,"functionality":1,"state":1,"maintained":1,"via":1,"tegra":1,"pmc":1,"occurs":1,"software":1,"power":1,"mapping":1,"chipset":1,"comments":1,"clock":1,"description":1,"cluster":1,"stays":1,"idle":1,"meaning":1,"during":1,"cpu":1,"core":1,"statistics":1,"read":1,"run":1,"mce\u002Fmts":1,"example":1,"counts":1,"boo":1,"cc6":1,"boot":1,"con":1,"thermal":1,"fan":1,"operation":1,"per":1,"oscillator":1,"firmware":1,"sc7":1,"ited":1}
,"(i.e":{"idle":1,"vdd_in)":1}
,"idle":{"state":1,"sabled":1,"power":1,"management":1,"states":1,"final":1,"tegra-specific":1,"tegra":1,"idle":1,"task":1,"offline":1,"time":1}
,"elected":{"cpu)":1}
,"cpu)":{"peripheral":1}
,"peripheral":{"power":1,"devices":1}
,"selected":{"i\u002Fo":1,"runtime":1,"tuned":1,"user":1}
,"i\u002Fo":{"controller)":1,"pads":1}
,"controller)":{"chipset":1}
,"chipset":{"power":1}
,"availability":{"cpu":1}
,"cpu":{"cores":1,"adjusts":1,"frequency":1,"thermal":1,"may":1,"exposes":1,"via":1,"power":1,"dynamic":1,"tegra":1,"nafl":1,"voltage":1,"frequencies":1,"core":1,"cluster":1,"idle":1,"last":1,"denver":1,"gpu":1,"online":1,"a57":1,"maximal":1,"clock":1,"khz":1,"clusters":1,"(x4)":1,"sens":1,"sensor":1,"temperatures":1,"cycle":1,"lower":1,"upper":1,"hot":1,"echo":1,"state":1}
,"cores":{"knobs":1,"cluster":1,"read":1,"online":1,"frequencies":1}
,"constrained":{"feature":1}
,"example":{"cpufreq":1,"prior":1,"vdd_cpu":1,"higher":1,"final":1,"status":1,"ctual":1,"number":1,"entry":1,"thermal":1,"tegra":1,"thermal_zone_cpu":1,"framework":1}
,"cpufreq":{"implements":1,"consequently":1,"tegra":1,"subsystem":1,"governor":1,"platform":1}
,"implements":{"load":1,"cpu":1,"emc":1,"feedback":1,"hysteresis":1}
,"load":{"based":1}
,"based":{"scaling":1,"busy":1,"pre-defined":1,"type":1,"current":1,"temperature":1,"proximi":1}
,"scaling":{"based":1,"closely":1,"example":1,"dynamic":1,"idle":1,"(dfs)":1,"policies":1,"depends":1,"memory":1,"policy":1,"enabled":1,"run":1}
,"busy":{"cpu":1}
,"adjusts":{"cpu":1}
,"frequency":{"accordingly":1,"cpufreq":1,"proportional":1,"lock":1,"scaling":1,"management":1,"change":1,"caling":1,"(mhz)":1,"unit":1,"thereby":1,"direct":1,"cpu":1,"tables":1,"cap":1,"changes":1,"temperature":1,"ensor":1,"settings":1,"run":1,"value":1}
,"accordingly":{"cpu":1}
,"however":{"override":1,"thes":1}
,"override":{"target":1}
,"consequently":{"attempting":1,"tegra":1}
,"attempting":{"debug":1}
,"debug":{"power":1}
,"problems":{"fami":1}
,"fami":{"liarize":1}
,"liarize":{"yourself":1}
,"yourself":{"power":1}
,"present":{"kernel-space":1,"sensor":1,"oup":1,"nodes":1}
,"kernel-space":{"power":1,"interfaces":1}
,"saving":{"features":1,"feature":1}
,"imple":{"ments":1}
,"ments":{"save":1}
,"save":{"power":1,"state":1}
,"extend":{"battery":1,"ing":1}
,"implemented":{"linux":1}
,"linux":{"ker":1,"tegra":1,"power":1,"kernel":1,"common":1,"regulator":1,"device":1,"cpufreq":1,"cpuidle":1,"thermal":1,"trip":1,"hermal":1}
,"ker":{"nel":1}
,"nel":{"support":1}
,"firmware":{"hardware":1,"running":1,"configured":1,"aotag.c":1,"nct1008.c":1,"software":1,"linux":1,"described":1,"hosts":1,"example":1,"provides":1,"falls":1,"refers":1,"programs":1,"pports":1}
,"hardware":{"without":1,"ake":1,"power":1,"drivers":1,"reference":1,"assistance":1,"clock":1,"thermal":1,"throttling":1,"shutdown":1,"tegra":1,"reset":1,"blocks":1,"throttlin":1,"handles":1,"throttle":1,"worst-case":1}
,"without":{"significant":1,"knowledge":1,"thermal_zone":1,"side":1}
,"significant":{"involvement":1,"clock":1}
,"involvement":{"user-space":1}
,"user-space":{"chipset":1,"kernel-space":1}
,"states":{"supported":1,"listed":1,"following":1,"power":1,"devices":1,"onto":1,"follows":1,"core":1,"cpu":1,"applicable":1,"extend":1,"tegra":1,"llows":1,"denoted":1,"cluster":1,"ccplex":1,"table":1,"available":1,"clock-gating":1,"cc1":1,"ccp3":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":1,"status":1,"enabled":1,"pwm-rpm":1,"translate":1}
,"supported":{"power":1}
,"listed":{"order":1}
,"order":{"increasing":1}
,"increasing":{"flexibility":1}
,"flexibility":{"configurability":1}
,"configurability":{"system":1}
,"system":{"sc7":1,"stabili":1,"keeps":1,"tuning":1,"rising":1,"save":1,"(host":1,"running":1,"low":1,"includes":1,"becomes":1,"software":1,"clock":1}
,"sc7":{"minimally":1,"software":1,"enters":1,"define":1,"platforms":1,"state":1,"turned":1,"rail":1,"sta":1,"bpmp":1}
,"minimally":{"flexible":1,"impacted":1}
,"flexible":{"deep":1,"terms":1}
,"deep":{"sleep":1}
,"sleep":{"(sc7)":1,"software":1,"active":1,"(sc7":1,"supply":1}
,"(sc7)":{"offers":1}
,"offers":{"small":1}
,"small":{"amount":1,"ount":1}
,"amount":{"configur":1,"current":1}
,"configur":{"ability":1}
,"ability":{"example":1}
,"prior":{"entering":1}
,"entering":{"deep":1,"sc7":1}
,"select":{"hardware":1}
,"ake":{"events":1}
,"events":{"wake":1,"active":1,"thermal":1,"temperature":1,"over-current":1,"impact":1,"rare":1,"detect":1,"throttle":1,"occur":1,"transient":1}
,"wake":{"chip":1,"events":1}
,"chip":{"deep":1,"dedicated":1,"unavailable":1,"thermal":1,"logically":1}
,"active":{"state":1,"mode)":1,"mode":1,"power":1,"devices":1,"user":1,"core":1,"cores":1,"passive":1,"cooling":1}
,"extraordinarily":{"flexible":1}
,"terms":{"power":1,"accuracy":1}
,"encompasses":{"activity":1}
,"activity":{"levels":1}
,"levels":{"low":1,"side":1,"sc7":1,"follows":1}
,"low":{"power":1,"-power":1,"power-state":1,"trip":1}
,"aud":{"playback":1}
,"playback":{"peak":1}
,"peak":{"performance":1,"urrent":1,"current":1}
,"scenarios":{"wer":1}
,"wer":{"consumption":1}
,"consumption":{"active":1,"good":1,"15w":1,"helps":1,"maximizing":1,"firmware":1,"modeling":1}
,"range":{"tens":1,"degrees":1}
,"tens":{"milliwatts":1}
,"milliwatts":{"multiple":1}
,"multiple":{"watts":1}
,"watts":{"supported":1}
,"following":{"table":1,"transition":1,"option":1,"compatibility":1,"command":1,"node":1,"mmand":1,"device":1,"ommand":1,"factors":1,"file":1,"example":1,"capabiliti":1,"components":1,"code":1,"tab":1,"thermal":1,"tegra":1,"modes":1,"thermtrip":1,"procedures":1,"commands":1}
,"table":{"describes":1,"below":1,"(bct":1,"specific":1,"included":1,"average":1,"identifies":1,"tegra":1}
,"functionality":{"characteristics":1}
,"characteristics":{"power":1}
,"rails":{"none":1,"supplying":1,"vdd_rtc":1,"powered":1,"(inc":1,"(vdd_core":1}
,"none":{"power":1}
,"supplying":{"tegra":1}
,"dram":{"powered":1,"exiting":1,"power":1,"maintains":1,"self-refresh":1,"itical":1}
,"powered":{"state":1,"vdd_co":1,"power":1,"companion":1}
,"maintained":{"tegra":1}
,"exiting":{"exit":1,"software":1}
,"exit":{"state":1}
,"via":{"cold-boot":1,"linux":1,"bpmp":1,"fan":1,"software":1,"oil":1}
,"cold-boot":{"(into":1}
,"(into":{"active":1}
,"mode)":{"deep":1}
,"(sc7":{"power":1}
,"vdd_rtc":{"vddio_ddr":1}
,"vddio_ddr":{"vddio_sys":1}
,"vddio_sys":{"dram":1,"vdd_core":1}
,"rail":{"powered":1,"powers":1,"dependencies":1,"power-gated":1,"powering":1,"name":1,"current":1,"voltage":1,"power":1,"names":1,"channel":1,"note":1,"rail":1,"jetson":1}
,"vdd_co":{"vdd_cpu":1}
,"vdd_cpu":{"powered":1,"may":1,"vdd_sram":1}
,"maintains":{"small":1,"sta":1,"list":1}
,"ount":{"state":1}
,"pmc":{"block":1}
,"block":{"dram":1}
,"sta":{"exiting":1,"nodes":1,"distinction":1}
,"occurs":{"based":1,"cooling":1}
,"pre-defined":{"wake":1}
,"mode":{"active":1,"max-p":1,"mode":1,"sever":1,"configurations":1,"name":1,"online":1,"run":1,"module":1,"until":1,"rsists":1,"adding":1,"<power_model":1,"thermal":1,"increase":1}
,"vdd_core":{"dram":1}
,"(inc":{"luding":1}
,"luding":{"vdd_c":1}
,"vdd_c":{"pu)":1}
,"pu)":{"may":1}
,"may":{"state":1,"idle":1,"powered":1,"power-gated":1,"decline":1,"present":1,"due":1,"result":1,"overhea":1,"cause":1}
,"actively":{"manages":1,"manage":1}
,"manages":{"power":1}
,"comprising":{"tegra":1}
,"initiate":{"transition":1}
,"transition":{"active":1,"cpu":1,"dram":1}
,"mapping":{"linux":1,"various":1}
,"bsp":{"maps":1,"configures":1,"act":1,"new":1,"drivers":1,"implements":1,"includes":1,"provides":1,"supports":1,"specific":1,"tuned":1,"reads":1,"thermal":1,"provided":1,"nsors":1,"balanced":1,"performs":1,"defines":1,"uses":1}
,"maps":{"hardware":1,"pwm":1}
,"onto":{"linux":1}
,"follows":{"power":1,"model":1,"bpmp":1,"thermal":1,"hardware":1,"command":1,"jetson_clocks.sh":1}
,"comments":{"-suspend":1}
,"-suspend":{"sc7":1}
,"choose":{"whether":1}
,"whether":{"enter":1}
,"enter":{"sc7":1,"specified":1}
,"enters":{"suspend":1,"sc7":1}
,"suspend":{"running\u002Fidle":1}
,"running\u002Fidle":{"(display":1}
,"(display":{"off)":1}
,"off)":{"active":1}
,"within":{"tegra":1,"cluster":1,"safe":1,"thermal":1,"recomm":1,"a57":1,"gpu":1,"control":1}
,"sabled":{"driver":1}
,"driver":{"control":1,"cpu":1,"provides":1,"called":1,"tegra":1,"reconciles":1,"plugs":1,"exposes":1,"transition":1,"optionally":1,"cpuidle":1,"devices":1,"module":1,"linux":1,"walks":1,"uses":1,"receives":1,"firmware":1,"may":1}
,"control":{"example":1,"bpmp":1,"temperatures":1,"system":1,"loop":1,"cooling":1,"programming":1,"change":1,"during":1,"hardware":1,"heat":1}
,"companion":{"cpu":1}
,"power-gated":{"note":1,"system":1}
,"note":{"nvidia":1,"ascii":1,"background":1,"ina":1,"jetson":1,"terms":1}
,"uses":{"instead":1,"nafll":1,"temperature":1,"following":1,"fan":1,"current":1,"output":1,"fuses":1,"thermal":1}
,"instead":{"lpx":1,"gpu":1}
,"lpx":{"name":1}
,"name":{"chipset":1,"edp":1,"tegra":1,"cooling":1,"shown":1,"sensed":1,"in_current":1,"description":1,"vol":1,"(i.e":1}
,"voltage":{"management":1,"ynamic":1,"scaling":1,"current":1,"appropriate":1,"rail":1,"reduces":1,"additionally":1,"pllx":1,"guaranteed":1,"levels":1,"inductor":1,"droop":1,"in_power":1}
,"proportional":{"voltage":1,"integral":1}
,"ynamic":{"voltage":1}
,"closely":{"related":1}
,"frequ":{"ency":1}
,"ency":{"scaling":1,"peaks":1}
,"higher":{"frequencies":1,"voltages":1,"rpm":1,"temperature":1,"cooling":1,"frequency":1}
,"require":{"higher":1,"minimum":1}
,"vice":{"versa":1,"thermal":1}
,"versa":{"clock":1}
,"register":{"manipulation":1,"thermal":1,"trip":1}
,"manipulation":{"tegra":1}
,"ndled":{"boot":1}
,"boot":{"power":1,"time":1,"according":1,"confi":1,"offset":1,"calibrate":1}
,"(bpmp)":{"firm":1,"owdown":1}
,"firm":{"ware":1}
,"ware":{"power":1,"shutdown":1}
,"running":{"linux":1,"bpmp":1,"host":1,"cpus":1,"therefore":1}
,"kernel":{"driver":1,"requested":1,"software":1,"bpmp":1,"replaced":1}
,"exposes":{"som":1,"two":1}
,"som":{"ewhat":1}
,"ewhat":{"simplified":1}
,"simplified":{"view":1}
,"view":{"physical":1}
,"physical":{"clock":1}
,"tree":{"software":1,"framework":1,"topology":1,"suc":1,"appro":1,"configured":1,"board":1,"blob":1,"blob)":1,"node":1,"following":1,"file":1,"optimization":1,"thermal":1,"sers":1,"programs":1,"binary":1,"throttle":1,"bindings":1}
,"main":{"cpu":1,"module":1}
,"common":{"ock":1,"loads":1}
,"ock":{"framework":1}
,"framework":{"significant":1,"linux":1,"provides":1,"connect":1,"enable":1,"thermal":1,"available":1,"makes":1,"cmd_thermal_query_abi":1,"information":1,"bpmp":1,"register":1,"maintains":1,"examines":1,"ensure":1,"sends":1,"implements":1}
,"domains":{"chip":1}
,"dedicated":{"clock":1}
,"source":{"known":1}
,"known":{"nois":1,"vance":1}
,"nois":{"aware":1}
,"aware":{"frequency":1}
,"lock":{"loop":1}
,"loop":{"(nafll)":1,"linux":1,"milarly":1}
,"(nafll)":{"regulator":1}
,"abstract":{"ion":1}
,"ion":{"allows":1}
,"allows":{"regulator":1,"continuous":1,"bpmp":1,"host":1}
,"consumer":{"drivers":1,"apis":1}
,"drivers":{"dyna":1,"within":1,"peripheral":1,"registering":1,"implement":1,"policy":1,"(cpufreq":1,"usb":1,"on-die":1,"provide":1,"mperature":1,"linux":1}
,"dyna":{"mically":1}
,"mically":{"adjust":1}
,"adjust":{"voltage":1}
,"current":{"regulators":1,"mode":1,"temperature":1,"trip":1,"wit":1,"efore":1,"large":1,"consumption":1,"volt":1,"in_voltage":1,"power":1,"frequency":1,"clock":1,"settings":1}
,"regulators":{"ntime":1,"power":1}
,"ntime":{"without":1}
,"knowledge":{"underlying":1}
,"underlying":{"hardwar":1,"hardware":1}
,"hardwar":{"power":1,"thermal":1}
,"mechanism":{"platform":1,"governors":1,"following":1}
,"nitialization":{"code":1}
,"code":{"declare":1,"snippet":1}
,"declare":{"power":1}
,"topology":{"assign":1}
,"assign":{"driver":1,"unique":1}
,"regula":{"tors":1}
,"tors":{"node":1}
,"node":{"hardware":1,"enable":1,"status":1,"note":1,"type":1,"cat":1,"value":1}
,"suc":{"driver":1}
,"called":{"regulator":1,"critical":1}
,"provider":{"driver":1}
,"configures":{"platform":1,"sensor":1}
,"appro":{"priately":1}
,"priately":{"tegra":1}
,"additionally":{"drivers":1,"final":1,"tegra":1,"nsors":1,"monito":1,"framework":1}
,"act":{"regulator":1,"ions":1}
,"consumers":{"appropriate":1,"cause":1}
,"appropriate":{"porting":1,"nafll":1,"node":1,"device":1,"core\u002Fcluster":1}
,"porting":{"tegra":1}
,"new":{"platform":1,"printed":1}
,"ensure":{"hat":1,"purious":1,"accurate":1,"notifi":1}
,"hat":{"platform":1,"replacing":1,"cpu":1}
,"configured":{"correctly":1,"via":1,"avfs":1}
,"correctly":{"match":1,"regulator":1}
,"match":{"underlying":1}
,"apis":{"device":1}
,"configuration":{"file":1,"jetson":1,"bpmp":1}
,"file":{"infor":1,"following":1,"disable":1,"emc":1,"<top>\u002Fdevice\u002Ft18x\u002Ft186\u002Fnvpmodel.conf":1,"restore":1,"jetson_clocks.sh":1,"default":1,"l4t_dfs.conf":1}
,"infor":{"mation":1}
,"mation":{"new":1}
,"avoids":{"conflicts":1}
,"conflicts":{"betw":1}
,"betw":{"een":1}
,"een":{"functions":1}
,"functions":{"using":1,"tegra":1}
,"using":{"i\u002Fo":1,"kconfig":1,"device":1,"cpu-ba":1,"application":1,"fan":1,"acti":1,"hermal":1,"callback":1,"perfor":1,"sysfs":1,"cpu":1}
,"pads":{"bsp":1,"chip":1}
,"registering":{"regulator":1}
,"cause":{"i\u002Fo":1,"irreversible":1,"lower":1}
,"unavailable":{"functions":1}
,"core":{"power":1,"management":1,"framework":1,"cpuidle":1,"state":1,"clock-gated":1,"within":1,"transitioning":1,"puts":1,"cpu":1,"states":1,"pathnames":1,"read":1,"enter":1,"actual":1,"less":1,"spent":1,"entered":1,"settings":1,"number":1}
,"(vdd_core":{"vdd_cpu":1}
,"vdd_sram":{"vdd_gpu)":1}
,"vdd_gpu)":{"direct":1}
,"direct":{"control":1,"support":1,"impact":1}
,"bpmp":{"firmware":1,"evice":1,"ensures":1,"dev":1,"information":1,"sensors":1,"sensor":1,"ermal":1,"thermal":1,"tegra":1,"modules":1,"owne":1,"device":1}
,"evice":{"tree":1,"device":1}
,"blob":{"(which":1}
,"(which":{"distinct":1}
,"distinct":{"linux":1}
,"blob)":{"cpu":1}
,"strategy":{"includes":1}
,"includes":{"dynam":1,"drivers":1,"several":1,"driver":1,"current":1,"imitations":1}
,"dynam":{"frequency":1}
,"dynamic":{"voltage":1,"frequency":1}
,"tuned":{"tegra":1,"achieve":1,"provide":1}
,"architecture":{"frequency":1}
,"(dfs)":{"linux":1}
,"subsystem":{"cpufreq":1,"comprises":1}
,"comprises":{"platform":1}
,"implement":{"clock":1,"frequency":1}
,"adjustment":{"mechanism":1}
,"governors":{"implement":1,"platform":1,"thermal":1,"tegra":1}
,"policies":{"core":1}
,"connect":{"governors":1}
,"policy":{"frequency":1,"following":1,"runtime":1}
,"depends":{"cpufreq":1}
,"governor":{"selected":1,"requests":1,"selects":1,"tegra":1,"implements":1,"progressively":1,"uses":1,"progre":1}
,"runtime":{"details":1,"entries":1}
,"details":{"consult":1,"mrq":1}
,"consult":{"information":1}
,"information":{"available":1,"linux":1,"mce\u002Fmts":1,"thermal":1,"fan":1,"aotag":1,"ina3221":1,"run":1}
,"available":{"<top":1,"t186":1,"<top>\u002Fkernel\u002Fdocumentation\u002Fthermal\u002Fsysfs-api.txt":1,"<top>\u002Fkernel\u002Fdocumentation\u002Fdevicetree\u002Fbindings\u002Fthe":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fscaling_avail":1,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevfreq\u002F17000000.gp10b":1,"$home\u002Fjetson_clocks":1}
,"<top":{">\u002Fkernel\u002Fkernel\u002Fkernel-4.4\u002Fdocumentation\u002Fcpu-freq\u002Ffor":1}
,">\u002Fkernel\u002Fkernel\u002Fkernel-4.4\u002Fdocumentation\u002Fcpu-freq\u002Ffor":{"tegra":1}
,"reference":{"design":1}
,"design":{"cpufreq":1,"calibration":1,"emc":1,"power":1,"considerations":1,"limits":1,"mana":1}
,"achieve":{"balan":1,"above":1}
,"balan":{"power":1}
,"requests":{"cpu":1,"information":1,"made":1,"(mrq)":1,"handled":1,"api":1}
,"change":{"tegra-specific":1,"mode":1,"switch":1,"speed":1,"framework":1,"notif":1,"cpu":1,"gpu":1,"lower":1,"emc":1}
,"tegra-specific":{"cpufreq":1,"cpuidle":1}
,"reconciles":{"request":1}
,"request":{"limi":1}
,"limi":{"imposed":1}
,"imposed":{"thermal":1}
,"limits":{"iver":1,"dynamically":1,"cooling":1,"device":1,"software":1,"follows":1,"events":1}
,"iver":{"updates":1}
,"updates":{"clock":1}
,"speed":{"cpu":1,"control":1,"fan":1}
,"nafll":{"clock":1,"deliver":1}
,"nafl":{"configured":1}
,"avfs":{"hardware":1}
,"assistance":{"bpmp":1}
,"equested":{"cpu":1}
,"cpuidle":{"linux":1,"infrastructure":1,"lacks":1,"driver":1,"framework":1,"governor":1,"enable":1,"configuration":1,"device":1,"{compatible":1,"boot":1}
,"infrastructure":{"supports":1,"<top>\u002Fkernel\u002Fkernel\u002Fkernel-4.4\u002Fdocumentation\u002Fcpuid":1}
,"supports":{"implementation":1,"fan":1}
,"implementation":{"soc":1}
,"soc":{"-specific":1,"resources":1,"power":1}
,"-specific":{"idle":1}
,"lacks":{"direct":1}
,"applicable":{"entire":1}
,"entire":{"cpu":1}
,"cluster":{"idle":1,"information":1,"transitions":1,"cluste":1,"state":1,"clock":1,"ransitions":1,"low":1,"states":1,"read":1,"a57":1,"stat":1,"run":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu0\u002Fcpufreq\u002Fscaling_min_f":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu1\u002Fcpufreq\u002Fscaling_max_f":1,"gpu":1,"grouped":1}
,"ing":{"beyond":1,"static":1}
,"beyond":{"cpu":1}
,"<top>\u002Fkernel\u002Fkernel\u002Fkernel-4.4\u002Fdocumentation\u002Fcpuid":{"le\u002Fnvidia":1}
,"le\u002Fnvidia":{"provides":1}
,"plugs":{"cpuidle":1}
,"enable":{"cpu":1,"cpuid":1,"cpuidle":1,"boot":1}
,"per-core":{"cpu":1,"state":1}
,"two":{"per-core":1,"software":1}
,"llows":{"core":1}
,"description":{"cpu":1,"cc1":1,"rail_name_<n>":1,"channel":1,"--show":1}
,"clock-gated":{"transition":1}
,"final":{"core":1,"cpu":1,"fail-safe":1}
,"transitions":{"idle":1}
,"cluste":{"idle":1}
,"cc1":{"cpu":1,"auto":1,"enabled":1}
,"halted":{"additionally":1}
,"ransitions":{"idle":1}
,"optionally":{"disables":1,"following":1}
,"disables":{"soc":1}
,"resources":{"wher":1}
,"wher":{"cpu":1}
,"last":{"active":1}
,"transitioning":{"dle":1}
,"dle":{"optionally":1}
,"self-refresh":{"clock-gate":1}
,"clock-gate":{"mc\u002Femc":1}
,"mc\u002Femc":{"halt":1}
,"halt":{"various":1}
,"various":{"plls":1,"device":1,"cpu":1,"clocks":1,"power":1,"ramp":1,"bpmp":1,"thro":1}
,"plls":{"cpu":1}
,"task":{"scheduled":1,"cpuidle":1,"puts":1}
,"scheduled":{"runna":1}
,"runna":{"ble":1}
,"ble":{"tasks":1,"reporting":1}
,"tasks":{"left":1}
,"left":{"runqueue":1}
,"runqueue":{"particular":1}
,"selects":{"core":1}
,"puts":{"low":1,"entire":1}
,"-power":{"state":1}
,"stays":{"until":1,"mode":1}
,"until":{"interrupt":1,"change":1,"higher":1,"temperature":1}
,"interrupt":{"kes":1}
,"kes":{"process":1}
,"process":{"work":1}
,"work":{"last":1}
,"offline":{"state":1}
,"power-state":{"ccplex":1,"firmw":1}
,"ccplex":{"idle":1,"states":1}
,"denoted":{"states":1,"ccp":1}
,"ccp":{"states":1}
,"below":{"summarizes":1,"54c":1,"limit":1,"ccuracy":1}
,"summarizes":{"different":1}
,"different":{"states":1,"governors":1}
,"t186":{"state":1}
,"meaning":{"core":1}
,"clock-gating":{"cluster":1,"cc3":1}
,"auto":{"clock-gating":1}
,"cc3":{"fmax@vmin":1,"using":1}
,"fmax@vmin":{"ccplex":1}
,"ccp3":{"emc":1}
,"emc":{"reduction":1,"frequency":1,"vfs":1,"table":1,"dvfs":1,"clock":1,"frequencies":1,"clocks":1,"lower":1,"upper":1,"min":1}
,"reduction":{"state":1}
,"during":{"cc3":1,"sc7":1,"various":1,"boot":1,"nimum":1}
,"kconfig":{"device":1}
,"cpuid":{"kconfig":1}
,"option":{"config_cpu_idle=y":1}
,"config_cpu_idle=y":{"enable":1}
,"compatibility":{"string":1}
,"string":{"alre":1,"nvidia":1}
,"alre":{"ady":1}
,"ady":{"enabled":1}
,"enabled":{"cpuidle":1,"cluster":1,"example":1,"default":1}
,"{compatible":{"nvidia":1}
,"tegra18x-cpuidle":{"status":1,"appropriate":1}
,"status":{"okay":1,"core":1,"rite":1,"cluster":1}
,"okay":{"core":1,"polling-delay":1}
,"denver":{"core":1,"cores":1,"cluster":1,"bloat":1,"idle":1}
,"pathnames":{"nodes":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcp":1}
,"nodes":{"represent":1,"following":1,"naming":1,"follows":1,"modify":1,"read":1}
,"represent":{"ore":1}
,"ore":{"states":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":{"<x>":1,"<x>\u002Fcpuidle\u002Fstate":1,"\u002Fcpufreq":1}
,"<x>":{"\u002Fcpuidle\u002Fstate0\u002F*\u2022":1}
,"\u002Fcpuidle\u002Fstate0\u002F*\u2022":{"a57":1,"status":1}
,"a57":{"core":1,"cores":1,"cpu":1,"cluster":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcp":{"<x>":1}
,"read":{"appropriate":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle_a57\u002Fdeepest_cc_state":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle":1,"following":1,"using":1,"rail":1,"ina3221":1,"vdd_in":1}
,"rite":{"ascii":1}
,"ascii":{"node":1,"corresponds":1}
,"corresponds":{"disabled":1}
,"disabled":{"enabl":1}
,"enabl":{"cluster":1}
,"type":{"cores":1,"critical":1,"passive":1,"cooling":1,"point":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle_a57\u002Fdeepest_cc_state":{"denver":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle":{"_denver":1}
,"_denver":{"\u002Fdeepest_cc_state":1}
,"\u002Fdeepest_cc_state":{"value":1,"per-core":1}
,"value":{"returned":1,"note":1,"modifying":1,"available":1,"emc":1}
,"returned":{"cc1":1}
,"stat":{"denver":1}
,"run":{"following":1,"time":1}
,"command":{"cat":1,"requests":1,"sudo":1,"\u002Fusr\u002Fsbin":1,"cmd_thermal_host_trip_reached":1,"description":1,"echo":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Fclk_tree":1,"turn":1}
,"cat":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Ftegra_mce\u002Fcstats":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fcpuidle\u002Fstate1\u002Fusage":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fcpuidle\u002Fstate1\u002Ftime":1,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0041\u002Fiio:devic":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_m":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_c":1,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevfreq\u002F17000000.g":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fmin_rate":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fmax_rate":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Frate":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fonline":1}
,"statistics":{"number":1}
,"number":{"times":1,"cores":1,"field":1,"0-2":1,"print":1}
,"times":{"kernel":1,"specified":1,"denver":1}
,"requested":{"specified":1,"state":1}
,"specified":{"core":1,"state":1,"thermal":1}
,"<x>\u002Fcpuidle\u002Fstate":{"<y>\u002Fus":1,"<y>\u002Fti":1}
,"<y>\u002Fus":{"age":1}
,"age":{"number":1,"requests":1,"regulator":1}
,"actual":{"entered":1}
,"entered":{"specified":1,"state":1}
,"mmand":{"cat":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Ftegra_mce\u002Fcstats":{"command":1}
,"mce\u002Fmts":{"whi":1,"may":1}
,"whi":{"actually":1,"results":1}
,"actually":{"sets":1,"remove":1}
,"sets":{"state":1,"low":1}
,"decline":{"requested":1}
,"ctual":{"idle":1}
,"time":{"core":1,"microseconds":1,"remove":1,"features":1}
,"less":{"cros":1}
,"cros":{"sover":1,"ses":1}
,"sover":{"threshold":1}
,"threshold":{"value":1}
,"background":{"translations":1}
,"translations":{"denver":1}
,"bloat":{"denver":1}
,"counts":{"total":1,"inaccuracy":1}
,"total":{"time":1}
,"microseconds":{"speci":1,"denver":1}
,"speci":{"fied":1}
,"fied":{"core":1}
,"spent":{"specified":1,"state":1}
,"boo":{"read":1}
,"<y>\u002Fti":{"example":1}
,"cc6":{"run":1}
,"ommand":{"cat":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fcpuidle\u002Fstate1\u002Fusage":{"total":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fcpuidle\u002Fstate1\u002Ftime":{"disable":1}
,"disable":{"cpuidle":1,"compatibility":1,"core\u002Fcluster":1,"appropriate":1,"frequency":1}
,"remove":{"disable":1,"actu":1,"heat":1}
,"core\u002Fcluster":{"power":1,"sta":1}
,"trees":{"tegra186-a57-cpuidle.dtsi":1}
,"tegra186-a57-cpuidle.dtsi":{"tegra186-denver-cpuidle.dtsi":1}
,"tegra186-denver-cpuidle.dtsi":{"memory":1}
,"memory":{"power":1,"controller":1,"bandwidth":1,"cpu":1,"maximal":1}
,"chipsets":{"include":1}
,"include":{"power":1,"bct":1}
,"whose":{"operation":1,"temperature":1}
,"operation":{"largely":1,"during":1,"cooling":1,"temperature":1,"soc_therm":1}
,"largely":{"invisible":1}
,"invisible":{"software":1}
,"statically":{"enable":1}
,"according":{"settings":1}
,"confi":{"guration":1}
,"guration":{"table":1}
,"(bct":{"additionally":1}
,"caling":{"dynamic":1,"frequency":1}
,"controller":{"(emc\u002Fmc)":1,"passive":1}
,"(emc\u002Fmc)":{"dram":1}
,"itical":{"power":1}
,"requires":{"tuning":1,"form":1}
,"tuning":{"characterization":1,"thermal":1,"limited":1,"remedy":1}
,"characterization":{"new":1}
,"printed":{"circuit":1}
,"circuit":{"oard":1}
,"oard":{"design":1}
,"calibration":{"results":1,"complete":1}
,"results":{"include":1,"higher":1,"cooling":1,"bad":1,"rge":1}
,"bct":{"emc":1}
,"vfs":{"table":1}
,"specific":{"board":1,"thermal":1}
,"included":{"platform":1}
,"dev":{"ice":1}
,"ice":{"tree":1,"and\u002For":1}
,"factors":{"affect":1}
,"affect":{"emc":1}
,"entries":{"emc":1,"device":1}
,"dvfs":{"table":1,"capabilities":1}
,"average":{"memory":1}
,"bandwidth":{"used":1}
,"used":{"(as":1,"control":1,"communicate":1,"thermal":1,"show":1}
,"(as":{"measur":1}
,"measur":{"hardware)":1}
,"hardware)":{"requests":1}
,"made":{"various":1}
,"(cpufreq":{"graphics":1}
,"graphics":{"drivers":1}
,"usb":{"hdmi":1}
,"hdmi":{"display)":1}
,"display)":{"limits":1}
,"throttli":{"max-q":1}
,"max-q":{"max-p":1,"mode":1}
,"max-p":{"power":1,"(15w)":1,"max-p":1,"(id:3)":1}
,"efficiency":{"jetson":1,"mind":1,"achievable":1}
,"jetson":{"designed":1,"tx2":1,"tx2i":1}
,"designed":{"good":1,"power":1}
,"good":{"power":1}
,"mind":{"selecting":1}
,"selecting":{"right":1}
,"right":{"pmic":1,"sensors":1}
,"pmic":{"regulators":1,"temperature":1,"hard":1}
,"optimization":{"specifically":1}
,"specifically":{"power":1}
,"effici":{"ency":1}
,"peaks":{"module":1}
,"module":{"power":1,"max-q":1,"target":1,"stays":1,"tegr":1,"name":1,"registers":1,"3-channel":1}
,"achievable":{"dule":1}
,"dule":{"power":1}
,"15w":{"modu":1,"module":1,"15w":1,"mode":1}
,"modu":{"power":1}
,"limited":{"15w":1,"ermal":1}
,"(15w)":{"mode":1}
,"sever":{"configurations":1}
,"configurations":{"various":1,"re-defined":1}
,"online":{"possible":1,"a57":1,"d20":1}
,"capping":{"memory":1,"cpu":1,"prevents":1}
,"gpu":{"frequencies":1,"maximal":1,"clock":1,"emmc":1,"emc":1,"balanced":1,"tboard_tegra":1,"soc_therm":1,"ram":1,"(x2)":1,"tegra":1,"temperatu":1,"sensor":1,"aotag":1,"clocks":1,"drawing":1,"power":1,"lower":1,"upper":1,"frequency":1}
,"pre-qualified":{"level":1}
,"level":{"confin":1,"bsp":1}
,"confin":{"module":1}
,"re-defined":{"nvidia":1}
,"model":{"clock":1,"mode":1}
,"edp":{"max-q":1,"limit":1}
,"budget":{"n\u002Fa":1}
,"n\u002Fa":{"15w":1,"1400":1,"2000":1,"7.5w":1,"1958":1,"1497":1}
,"d20":{"cpu":1}
,"maximal":{"frequency":1}
,"(mhz)":{"2000":1,"1300":1,"1866":1,"1920":1,"1958":1,"1236":1,"1600":1,"1420":1,"1497":1,"918":1}
,"2000":{"1200":1,"354":1,"n\u002Fa":1,"gpu":1}
,"1200":{"1400":1}
,"1400":{"2000":1,"n\u002Fa":1,"1920":1,"1420":1}
,"354":{"d20":1}
,"1300":{"112":1}
,"112":{"112":1,"memory":1}
,"1866":{"1331":1}
,"1331":{"1600":1}
,"1600":{"1600":1,"default":1}
,"default":{"mode":1,"disable":1,"file":1}
,"(id:3)":{"nvpmodel":1,"change":1}
,"nvpmodel":{"clock":1}
,"tx2i":{"ucm1":1,"ucm2":1,"channel":1}
,"ucm1":{"profile":1}
,"profile":{"mode":1}
,"7.5w":{"15w":1}
,"1920":{"1200":1,"354":1}
,"1958":{"n\u002Fa":1,"gpu":1}
,"1236":{"854":1}
,"854":{"1122":1,"918":1}
,"1122":{"1122":1,"memory":1}
,"ucm2":{"profile":1}
,"1420":{"1200":1,"354":1}
,"1497":{"n\u002Fa":1,"gpu":1}
,"918":{"854":1,"918":1,"memory":1}
,"sudo":{"\u002Fusr\u002Fsbin":1,"${home}\u002Fjetson_clocks.sh":1}
,"\u002Fusr\u002Fsbin":{"\u002Fnvpmodel":1}
,"\u002Fnvpmodel":{"numbers":1,"learn":1,"once":1}
,"numbers":{"find":1}
,"find":{"current":1}
,"learn":{"options":1}
,"options":{"run":1,"description":1}
,"once":{"mode":1,"calibration":1}
,"switch":{"model":1}
,"rsists":{"across":1}
,"across":{"power":1,"die":1}
,"cycle":{"sc7":1,"unters":1}
,"define":{"custom":1,"sensors":1,"special":1}
,"custom":{"mode":1}
,"adding":{"definition":1}
,"definition":{"following":1}
,"<top>\u002Fdevice\u002Ft18x\u002Ft186\u002Fnvpmodel.conf":{"following":1}
,"entry":{"mode":1}
,"<power_model":{"id=2":1}
,"id=2":{"name=maxp_core_all":1}
,"name=maxp_core_all":{"cpu":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu1\u002Fonline":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fonline":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fonline":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu3\u002Fonline":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu3\u002Fonline":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu4\u002Fonline":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu4\u002Fonline":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu5\u002Fonline":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu5\u002Fonline":{"cpu":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu0\u002Fcpufreq\u002Fscaling_min_f":{"req":1}
,"req":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu0\u002Fcpufreq\u002Fscaling_max_f":1,"1400000":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu0\u002Fcpufreq\u002Fscaling_max_f":{"req":1}
,"1400000":{"denver":1,"gpu":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu1\u002Fcpufreq\u002Fscaling_max_f":{"req":1}
,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevfreq\u002F17000000.gp10b":{"\u002Fmin_freq":1,"\u002Fmax_freq":1,"\u002Favailable_frequencies":1}
,"\u002Fmin_freq":{"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevfreq\u002F17000000.gp10b":1}
,"\u002Fmax_freq":{"1120000000":1}
,"1120000000":{"emc":1}
,"\u002Fsys\u002Fkernel\u002Fnvpmodel_emc_cap\u002Femc_iso_cap":{"160000000":1}
,"160000000":{"frequency":1}
,"unit":{"measure":1,"gpu":1}
,"measure":{"cpu":1,"temperature":1,"temperatures":1}
,"khz":{"unit":1}
,"emmc":{"assign":1}
,"unique":{"number":1}
,"field":{"test":1}
,"test":{"case":1}
,"case":{"etermine":1}
,"etermine":{"active":1}
,"clusters":{"gpu":1}
,"subject":{"edp":1}
,"limit":{"defined":1,"orderly":1,"degrees":1,"hardware":1}
,"defined":{"mode":1,"components":1}
,"essential":{"system":1}
,"stabili":{"quality":1}
,"quality":{"user":1}
,"ermal":{"management":1,"design":1,"framework":1,"shutdown":1}
,"capabiliti":{"sensing":1}
,"sensing":{"temperature":1,"soctherm.c":1,"linux":1,"gains":1,"nct":1,"bpmp":1,"senso":1,"allows":1}
,"temperature":{"reporting":1,"devices":1,"monitored":1,"sensor":1,"limits":1,"thermal_zone_cpu":1,"sensors":1,"milli":1,"sen":1,"perform":1,"governor":1,"degrees":1,"ell":1,"remote":1,"die":1,"board":1,"range":1,"comes":1,"tegra":1,"increases":1,"clock":1,"cooling":1,"ensor":1,"rates":1,"convert":1,"oscillating":1,"known":1,"egrees":1,"given":1,"current":1,"cros":1,"sensing":1,"measurements":1,"reports":1,"sc7":1,"readings":1,"change":1,"crosses":1,"reache":1,"drops":1,"ses":1,"dropped":1,"spikes":1,"within":1}
,"reporting":{"cooldown":1,"temperature":1,"thermal":1}
,"cooldown":{"removing":1,"software":1}
,"removing":{"heat":1,"ther":1}
,"heat":{"via":1,"fan":1,"linux":1,"generation":1}
,"fan":{"ntrolling":1,"clock":1,"cooling":1,"management":1,"ntrol":1,"control":1,"speed":1,"smoothly":1,"results":1,"whi":1,"first":1}
,"ntrolling":{"heat":1}
,"throttling":{"slowdown":1,"shutdown":1,"tegraxx_throttle.c":1,"soctherm.c":1,"performed":1,"cooling":1,"type":1,"governors":1,"needs":1,"various":1,"until":1,"tegra":1,"arious":1,"relies":1,"clocks":1,"voltage":1,"element":1,"hardware":1,"performs":1,"thermal_zone_cpu":1,"levels":1,"clock":1,"unab":1}
,"slowdown":{"hardware":1}
,"shutdown":{"orderly":1,"hardwar":1,"thermal_core.c":1,"soctherm.c":1,"correction":1,"thermal":1,"special":1,"hardware":1,"ermal":1,"occurs":1,"limits":1,"limit":1,"trigger":1,"fallback":1,"final":1,"mechanism":1}
,"orderly":{"software":1,"shutdown":1}
,"reset":{"previously":1,"following":1,"high":1,"thermtrip":1,"pin":1}
,"previously":{"tegra":1}
,"performed":{"software":1,"drivers":1,"using":1,"soctherm":1}
,"manageme":{"tegra":1}
,"on-die":{"thermal":1}
,"sensors":{"board":1,"temperature":1,"tegra":1,"setup":1,"generate":1,"allow":1,"except":1,"bpmp":1,"without":1,"trip":1,"follows":1,"sensor":1,"chip":1,"a57":1,"present":1,"report":1,"capable":1,"stop":1,"restarted":1,"invalidate":1,"measuring":1,"thermal":1,"rec":1}
,"owdown":{"hardware":1}
,"identifies":{"thermal":1,"temperature":1}
,"manage":{"ment":1,"peak":1,"components":1,"power":1,"cpu":1}
,"ment":{"action":1}
,"action":{"associated":1,"module":1,"trip":1,"balanced":1}
,"associated":{"module":1,"certain":1}
,"tegr":{"chip":1}
,"soctherm.c":{"bpmp":1,"aotag.c":1}
,"aotag.c":{"bpmp":1}
,"nct1008.c":{"kernel":1}
,"tegraxx_throttle.c":{"kernel":1}
,"pwm_fan.c":{"kernel":1}
,"thermal_core.c":{"kernel":1}
,"generic":{"user-space":1}
,"interfaces":{"working":1,"defined":1}
,"working":{"devices":1,"thermal":1}
,"temperatures":{"central":1,"aotag":1,"even":1,"ltage":1,"change":1,"follows":1,"tegra":1}
,"central":{"component":1}
,"component":{"framework":1}
,"zone":{"information":1,"thermal":1,"virtual":1,"tegra-base":1,"using":1,"provides":1,"tegra":1,"following":1,"mon":1,"responsi":1,"trip":1,"uses":1,"based":1,"provided":1,"users":1,"shutdown":1,"hardware":1}
,"<top>\u002Fkernel\u002Fdocumentation\u002Fthermal\u002Fsysfs-api.txt":{"thermal":1}
,"virtual":{"object":1}
,"object":{"represents":1,"following":1}
,"represents":{"area":1}
,"area":{"die":1}
,"die":{"whose":1,"board":1,"near":1,"within":1}
,"monitored":{"controlled":1}
,"controlled":{"essentially":1,"either":1}
,"essentially":{"working":1}
,"sensor":{"acts":1,"cooling":1,"clock":1,"thermal":1,"controlled":1,"abi":1,"sensed":1,"temperature":1,"operate":1,"gated":1,"stopped":1,"counts":1,"hardware":1,"driver":1,"device":1,"exposed":1,"specified":1,"crosses":1,"once":1,"reports":1,"groups":1,"host":1,"power-gat":1,"entering":1,"measuri":1,"tegra":1,"resent":1,"operation":1,"aotag":1,"generate":1,"ideal":1,"soc_therm":1,"gpu":1,"includes":1}
,"acts":{"object":1}
,"components":{"temperature":1,"topic":1,"demonst":1,"consequently":1,"avoid":1}
,"cooling":{"device":1,"actions":1,"trigger":1,"map":1,"devices":1,"active":1,"action":1,"tegra":1,"form":1,"state":1,"throttling":1,"achieved":1,"states":1,"evice":1,"results":1,"strategies":1}
,"trip":{"points":1,"point":1,"allocated":1,"poi":1,"poin":1,"temperature":1}
,"points":{"governor":1,"trip":1,"used":1,"classified":1,"tegra":1,"hardware":1,"perform":1,"thermal":1,"using":1,"notifies":1,"given":1,"sensors":1,"vector":1,"throttle":1,"modified":1}
,"provide":{"interfaces":1,"optimum":1,"best":1,"accurate":1}
,"introduces":{"components":1}
,"demonst":{"rates":1}
,"rates":{"form":1,"stored":1,"tegra":1}
,"form":{"thermal":1,"feedback":1,"fan":1,"orderly":1}
,"tegra-base":{"device":1}
,"configuring":{"thermal":1}
,"tune":{"therma":1}
,"therma":{"response":1}
,"response":{"zone":1}
,"several":{"thermal":1,"types":1,"drivers":1,"softwar":1,"trip":1}
,"zones":{"tuned":1,"mod":1,"platform":1,"provided":1,"guarantee":1,"bpmp":1,"define":1,"ident":1,"allows":1}
,"optimum":{"thermal":1}
,"rformance":{"provided":1,"within":1}
,"provided":{"thermal":1,"tegra":1,"part":1,"using":1,"following":1}
,"mod":{"ified":1}
,"ified":{"editing":1,"thermal":1}
,"editing":{"entries":1}
,"sers":{"define":1}
,"actions":{"limits":1}
,"becomes":{"hot":1,"compelling":1,"unresponsive":1}
,"hot":{"cases":1,"plug":1}
,"cases":{"resolve":1}
,"resolve":{"tuning":1}
,"snippet":{"provides":1}
,"mon":{"itors":1}
,"itors":{"temperature":1}
,"thermal_zone_cpu":{"sensor":1,"cpu_balanced":1,"within":1,"operating":1,"trip":1,"97.5":1,"101.5":1,"100.0":1}
,"cpu-ba":{"lanced":1}
,"lanced":{"cooling":1}
,"passive":{"trip":1,"hysteresis":1,"based":1,"ooling":1,"throttling":1}
,"point":{"trip_bthrot":1,"identifies":1,"cla":1,"tegra_bpmp_thermal":1,"relayed":1,"clock":1,"called":1,"trigger":1,"ows":1,"per":1,"sensors":1,"crosse":1,"management":1,"crossed":1,"55c":1}
,"trip_bthrot":{"crossed":1,"{temperature":1}
,"crossed":{"95.5":1,"example":1}
,"95.5":{"degrees":1,"mcpu-therm":1,"gpu-therm":1}
,"degrees":{"celsius":1}
,"celsius":{"bcpu-therm":1,"191":1,"operation":1,"0.5c":1,"hardware":1,"thermal_zone_cpu":1}
,"bcpu-therm":{"{status":1,"thermal_zone_cpu":1,"101.0":1}
,"{status":{"okay":1}
,"polling-delay":{"-passive":1}
,"-passive":{"=<50":1}
,"=<50":{"thermal-zone-params":1}
,"thermal-zone-params":{"{governor-name":1}
,"{governor-name":{"step_wise":1}
,"step_wise":{"trips":1}
,"trips":{"{trip_critical":1,"thermal":1,"program":1,"owned":1}
,"{trip_critical":{"{temperature":1}
,"{temperature":{"=<101":1,"=<95":1}
,"=<101":{"000>":1}
,"000>":{"type":1}
,"critical":{"hysteresis":1,"triggers":1,"trip":1}
,"hysteresis":{"=<0":1,"=<0>":1,"prevent":1}
,"=<0":{"writable":1}
,"writable":{"trip_bthrot":1,"cooling-maps":1}
,"=<95":{"500>":1}
,"500>":{"type":1}
,"=<0>":{"writable":1}
,"cooling-maps":{"{map0":1}
,"{map0":{"{trip":1}
,"{trip":{"=<&{\u002Fthermal-zones\u002Fbcpu-therm\u002Ftr":1}
,"=<&{\u002Fthermal-zones\u002Fbcpu-therm\u002Ftr":{"ips\u002Ftrip_bthrot}>":1}
,"ips\u002Ftrip_bthrot}>":{"cdev-type":1}
,"cdev-type":{"cpu-balanced":1}
,"cpu-balanced":{"cooling-device":1}
,"cooling-device":{"=<&{\u002Fbthrot_cdev\u002Fcpu_b":1}
,"=<&{\u002Fbthrot_cdev\u002Fcpu_b":{"alanced}":1}
,"alanced}":{"thermal_no_limit":1}
,"thermal_no_limit":{"thermal_no_limit>":1}
,"thermal_no_limit>":{"information":1}
,"<top>\u002Fkernel\u002Fdocumentation\u002Fdevicetree\u002Fbindings\u002Fthe":{"rmal.txt":1}
,"rmal.txt":{"temperature":1}
,"responsi":{"ble":1}
,"milli":{"elsius":1}
,"elsius":{"tegra":1}
,"types":{"temperature":1}
,"sen":{"sors":1}
,"sors":{"spread":1}
,"spread":{"across":1}
,"communicate":{"therm":1,"bpmp":1}
,"therm":{"zone":1}
,"perform":{"thermal":1,"ance":1,"following":1}
,"classified":{"active":1,"passive":1}
,"trigger":{"trip":1,"software":1,"hardware":1}
,"cla":{"ssified":1}
,"ssified":{"critical":1}
,"triggers":{"thermal":1}
,"shutd":{"cooling":1}
,"map":{"specifies":1}
,"specifies":{"cooling":1}
,"certain":{"trip":1,"hardware":1,"amount":1}
,"actu":{"heat":1}
,"makes":{"distinction":1}
,"distinction":{"classifying":1,"aotag":1}
,"classifying":{"fan":1}
,"ooling":{"device":1}
,"feedback":{"control":1}
,"keeps":{"device":1}
,"safe":{"operating":1,"limits":1,"measures":1}
,"operating":{"temperature":1,"frequency":1,"system":1}
,"simple":{"proportional":1}
,"integral":{"deriv":1}
,"deriv":{"ative":1}
,"ative":{"(pid)":1}
,"(pid)":{"controller":1}
,"needs":{"tegra":1}
,"either":{"linux":1}
,"described":{"following":1,"device":1}
,"tab":{"thermal":1}
,"abi":{"name":1}
,"balanced":{"throttle":1,"throttles":1,"cooling":1}
,"throttle":{"temperature":1,"points":1,"settings":1,"temperatures":1,"limit":1,"vectors":1}
,"cpu_balanced":{"95.5":1,"emergency_balanced":1}
,"mcpu-therm":{"thermal_zone_aux":1,"101.0":1}
,"thermal_zone_aux":{"cpu_balanced":1,"within":1,"98.5":1,"101.5":1,"100.0":1}
,"gpu-therm":{"thermal_zone_gpu":1,"gpu":1}
,"thermal_zone_gpu":{"--pll-therm":1,"within":1}
,"--pll-therm":{"thermal_zone_pllx":1}
,"thermal_zone_pllx":{"--ao-therm":1,"b\u002Fw":1}
,"--ao-therm":{"thermal_zone_ao":1}
,"thermal_zone_ao":{"gpu_balanced":1,"near":1,"101.5":1,"100.5":1}
,"gpu_balanced":{"93.5":1,"cpu_balanced":1}
,"93.5":{"tboard_tegra":1}
,"tboard_tegra":{"tmp451":1,"local":1}
,"tmp451":{"--tdiode_tegra":1,"--thermal-fan-est":1,"devices":1}
,"--tdiode_tegra":{"tmp451":1}
,"--thermal-fan-est":{"pwm_fan":1}
,"pwm_fan":{"51.0":1}
,"51.0":{"information":1}
,"aotag":{"versus":1,"thermal":1,"drivers":1,"aotag":1,"thermal_zone_ao":1,"sensor":1,"always-on":1,"capability":1}
,"versus":{"gpu-therm":1}
,"throttles":{"aotag":1}
,"gains":{"achieved":1}
,"achieved":{"tuning":1,"reducing":1}
,"(tdp)":{"system":1}
,"remedy":{"faulty":1}
,"faulty":{"tdp":1}
,"tdp":{"removing":1}
,"ther":{"mal":1}
,"mal":{"zones":1}
,"guarantee":{"maximum":1}
,"maximum":{"performance":1,"llowable":1,"sensors":1}
,"ecause":{"cause":1}
,"irreversible":{"damage":1}
,"damage":{"dev":1,"device":1}
,"and\u002For":{"resets":1}
,"resets":{"thermal":1}
,"mperature":{"sensing":1}
,"nct":{"sensors":1}
,"nct1008":{"nct72":1}
,"nct72":{"tmp451":1}
,"sense":{"temperature":1}
,"ell":{"sensing":1}
,"remote":{"diode":1,"sensor":1}
,"diode":{"tegra":1}
,"platforms":{"sensors":1,"voltage":1}
,"setup":{"follow":1}
,"follow":{"thermal":1}
,"sensed":{"location":1}
,"location":{"tdiode_tegra":1,"aotag":1}
,"tdiode_tegra":{"remote":1,"107":1}
,"near":{"gpu":1}
,"local":{"sensor":1}
,"operate":{"extended":1,"rail":1}
,"extended":{"mode":1}
,"increase":{"temperature":1}
,"191":{"degrees":1}
,"powers":{"sensor":1,"clock":1}
,"gated":{"tegra":1}
,"con":{"sequently":1}
,"sequently":{"sensor":1}
,"stopped":{"tegra":1}
,"turned":{"back":1}
,"back":{"tegra":1,"linux":1,"pllx":1,"55c":1}
,"exits":{"sc7":1}
,"capabilities":{"nct":1,"clocks":1}
,"generate":{"thermal":1,"interrupts":1}
,"correction":{"offset":1}
,"offset":{"nct":1,"temperature":1,"fro":1,"reg":1,"calculated":1,"result":1,"fallbac":1,"compensates":1}
,"allow":{"software":1}
,"program":{"static":1,"bpmp":1,"mable":1}
,"static":{"offset":1,"cpu":1,"gpu":1,"emc":1,"max":1}
,"inaccuracy":{"may":1}
,"reads":{"offset":1}
,"fro":{"device":1}
,"programs":{"offset":1,"hardware":1}
,"reg":{"ister":1}
,"ister":{"boot":1}
,"calculated":{"valida":1}
,"valida":{"ted":1}
,"ted":{"via":1}
,"oil":{"bath":1}
,"bath":{"experiments":1}
,"experiments":{"bpmp":1}
,"soctherm":{"aotag":1,"driver":1}
,"replaced":{"tegra_bpmp_thermal":1}
,"tegra_bpmp_thermal":{"sensor":1,"driver":1}
,"registers":{"itself":1}
,"itself":{"sensor":1}
,"fram":{"ework":1}
,"ework":{"thermal":1}
,"except":{"nct":1}
,"exposed":{"using":1}
,"application":{"binary":1}
,"binary":{"interface":1,"pwm-fan":1,"governor":1,"holds":1}
,"interface":{"(api)":1}
,"(api)":{"given":1}
,"shown":{"table":1}
,"thermal_zone":{"prefix":1}
,"prefix":{"follows":1}
,"allocated":{"used":1}
,"walks":{"list":1}
,"list":{"thermal":1,"trip":1,"current":1}
,"comes":{"trips":1}
,"zon":{"driver":1,"without":1}
,"mess":{"age":1}
,"(mrq)":{"communicate":1}
,"cmd_thermal_query_abi":{"cmd_thermal_get_temp":1}
,"cmd_thermal_get_temp":{"cmd_thermal_set_trip":1}
,"cmd_thermal_set_trip":{"cmd_thermal_get_num_zones":1}
,"cmd_thermal_get_num_zones":{"driver":1,"details":1}
,"receives":{"cmd_thermal_host_trip_reached":1}
,"cmd_thermal_host_trip_reached":{"mrq":1,"trips":1}
,"mrq":{"message":1,"messages":1,"command":1,"requests":1}
,"message":{"particular":1}
,"crosses":{"point":1,"trip":1,"55c":1}
,"relayed":{"back":1}
,"hermal":{"framework":1,"mrq":1}
,"eatures":{"provided":1}
,"part":{"tegra":1,"device":1,"firmware":1}
,"ntrol":{"throttling":1}
,"clocks":{"syst":1,"system":1,"reduce":1,"remedied":1,"frequencies":1,"part":1,"potentially":1,"maintain":1,"handle":1,"using":1,"three":1}
,"syst":{"fan":1}
,"acti":{"cooling":1}
,"pwm-fan":{"provides":1,"cooling":1}
,"programming":{"pwm":1}
,"pwm":{"controlle":1,"values":1}
,"controlle":{"ramp-up":1}
,"ramp-up":{"ramp-down":1}
,"ramp-down":{"control":1}
,"smoothly":{"fan":1}
,"pwm-rpm":{"mapping":1}
,"ramp":{"rates":1}
,"stored":{"part":1,"on-chip":1}
,"values":{"cooling":1,"ensure":1,"result":1}
,"attached":{"monitor":1}
,"monitor":{"temperature":1}
,"nsors":{"temperature":1,"cannot":1}
,"increases":{"governor":1}
,"progressively":{"picks":1}
,"picks":{"deeper":1,"higher":1}
,"deeper":{"cooling":1}
,"rpm":{"fan":1}
,"first":{"line":1}
,"line":{"defense":1}
,"defense":{"delay":1}
,"delay":{"clock":1}
,"arious":{"clocks":1}
,"rising":{"tempera":1}
,"tempera":{"ture":1}
,"ture":{"crosses":1}
,"relies":{"dvfs":1}
,"reduce":{"operating":1}
,"thereby":{"voltage":1}
,"lowered":{"requency":1}
,"requency":{"voltage":1,"caling":1}
,"reduces":{"power":1}
,"helps":{"controlling":1}
,"controlling":{"temperature":1}
,"reducing":{"clock":1}
,"impact":{"perform":1,"similar":1}
,"ance":{"user":1}
,"feels":{"warm":1}
,"warm":{"seems":1}
,"seems":{"sluggish":1}
,"sluggish":{"may":1}
,"due":{"thermal":1,"even":1}
,"thrott":{"ling":1}
,"ling":{"clocks":1}
,"remedied":{"tuning":1}
,"emergency_balanced":{"balanced":1}
,"veral":{"cooling":1}
,"translate":{"maximum":1}
,"llowable":{"operating":1}
,"optimized":{"ovide":1,"limiting":1}
,"ovide":{"best":1}
,"tem":{"perature":1}
,"perature":{"frequency":1,"measurement":1}
,"tables":{"clocks":1}
,"ensor":{"input":1,"fixed":1}
,"input":{"feedback":1,"channel":1}
,"milarly":{"governor":1}
,"output":{"cooling":1,"voltage":1}
,"heats":{"governor":1}
,"progre":{"ssively":1}
,"ssively":{"picks":1}
,"cap":{"clocks":1}
,"potentially":{"higher":1}
,"performs":{"thi":1,"clamp":1}
,"thi":{"thermal":1}
,"maintain":{"junction":1,"output":1,"temperature":1}
,"junction":{"temperature":1}
,"recomm":{"ended":1}
,"ended":{"safe":1}
,"special":{"type":1,"trip":1}
,"ows":{"operating":1}
,"per":{"form":1,"thermal":1,"sensor":1}
,"defines":{"critical":1}
,"users":{"lower":1}
,"lower":{"limit":1,"voltage":1,"performance":1,"bound":1,"boundary":1}
,"strategies":{"failed":1}
,"failed":{"considered":1}
,"considered":{"rare":1}
,"rare":{"ent":1,"transient":1}
,"ent":{"shutdown":1}
,"101.0":{"mcpu-therm":1,"tdiode_tegra":1}
,"107":{"thermal":1}
,"platfor":{"running":1,"minimum":1}
,"host":{"operating":1,"bpmp":1,"continues":1,"therefo":1,"register":1,"various":1,"primary":1,"notified":1,"works":1}
,"(host":{"os)":1}
,"os)":{"cpu":1}
,"hosts":{"soctherm":1,"thermal":1}
,"soc_therm":{"pllx":1,"soc_therm":1,"collection":1,"reports":1,"sens":1,"sensor":1,"proximity":1}
,"pllx":{"thermal_zone_pllx":1,"sensor":1,"oscillator":1,"fallback":1}
,"b\u002Fw":{"gpu":1}
,"ram":{"aux":1}
,"aux":{"(x2)":1}
,"(x2)":{"thermal_zone_aux":1,"thermal_zone_gpu":1}
,"(x4)":{"thermal_zone_cpu":1}
,"collection":{"on-chip":1}
,"on-chip":{"ring":1,"fuses":1}
,"ring":{"oscill":1,"oscillator":1}
,"oscill":{"ators":1}
,"ators":{"frequency":1}
,"changes":{"based":1}
,"convert":{"measured":1}
,"measured":{"frequency":1}
,"oscillating":{"frequency":1}
,"fixed":{"temperature":1}
,"vance":{"stored":1}
,"fuses":{"soctherm":1,"during":1}
,"calibrate":{"sensor":1}
,"complete":{"temperature":1}
,"reports":{"temperature":1,"sensors":1,"accurate":1}
,"egrees":{"celsius":1}
,"0.5c":{"precision":1}
,"precision":{"margin":1}
,"margin":{"sensors":1}
,"groups":{"temperature":1,"based":1,"represented":1}
,"logically":{"grouped":1}
,"grouped":{"sensor":1,"cpu":1}
,"proximi":{"certain":1}
,"blocks":{"sensor":1}
,"represented":{"single":1,"thermal_zone_cpu":1}
,"single":{"sensor":1,"notification":1}
,"four":{"temperature":1}
,"sens":{"ors":1}
,"ors":{"represented":1,"thermal":1}
,"cpus":{"soc_therm":1,"run":1}
,"group":{"takin":1}
,"takin":{"maximum":1}
,"oup":{"thermal":1}
,"event":{"detection":1}
,"detection":{"thermal":1,"just":1}
,"report":{"temperature":1,"thermal":1,"current":1}
,"ses":{"software":1,"back":1}
,"programmed":{"trip":1,"level":1}
,"capable":{"monitoring":1}
,"monitoring":{"several":1,"gpu":1}
,"softwar":{"trip":1}
,"ions":{"report":1}
,"crosse":{"trigger":1}
,"dependencies":{"provide":1}
,"accurate":{"temperature":1,"temperatu":1}
,"senso":{"require":1}
,"minimum":{"voltage":1}
,"cannot":{"operate":1}
,"firmw":{"provides":1}
,"modes":{"operation":1}
,"measurements":{"during":1,"greater":1}
,"powering":{"sensor":1}
,"power-gat":{"during":1}
,"oscillator":{"running":1,"platfor":1,"programmable":1,"added":1,"allows":1,"farther":1,"hat":1,"based":1}
,"therefore":{"frequency-to-temperature":1}
,"frequency-to-temperature":{"conversi":1}
,"conversi":{"may":1}
,"result":{"inaccurate":1,"sensors":1,"fast":1,"damage":1}
,"inaccurate":{"values":1}
,"purious":{"temperature":1}
,"stop":{"sensor":1}
,"measuri":{"temperature":1}
,"ited":{"sensors":1}
,"restarted":{"fallback":1}
,"fallback":{"pllx":1,"program":1,"gpu":1}
,"readings":{"during":1}
,"nimum":{"voltage":1}
,"guaranteed":{"firmware":1}
,"falls":{"back":1}
,"programmable":{"offset":1}
,"invalidate":{"oscillators":1}
,"oscillators":{"llx":1}
,"llx":{"oscillator":1}
,"added":{"offset":1}
,"fallbac":{"pllx":1}
,"continuous":{"tem":1}
,"measurement":{"even":1}
,"even":{"lower":1,"device":1,"throttle":1}
,"side":{"effect":1,"effects":1}
,"effect":{"pllx":1}
,"mable":{"offset":1}
,"compensates":{"fact":1}
,"fact":{"pll":1}
,"pll":{"oscillator":1}
,"farther":{"away":1}
,"away":{"oscillator":1}
,"replacing":{"host":1}
,"continues":{"thermal":1}
,"effects":{"off-setting":1}
,"off-setting":{"ensures":1}
,"temperatu":{"res":1}
,"res":{"pllx":1,"instead":1}
,"therefo":{"continue":1}
,"continue":{"right":1}
,"measuring":{"cpu":1,"tools":1}
,"always-on":{"thermal":1,"power":1}
,"alert":{"generator":1}
,"generator":{"(aotag)":1}
,"(aotag)":{"ring":1}
,"resent":{"always-on":1}
,"domain":{"monit":1}
,"monit":{"temperatures":1}
,"just":{"soc_therm":1}
,"interrupts":{"additionally":1,"due":1}
,"monito":{"two":1}
,"ideal":{"monitoring":1}
,"proximity":{"aotag":1}
,"capability":{"measure":1}
,"ltage":{"levels":1}
,"ident":{"ified":1}
,"modules":{"register":1,"temperatures":1}
,"messages":{"provides":1}
,"poi":{"nts":1}
,"nts":{"per":1}
,"poin":{"host":1}
,"examines":{"list":1}
,"notifies":{"owne":1}
,"owne":{"trip":1,"trips":1}
,"notif":{"ication":1}
,"ication":{"sent":1}
,"sent":{"using":1}
,"callback":{"bpmp":1}
,"owned":{"host":1}
,"primary":{"thermal":1}
,"handled":{"amework":1}
,"amework":{"cmd_thermal_query_abi":1,"sets":1}
,"api":{"doc":1}
,"doc":{"umentation":1}
,"umentation":{"several":1}
,"notifi":{"cation":1}
,"cation":{"generated":1}
,"generated":{"anytime":1}
,"anytime":{"given":1}
,"55c":{"60c":1,"waits":1,"achieve":1}
,"60c":{"65c":1}
,"65c":{"70c":1}
,"70c":{"hermal":1,"additionally":1}
,"sends":{"single":1,"notification":1}
,"notification":{"temperature":1}
,"prevent":{"sending":1}
,"sending":{"notifications":1}
,"notifications":{"above":1,"thermal":1}
,"above":{"example":1,"notifications":1}
,"reache":{"55c":1}
,"waits":{"until":1}
,"drops":{"below":1}
,"54c":{"sends":1}
,"rec":{"eive":1}
,"eive":{"events":1}
,"dropped":{"below":1}
,"element":{"power":1}
,"delivery":{"system":1,"systems":1}
,"imitations":{"battery":1}
,"supplies":{"certain":1}
,"wit":{"hout":1}
,"hout":{"shutting":1}
,"shutting":{"down":1}
,"down":{"regulator":1,"clocks":1,"device":1}
,"efore":{"fails":1}
,"fails":{"maintain":1}
,"inductor":{"switching":1}
,"switching":{"regulator":1}
,"overhea":{"ripple":1}
,"ripple":{"current":1}
,"large":{"limitations":1}
,"limitations":{"result":1}
,"fast":{"transient":1}
,"transient":{"ele":1,"nature":1}
,"ele":{"ctrical":1}
,"ctrical":{"thermal":1}
,"over-current":{"battery":1}
,"droop":{"pmic":1}
,"spikes":{"firmware":1}
,"refers":{"alarms":1}
,"alarms":{"trig":1}
,"trig":{"gers":1}
,"gers":{"hardware":1}
,"handle":{"hese":1,"events":1}
,"hese":{"events":1}
,"similar":{"software":1}
,"throttlin":{"may":1}
,"thes":{"events":1}
,"nature":{"experience":1,"need":1}
,"impacted":{"host":1}
,"notified":{"events":1}
,"detect":{"drop":1}
,"drop":{"clocks":1}
,"perfor":{"mance":1}
,"mance":{"measuring":1}
,"sample":{"cpu":1}
,"unters":{"thermal":1}
,"works":{"maintain":1}
,"clamp":{"down":1}
,"vector":{"configuration":1}
,"holds":{"various":1}
,"thro":{"ttle":1}
,"ttle":{"points":1}
,"govern":{"throttling":1}
,"handles":{"resulting":1}
,"resulting":{"interrupts":1}
,"modified":{"changin":1}
,"changin":{"bpmp":1}
,"97.5":{"heavy":1}
,"heavy":{"thermal_zone_aux":1,"hardware":1,"87.5":1}
,"98.5":{"heavy":1}
,"throttled":{"percentage":1}
,"percentage":{"heavy":1}
,"87.5":{"medium":1}
,"medium":{"lite":1,"heavy)":1}
,"lite":{"throttle":1}
,"vectors":{"optimized":1}
,"limiting":{"peak":1}
,"urrent":{"consumption":1}
,"maximizing":{"performance":1,"jetson":1}
,"pports":{"capping":1}
,"three":{"lev":1}
,"lev":{"els":1}
,"els":{"(lite":1}
,"(lite":{"medium":1}
,"heavy)":{"described":1}
,"bindings":{"capping":1}
,"prevents":{"gpu":1}
,"drawing":{"current":1}
,"volt":{"age":1}
,"supply":{"design":1,"channel":1,"rail":1,"m.2":1}
,"considerations":{"designing":1}
,"designing":{"fail":1,"power":1}
,"fail":{"safe":1}
,"measures":{"power":1}
,"ntegrated":{"circuits":1}
,"circuits":{"(pmic)":1}
,"(pmic)":{"battery":1}
,"controll":{"shut":1}
,"shut":{"down":1}
,"occur":{"results":1}
,"bad":{"user":1}
,"similarly":{"designing":1}
,"livery":{"hardware":1}
,"worst-case":{"loads":1}
,"loads":{"results":1,"additionally":1}
,"rge":{"costly":1}
,"costly":{"components":1}
,"sys":{"tems":1}
,"tems":{"designed":1}
,"systems":{"adequate":1,"actively":1,"thermal":1}
,"adequate":{"common":1}
,"avoid":{"xceeding":1}
,"xceeding":{"design":1}
,"need":{"design":1}
,"mana":{"gement":1}
,"gement":{"system":1}
,"compelling":{"hardware":1}
,"fail-safe":{"firmware":1}
,"har":{"dware":1}
,"dware":{"thermal":1}
,"thermtrip":{"software":1,"temperatures":1}
,"unab":{"control":1}
,"generation":{"system":1}
,"unresponsive":{"tegra":1}
,"stem":{"asserts":1}
,"asserts":{"reset":1}
,"pin":{"pmic":1}
,"hard":{"ware":1}
,"101.5":{"thermal_zone_aux":1,"thermal_zone_ao":1,"following":1}
,"100.0":{"thermal_zone_aux":1,"thermal_zone_ao":1}
,"100.5":{"software-based":1}
,"software-based":{"power":1}
,"modeling":{"jetson":1}
,"3-channel":{"ina3221":1}
,"ina3221":{"power":1,"0x41":1}
,"monitors":{"i2c":1,"read":1}
,"i2c":{"addresses":1,"address":1}
,"addresses":{"0x40":1,"0x4":1}
,"0x40":{"0x41":1,"rail":1}
,"0x41":{"information":1,"sysfs":1,"rail":1,"channel-0":1}
,"sysfs":{"nodes":1,"node":1,"odes":1}
,"naming":{"convention":1}
,"convention":{"sysfs":1}
,"rail_name_<n>":{"exports":1}
,"exports":{"rail":1}
,"in_current":{"<n>_input":1}
,"<n>_input":{"exports":1}
,"in_voltage":{"<n>_input":1}
,"in_power":{"<n>_input":1}
,"<n>":{"channel":1}
,"channel":{"number":1,"vdd_sys_gpu":1,"vdd_sys_soc":1,"vdd_4v0_wifi":1,"connected":1,"vdd_in":1,"vdd_sys_cpu":1,"vdd_sys_ddr":1,"vdd_mux":1,"vdd_5v_io_sys":1,"vdd_3v3_sys":1,"vdd_3v3_io_slp":1,"vdd_1v8_io":1,"vdd_3v3_sys_m2":1}
,"0-2":{"note":1}
,"ina":{"driver":1,"sysfs":1}
,"modify":{"ina":1}
,"modifying":{"values":1}
,"address":{"0x40":1,"0x41":1,"0x42":1,"0x43":1}
,"odes":{"read":1}
,"names":{"voltage":1,"i2c":1}
,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0040\u002Fiio:device0":{"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0041\u002Fiio:device1":1}
,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0041\u002Fiio:device1":{"rail":1}
,"vdd_sys_gpu":{"gpu":1}
,"vdd_sys_soc":{"soc":1}
,"vdd_4v0_wifi":{"wifi":1}
,"wifi":{"power":1}
,"connected":{"rail":1}
,"vdd_in":{"main":1,"voltage":1}
,"vdd_sys_cpu":{"cpu":1}
,"vdd_sys_ddr":{"ddr":1}
,"ddr":{"power":1}
,"developer":{"kit":1}
,"kit":{"carrier":1}
,"carrier":{"board":1}
,"3-c":{"hannel":1}
,"hannel":{"ina3221":1}
,"0x4":{"0x43":1}
,"0x43":{"sysfs":1,"rail":1}
,"vol":{"tage":1}
,"tage":{"current":1}
,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0042\u002Fiio:device2":{"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0043\u002Fiio:device3":1}
,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0043\u002Fiio:device3":{"rail":1}
,"0x42":{"rail":1}
,"vdd_mux":{"carrier":1}
,"vdd_5v_io_sys":{"carrier":1}
,"vdd_3v3_sys":{"carrier":1}
,"3.3":{"supply":1,"sleep":1}
,"vdd_3v3_io_slp":{"carrier":1}
,"vdd_1v8_io":{"(name":1}
,"(name":{"schematic":1}
,"schematic":{"vdd_1v":1}
,"vdd_1v":{"carrier":1}
,"1.8":{"supply":1}
,"vdd_3v3_sys_m2":{"3.3":1}
,"m.2":{"key":1}
,"key":{"connector":1}
,"connector":{"examples":1}
,"examples":{"read":1}
,"channel-0":{"rail":1}
,"vdd_in)":{"execute":1}
,"execute":{"command":1}
,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F0-0041\u002Fiio:devic":{"e1\u002Frail_name_0":1,"e1\u002Fin_current0_input":1,"e1\u002Fin_voltage0_input":1,"e1\u002Fin_power0_input":1}
,"e1\u002Frail_name_0":{"read":1}
,"execut":{"commands":1}
,"commands":{"cat":1,"echo":1}
,"e1\u002Fin_current0_input":{"cat":1}
,"e1\u002Fin_voltage0_input":{"cat":1}
,"e1\u002Fin_power0_input":{"note":1}
,"accuracy":{"assume":1}
,"assume":{"guard":1}
,"guard":{"band":1}
,"band":{"measurements":1}
,"greater":{"200":1}
,"200":{"below":1}
,"ccuracy":{"deviate":1}
,"deviate":{"related":1}
,"section":{"describes":1}
,"echo":{"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fenable":1,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fenable_3d_sc":1,"<cpu_freq>":1,"<cpu_freq":1,"<gpu_freq>":1,"<emc_freq>":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fmrq_rate_locked":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fstat":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux":1}
,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fenable":{"_3d_scaling":1}
,"_3d_scaling":{"able":1}
,"able":{"frequency":1}
,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fenable_3d_sc":{"aling":1}
,"aling":{"setting":1}
,"setting":{"frequencies":1}
,"procedures":{"frequencies":1,"manually":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Fclk_tree":{"print":1}
,"print":{"cpu":1,"gpu":1,"emc":1}
,"bound":{"ary":1}
,"ary":{"upper":1,"current":1,"run":1}
,"upper":{"bound":1,"boundary":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_m":{"in_freq":1}
,"in_freq":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux":{"\u002Fcpufreq\u002Fcpuinfo_max_freq":1,"\u002Fonline":1}
,"\u002Fcpufreq\u002Fcpuinfo_max_freq":{"cat":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_c":{"ur_freq":1}
,"ur_freq":{"change":1}
,"<cpu_freq>":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpu":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":1,"frequency":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpu":{"freq\u002Fscaling_m":1}
,"freq\u002Fscaling_m":{"_freq":1}
,"_freq":{"change":1,"static":1}
,"\u002Fcpufreq":{"\u002Fscaling_min_freq":1,"\u002Fscaling_max_freq":1}
,"\u002Fscaling_min_freq":{"echo":1}
,"<cpu_freq":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":1}
,"\u002Fscaling_max_freq":{"<cpu_freq>":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fscaling_avail":{"able_frequencies":1}
,"able_frequencies":{"cpu":1}
,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevfreq\u002F17000000.g":{"p10b\u002Fmin_freq":1,"p10b\u002Fmax_freq":1,"p10b\u002Fcur_freq":1}
,"p10b\u002Fmin_freq":{"cat":1}
,"p10b\u002Fmax_freq":{"cat":1}
,"p10b\u002Fcur_freq":{"change":1}
,"<gpu_freq>":{"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevf":1,"value":1}
,"\u002Fsys\u002Fdevices\u002F17000000.gp10b\u002Fdevf":{"req\u002F17000000.gp10b\u002Fmax_freq":1,"req\u002F17000000.gp10b\u002Fmin_freq":1}
,"req\u002F17000000.gp10b\u002Fmax_freq":{"change":1,"<gpu_freq>":1}
,"req\u002F17000000.gp10b\u002Fmin_freq":{"static":1,"echo":1}
,"\u002Favailable_frequencies":{"print":1}
,"boundary":{"upper":1,"current":1,"run":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fmin_rate":{"cat":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fmax_rate":{"cat":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Frate":{"change":1}
,"<emc_freq>":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk":1,"frequency":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk":{"\u002Femc\u002Fmax_rate":1,"\u002Femc\u002Fmin_rate":1,"\u002Femc\u002Frate":1}
,"\u002Femc\u002Fmax_rate":{"change":1}
,"\u002Femc\u002Fmin_rate":{"static":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fmrq_rate_locked":{"echo":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc\u002Fstat":{"echo":1}
,"\u002Femc\u002Frate":{"<emc_freq>":1}
,"min":{"_rate_and":1}
,"_rate_and":{"max_rate":1}
,"max_rate":{"maximizing":1}
,"jetson_clocks.sh":{"script":1,"[options":1}
,"script":{"maximize":1,"used":1,"available":1}
,"maximize":{"jetson-tx2":1,"jetson":1}
,"jetson-tx2":{"performance":1}
,"sett":{"ing":1}
,"max":{"frequency":1}
,"show":{"current":1}
,"store":{"current":1}
,"restore":{"clock":1,"previous":1}
,"$home\u002Fjetson_clocks":{".sh":1}
,".sh":{"basic":1}
,"basic":{"usage":1}
,"usage":{"follows":1}
,"[options":{"options":1}
,"--show":{"displays":1,"store":1}
,"displays":{"current":1}
,"--store":{"[file]":1,"maximize":1}
,"[file]":{"stores":1,"restores":1}
,"stores":{"current":1}
,"l4t_dfs.conf":{"--restore":1,"show":1}
,"--restore":{"[file]":1,"using":1}
,"restores":{"saved":1}
,"saved":{"settings":1}
,"${home}\u002Fjetson_clocks.sh":{"--show":1,"--store":1,"restore":1,"--restore":1}
,"previous":{"settings":1}
,"plug":{"manage":1,"following":1}
,"manually":{"turn":1}
,"turn":{"on\u002Foff":1,"slave":1}
,"on\u002Foff":{"slave":1}
,"slave":{"cpus":1,"cpu":1}
,"\u002Fonline":{"run":1,"check":1}
,"check":{"cpu":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fonline":{"cpu":1}
}
;Search.control.loadWordPairs(pairs);
