var pairs =
{
"sensor":{"driver":1,"two":1,"validating":1,"requires":1,"camera":1,"typical":1,"add":1,"device":1,"physical_h":1,"sensor_model":1,"module":1,"crop":1,"river":1,"mode":1,"tsi":1,"programmed":1,"progra":1,"information":1,"iver":1,"output":1,"pixel":1,"data":1,"increased":1,"control":1,"used":1,"connection":1,"remote-endpoint":1,"flags":1,"(imx185.c)":1,"timing":1,"struct":1,"properties":1,"ctrl_handlerr":1,"i2c":1,"update":1,"determine":1,"point":1,"static":1,"create":1,"leave":1,"group":1,"fuse":1,"frame":1,"coarse":1,"special":1,"drivers":1,"timeout":1,"conf":1,"connected":1,"nning":1,"verify":1,"power-on":1,"specification":1,"table":1}
,"driver":{"programming":1,"enable":1,"without":1,"provided":1,"follows":1,"specific":1,"value":1,"expressed":1,"delays":1,"frame":1,"uses":1,"documentation":1,"version":1,"topic":1,"sony":1,"information":1,"call":1,"power_put":1,"refers":1,"v4l2":1,"true":1,"gain":1,"minimum":1,"sponsible":1,"implements":1,"values":1,"nction":1,"development":1,"driver":1,"complete":1,"capture":1,"ing":1,"loaded":1,"accesses":1,"problems":1,"name":1,"kernel":1,"device":1,"static":1,"tables":1}
,"programming":{"guide":1,"paths":1,"table":1}
,"guide":{"implement":1,"release":1}
,"implement":{"ing":1}
,"ing":{"camera":1,"get-control":1,"sensor":1,"v4l2":1,"v4l2-compliance":1}
,"camera":{"sensor":1,"data":1,"programming":1,"application":1,"core":1,"modules":1,"module":1,"board":1,"call":1,"layouts":1,"require":1,"tx1":1,"include":1,"stack":1,"common":1,"drivers":1,"programmed":1,"devices":1,"configuration":1,"plugin":1,"lists":1,"device":1,"availabl":1,"test":1,"driver":1,"devi":1}
,"enable":{"acquisition":1,"dpcm":1,"flag":1,"plugin":1}
,"acquisition":{"camera":1}
,"data":{"csi":1,"sensor":1,"type":1,"multi":1,"sheet":1,"structure":1,"specific":1,"documentation":1,"populated":1,"ransferred":1,"controls":1,"tegra_camera":1,"required":1,"sensor-private":1,"informati":1,"common_data":1,"senso":1,"format":1,"linking":1,"information":1,"above":1,"applied":1,"hrough":1,"provide":1,"macro":1,"sheets":1}
,"csi":{"bus":1,"port":1,"lanes":1}
,"bus":{"native":1,"mode_type":1,"width":1,"info":1}
,"native":{"format":1}
,"format":{"provided":1,"yuv":1,"sensor":1,"(24":1,"adjust":1,"(42":1,"fixed":1,"driver":1,"q42.22":1,"achieved":1,"values":1,"mode":1,"definition":1,"macro":1,"frame":1,"tegra":1,"examine":1,"pairs":1}
,"provided":{"sensor":1,"examples":1}
,"two":{"types":1,"cameras":1,"ports":1,"above":1,"ways":1}
,"types":{"camera":1,"equal":1,"controls":1,"corresponding":1}
,"paths":{"depending":1}
,"depending":{"camera":1,"i2c":1,"sensor":1}
,"application":{"camera":1,"kernel-m":1,"ernel":1,"support":1,"uses":1}
,"core":{"library":1,"user":1,"lib":1,"video":1}
,"library":{"interface":1,"provides":1,"path":1,"=20":1,"note":1,"three":1,"tegra_camera":1,"control":1,"uses":1,"converts":1,"passes":1,"imx185_set_frame_rate":1}
,"interface":{"direct":1,"camera":1,"include":1,"application":1,"interface":1,"communicate":1,"lanes":1,"information":1,"sensor":1,"i2c":1,"however":1,"details":1,"user-space":1}
,"direct":{"v4l2":1,"calls":1}
,"v4l2":{"interface":1,"drivers":1,"driver":1,"sensor":1,"sensor-device":1,"implementation":1,"subdev":1,"kernel":1,"controls":1,"handler":1,"control":1,"sub-device":1,"framework":1,"sub":1,"cid_frame_rate":1,"media":1,"cid_exposure":1,"set-control":1,"open":1,"subdevice":1,"async":1}
,"user":{"mode":1,"ode":1}
,"mode":{"library":1,"v4l2":1,"driver":1,"bypasses":1,"selection":1,"true":1,"type":1,"uses":1,"types":1,"possible":1,"calibrating":1,"table":1,"floor":1,"microseconds":1,"(for":1,"tables":1,"vailable":1,"based":1,"(free":1,"(gated)":1,"sensor":1,"static":1,"res":1,"camera_common":1}
,"provides":{"controls":1,"media":1,"list":1}
,"controls":{"processing":1,"include":1,"sensor":1,"needed":1,"dynamic":1,"controls":1,"linked":1,"initialized":1,"con":1,"defined":1,"require":1,"nless":1,"following":1,"follows":1,"handler":1,"operation":1,"32-bit":1,"mix":1,"deprecated":1,"low":1,"received":1,"fuse_id":1,"calls":1,"get-control":1,"modifying":1,"imx185":1,"binding":1,"details":1,"added":1}
,"processing":{"application":1}
,"kernel-m":{"ode":1}
,"ode":{"v4l2":1,"library":1}
,"drivers":{"typical":1,"follows":1,"application":1,"nvidia":1,"imx185":1}
,"typical":{"usecases":1,"rear":1,"front":1,"device-tree":1}
,"usecases":{"using":1}
,"using":{"camera":1,"auto-calibration":1,"user":1,"hese":1,"plugin":1,"main":1,"main-platform":1}
,"lib":{"ray":1}
,"ray":{"interface":1}
,"include":{"applications":1,"single":1,"camera0":1,"-camera0":1,"uyvy":1,"digital":1,"minimum":1,"regulators":1,"limited":1,"new":1,"jetson-plugin-manager\u002Ftegra210-jetson-cv":1,"<t18x-common-plugin-manager\u002Ftegra186-quil":1,"jetson-platforms":1,"<t18x-common-platforms\u002Ftegra186-quill-cam":1,"statement":1}
,"applications":{"tegra":1,"convert":1,"check":1}
,"tegra":{"isp":1,"architecture":1,"-camera-platform":1,"serial":1,"video":1,"uses":1,"18x":1,"technical":1,"sensor":1}
,"isp":{"functionality":1,"clock":1,"underrun":1,"running":1}
,"functionality":{"applications":1,"sensor-private":1}
,"convert":{"rgb":1,".dtb":1}
,"rgb":{"format":1}
,"yuv":{"ormat":1,"bayer":1}
,"ormat":{"perform":1,"v4l2":1}
,"perform":{"various":1,"additional":1}
,"various":{"post-processing":1,"free":1}
,"post-processing":{"tasks":1}
,"tasks":{"bayer":1}
,"bayer":{"sensors":1,"pixel":1,"pixel_phase":1,"bayer_wdr_pwl":1}
,"sensors":{"linux":1,"ource":1,"decibels":1,"min_hdr_ratio":1,"unit":1,"supporting":1,"true":1}
,"linux":{"tegra":1,"kernel":1,"(v4l2)":1,"tx1":1}
,"architecture":{"framework":1}
,"framework":{"applicati":1,"application":1,"requiring":1,"s_stream":1,"s_ctrl":1,"acts":1,"defining":1,"establishing":1,"media_entity_init":1,"media":1,"elements":1}
,"applicati":{"kernel":1}
,"kernel":{"mode":1,"v4l2":1,"source":1,"uses":1,"driver":1,"format":1,"configuration":1,"follow":1,"devi":1,"boots":1,"enable":1,"development":1,"inds":1,"logs":1}
,"follows":{"android":1,"direct":1,"bringing":1,"tegra-camera-platform":1,"property":1,"imx185_a@1a":1,"min_exp_time":1,"min_framerate":1,"max_framerate":1,"input":1,"num_control_point":1,"function":1,"point":1,"struct":1,"controls":1,"define":1,"control":1,"entry":1,"imx185":1}
,"android":{"architecture":1,"specifies":1,"tx1":1}
,"ernel":{"mode":1}
,"support":{"direct":1,"device":1,"num_control_point*valid":1,"multiple":1,"dtsi":1,"add":1}
,"communicate":{"nvidia":1}
,"nvidia":{"v4l2":1,"tegra-camera-platform":1,"imx185":1,"tegra":1,"kernel":1}
,"without":{"having":1,"pre-processing":1}
,"having":{"camera":1}
,"path":{"capturing":1,"option":1,"\u002Fdev\u002Fvideo0":1}
,"capturing":{"raw":1}
,"raw":{"data":1,"memory":1}
,"validating":{"ensor":1}
,"ensor":{"drivers":1,"focuser":1}
,"uses":{"kernel":1,"keyword":1,"tegra_camera":1,"piece-wise":1,"24.8":1,"42.22":1,"values":1,"cam":1,"plugin":1}
,"bringing":{"bayer":1}
,"pixel":{"format":1,"data":1,"phase":1,"line":1,"clock":1,"binning":1}
,"requires":{"customers":1}
,"customers":{"develop":1}
,"develop":{"evice":1}
,"evice":{"tree":1}
,"tree":{"kernel":1,"camera":1,"locate":1,"tx1":1,"node":1,"-supply":1,"ctrls":1,"of_device_id":1,"static":1,"parser":1,"nod":1,"respective":1,"instantiated":1,"instead":1,"file":1,"entries":1,"dtsi":1,"device":1,"driver":1,"compatible":1,"verify":1,"erify":1,"fields":1,"causing":1,"compiler":1,"pdate":1}
,"examples":{"sony":1}
,"sony":{"imx185":1}
,"imx185":{"sensors":1,"sensor":1,"30-001a":1,"_rear_liimx185":1,"v4l2":1,"reg":1,"post_crop_frame_drop":1,"{struct":1,"_ctrl_ops":1,"standard":1,"_get_frame_length_regs":1,"_get_coarse_time_regs":1,"_get_gain_reg":1,"regmap":1,"_read_reg":1,"_write_reg":1,"_write_table":1,"_power_on":1,"_power_off":1,"_power_put":1,"_power_get":1,"_s_stream":1,"_mode_tbls.h":1,"_subdev_video_ops":1,"_subdev_core_ops":1,"_subdev_ops":1,"_of_match":1,"structure":1,"_common_ops":1,"_s_ctrl":1,"_set_group_hold":1,"_set_gain":1,"_set_frame_length":1,"_set_coarse_time":1,"_set_coarse_time_short":1,"_write_eeprom":1,"_g_volatile_ctrl":1,"_ctrls_init":1,"_parse_dt":1,"_open":1,"_subdev_internal_ops":1,"_media_ops":1,"_probe":1,"sizeof":1,"common_data":1,"_remove":1,"android":1,"_cam0":1,"_a@1a":1,"driver":1,".driver":1,".owner":1,"_reg":1,"_start":1,"_stop":1,"_frmfmt":1,"_mode_#":1}
,"ource":{"code":1}
,"code":{"available":1,"example":1,"snippets":1}
,"available":{"sony":1,"unique":1,"device":1,"hdr":1,"system":1,"open":1,"linuxtv":1}
,"modules":{"device":1,"module":1,"{module0":1,"follows":1,"identical":1,"power":1}
,"device":{"tree":1,"node":1,"nodes":1,"display":1,"imaging":1,"component":1,"oper":1,"ass":1,"slave":1,"datas":1,"properties":1,"follows":1,"identifier":1,"reg":1,"tx1":1,"xxx":1,"information":1,"serial":1,"topology":1,"work":1,"trees":1,"camera_common_parse_ports":1,"whic":1,"represented":1,"behaves":1,"source":1,"sink":1,"shutdown":1,"registration":1,"module":1,"replace":1,"dtsi":1,"updating":1,"using":1,"files":1,"note":1,"path":1,"name":1,"device":1}
,"module":{"installed":1,"includes":1,"may":1,"tabl":1,"contain":1,"note":1,"follows":1,"properties":1,"module":1,"(or":1,"guidelines":1,"second":1,"vendor":1,"example":1,"imx185":1,"ensor":1,"ost_crop_frame_drop":1,"change":1,"one-time":1,"onboard":1,"meet":1,"returned":1,"reboot":1,"works":1}
,"installed":{"target":1,"board":1}
,"target":{"platform":1}
,"platform":{"consist":1,"dtsi":1,"data":1,"device":1}
,"consist":{"devices":1}
,"devices":{"typical":1,"inside":1,"refer":1,"media":1,"focuser":1,"imx185":1,"register":1,"regi":1,"system":1,"chang":1}
,"rear":{"camera":1,"front":1,"facing":1}
,"includes":{"complementary":1}
,"complementary":{"metal-oxide":1}
,"metal-oxide":{"semiconductor":1}
,"semiconductor":{"(cmos)":1}
,"(cmos)":{"sensor":1}
,"front":{"module":1,"third":1,"three-camera":1,"facing":1}
,"may":{"include":1,"occur":1}
,"single":{"cmos":1,"system":1,"camera":1}
,"cmos":{"sensor":1}
,"add":{"camera":1,"test_mode":1,"new":1,"device":1,"override":1,"register":1,"note":1,"array":1}
,"locate":{"create":1,"edit":1}
,"create":{"egra":1,"module":1,"unique":1,"register":1,"nam":1,"new":1}
,"egra":{"-camera-platform":1}
,"-camera-platform":{"device":1}
,"node":{"kernel":1,"create":1,"camera":1,"support":1,"device":1,"contains":1,"note":1,"imx185":1,"v4l2":1,"name":1,"subtype":1,"setup":1,"path":1,"(s)":1,"displayed":1,"file":1,"proper":1}
,"source":{"tree":1,"verify":1,"vi-output":1,"[fmt:srggb12\u002F1920x1080":1,"content":1,"group_hold_prev":1,"control":1,"port":1,"files":1,"projects":1}
,"tx1":{"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft":1,"default":1,"<top>\u002Fkernel\u002Fkernel-4.4\u002Farch\u002Farm64\u002Fconfigs\u002Ftegra21":1,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002F:q":1,"include":1,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft210":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft":{"210":1,"210\u002Fjetson":1}
,"210":{"\u002Fjetson":1,"-jetson":1,"-jetson-cv":1}
,"\u002Fjetson":{"\u002Fkernel-dts\u002Fjetson-platforms\u002Ftegra210-camera-imx185":1,"\u002Fkernel-dts\u002Fjetson":1,"\u002Fkernel-dts\u002Fjetson-plugin-manager\u002Ftegra210-jetson-cv":1,"\u002Fkernel-dts\u002Ftegra":1}
,"\u002Fkernel-dts\u002Fjetson-platforms\u002Ftegra210-camera-imx185":{"-a00.dtsi":1}
,"-a00.dtsi":{"tx2":1,"<top>":1}
,"tx2":{"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fcommon\u002Fkernel-dts\u002Ft1":1,"default":1,"<top>\u002Fkernel\u002Fkernel-4.4\u002Farch\u002Farm64\u002Fconfigs\u002Ftegra18":1,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fquill\u002Fkernel-dts\u002Fteg":1,"include":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fcommon\u002Fkernel-dts\u002Ft1":{"8x-common-modules":1,"8x-common-platforms\u002Ftegra186-quill-camera-modules":1,"8x-common-plugin-manager\u002Ftegra186-quill-camera":1}
,"8x-common-modules":{"\u002Ftegra186-camera-li-mipi-adpt":1}
,"\u002Ftegra186-camera-li-mipi-adpt":{"-a00.dtsi":1}
,"<top>":{"directory":1}
,"directory":{"installed":1}
,"board":{"pport":1,"(camera_board_id":1,"found":1}
,"pport":{"package":1}
,"package":{"tegra":1}
,"tabl":{"(modules)":1}
,"(modules)":{"modules":1}
,"contain":{"basic":1,"appropriate":1}
,"basic":{"information":1}
,"information":{"definition":1,"module":1,"positions":1,"added":1,"refer":1,"0-based":1,"port":1,"consult":1,"------------------------driver":1,"v4l2":1,"setting":1,"configuration":1,"device":1,"used":1,"macro":1,"entity":1,"kernel":1,"system":1,"runtime":1,"fragment-imx185":1,"tx1":1,"main":1,"synchronizing":1,"sensor-private":1}
,"definition":{"devices":1,"genera":1}
,"inside":{"tha":1,"camera":1}
,"tha":{"module":1}
,"note":{"value":1,"except":1,"additional":1,"either":1,"read-only":1,"non-volatile":1,"tegra210-jetson-cv-camera-modules.dtsi":1,"separate":1}
,"value":{"fields":1,"badge":1,"field":1,"compatible":1,"received":1,"driver":1,"modex":1,"ths-s":1,"attempts":1,"equal":1,"larger":1,"calculated":1,"inherent_gain":1,"min_gain_val":1,"follows":1,"x-coordinate":1,"y-coordinate":1,"control":1,"power":1,"reg_map":1,"reg_bits":1,"likely":1,"lower":1,"upper":1,".step":1,"determine":1,"user":1,"<<22":1,"defined":1,"divided":1,"fixed_point_scaling_factor":1,"stored":1,"read-onl":1,"according":1,"following":1,"num_lanes":1,"mclk_multiplier":1}
,"fields":{"camera-related":1,"match":1}
,"camera-related":{"device":1}
,"nodes":{"string":1,"typical":1,"value":1,"stri":1,"disabled":1,"made":1}
,"string":{"data":1,"identifies":1,"max_hdr_ratio":1}
,"type":{"except":1,"example":1,"possible":1,"=bayer_wdr_pwl":1,"v4l2":1,"node":1,"priv->":1}
,"except":{"files":1,"devices":1}
,"files":{"refer":1,"exa":1,"property-value":1,"informa":1,"mor":1,"locate":1}
,"refer":{"device":1,"imx185":1,"sensor":1}
,"device-tree":{"node":1,"values":1}
,"tegra-camera-platform":{"{compatible":1,"modules":1}
,"{compatible":{"nvidia":1}
,"{module0":{"{badge":1}
,"{badge":{"imx185_bottom_liimx185":1}
,"imx185_bottom_liimx185":{"position":1}
,"position":{"bottom":1,"modul":1,"amera-facing":1}
,"bottom":{"orientation":1,"top":1}
,"orientation":{"drivernode0":1,"index":1,"sensor":1,"based":1,"camera":1}
,"drivernode0":{"{pcl_id":1}
,"{pcl_id":{"v4l2_sensor":1}
,"v4l2_sensor":{"devname":1}
,"devname":{"imx185":1}
,"30-001a":{"proc-device-tree":1,"[enabled]":1,"pad":1}
,"proc-device-tree":{"=\u0022\u002Fproc\u002Fdevice-t":1}
,"=\u0022\u002Fproc\u002Fdevice-t":{"ree\u002Fi2c@3180000\u002Ftca9546@70\u002Fi2c@0\u002Fimx185_a@1a":1}
,"ree\u002Fi2c@3180000\u002Ftca9546@70\u002Fi2c@0\u002Fimx185_a@1a":{"module":1}
,"properties":{"information":1,"device":1,"table":1,"specified":1,"mode_type":1,"follows":1}
,"(or":{"modulex":1}
,"modulex":{"modules":1}
,"property":{"value":1,"first":1,"deprecated":1,"program":1}
,"badge":{"unique":1}
,"unique":{"name":1,"identifier":1,"index":1}
,"name":{"identifies":1,"module":1,"device":1,"input":1,"defined":1,"regulator":1,"sensor":1,"suffix":1,"\u002Fdev\u002Fv4l-subdev0":1,"\u002Fdev\u002Fv4l-subdev1":1,"\u002Fdev\u002Fvideo0":1,"control":1,"pointer":1,"list":1,"hange":1,"match":1,"example":1}
,"identifies":{"module":1,"node":1}
,"guidelines":{"naming":1}
,"naming":{"three":1}
,"three":{"parts":1,"types":1,"value":1}
,"parts":{"badge_info":1}
,"badge_info":{"property":1}
,"first":{"part":1,"acquire":1,"divide":1,"unregister":1,"value":1}
,"part":{"camera":1,"contains":1,"number":1,"name":1}
,"(camera_board_id":{"module":1}
,"second":{"part":1,"(fps)":1}
,"contains":{"position":1,"last":1,"name":1,"private":1,"power-on":1,"power-off":1,"switch":1,"correct":1,"resolutions":1}
,"modul":{"example":1}
,"example":{"rear":1,"device-tree":1,"piece-wise":1,"lists":1,"equations":1,"static":1}
,"third":{"part":1}
,"last":{"six":1,"field":1,"avoid":1}
,"six":{"characters":1}
,"characters":{"part":1}
,"number":{"find":1,"available":1,"cameras":1,"frames":1,"lane":1,"control":1,"csi":1,"v4l2":1,"bits":1,"video":1}
,"find":{"datashee":1}
,"datashee":{"module":1}
,"vendor":{"part":1,"register":1}
,"identifier":{"system":1,"linux":1}
,"system":{"multiple":1,"two-camera":1,"rear":1,"bottom":1,"bottomleft":1,"kernel":1,"image":1,"prerequisites":1,"program":1,"driver":1}
,"multiple":{"modules":1,"pads":1,"camera":1,"cameras":1}
,"identical":{"create":1}
,"facing":{"camera":1,"front":1,"additional":1}
,"call":{"rear":1,"initialize":1,"power_get":1,"desired":1,"placeholder":1,"device":1}
,"_rear_liimx185":{"position":1}
,"amera-facing":{"information":1}
,"positions":{"supported":1}
,"supported":{"depends":1,"sensor":1,"camer":1}
,"depends":{"number":1}
,"cameras":{"system":1,"typically":1,"number":1}
,"two-camera":{"system":1}
,"three-camera":{"system":1}
,"top":{"center":1}
,"center":{"six-camera":1}
,"six-camera":{"system":1}
,"bottomleft":{"bottomright":1}
,"bottomright":{"centerleft":1}
,"centerleft":{"centerright":1}
,"centerright":{"topleft":1}
,"topleft":{"topright":1}
,"topright":{"orientation":1}
,"index":{"based":1,"individual":1,"orts":1,"tegra_camera":1,"camera":1}
,"based":{"orientation":1,"following":1,"ompression":1,"compression":1,"input":1,"video":1,"index":1}
,"display":{"two":1}
,"typically":{"hese":1,"problems":1}
,"hese":{"indices":1,"controls":1}
,"indices":{"used":1}
,"used":{"rear":1,"piece-wise":1,"compress":1,"example":1,"access":1,"media":1,"user-mode":1,"on\u002Foff":1,"define":1,"val":1,"call":1,"control":1,"create":1,"device":1,"test_mode":1}
,"additional":{"camera":1,"controls":1,"control-handling":1,"components":1}
,"layouts":{"camera":1}
,"require":{"unique":1,"change":1,"debugging":1}
,"individual":{"imaging":1}
,"imaging":{"device":1}
,"component":{"inside":1}
,"focuser":{"flash":1}
,"flash":{"required":1,"field":1}
,"required":{"information":1,"hardwa":1,"bus-width":1,"sensor":1,"v4l2":1,"camera":1,"tes":1,"table":1}
,"added":{"device-tree":1,"*\u002F{.ops":1,"control":1}
,"oper":{"ation":1}
,"ation":{"device-tree":1,"information":1}
,"ass":{"ign":1}
,"ign":{"device":1}
,"slave":{"address":1}
,"address":{"device":1,"available":1,"mclk":1,"formats":1}
,"datas":{"heet":1}
,"heet":{"compatible":1}
,"compatible":{"string":1,"specifies":1,"field":1,"nvidia":1}
,"field":{"camera-related":1,"regulator":1,"required":1,"configuring":1,"device":1,"imx185":1,"devi":1}
,"stri":{"data":1}
,"imx185_a@1a":{"{compatible":1}
,"reg":{"=<0x1a>":1,"specifies":1,"ister":1}
,"=<0x1a>":{"devnode":1}
,"devnode":{"video0":1}
,"video0":{"physical_w":1}
,"physical_w":{"15.0":1,"specifies":1}
,"15.0":{"physical_h":1}
,"physical_h":{"12.5":1,"specifies":1}
,"12.5":{"sensor_model":1}
,"sensor_model":{"imx185":1,"*specifies":1}
,"post_crop_frame_drop":{"use_decibel_gain":1}
,"use_decibel_gain":{"true":1,"*use":1}
,"true":{"delayed_gain":1,"use_sensor_mode_id":1,"mode0":1,"analog":1,"user":1,"false":1,"dynamic":1,"default":1}
,"delayed_gain":{"true":1}
,"use_sensor_mode_id":{"true":1}
,"mode0":{"{mclk_khz":1}
,"{mclk_khz":{"37125":1}
,"37125":{"num_lanes":1}
,"num_lanes":{"tegra_sinterface":1,"specifies":1,"depending":1}
,"tegra_sinterface":{"serial_a":1,"specifies":1,"setting":1}
,"serial_a":{"discontinuous_clk":1}
,"discontinuous_clk":{"dpcm_enable":1,"specifies":1,"setting":1}
,"dpcm_enable":{"false":1,"specifies":1}
,"false":{"cil_settletime":1,"information":1,"active_h":1,"tegra_camera":1}
,"cil_settletime":{"dynamic_pixel_bit_depth":1,"specifies":1}
,"dynamic_pixel_bit_depth":{"csi_pixel_bit_depth":1,"control":1}
,"csi_pixel_bit_depth":{"mode_type":1,"pixel_phase":1,"specifies":1,"dynamic_pixel_bit_depth":1}
,"mode_type":{"bayer":1,"csi_pixel_bit_depth":1,"specifies":1,"=bayer_wdr_pwl":1}
,"pixel_phase":{"rggb":1,"mode_type":1}
,"rggb":{"active_w":1,"bggr":1}
,"active_w":{"1920":1,"specifies":1,"mclk_multiplier":1}
,"1920":{"active_h":1}
,"active_h":{"1080":1,"specifies":1}
,"1080":{"readout_orientation":1,"imx185_mode_1920x1080_crop_30fps":1}
,"readout_orientation":{"line_length":1,"applies":1}
,"line_length":{"2200":1,"specifies":1}
,"2200":{"inherent_gain":1}
,"inherent_gain":{"mclk_multiplier":1,"specifies":1}
,"mclk_multiplier":{"pix_clk_hz":1,"parameter":1,"specifies":1,"=desired":1,"equal":1}
,"pix_clk_hz":{"74250000":1,"specifies":1,"\u002Fmclk":1}
,"74250000":{"min_gain_val":1}
,"min_gain_val":{"\u002F*db":1,"specifies":1}
,"\u002F*db":{"*\u002Fmax_gain_val":1,"*\u002Fmin_hdr_ratio":1}
,"*\u002Fmax_gain_val":{"\u002F*db":1}
,"*\u002Fmin_hdr_ratio":{"max_hdr_ratio":1}
,"max_hdr_ratio":{"min_framerate":1,"specifies":1}
,"min_framerate":{"1.5":1,"=pix_clk_hz":1}
,"1.5":{"max_framerate":1}
,"max_framerate":{"min_exp_time":1,"=pix_clk_hz":1}
,"min_exp_time":{"max_exp_time":1,"specifies":1,"=(minimum":1,"=(m":1}
,"max_exp_time":{"660000":1,"specifies":1}
,"660000":{"embedded_metadata_height":1}
,"embedded_metadata_height":{"ports":1,"specifies":1}
,"ports":{"address-cells":1,"binding":1}
,"address-cells":{"=<1>":1}
,"=<1>":{"size-cells":1,"ports":1,"address-cells":1,"liimx185":1}
,"size-cells":{"=<0>":1}
,"=<0>":{"port@0":1,"liimx185_imx185_out0":1,"bus-width":1,"liimx185":1,"channel@0":1,"ports":1}
,"port@0":{"{reg":1}
,"{reg":{"=<0>":1,"=<1>":1}
,"liimx185_imx185_out0":{"endpoint":1}
,"endpoint":{"{csi-port":1}
,"{csi-port":{"=<0>":1,"=<2>":1,"=<0":1}
,"bus-width":{"=<4>":1,"=<2>":1,"=<4":1,"defines":1}
,"=<4>":{"remote-endpoint":1}
,"remote-endpoint":{"=<&liimx185_csi_in0>":1,"=<&liimx185":1,"=<&liimx185_imx185":1,"defines":1}
,"=<&liimx185_csi_in0>":{"device":1}
,"sensor-device":{"define":1,"instance":1}
,"define":{"required":1,"states":1,"fixed_point_scaling_factor":1}
,"hardwa":{"resource":1}
,"resource":{"device":1}
,"specifies":{"device":1,"i2c":1,"name":1,"general-purpose":1,"regulator":1,"physical":1,"sensor-mode":1,"standard":1,"number":1,"base":1,"indication":1,"value":1,"whether":1,"height":1,"width":1,"sensor":1,"bit":1,"readout":1,"pixel":1,"multiplier":1,"gain":1,"minimum":1,"maximum":1,"extra":1,"x-coordinate":1,"y-coordinate":1,"mediapad":1,"pre-processed":1,"unprocessed":1,"tegra":1}
,"keyword":{"bind":1}
,"bind":{"vice":1,"device":1}
,"vice":{"driver":1,"tree":1}
,"specific":{"device":1,"sensor":1,"camera":1}
,"i2c":{"slave":1,"client":1,"read":1,"interface":1,"register":1,"check":1,"access":1,"errors":1,"error":1}
,"mclk":{"specifies":1,"clk_out_3":1,"extperiph1":1,"timing":1,"pwdn-gpios":1}
,"input":{"clock":1,"signal":1,"device":1,"lue":1,"bit":1,"parameters":1,"tegra_camera":1,"topic":1}
,"clock":{"device":1,"gpio":1,"unit":1,"mipi":1,"lane":1,"frequency":1,"calculating":1,"(mclk":1,"names":1,"mode":1}
,"default":{"mclk":1,"gpio":1,"alse":1,"mode":1,"false":1,"value":1,"using":1,"sensor":1,"change":1,"data":1,"values":1,"ust":1,"macros":1}
,"clk_out_3":{"tx2":1}
,"extperiph1":{"xxx-gpio":1}
,"xxx-gpio":{"specifies":1}
,"general-purpose":{"input\u002Foutput":1}
,"input\u002Foutput":{"(gpio)":1}
,"(gpio)":{"pins":1}
,"pins":{"device":1,"camera":1,"imx185":1}
,"xxx":{"gpio":1,"act":1,"regula":1}
,"gpio":{"pin":1,"pins":1,"regulator":1,"numctrls":1,"numbers":1,"timing":1}
,"pin":{"camera":1}
,"camera0":{"reset":1,"power":1}
,"reset":{"camera0":1,"camera1":1,"-camera0":1,"-camera1":1}
,"power":{"down":1,"dynamic_pixel_width_depth":1,"csi_pixel_width_depth":1,"int":1,"holds":1,"controls":1,"functions":1,"=&priv->":1,"\u002F\u002Fsensor-private":1,"clock":1}
,"down":{"camera1":1,"tx2":1,"-camera1":1,"xxx-supply":1,"device":1}
,"camera1":{"reset":1,"power":1}
,"-camera0":{"reset":1,"power":1}
,"-camera1":{"reset":1,"power":1}
,"xxx-supply":{"specifies":1}
,"regulator":{"device":1,"name":1,"xxx":1,"properties":1,"setup":1,"names":1}
,"act":{"ual":1}
,"ual":{"regulator":1}
,"defined":{"somewhere":1,"regulators":1,"imx185":1,"\u002F\u002Fcamera_common.h":1,"follows":1,"ctrl_config_list":1}
,"somewhere":{"else":1}
,"else":{"evice":1}
,"-supply":{"suffix":1}
,"suffix":{"mandatory":1,"-reg":1}
,"mandatory":{"following":1,"property-value":1}
,"following":{"defined":1,"conversion":1,"equation":1,"media":1,"code":1,"three":1,"functions":1,"file":1,"line":1,"device":1,"settings":1,"{imx185":1}
,"regulators":{"vana-supply":1,"avdd-reg":1,"clks":1,"gpio_set_value":1,"imx185":1,"driver":1,"prior":1,"drive":1}
,"vana-supply":{"=<&en_vdd_cam_hv_2v8>":1}
,"=<&en_vdd_cam_hv_2v8>":{"\u002F\u002Fanalog":1}
,"\u002F\u002Fanalog":{"2.8v":1}
,"2.8v":{"vdig-supply":1,"vcm":1}
,"vdig-supply":{"=<&en-vdd-cam_1v2>":1}
,"=<&en-vdd-cam_1v2>":{"\u002F\u002Fdigital":1}
,"\u002F\u002Fdigital":{"1.2v":1}
,"1.2v":{"vif-supply":1}
,"vif-supply":{"=<&en-vdd-cam>":1}
,"=<&en-vdd-cam>":{"\u002F\u002Finterface":1}
,"\u002F\u002Finterface":{"1.8v":1}
,"1.8v":{"vvcm-supply":1}
,"vvcm-supply":{"=<&en_vdd_vcm_2v8>":1}
,"=<&en_vdd_vcm_2v8>":{"\u002F\u002Fanalog":1}
,"vcm":{"xxx-reg":1}
,"xxx-reg":{"specifies":1}
,"regula":{"tor":1}
,"tor":{"name":1}
,"-reg":{"following":1}
,"avdd-reg":{"vana":1,"dvdd-reg":1}
,"vana":{"dvdd-reg":1}
,"dvdd-reg":{"vdig":1,"iovdd-reg":1}
,"vdig":{"iovdd-reg":1}
,"iovdd-reg":{"vif":1,"details":1}
,"vif":{"vcmvdd-reg":1}
,"vcmvdd-reg":{"vvcm":1}
,"vvcm":{"physical_w":1}
,"physical":{"width":1,"height":1}
,"width":{"(in":1,"pixel-active":1,"horizontal":1,"identifying":1}
,"(in":{"limeters)":1}
,"limeters)":{"sensor":1}
,"height":{"(in":1,"pixel-active":1}
,"*specifies":{"sensor":1,"number":1}
,"ost_crop_frame_drop":{"*specifies":1}
,"frames":{"dropped":1,"per":1}
,"dropped":{"app":1}
,"app":{"lying":1}
,"lying":{"sensor":1}
,"crop":{"settings":1}
,"settings":{"information":1,"sensor":1,"unit":1,"kernel":1,"fro":1,"method":1,"correct":1,"device":1,"value":1}
,"river":{"documentation":1,"without":1}
,"documentation":{"use_decibel_gain":1,"delayed_gain*used":1,"user_sensor_mode_id*when":1,"*optional":1,"csi_pixel_bit_depth":1,"dynamic_pixel_bit_depth*specifies":1,"pixel_phase*specifies":1,"readout_orientation":1,"control_point_x_[0":1,"camer":1,"match":1}
,"*use":{"option":1}
,"option":{"sensors":1,"single":1}
,"decibels":{"epresent":1,"(db)":1}
,"epresent":{"analog":1}
,"analog":{"gain":1}
,"gain":{"true":1,"value":1,"setting":1,"obtained":1,"limit":1,"min_exp_time":1,"coarse":1,"\u002F\u002Fstring":1,"settings":1,"control":1,"exposure":1,"values":1,"ran":1,"formula":1}
,"received":{"driver":1,"control":1}
,"expressed":{"decibels":1}
,"(db)":{"based":1}
,"conversion":{"mode":1}
,"=20":{"*log":1}
,"*log":{"(analog":1}
,"(analog":{"gain)":1}
,"gain)":{"information":1,"max_gain_val":1}
,"delayed_gain*used":{"delay":1}
,"delay":{"gain":1}
,"setting":{"true":1,"integer":1,"control":1,"sub":1,"takes":1,"v4l2":1,"common":1,"proper":1,"specifies":1}
,"delays":{"sending":1}
,"sending":{"updated":1}
,"updated":{"value":1,"achieved":1,"appropriately":1}
,"frame":{"default":1,"rate":1,"length)":1,"disable":1,"length":1,"ength":1,"format":1}
,"alse":{"information":1}
,"user_sensor_mode_id*when":{"true":1}
,"tegra_camera":{"_cid_sensor_mode_id":1,"_cid_gain":1,"_cid_frame_length":1,"_cid_coarse_time":1,"_cid_exposure":1,"_cid_coarse_time_short*updates":1,"_cid_group_hold*provides":1,"_cid_hdr_enable*toggles":1,"_cid_otp_data*reads":1,"_cid_fuse_id*reads":1,"_cid_sensor_mode_id*used":1,"_cid_vi_bypass_mode**used":1,"_cid_override_enable**used":1,"_cid_frame_rate":1,"_cid_eeprom_data":1,"_cid_hdr_en":1}
,"_cid_sensor_mode_id":{"control":1}
,"control":{"select":1,"points":1,"point":1,"default":1,"macro":1,"init":1,"handler":1,"frame_length":1,"handlers":1,"setting":1,"ops":1,".type":1,".flags":1,"value":1,"used":1,"registers":1,"imx185":1,"[1]":1,"[2]":1,"[0]":1,"top-level":1,"set-control":1,"tegra_camera":1,"gain":1,"per-frame":1,"input":1,"exposure":1,"values":1,"switch":1,"control":1,"reg":1,"initialization":1,"new":1,"configuration":1,"-register":1,"create":1}
,"select":{"specific":1}
,"bypasses":{"default":1}
,"selection":{"logic":1}
,"logic":{"default":1}
,"*optional":{"properties":1,"**provided":1}
,"table":{"specified":1,"please":1,"sensor":1,"patt":1,"camera":1,"*optional":1,"data":1,"separate":1,"color":1,"required":1,"pointers":1,"sets":1,"obtain":1,"add":1,"format":1,"place":1,"array":1}
,"specified":{"different":1,"platform":1,"sensor":1}
,"different":{"dtsi":1,"readout":1,"esults":1}
,"dtsi":{"files":1,"file":1,"proper":1,"camera":1,"add":1,"remove":1}
,"exa":{"mple":1}
,"mple":{"clock":1}
,"file":{"rest":1,"details":1,"exposure":1,"*see":1,"plugin":1,"camera":1,"status":1,"register":1,"include":1,"ecause":1,"prerequisites":1,"tx1":1,"eplace":1,"new":1,"change":1,"i\u002Fo":1,"back":1,"called":1}
,"rest":{"properties":1}
,"tsi":{"files":1}
,"property-value":{"pairs":1}
,"pairs":{"mandatory":1,"apply":1,"media":1,"mode":1,"according":1,"*\u002F}":1}
,"apply":{"sensor":1}
,"implementation":{"follows":1,"consult":1}
,"modex":{"specifies":1}
,"sensor-mode":{"information":1}
,"0-based":{"index":1}
,"orts":{"provides":1}
,"media":{"controller":1,"pad":1,"device":1,"entity":1,"contr":1,"links":1,"operations":1,"ent":1,"enti":1}
,"controller":{"graph":1,"api":1,"initialization":1,"framew":1,"setup":1,"v4l2":1,"usage)":1,"imager":1,"framework":1,"pad":1}
,"graph":{"binding":1}
,"binding":{"inform":1,"mclk_khz":1,"{num-channels":1,"properties":1,"connec":1,"two":1,"expects":1,"parsing":1,"\u002F\u002Flink":1}
,"inform":{"ation":1}
,"port":{"binding":1,"specifies":1,"connection":1,"sensor":1,"sink":1,"bin":1,"information":1,"imager":1,"whi":1,"bind":1,"represented":1}
,"mclk_khz":{"specifies":1}
,"standard":{"mipi":1,"ones":1}
,"mipi":{"driving":1,"lanes":1,"lane":1,"alliance":1}
,"driving":{"clock":1}
,"unit":{"khz":1,"interval":1,"lines":1,"ratios":1,"fps":1,"econds":1,"seconds":1,"device":1}
,"khz":{"num_lanes":1}
,"lane":{"channels":1,"value":1,"consult":1}
,"channels":{"sensor":1}
,"programmed":{"output":1,"plugin":1}
,"output":{"tegra_sinterface":1,"csi":1,"piece-wise":1,"iece":1,"signal":1,"returned":1}
,"base":{"tegra":1}
,"serial":{"interface":1,"bus":1}
,"lanes":{"connected":1,"cil_settletime":1}
,"connected":{"discontinuous_clk":1,"sensor":1}
,"indication":{"sensor":1}
,"progra":{"mmed":1}
,"mmed":{"discontinuous":1}
,"discontinuous":{"clock":1}
,"ths-s":{"ettle":1}
,"ettle":{"time":1}
,"time":{"mipi":1,"limit":1,"minimum":1,"maximum":1,"registers":1,"register":1,"driver":1,"settings":1,"follows":1}
,"attempts":{"auto-calibrate":1}
,"auto-calibrate":{"according":1}
,"according":{"mclk_multiplier":1,"specification":1,"sensor-related":1,"mode":1,"gain":1,"register":1}
,"parameter":{"using":1,"values":1}
,"auto-calibration":{"cal":1}
,"cal":{"culate":1}
,"culate":{"values":1}
,"values":{"formula":1,"clude":1,"include":1,"180":1,"control":1,"required":1,"reg_bits":1,"list":1,"gain":1,"register":1,"user":1,"program":1,"river":1,"frame":1,"q42":1,"lower":1,"workaround":1,"caution":1,"documentation":1,"\u002F\u002Flink":1,"common":1,"camera":1,"match":1,"assigned":1,"correctly":1,"linked":1,"mode":1,"probing":1,"correct":1,"separate":1,"end":1}
,"formula":{"85n":1,"data":1}
,"85n":{"6*ui":1}
,"6*ui":{"<(cli_settletime":1}
,"<(cli_settletime":{"<145ns":1}
,"<145ns":{"10*ui":1}
,"10*ui":{"unit":1}
,"interval":{"equal":1}
,"equal":{"duration":1,"csi_pixel":1,"larger":1}
,"duration":{"state":1}
,"state":{"clock":1,"group":1,"group_hold_en":1,"erify":1}
,"consult":{"mipi":1,"imx185":1,"https:\u002F\u002Flinuxtv.org\u002Fdownloads\u002Fv4l-dvb-apis\u002Fmacro":1}
,"alliance":{"specification":1}
,"specification":{"d-phy":1,"sheets":1,"mode":1}
,"d-phy":{"details":1}
,"details":{"dpcm_enable":1,"mode":1,"section":1,"modifying":1,"device":1,"\u002F\u002Ffreeing":1,"raw":1,"power":1}
,"whether":{"enable":1}
,"dpcm":{"compression":1}
,"compression":{"mode":1,"applied":1,"function":1}
,"pixel-active":{"region":1}
,"region":{"active_w":1,"pixel_t":1}
,"pixel_t":{"deprecated":1,"wdr":1}
,"deprecated":{"property":1,"replaced":1,"controls":1}
,"replaced":{"thes":1}
,"thes":{"properties":1}
,"possible":{"values":1}
,"clude":{"yuv":1}
,"bayer_wdr_pwl":{"-wide":1}
,"-wide":{"dynamic":1}
,"dynamic":{"range":1,"arra":1}
,"range":{"mode":1,"signal":1}
,"piece-wise":{"linear":1}
,"linear":{"function":1,"compression":1}
,"function":{"compress":1,"based":1,"integer":1,"used":1,"value":1,"example":1,"follows":1,"description":1,"pointers":1,"interfaces":1,"according":1,"regulator_get":1,"first":1,"release":1,"mainly":1,"mode":1,"sensor":1,"two":1,"controls":1,"imx185.c":1,"contains":1,"iterates":1,"necessary":1,"parses":1,"eration":1,"entry":1,"initializes":1,"calls":1,"links":1,"removes":1,"makes":1,"matches":1,"calculating":1,"verify":1}
,"compress":{"multi":1}
,"multi":{"exposure":1}
,"exposure":{"fused":1,"fusion":1,"frame":1,"time":1,"intervals":1,"settings":1,"control":1,"updated":1,"sensor":1,"values":1}
,"fused":{"pixel":1,"output":1}
,"fusion":{"performe":1,"performed":1}
,"performe":{"sensor":1}
,"iver":{"documentation":1,"follows":1}
,"bit":{"depth":1,"dep":1,"bit":1,"input":1,"(deprecated)":1,"tegra_camera":1,"integer":1,"fract":1,"value":1,"value*":1}
,"depth":{"final":1,"multi":1,"output":1,"csi_pixel_bit_depth":1}
,"final":{"sensor":1}
,"=bayer_wdr_pwl":{"represents":1,"specifies":1}
,"represents":{"bit":1,"device":1}
,"dep":{"output":1}
,"ompression":{"applied":1}
,"applied":{"information":1,"spec":1}
,"dynamic_pixel_bit_depth*specifies":{"true":1}
,"signal":{"non":1,"16-bit":1,"12-bit":1}
,"non":{"wdr":1}
,"wdr":{"mode":1,"sensor":1}
,"csi_pixel":{"_bit_depth":1}
,"_bit_depth":{"mode":1}
,"iece":{"wise":1}
,"wise":{"linear":1}
,"pixel_phase*specifies":{"sensor":1}
,"phase":{"possible":1}
,"uyvy":{"vyuy":1}
,"vyuy":{"yuyv":1}
,"yuyv":{"yvyu":1}
,"yvyu":{"rggb":1}
,"bggr":{"grbg":1}
,"grbg":{"gbrg":1}
,"gbrg":{"information":1}
,"applies":{"android":1}
,"readout":{"orientation":1,"order":1}
,"change":{"property":1,"state":1,"user":1,".min":1,"controls":1,"format":1,"besides":1,"status":1}
,"program":{"different":1,"frame":1,"camera":1}
,"order":{"mode":1}
,"180":{"270":1}
,"270":{"line_length":1}
,"line":{"width":1,"tx1":1}
,"horizontal":{"timing":1}
,"timing":{"size":1,"pture":1,"gen":1,"comply":1}
,"size":{"sensor":1,"reg_bits":1,"\u002F\u002Fvalue":1}
,"calibrating":{"features":1}
,"features":{"camera":1}
,"stack":{"value":1}
,"larger":{"active_w":1,"pixel_clk_hz":1,"pix_clk_hz":1}
,"multiplier":{"mclk":1}
,"pture":{"sequence":1}
,"sequence":{"hardware":1,"modify":1,"correct":1}
,"hardware":{"following":1,"simply":1,"ensure":1,"describe":1}
,"equation":{"calculate":1}
,"calculate":{"valu":1,"value":1,"_gain":1}
,"valu":{"mclk_multiplier":1}
,"=desired":{"isp":1}
,"frequency":{"\u002Fmc":1}
,"\u002Fmc":{"value":1}
,"pixel_clk_hz":{"\u002Fmclk":1}
,"\u002Fmclk":{"prevent":1,"sure":1}
,"prevent":{"isp":1}
,"underrun":{"pix_clk_hz":1}
,"calculating":{"exposure":1,"gain":1}
,"rate":{"forth":1,"settings":1,"sensor":1,"exposure":1}
,"forth":{"value":1}
,"calculated":{"based":1}
,"(mclk":{"pll":1}
,"pll":{"settings":1}
,"please":{"refer":1}
,"sheet":{"calculate":1}
,"obtained":{"inherently":1,"kernel":1}
,"inherently":{"pixel":1}
,"binning":{"know":1}
,"know":{"value":1}
,"minimum":{"gain":1,"exposure":1,"coarse":1,"high-dynamic-range":1,"frame-rate":1,"maximum":1}
,"limit":{"mode":1,"mod":1}
,"floor":{"decimal":1}
,"decimal":{"places":1}
,"places":{"usually":1,"supported":1,"equation":1}
,"usually":{"1.0":1}
,"1.0":{"(1x":1}
,"(1x":{"gain)":1}
,"max_gain_val":{"specifies":1}
,"maximum":{"gain":1,"exposure":1,"hdr":1,"frame-rate":1,"values":1}
,"increased":{"include":1}
,"digital":{"gain":1}
,"microseconds":{"ceiling":1}
,"ceiling":{"function":1}
,"integer":{"equation":1,"values":1,"controls":1,"bit":1}
,"=(minimum":{"coarse":1}
,"coarse":{"integration":1,"*time":1,"integratio":1}
,"integration":{"time)":1,"time":1}
,"time)":{"*line_length":1}
,"*line_length":{"\u002Fpix_clk_hz":1}
,"\u002Fpix_clk_hz":{"*1000000":1}
,"*1000000":{"minimum":1}
,"intervals":{"unit":1}
,"lines":{"max_exp_time":1,"min_hdr_ratio":1,"updates":1,"update":1}
,"=(m":{"imum":1}
,"imum":{"coarse":1}
,"min_hdr_ratio":{"specifies":1,"empty":1}
,"high-dynamic-range":{"(hdr)":1}
,"(hdr)":{"rat":1}
,"rat":{"limit":1}
,"(for":{"interleave":1,"hdr":1,"dia":1}
,"interleave":{"hdr":1}
,"hdr":{"sensors)":1,"ratio":1,"*switch_ctrl_qmenu":1,"sensors":1,"sensor":1}
,"sensors)":{"non-hdr":1,"min_framerat":1}
,"non-hdr":{"sensors":1}
,"empty":{"string":1}
,"ratio":{"limit":1}
,"min_framerat":{"specifies":1}
,"frame-rate":{"limit":1}
,"mod":{"frames":1,"fps":1}
,"per":{"second":1}
,"(fps)":{"floor":1}
,"=pix_clk_hz":{"\u002F(line_length":1}
,"\u002F(line_length":{"*maximu":1,"*minimu":1}
,"*maximu":{"frame":1}
,"length)":{"max_framerat":1,"embedded_metadata_height":1}
,"max_framerat":{"specifies":1}
,"fps":{"floor":1,"tegra_camera":1}
,"*minimu":{"frame":1}
,"extra":{"embedded":1}
,"embedded":{"metadata":1}
,"metadata":{"rows":1,"support":1}
,"rows":{"frame":1}
,"disable":{"embedded":1}
,"num_control_point*valid":{"mode_type":1}
,"points":{"used":1,"supported":1}
,"performed":{"sensor":1}
,"camer":{"core":1,"a_common_data":1}
,"control_point_x_[0":{".15]*valid":1}
,".15]*valid":{"mode_type":1}
,"x-coordinate":{"control":1,"cannot":1}
,"point":{"piece-wise":1,"properties":1,"g_volatile_ctrl":1,"s_ctrl":1,"scaling":1,"internal":1,"format":1,"forma":1,"initialization":1,"driver":1}
,"cannot":{"exceed":1,"handled":1}
,"exceed":{"power":1}
,"dynamic_pixel_width_depth":{"control_point_y_[0":1}
,"control_point_y_[0":{".15]*valid":1}
,"y-coordinate":{"control":1,"cannot":1}
,"csi_pixel_width_depth":{"*alternative":1}
,"*alternative":{"pixel_t":1}
,"16-bit":{"depth":1}
,"12-bit":{"depth":1}
,"num_control_point":{"control_point_x_0":1}
,"control_point_x_0":{"control_point_x_1":1}
,"control_point_x_1":{"2048":1}
,"2048":{"control_point_x_2":1,"control_point_y_2":1}
,"control_point_x_2":{"16384":1}
,"16384":{"control_point_x_3":1}
,"control_point_x_3":{"65536":1}
,"65536":{"control_point_y_0":1}
,"control_point_y_0":{"control_point_y_1":1}
,"control_point_y_1":{"2048":1}
,"control_point_y_2":{"2944":1}
,"2944":{"control_point_y_3":1}
,"control_point_y_3":{"3712":1}
,"3712":{"port":1}
,"{num-channels":{"=<1>":1}
,"liimx185":{"_vi_in0":1,"_csi_in0":1,"_csi_out0":1}
,"_vi_in0":{"endpoint":1}
,"=<2>":{"bus-width":1,"remote-endpoint":1}
,"=<&liimx185":{"_csi_out0>":1,"_vi_in0>":1}
,"_csi_out0>":{"nvcsi":1}
,"nvcsi":{"{num-channels":1}
,"channel@0":{"{reg":1}
,"_csi_in0":{"endpoint@0":1}
,"endpoint@0":{"{csi-port":1}
,"=<0":{"bus-width":1}
,"=<4":{"remote-endpoint":1}
,"=<&liimx185_imx185":{"_out0>":1}
,"_out0>":{"port@1":1}
,"port@1":{"{reg":1}
,"_csi_out0":{"endpoint@1":1}
,"endpoint@1":{"{remote-endpoint":1}
,"{remote-endpoint":{"=<&liimx185":1}
,"_vi_in0>":{"port":1}
,"description":{"port":1,"imx185":1}
,"mediapad":{"port":1}
,"connection":{"imager":1}
,"imager":{"devices":1,"device":1}
,"pad":{"binding":1,"link)":1,"nk)":1,"u32":1,"holds":1,"used":1,"pad":1,"represents":1,"flags":1,"v4l2_async_register_subdev":1}
,"connec":{"tion":1}
,"tion":{"csi-port":1,"synchronizing":1}
,"csi-port":{"defines":1}
,"defines":{"csi":1,"bus":1,"label":1}
,"identifying":{"number":1}
,"label":{"binding":1}
,"expects":{"port":1}
,"sink":{"source":1,"<-\u0022":1,"sour":1,"por":1,"port":1}
,"verify":{"port":1,"ing":1,"names":1,"default":1,"i2c":1,"sensor":1}
,"bin":{"din":1}
,"din":{"result":1}
,"result":{"execute":1}
,"execute":{"command":1}
,"command":{"sudo":1,"v4l2-compliance":1,"v4l2-ctl":1}
,"sudo":{"media-ctl":1}
,"media-ctl":{"\u002Fdev\u002Fmedia0":1}
,"\u002Fdev\u002Fmedia0":{"output":1}
,"returned":{"similar":1,"boot":1}
,"similar":{"following":1}
,"api":{"version":1}
,"version":{"0.1.0":1,"0.0.0":1}
,"0.1.0":{"media":1}
,"------------------------driver":{"tegra-vi4":1}
,"tegra-vi4":{"model":1}
,"model":{"nvidia":1,"generating":1}
,"video":{"input":1,"linux":1,"operations":1,"indicates":1}
,"info":{"revision":1}
,"revision":{"0x3":1}
,"0x3":{"driver":1}
,"0.0.0":{"device":1}
,"topology":{"-entity":1}
,"-entity":{"150c0000.nvcsi-0":1,"imx185":1,"vi-output":1}
,"150c0000.nvcsi-0":{"pads":1,"[enabled]":1}
,"pads":{"links)":1,"information":1,"fra":1}
,"links)":{"type":1}
,"subdev":{"subtype":1,"holds":1,"perations":1,"ops":1,"client":1,"=&common_data->":1,"\u002F\u002Flink":1,"(priv->":1,"\u002F\u002Fcleanup":1,"entity)":1}
,"subtype":{"unknown":1,"sensor":1,"v4l":1}
,"unknown":{"flags":1}
,"flags":{"device":1,"\u002F\u002Fthe":1,"media":1,"|=v4l2_subdev_fl_has_devnode":1,"priv->":1}
,"\u002Fdev\u002Fv4l-subdev0":{"pad0":1}
,"pad0":{"sink":1,"source":1}
,"<-\u0022":{"imx185":1,"150c0000.nvcsi-0":1}
,"[enabled]":{"pad1":1,"-entity":1,"v4l2":1}
,"pad1":{"source":1}
,"vi-output":{"imx185":1}
,"link)":{"type":1}
,"\u002Fdev\u002Fv4l-subdev1":{"pad0":1}
,"[fmt:srggb12\u002F1920x1080":{"field:none]":1}
,"field:none]":{"150c0000.nvcsi-0":1}
,"nk)":{"type":1}
,"v4l":{"flags":1}
,"\u002Fdev\u002Fvideo0":{"pad0":1,"specify":1,"multiple":1,"v4l2-ctl":1}
,"topic":{"based":1,"describes":1,"run":1}
,"(v4l2)":{"driver":1}
,"(imx185.c)":{"kernel\u002Fkernel-4.4\u002Fdrivers\u002Fmedia\u002Fi2c\u002Fimx185.c":1}
,"kernel\u002Fkernel-4.4\u002Fdrivers\u002Fmedia\u002Fi2c\u002Fimx185.c":{"examine":1}
,"examine":{"source":1,"ntent":1,"kernel":1}
,"content":{"obtain":1}
,"obtain":{"complete":1,"address-value":1}
,"complete":{"understanding":1,"binding":1,"add":1,"run":1,"running":1}
,"understanding":{"driver":1}
,"https:\u002F\u002Flinuxtv.org\u002Fdownloads\u002Fv4l-dvb-apis\u002Fmacro":{"definitions":1}
,"definitions":{"sensor-specific":1,"common_data->":1,"new":1}
,"sensor-specific":{"macro":1}
,"macro":{"values":1,"definitions":1}
,"gen":{"eral":1}
,"eral":{"functionality":1}
,"sensor-private":{"data":1}
,"structure":{"contains":1,"static":1,"required":1,"tells":1}
,"private":{"data":1,"\u002F\u002Fdata":1}
,"struct":{"imx185":1,"v4l2_ctrl_handler":1,"i2c_client":1,"v4l2_subdev":1,"media_pad":1,"regmap":1,"camera_common_data":1,"camera_common_pdata":1,"v4l2_ctrl":1,"v4l2_ctrl_ops":1,"v4l2_ctrl_config":1,"camera_common_sensor_ops":1,"v4l2_subdev_video_ops":1,"v4l2_subdev_core_ops":1,"v4l2_subdev_ops":1,"of_device_id":1,"v4l2_subdev_internal_ops":1,"media_entity_operations":1,"camera_common_frmfmt":1}
,"{struct":{"camera_common_power_rail":1}
,"camera_common_power_rail":{"power":1}
,"int":{"numctrls":1}
,"numctrls":{"struct":1,"holds":1}
,"v4l2_ctrl_handler":{"ctrl_handler":1,"free":1}
,"ctrl_handler":{"struct":1,"&co":1,"=&priv->":1,"\u002F\u002Fi2c":1}
,"i2c_client":{"*i2c_client":1,"holds":1,"used":1,"=client":1,"dev":1}
,"*i2c_client":{"struct":1}
,"v4l2_subdev":{"*subdev":1}
,"*subdev":{"struct":1}
,"media_pad":{"pad":1}
,"u32":{"frame_length":1}
,"frame_length":{"s32":1,"holds":1,"value":1}
,"s32":{"group_hold_prev":1}
,"group_hold_prev":{"bool":1,"holds":1}
,"bool":{"group_hold_en":1}
,"group_hold_en":{"s64":1,"holds":1}
,"s64":{"last_wdr_et_va":1}
,"last_wdr_et_va":{"struct":1}
,"regmap":{"*regmap":1,"depending":1,"interface":1,"priv->":1,"=devm_regmap_init_i2c":1}
,"*regmap":{"struct":1}
,"camera_common_data":{"*s_data":1,"details":1}
,"*s_data":{"struct":1}
,"camera_common_pdata":{"*pdata":1}
,"*pdata":{"struct":1}
,"v4l2_ctrl":{"*ctrls":1,"*array_size":1}
,"*ctrls":{"sensor":1}
,"holds":{"generic":1,"number":1,"required":1,"handle":1,"media":1,"previous":1,"group":1,"register":1,"handles":1}
,"generic":{"power":1}
,"clks":{"gpio":1}
,"ctrl_handlerr":{"holds":1}
,"handler":{"controls":1,"check":1,"link":1,"sensor":1,"private":1,"control":1,"calls":1,"expected":1,"follows":1,"ites":1,"boot-time":1,"linking":1,"priv->":1,"v4l2_ctrl_handler":1}
,"needed":{"v4l2":1,"run":1,"represent":1,"setup":1}
,"init":{"i2c_client":1,"erify":1}
,"handle":{"i2c_client":1,"v4l2":1,"common":1,"control":1}
,"access":{"sensor":1,"working":1}
,"client":{"instance":1,"&subdev_ops)":1,"passed":1}
,"instance":{"subdev":1,"call":1}
,"sub-device":{"needed":1,"internal":1,"function":1,"link":1,"register":1,"v4l2":1}
,"run":{"subdev":1,"v4l2-compliance":1,"v4l2-ctl":1,"completion":1}
,"perations":{"(ops)":1}
,"(ops)":{"pad":1}
,"initialization":{"device":1,"functions":1,"imx185":1,"during":1,"nctions":1,"controls":1,"ther":1}
,"work":{"sink":1}
,"previous":{"state":1,"frame_length":1}
,"group":{"hold":1,"old":1}
,"hold":{"control":1,"enable":1,".type":1,"(register":1}
,"check":{"change":1,"vendor":1,"camera":1,"power-on":1}
,"flag":{"directly":1,"write":1,"enabled":1,"enumeration":1}
,"directly":{"related":1}
,"related":{"group":1}
,"old":{"control":1,"hdr":1}
,"reg_map":{"holds":1}
,"register":{"map":1,"offset":1,"programming":1,"writes":1,"following":1,"imx185":1,"write_table":1,"direct":1,"table":1,"available":1,"themselves":1,"media":1,"subdevice":1,"new":1,"device":1,"address":1,"reside":1,"mode":1,"structu":1}
,"map":{"setup":1}
,"setup":{"i2c":1,"functions":1,"few":1,"media":1,"likely":1,"sprintf":1,"default":1,"erify":1,"contains":1}
,"read":{"write":1,"device":1,"parse_dt":1}
,"write":{"s_data":1,"test-mode":1}
,"s_data":{"holds":1,"=common_data":1}
,"common":{"data":1,"platform":1,"imx185":1,"functions":1,"sets":1,"registering":1,"function":1,"v4l2_i2c_subdev_init":1,"common_data->":1,"problem":1,"issues":1}
,"a_common_data":{"pdata":1}
,"pdata":{"holds":1,"field":1}
,"populated":{"read":1,"correctly":1}
,"ctrls":{"holds":1,"handler":1}
,"handles":{"initialized":1}
,"initialized":{"v4l2":1,"values":1}
,"arra":{"last":1}
,"configuring":{"regmap":1,"controls":1}
,"update":{"values":1,"exposure":1}
,"reg_bits":{"val_bits":1,"specifies":1}
,"val_bits":{"regmap_config":1,"specifies":1,"configuring":1}
,"regmap_config":{"{reg_bits":1,"properties":1}
,"{reg_bits":{"=16":1}
,"=16":{"val_bits":1}
,"bits":{"needed":1,"buffer":1,"storing":1,"fraction":1}
,"represent":{"i2c":1}
,"offset":{"val_bits":1}
,"buffer":{"store":1}
,"store":{"data":1}
,"ransferred":{"i2c":1}
,"determine":{"size":1,"fraction":1}
,"linked":{"control":1,"verify":1,"correctl":1}
,"link":{"cont":1,"power_on":1,"open":1,"v4l2":1,"validation":1}
,"cont":{"rols":1}
,"rols":{"control":1}
,"handlers":{"function":1,"details":1,"ontrol":1,"topic":1,"control":1,"note":1,"(writes)":1,"alled":1,"imx185":1,"default":1}
,"pointers":{"follows":1,"appropriately":1,"enum":1}
,"g_volatile_ctrl":{"internal":1}
,"internal":{"volatile":1,"control":1,"s_stream":1,"operation":1,"media":1}
,"volatile":{"control":1}
,"s_ctrl":{"internal":1,"perform":1,"called":1}
,"static":{"const":1,"struct":1,"imx185":1,"oimx185":1,"array":1}
,"const":{"struct":1}
,"v4l2_ctrl_ops":{"imx185":1}
,"_ctrl_ops":{"={.g_volatile_ctrl":1,"\u002F\u002Fpointer":1,".id":1}
,"={.g_volatile_ctrl":{"=imx185":1}
,"=imx185":{"_g_volatile_ctrl":1,"_s_ctrl":1,"_s_stream":1,"_power_on":1,"_power_off":1,"_write_reg":1,"_read_reg":1,"_fuse_id_setup":1,"_open":1,"_default_mode":1,"_default_width":1,"_default_height":1,"_default_clk_freq":1}
,"_g_volatile_ctrl":{".s_ctrl":1,"function":1}
,".s_ctrl":{"=imx185":1}
,"_s_ctrl":{"following":1,"switch":1}
,"lists":{"controls":1,"tx1":1}
,"list":{"looped":1,"names":1,"known":1,"rare":1,"reg_8":1,"required":1,"contains":1,"enumeratio":1}
,"looped":{"during":1}
,"during":{"ctrls_init":1,"parsing":1,"boot":1,"probe":1}
,"ctrls_init":{"call":1}
,"initialize":{"controls":1,"static":1}
,"con":{"trol":1}
,"trol":{"accessible":1,"sensors":1,"handler":1}
,"accessible":{"ctrls":1}
,"ones":{"used":1}
,"user-mode":{"library":1}
,"v4l2_ctrl_config":{"ctrl_config_list":1}
,"ctrl_config_list":{"={\u002F*integer":1,"registers":1,"information":1}
,"={\u002F*integer":{"control":1}
,"*time":{"*and":1}
,"*and":{"frame":1}
,"length":{"*\u002F{.ops":1,"registers":1,"converts":1,"coarse":1}
,"*\u002F{.ops":{"=&imx185":1}
,"=&imx185":{"_ctrl_ops":1,"_subdev_core_ops":1,"_subdev_video_ops":1,"_common_ops":1,"_frmfmt":1,"_subdev_internal_ops":1,"_media_ops":1}
,"\u002F\u002Fpointer":{"control":1}
,"ops":{"\u002F\u002Ffunction":1,"\u002F\u002Fsetting":1,"setting":1,"=&imx185":1}
,"\u002F\u002Ffunction":{".id":1}
,".id":{"=tegra_camera":1}
,"=tegra_camera":{"_cid_gain":1,"_cid_group_hold":1,"_cid_frame_rate":1,"_cid_exposure":1}
,"_cid_gain":{"\u002F\u002Fid":1,"control":1,"updates":1,"specifies":1,"case":1}
,"\u002F\u002Fid":{"defined":1}
,"\u002F\u002Fcamera_common.h":{".name":1}
,".name":{"gain":1,"group":1}
,"\u002F\u002Fstring":{"name":1}
,".type":{"=v4l2_ctrl_type_integer":1,"=v4l2_ctrl_type_integer_menu":1}
,"=v4l2_ctrl_type_integer":{"\u002F\u002Ftype":1}
,"\u002F\u002Ftype":{"control":1}
,".flags":{"=v4l2_ctrl_flag_slider":1}
,"=v4l2_ctrl_flag_slider":{"\u002F\u002Fcontrol":1}
,"\u002F\u002Fcontrol":{"flags":1,"value":1,"handler":1}
,"\u002F\u002Fthe":{"following":1}
,"likely":{"need":1}
,"need":{"change":1,"modify":1}
,".min":{"*fixed":1,".max":1}
,"*fixed":{"point":1}
,"scaling":{"factor":1}
,"factor":{"\u002F\u002Fcontrol":1,"\u002F\u002Fdefault":1,"\u002F10":1}
,"lower":{"bound":1,"bits":1}
,"bound":{".max":1,".def":1}
,".max":{"=48":1,"=array_size":1}
,"=48":{"*fixed":1}
,"upper":{"bound":1,"bits":1}
,".def":{"*fixed":1,".qmenu_int":1}
,"\u002F\u002Fdefault":{"control":1,"frame":1}
,".step":{"*fixed":1}
,"\u002F10":{"\u002F\u002Fincrement":1}
,"\u002F\u002Fincrement":{"step":1}
,"step":{"size":1}
,"\u002F\u002Fvalue":{"\u002F*menu":1}
,"\u002F*menu":{"control":1}
,"on\u002Foff":{"switch":1,"*shouldn\u0027t":1}
,"switch":{"group":1,"statement":1,"(ctrl->":1}
,"*switch_ctrl_qmenu":{"used":1}
,"states":{"on\u002Foff":1}
,"*shouldn\u0027t":{"need":1}
,"nless":{"*completely":1}
,"*completely":{"new":1}
,"new":{"added":1,"modes":1,"custom":1,"device":1,"module":1,"controls":1,"calculate":1,"enumeration":1,"mode":1}
,"_cid_group_hold":{".name":1}
,"=v4l2_ctrl_type_integer_menu":{".min":1}
,"=array_size":{"(switch_ctrl_qmenu)":1,"(imx185":1}
,"(switch_ctrl_qmenu)":{".menu_skip_mask":1}
,".menu_skip_mask":{".def":1}
,".qmenu_int":{"=switch_ctrl_qmenu":1}
,"=switch_ctrl_qmenu":{"setting":1}
,"registers":{"register":1,"unit":1,"uni":1,"controls":1,"majority":1,"imx185":1,"control":1,"gain":1}
,"writes":{"integer":1,"control":1,"imx185":1,"initial":1,"registers":1,"erify":1}
,"functions":{"addr":1,"register":1,"wrappers":1,"functions":1,"power-related":1,"additionally":1,"commo":1,"static":1,"imx185.c":1,"information":1,"initializing":1,"imx185":1,"match":1,"run":1,"boot-time":1}
,"addr":{"epends":1,"val":1}
,"epends":{"sensor":1}
,"val":{"source":1,"pairs":1}
,"calls":{"functions":1,"regulator_enable":1,"regulator_put":1,"camera_common_regulator_get":1,"register":1,"integer-control":1,"appropriate":1,"control":1,"initializing":1,"otp_setup":1,"initialization":1,"various":1,"pro":1,"runs":1}
,"_get_frame_length_regs":{"imx185":1}
,"_get_coarse_time_regs":{"_shs1":1,"_shs2":1}
,"_shs1":{"imx185":1}
,"_shs2":{"imx185":1}
,"_get_gain_reg":{"read-write":1}
,"read-write":{"wrapper":1,"interface":1}
,"wrapper":{"register":1}
,"wrappers":{"read-write":1}
,"however":{"modify":1}
,"modify":{"function":1,"structure":1}
,"interfaces":{"imx185":1}
,"_read_reg":{"imx185":1,"control":1}
,"_write_reg":{"imx185":1,".read_reg":1}
,"_write_table":{"power":1}
,"power-related":{"controls":1}
,"_power_on":{"contains":1,".power_off":1}
,"power-on":{"sequence":1,"function":1}
,"sheets":{"calls":1,"information":1,"erify":1}
,"regulator_enable":{"turn":1}
,"turn":{"regulators":1}
,"gpio_set_value":{"toggle":1}
,"toggle":{"gpio":1}
,"_power_off":{"contains":1,".write_reg":1}
,"power-off":{"sequence":1}
,"_power_put":{"calls":1}
,"regulator_put":{"regulators":1}
,"_power_get":{"calls":1,"(priv)":1}
,"camera_common_regulator_get":{"helper":1}
,"helper":{"function":1}
,"regulator_get":{"acquire":1}
,"acquire":{"regulators":1}
,"power_get":{"function":1,"calls":1}
,"prior":{"calling":1}
,"calling":{"power_on":1}
,"power_on":{"power_off":1}
,"power_off":{"functions":1,"write_reg":1}
,"additionally":{"driver":1}
,"power_put":{"function":1}
,"release":{"regulators":1,"register":1}
,"drive":{"released":1}
,"released":{"setting":1}
,"sub":{"-device":1,"-devices":1,"devices":1}
,"-device":{"camera":1}
,"_s_stream":{"function":1,"writes":1,"need":1}
,"mainly":{"writing":1}
,"writing":{"mode":1}
,"tables":{"maki":1,"imx185":1,"addition":1,"enabling":1,"following":1,"common_data->":1,"modes":1,"register":1,"list":1,"separated":1,"static":1,"enumeration":1,"ist":1,"xist":1,"enum":1}
,"maki":{"calls":1}
,"write_table":{"function":1}
,"_mode_tbls.h":{"file":1}
,"addition":{"writing":1}
,"enabling":{"stream":1,"power":1}
,"stream":{"stream-enable":1}
,"stream-enable":{"register":1}
,"initial":{"integer-control":1}
,"integer-control":{"values":1,"handlers":1}
,"section":{"control":1,"parser":1}
,"ontrol":{"[0]":1}
,"[0]":{".id":1,".value":1,"\u002F\u002Fbased":1}
,"[1]":{".id":1}
,"_cid_frame_rate":{"control":1,"tegra_camera":1,"v4l2":1}
,"[2]":{".id":1}
,"_cid_exposure":{"err":1,"updates":1,"note":1,"controls":1}
,"err":{"=v4l2_g_ext_ctrl":1,"|=imx185":1,"=imx185":1}
,"=v4l2_g_ext_ctrl":{"(&priv->":1}
,"(&priv->":{"ctrl_handler":1,"subdev->":1,"subdev":1,"ctrl_handler)":1}
,"&co":{"trl":1}
,"trl":{"err":1}
,"|=imx185":{"_set_gain":1}
,"_set_gain":{"(priv":1,"imx185":1}
,"(priv":{"control":1}
,".value":{"test":1}
,"test":{"pattern":1,"enter":1,"run":1,"patte":1}
,"pattern":{"supported":1}
,"patt":{"ern":1}
,"ern":{"add":1}
,"test_mode":{"flag":1}
,"test-mode":{"table":1}
,"commo":{"camera":1,"data":1}
,"refers":{"camera":1}
,"sets":{"v4l2":1,"once":1,"ormat":1}
,"requiring":{"linkage":1}
,"linkage":{"iver":1}
,"camera_common_sensor_ops":{"struct":1,"imx185":1}
,"modifying":{"adding":1,"function":1}
,"adding":{"new":1}
,"modes":{"mode":1,"tables":1}
,"snippets":{"v4l2":1}
,"-devices":{"camera":1}
,"registering":{"sens":1,"devi":1}
,"sens":{"driver":1}
,"s_stream":{"pointer":1,"function":1}
,"pointer":{"point":1,"core":1}
,"leave":{"ointers":1}
,"ointers":{"static":1}
,"v4l2_subdev_video_ops":{"imx185":1}
,"_subdev_video_ops":{"={.s_stream":1,"during":1}
,"={.s_stream":{"=imx185":1}
,"v4l2_subdev_core_ops":{"imx185":1}
,"_subdev_core_ops":{"match":1,".video":1}
,"match":{"name":1,"devices":1,"several":1,"device":1,"hardware":1}
,"operations":{"function":1,"pad":1}
,"above":{"ollows":1,"priv->":1}
,"ollows":{"static":1}
,"v4l2_subdev_ops":{"imx185":1}
,"_subdev_ops":{"={.core":1}
,"={.core":{"=&imx185":1}
,".video":{"=&imx185":1}
,"parsing":{"device":1,"establi":1}
,"of_device_id":{"matches":1,"imx185":1}
,"matches":{"compatible":1,"device":1}
,"_of_match":{"={{.compatible":1}
,"={{.compatible":{"nvidia":1}
,"appropriately":{"link":1,"values":1}
,"write_reg":{"read_reg":1}
,"read_reg":{"functions":1}
,"_common_ops":{"={.power_on":1,"\u002F\u002Fcontrol":1}
,"={.power_on":{"=imx185":1}
,".power_off":{"=imx185":1}
,".write_reg":{"=imx185":1}
,".read_reg":{"=imx185":1}
,"describes":{"control":1}
,"top-level":{"structure":1}
,"tells":{"function":1}
,"expected":{"handle":1}
,"set-control":{"function":1,"operation":1,"calls":1}
,"desired":{"control":1}
,"operation":{"tegra_camera":1,"v4l2":1,"requirements":1,"static":1}
,"updates":{"gain":1,"frame":1,"coarse":1}
,"ratios":{"gain":1}
,"_cid_frame_length":{"v4l2":1,"tegra_camera":1}
,"cid_frame_rate":{"updates":1}
,"_cid_coarse_time":{"tegra_camera":1,"(deprecated)":1}
,"uni":{"lines":1}
,"econds":{"exposure":1}
,"_cid_coarse_time_short*updates":{"short":1}
,"short":{"coarse":1}
,"seconds":{"tegra_camera":1}
,"_cid_group_hold*provides":{"sensor":1}
,"(register":{"hold)":1}
,"hold)":{"con":1}
,"supporting":{"feature":1}
,"feature":{"true":1}
,"_cid_hdr_enable*toggles":{"normal":1}
,"normal":{"hdr":1}
,"vailable":{"hdr":1}
,"_cid_otp_data*reads":{"module":1}
,"one-time":{"programmable":1}
,"programmable":{"(otp)":1,"read-only":1}
,"(otp)":{"memor":1}
,"memor":{"data":1}
,"_cid_fuse_id*reads":{"sensor":1}
,"fuse":{"tegra_camera":1}
,"_cid_sensor_mode_id*used":{"selecting":1}
,"selecting":{"specific":1}
,"_cid_vi_bypass_mode**used":{"bypassing":1}
,"bypassing":{"settings":1}
,"_cid_override_enable**used":{"overriding":1}
,"overriding":{"gain":1}
,"fro":{"default":1}
,"**provided":{"nvidia":1}
,"framew":{"ork":1}
,"ork":{"kernel":1}
,"per-frame":{"gain":1}
,"takes":{"bit":1,"vice":1}
,"lue":{"user":1}
,"(deprecated)":{"bit":1,"64-bit":1,"specifies":1}
,"24.8":{"format":1}
,"(24":{"bit":1}
,"fract":{"ion)":1}
,"ion)":{"default":1,"*see":1}
,"adjust":{"min\u002Fmax":1}
,"min\u002Fmax":{"gain":1}
,"ran":{"driver":1}
,"fraction":{"specifies":1,"values":1}
,"42.22":{"format":1}
,"(42":{"bit":1}
,"*see":{"imx185_set_gain":1,"fixed":1}
,"imx185_set_gain":{"function":1}
,"imx185.c":{"file":1}
,"achieved":{"using":1,"multiplying":1}
,"32-bit":{"input":1}
,"parameters":{"tegra_camera":1,"according":1}
,"64-bit":{"input":1}
,"either":{"controls":1}
,"mix":{"oth":1}
,"oth":{"sets":1}
,"once":{"control":1,"sub":1}
,"pre-processed":{"bit":1}
,"converts":{"frame":1,"exposure":1}
,"integratio":{"time":1}
,"low":{"tegra_camera":1}
,"cid_exposure":{"specifies":1}
,"unprocessed":{"bit":1}
,"value*":{"user":1}
,"passes":{"frame":1}
,"pre-processing":{"driver":1}
,"sponsible":{"converting":1}
,"converting":{"values":1}
,"ength":{"coarse":1}
,"method":{"sensor":1,"static":1}
,"special":{"requirem":1}
,"requirem":{"ents":1}
,"ents":{"cannot":1}
,"handled":{"user":1}
,"imx185_set_frame_rate":{"imx185_set_exposure":1}
,"imx185_set_exposure":{"functions":1}
,"fixed":{"point":1}
,"implements":{"tegra_camera":1}
,"q42":{"fixed":1}
,"q42.22":{"fixed":1}
,"forma":{"upper":1}
,"storing":{"integer":1}
,"workaround":{"due":1}
,"due":{"lack":1,"wrong":1}
,"lack":{"floating":1}
,"floating":{"oint":1}
,"oint":{"kernel":1}
,"multiplying":{"origina":1}
,"origina":{"value":1}
,"<<22":{"fixed_point_scaling_factor":1}
,"fixed_point_scaling_factor":{"value":1,"(1ull":1,"last":1}
,"(1ull":{"<<22)":1}
,"<<22)":{"fixed-point":1}
,"fixed-point":{"format":1}
,"caution":{"value":1}
,"divided":{"back":1}
,"back":{"original":1,".dtsi":1}
,"original":{"pre":1}
,"pre":{"cision":1}
,"cision":{"calculation":1}
,"calculation":{"best":1}
,"best":{"results":1}
,"results":{"multiply":1}
,"multiply":{"first":1}
,"divide":{"value":1}
,"avoid":{"unexpected":1}
,"unexpected":{"precision":1}
,"precision":{"loss":1}
,"loss":{"flow":1,"gain8":1}
,"flow":{"issues":1}
,"issues":{"example":1,"cause":1}
,"equations":{"yield":1}
,"yield":{"different":1}
,"esults":{"gain8":1}
,"gain8":{"=(u8)":1}
,"=(u8)":{"(gain64":1}
,"(gain64":{"\u002Ffixed_point_scaling_factor":1,"*160":1}
,"\u002Ffixed_point_scaling_factor":{"*160":1,"\u002F\u002Fcorrect":1}
,"*160":{"\u002F48)":1,"\u002F48":1}
,"\u002F48)":{"\u002F\u002Fincorrect":1}
,"\u002F\u002Fincorrect":{"precision":1}
,"\u002F48":{"\u002Ffixed_point_scaling_factor":1}
,"\u002F\u002Fcorrect":{"v4l2":1}
,"statement":{"redirect":1,"control":1,"imx185":1,"setter-control":1,"specifying":1}
,"redirect":{"set-control":1,"ing":1}
,"appropriate":{"control":1,"values":1,"parameter":1}
,"read-only":{"controls":1,"memory":1}
,"fuse_id":{"one-time":1}
,"memory":{"(otp":1,"commo":1,"format":1}
,"(otp":{"om)":1}
,"om)":{"case":1}
,"case":{"statement":1,"tegra_camera":1}
,"(ctrl->":{"id)":1}
,"id)":{"{case":1}
,"{case":{"tegra_camera":1}
,"_cid_eeprom_data":{"case":1}
,"_cid_hdr_en":{"hdr_en":1}
,"hdr_en":{"pure":1}
,"pure":{"software":1}
,"software":{"control":1}
,"ites":{"hardware":1}
,"simply":{"break":1,"retu":1}
,"break":{"itch":1}
,"itch":{"statement":1}
,"setter-control":{"handlers":1}
,"(writes)":{"setter-control":1}
,"alled":{"s_ctrl":1}
,"control-handling":{"operati":1}
,"operati":{"ons":1}
,"ons":{"writes":1,"media":1}
,"majority":{"controls":1}
,"ister":{"setup":1}
,"_set_group_hold":{"imx185":1}
,"_set_frame_length":{"imx185":1}
,"_set_coarse_time":{"imx185":1}
,"_set_coarse_time_short":{"imx185":1}
,"_write_eeprom":{"get-volatile":1}
,"get-volatile":{"control":1}
,"get-control":{"calls":1,"simply":1}
,"non-volatile":{"controls":1}
,"retu":{"rns":1}
,"rns":{"previously":1}
,"previously":{"written":1}
,"written":{"value":1}
,"stored":{"con":1,"private":1}
,"boot-time":{"initialization":1}
,"initializing":{"boot":1,"value":1}
,"boot":{"time":1,"imx185":1,"loader":1}
,"_ctrls_init":{"function":1,"err":1,"(priv)":1}
,"iterates":{"ctrl_config_list":1}
,"custom":{"contr":1}
,"contr":{"v4l2":1,"oller":1}
,"called":{"control":1,"sensor_mode_tbls.h":1}
,"configuration":{"controls":1,"driver":1,"enabled":1,"dtsi":1,"verify":1,"list":1}
,"necessary":{"calls":1,"common":1}
,"read-onl":{"controls":1}
,"otp_setup":{"fuse_id_setup":1}
,"fuse_id_setup":{"control":1}
,"_fuse_id_setup":{"(priv)":1}
,"(priv)":{"device":1,"\u002F\u002Flink":1,"next":1}
,"parser":{"imx185":1,"device":1}
,"_parse_dt":{"function":1,"(client)":1}
,"parses":{"device":1}
,"trees":{"takes":1,"appropriate":1,"stored":1}
,"nod":{"looks":1}
,"looks":{"parameters":1}
,"sensor-related":{"private":1}
,"limited":{"mclk":1}
,"pwdn-gpios":{"reset-gpios":1}
,"reset-gpios":{"af-gpios":1}
,"af-gpios":{"avdd-reg":1}
,"names":{"devic":1,"match":1,"read":1,"gpio":1,"out-of-date":1}
,"devic":{"tree":1}
,"respective":{"name-value":1}
,"name-value":{"pairs":1}
,"few":{"additional":1}
,"components":{"needed":1}
,"open":{"call":1,"operation":1,"source":1}
,"placeholder":{"operat":1}
,"operat":{"ion":1,"ions":1}
,"ion":{"satisfying":1,"commands":1}
,"satisfying":{"v4l2":1}
,"requirements":{"setup":1}
,"besides":{"name":1}
,"hange":{"match":1}
,"_open":{"sub-device":1,"media":1}
,"eration":{"link":1}
,"v4l2_subdev_internal_ops":{"imx185":1}
,"_subdev_internal_ops":{"={.open":1,"\u002F\u002Fsetup":1}
,"={.open":{"=imx185":1}
,"entity":{"function":1,"pads":1,"media":1,"unit":1,"multiple":1,"types":1,"operat":1,"type":1,"&priv->":1,"cleanup":1}
,"validation":{"method":1}
,"media_entity_operations":{"imx185":1}
,"_media_ops":{"={.link_validate":1,"\u002F\u002Finitialize":1}
,"={.link_validate":{"=v4l2_subdev_link_validate":1}
,"=v4l2_subdev_link_validate":{"sensor-driver":1}
,"sensor-driver":{"probing":1}
,"probing":{"probing":1,"function":1,"process":1,"succeeds":1}
,"entry":{"point":1}
,"_probe":{"function":1}
,"nction":{"starts":1}
,"starts":{"allocating":1}
,"allocating":{"memory":1}
,"informati":{"sensor-private":1}
,"common_data":{"=devm_kzalloc":1,"csi_port":1}
,"=devm_kzalloc":{"(&client->":1}
,"(&client->":{"dev":1}
,"dev":{"sizeof":1,"i2c_client":1,"(for":1,"=&client->":1,"setup":1}
,"sizeof":{"(struct":1}
,"(struct":{"camera_common_data)":1,"imx185":1,"v4l2_ctrl":1}
,"camera_common_data)":{"gfp_kernel)":1}
,"gfp_kernel)":{"priv":1,"function":1}
,"priv":{"=devm_kzalloc":1,"=(void":1,"\u002F\u002Fnumber":1}
,"*array_size":{"(ctrl_config_list)":1}
,"(ctrl_config_list)":{"gfp_kernel)":1}
,"initializes":{"regmap":1}
,"priv->":{"regmap":1,"i2c_client":1,"s_data":1,"subdev":1,"subdev->":1,"pad.flags":1}
,"=devm_regmap_init_i2c":{"(client":1}
,"(client":{"&senso":1}
,"&senso":{"r_regmap_config)":1}
,"r_regmap_config)":{"next":1}
,"next":{"function":1}
,"nctions":{"including":1}
,"including":{"\u002F\u002Fsee":1}
,"\u002F\u002Fsee":{"section":1,"power":1,"initialization":1}
,"\u002F\u002Fdata":{"pdata":1}
,"(client)":{"\u002F\u002Fsee":1}
,"\u002F\u002Flink":{"appropr":1,"ops":1,"common":1,"v4l2":1,"subdevice":1}
,"appropr":{"iate":1}
,"iate":{"subdev":1}
,"\u002F\u002Fsetting":{"v4l2":1}
,"subdevice":{"camera":1,"handler":1,"dev":1,"internal":1,"flags":1,"media":1}
,"v4l2_i2c_subdev_init":{"(&common_data->":1}
,"(&common_data->":{"subdev":1}
,"&subdev_ops)":{"\u002F\u002Fsee":1}
,"links":{"common":1,"once":1,"devices":1}
,"senso":{"r-private":1}
,"r-private":{"values":1}
,"common_data->":{"ops":1,"ctrl_handler":1,"i2c_client":1,"frmfmt":1,"colorfmt":1,"power":1,"priv":1,"numfmts":1,"def_mode":1,"def_width":1,"def_height":1,"def_clk_freq":1}
,"linking":{"common_data->":1}
,"=&priv->":{"ctrl_handler":1,"power":1}
,"\u002F\u002Fi2c":{"client":1}
,"passed":{"probe":1}
,"probe":{"common_data->":1,"priv->":1,"control":1}
,"=client":{"\u002F\u002Fdefault":1,"\u002F\u002Flink":1}
,"frmfmt":{"=&imx185":1,"array":1}
,"_frmfmt":{"[0]":1,"={{{1920":1,"{{#":1}
,"\u002F\u002Fbased":{"default":1}
,"genera":{"lly":1}
,"lly":{"defaults":1}
,"defaults":{"\u002F\u002Fto":1}
,"\u002F\u002Fto":{"format":1}
,"colorfmt":{"=camera_common_find_datafmt":1}
,"=camera_common_find_datafmt":{"(imx185":1}
,"(imx185":{"_default_datafmt)":1,"_frmfmt)":1,"_of_match)":1}
,"_default_datafmt)":{"\u002F\u002Fpower-handler":1}
,"\u002F\u002Fpower-handler":{"linking":1}
,"\u002F\u002Fsensor-private":{"data":1}
,"=(void":{"priv":1}
,"\u002F\u002Fnumber":{"format":1}
,"numfmts":{"=array_size":1}
,"_frmfmt)":{"\u002F\u002Fset":1}
,"\u002F\u002Fset":{"port":1}
,"camera_common_parse_ports":{"\u002F\u002Fport":1}
,"\u002F\u002Fport":{"information":1}
,"nam":{"debugfs":1}
,"debugfs":{"node":1}
,"sprintf":{"(debugfs_name":1}
,"(debugfs_name":{"imx185":1}
,"csi_port":{"\u0027a\u0027)":1}
,"\u0027a\u0027)":{"camera_common_create_debugfs":1}
,"camera_common_create_debugfs":{"(common_data":1}
,"(common_data":{"debugfs_name":1}
,"debugfs_name":{"setup":1}
,"def_mode":{"=imx185":1}
,"_default_mode":{"common_data->":1}
,"def_width":{"=imx185":1}
,"_default_width":{"common_data->":1}
,"def_height":{"=imx185":1}
,"_default_height":{"common_data->":1}
,"def_clk_freq":{"=imx185":1}
,"_default_clk_freq":{"\u002F\u002Fi2c":1}
,"=common_data":{"\u002F\u002Flink":1}
,"=&common_data->":{"subdev":1}
,"dia":{"controller":1}
,"usage)":{"priv->":1}
,"subdev->":{"dev":1,"internal_ops":1,"flags":1,"entity.type":1,"entity.ops":1,"entity":1}
,"=&client->":{"dev":1}
,"themselves":{"sub":1}
,"oller":{"framework":1}
,"acts":{"master":1}
,"master":{"device":1}
,"whic":{"controls":1}
,"establi":{"media":1}
,"regi":{"stered":1}
,"stered":{"sub-device":1}
,"defining":{"entity":1}
,"represented":{"dia":1,"complete":1}
,"establishing":{"connecti":1}
,"connecti":{"ons":1}
,"fra":{"mework":1}
,"mework":{"provides":1}
,"known":{"entity":1}
,"corresponding":{"media":1}
,"behaves":{"sink":1}
,"sour":{"port":1}
,"whi":{"ound":1}
,"ound":{"imager":1}
,"por":{"source":1}
,"ions":{"priv->":1}
,"internal_ops":{"=&imx185":1}
,"\u002F\u002Fsetup":{"subdevice":1,"media":1}
,"|=v4l2_subdev_fl_has_devnode":{"v4l2_subdev_fl_has_events":1}
,"v4l2_subdev_fl_has_events":{"\u002F\u002Fsetup":1}
,"pad.flags":{"=media_pad_fl_source":1}
,"=media_pad_fl_source":{"priv->":1}
,"entity.type":{"=media_ent_t_v4l2_subde":1}
,"=media_ent_t_v4l2_subde":{"v_sensor":1}
,"v_sensor":{"priv->":1}
,"entity.ops":{"=&imx185":1}
,"\u002F\u002Finitialize":{"register":1}
,"ent":{"ity":1}
,"ity":{"media":1}
,"media_entity_init":{"(&priv->":1}
,"&priv->":{"pad":1}
,"v4l2_async_register_subdev":{"(priv->":1}
,"(priv->":{"subdev)":1,"subdev":1}
,"subdev)":{"remov":1}
,"remov":{"ing":1}
,"_remove":{"function":1}
,"removes":{"sensor-device":1}
,"shutdown":{"function":1}
,"makes":{"calls":1}
,"free":{"put":1,"(&priv->":1}
,"put":{"destroy":1}
,"destroy":{"functions":1}
,"several":{"calls":1}
,"pro":{"remain":1}
,"remain":{"largely":1}
,"largely":{"\u002F\u002Funregister":1}
,"\u002F\u002Funregister":{"v4l2":1}
,"async":{"unregister":1}
,"unregister":{"subdev":1,"subdevice":1,"plugin":1}
,"\u002F\u002Fcleanup":{"unregister":1}
,"enti":{"media":1}
,"cleanup":{"(&priv->":1}
,"entity)":{"initialization":1}
,"\u002F\u002Ffreeing":{"control":1}
,"ctrl_handler)":{"kernel":1}
,"development":{"complete":1,"guide":1}
,"enabled":{"kernel":1,"activating":1}
,"follow":{"config_video":1}
,"config_video":{"imx185":1}
,"<top>\u002Fkernel\u002Fkernel-4.4\u002Farch\u002Farm64\u002Fconfigs\u002Ftegra21":{"_android_defconfig":1,"_defconfig":1}
,"_android_defconfig":{"tx2":1,"linux":1}
,"<top>\u002Fkernel\u002Fkernel-4.4\u002Farch\u002Farm64\u002Fconfigs\u002Ftegra18":{"_android_defconfig":1,"_defconfig":1}
,"_defconfig":{"tx2":1,"device":1}
,"registration":{"driver":1}
,"devi":{"tree":1,"using":1,"node":1}
,"instantiated":{"kernel":1}
,"boots":{"two":1,"plugin":1,"specific":1}
,"ways":{"registering":1}
,"plugin":{"man":1,"manager":1}
,"man":{"ger":1}
,"ger":{"camera":1,"support":1}
,"onboard":{"eeprom":1}
,"eeprom":{"valid":1}
,"valid":{"camera":1}
,"manager":{"used":1,"automatically":1,"uses":1,"allows":1,"support":1,"dtsi":1,"default":1}
,"meet":{"equirement":1}
,"equirement":{"main":1}
,"main":{"platform":1,"devi":1,"driver":1}
,"instead":{"followin":1}
,"followin":{"directions":1}
,"directions":{"using":1}
,"automatically":{"links":1,"plugin":1}
,"cam":{"era":1}
,"era":{"module":1}
,"loader":{"updat":1}
,"updat":{"device":1}
,"entries":{"proper":1}
,"proper":{"information":1,"verride":1,"state":1,"csi":1}
,"runtime":{"plugin":1}
,"allows":{"single":1}
,"image":{"support":1}
,"chang":{"camera":1}
,"replace":{"camera":1}
,"reboot":{"new":1}
,"works":{"automatically":1}
,"status":{"device":1,"=disable":1,"=okay":1,"field":1}
,"disabled":{"follows":1,"pdate":1}
,"_cam0":{"imx185":1}
,"_a@1a":{"{status":1}
,"{status":{"disabled":1}
,"pdate":{"camera":1,"necessary":1}
,"verride":{"information":1}
,"fragment-imx185":{"{ids":1}
,"{ids":{"lprd-002001":1}
,"lprd-002001":{"override@0":1}
,"override@0":{"{target":1}
,"{target":{"=<&imx185":1}
,"=<&imx185":{"_cam0>":1}
,"_cam0>":{"_overlay_{status":1}
,"_overlay_{status":{"okay":1}
,"okay":{"kernel":1}
,"found":{"override":1}
,"override":{"data":1,"information":1}
,"spec":{"ific":1}
,"ific":{"device":1}
,"made":{"available":1}
,"prerequisites":{"obtained":1}
,"informa":{"tion":1}
,"synchronizing":{"kernel":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002F:q":{"210":1}
,"\u002Fkernel-dts\u002Fjetson":{"-platforms\u002Ftegra":1}
,"-platforms\u002Ftegra":{"210":1}
,"-jetson":{"-cv-camera-modules.dtsi":1,"-cv-base-p":1}
,"-cv-camera-modules.dtsi":{"tx2":1,"model":1}
,"8x-common-platforms\u002Ftegra186-quill-camera-modules":{"dtsi":1}
,"\u002Fkernel-dts\u002Fjetson-plugin-manager\u002Ftegra210-jetson-cv":{"-camera-plugin-manager.dtsi":1}
,"-camera-plugin-manager.dtsi":{"tx2":1}
,"8x-common-plugin-manager\u002Ftegra186-quill-camera":{"-plugin-manager.dtsi":1}
,"-plugin-manager.dtsi":{"using":1}
,"updating":{"main":1}
,"ecause":{"tegra":1}
,"ust":{"first":1}
,"mor":{"information":1}
,"main-platform":{"device":1}
,"edit":{"following":1}
,"210\u002Fjetson":{"\u002Fkernel-dts\u002Ftegra":1}
,"\u002Fkernel-dts\u002Ftegra":{"210":1}
,"-cv-base-p":{"2597":1}
,"2597":{"0-2180-a00.dts":1,"-2180-a00":1}
,"0-2180-a00.dts":{"tx2":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fquill\u002Fkernel-dts\u002Fteg":{"ra186-quill-p3310-1000-a00-00-base.dtsi":1,"ra186-quill-p3310-1000-a00-00-base.dts":1}
,"ra186-quill-p3310-1000-a00-00-base.dtsi":{"dtsi":1}
,"remove":{"following":1}
,"jetson-plugin-manager\u002Ftegra210-jetson-cv":{"-camera-plugin-manager.dtsi":1}
,"<t18x-common-plugin-manager\u002Ftegra186-quil":{"l-camera-plugin-manager.dtsi":1}
,"l-camera-plugin-manager.dtsi":{"locate":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft210":{"\u002Fjetson":1}
,"-2180-a00":{".dts":1}
,".dts":{"tx2":1}
,"ra186-quill-p3310-1000-a00-00-base.dts":{"dts":1}
,"dts":{"file":1}
,"eplace":{"following":1}
,"jetson-platforms":{"\u002Ftegra":1}
,"\u002Ftegra":{"210":1}
,"-jetson-cv":{"-camera-modules.dtsi":1}
,"-camera-modules.dtsi":{"tx2":1}
,"<t18x-common-platforms\u002Ftegra186-quill-cam":{"era-modules.dtsi>":1}
,"era-modules.dtsi>":{"ith":1}
,"ith":{"include":1}
,"specifying":{"dtsi":1}
,"tegra210-jetson-cv-camera-modules.dtsi":{"tegra":1}
,"18x":{"-quill":1}
,"-quill":{"-cv-camera-modules.dtsi":1}
,"generating":{"dtsi":1}
,"=disable":{"status":1}
,"=okay":{"verify":1}
,"v4l2-compliance":{"v4l2-ctl":1,"test":1,"\u002Fdev\u002Fvideo0":1}
,"v4l2-ctl":{"ensure":1,"test":1,"--set-fmt-video=width=1":1,"capture":1,"available":1}
,"ensure":{"driver":1,"values":1,"status":1,"power_get":1,"contain":1,"control":1}
,"capture":{"raw":1}
,"hrough":{"v4l2":1}
,"technical":{"reference":1}
,"reference":{"manual":1}
,"manual":{"video":1}
,"enter":{"command":1}
,"specify":{"device":1}
,"indicates":{"index":1}
,"availabl":{"system":1}
,"--set-fmt-video=width=1":{"height=1080":1}
,"height=1080":{"pixelformat=rg1":1}
,"pixelformat=rg1":{"--stream-mmap":1}
,"--stream-mmap":{"-set-ctrl=sensor_mode=0":1}
,"-set-ctrl=sensor_mode=0":{"--stream-count=100":1}
,"--stream-count=100":{"\u002Fdev\u002Fvideo0":1}
,"provide":{"appropriate":1}
,"projects":{"documentat":1}
,"documentat":{"ion":1}
,"commands":{"available":1}
,"linuxtv":{"https:\u002F\u002Fwww.linuxtv.org\u002Fwiki\u002Findex.php\u002Fv4l-utils":1}
,"https:\u002F\u002Fwww.linuxtv.org\u002Fwiki\u002Findex.php\u002Fv4l-utils":{"debugging":1}
,"debugging":{"tips":1,"typically":1}
,"tips":{"driver":1}
,"running":{"mera":1,"fast":1}
,"mera":{"applications":1}
,"(s)":{"populated":1}
,"correctly":{"system":1,"linked":1}
,"loaded":{"properly":1}
,"properly":{"following":1,"closely":1}
,"displayed":{"\u002Fdev\u002F<video":1}
,"\u002Fdev\u002F<video":{"device":1}
,"i\u002Fo":{"interface":1}
,"user-space":{"driver":1}
,"accesses":{"driver":1}
,"problems":{"may":1,"occur":1}
,"occur":{"probing":1,"clock":1,"control":1}
,"process":{"require":1}
,"erify":{"driver":1,"names":1,"device-tree":1,"functions":1,"default":1,"control-register":1,"mode-specific":1}
,"inds":{"driver":1}
,".driver":{"={.name":1}
,"={.name":{"imx185":1}
,".owner":{"=this_module":1}
,"=this_module":{".of_match_table":1}
,".of_match_table":{"=of_match_ptr":1}
,"=of_match_ptr":{"(imx185":1}
,"_of_match)":{"erify":1}
,"parse_dt":{"function":1}
,"assigned":{"device":1}
,"describe":{"oftentim":1}
,"oftentim":{"regulator":1}
,"numbers":{"clock":1}
,"out-of-date":{"device":1}
,"causing":{"probi":1}
,"probi":{"fail":1}
,"fail":{"device":1}
,"compiler":{"(dtc)":1}
,"(dtc)":{"convert":1}
,".dtb":{"file":1}
,".dtsi":{"format":1}
,"ntent":{"ensure":1}
,"completion":{"ensure":1}
,"runs":{"completio":1}
,"completio":{"details":1}
,"ther":{"common":1}
,"problem":{"occurs":1,"values":1}
,"occurs":{"during":1}
,"correctl":{"control":1}
,"macros":{"updated":1}
,"rare":{"occasions":1}
,"occasions":{"ensure":1}
,"succeeds":{"problems":1}
,"control-register":{"values":1}
,"correct":{"ensure":1,"register":1,"double-check":1,"orde":1}
,"-register":{"setup":1}
,"formats":{"according":1}
,"_gain":{"(to_gain":1}
,"(to_gain":{"function":1}
,"mode-specific":{"settings":1}
,"double-check":{"mode-specifi":1}
,"mode-specifi":{"settings":1}
,"cause":{"sensor":1}
,"timeout":{"due":1}
,"wrong":{"value":1}
,"conf":{"iguration":1}
,"iguration":{"tegra_sinterface":1}
,"nning":{"continuous":1}
,"continuous":{"clock":1}
,"(free":{"running)":1}
,"running)":{"discontinuous":1}
,"(gated)":{"unsure":1}
,"unsure":{"first":1}
,"sure":{"isp":1}
,"fast":{"enough":1}
,"enough":{"ocess":1}
,"ocess":{"data":1}
,"working":{"properly":1}
,"closely":{"examine":1}
,"logs":{"i2c":1}
,"errors":{"camera":1}
,"error":{"check":1}
,"orde":{"enabling":1}
,"comply":{"sensor":1}
,"reside":{"separ":1}
,"separ":{"ate":1}
,"ate":{"header":1}
,"header":{"file":1,"mode":1}
,"sensor_mode_tbls.h":{"included":1}
,"included":{"main":1}
,"reg_8":{"reg_16":1}
,"reg_16":{"address-value":1}
,"address-value":{"pairs":1}
,"separated":{"resolution":1}
,"resolution":{"start":1}
,"start":{"stop":1,"stream-register":1}
,"stop":{"stream-register":1}
,"stream-register":{"values":1}
,"separate":{"mode":1,"delete":1,"stream-on":1}
,"delete":{"start":1}
,"end":{"resoluti":1,"header":1}
,"resoluti":{"mode":1}
,"_reg":{"imx185":1,"tp_colorbars":1,"*mode_table":1,"mode_#":1}
,"_start":{"={{0x3000":1}
,"={{0x3000":{"0x00":1,"0x01":1}
,"0x00":{"{imx185_table_wait_ms":1,"static":1,"table":1,"\u002F*your":1,"create":1}
,"{imx185_table_wait_ms":{"imx185_wait_ms_start}":1,"imx185_wait_ms_stream}":1,"imx185_wait_ms_stop}":1}
,"imx185_wait_ms_start}":{"{0x3002":1}
,"{0x3002":{"0x00}":1}
,"0x00}":{"{0x3049":1}
,"{0x3049":{"0x02}":1}
,"0x02}":{"{imx185_table_wait_ms":1}
,"imx185_wait_ms_stream}":{"{imx185_table_end":1}
,"{imx185_table_end":{"0x00":1}
,"_stop":{"={{0x3000":1}
,"0x01":{"{imx185_table_wait_ms":1}
,"imx185_wait_ms_stop}":{"{imx185_table_end":1}
,"color":{"bars":1}
,"bars":{"test":1}
,"patte":{"used":1}
,"activating":{"test-pattern":1}
,"test-pattern":{"mode":1}
,"tes":{"pattern":1}
,"tp_colorbars":{"end":1}
,"enumeration":{"mode":1,"table":1,"list":1}
,"ist":{"maps":1}
,"maps":{"enumeration":1}
,"enum":{"{imx185":1,"imx185":1}
,"{imx185":{"_mode_1920x1080_crop_30fps":1,"_table_end":1}
,"_mode_1920x1080_crop_30fps":{"static":1,"=imx185_1920x1080_crop_30fps":1}
,"oimx185":{"_reg":1}
,"*mode_table":{"={[imx185":1,"[imx185":1}
,"={[imx185":{"_mode_1920x1080_crop_30fps":1}
,"=imx185_1920x1080_crop_30fps":{"camera_common_frmfmt":1}
,"camera_common_frmfmt":{"array":1,"imx185":1}
,"array":{"list":1,"mode":1,"following":1,"static":1}
,"elements":{"list":1}
,"resolutions":{"is_hdr":1}
,"is_hdr":{"flag":1}
,"={{{1920":{"1080":1}
,"imx185_mode_1920x1080_crop_30fps":{"add":1}
,"stream-on":{"stream-off":1}
,"stream-off":{"mode":1}
,"xist":{"omit":1}
,"omit":{"mode":1}
,"structu":{"initialize":1}
,"res":{"olution":1}
,"olution":{"part":1}
,"mode_#":{"={{0x3000":1}
,"\u002F*your":{"addr":1}
,"*\u002F}":{"mode":1}
,"place":{"table":1}
,"_table_end":{"0x00":1}
,"enumeratio":{"add":1}
,"_mode_#":{"static":1,"=mode_#":1}
,"[imx185":{"_mode_#":1}
,"=mode_#":{"add":1}
,"camera_common":{"frmfmt":1}
,"{{#":{"imx185":1}
}
;Search.control.loadWordPairs(pairs);
