var pairs =
{
"flashing":{"booting":1,"tools":1,"port":1,"board":1}
,"booting":{"arget":1,"script":1}
,"arget":{"device":1}
,"device":{"flash.sh":1,"mode":1,"connected":1,"enumerates":1,"reset\u002Frecovery":1,"(such":1,"tree":1,"<flashapp>":1}
,"flash.sh":{"helper":1,"script":1,"(using":1,"change":1}
,"helper":{"script":1}
,"script":{"flash":1,"top-level":1,"sup":1,"follows":1,"usage":1,"included":1,"file":1,"adds":1,"<size-in-bytes>":1}
,"flash":{"board":1,"root":1,"using":1,"boot":1,"read":1,"file":1,"clone":1,"new":1,"script":1,"application":1,"larger":1}
,"board":{"boot":1,"hold":1,"(jetson-tx2":1,"filesystem":1,"flashed":1,"image":1,"default":1,"following":1,"creates":1,"verify":1}
,"boot":{"loader":1,"nfs":1,"configuration":1,"partition":1,"script":1}
,"loader":{"kernel":1,"plus":1,"fastboot.bin":1}
,"kernel":{"optionally":1,"kernel":1,"image":1,"modules":1,"put":1,"command":1,"as-is":1,"partition":1,"command-line":1}
,"optionally":{"flash":1,"specifies":1}
,"root":{"file":1}
,"file":{"system":1,"ystem":1,"<cfg":1,"<dtb_file":1,"ins":1,"u-boot":1,"null":1,"name":1,"used":1,"missing":1,"directory":1,"different":1,"producing":1}
,"system":{"inter":1,"download":1,"nv_tegra":1,"sudo":1,"located":1,"jetson":1,"usb":1,"card":1,"gold":1,"suggested":1}
,"inter":{"nal":1}
,"nal":{"emmc":1}
,"emmc":{"begin":1,"execute":1,"mmcblk1p1":1,"size":1,"boot":1}
,"begin":{"following":1}
,"following":{"directories":1,"command":1,"commands":1,"table":1,"mmcblk0p1":1}
,"directories":{"present":1}
,"present":{"bootloader":1}
,"bootloader":{"oot":1,"updated":1}
,"oot":{"loader":1}
,"plus":{"flashing":1,"<rootfs":1}
,"tools":{"nvflash":1}
,"nvflash":{"cfg":1,"boot":1,"configuration":1,"tegra-rcm":1}
,"cfg":{"bct":1}
,"bct":{"kernel":1}
,"image":{"\u002Fvmlinux.uimg":1,"copy":1,"app":1,"gold":1,"zimage":1}
,"\u002Fvmlinux.uimg":{"dtb":1}
,"dtb":{"files":1}
,"files":{"kernel":1}
,"modules":{"rootfs":1}
,"rootfs":{"root":1,"directory":1,"size":1,"partition":1}
,"download":{"directory":1}
,"directory":{"starts":1,"release":1,"new":1,"following":1,"<nfsroot>":1,"\u002Fusr\u002Flib\u002Fxorg\u002Fmodules\u002Fdrivers\u002Fnvidia_drv.so":1}
,"starts":{"empty":1}
,"empty":{"populate":1}
,"populate":{"sample":1}
,"sample":{"file":1,"applications":1,"rootfs":1}
,"nv_tegra":{"nvidia":1}
,"nvidia":{"tegra":1}
,"tegra":{"user":1}
,"user":{"space":1,"kernel":1}
,"space":{"binaries":1}
,"binaries":{"sample":1}
,"applications":{"additionally":1}
,"additionally":{"runn":1}
,"runn":{"ing":1}
,"ing":{"commands":1}
,"commands":{"usb":1,"flash":1,"copy":1,"determine":1}
,"usb":{"cable":1,"usb":1,"device":1,"disk":1,"memory":1,"ethernet":1,"instance":1,"port":1}
,"cable":{"connected":1}
,"connected":{"recovery":1,"device":1,"integer":1}
,"recovery":{"port":1,"utton":1}
,"port":{"flash":1,"operates":1,"path":1}
,"using":{"usb":1,"following":1}
,"mode":{"default":1,"details":1,"power":1}
,"default":{"configuration":1,"relea":1,"release":1,"<emmc_file":1,"<kernel>":1,"<target_board>":1}
,"configuration":{"scri":1,"table":1,"file":1}
,"scri":{"associated":1}
,"associated":{"readme":1}
,"readme":{"describes":1}
,"describes":{"flashing":1}
,"operates":{"device":1}
,"details":{"quick":1}
,"quick":{"start":1}
,"start":{"guide":1,"address":1}
,"guide":{"flash":1}
,"put":{"target":1,"device":1}
,"target":{"reset\u002Frecovery":1,"board":1,"device":1,"evice":1}
,"reset\u002Frecovery":{"mode":1}
,"power":{"carrier":1}
,"carrier":{"board":1}
,"hold":{"recovery":1}
,"utton":{"press":1}
,"press":{"reset":1}
,"reset":{"button":1}
,"button":{"run":1,"execute":1}
,"run":{"flash.sh":1}
,"top-level":{"directory":1}
,"release":{"script":1,"images":1,"example":1}
,"sup":{"plied":1}
,"plied":{"target":1}
,"(jetson-tx2":{"jetson-tx1":1}
,"jetson-tx1":{"root":1,"mmcblk0p1":1,"<rootdev>":1}
,"sudo":{".\u002Fflash.sh":1,"clone.img":1}
,".\u002Fflash.sh":{"<platform":1,"jetson-tx":1,"jetson-tx2":1,"app":1,"jetson-tx1":1,"<ip-addr-of-linux-host>":1,"[options]":1,"<size>":1}
,"<platform":{"<rootdev>":1,"specifies":1}
,"<rootdev>":{"<rootdev>":1,"depends":1,"specify":1,"specifies":1,"<size>":1,"rootfs":1}
,"depends":{"root":1}
,"located":{"root":1}
,"jetson":{"tx2":1}
,"tx2":{"internal":1,"sudo":1,"\u002Ftx1":1}
,"internal":{"emmc":1,"rootdev":1,"memory":1}
,"execute":{"script":1,"command":1,"following":1}
,"follows":{"sudo":1}
,"jetson-tx":{"mmcblk0p1":1}
,"mmcblk0p1":{"root":1,"tx1":1,"creates":1,"opitonally":1,"ram":1,"specifies":1,"determining":1}
,"disk":{"exe":1}
,"exe":{"cute":1}
,"cute":{"script":1}
,"jetson-tx2":{"sda1":1,"mmcblk1p1":1,"mmcblk0p1":1,"eth0":1,"jetson-tx1":1}
,"sda1":{"-if":1,"root":1,"specifies":1}
,"-if":{"sata":1}
,"sata":{"device":1}
,"enumerates":{"sda1":1}
,"card":{"exe":1}
,"mmcblk1p1":{"clone":1,"specifies":1}
,"clone":{"tx1\u002Ftx2":1,".img":1,"image":1}
,"tx1\u002Ftx2":{"flash":1}
,"read":{"system.img":1,"driver":1}
,"system.img":{"gold":1,"--bup":1}
,"gold":{"board":1}
,"filesystem":{"partition":1}
,"partition":{"following":1,"updated":1,"size":1,"root":1,"execute":1,"8589934592":1,"<rootdev>":1,"internal":1}
,"command":{"tx2":1,"sudo":1,"line":1,"$sudo":1,"booted":1}
,"app":{"clone.img":1,"partition":1,"jetson-tx2":1,"jetson-tx1":1}
,"clone.img":{"jetson-tx2":1,"jetson-tx1":1,"clone":1,".raw":1}
,"tx1":{"sudo":1}
,"creates":{"clone.img":1,"system.img":1}
,".img":{".raw":1}
,".raw":{"<top>":1,"<l4t>\u002Fbootloader\u002Fsystem.img":1,"bootloader\u002Fsystem.img":1}
,"<top>":{"directory":1}
,"new":{"board":1,"file":1}
,"flashed":{"default":1}
,"relea":{"images":1}
,"images":{"following":1,"except":1}
,"copy":{"clone.img":1}
,"<l4t>\u002Fbootloader\u002Fsystem.img":{"directory":1}
,"bootloader\u002Fsystem.img":{"flash":1}
,"opitonally":{"instead":1}
,"instead":{"step":1}
,"step":{"flash":1}
,"except":{"file":1,"physically":1}
,"ystem":{"image":1}
,"ram":{"boot":1}
,"nfs":{"put":1,"network":1,"booting":1,"bootin":1}
,"<ip-addr-of-linux-host>":{":\u002F<path-to-nfs-rootfs>":1}
,":\u002F<path-to-nfs-rootfs>":{"--rc":1}
,"--rc":{"m-boot":1}
,"m-boot":{"jetson-tx2":1}
,"eth0":{"flash":1,"specifies":1}
,"usage":{"locate":1,"information":1,"follows":1}
,"locate":{"up-to-date":1}
,"up-to-date":{"usage":1}
,"information":{"nning":1,"<bct":1}
,"nning":{"flash.sh":1}
,"(using":{"flash.sh":1}
,"included":{"release)":1}
,"release)":{"basic":1}
,"basic":{"usage":1}
,"[options]":{"<platform":1}
,"specify":{"required":1}
,"required":{"parameters":1}
,"parameters":{"options":1,"description":1}
,"options":{"following":1,"description":1}
,"table":{"parameters":1,"(bc":1}
,"description":{"<platform":1,"specifies":1}
,"specifies":{"platform":1,"following":1,"internal":1,"external":1,"nfsroot":1,"print":1,"nvflash":1,"device":1,"emmc":1,"ath":1,"pass":1,"kernel":1,"static":1,"odm":1,"skip":1,"boot":1,"lash":1,"initrd":1,"full":1,"sum":1,"sample":1,"rootfs":1,"usb":1}
,"platform":{"name":1,"gigabytes":1}
,"name":{"release":1,"valid":1,"typical":1}
,"example":{"jetson-tx2":1,"<my":1,"1gib":1}
,"external":{"sdcard":1,"usb":1}
,"sdcard":{"sda1":1}
,"(such":{"usb":1}
,"memory":{"stick":1,"partition":1,"exam":1}
,"stick":{"hdd)":1}
,"hdd)":{"eth0":1}
,"nfsroot":{"via":1,"example":1}
,"via":{"external":1}
,"ethernet":{"interf":1}
,"interf":{"ace":1}
,"ace":{"options":1}
,"print":{"usage":1}
,"<bct":{"_file>":1}
,"_file>":{"specifies":1}
,"(bc":{"file":1}
,"<cfg":{"_file>":1}
,"<dtb_file":{"optionally":1}
,"tree":{"file":1}
,"ins":{"tead":1}
,"tead":{"default":1}
,"<emmc_file":{"specifies":1}
,"size":{"target":1,"specifies":1,"ppt":1,"bytes":1,"jetson":1,"flash":1,"partition":1}
,"<flashapp>":{"specifies":1}
,"ath":{"flash":1}
,"application":{"nvflash":1}
,"tegra-rcm":{"specifies":1}
,"pass":{"user":1}
,"line":{"kernel":1,"warning":1}
,"as-is":{"<partition":1}
,"<partition":{"id>":1}
,"id>":{"specifies":1}
,"updated":{"inimum":1,"payload":1}
,"inimum":{"=5)":1}
,"=5)":{"<nfs":1}
,"<nfs":{"args>":1}
,"args>":{"specifies":1}
,"static":{"nfs":1}
,"network":{"assignments":1}
,"assignments":{"<client":1}
,"<client":{"ip>":1}
,"ip>":{"<server":1,"<gateway":1,"<netmask>":1}
,"<server":{"ip>":1}
,"<gateway":{"ip>":1}
,"<netmask>":{"<odmdata>":1}
,"<odmdata>":{"specifies":1}
,"odm":{"data":1}
,"data":{"value":1}
,"value":{"total":1}
,"total":{"emmc":1}
,"skip":{"building":1}
,"building":{"reuse":1,"multi-spec":1}
,"reuse":{"existing":1}
,"existing":{"system.i":1,"file":1}
,"system.i":{"<ubootscript>":1}
,"<ubootscript>":{"specifies":1}
,"u-boot":{"<cmdline>":1,"--no-flash":1}
,"<cmdline>":{"specifies":1}
,"warning":{"option":1}
,"option":{"kernel":1,"fastboot":1,"omitted":1,"increasing":1}
,"command-line":{"gets":1}
,"gets":{"highe":1}
,"highe":{"precedence":1}
,"precedence":{"option":1}
,"fastboot":{"case":1}
,"case":{"nfs":1}
,"adds":{"nfs":1}
,"bootin":{"related":1}
,"related":{"arguments":1}
,"arguments":{"option":1}
,"omitted":{"<flasher>":1}
,"<flasher>":{"specifies":1}
,"lash":{"server":1}
,"server":{"fastboot.bin":1}
,"fastboot.bin":{"<initrd>":1,"u-boot.bin":1}
,"<initrd>":{"specifies":1}
,"initrd":{"file":1,"default":1}
,"null":{"initrd":1}
,"<kernel>":{"specifies":1}
,"zimage":{"<bootloader>":1}
,"<bootloader>":{"specifies":1}
,"full":{"path":1}
,"path":{"boot":1,"(3-14)":1}
,"u-boot.bin":{"<end_of_ppt_plus_1>":1}
,"<end_of_ppt_plus_1>":{"specifies":1}
,"sum":{"primary":1}
,"primary":{"gpt":1}
,"gpt":{"start":1}
,"address":{"size":1}
,"ppt":{"plus":1}
,"<rootfs":{"_dir>":1}
,"_dir>":{"specifies":1}
,"<nfsroot>":{"specifies":1}
,"<my":{"addr>":1}
,"addr>":{":\u002Fmy\u002Fexported\u002Fnfs\u002Frootfs":1}
,":\u002Fmy\u002Fexported\u002Fnfs\u002Frootfs":{"<size>":1}
,"<size>":{"specifies":1,"<platform":1,"desired":1}
,"bytes":{"valid":1,"<its_file":1}
,"valid":{"internal":1,"u-boot":1}
,"rootdev":{"kib":1}
,"kib":{"mib":1}
,"mib":{"gib":1}
,"gib":{"style":1}
,"style":{"shorthand":1}
,"shorthand":{"allowed":1}
,"allowed":{"example":1}
,"1gib":{"signifies":1}
,"signifies":{"1024":1}
,"1024":{"*1024":1}
,"*1024":{"*1024":1,"bytes":1}
,"<its_file":{"file":1}
,"--no-flash":{"performs":1}
,"performs":{"steps":1}
,"steps":{"except":1}
,"physically":{"flashing":1}
,"--bup":{"generates":1}
,"generates":{"bootloader":1}
,"payload":{"(bup)":1}
,"(bup)":{"--multi-spec":1}
,"--multi-spec":{"enables":1}
,"enables":{"support":1}
,"support":{"building":1}
,"multi-spec":{"bup":1,"enable":1}
,"bup":{"--clean-up":1,"buffer":1}
,"--clean-up":{"cleans":1}
,"cleans":{"bup":1}
,"buffer":{"multi-spec":1}
,"enable":{"--usb-instance":1}
,"--usb-instance":{"specifies":1}
,"instance":{"connected":1}
,"integer":{"bus\u002Fdev":1}
,"bus\u002Fdev":{"(003\u002F091)":1}
,"(003\u002F091)":{"usb":1}
,"(3-14)":{"best":1}
,"best":{"option":1}
,"increasing":{"internal":1}
,"suggested":{"rootfs":1}
,"\u002Ftx1":{"platform":1}
,"gigabytes":{"(gb)":1}
,"(gb)":{"specified":1}
,"specified":{"default":1}
,"<target_board>":{".conf":1}
,".conf":{"file":1}
,"used":{"flash.sh":1}
,"<size-in-bytes>":{"argument":1}
,"argument":{"flash.sh":1}
,"change":{"partition":1}
,"larger":{"partition":1}
,"$sudo":{".\u002Fflash.sh":1}
,"desired":{"size":1}
,"8589934592":{"(or":1}
,"(or":{"gib)":1}
,"gib)":{"want":1}
,"want":{"decrease":1}
,"decrease":{"size":1}
,"exam":{"ple":1}
,"ple":{"mmcblk0p1":1}
,"determining":{"success":1}
,"success":{"driver":1,"failure":1,"message":1}
,"driver":{"update":1}
,"update":{"updating":1,"completed":1,"using":1,"execute":1,"succeeded":1,"fails":1}
,"updating":{"drivers":1}
,"drivers":{"target":1}
,"verify":{"hat":1}
,"hat":{"update":1}
,"completed":{"successfully":1}
,"successfully":{"det":1}
,"det":{"ermine":1}
,"ermine":{"success":1}
,"failure":{"driver":1}
,"determine":{"success":1}
,"booted":{"target":1}
,"evice":{"$sha1sum":1}
,"$sha1sum":{"\u002Fetc\u002Fnv_tegra_release":1}
,"\u002Fetc\u002Fnv_tegra_release":{"driver":1}
,"succeeded":{"output":1}
,"output":{"displays":1}
,"displays":{"word":1}
,"word":{"file":1}
,"typical":{"success":1,"error":1}
,"message":{"oks":1,"looks":1}
,"oks":{"\u002Fusr\u002Flib\u002Fxorg\u002Fmodules\u002Fdrivers\u002Fnvidia_drv.so":1}
,"\u002Fusr\u002Flib\u002Fxorg\u002Fmodules\u002Fdrivers\u002Fnvidia_drv.so":{"driver":1,"faile":1}
,"fails":{"file":1,"new":1}
,"missing":{"typical":1}
,"error":{"message":1,"\u002Fusr\u002Flib\u002Fxorg\u002Fmodules\u002Fdrivers\u002Fnvidia_drv.so":1}
,"looks":{"sha1sum":1}
,"sha1sum":{"\u002Fusr\u002Flib\u002Fxorg\u002Fmodules\u002Fdrivers\u002Fnvidia_drv":1}
,"\u002Fusr\u002Flib\u002Fxorg\u002Fmodules\u002Fdrivers\u002Fnvidia_drv":{"file":1}
,"faile":{"open":1}
,"open":{"read":1}
,"different":{"existing":1}
,"producing":{"error":1}
}
;Search.control.loadWordPairs(pairs);
