var pairs =
{
"bsp":{"customization":1,"version":1}
,"customization":{"customize":1}
,"customize":{"nvidia":1}
,"nvidia":{"tegra":1,"jetpack":1,"t-boot":1,"pass":1,"hange":1,"packages":1,"bug":1,"whether":1}
,"tegra":{"linux":1,"package":1,"device":1,"x1\u002Fx":1,"<186":1}
,"linux":{"driver":1,"tegra":1,"host":1,"kernel":1,"ost":1,"tegra-ubuntu":1}
,"driver":{"package":1}
,"package":{"(l4t":1,"configure":1,"procedures":1,"commands":1,"tract":1,"extract":1,"man":1,"configured":1,"updates":1,"list":1,"com":1}
,"(l4t":{"manually":1}
,"manually":{"configuring":1}
,"configuring":{"ting":1,"nfs":1}
,"ting":{"software":1}
,"software":{"drivers":1,"prerequisites":1}
,"drivers":{"llow":1}
,"llow":{"ing":1}
,"ing":{"jetpack":1}
,"jetpack":{"perform":1,"performs":1,"skip":1,"documentat":1}
,"perform":{"standard":1}
,"standard":{"setup":1}
,"setup":{"note":1}
,"note":{"nvidia":1,"ensure":1,"executing":1}
,"performs":{"following":1}
,"following":{"install":1,"hardware":1,"file":1,"line":1,"command":1,"step":1,"(release)":1,"version":1,"linux":1,"information":1}
,"install":{"linux":1,"additional":1,"package":1,"packages":1,"wget":1,"nfs":1,"nfs-common":1}
,"configure":{"flash":1,"nfs":1}
,"flash":{"tegra":1}
,"device":{"run":1,"rough":1,"verify":1,"nfs":1,"$mkdir":1,"sure":1}
,"run":{"samples":1,"sudo":1}
,"samples":{"installed":1}
,"installed":{"using":1,"ckages":1}
,"using":{"jetpack":1,"provided":1,"apt-get":1,"flags":1}
,"skip":{"topics":1}
,"topics":{"information":1}
,"information":{"jetpack":1,"specified":1,"procedures":1,"determine":1,"chipid=0x18":1}
,"documentat":{"ion":1}
,"ion":{"boot":1,"command":1}
,"boot":{"options":1,"loader":1,"l4t":1,"target":1,"verify":1,"configuration":1}
,"options":{"oot":1,"include":1}
,"oot":{"l4t":1,"network":1,"target":1}
,"l4t":{"jetson":1,"linux":1,"contains":1,"reference":1,"package":1,"tested":1}
,"jetson":{"reference":1,"tx1\u002Ftx":1}
,"reference":{"board":1}
,"board":{"root":1,"requires":1,"linux":1,"usb\u002Fsd\u002Finternal":1,"186":1,"xecute":1,"execute":1}
,"root":{"file":1,"filesystem":1,"linux":1,"mount":1,"point":1,"access":1}
,"file":{"system":1,"\u002Fetc\u002Fapt\u002Fsources.list":1,"modify":1,"communicat":1,"bug":1,"reporting":1}
,"system":{"(rootfs)":1,"(nfs)":1,"prerequisites":1,"following":1,"intend":1,"network-accessible":1,"l4t":1,"ubuntu":1,"$sudo":1,"nfsroot":1,"configured":1,"running":1}
,"(rootfs)":{"integrated":1}
,"integrated":{"attached":1}
,"attached":{"network-accessible":1}
,"network-accessible":{"storag":1,"server":1}
,"storag":{"boot":1}
,"loader":{"loaded":1,"flashing":1,"combination":1}
,"loaded":{"internal":1}
,"internal":{"emmc":1}
,"emmc":{"root":1,"network":1,"possible":1}
,"filesystem":{"options":1}
,"include":{"usb":1,"option":1}
,"usb":{"stick":1,"hard":1,"cable":1,"ethernet":1}
,"stick":{"(formatted":1}
,"(formatted":{"ext4)":1}
,"ext4)":{"usb":1,"card":1,"sata":1,"internal":1}
,"hard":{"disk":1}
,"disk":{"(formatted":1}
,"card":{"(formatted":1}
,"sata":{"(formated":1}
,"(formated":{"ext4)":1}
,"network":{"file":1}
,"(nfs)":{"linux":1}
,"host":{"system":1,"running":1,"boot":1,"install":1,"machine":1,"nfs":1,"configuration":1}
,"prerequisites":{"l4t":1,"met":1,"ethernet":1}
,"hardware":{"software":1}
,"met":{"host":1}
,"running":{"linux":1,"determine":1}
,"kernel":{"image":1,"version":1,"directory":1,"vers":1,"build":1}
,"image":{"(image":1,"alternatively":1,"source":1}
,"(image":{"l4t":1}
,"contains":{"kernel":1}
,"alternatively":{"download":1,"export":1}
,"download":{"rebuild":1}
,"rebuild":{"kernel":1}
,"source":{"boot":1}
,"flashing":{"tegra":1,"booting":1,"configuration":1}
,"x1\u002Fx":{"series":1}
,"series":{"jetson":1}
,"tx1\u002Ftx":{"developer":1}
,"developer":{"board":1}
,"requires":{"boot":1}
,"combination":{"nvidia":1}
,"t-boot":{"(nvtboot)":1}
,"(nvtboot)":{"oot":1}
,"intend":{"boot":1}
,"server":{"usb":1,"know":1}
,"cable":{"plug":1,"device":1}
,"plug":{"recovery":1}
,"recovery":{"port":1}
,"port":{"extracting":1,"ailable":1}
,"extracting":{"tegra":1}
,"procedures":{"extract":1,"determine":1,"located":1}
,"extract":{"l4t":1,"package":1}
,"commands":{"examples":1,"install":1}
,"examples":{"assume":1}
,"assume":{"extracted":1}
,"extracted":{"release":1}
,"release":{"package":1,"full":1,"install":1,"nvidia-bug-report-tegra.sh":1}
,"tract":{"tegra":1}
,"man":{"ually":1}
,"ually":{"executing":1}
,"executing":{"command":1,"$sudo":1,"following":1,"mount":1}
,"command":{"$sudo":1,"un-exports":1,"proves":1,"target":1,"head":1,"kernel":1,"linux":1}
,"$sudo":{"tar":1,"apt-get":1,"\u002Fetc\u002Finit.d\u002Fnfs-kernel-server":1,"mkdir":1,"*\u002Fnfsroot":1,"exportfs":1,"ufw":1,"mount":1,"\u002Fusr\u002Fbin\u002Fnvidia-bug-report-tegra.sh":1}
,"tar":{"-vxjf":1}
,"-vxjf":{"tegra":1}
,"<186":{"210>":1}
,"210>":{">_linux_r":1}
,">_linux_r":{"<release_num":1}
,"<release_num":{"_<release_type":1}
,"_<release_type":{".tbz2":1}
,".tbz2":{"login":1}
,"login":{"credentials":1,"security":1}
,"credentials":{"default":1,"username":1}
,"default":{"login":1,"password":1,"kernel":1,"logfile":1}
,"username":{"nvidia":1}
,"pass":{"word":1}
,"word":{"nvidia":1}
,"hange":{"default":1}
,"password":{"ensure":1}
,"ensure":{"login":1,"run":1}
,"security":{"installing":1}
,"installing":{"additional":1}
,"additional":{"packages":1,"nvidia":1}
,"packages":{"comes":1,"includin":1,"ubuntu":1,"may":1,"directly":1,"periodic":1,"oot":1,"using":1,"hos":1}
,"comes":{"additional":1}
,"includin":{"packages":1}
,"ubuntu":{"google":1,"using":1,"packages":1,"package":1,"add":1}
,"google":{"chrome":1}
,"chrome":{"dditional":1}
,"dditional":{"nvidia":1}
,"may":{"posted":1}
,"posted":{"alongside":1}
,"alongside":{"release":1}
,"full":{"features":1}
,"features":{"release":1}
,"directly":{"apply_binaries":1}
,"apply_binaries":{"install":1}
,"configured":{"rootfs":1,"properly":1}
,"rootfs":{"nstall":1,"based":1,"$sudo":1}
,"nstall":{"additional":1}
,"provided":{"sample":1}
,"sample":{"file":1}
,"tested":{"provided":1}
,"periodic":{"ubuntu":1}
,"updates":{"canonical":1}
,"canonical":{"validated":1}
,"validated":{"receive":1}
,"receive":{"notifications":1}
,"notifications":{"locate":1}
,"locate":{"edit":1}
,"edit":{"following":1}
,"\u002Fetc\u002Fapt\u002Fsources.list":{"add":1}
,"add":{"following":1,"line":1}
,"line":{"deb":1}
,"deb":{"http:\u002F\u002Fports.ubuntu.com\u002Fubuntu-ports":1}
,"http:\u002F\u002Fports.ubuntu.com\u002Fubuntu-ports":{"<os":1,"xenial":1}
,"<os":{"version":1}
,"version":{"(target)":1,"platform":1,"kern":1,"execute":1,"patchlevel":1}
,"(target)":{">-updates":1}
,">-updates":{"main":1}
,"main":{"universe":1}
,"universe":{"example":1,"prerequisite":1}
,"example":{"rootfs":1,"install":1,"jetson-tx2.conf":1}
,"based":{"xenial":1}
,"xenial":{"xerus":1,"-updates":1}
,"xerus":{"distribution":1}
,"distribution":{"ubuntu":1}
,"-updates":{"main":1}
,"prerequisite":{"attach":1}
,"attach":{"ethernet":1,"log":1}
,"ethernet":{"cable":1,"port":1,"adapter":1,"connection":1}
,"rough":{"either":1}
,"either":{"ethernet":1}
,"ailable":{"usb":1}
,"adapter":{"install":1}
,"target":{"device":1,"configure":1,"board":1,"ystem":1,"nfs":1}
,"verify":{"ethernet":1,"everything":1}
,"connection":{"update":1,"install":1,"target":1}
,"update":{"package":1,"note":1,"t-get":1}
,"list":{"executing":1}
,"apt-get":{"update":1,"example":1,"install":1}
,"sudo":{"apt-get":1}
,"t-get":{"upgrade":1}
,"upgrade":{"upgrades":1}
,"upgrades":{"already":1}
,"already":{"installed":1}
,"ckages":{"confuse":1}
,"confuse":{"two":1}
,"two":{"commands":1}
,"wget":{"execute":1,"configuring":1}
,"execute":{"command":1}
,"nfs":{"root":1,"provide":1,"components":1,"server":1,"boot":1}
,"provide":{"nfs":1}
,"mount":{"point":1,"host":1,"nfsvers=3":1,"command":1}
,"point":{"linux":1,"$sudo":1,"target":1,"flashing":1,"determining":1}
,"ost":{"system":1}
,"hos":{"ethernet":1}
,"components":{"host":1}
,"machine":{"$sudo":1,"taken":1}
,"nfs-common":{"nfs-kernel-serve":1,"package":1,"boot":1}
,"nfs-kernel-serve":{"nfs":1}
,"know":{"directories":1}
,"directories":{"want":1,"using":1}
,"want":{"export":1}
,"export":{"clients":1,"root":1,"-export":1}
,"clients":{"information":1}
,"specified":{"\u002Fetc\u002Fexports":1}
,"\u002Fetc\u002Fexports":{"file":1,"look":1}
,"modify":{"\u002Fetc\u002Fexports":1}
,"look":{"somewhat":1}
,"somewhat":{"$\u002Fnfsroot":1}
,"$\u002Fnfsroot":{"*(rw":1}
,"*(rw":{"nohide":1}
,"nohide":{"insecure":1}
,"insecure":{"no_subtree_check":1}
,"no_subtree_check":{"sync":1}
,"sync":{"no_root_squash)":1}
,"no_root_squash)":{"adding":1}
,"adding":{"entry":1}
,"entry":{"estart":1}
,"estart":{"command":1}
,"\u002Fetc\u002Finit.d\u002Fnfs-kernel-server":{"restart":1}
,"restart":{"create":1}
,"create":{"\u002Fnfsroot":1}
,"\u002Fnfsroot":{"directory":1,"copy":1}
,"directory":{"linux":1,"$cd":1,"head":1}
,"mkdir":{"\u002Fnfsroot":1}
,"copy":{"file":1}
,"nfsroot":{"directory":1}
,"$cd":{".\u002Frootfs":1}
,".\u002Frootfs":{"$sudo":1}
,"*\u002Fnfsroot":{"export":1}
,"exportfs":{"alternatively":1,"-au":1}
,"-export":{"directories":1}
,"flags":{"following":1}
,"un-exports":{"direc":1}
,"direc":{"tories":1}
,"tories":{"$sudo":1}
,"-au":{"optionally":1}
,"optionally":{"buntu":1}
,"buntu":{"firewall":1}
,"firewall":{"block":1}
,"block":{"nfs":1}
,"access":{"disabled":1}
,"disabled":{"depending":1}
,"depending":{"configuration":1}
,"configuration":{"following":1,"correc":1,"boot":1,"present":1,"example":1,"follows":1}
,"ufw":{"disable":1}
,"disable":{"ssues":1}
,"ssues":{"performing":1}
,"performing":{"nfs":1}
,"everything":{"host":1}
,"properly":{"executing":1}
,"step":{"booted":1}
,"booted":{"target":1}
,"usb\u002Fsd\u002Finternal":{"emmc":1}
,"possible":{"mount":1}
,"$mkdir":{"rootfs":1}
,"nfsvers=3":{"<ip-addr>":1}
,"<ip-addr>":{":\u002Fnfsroot":1,"address":1}
,":\u002Fnfsroot":{"otfs":1}
,"otfs":{"<ip-addr>":1}
,"address":{"linux":1}
,"taken":{"ifconfig":1}
,"ifconfig":{"command":1}
,"proves":{"host":1}
,"correc":{"note":1}
,"ystem":{"install":1}
,"com":{"mand":1}
,"mand":{"$sudo":1}
,"booting":{"target":1}
,"sure":{"include":1}
,"option":{"nfs":1}
,"determining":{"version":1}
,"platform":{"information":1,"formation":1}
,"determine":{"lashed":1,"bsp":1,"kernel":1,"boot":1}
,"lashed":{"bsp":1}
,"kern":{"version":1}
,"formation":{"execute":1}
,"head":{"\u002Fetc\u002Fnv_tegra_release":1,"makefile":1}
,"\u002Fetc\u002Fnv_tegra_release":{"output":1}
,"output":{"similar":1}
,"similar":{"following":1}
,"(release)":{"revision":1}
,"revision":{"gcid":1}
,"gcid":{"10436258":1}
,"10436258":{"board":1}
,"186":{"ref":1}
,"ref":{"eabi":1}
,"eabi":{"aarch64":1}
,"aarch64":{"date":1,"aarch64":1,"nu\u002Flinux":1,"gnu\u002Flinux":1}
,"date":{"sat":1}
,"sat":{"feb":1}
,"feb":{":34":1,"19:21:29":1}
,":34":{"utc":1}
,"utc":{"201":1}
,"201":{"determine":1}
,"makefile":{"output":1}
,"patchlevel":{"sublevel":1}
,"sublevel":{"=15":1}
,"=15":{"system":1}
,"vers":{"ion":1}
,"tegra-ubuntu":{"4.4.38-tegra":1,"-tegra":1}
,"4.4.38-tegra":{"smp":1}
,"smp":{"preempt":1}
,"preempt":{"fri":1,"tue":1}
,"fri":{"feb":1}
,"19:21:29":{"pst":1}
,"pst":{"2018":1}
,"2018":{"aarch64":1}
,"nu\u002Flinux":{"output":1}
,"-tegra":{"smp":1}
,"tue":{"jun":1}
,"jun":{"16:29:05":1}
,"16:29:05":{"pdt":1}
,"pdt":{"2017":1}
,"2017":{"aarch64":1}
,"gnu\u002Flinux":{"determine":1}
,"present":{"flashing":1}
,"jetson-tx2.conf":{"provides":1}
,"provides":{"following":1}
,"chipid=0x18":{"emmc_cfg=flash_l4t_t186.xml":1}
,"emmc_cfg=flash_l4t_t186.xml":{"bootpartsize=8388608":1}
,"bootpartsize=8388608":{"emmcsize=31276924928":1}
,"emmcsize=31276924928":{"its_file=":1}
,"its_file=":{"sysbootfile=p2771-0000\u002Fextlinux.conf":1}
,"sysbootfile=p2771-0000\u002Fextlinux.conf":{"emmc_bct=p3310_a00_8gb_samsung_8gb_lpddr4_204mhz_a":1}
,"emmc_bct=p3310_a00_8gb_samsung_8gb_lpddr4_204mhz_a":{"02_l4t.cfg":1}
,"02_l4t.cfg":{"dtb_file=tegra186-quill-p3310-1000-a00-00-base.dtb":1}
,"dtb_file=tegra186-quill-p3310-1000-a00-00-base.dtb":{"tbcdtb_file=tegra186-quill-p3310-1000-a00-00-base":1}
,"tbcdtb_file=tegra186-quill-p3310-1000-a00-00-base":{"dtb":1}
,"dtb":{"default":1}
,"build":{"configuration":1}
,"follows":{"arch\u002Farm64\u002Fconfigs\u002Ftegra18":1}
,"arch\u002Farm64\u002Fconfigs\u002Ftegra18":{"_defconfig":1}
,"_defconfig":{"nvidia":1}
,"bug":{"reporting":1}
,"reporting":{"debugging":1,"log":1,"exte":1,"issues":1}
,"debugging":{"purposes":1}
,"purposes":{"attach":1}
,"log":{"file":1,"files":1,"target":1}
,"communicat":{"issues":1}
,"issues":{"found":1,"nvidia":1}
,"found":{"release":1}
,"nvidia-bug-report-tegra.sh":{"script":1}
,"script":{"generate":1}
,"generate":{"log":1}
,"files":{"generate":1}
,"xecute":{"command":1}
,"\u002Fusr\u002Fbin\u002Fnvidia-bug-report-tegra.sh":{"generate":1,"default":1}
,"exte":{"nded":1}
,"nded":{"logging":1}
,"logging":{"mode":1}
,"mode":{"log":1}
,"logfile":{"generated":1}
,"generated":{"procedures":1}
,"located":{"$home":1}
,"$home":{"\u002Fnvidia-bug-report-tegra.log":1}
,"\u002Fnvidia-bug-report-tegra.log":{"attach":1}
,"whether":{"email":1}
,"email":{"forums":1}
}
;Search.control.loadWordPairs(pairs);
