var pairs =
{
"tx1":{"software":1,"path":1}
,"software":{"features":1,"hardware":1}
,"features":{"nvidia":1,"provide":1,"boot":1,"lanes":1,"message":1,"dynamic":1,"include":1}
,"nvidia":{"tegra":1}
,"tegra":{"linux":1,"devices":1,"low":1,"tx1":1}
,"linux":{"driver":1,"targeted":1}
,"driver":{"package":1,"suspend\u002Fresume":1,"model":1,"provided":1,"release":1,"gyro":1}
,"package":{"supports":1,"bring":1}
,"supports":{"following":1,"gen2":1,"link":1,"egl":1}
,"following":{"softw":1,"opengl":1}
,"softw":{"features":1}
,"provide":{"users":1}
,"users":{"complete":1}
,"complete":{"package":1}
,"bring":{"linux":1}
,"targeted":{"nvidia":1}
,"devices":{"note":1,"ina":1,"usb0":1}
,"note":{"always":1,"media-controller":1,"gst-inspect-1.0":1}
,"always":{"check":1,"feature":1}
,"check":{"release":1}
,"release":{"notes":1,"soc_camera":1,"1.0.66":1,"consult":1,"supports":1}
,"notes":{"constraints":1,"nvboot":1,"aarch64":1,"dsi":1,"spi":1,"opengl":1,"egl":1,"h.264":1,"i420":1,"nvmm:i420":1}
,"constraints":{"related":1}
,"related":{"features":1}
,"boot":{"loaders":1,"loader":1,"device":1}
,"loaders":{"boot":1}
,"loader":{"feature":1,"version":1}
,"feature":{"notes":1,"tool":1,"device":1,"version":1,"details":1}
,"nvboot":{"boot":1}
,"device":{"emmc":1,"support":1,"life":1,"power":1,"need":1,"mode":1,"capabilities":1}
,"emmc":{"2nd":1,"u-boot":1,"(no":1}
,"2nd":{"stage":1}
,"stage":{"load":1}
,"load":{"device":1}
,"u-boot":{"storage":1,"kernel":1}
,"storage":{"device":1,"(usb0":1}
,"support":{"emmc":1,"i2c":1,"-dsi":1,"-hot-plug":1,"-ethernet":1,"(csi":1,"current":1,"baseboard":1,"sdmmc1":1,"cbs":1,"pio":1,"usb":1,"usb0":1,"usb1":1,"mass":1,"-uart":1,"role-based":1,"notes":1,"egl":1,"gstreamer":1,"af2.8":1,"auto":1}
,"(no":{"cq)":1}
,"cq)":{"card":1}
,"card":{"usb":1}
,"usb":{"(hs":1,"(hs)":1,"(device)":1,"2.0":1,"3.0":1,"2.0\u002F3.0":1,"video":1,"audio":1,"camera":1}
,"(hs":{"display":1,"-3.4mbps)":1}
,"display":{"console":1,"splash\u002Fmenu":1,"support":1,"-run":1,"-dual":1,"-hdmi":1,"without":1,"outputs":1}
,"console":{"uart":1}
,"uart":{"display":1,"i\u002Fo":1}
,"splash\u002Fmenu":{"uart":1}
,"i\u002Fo":{"bus":1,"i\u002Fo":1,"type":1}
,"bus":{"support":1,"speed":1,"clock":1,"clear":1}
,"i2c":{"usb":1,"gen1":1,"gen2":1,"gen3":1,"ddc":1,"pwr":1,"message":1,"bus":1}
,"(hs)":{"usb":1}
,"(device)":{"toolchain":1}
,"toolchain":{"feature":1}
,"tool":{"chains":1}
,"chains":{"notes":1}
,"aarch64":{"gcc-4.8.2-glibc-2.17":1}
,"gcc-4.8.2-glibc-2.17":{"64-bit":1}
,"64-bit":{"kernel":1}
,"kernel":{"userspace":1,"interface":1}
,"userspace":{"u-boot":1}
,"interface":{"feature":1,"khronos":1,"(egl":1,"sensor":1}
,"dsi":{"dsi":1,"display":1}
,"-dsi":{"ganged":1}
,"ganged":{"mode":1}
,"mode":{"-pwm":1,"-dual":1,"-wifi":1,"bcm4354":1,"spi4":1,"sdmmc1":1,"1.3.1":1,"(sm":1,"(fm":1,"plus":1,"(hs":1,"dynamic":1,"i2c":1,"usb0":1,"uart0":1,"(lp0)":1}
,"-pwm":{"backlight":1,"speed":1}
,"backlight":{"-dc":1}
,"-dc":{"continuous":1}
,"continuous":{"mode":1}
,"-dual":{"display":1}
,"-run":{"time":1}
,"time":{"power":1}
,"power":{"management":1,"-hdmi":1,"notification":1,"down":1,"mode":1}
,"management":{"-hdmi":1,"sdmmc1":1,"states":1,"-s.m.a.r.t":1,"data":1,"surface\u002Fb":1}
,"-hdmi":{"edid":1,"1.4":1,"primary":1,"1.4b":1}
,"edid":{"support":1}
,"-hot-plug":{"detection":1}
,"detection":{"mechanism":1,"-hdfx":1}
,"mechanism":{"-hdmi":1}
,"1.4":{"480p":1}
,"480p":{"720p":1}
,"720p":{"1080p":1}
,"1080p":{"rgb":1}
,"rgb":{"444":1}
,"444":{"@30":1}
,"@30":{"driver":1}
,"suspend\u002Fresume":{"low":1}
,"low":{"power":1}
,"primary":{"display":1}
,"1.4b":{"compliance":1}
,"compliance":{"pending":1}
,"pending":{"certification":1}
,"certification":{"hdmi":1,"audio":1}
,"hdmi":{"2.0":1}
,"2.0":{"compliance":1,"device":1,"support":1,"usb1":1,"egl":1,"opengl":1}
,"audio":{"support":1,"class":1}
,"-ethernet":{"10\u002F100\u002F1000":1}
,"10\u002F100\u002F1000":{"base":1}
,"base":{"-mac":1}
,"-mac":{"filtering":1}
,"filtering":{"-pwm":1}
,"speed":{"control":1,"spi4":1,"mode":1,"gen1":1,"devices":1,"uart0":1,"pcie":1,"supports":1}
,"control":{"sysfs":1,"sdmmc4":1,"uart2":1,"read":1,"system":1}
,"sysfs":{"-control":1,"bit":1}
,"-control":{"temperature":1}
,"temperature":{"variation":1}
,"variation":{"-i2c":1}
,"-i2c":{"master":1}
,"master":{"mode":1,"i2c":1}
,"-wifi":{"wake":1}
,"wake":{"wifi":1}
,"wifi":{"bcm4354":1}
,"bcm4354":{"dual-band":1,"sta":1,"hostap":1,"p2p":1,"wpa2":1,"bluetooth":1,"camera":1}
,"dual-band":{"2.4":1}
,"2.4":{"ghz\u002F5":1}
,"ghz\u002F5":{"ghz":1}
,"ghz":{"bcm4354":1}
,"sta":{"mode":1}
,"hostap":{"mode":1}
,"p2p":{"mode":1}
,"wpa2":{"security":1}
,"security":{"bcm4354":1}
,"bluetooth":{"bluetooth":1,"4.0":1}
,"4.0":{"bcm4354":1}
,"camera":{"support":1,"formats":1}
,"(csi":{"input":1}
,"input":{"support)":1,"formats":1}
,"support)":{"v4l2":1}
,"v4l2":{"media-controller":1,"interface":1}
,"media-controller":{"(v4l2":1,"driver":1}
,"(v4l2":{"api":1}
,"api":{"bypasses":1,"support":1,"registry":1}
,"bypasses":{"isp)":1}
,"isp)":{"csi0":1}
,"csi0":{"csi1":1}
,"csi1":{"csi2":1}
,"csi2":{"csi3":1}
,"csi3":{"csi4":1}
,"csi4":{"csi5":1}
,"csi5":{"note":1}
,"model":{"adopted":1}
,"adopted":{"24.1":1}
,"24.1":{"release":1}
,"soc_camera":{"driver":1}
,"provided":{"deprecated":1}
,"deprecated":{"peripheral":1}
,"peripheral":{"devices":1}
,"ina":{"support":1}
,"current":{"monitoring":1}
,"monitoring":{"cpu\u002Fgpu\u002Fvdd_in":1}
,"cpu\u002Fgpu\u002Fvdd_in":{"platform":1}
,"platform":{"support":1,"window":1,"graphics":1}
,"baseboard":{"p2597":1}
,"p2597":{"jetson":1}
,"jetson":{"module":1}
,"module":{"p2180":1}
,"p2180":{"i\u002Fo":1}
,"type":{"feature":1,"sdmmc4":1,"usb":1}
,"spi":{"max":1}
,"max":{"bus":1,"payload":1}
,"spi4":{"mhz":1,"spi1":1,"ouch":1}
,"mhz":{"spi1":1,"spi2":1,"chip":1,"sdmmc4":1,"sdmmc":1,"hot":1}
,"spi1":{"mhz":1,"0\u002F1":1,"spi2":1,"udio":1}
,"spi2":{"mhz":1,"0\u002F1":1,"full":1,"enable":1,"bi-directional":1,"least":1,"software":1,"supported":1,"purpose\u002Fclient":1,"cam\u002Fd":1}
,"chip":{"select":1}
,"select":{"spi4":1,"polarity":1}
,"0\u002F1":{"spi2":1,"packed\u002Funpacked":1}
,"packed\u002Funpacked":{"spi4":1}
,"full":{"duplex":1}
,"duplex":{"mode":1}
,"enable":{"bit":1,"byte":1,"extended":1}
,"bit":{"spi4":1,"banging":1,"rate\u002Fframe":1}
,"byte":{"spi4":1,"first":1}
,"bi-directional":{"spi4":1}
,"least":{"significant":1}
,"significant":{"bit":1,"byte":1}
,"first":{"spi4":1}
,"hardware":{"chip":1,"flow":1,"clock":1}
,"polarity":{"section":1}
,"section":{"spi4":1}
,"supported":{"modes":1,"features":1}
,"modes":{"1\u002F2\u002F3\u002F4":1}
,"1\u002F2\u002F3\u002F4":{"spi4":1}
,"purpose\u002Fclient":{"spi4":1}
,"ouch":{"spi1":1}
,"udio":{"spi2":1}
,"cam\u002Fd":{"isplay":1}
,"isplay":{"sdmmc":1}
,"sdmmc":{"speeds":1,"(m.2\u002Fsdio)":1}
,"speeds":{"(clock":1,"usb0":1,"maximum":1}
,"(clock":{"speed)":1}
,"speed)":{"sdmmc1":1}
,"sdmmc1":{"204":1,"high":1,"sdmmc":1,"sdmmc4":1}
,"204":{"mhz":1}
,"sdmmc4":{"200":1,"sdmmc":1,"hs400":1,"hs200":1,"ddr":1,"discard":1,"sanitize":1,"rpmb":1,"hpi":1,"bkops":1,"power":1,"sleep":1,"field":1,"cmd":1,"device":1,"pre":1}
,"200":{"mhz":1}
,"(m.2\u002Fsdio)":{"204":1,"sdr50":1,"sdr104":1,"hs533":1,"voltage":1,"frequency":1,"packed":1,"cache":1,"sata":1}
,"hot":{"plug":1}
,"plug":{"support":1}
,"high":{"speed":1}
,"sdr50":{"sdmmc1":1}
,"sdr104":{"sdmmc1":1}
,"hs533":{"sdmmc4":1}
,"hs400":{"sdmmc4":1}
,"hs200":{"sdmmc4":1}
,"ddr":{"ode":1}
,"ode":{"sdmmc1":1}
,"voltage":{"switching":1,"frequency":1}
,"switching":{"sdmmc1":1}
,"frequency":{"tuning":1,"changes":1,"(dvps)":1,"bit":1}
,"tuning":{"sdmmc1":1}
,"packed":{"commands":1}
,"commands":{"sdmmc4":1}
,"cache":{"control":1}
,"discard":{"sdmmc4":1}
,"sanitize":{"sdmmc4":1}
,"rpmb":{"sdmmc4":1}
,"hpi":{"sdmmc4":1}
,"bkops":{"sdmmc4":1}
,"notification":{"sdmmc4":1,"capability":1}
,"sleep":{"sdmmc4":1}
,"field":{"firmware":1,"support":1}
,"firmware":{"upgrade":1}
,"upgrade":{"sdmmc4":1}
,"cmd":{"ueuing":1}
,"ueuing":{"-device":1}
,"-device":{"life":1}
,"life":{"estimation":1}
,"estimation":{"type":1}
,"pre":{"eol":1}
,"eol":{"information":1}
,"information":{"sdmmc4":1,"opengl":1}
,"sata":{"speed":1,"pecification":1}
,"gen1":{"gen2":1,"i2c":1}
,"gen2":{"ahci":1,"i2c":1,"speeds":1}
,"ahci":{"mode":1}
,"1.3.1":{"sata":1}
,"pecification":{"3.1":1}
,"3.1":{"hipm":1}
,"hipm":{"-dipm":1}
,"-dipm":{"-ncq":1}
,"-ncq":{"-port":1}
,"-port":{"multiplier":1}
,"multiplier":{"support":1}
,"cbs":{"link":1}
,"link":{"power":1,"speed":1,"width":1,"layer":1,"active":1,"bandwidth":1,"control":1}
,"states":{"partial":1,"runtime":1}
,"partial":{"slumber":1}
,"slumber":{"device":1}
,"runtime":{"time":1,"i2c":1,"jtag":1}
,"-s.m.a.r.t":{"-ata":1}
,"-ata":{"error":1}
,"error":{"logging":1,"reporting":1,"correctable":1,"system":1,"non-fatal":1,"fatal":1,"pme":1}
,"logging":{"-i2c":1}
,"gen3":{"i2c":1}
,"ddc":{"i2c":1}
,"pwr":{"standard":1}
,"standard":{"mode":1}
,"(sm":{"100kbps)":1}
,"100kbps)":{"fast":1}
,"fast":{"mode":1,"responses":1}
,"(fm":{"400kbps)":1,"-1mbps)":1}
,"400kbps)":{"fast":1}
,"plus":{"(fm":1}
,"-1mbps)":{"high":1}
,"-3.4mbps)":{"7-bit":1}
,"7-bit":{"10-bit":1}
,"10-bit":{"slave":1}
,"slave":{"addressing":1}
,"addressing":{"lost":1}
,"lost":{"arbitration":1}
,"arbitration":{"detect":1}
,"detect":{"packet":1}
,"packet":{"mode":1}
,"dynamic":{"clock":1,"voltage":1}
,"clock":{"gating":1,"always":1,"frequency":1,"power":1}
,"gating":{"multi-master":1,"deep":1}
,"multi-master":{"support":1}
,"pio":{"mode":1}
,"message":{"length":1,"split":1,"size":1,"signaled":1}
,"length":{"<=20":1,"bytes":1}
,"<=20":{"bytes":1}
,"bytes":{"dma":1,"clock":1,"runtime":1,"extended":1}
,"dma":{"mode":1,"gines":1}
,"need":{"fast":1}
,"responses":{"message":1}
,"split":{"message":1}
,"size":{"greater":1,"128":1}
,"greater":{"bytes":1}
,"changes":{"sysfs":1}
,"banging":{"gpios":1}
,"gpios":{"clubbing":1}
,"clubbing":{"transactions":1}
,"transactions":{"program":1}
,"program":{"packets":1}
,"packets":{"together":1}
,"together":{"bus":1}
,"clear":{"support":1}
,"usb0":{"otg":1,"host":1,"usb1":1,"usb":1,"hs\u002F480":1,"micro":1,"class":1}
,"otg":{"mode":1,"support":1}
,"host":{"mode":1,"-low":1,"-full":1,"-high":1,"-auto":1,"controller":1}
,"usb1":{"host":1,"ss\u002F5":1,"pex5":1,"connector":1,"type":1,"remote":1,"usb":1,"otg":1}
,"-low":{"speed":1}
,"-full":{"speed":1}
,"-high":{"speed":1}
,"-auto":{"suspend":1}
,"suspend":{"support":1}
,"3.0":{"speeds":1,"support":1}
,"hs\u002F480":{"mbps":1}
,"mbps":{"usb1":1,"full-frame":1,"decode":1,"supported":1}
,"ss\u002F5":{"gbps":1}
,"gbps":{"lanes":1}
,"lanes":{"usb1":1,"xbar":1}
,"pex5":{"usb":1}
,"connector":{"usb0":1}
,"micro":{"usb1":1}
,"remote":{"wakeup":1}
,"wakeup":{"support":1}
,"2.0\u002F3.0":{"host":1}
,"class":{"support":1,"(usb0":1}
,"mass":{"storage":1}
,"(usb0":{"usb1)":1}
,"usb1)":{"usb":1,"hid":1,"mtp":1,"cdc":1,"gpio":1}
,"video":{"class":1,"decoders":1,"decode":1,"encoders":1,"encode":1,"video":1,"snapshot":1}
,"hid":{"(usb0":1}
,"mtp":{"(usb0":1}
,"cdc":{"-ncm\u002Fecm":1}
,"-ncm\u002Fecm":{"(usb0":1}
,"gpio":{"pinmux":1}
,"pinmux":{"configuration":1}
,"configuration":{"-gpio":1,"programming":1}
,"-gpio":{"configuration":1,"interrupt":1}
,"programming":{"-gpio":1}
,"interrupt":{"support":1,"enable":1}
,"-uart":{"speed":1}
,"uart0":{"115200":1,"uart2":1}
,"115200":{"uart2":1}
,"uart2":{"921600":1,"uart3":1}
,"921600":{"uart3":1}
,"uart3":{"3000000":1,"pio":1,"dma":1,"fifo":1,"pcie":1}
,"3000000":{"hardware":1}
,"flow":{"control":1}
,"fifo":{"mode":1}
,"pcie":{"speed":1,"gen1\u002Fgen2":1,"pcie":1,"host":1,"device":1,"tegra":1,"connec":1,"cuda":1}
,"gen1\u002Fgen2":{"pcie":1,"lane":1}
,"lane":{"idth":1}
,"idth":{"pcie":1}
,"controller":{"features":1}
,"xbar":{"config":1}
,"config":{"(x4_x1":1,"space":1}
,"(x4_x1":{"x2_x1)":1}
,"x2_x1)":{"extended":1}
,"extended":{"config":1,"tag":1,"capabilities":1}
,"space":{"hardware":1}
,"deep":{"power":1}
,"down":{"(dpd)":1}
,"(dpd)":{"pci":1}
,"pci":{"features":1}
,"signaled":{"interrupts":1}
,"interrupts":{"vendor":1}
,"vendor":{"specific":1,"neutral":1}
,"specific":{"messages":1}
,"messages":{"msi-x":1}
,"msi-x":{"pcie":1}
,"capabilities":{"max":1,"advanced":1}
,"payload":{"size":1}
,"128":{"bytes":1}
,"tag":{"field":1}
,"role-based":{"error":1}
,"reporting":{"maximum":1,"capable":1,"(aer)":1,"(ltr)":1}
,"maximum":{"link":1}
,"width":{"supports":1,"aspm":1}
,"aspm":{"upport":1}
,"upport":{"(l0":1}
,"(l0":{"l1)":1}
,"l1)":{"clock":1}
,"data":{"link":1}
,"layer":{"link":1}
,"active":{"reporting":1}
,"capable":{"link":1}
,"bandwidth":{"notification":1}
,"capability":{"link":1}
,"read":{"completion":1}
,"completion":{"boundary":1}
,"boundary":{"root":1}
,"root":{"control":1}
,"system":{"error":1,"handles":1}
,"correctable":{"error":1}
,"non-fatal":{"error":1}
,"fatal":{"error":1}
,"pme":{"interrupt":1}
,"advanced":{"error":1}
,"(aer)":{"latency":1}
,"latency":{"tolerance":1}
,"tolerance":{"reporting":1}
,"(ltr)":{"substates":1}
,"substates":{"l1.1":1}
,"l1.1":{"l1.2":1}
,"l1.2":{"misc":1}
,"misc":{"features":1}
,"(dvps)":{"tegra":1}
,"(lp0)":{"runtime":1}
,"jtag":{"jtag":1,"attach":1}
,"attach":{"-jtag":1}
,"-jtag":{"halt\u002Fstep\u002Fgo":1}
,"halt\u002Fstep\u002Fgo":{"-note":1}
,"-note":{"pcie":1}
,"path":{"ahb-dma":1}
,"ahb-dma":{"apb-dma":1,"apb":1}
,"apb-dma":{"engines":1}
,"engines":{"pcie":1}
,"connec":{"ted":1}
,"ted":{"directly":1}
,"directly":{"mselect":1}
,"mselect":{"ahb-dma":1}
,"apb":{"dma":1,"buses":1,"engines":1}
,"gines":{"interact":1}
,"interact":{"ips":1}
,"ips":{"connected":1}
,"connected":{"respective":1}
,"respective":{"ahb":1}
,"ahb":{"apb":1}
,"buses":{"possibl":1}
,"possibl":{"either":1}
,"either":{"ahb":1}
,"cuda":{"feature":1,"version":1}
,"version":{"cuda":1,"9.0.252":1,"egl":1,"release":1}
,"9.0.252":{"graphics":1}
,"graphics":{"graphics":1,"apis":1,"context":1,"interface":1}
,"apis":{"notes":1,"opengl":1,"l4t":1}
,"opengl":{"4.5":1,"support":1,"underlying":1,"driver":1,"specifications":1,"common":1,"information":1,"khronos":1,"api":1}
,"4.5":{"opengl-es":1}
,"opengl-es":{"3.2":1}
,"3.2":{"vulkan":1}
,"vulkan":{"1.0":1,"loader":1}
,"1.0":{"egl":1}
,"egl":{"1.5":1,"vendor":1,"stream":1,"egl":1,"without":1,"opengl":1,"interface":1,"enables":1,"specification":1}
,"1.5":{"glx":1}
,"glx":{"glvnd":1}
,"glvnd":{"version":1}
,"neutral":{"functionality":1}
,"functionality":{"nvdc":1}
,"nvdc":{"-direct":1}
,"-direct":{"rendering":1}
,"rendering":{"manager":1,"apis":1,"synchronization":1,"using":1}
,"manager":{"(drm)":1}
,"(drm)":{"compatibility":1}
,"compatibility":{"drm":1}
,"drm":{"2.0":1}
,"stream":{"x11":1}
,"x11":{"abi-20":1,"content":1,"usage":1,"window":1}
,"abi-20":{"legacy":1}
,"legacy":{"24.2":1}
,"24.2":{"using":1}
,"using":{"ubuntu":1,"khronos":1}
,"ubuntu":{"16.04":1}
,"16.04":{"api":1}
,"without":{"x11":1}
,"content":{"display":1}
,"usage":{"vulkan":1}
,"1.0.66":{"verified":1}
,"verified":{"working":1}
,"working":{"properly":1}
,"properly":{"release":1}
,"consult":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fvulkan":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fvulkan":{"details":1}
,"details":{"egl":1,"example":1,"h.264":1}
,"khronos":{"rendering":1,"apis":1,"native":1,"opengl":1}
,"underlying":{"native":1}
,"native":{"platform":1}
,"window":{"system":1,"panel":1}
,"handles":{"graphics":1}
,"context":{"management":1}
,"surface\u002Fb":{"uffer":1}
,"uffer":{"binding":1}
,"binding":{"rendering":1}
,"synchronization":{"egl":1}
,"enables":{"high-performance":1}
,"high-performance":{"accelerated":1}
,"accelerated":{"mixed-mode":1}
,"mixed-mode":{"rendering":1}
,"l4t":{"supports":1,"vstab":1}
,"specification":{"khronos":1,"2.0":1}
,"(egl":{"specification)":1}
,"specification)":{"opengl":1}
,"specifications":{"opengl":1}
,"common":{"profile":1}
,"profile":{"specification":1,"insert-aud":1}
,"registry":{"video":1}
,"decoders":{"video":1}
,"decode":{"output":1,"support":1}
,"output":{"formats":1,"format":1}
,"formats":{"sampling":1,"input":1,"output":1,"notes":1}
,"sampling":{"frequency":1}
,"rate\u002Fframe":{"rate":1}
,"rate":{"notes":1}
,"h.264":{"nv12":1,"i420":1,"enc":1}
,"nv12":{"nvmm:nv12":1,"nvmm:1420":1,"nvmm:i420":1,"nv12":1,"flip-method":1}
,"nvmm:nv12":{"3840":1,"nvmm:nv12":1,"flip-method":1}
,"3840":{"2160":1}
,"2160":{"fps":1}
,"fps":{"120":1,"160":1,"140":1,"100":1}
,"120":{"mbps":1}
,"full-frame":{"disable-dpb":1}
,"disable-dpb":{"skip-frames":1}
,"skip-frames":{"enable-error":1}
,"enable-error":{"-check":1}
,"-check":{"enable-frame-type-reporting":1}
,"enable-frame-type-reporting":{"h.265":1,"jpeg":1,"vp9":1,"video":1}
,"h.265":{"nv12":1}
,"160":{"mbps":1}
,"gstreamer":{"1.4.5":1}
,"1.4.5":{"later":1}
,"later":{"full-frame":1}
,"jpeg":{"i420":1}
,"i420":{"nvmm:i420":1,"nv12":1,"i420":1,"flip-method":1}
,"nvmm:i420":{"600":1,"nvmm:nv12":1,"nvmm:i420":1,"flip-method":1,"scene-mode":1}
,"600":{"mp\u002Fsec":1}
,"mp\u002Fsec":{"-vp8":1,"-h.265":1}
,"-vp8":{"nv12":1}
,"140":{"mbps":1}
,"vp9":{"nv12":1,"i420":1}
,"encoders":{"video":1}
,"encode":{"input":1}
,"nvmm:1420":{"nvmm:nv12":1}
,"include":{"control-rate":1}
,"control-rate":{"bitrate":1}
,"bitrate":{"peak-bitrate":1}
,"peak-bitrate":{"iframeinterval":1}
,"iframeinterval":{"sliceintrarefreshenable":1}
,"sliceintrarefreshenable":{"sliceintrarefreshinterval":1}
,"sliceintrarefreshinterval":{"bit-packetization":1}
,"bit-packetization":{"vbv-size":1}
,"vbv-size":{"temporal-tradeoff":1}
,"temporal-tradeoff":{"enablemvbuffermeta":1}
,"enablemvbuffermeta":{"qp-range":1}
,"qp-range":{"measureencoderlatency":1}
,"measureencoderlatency":{"enabletwopasscbr":1}
,"enabletwopasscbr":{"preset-level":1}
,"preset-level":{"enablestrimgentbitrate":1}
,"enablestrimgentbitrate":{"insert-sps-pps":1}
,"insert-sps-pps":{"num-b-frames":1}
,"num-b-frames":{"slice-header-spacing":1}
,"slice-header-spacing":{"profile":1}
,"insert-aud":{"insert-vui":1}
,"insert-vui":{"force-idr":1}
,"force-idr":{"jpeg":1,"vp8":1,"applies":1,"note":1}
,"-h.265":{"i420":1}
,"100":{"mbps":1}
,"vp8":{"i420":1}
,"applies":{"tx2":1}
,"tx2":{"vp9":1}
,"gst-inspect-1.0":{"utility":1,"omxh264enc":1}
,"utility":{"understand":1}
,"understand":{"feat":1}
,"feat":{"ure":1}
,"ure":{"details":1}
,"example":{"gst-inspect-1.0":1}
,"omxh264enc":{"command":1}
,"command":{"provides":1}
,"provides":{"feature":1}
,"enc":{"oder":1}
,"oder":{"display":1}
,"outputs":{"nveglglessink":1}
,"nveglglessink":{"nvoverlaysink":1}
,"nvoverlaysink":{"x11":1}
,"panel":{"overlay":1}
,"overlay":{"-overlay":1}
,"-overlay":{"-overlay-depth":1}
,"-overlay-depth":{"-overlay-x":1}
,"-overlay-x":{"-overlay-y":1}
,"-overlay-y":{"-overlay-w":1}
,"-overlay-w":{"-overlay-h":1}
,"-overlay-h":{"conversion":1}
,"conversion":{"scaling":1,"uyvy":1,"yuy2":1,"yvyu":1,"nv12":1,"gray8":1,"bgrx":1,"rgba":1,"nvmm:i420":1,"nvmm:i420_10le":1,"nvmm:nv12":1,"csi":1}
,"scaling":{"rotation":1}
,"rotation":{"formats":1}
,"flip-method":{"interpolation-method":1}
,"interpolation-method":{"crop":1}
,"crop":{"format":1}
,"format":{"conversion":1,"options":1}
,"uyvy":{"uyvy":1,"flip-method":1}
,"yuy2":{"yuy2":1,"flip-method":1}
,"yvyu":{"yvyu":1,"flip-method":1}
,"gray8":{"gray8":1,"flip-method":1}
,"bgrx":{"bgrx":1,"flip-method":1}
,"rgba":{"rgba":1,"flip-method":1}
,"nvmm:i420_10le":{"nvmm:i420_10le":1,"flip-method":1}
,"csi":{"usb":1}
,"options":{"notes":1}
,"scene-mode":{"-color-effect":1}
,"-color-effect":{"-auto-exposure":1}
,"-auto-exposure":{"-flicker":1}
,"-flicker":{"-contrast":1}
,"-contrast":{"-saturation":1}
,"-saturation":{"-tnr-strength":1}
,"-tnr-strength":{"-tnr-mode":1}
,"-tnr-mode":{"-edge-enhancement":1}
,"-edge-enhancement":{"-intent":1}
,"-intent":{"video":1}
,"snapshot":{"preview":1}
,"preview":{"sensor-id":1}
,"sensor-id":{"-enable-exif":1}
,"-enable-exif":{"-aer":1}
,"-aer":{"egion":1}
,"egion":{"-wbr":1,"-fpsr":1}
,"-wbr":{"egion":1}
,"-fpsr":{"ange":1}
,"ange":{"-exposure-time":1}
,"-exposure-time":{"-wb":1}
,"-wb":{"manualmode":1}
,"manualmode":{"-wbgains":1}
,"-wbgains":{"-embedded":1}
,"-embedded":{"metadata":1}
,"metadata":{"recision":1}
,"recision":{"timestamping":1}
,"timestamping":{"dct-nr":1}
,"dct-nr":{"v4l2":1}
,"sensor":{"driver":1}
,"gyro":{"service":1}
,"service":{"l4t":1}
,"vstab":{"libargus":1,"support":1}
,"libargus":{"-raw":1}
,"-raw":{"capture":1}
,"capture":{"-egl":1}
,"-egl":{"producer":1}
,"producer":{"-face":1}
,"-face":{"detection":1}
,"-hdfx":{"-simultaneous":1}
,"-simultaneous":{"multi-camera":1}
,"multi-camera":{"pluggable\u002Freplacable":1,"support":1}
,"pluggable\u002Freplacable":{"12-and":1}
,"12-and":{"14-b":1}
,"14-b":{"sensors":1}
,"sensors":{"dpcm":1,"vstab":1}
,"dpcm":{"sensors":1}
,"af2.8":{"support":1}
,"auto":{"iris":1}
,"iris":{"image":1}
,"image":{"de-warping":1}
,"de-warping":{"distortion":1}
,"distortion":{"correction":1}
,"correction":{"global":1}
,"global":{"shutter":1}
,"shutter":{"coordinated":1}
,"coordinated":{"multi-camera":1}
}
;Search.control.loadWordPairs(pairs);
