var pairs =
{
"debugging":{"register":1}
,"register":{"trace":1,"access":1}
,"trace":{"buffers":1,"buffer":1,"stop":1,"locating":1}
,"buffers":{"rtrace":1}
,"rtrace":{"used":1,"kernel":1,"require":1,"add":1,"automatically":1,"start":1,"enter":1,"output":1,"available":1}
,"used":{"determine":1}
,"determine":{"register":1}
,"access":{"happene":1}
,"happene":{"reset":1}
,"reset":{"panic":1}
,"panic":{"wit":1}
,"wit":{"rtrace":1}
,"kernel":{"traces":1,"configuration":1}
,"traces":{"trigger":1}
,"trigger":{"read\u002Fwrite":1}
,"read\u002Fwrite":{"calls":1}
,"calls":{"persistent":1}
,"persistent":{"register":1}
,"buffer":{"decoded":1}
,"decoded":{"dumped":1}
,"dumped":{"reboo":1}
,"reboo":{"using":1}
,"using":{"pstore":1}
,"pstore":{"file":1}
,"file":{"ystem":1,"device":1}
,"ystem":{"tegra":1}
,"tegra":{"rtrace":1}
,"require":{"ramdump":1}
,"ramdump":{"prints":1}
,"prints":{"parsed":1}
,"parsed":{"output":1}
,"output":{"device":1,"output":1,"rtrace":1,"similar":1}
,"device":{"directly":1,"\u002Fsys\u002Ffs\u002Fpstore\u002Frtrace-ramoops":1}
,"directly":{"enable":1}
,"enable":{"rtrace":1}
,"add":{"following":1}
,"following":{"kernel":1,"start":1,"file":1,"fe406314":1}
,"configuration":{"config_pstore_rtrace=y":1}
,"config_pstore_rtrace=y":{"along":1}
,"along":{"above":1}
,"above":{"macro":1}
,"macro":{"add":1}
,"start":{"rtrace":1,"top":1}
,"automatically":{"config_pstore_rtrace_enable_at_startup=y":1}
,"config_pstore_rtrace_enable_at_startup=y":{"start":1}
,"top":{"rtrace":1}
,"enter":{"command":1}
,"command":{"$echo":1}
,"$echo":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fpstore\u002Frecord_r":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fpstore\u002Frecord_r":{"trace":1}
,"stop":{"rtrace":1}
,"locating":{"rtrace":1}
,"available":{"reboot":1}
,"reboot":{"following":1}
,"\u002Fsys\u002Ffs\u002Fpstore\u002Frtrace-ramoops":{"rtrace":1}
,"similar":{"following":1}
,"fe406314":{"<-c038df4c":1}
,"<-c038df4c":{"mem_serial_in":1}
,"mem_serial_in":{"0x2c\u002F0x3":1}
,"0x2c\u002F0x3":{"fe406314":1,"fe406304":1}
,"fe406304":{"<-c038df18":1}
,"<-c038df18":{"mem_serial_out":1}
,"mem_serial_out":{"0x30\u002F0x":1}
}
;Search.control.loadWordPairs(pairs);
