var pairs =
{
"bootloader":{"update":1,"directory":1,".\u002Fmkbctpart":1}
,"update":{"redundancy":1,"procedure":1,"mechanism":1,"runtime":1,"either":1,"new":1,"standard":1,"mplement":1,"convenience":1,"process":1,"boot":1,"u-boot":1,"entry":1,"recover":1,"reboot":1,"bfs\u002Fkfs":1,"update":1,"status":1,"system":1}
,"redundancy":{"guidelines":1,"features":1,"tegra":1,"follows":1,"prepare":1,"ollow":1,"enabling":1,"requires":1,"enabled":1,"partit":1,"inter-operability":1,"flash":1,"makes":1,"bct":1}
,"guidelines":{"enable":1}
,"enable":{"runtime":1,"boot":1}
,"runtime":{"boot":1,"access":1,"linux":1}
,"boot":{"firmwa":1,"flow":1,"file":1,"kernel":1,"files":1,"loader":1,"firmware":1,"deploy":1,"partitions":1,"partition":1,"loaders":1,"firmwares":1,"partit":1,"fir":1,"version":1,"load":1,"epeat":1,"cycle":1,"rom":1}
,"firmwa":{"updates":1}
,"updates":{"data":1,"bct":1,"boot":1}
,"data":{"redundancy":1}
,"features":{"part":1}
,"part":{"failure-tolerant":1,"bfs":1,"kernel":1}
,"failure-tolerant":{"system":1,"bct":1,"boot":1}
,"system":{"update":1,"offli":1,"partition":1,"modifying":1,"updating":1,".\u002Ftegraflash.py":1,".\u002Fflash.sh":1,"<l4t":1,"execute":1,"*.signed":1,"executing":1,"recovering":1,"configure":1,"properly":1,"halted":1}
,"procedure":{"nvidia":1,"outside":1,"implementing":1,"numbers":1}
,"nvidia":{"tegra":1,"developer":1,"flashing":1,"provides":1}
,"tegra":{"linux":1,"x1-based":1,"bootrom":1,"partition":1,"chip":1}
,"linux":{"driver":1,"kernel":1,"partition":1,"\u002Fdev\u002Fmmcblk0px":1,"dtb":1}
,"driver":{"package":1,"partition":1,"<kernel>\u002Fdrivers\u002Fmmc\u002Fhost\u002Fsdhci-tegra.c":1}
,"package":{"(l4t)":1}
,"(l4t)":{"relea":1}
,"relea":{"ses":1}
,"ses":{"jetson":1}
,"jetson":{"tx1":1,"copy":1,"device":1}
,"tx1":{"development":1,"boot":1,"developer":1,"enable":1,"mib":1,"platform":1,"device":1,"copy":1,"emm":1}
,"development":{"kit":1,"guide":1}
,"kit":{"adaptation":1,"user":1}
,"adaptation":{"instructions":1}
,"instructions":{"may":1,"development":1,"place":1}
,"may":{"required":1,"enclosed":1}
,"required":{"tegra":1,"tx1":1,"inform":1}
,"x1-based":{"platforms":1}
,"platforms":{"implementation":1}
,"implementation":{"specific":1}
,"specific":{"update":1}
,"mechanism":{"pdate":1}
,"pdate":{"procedure":1,"u-boot":1}
,"outside":{"scope":1}
,"scope":{"docum":1}
,"docum":{"ent":1}
,"ent":{"prerequisites":1}
,"prerequisites":{"understanding":1}
,"understanding":{"concepts":1}
,"concepts":{"required":1}
,"flow":{"nvidia":1}
,"developer":{"embedded":1,"kit":1}
,"embedded":{"computing":1}
,"computing":{"website":1}
,"website":{"jetson":1,"update":1}
,"user":{"guide":1}
,"guide":{"bct":1,"device":1}
,"bct":{"tegraboot":1,"int":1,"attempts":1,"searched":1,"based":1,"partition":1,"contain":1,"dtb":1,"deployed":1,"bfs":1,"boot":1,"bfs0":1,"gp1":1,"nvc":1,"images":1,"image":1,"modified":1,"binary":1,"system":1,"(bct_1111)":1,"used":1,"retrieve":1,"place":1,"bct_1111":1,"executing":1,"_2211":1,"mkbctpar":1,"rtition":1,"spec":1,"file]":1,"file>":1,"n\u002Fa":1,"file":1,"bfsblob":1,"_2222":1,"redundancy":1,"clobbered":1,"configure":1}
,"tegraboot":{"boot":1,"entry":1,"tegraboot":1,"computes":1,"takes":1,"transfers":1,"fails":1,"bootfileset":1,"partitions":1,"instances":1,"new":1,"example":1,"cboot.bin":1}
,"file":{"redundancy":1,"tegraboot":1,"tegraflash":1,"automatically":1,"navigate":1,"ith":1,"modify":1,"available":1,"contains":1,"partitions":1,"move":1,"lnx":1,"altered":1,"follows":1,"system":1,"stem":1,"flashing":1,"version":1,"padded":1,"new":1,"validates":1,"bfsblob":1,"mkbctpart":1,"output":1,"bct_2211":1,"image":1}
,"bootrom":{"validates":1,"searches":1,"computes":1,"transfers":1,"validate":1}
,"validates":{"bct":1,"checksum":1,"load":1,"reads":1}
,"int":{"egrated":1}
,"egrated":{"checksum":1}
,"checksum":{"rsa":1,"signature":1,"companion":1,"pkc":1}
,"rsa":{"signature":1,"key":1}
,"signature":{"calculated":1,"match":1,"value":1,"tegrab":1,"tegraboot":1,"located":1,"boot":1}
,"calculated":{"checksum":1}
,"match":{"checksum":1}
,"value":{"within":1,"appended":1,"updated":1}
,"within":{"bootrom":1,"bootfiles":1,"bct":1}
,"searches":{"next":1}
,"next":{"bct":1,"level":1,"tegraboot":1,"boot":1}
,"attempts":{"validate":1}
,"validate":{"copies":1,"bootfileset":1,"load":1}
,"copies":{"bct":1}
,"searched":{"mod-16kib":1}
,"mod-16kib":{"boundaries":1}
,"boundaries":{"nvidia":1}
,"flashing":{"utility":1,"modification":1,"flashing":1,"instructions":1,"initial":1}
,"utility":{"tegraflash":1,"read":1,"prints":1,"mkbctpart":1,"generates":1,"expects":1,"print":1}
,"tegraflash":{"writes":1,"scripts":1,"script":1,"utility":1}
,"writes":{"copies":1,"new":1}
,"based":{"space":1}
,"space":{"allocated":1}
,"allocated":{"bct":1}
,"partition":{"bct":1,"configuration":1,"configuratio":1,"configuratin":1,"configurat":1,"table":1,"nvc":1,"(lnx)":1,"part":1,"partition":1,"first":1,"dtb":1,"entry":1,"stay":1,"check":1,"file":1,"filename":1,"bfsblob":1,"identical":1,"clobbered":1}
,"contain":{"four":1,"layout":1,"cpu-portion":1,"graboot":1,"condary":1,"warmboot":1,"microcode":1,"cure":1,"rnel":1,"ther":1,"two":1}
,"four":{"entries":1,"appended":1,"version":1}
,"entries":{"indicatin":1,"bct":1,"known":1}
,"indicatin":{"locations":1}
,"locations":{"(offset":1}
,"(offset":{"size)":1}
,"size)":{"checksums":1}
,"checksums":{"signature":1,"bfs":1}
,"tegrab":{"oot":1}
,"oot":{"bootfileset":1,"rom":1}
,"bootfileset":{"(bfs)":1,"kernelfileset":1,"kernelfiileset":1,"partitions":1,"defined":1,"combinations":1}
,"(bfs)":{"kernelfileset":1}
,"kernelfileset":{"(kfs)":1,"overwrites":1,"(dtb":1}
,"(kfs)":{"bootrom":1}
,"computes":{"validates":1}
,"entry":{"rst":1,"immediately":1,"rootfs":1,"id=values":1,"csv>":1}
,"rst":{"valid":1}
,"valid":{"checksum":1,"bct":1}
,"located":{"bootrom":1,"boot":1,"ebt":1}
,"transfers":{"contro":1,"control":1}
,"contro":{"(jumps)":1}
,"(jumps)":{"specified":1,"boot":1}
,"specified":{"tegraboot":1,"root":1,"dification":1}
,"companion":{"bfs":1}
,"bfs":{"kfs":1,"validated":1,"dtb":1,"image":1,"starting":1,"boot":1,"indicate":1,"partitions":1,"nly":1,"--pt":1,"instance":1,"blobs":1,"version-2":1,"version-1":1,"files":1,"blob":1,"images":1}
,"kfs":{"checksums":1,"images":1,"files":1,"modify":1,"--dtb":1,"partitions":1}
,"validated":{"signature":1,"loaded":1}
,"kernel":{"files":1,"u-boo":1,"expose":1,"ages":1,"images":1,"dtb":1,"whi":1,"emmc":1,"odify":1,"driver":1,"booted":1,"partition":1,"dtbs":1,"u-boot":1,"file":1,"location":1,"proper":1,"independently":1,"dtb>":1}
,"files":{"verifi":1,"tegraboot-cpu":1,"verified":1,"protected":1,"upon":1,"target":1,"provided":1,"signed":1,"pkc":1,"*.encrypt":1,"download":1}
,"verifi":{"tegraboot":1}
,"takes":{"appropriate":1,"bct_1111":1}
,"appropriate":{"action":1}
,"action":{"loads":1}
,"loads":{"boot":1}
,"tegraboot-cpu":{"bootloader-dtb":1}
,"bootloader-dtb":{"kernel-dtb":1}
,"kernel-dtb":{"warmboot-vector":1}
,"warmboot-vector":{"tos":1}
,"tos":{"necessary":1,"tos-1":1,"nvc-1":1}
,"necessary":{"boot":1,"modify":1,"name":1}
,"verified":{"loaded":1}
,"loaded":{"tegraboot":1,"boot":1}
,"control":{"(jumps)":1}
,"loader":{"cboot":1,"validates":1,"note":1,"kernel":1,"redundancy":1,"partitions":1,"linux":1,"binary":1,"files":1,"entries":1,"bei":1,"execute":1,"reboot":1}
,"cboot":{"boot":1,"beginning":1,"allowed":1}
,"load":{"next":1,"file":1}
,"level":{"software":1}
,"software":{"linux":1}
,"u-boo":{"tegraboot":1}
,"fails":{"validate":1}
,"overwrites":{"itself":1,"u-boot":1}
,"itself":{"resets":1}
,"resets":{"board":1}
,"board":{"bootrom":1}
,"kernelfiileset":{"combination":1}
,"combination":{"update":1}
,"firmware":{"implement":1,"redundancy":1,"bct":1,"dundancy":1,"update":1,"version":1,"kernel":1,"updated":1,"read":1,"tries":1,"new":1,"newer":1,"follow":1,"binaries":1,"blob":1,"builds":1}
,"implement":{"boot":1}
,"follows":{"modify":1,"bct":1,"<l4t":1,"navigate":1,"reads":1,"mkbctpart":1,"option":1}
,"modify":{"linux":1,"partition":1,"bsp":1,"gnu_linux_fastboot_emmc_full.xml":1,"new_config.xml":1}
,"expose":{"emmc":1}
,"emmc":{"boot0":1,"partitions":1,"driver":1,"boot":1,"sudo":1}
,"boot0":{"boot1":1,"mib":1}
,"boot1":{"partitions":1,"sudo":1}
,"partitions":{"runtime":1,"ecified":1,"verify":1,"reboot":1,"exposed":1,"navigate":1,"available":1,"opulate":1,"defined":1,"nvc-1":1,"partitions":1,"pt-1":1,"tbc":1,"rp1":1,"ebt":1,"wb0":1,"bpf":1,"tos":1,"dtb":1,"lnx":1,"eks":1,"sizes":1,"exceed":1,"disappear":1,"visible":1}
,"access":{"generate\u002Fmodify":1,"default":1}
,"generate\u002Fmodify":{"partition":1}
,"configuration":{"file":1,"generation":1,"filename>":1,"filename":1}
,"ecified":{"boot0":1}
,"verify":{"tegraflash":1,"bootfileset":1,"sum":1,"kernelfileset":1,"proper":1,"boot":1}
,"scripts":{"inter-operable":1}
,"inter-operable":{"secure":1}
,"secure":{"boot":1}
,"deploy":{"devices":1,"boot":1}
,"devices":{"boot":1}
,"prepare":{"new":1}
,"new":{"boot":1,"l4t":1,"u-boot":1,"bct":1,"root":1,"line":1,"images":1,"location":1,"updated":1,"pfs":1,"configuration":1,"image":1,"bfsblob":1,"kernel":1,"bfs\u002Fkfs":1,"versions":1,"binaries":1}
,"dtb":{"kernel":1,"part":1,"dtb-1":1,"{-1,-2,-3}":1,"\u002Fdev\u002Fmmcblk0p2":1,"file":1}
,"ages":{"update":1}
,"either":{"download":1}
,"download":{"new":1,"install":1,"instruction":1,"boot.img":1,"bct_2222":1}
,"l4t":{"bsp":1,"r24.2.2":1,"r28.2":1,"release":1,"r28":1,"r24":1,"r24.x.x":1,"bsp>\u002Flinux_for_tegra\u002Fbootloader\u002Fpreparing":1,"bsp>\u002Flinux_for_tegra\u002Fbootload":1,"28.1.0":1,"environment":1}
,"bsp":{"generate":1,"version":1,"configuration":1,"inter-operate":1,"update":1,"prepare":1,"shown":1,"build":1,"<bsp>\u002Flinux_for_tegra\u002Fbootloaer\u002Fpreparing":1}
,"generate":{"new":1,"partition":1}
,"u-boot":{"extract":1,"cboot":1,"longer":1,"defined":1,"depending":1,"uild":1,"jetson-tx1":1,"old":1,"jetson":1,"r28.x.x":1,"target":1,"included":1}
,"extract":{"bct":1}
,"deployed":{"system":1,"initial":1}
,"offli":{"modification":1}
,"modification":{"offline":1,"auses":1}
,"offline":{"host-based":1,"modifications":1}
,"host-based":{"tools":1,"utility":1}
,"tools":{"regenerate":1}
,"regenerate":{"bfs":1}
,"images":{"download":1,"target":1,"copy":1,"emmc":1,"update":1,"slots":1,"nvidia":1,"using":1,"nto":1,"ach":1}
,"target":{"device":1,"regenerating":1,"commands":1,"syste":1,"bfs\u002Fkfs":1,"system":1}
,"device":{"update":1,"preparing":1,"bct":1,"forced-recovery":1,"recov":1,"tegraflash":1,"<bsp>\u002Flinux_for_tegra\u002Fbootloader\u002F\u2022":1,"bfsblob":1,"default":1,"generates":1,"prior":1,"downloading":1,"opy":1,"pdate":1,"copy":1,"mib":1,"even":1}
,"copy":{"bct":1,"u-boot-dtb.bin":1,"bct_1111":1,"ing":1}
,"reboot":{"execute":1,"system":1,"target":1}
,"execute":{"updated":1,"command":1,"following":1,"commands":1}
,"updated":{"boot":1,"bct":1,"bct_2211":1,"binaries":1,"successfully":1}
,"note":{"l4t":1,"provided":1}
,"r24.2.2":{"kernel":1}
,"image":{"protected":1,"names":1,"numeric":1,"file>":1,"filename":1,"downloaded":1,"bfsblob":1,"behaves":1,"intact":1}
,"protected":{"boot":1,"checksum":1,"system":1}
,"dundancy":{"even":1}
,"even":{"validated":1,"error":1,"first":1}
,"whi":{"part":1}
,"starting":{"l4t":1,"def":1}
,"r28.2":{"bfs":1}
,"pkc":{"authentication":1,"protected":1,"<rsa":1}
,"authentication":{"failure-tolerant":1}
,"standard":{"l4t":1,"partition":1,"jetson":1}
,"release":{"jetson":1,"28.1.1":1,"24.2.2":1}
,"mplement":{"deploy":1}
,"ollow":{"boot":1}
,"implementing":{"boot":1}
,"enabling":{"boot":1,"redundancy":1}
,"requires":{"modific":1}
,"modific":{"ation":1}
,"ation":{"components":1}
,"components":{"kernel":1,"functional":1}
,"script":{"once":1,"topic":1,"follows":1,"skip":1}
,"once":{"modifications":1,"bfs\u002Fkfs":1}
,"modifications":{"completed":1,"required":1,"update":1,"updates":1}
,"completed":{"flashed":1}
,"flashed":{"deployed":1,"production":1,"jetson":1}
,"initial":{"boot":1}
,"enabled":{"modifying":1,"boot":1}
,"modifying":{"linux":1,"existing":1,"tregaflash":1}
,"odify":{"linux":1}
,"default":{"emmc":1,"partition":1,"|--bctpartition":1,"name":1}
,"exposed":{"during":1}
,"during":{"runtime":1,"update":1}
,"navigate":{"kernel":1,"bootloader":1,"line":1,"l4t":1}
,"<kernel>\u002Fdrivers\u002Fmmc\u002Fhost\u002Fsdhci-tegra.c":{"comment":1}
,"comment":{"following":1,"entire":1}
,"following":{"line":1,"command":1,"location":1,"provides":1,"messages":1}
,"line":{"host->":1,"above":1,"python":1,"starting":1,"find":1,"tegraflash_parse_partitionlayout":1,"tegraflash_update_bfs_images":1,"<device":1}
,"host->":{"mmc->":1}
,"mmc->":{"caps2":1}
,"caps2":{"|=mmc_cap2_bootpart_noacc":1}
,"|=mmc_cap2_bootpart_noacc":{"depending":1}
,"depending":{"l4t":1,"user\u0027s":1}
,"version":{"line":1,"described":1,"identical":1,"referred":1,"bfs":1,"l4t":1,"update":1}
,"above":{"may":1,"modif":1}
,"enclosed":{"statement":1}
,"statement":{"case":1}
,"case":{"comment":1}
,"entire":{"block":1}
,"block":{"kernel":1}
,"booted":{"write-protected":1}
,"write-protected":{"boo":1}
,"boo":{"partitions":1}
,"available":{"-\u002Fdev\u002Fmmcblk0boot0":1,"bootloader\u002Ft210ref\u002Fcfg\u002Fgnu_linux_fastboot_emmc_ful":1}
,"-\u002Fdev\u002Fmmcblk0boot0":{"bct":1}
,"bfs0":{"bfs1":1,"corruption":1,"clobbered":1}
,"bfs1":{"-\u002Fdev\u002Fmmcblk0boot1":1,"***booting":1}
,"-\u002Fdev\u002Fmmcblk0boot1":{"bfs2":1}
,"bfs2":{"bfs3":1,"***booting":1}
,"bfs3":{"populating":1,"***booting":1,"corruption":1,"clobbered":1}
,"populating":{"bfs":1}
,"opulate":{"bfs":1}
,"configuratio":{"file":1}
,"automatically":{"generating":1,"generate":1}
,"generating":{"modifying":1}
,"existing":{"default":1}
,"configuratin":{"file":1}
,"configurat":{"ion":1}
,"ion":{"file":1}
,"directory":{"executing":1,"<l4t":1,"l4t":1}
,"executing":{"command":1,"updated":1}
,"command":{"<top>\u002Flinux_for_tegra":1,".\u002Fmkbctpart":1,"copy":1,"bct_1111":1,"syntax":1,"removable":1}
,"<top>\u002Flinux_for_tegra":{"\u002Fbootloader":1}
,"\u002Fbootloader":{"execute":1}
,".\u002Fmkbctpart":{"<newredundant.xml>":1,"new_config.xml":1,"bct_1111":1,"<rsa":1,"new_redundant_partition_config.xml":1,"bct_2211":1}
,"<newredundant.xml>":{"eplace":1,"instructed":1}
,"eplace":{"standard":1}
,"ith":{"<newredundant.xml>":1}
,"instructed":{"mkbctpart":1}
,"mkbctpart":{"modify":1,"overall":1,"generates":1,"utility":1,"offline":1,"syntax":1,"[options]":1,"takes":1}
,"bootloader\u002Ft210ref\u002Fcfg\u002Fgnu_linux_fastboot_emmc_ful":{"l.xml":1}
,"l.xml":{"bsp":1}
,"contains":{"partitioni":1,"tegraboot":1}
,"partitioni":{"information":1}
,"information":{"tegra":1,"bfs":1}
,"table":{"gpt":1}
,"gpt":{"partitions":1}
,"defined":{"gp1":1,"bct":1,"kernel":1,"app":1,"immediatel":1,"order":1}
,"gp1":{"visible":1,"located":1,"entry":1,"app":1}
,"visible":{"linux":1,"auses":1}
,"nvc":{"contains":1,"partition":1,"bootfileset":1,"rest":1,"matching":1,"bfs":1}
,"nvc-1":{"nvc-2":1,"bfs-1":1}
,"nvc-2":{"nvc-3":1,"bfs-2":1}
,"nvc-3":{"store":1,"bfs-3":1}
,"store":{"additiona":1}
,"additiona":{"tegraboot":1}
,"instances":{"redundancy":1}
,"partit":{"ions":1}
,"ions":{"defined":1,"crowded":1}
,"pt-1":{"pt-2":1}
,"pt-2":{"pt-3":1}
,"pt-3":{"contain":1}
,"layout":{"information":1,"partition":1}
,"indicate":{"beginn":1,"boot":1}
,"beginn":{"ing":1}
,"ing":{"bfs":1,"downloaded":1,"messages":1}
,"tbc":{"tbc-1":1,"rp1":1}
,"tbc-1":{"tbc-2":1,"rp1-1":1}
,"tbc-2":{"tbc-3":1,"rp1-2":1}
,"tbc-3":{"contain":1,"rp1-3":1}
,"cpu-portion":{"tegraboot":1}
,"rp1":{"rp1-1":1,"ebt":1}
,"rp1-1":{"rp1-2":1,"ebt-1":1}
,"rp1-2":{"rp1-3":1,"ebt-2":1}
,"rp1-3":{"contain":1,"ebt-3":1}
,"graboot":{"dtbs":1}
,"dtbs":{"partitions":1,"beginning":1,"defined":1}
,"ebt":{"ebt-1":1,"partitio":1,"wb0":1}
,"ebt-1":{"ebt-2":1,"wb0-1":1}
,"ebt-2":{"ebt-3":1,"wb0-2":1}
,"ebt-3":{"contain":1,"wb0-3":1}
,"condary":{"boot":1}
,"loaders":{"u-boot":1}
,"beginning":{"l4t":1,"kernel":1}
,"28.1.1":{"u-boot":1}
,"longer":{"part":1}
,"nly":{"cboot":1}
,"allowed":{"located":1}
,"partitio":{"u-boot":1}
,"(lnx)":{"secondary":1}
,"secondary":{"boot":1}
,"wb0":{"wb0-1":1,"bpf":1}
,"wb0-1":{"wb0-2":1,"bpf-1":1}
,"wb0-2":{"wb0-3":1,"bpf-2":1}
,"wb0-3":{"contain":1,"bpf-3":1}
,"warmboot":{"vector":1}
,"vector":{"partitions":1}
,"bpf":{"bpf-1":1,"tos":1}
,"bpf-1":{"bpf-2":1,"tos-1":1}
,"bpf-2":{"bpf-3":1,"tos-2":1}
,"bpf-3":{"contain":1,"tos-3":1}
,"microcode":{"partitions":1}
,"tos-1":{"tos-2":1,"nvc-2":1}
,"tos-2":{"tos-3":1,"nvc-3":1}
,"tos-3":{"contain":1,"gp1":1}
,"cure":{"monitor":1}
,"monitor":{"code":1}
,"code":{"partitions":1,"tegraflash":1}
,"dtb-1":{"dtb-2":1,"\u002Fdev\u002Fmmcblkp5":1,"clobbered":1}
,"dtb-2":{"dtb-3":1}
,"dtb-3":{"contain":1}
,"rnel":{"dtbs":1}
,"24.2.2":{"kernel":1}
,"app":{"partition":1,"entry":1,"kfs":1}
,"lnx":{"lnx-1":1,"{-1,-2,-3}":1,"kfs-1":1,"\u002Fdev\u002Fmmcblk0p":1}
,"lnx-1":{"lnx-2":1,"kfs-2":1,"\u002Fdetc\u002Fmmcblkp6":1}
,"lnx-2":{"lnx-3":1,"kfs-3":1,"clobbered":1}
,"lnx-3":{"contain":1,"example":1}
,"ther":{"linux":1}
,"user\u0027s":{"oice":1}
,"oice":{"dflt_kernel_image":1}
,"dflt_kernel_image":{"jetson-tx1.conf":1}
,"jetson-tx1.conf":{"file":1}
,"eks":{"eks-1":1}
,"eks-1":{"eks-2":1}
,"eks-2":{"eks-3":1}
,"eks-3":{"option":1}
,"option":{"future":1,"entries":1,"description":1}
,"future":{"verify":1}
,"immediatel":{"nvc":1}
,"first":{"within":1,"100kib":1,"healthy":1}
,"bootfiles":{"nvc":1}
,"combinations":{"defined":1}
,"order":{"nvc":1}
,"rest":{"verify":1}
,"sum":{"partitions":1}
,"sizes":{"nvc":1}
,"matching":{"bfs":1}
,"exceed":{"(boot0_si":1}
,"(boot0_si":{"mib)":1}
,"mib)":{"standard":1}
,"mib":{"modify":1,"boot0":1,"boot1":1}
,"gnu_linux_fastboot_emmc_full.xml":{"file":1}
,"move":{"app":1}
,"immediately":{"gp1":1}
,"rootfs":{"\u002Fdev\u002Fmmcblk0p1":1}
,"\u002Fdev\u002Fmmcblk0p1":{"verify":1,"unlike":1}
,"(dtb":{"lnx)":1}
,"lnx)":{"fined":1}
,"fined":{"app":1}
,"{-1,-2,-3}":{"beginning":1,"ending":1}
,"ending":{"kfs":1}
,"id=values":{"contigu":1}
,"contigu":{"ous":1}
,"ous":{"partition":1}
,"altered":{"original":1}
,"original":{"generation":1}
,"generation":{"mkbctpart":1,"follows":1}
,"overall":{"layout":1}
,"--pt":{"tbc":1}
,"bfs-1":{"--pt-1":1}
,"--pt-1":{"tbc-1":1}
,"bfs-2":{"--pt-2":1}
,"--pt-2":{"tbc-2":1}
,"bfs-3":{"--pt-3":1}
,"--pt-3":{"tbc-3":1}
,"--dtb":{"lnx":1}
,"kfs-1":{"--dtb-1":1}
,"--dtb-1":{"lnx-1":1}
,"kfs-2":{"--dtb-2":1}
,"--dtb-2":{"lnx-2":1}
,"kfs-3":{"--dtb-3":1}
,"--dtb-3":{"lnx-3":1}
,"example":{"complete":1,"flashing":1,"bfsblob":1,"cboot.bin":1,".\u002Fmkbctpart":1,"target":1,"standard":1,"copying":1,"navigate":1}
,"complete":{"partition":1}
,"<l4t":{"bsp>\u002Flinux_for_tegra\u002Fbootloader\u002Ft210ref\u002Fcf":1,"bsp>\u002Flinux_for_tegra\u002Fbootloader":1,"bsp>\u002Flinux_for_tegra\u002Fbootloader\u002Ft210ref\u002Fp2371":1,"bsp>\u002Flinux_for_tegra":1}
,"bsp>\u002Flinux_for_tegra\u002Fbootloader\u002Ft210ref\u002Fcf":{"gnu_linux_tegraboot_emmc_full.xml":1}
,"gnu_linux_tegraboot_emmc_full.xml":{"gnu_linux_tegraboot_emmc_full.xml.sav":1}
,"gnu_linux_tegraboot_emmc_full.xml.sav":{".\u002Fmkbctpart":1}
,"new_config.xml":{"necessary":1,"new_config":1}
,"new_config":{"xml":1}
,"xml":{"t210ref\u002Fcfg\u002Fgnu_linux_tegraboot_emmc_full.xml":1}
,"t210ref\u002Fcfg\u002Fgnu_linux_tegraboot_emmc_full.xml":{"point":1}
,"point":{"perform":1,"system":1}
,"perform":{"normal":1}
,"normal":{"operations":1}
,"operations":{"signing":1,"necessary":1}
,"signing":{"flashing":1}
,"auses":{"tegraboot":1,"root":1}
,"disappear":{"linux":1}
,"\u002Fdev\u002Fmmcblk0px":{"akes":1}
,"akes":{"partitions":1}
,"root":{"file":1}
,"stay":{"\u002Fdev\u002Fmmcblk0p1":1}
,"unlike":{"bfs":1}
,"\u002Fdev\u002Fmmcblk0p2":{"lnx":1}
,"\u002Fdev\u002Fmmcblk0p":{"dtb-1":1}
,"\u002Fdev\u002Fmmcblkp5":{"lnx-1":1}
,"\u002Fdetc\u002Fmmcblkp6":{"further":1}
,"further":{"modifications":1}
,"inform":{"loader":1}
,"location":{"new":1,"specified":1,"size":1,"<l4t":1}
,"tregaflash":{"script":1}
,"topic":{"apply":1,"development":1}
,"apply":{"l4t":1}
,"r28":{"releases":1}
,"releases":{"secureboot":1,"adding":1}
,"secureboot":{"used":1,"l4t":1,"enabling":1}
,"used":{"enable":1,"later":1,"next":1}
,"inter-operability":{"secureboot":1}
,"r24":{"releases":1}
,"adding":{"line":1}
,"python":{"code":1}
,"bsp>\u002Flinux_for_tegra\u002Fbootloader":{"dit":1,".\u002Fmkbctpart":1}
,"dit":{"tegraflash_internal.py":1}
,"tegraflash_internal.py":{"navigate":1}
,"def":{"tegraflash_secureflash":1}
,"tegraflash_secureflash":{"def":1,"line":1}
,"find":{"line":1}
,"tegraflash_parse_partitionlayout":{"add":1,"ensure":1}
,"add":{"new":1}
,"tegraflash_update_bfs_images":{"nder":1}
,"nder":{"following":1}
,"ensure":{"leading":1,"build":1}
,"leading":{"spaces":1}
,"spaces":{"enforced":1}
,"enforced":{"proper":1}
,"proper":{"indentation":1,"loading":1,"location":1}
,"indentation":{"congratulations":1}
,"congratulations":{"l4t":1}
,"r24.x.x":{"bsp":1,"u-boot":1}
,"inter-operate":{"secureboot":1}
,"flash":{"jetson":1,"new":1}
,"platform":{"above":1,"topic":1}
,"modif":{"ications":1}
,"ications":{"verify":1}
,"loading":{"functioning":1}
,"functioning":{"boot":1}
,"firmwares":{"linux":1,"kernel":1}
,"stem":{"ensure":1}
,"build":{"components":1,"new":1,"bct_2222":1}
,"functional":{"verify":1}
,"independently":{"prior":1}
,"prior":{"enabling":1,"update":1}
,"makes":{"emmc":1}
,"crowded":{"notify":1}
,"notify":{"flash.sh":1}
,"flash.sh":{"script":1}
,"skip":{"boot":1}
,"check":{"commenting":1}
,"commenting":{"bootpartsize=xxx":1}
,"bootpartsize=xxx":{"line":1}
,"<device":{"name>":1}
,"name>":{".conf":1}
,".conf":{"file":1}
,"preparing":{"new":1}
,"convenience":{"bct":1}
,"names":{"identified":1}
,"identified":{"four":1}
,"appended":{"numeric":1,"name":1}
,"numeric":{"values":1,"versions":1}
,"values":{"denote":1}
,"denote":{"boot":1}
,"described":{"bct":1}
,"versions":{"arbitrary":1,"bfs\u002Fkfs":1,"repe":1}
,"arbitrary":{"indicate":1}
,"process":{"example":1,"mkbctpart":1,"stateless":1}
,"fir":{"mware":1}
,"mware":{"redundancy":1}
,"identical":{"referred":1,"bct":1}
,"referred":{"bct_1111":1,"bct_2211":1}
,"bct_1111":{"boot":1,"device":1,"pkc":1,"--secur":1,"bct_1111":1,"<new":1,"0,1":1,"input":1,"command":1}
,"modified":{"contain":1}
,"two":{"new":1}
,"slots":{"positions":1,"specified":1,"bfs":1,"generates":1}
,"positions":{"boot":1}
,"bct_2211":{"likewise":1,"mkbctpart":1,"bfsblob.bin":1,"bfsblob_signed.bin":1,".\u002Fmkbctpart":1,"describes":1,"bfsblob":1,"new":1,"build":1,"0,1":1}
,"likewise":{"descriptive":1}
,"descriptive":{"purposes":1}
,"purposes":{"similar":1}
,"similar":{"nume":1}
,"nume":{"ric":1}
,"ric":{"value":1}
,"name":{"bct":1,"bfsblob":1,"kfs":1}
,"binary":{"extracting":1,"bct":1,"mcbctpart":1}
,"extracting":{"bct":1}
,"updating":{"boot":1,"bfs\u002Fkfs":1}
,"read":{"mainta":1,"bct_1111":1,"bct":1}
,"mainta":{"copy":1}
,"(bct_1111)":{"flashed":1}
,"production":{"device":1}
,"later":{"modifications":1,"version":1}
,"tries":{"(location":1}
,"(location":{"size":1}
,"size":{"hash":1}
,"hash":{"signature)":1,"value":1,"signatures":1}
,"signature)":{"within":1}
,"retrieve":{"binary":1}
,"place":{"production":1,"device":1}
,"forced-recovery":{"mod":1}
,"mod":{"instructions":1}
,"recov":{"ery":1}
,"ery":{"mode":1}
,"mode":{"setting":1}
,"setting":{"platform":1}
,"<bsp>\u002Flinux_for_tegra\u002Fbootloader\u002F\u2022":{"clear":1}
,"clear":{"system":1}
,".\u002Ftegraflash.py":{"--bl":1}
,"--bl":{"cboot.bin":1,"cboot.bin.signed":1}
,"cboot.bin":{"--chip":1,"{.signed}":1}
,"--chip":{"0x21":1}
,"0x21":{"--apple":1,"--applet":1,"pkc":1}
,"--apple":{"\u005Cnvtboot_recovery.bin":1}
,"\u005Cnvtboot_recovery.bin":{"--cmd":1}
,"--cmd":{"read":1}
,"cboot.bin.signed":{"--chip":1}
,"--applet":{"\u005Crcm_1_signed.rcm":1}
,"\u005Crcm_1_signed.rcm":{"--cmd":1}
,"--secur":{"edev":1}
,"edev":{"--skipuid":1}
,"--skipuid":{"preparing":1}
,"newer":{"l4t":1}
,"follow":{"download":1,"ing":1}
,"install":{"new":1}
,"shown":{"developer":1}
,"uild":{"new":1}
,"jetson-tx1":{"copy":1,"mmcblk0p1":1}
,"u-boot-dtb.bin":{"<l4t":1,"following":1}
,"bsp>\u002Flinux_for_tegra\u002Fbootloader\u002Ft210ref\u002Fp2371":{"-0000\u002F3":1,"-0000\u002F2":1}
,"-0000\u002F3":{"populate":1}
,"populate":{"boot":1}
,"binaries":{"flashable":1,"flashab":1,"bfs":1,"emmc":1}
,"flashable":{"ormat":1}
,"ormat":{"clear":1}
,".\u002Fflash.sh":{"--no-flash":1}
,"--no-flash":{"jetson-tx1":1,"0x21":1}
,"mmcblk0p1":{"pkc":1,"execute":1,"bootloader":1}
,"<rsa":{"key>":1,"private":1,"key":1}
,"key>":{"jetson-tx1":1,"bct_1111":1,"bct_2211":1}
,"<new":{"l4t":1,"filename>":1,"configuration":1}
,"bsp>\u002Flinux_for_tegra\u002Fbootloader\u002Fpreparing":{"new":1}
,"old":{"l4t":1}
,"-0000\u002F2":{"copy":1}
,"bsp>\u002Flinux_for_tegra\u002Fbootload":{"er\u002F3":1}
,"er\u002F3":{"populate":1}
,"bsp>\u002Flinux_for_tegra":{".\u002Fflash.sh":1}
,"0,1":{"bct_2211":1,"bct":1,"|--keyfile":1,"bct_2222":1}
,"generates":{"bct_2211":1,"updated":1,"new":1,"bct_2222":1}
,"bfsblob.bin":{"iles":1,"files":1}
,"iles":{"pkc":1}
,"_2211":{"mkbctpart":1}
,"bfsblob_signed.bin":{"files":1}
,"upon":{"completion":1}
,"completion":{"mkbctpart":1}
,"prints":{"download":1}
,"instruction":{"identifies":1,"identify":1}
,"identifies":{"locate":1}
,"locate":{"files":1}
,"regenerating":{"bct":1}
,"blob":{"images":1,"includes":1}
,"provides":{"host-based":1,"example":1}
,"mkbctpar":{"specify":1}
,"specify":{"new":1}
,"mcbctpart":{"utility":1}
,"rtition":{"file":1}
,"padded":{"boot":1}
,"provided":{"bct":1,"example":1}
,"reads":{"bct":1,"new":1}
,"builds":{"bfsblob":1}
,"bfsblob":{"{signed}":1,"example":1,"{_signed}":1,"blob":1,"bfsblob":1,"named":1,"{_signe":1,"additional":1}
,"{signed}":{".bin":1}
,".bin":{"calculates":1,"file":1,"|--tegratype":1,"tegraboot":1,"bct_2211":1,"<dtb":1,"target":1,"updated":1,"of=\u002Fdev\u002Fmmcblk0boot0":1,"flash":1,"of=\u002Fdev\u002Fmmcblk0boot1":1}
,"calculates":{"hashes":1}
,"hashes":{"signatures":1}
,"signatures":{"updates":1,"boot":1}
,"spec":{"ified":1}
,"ified":{"option":1}
,"known":{"slots":1}
,"dification":{"remain":1}
,"remain":{"assuming":1}
,"assuming":{"location":1}
,"bei":{"replaced":1}
,"replaced":{"writes":1}
,"syntax":{"follows":1}
,"[options]":{"[new":1}
,"[new":{"bct":1}
,"file]":{"command":1}
,"description":{"default":1}
,"|--bctpartition":{"<input":1}
,"<input":{"bct":1}
,"file>":{"specifies":1,"bct_1111":1,".dtb":1}
,"specifies":{"bct":1,"bfs":1,"rsa":1,"tegra":1,"bootloeader":1,"new":1}
,"filename":{"bct.dump":1,"none":1,"include":1,"tegraboot":1,"dated":1}
,"bct.dump":{"|--instances":1}
,"|--instances":{"<bfs":1}
,"<bfs":{"update":1}
,"csv>":{"specifies":1}
,"instance":{"0,1":1,"example":1}
,"|--keyfile":{"<rsa":1}
,"private":{"key":1}
,"key":{"filename>":1,"filename":1,"file>":1}
,"filename>":{"specifies":1}
,"none":{"|--listbcts":1,"|--verbose":1}
,"|--listbcts":{"specifies":1}
,"n\u002Fa":{"|--paddedfile":1}
,"|--paddedfile":{"<flashable":1}
,"<flashable":{"bfs":1}
,"include":{"tegraboot":1}
,"pfs":{"image":1}
,"downloaded":{"flashed":1,"device":1,"bct":1}
,"{_signed}":{".bin":1}
,"|--tegratype":{"<tegra":1}
,"<tegra":{"type>":1}
,"type>":{"specifies":1}
,"chip":{"t210":1}
,"t210":{"|--bootloader":1}
,"|--bootloader":{"<new":1}
,"bootloeader":{"filename":1}
,"{.signed}":{"|--genconfig":1,"example":1}
,"|--genconfig":{"<new":1}
,"|--verbose":{"returns":1}
,"returns":{"verbose":1}
,"verbose":{"output":1}
,"output":{"new":1,"filename":1}
,"dated":{"bct":1}
,"includes":{"tegraboot":1}
,"new_redundant_partition_config.xml":{".\u002Fmkbctpart":1}
,"input":{"describing":1}
,"describing":{"four":1}
,"blobs":{"ori":1}
,"ori":{"ginally":1}
,"ginally":{"flashed":1}
,"describes":{"bfs":1}
,"version-2":{"slots":1}
,"version-1":{"slots":1}
,"named":{"bfsblob":1}
,"<dtb":{"file>":1}
,".dtb":{"{encrypt":1}
,"{encrypt":{"signed}":1}
,"signed}":{"downloaded":1,"of=\u002Fdev\u002Fmmcblk0p2":1,"of=\u002Fdev\u002Fmmcblk0p":1,"of=\u002Fdev\u002Fmmcblk0p5":1,"overwrites":1,"of=\u002Fdev\u002Fmmcblk0p8":1,"of=\u002Fdev\u002Fmmcblk0p11":1}
,"expects":{"bfs":1}
,"signed":{"unsigned":1}
,"unsigned":{"exist":1}
,"exist":{"directory":1}
,"<bsp>\u002Flinux_for_tegra\u002Fbootloaer\u002Fpreparing":{"new":1}
,"flashab":{"format":1}
,"format":{"clear":1}
,"commands":{"<l4t":1,"overwrite":1}
,"print":{"download":1}
,"identify":{"locate":1}
,"downloading":{"updated":1}
,"using":{"scp":1}
,"scp":{"command":1}
,"removable":{"storage":1}
,"storage":{"device":1}
,"opy":{"updated":1}
,"{_signe":{".bin":1}
,"r28.x.x":{"download":1}
,"boot.img":{"target":1,"{encrypt":1}
,"nto":{"mmc":1}
,"mmc":{"following":1}
,"overwrite":{"bct":1}
,"emm":{"device":1}
,"sudo":{"bash":1}
,"bash":{"enter":1}
,"enter":{"password":1}
,"password":{"become":1}
,"become":{"superus":1,"superuser":1}
,"superus":{"echo":1,"if=\u002Fdev\u002Fzero":1,"if=\u002Fbin\u002Fls":1}
,"echo":{"\u002Fsys\u002Fblock\u002Fmmcblk0boot0\u002Fforce_ro":1,">\u002Fsys\u002Fblock\u002Fmmcblk0boot0\u002Fforce_ro":1,"\u002Fsys\u002Fblock\u002Fmmcblk0boot1\u002Fforce_ro":1,">\u002Fsys\u002Fblock\u002Fmmcblk0boot1\u002Fforce_ro":1}
,"\u002Fsys\u002Fblock\u002Fmmcblk0boot0\u002Fforce_ro":{"if=bct_2211":1,"if=bct_2222":1,"if=\u002Fbin\u002Fls":1}
,"if=bct_2211":{"of=\u002Fdev\u002Fmmcblk0boot0":1}
,"of=\u002Fdev\u002Fmmcblk0boot0":{"if=bfsblob":1,"seek=2048":1,"seek=5120":1,"echo":1,"count=20":1,"seek=3048":1}
,"if=bfsblob":{"{_signed}":1}
,"seek=2048":{"if=bfsblob":1}
,"seek=5120":{"if=<new":1}
,"if=<new":{"kernel":1}
,"dtb>":{"{encrypt":1}
,"of=\u002Fdev\u002Fmmcblk0p2":{"if=boot.img":1}
,"if=boot.img":{"{encrypt":1}
,"of=\u002Fdev\u002Fmmcblk0p":{"if=<new":1,"sync":1}
,"of=\u002Fdev\u002Fmmcblk0p5":{"if=boot.img":1,"count=1":1}
,"sync":{"sync":1,"echo":1,"<reset":1}
,">\u002Fsys\u002Fblock\u002Fmmcblk0boot0\u002Fforce_ro":{"note":1,"echo":1}
,"copying":{"boot.img":1}
,"syste":{"running":1}
,"running":{"l4t":1}
,"28.1.0":{"later":1}
,"included":{"bfsblob":1}
,"additional":{"operations":1}
,"*.encrypt":{"non-pkc":1}
,"non-pkc":{"protected":1}
,"*.signed":{"pkc":1}
,"recovering":{"error":1}
,"error":{"during":1}
,"recover":{"error":1}
,"bfs\u002Fkfs":{"bfs\u002Fkfs":1,"intact":1,"once":1,"updated":1,"used":1,"new":1,"older":1,"redundancies":1,"clobbered":1}
,"intact":{"abl":1,"oot":1}
,"abl":{"boot":1}
,"epeat":{"update":1}
,"stateless":{"res":1}
,"res":{"tart":1}
,"tart":{"without":1}
,"without":{"knowing":1}
,"knowing":{"previous":1}
,"previous":{"update":1}
,"status":{"updating":1}
,"successfully":{"new":1}
,"cycle":{"eave":1}
,"eave":{"target":1}
,"older":{"version":1}
,"repe":{"update":1}
,"numbers":{"changed":1}
,"changed":{"example":1}
,"environment":{"built":1}
,"built":{"bct_2211":1}
,"bct_2222":{"clear":1,"mkbctpart":1,"bfsblob.bin":1,"bfsblob_signe":1,"fbsblob":1}
,"_2222":{"mkbctpart":1}
,"bfsblob_signe":{"d.bin":1}
,"d.bin":{"files":1}
,"fbsblob":{"{_signed}":1}
,"superuser":{"echo":1}
,"if=bct_2222":{"of=\u002Fdev\u002Fmmcblk0boot0":1}
,"\u002Fsys\u002Fblock\u002Fmmcblk0boot1\u002Fforce_ro":{"if=bfsblob":1,"if=\u002Fbin\u002Fls":1}
,"of=\u002Fdev\u002Fmmcblk0boot1":{"if=bfsblob":1,"seek=3072":1}
,"seek=3072":{"if=<new":1,"cou":1}
,"of=\u002Fdev\u002Fmmcblk0p8":{"if=boot.img":1}
,"of=\u002Fdev\u002Fmmcblk0p11":{"if=boot.img":1}
,">\u002Fsys\u002Fblock\u002Fmmcblk0boot1\u002Fforce_ro":{"testing":1}
,"testing":{"bfs\u002Fkfs":1,"bct":1,"bfs0":1,"kfs1":1,"kfs2":1,"bfs3":1}
,"redundancies":{"testing":1}
,"ach":{"bct":1}
,"behaves":{"sub-partition":1}
,"sub-partition":{"long":1}
,"long":{"valid":1}
,"rom":{"detect":1,"quietly":1}
,"detect":{"target":1,"first":1}
,"configure":{"properly":1,"system":1}
,"properly":{"sudo":1,"testing":1}
,"if=\u002Fbin\u002Fls":{"of=\u002Fdev\u002Fmmcblk0boot0":1,"of=\u002Fdev\u002Fmmcblk0p9":1,"of=\u002Fdev\u002Fmmcblk0boot1":1}
,"count=20":{"0kib":1}
,"0kib":{"bct":1}
,"clobbered":{"sync":1,"boot":1,"e-flash":1}
,"<reset":{"board>":1}
,"board>":{"even":1,"following":1,"follow":1,"point":1}
,"100kib":{"bct":1}
,"quietly":{"detect":1}
,"healthy":{"bct":1}
,"corruption":{"sudo":1}
,"seek=3048":{"cou":1}
,"cou":{"nt=1":1}
,"nt=1":{"bfs0":1,"bfs3":1}
,"messages":{"displayed":1}
,"displayed":{"uart":1}
,"uart":{"log":1}
,"log":{"***failing":1}
,"***failing":{"bfs1":1,"kfs2":1,"kfs3":1}
,"***booting":{"bfs1":1,"kfs1":1,"bfs2":1,"kfs2":1,"bfs3":1,"kfs3":1}
,"kfs1":{"testing":1,"corruption":1}
,"if=\u002Fdev\u002Fzero":{"of=\u002Fdev\u002Fmmcblk0p5":1}
,"count=1":{"dtb-1":1}
,"kfs2":{"***booting":1,"testing":1,"corruption":1}
,"of=\u002Fdev\u002Fmmcblk0p9":{"count=10":1}
,"count=10":{"lnx-2":1}
,"kfs3":{"***booting":1,"testing":1}
,"halted":{"bfs\u002Fkfs":1}
,"e-flash":{"update":1}
}
;Search.control.loadWordPairs(pairs);
