var pairs =
{
"security":{"section":1,"bdk":1}
,"section":{"explains":1}
,"explains":{"security":1}
,"bdk":{"validation":1}
,"validation":{"binaries":1}
,"binaries":{"binaries":1,"involved":1,"associated":1,"vailable":1}
,"involved":{"boot":1}
,"boot":{"process":1,"boot":1,"binaries":1,"binary":1}
,"process":{"ave":1}
,"ave":{"generic":1}
,"generic":{"header":1}
,"header":{"(except":1,"header":1,"stores":1}
,"(except":{"mb1)":1}
,"mb1)":{"binary":1}
,"binary":{"ppended":1,"used":1,"signing":1,"signed":1,"signed\u002Fencrypted":1}
,"ppended":{"generic":1}
,"stores":{"signature":1}
,"signature":{"binary":1}
,"used":{"vali":1}
,"vali":{"dation":1}
,"dation":{"secure":1}
,"secure":{"boot":1}
,"associated":{"signing":1}
,"signing":{"following":1,"aut":1,"authority":1}
,"following":{"table":1}
,"table":{"summarizes":1}
,"summarizes":{"boot":1}
,"vailable":{"tegra":1}
,"tegra":{"respective":1}
,"respective":{"signing":1}
,"aut":{"horities":1}
,"horities":{"boot":1}
,"authority":{"brbct":1}
,"brbct":{"oem":1}
,"oem":{"generated":1,"mb1bct":1,"mb1":1,"sign\u002Fencrypt":1,"gn\u002Fencrypt":1,"owned":1,"tboot":1,"signed\u002Fencrypted":1,"uboot\u002Fkernel":1}
,"generated":{"binary":1}
,"signed":{"oem":1,"nvidia":1}
,"mb1bct":{"oem":1}
,"mb1":{"idia":1}
,"idia":{"provided":1}
,"provided":{"binary":1,"ref":1,"reference":1}
,"signed\u002Fencrypted":{"nvidia":1,"separately":1,"oem":1,"tboot":1,"cboot":1,"tos":1,"sc7-fw":1}
,"nvidia":{"oem":1,"provided":1}
,"sign\u002Fencrypt":{"again":1}
,"again":{"mts-preboot":1,"mts-package":1,"spe-can-fw":1,"bl-dtb":1}
,"mts-preboot":{"idia":1}
,"mts-package":{"(mts-dmce":1}
,"(mts-dmce":{"mts-proper)":1}
,"mts-proper)":{"signed\u002Fencrypted":1}
,"separately":{"nvidia":1}
,"gn\u002Fencrypt":{"again":1}
,"spe-can-fw":{"oem":1}
,"owned":{"binary":1,"signed\u002Fencrypted":1}
,"tboot":{"-bpmp":1,"-cpu":1}
,"-bpmp":{"idia":1}
,"ref":{"erence":1}
,"erence":{"code":1}
,"code":{"ultimately":1,"signed\u002Fencrypted":1}
,"ultimately":{"oem":1}
,"-cpu":{"nvidia":1}
,"reference":{"code":1}
,"cboot":{"nvidia":1}
,"tos":{"nvidia":1}
,"sc7-fw":{"nvidia":1}
,"bl-dtb":{"nvidia":1}
,"uboot\u002Fkernel":{"nvidia-adapted":1}
,"nvidia-adapted":{"oss":1}
,"oss":{"code":1}
}
;Search.control.loadWordPairs(pairs);
