var pairs =
{
"oot":{"customization":1,"scan":1,"execute":1}
,"customization":{"u-boot":1}
,"u-boot":{"default":1,"build":1,"source":1,"kernel":1,"flashing":1,"reference":1,"binaries":1,"file":1,"perform":1,"sources":1,"executing":1,"l4t":1,"full":1,"internal":1,"fetches":1,"specify":1,"flash":1,"xecute":1,"aside":1,"ternal":1,"partition":1,"u-boot":1,"used":1,"expects":1,"functionality":1,"performs":1,"boot":1,"ncludes":1,"allow":1,"delays":1,"runtime":1,"environment":1,"gins":1,"shell":1,"executes":1,"pauses":1,"scans":1,"searches":1,"search":1,"complain":1,"script":1,"starts":1,"uses":1,"binary":1,"cause":1,"runs":1,"using":1,"begins":1,"automatic":1,"execute":1,"fw_env":1,"consult":1,"documentation":1,"interrupt":1,"during":1,"connect":1,"sign":1,"help":1,"nvironment":1,"sends":1}
,"default":{"boot":1,"option":1,"directory":1,"bootin":1,"u-boot":1,"configuration":1,"scan_dev_for_boot_part":1,"values":1,"l4t":1,"environment":1,"value":1,"setenv":1}
,"boot":{"loader":1,"time":1,"configuration":1,"internal":1,"partition":1,"loaders":1,"device":1,"environmen":1,"replace":1,"ternal":1,"jetson":1,"card":1,"nfs":1,"sequence":1,"infor":1,"command":1,"scripts":1,"conf":1,"script":1,"seque":1,"process":1,"specific":1,"systems":1,"files":1,"scri":1,"using":1,"menu":1,"proce":1,"interrupt":1,"proc":1,"<dir>":1}
,"loader":{"nvidia":1}
,"nvidia":{"tegra":1,"kernel":1}
,"tegra":{"linux":1,"developer":1}
,"linux":{"driver":1,"distributions":1,"distribution":1,"host":1}
,"driver":{"package":1}
,"package":{"(l4t)":1,"tegra":1,"backup":1}
,"(l4t)":{"requirements":1,"download":1}
,"requirements":{"software":1,"prerequisites":1,"value":1}
,"software":{"requirements":1,"layout":1}
,"prerequisites":{"include":1}
,"include":{"linux-based":1,"replacing":1,"tegra-common-usb-gadget.h":1,"mmc0":1}
,"linux-based":{"host":1}
,"host":{"system":1,"ystem":1,"runs":1,"l4t":1}
,"system":{"unctionality":1,"ater":1,"downloading":1,"vidia":1,"copy":1,"replace":1,"connect":1,"reboot":1,"target":1,"enter":1,"copying":1,"required":1,"bootloader\u002F<platform":1,"hardware":1,"boot":1,"layouts":1,"based":1,"known":1,"detect":1,"modify":1,"file":1}
,"unctionality":{"u-boot":1}
,"build":{"flashing":1,"dtc":1,"linux":1,"u-boot":1,"environment":1}
,"flashing":{"utilities":1,"u-boot":1,"flashing":1,"copy":1,"reference":1,"file":1,"flash.sh":1,"time":1,"process":1,"board":1,"tools":1,"directo":1}
,"utilities":{"validated":1}
,"validated":{"using":1}
,"using":{"ubuntu":1,"u-boot":1,"scp":1,"dhcp":1,"extlinux":1,"serial":1,"l4t":1}
,"ubuntu":{"<os_ver_host":1}
,"<os_ver_host":{"host":1}
,"ater":{"versions":1}
,"versions":{"ubun":1}
,"ubun":{"alternative":1}
,"alternative":{"linux":1}
,"distributions":{"may":1}
,"may":{"work":1,"necessary":1,"know":1,"interrupt":1,"separate":1,"variab":1,"ignored":1}
,"work":{"host-specific":1,"connections":1}
,"host-specific":{"modifications":1}
,"modifications":{"tegra":1}
,"download":{"install":1,"linaro":1,"build":1,"dtc":1,"syslinux":1,"u-boot":1}
,"install":{"latest":1,"default":1,"install":1,"specific":1,"prefix=\u002Fusr\u002Flocal":1}
,"latest":{"l4t":1}
,"l4t":{"package":1,"prerequisite":1,"release":1,"tree":1,"image":1,"flashing":1,"partition":1,"rtition":1,"includes":1,"target":1}
,"developer":{"http:\u002F\u002Fdeveloper.nvidia.com\u002Flinux-tegra":1}
,"http:\u002F\u002Fdeveloper.nvidia.com\u002Flinux-tegra":{"device":1}
,"device":{"tree":1,"containing":1,"<host":1,"datasheet":1,"information":1,"last":1,"u-boot":1,"device":1,"boot":1,"cases":1,"connect":1,"host":1,"disconnect":1,"jetson":1,"running":1,"target":1,"nfs":1,"looks":1,"<rootfs>\u002Fboot\u002Fextlinux":1,"contains":1,"consequently":1,"plicitly":1,"nsequently":1,"pxe":1,"restrictive":1,"partition":1,"list":1}
,"tree":{"compiler":1,"files":1,"dtc":1,"checkout":1,"copy":1,"reside":1,"build":1,"blob":1}
,"compiler":{"(dtc":1,"pre-built":1,"device":1}
,"(dtc":{"dtc":1,"built":1}
,"dtc":{"used":1,"packages":1,"support":1,"source":1,"binary":1,"building":1,"filename":1,"\u002Fusr\u002Flocal\u002Fbin":1,"rest":1,"executing":1}
,"used":{"compile":1,"boot":1,"cboot":1,"partitions":1,"contain":1,"reads":1,"card":1,"initially":1}
,"compile":{"device":1}
,"files":{"contained":1,"linux_for_tegra\u002F<target_board>":1,"exist":1,"app":1,"<app":1,"using":1,"\u002Fboot":1,"root":1,"u-boot":1,"test":1,"provided":1,"similar":1,"host":1,"certain":1,"partition":1,"file":1,"found":1,"replace":1,"script":1}
,"contained":{"u-boot":1}
,"source":{"tree":1,"building":1,"information":1,"<source_sync.sh_location>\u002Fsources\u002Fu-boot_source":1,"code":1,"download":1}
,"packages":{"available":1}
,"available":{"standard":1,"https:\u002F\u002Fwww.linaro.org\u002Fdownloads\u002F\u2022":1,"devices":1}
,"standard":{"linux":1,"text-format":1}
,"distribution":{"ckage":1}
,"ckage":{"management":1}
,"management":{"systems":1,"(aspm":1}
,"systems":{"apt":1,"kernel":1,"using":1,"gnu_linux_tegraboot_emmc_full.xml":1,"flash_l4t_t186.xml":1,"boot":1,"flexibility":1,"custom":1,"example":1}
,"apt":{"updated":1}
,"updated":{"version":1,"u-boot":1}
,"version":{"dtc":1,"\u2011boot":1,"u-boot":1}
,"support":{"features":1,"widest":1,"takes":1,"u-boot":1,"reduce":1,"remove":1}
,"features":{"required":1,"earches":1}
,"required":{"\u2011boot":1,"appropriate":1,"flash.sh":1,"files":1,"initi":1}
,"\u2011boot":{"makefile":1,"source":1,"suitable":1,"directed":1,"terminal":1,"environment":1,"example":1,"<new_value>":1}
,"makefile":{"detailed":1}
,"detailed":{"example":1}
,"example":{"building":1,"export":1,"configuration":1,"extlinux.conf":1,"\u002Fboot":1,"utput":1,"list":1,"output":1,"print":1,"modify":1}
,"building":{"dtc":1,"device":1,"kernel":1,"u-boot":1,"nvidia":1}
,"pre-built":{"dtc":1}
,"binary":{"included":1,"built":1,"default":1}
,"included":{"kernel":1}
,"kernel":{"directory":1,"sources":1,"dtbs":1,"source":1,"adding":1,"root":1,"u-boot":1,"device":1,"command":1,"looks":1,"mount":1,"<platform>":1,"installed":1,"(lnx)":1,"obtain":1,"tx1":1,"files":1,"(image":1,"replace":1,"custom":1,"procedure":1,"systems":1,"image":1,"without":1,"boot":1,"filenames":1,"file":1}
,"directory":{"release":1,"build":1,"becomes":1,"[-n":1,"flash.sh":1,"full":1,"dtc":1,"$home":1,"execute":1,"bin":1,"reboot":1,"card":1,"host":1,"bootable":1,"name":1,"u-boot":1,"structure":1,"tructure":1,"list":1,"ist":1,"contents":1,"file":1}
,"release":{"binary":1,"sources":1,"package":1,"run":1,"tag":1,"notes":1,"supported":1}
,"built":{"rom":1,"source":1,"u-boot":1}
,"rom":{"kernel":1}
,"sources":{"release":1,"located":1,"space":1,"run":1,"disabling":1}
,"located":{"scripts\u002Fdtc":1,"lba":1,"last":1,"tools\u002Fenv":1,"host":1}
,"scripts\u002Fdtc":{"directory":1}
,"dtbs":{"target":1}
,"target":{"download":1,"device":1,"system":1,"<rootfs>\u002Fboot\u002Fextlinux\u002Fextlinux.conf":1,"mmc":1}
,"linaro":{"aarch64":1}
,"aarch64":{"toolchain":1}
,"toolchain":{"available":1}
,"https:\u002F\u002Fwww.linaro.org\u002Fdownloads\u002F\u2022":{"\u2011boot":1}
,"information":{"downloading":1,"ting":1,"following":1,"prevent":1,"primary":1}
,"downloading":{"building":1,"kernel":1}
,"ting":{"root":1}
,"root":{"file":1,"filesystem":1,"filesystem-on-ip-network":1,"filesy":1,"<dir>":1}
,"file":{"system":1,"ystem":1,"linux_for_tegra\u002Fbootloader\u002F<platform":1,"kernel":1,"selected":1,"contains":1,"cause":1,"causes":1,"tx1":1,"imit":1,"note":1,"(extlinux":1,"following":1,"tx2":1,"building":1,"u-boot":1,"boots":1,"user":1,"extlinux.conf":1,"board":1,"defines":1,"already":1,"host":1,"data":1,"rather":1,"generate":1,"tells":1,"configured":1,"remove":1,"cated":1,"located":1,"(as":1}
,"adding":{"compiled":1}
,"compiled":{"kernel":1}
,"ystem":{"downloading":1,"$cp":1}
,"reference":{"platform":1,"platfor":1}
,"platform":{"download":1,"<board_and_rev>":1,"execute":1,"<board>":1}
,"vidia":{"offers":1}
,"offers":{"git":1}
,"git":{"repository":1,"tag":1,"clone":1}
,"repository":{"containing":1}
,"containing":{"sourc":1,"root":1,"boot":1,"following":1}
,"sourc":{"code":1}
,"code":{"version":1,"note":1,"executing":1,"value":1,"u-boot":1,"variable":1,"modify":1}
,"suitable":{"l4t":1}
,"prerequisite":{"over-writing":1}
,"over-writing":{"u-boot":1}
,"binaries":{"extracted":1}
,"extracted":{"l4t":1,"saved":1}
,"backup":{"original":1,"located":1}
,"original":{"u-boot":1}
,"linux_for_tegra\u002Fbootloader\u002F<platform":{">\u002F<board_and_rev":1}
,">\u002F<board_and_rev":{">\u002Fwhere":1,"<board_and_rev>":1,">\u002Fextlinux.conf.emmc":1}
,">\u002Fwhere":{"<platform>":1}
,"<platform>":{"soc":1,"mmcblk0p1":1}
,"soc":{"name":1}
,"name":{"platform":1,"provided":1,"$git":1,"local":1,"u-boot":1,"known":1,"filesystem":1}
,"<board_and_rev>":{"jetson":1}
,"jetson":{"tx1":1,"tx2":1,"\u002Ftx2":1,"tx2i":1}
,"tx1":{"p2371-2180":1,"$sudo":1,"tx2":1,"systems":1}
,"p2371-2180":{"jetson":1}
,"tx2":{"\u002Ftx2i":1,"$sudo":1,"systems":1,"p2771-000":1,"p2771-0000\u002F500":1}
,"\u002Ftx2i":{"p2771-000":1,"p2771-0000-500":1,"p2771-0000":1,"system":1}
,"p2771-000":{"-500":1,"optimizing":1,"jetson":1,"0-500":1}
,"-500":{"download":1,"flashing":1,"<board_and_rev>":1,"jetson":1}
,"perform":{"either":1,"foll":1}
,"either":{"following":1,"case":1}
,"following":{"options":1,"command":1,"storage":1,"files":1,"kernel":1,"tx1":1,"git":1,"directories":1,"order":1,"directory":1,"uses":1,"ocation":1,"values":1,"value":1,"table":1,"variables":1,"places":1,"provides":1,"env":1,"keywords":1,"mmand":1}
,"options":{"execute":1,"allowed":1}
,"execute":{"following":1,"$make":1,"modifying":1,"empty":1,"<scan_dev_for_ex":1,"u-boot":1,"commands":1,"program":1,"sequence":1,"printenv":1}
,"command":{"$git":1,"linux":1,"line":1,"jetson":1,"path":1,"$sudo":1,"attach":1,"read":1,"lines":1,"<bootcmd>":1,"target":1,"functions":1,"mmc":1,"ext2ls":1,"printenv":1,"setenv":1,"saveenv":1}
,"$git":{"clone":1,"checkout":1}
,"clone":{"git:\u002F\u002Fnv-tegra.nvidia.com\u002F3rdparty\u002Fu-boot.git":1,"command":1,"git:\u002F\u002Fgit.kernel.org\u002Fpub\u002Fscm\u002Futils\u002Fdtc":1}
,"git:\u002F\u002Fnv-tegra.nvidia.com\u002F3rdparty\u002Fu-boot.git":{"source_sync.sh":1}
,"source_sync.sh":{"script":1,"without":1}
,"script":{"l4t":1,"prompts":1,"sync":1,"passing":1,"flashes":1,"mount":1,"creates":1,"treats":1,"adds":1,"explicitly":1,"var":1,"parse":1,"simpler":1,"hard":1,"search":1,"commands":1,"scan_dev_for_scripts":1,"found":1,"executed":1,"boot_scripts":1,"names":1,"name":1}
,"run":{"source_sync.sh":1,"script":1,"either":1}
,"without":{"parameters":1,"flashing":1}
,"parameters":{"script":1,"control":1}
,"prompts":{"<tag_name":1}
,"<tag_name":{"release":1,"follows":1,"sync":1}
,"tag":{"name":1}
,"provided":{"release":1,"script":1,"l4t":1}
,"notes":{"option":1,"build":1}
,"option":{"source_sync":1,"provided":1,"identify":1,"recommended":1}
,"source_sync":{"syncs":1}
,"syncs":{"kernel":1}
,"space":{"options":1,"used":1}
,"allowed":{"default":1}
,"sync":{"kernel":1,"source":1}
,"passing":{"<tag_name":1}
,"follows":{"$cd":1,"<dir>":1,"stdout=serial":1}
,"$cd":{"<your_l4t_root>\u002Flinux_for_tegra":1,"dtc":1}
,"<your_l4t_root>\u002Flinux_for_tegra":{"$.\u002Fsource_sync.sh":1}
,"$.\u002Fsource_sync.sh":{"<tag_name":1}
,"<source_sync.sh_location>\u002Fsources\u002Fu-boot_source":{"<uboot_src_dir>":1}
,"<uboot_src_dir>":{"directory":1}
,"becomes":{"<your_l4t_root>\u002Flinux_for_tegra\u002Fsources\u002Fu-boot_sou":1}
,"<your_l4t_root>\u002Flinux_for_tegra\u002Fsources\u002Fu-boot_sou":{"rce":1}
,"rce":{"note":1,"interrupting":1}
,"note":{"rest":1,"option":1,"kernel":1,"boot0":1,"total":1,"flash.sh":1,"ish":1,"although":1,"entries":1,"default":1}
,"rest":{"instructions":1,"procedure":1}
,"instructions":{"assume":1}
,"assume":{"current":1}
,"current":{"working":1}
,"working":{"director":1,"directory":1}
,"director":{"u-boot":1}
,"checkout":{"git":1,"<branch_name>":1}
,"<branch_name>":{"<tag_name>":1,"name":1}
,"<tag_name>":{"<branch_name>":1,"release":1}
,"local":{"branch":1,"network":1,"command":1}
,"branch":{"<tag_name>":1}
,"environment":{"$export":1,"configuration":1,"u-boot":1,"variables":1,"variable":1,"values":1,"reset":1,"interactively":1,"data":1,"debugging":1,"examples":1,"print":1,"execute":1,"preserved":1}
,"$export":{"cross_compile=<your_toolchain_location>":1}
,"cross_compile=<your_toolchain_location>":{"example":1}
,"export":{"cross_compile=aarch64-linux-gnu-4":1}
,"cross_compile=aarch64-linux-gnu-4":{"build":1}
,"executing":{"$make":1,"script":1,"following":1,"automatic":1,"<scan_dev_for_scripts>":1,"attempts":1,"interrupt":1}
,"$make":{"distclean":1,"<board_and_rev":1,"<board_and_rev>":1,"install":1}
,"distclean":{"$make":1}
,"<board_and_rev":{">_defconfig":1}
,">_defconfig":{"$make":1,"config_pci_tegra":1,"config_pcieaspm":1,"config_pcieaspm_powersave=y":1}
,"p2771-0000-500":{"flashing":1}
,"copy":{"updated":1,"new":1,"root":1,"always":1,"environm":1}
,"$cp":{"<uboot_src_dir>\u002Fu-boot":1}
,"<uboot_src_dir>\u002Fu-boot":{".bin":1}
,".bin":{".dtb":1}
,".dtb":{",-dtb.bin}":1}
,",-dtb.bin}":{"\u005C<your_l4t_root>\u002Flinux_for_tegra\u002Fbootloader\u002F<platform":1}
,"\u005C<your_l4t_root>\u002Flinux_for_tegra\u002Fbootloader\u002F<platform":{">\u002F<board_and_rev":1}
,"p2771-0000":{"-500":1}
,"full":{"l4t":1,"pathname":1,"internal":1,"list":1}
,"image":{"flash":1,"reference":1,"above":1,"file":1,"user":1,"filename":1,"printing":1}
,"flash":{"u-boot":1,"-boot":1,"full":1,"new":1,"memory":1,"following":1,"during":1,"chips":1,"image":1}
,"internal":{"emmc":1}
,"emmc":{"boot":1,"card":1,"elect":1,"$sudo":1,"partition":1,"hardware":1,"parameter":1,"usable":1,"device":1,"root":1,"steps":1,"usb":1,"mmc1":1}
,"time":{"u-boot":1,"default":1,"initialize":1,"constrained":1,"orage":1,"onfigure":1,"changes":1,"disable":1,"enable":1,"user":1,"\u2011boot":1,"following":1,"replace":1,"thi":1,"flashing":1,"compile-time":1,"modify":1,"remove":1,"may":1,"list":1}
,"fetches":{"boot":1}
,"configuration":{"file":1,"files":1,"extlinux.conf":1,"ile":1,"enables":1,"u-boot":1,"dhcp":1}
,"reside":{"following":1}
,"storage":{"devices":1,"device":1,"emmc":1,"network":1,"evic":1,"devi":1}
,"devices":{"used":1,"following":1,"boot":1,"required":1,"until":1,"network":1,"u-boot":1}
,"card":{"executing":1,"elect":1,"$sudo":1,"usb":1,"internal":1,"slot":1}
,"flashes":{"u-boot":1,"following":1,"kernel":1}
,"specify":{"command-line":1}
,"command-line":{"option":1}
,"identify":{"storage":1}
,"filesystem":{"required":1,"flash":1,"internal":1,"card":1,"nfs":1,"<nfs_directory>":1,"<target":1,"alongs":1,"size":1,"partition":1,"app":1,"storage":1,"flashed":1,"external":1,"device":1,"directories":1,"default":1,"example":1}
,"appropriate":{"boot":1,"variant":1,"fla":1}
,"selected":{"boot":1}
,"contains":{"kernel":1,"u-boot":1,"device":1,"guid":1,"information":1,"dtc":1,"boot":1,"requir":1,"series":1,"number":1,"sequence":1,"space-separated":1,"script":1,"list":1}
,"line":{"parameters":1,"example":1,"pass":1}
,"control":{"nux":1}
,"nux":{"kernel":1}
,"looks":{"root":1,"extlinux.conf":1}
,"-boot":{"select":1,"script":1}
,"select":{"script":1}
,"mount":{"root":1,"\u002Fdev\u002Fmmcblk0p1":1}
,"elect":{"boot":1}
,"cause":{"kernel":1,"u-b":1}
,"$sudo":{".\u002Fflash.sh":1,"mount":1}
,".\u002Fflash.sh":{"<platform":1,"<ipa>":1,"lnx":1,"kernel":1}
,"<platform":{"mmcblk0p1":1,"mmcblk1p1":1,"<interface":1}
,"mmcblk0p1":{"flash":1,"execute":1,"changing":1}
,"causes":{"rnel":1,"kernel":1}
,"rnel":{"mount":1}
,"mmcblk1p1":{"flash":1}
,"nfs":{"server":1,"device":1}
,"server":{"elect":1,"$sudo":1,"hosting":1,"<gateway":1,"configure":1,"boot":1}
,"<ipa>":{":\u002F<nfs":1,"nfs":1}
,":\u002F<nfs":{"directory":1}
,"[-n":{"<target":1}
,"<target":{"ipa>":1}
,"ipa>":{"<host":1,"<gateway":1,"<netmas":1,"static":1}
,"<host":{"ipa>":1}
,"<gateway":{"ipa>":1}
,"<netmas":{"k>]":1}
,"k>]":{"<platform":1}
,"<interface":{"name>":1}
,"name>":{"<interface":1,"eth0":1}
,"eth0":{"rj45":1}
,"rj45":{"connector":1}
,"connector":{"eth1":1}
,"eth1":{"usb":1}
,"usb":{"ethernet":1,"storage":1,"device":1,"support":1,"dev":1,"entry":1,"mass":1}
,"ethernet":{"dongle":1}
,"dongle":{"<ipa>":1}
,"hosting":{"root":1}
,"<nfs_directory>":{"full":1}
,"pathname":{"exported":1}
,"exported":{"root":1}
,"static":{"address":1,"netmask":1}
,"address":{"target":1,"nfs":1,"gateway":1,"(lba)":1,"pxe":1,"tftp":1}
,"gateway":{"<netmask>":1}
,"<netmask>":{"static":1}
,"netmask":{"local":1}
,"network":{"note":1,"dev":1,"protocols":1,"using":1}
,"recommended":{"point-to-point":1}
,"point-to-point":{"net":1}
,"net":{"work":1}
,"connections":{"dhcp":1}
,"dhcp":{"server":1,"receive":1,"network":1}
,"configure":{"flashing":1}
,"platfor":{"flashing":1}
,"above":{"flash":1}
,"new":{"version":1,"u-boot":1,"kernel":1,"value":1}
,"foll":{"owing":1}
,"owing":{"flash":1}
,"xecute":{"following":1}
,"lnx":{"<platform":1,"partition":1}
,"changing":{"emmc":1}
,"partition":{"layout":1,"contains":1,"size":1,"largest":1,"key":1,"table":1,"lnx":1,"nominally":1,"used":1,"root":1,"u-boot":1,"device":1,"u-b":1,"number":1,"umber":1,"enter":1}
,"layout":{"topic":1,"information":1,"used":1,"determination":1,"rotective":1,"example":1,"xml":1}
,"topic":{"based":1}
,"based":{"emmc":1,"internal":1,"eir":1}
,"hardware":{"software":1,"features":1,"support":1}
,"linux_for_tegra\u002F<target_board>":{".conf":1}
,".conf":{".common":1,"note":1}
,".common":{"linux_for_tegra\u002Fbootloader":1,"file":1}
,"linux_for_tegra\u002Fbootloader":{"\u002F<platform":1}
,"\u002F<platform":{">\u002Fcfg\u002Fgnu":1}
,">\u002Fcfg\u002Fgnu":{"_linux":1}
,"_linux":{"_tegraboot":1}
,"_tegraboot":{"_emmc":1}
,"_emmc":{"_full.xml":1}
,"_full.xml":{"linux_for_tegra\u002Fbootloader\u002F<platform>\u002Fcfg\u002Fflash":1}
,"linux_for_tegra\u002Fbootloader\u002F<platform>\u002Fcfg\u002Fflash":{"_l4t_t186.xml":1}
,"_l4t_t186.xml":{"note":1}
,"installed":{"filesystem":1,"l4t":1}
,"alongs":{"ide":1}
,"ide":{"boot":1}
,"(lnx)":{"partition":1}
,"aside":{"difference":1}
,"difference":{"u-boot":1}
,"ternal":{"emmc":1}
,"cboot":{"emmc":1}
,"parameter":{"emmc":1,"defined":1,"includes":1,"boot":1}
,"defined":{"two":1,"alue":1}
,"two":{"variables":1}
,"variables":{"linux_for_tegra\u002F<target":1,"comp":1,"modified":1,"scan_dev_for_extlinux":1,"environment":1,"data":1,"scripts":1,"flash":1,"print":1}
,"linux_for_tegra\u002F<target":{"_board":1}
,"_board":{".conf":1}
,"imit":{"size":1}
,"size":{"total":1,"consists":1,"boot1":1,"emmcsize":1,"note":1,"obtai":1,"root":1,"partition":1,"odify":1}
,"total":{"usable":1,"space":1}
,"usable":{"data":1}
,"data":{"area":1,"size":1,"stored":1,"determined":1,"missing":1,"flash":1,"written":1,"using":1,"writt":1}
,"area":{"etermine":1}
,"etermine":{"location":1}
,"location":{"gpt":1,"booting":1,"users":1,"data":1}
,"gpt":{"partitions":1,"part":1,"partition":1,"serves":1}
,"partitions":{"emmc":1,"cannot":1,"flash.sh":1}
,"includes":{"bootpartsize":1,"default":1,"extlinux.conf":1,"command":1}
,"bootpartsize":{"specifies":1,"user":1}
,"specifies":{"emmc":1}
,"consists":{"boot0":1,"bootpartsize":1}
,"boot0":{"partition":1,"boot1":1}
,"boot1":{"partition":1,"user":1}
,"emmcsize":{"specifies":1,"gpt":1}
,"user":{"partition":1,"-accessible":1,"accessible":1,"boot":1,"may":1,"wishes":1,"requested":1,"seconds":1}
,"obtai":{"ned":1}
,"ned":{"emmc":1}
,"datasheet":{"root":1}
,"largest":{"partition":1}
,"key":{"factors":1,"presses":1,"interrupt":1}
,"factors":{"partition":1}
,"determination":{"modify":1}
,"modify":{"root":1,"value":1,"include\u002Fconfig_distro_bootcmd.h":1,"include\u002Fconfig\u002F<board>":1,"manufacturing":1,"save":1,"l4t":1,"devices":1}
,"odify":{"value":1}
,"value":{"rootfssize":1,"configs\u002F<board":1,"config_pcieaspm_powersave=y":1,"config_pcieaspm":1,"avoids":1,"completely":1,"<devplist>":1,"true":1,"rather":1,"include\u002Fconfig_distro_bootcmd.h":1,"config_bootdelay":1,"<bootdelay>":1,"boot_target_devices":1,"<boot_targets>":1,"compile-time":1,"variable":1}
,"rootfssize":{"variable":1}
,"variable":{"linux_for_tegra\u002F<target":1,"description":1,"contain":1,"innocuou":1,"script":1,"ffect":1,"desired":1,"compile-time":1,"value":1,"prevents":1,"execute":1,"\u2011boot":1,"example":1}
,"cannot":{"exce":1}
,"exce":{"emmcsize":1}
,"flash.sh":{"script":1,"flashes":1,"command":1,"copies":1}
,"creates":{"primary":1}
,"primary":{"secondary":1,"gpt":1}
,"secondary":{"gpt":1}
,"part":{"itions":1,"root":1}
,"itions":{"automatically":1}
,"automatically":{"based":1,"boot":1,"booting":1}
,"rotective":{"mbr":1}
,"mbr":{"contains":1}
,"prevent":{"traditional":1}
,"traditional":{"boot":1}
,"loaders":{"performing":1}
,"performing":{"destructive":1}
,"destructive":{"actions":1}
,"actions":{"located":1}
,"lba":{"primary":1,"secondary":1,"boot":1,"lnx":1}
,"guid":{"partition":1}
,"table":{"located":1,"identifies":1,"determine":1}
,"serves":{"backup":1}
,"last":{"lba":1,"logical":1}
,"logical":{"block":1}
,"block":{"address":1}
,"(lba)":{"varies":1}
,"varies":{"evice":1}
,"evice":{"device":1}
,"obtain":{"last":1}
,"nominally":{"contains":1}
,"contain":{"u-boot":1,"leading":1,"space-separated":1}
,"reads":{"kernel":1}
,"app":{"partition":1,"par":1}
,"flashed":{"partition":1}
,"expects":{"boot":1}
,"exist":{"<rootfs>\u002Fboot":1}
,"<rootfs>\u002Fboot":{"directory":1,"location":1}
,"par":{"tition":1}
,"tition":{"kernel":1}
,"(image":{"boot":1}
,"(extlinux":{"\u002Fextlinux":1}
,"\u002Fextlinux":{".conf":1}
,"treats":{"root":1}
,"filesystem-on-ip-network":{"configura":1}
,"configura":{"tion":1}
,"tion":{"special":1,"files":1}
,"special":{"case":1}
,"case":{"flashes":1,"following":1}
,"<app":{"partition>":1}
,"partition>":{"\u002Fboot":1}
,"\u002Fboot":{"directory":1,"may":1,"\u002Fextlinux\u002Fextlinux.conf":1,"<dir>":1}
,"gnu_linux_tegraboot_emmc_full.xml":{"file":1}
,"flash_l4t_t186.xml":{"file":1}
,"ish":{"pass":1}
,"pass":{"dtc":1,"kernel":1}
,"filename":{"parameter":1,"device":1}
,"environmen":{"ensure":1}
,"ensure":{"local":1}
,"path":{"contains":1,"build":1,"name":1}
,"\u002Fusr\u002Flocal\u002Fbin":{"choice":1}
,"choice":{"begin":1}
,"begin":{"ning":1}
,"ning":{"shell":1}
,"shell":{"command":1,"interrupted":1,"reached":1,"commands":1}
,"git:\u002F\u002Fgit.kernel.org\u002Fpub\u002Fscm\u002Futils\u002Fdtc":{"\u002Fdtc.git":1}
,"\u002Fdtc.git":{"$cd":1}
,"procedure":{"assume":1,"applies":1}
,"$home":{"execute":1}
,"specific":{"directory":1,"devic":1,"manner":1,"storage":1}
,"prefix=\u002Fusr\u002Flocal":{"either":1}
,"directories":{"created":1,"scan":1,"note":1}
,"created":{"below":1}
,"below":{"installation":1}
,"installation":{"directory":1}
,"bin":{"lib":1,"<dir>":1}
,"lib":{"include":1,"<dir>":1}
,"replacing":{"kernel":1}
,"replace":{"kernel":1,"script":1}
,"custom":{"kernel":1,"requirements":1}
,"applies":{"type":1}
,"type":{"storage":1,"help":1}
,"steps":{"used":1}
,"cases":{"boot":1,"user":1}
,"\u002Ftx2":{"\u002Ftx2i":1}
,"scp":{"\u002Fboot":1}
,"reboot":{"jetson":1}
,"connect":{"card":1,"terminal":1}
,"disconnect":{"card":1}
,"enter":{"following":1}
,"\u002Fdev\u002Fmmcblk0p1":{"\u002Fmnt":1}
,"\u002Fmnt":{"copy":1}
,"copying":{"root":1}
,"external":{"media":1,"card":1}
,"media":{"copy":1,"<dir>":1}
,"running":{"flash.sh":1}
,"attach":{"device":1}
,"adds":{"required":1}
,"filesy":{"stem":1}
,"stem":{"directory":1}
,"runs":{"boot":1,"send":1}
,"sequence":{"sysboot":1,"scans":1,"avoid":1,"u-boot":1,"commands":1}
,"sysboot":{"configuration":1,"command":1}
,"functionality":{"includes":1,"full":1}
,"bootin":{"scan":1}
,"scan":{"sequence":1,"boot":1}
,"scans":{"bootable":1,"find":1}
,"bootable":{"devices":1,"partition":1}
,"order":{"external":1}
,"extlinux.conf":{"configuration":1,"file":1,"loads":1,"standard":1,"files":1,"modi":1,"timeout":1}
,"<rootfs>\u002Fboot\u002Fextlinux":{"upon":1,"location":1}
,"upon":{"find":1}
,"find":{"ing":1,"extlinux.conf":1,"boot":1}
,"ing":{"extlinux.conf":1}
,"performs":{"following":1}
,"uses":{"sysboot":1,"default":1}
,"read":{"boot":1}
,"loads":{"kernel":1,"executes":1}
,"boots":{"kernel":1,"system":1}
,"-accessible":{"<rootfs>\u002Fboot":1}
,"booting":{"extlinux.conf":1,"require":1,"reduce":1}
,"accessible":{"<rootfs>\u002Fboot\u002Fextlinux":1}
,"users":{"easily":1}
,"easily":{"change":1}
,"change":{"files":1}
,"test":{"kernel":1}
,"text-format":{"sysboot":1}
,"ile":{"contains":1,"manufacturing":1}
,"infor":{"mation":1}
,"mation":{"indicates":1}
,"indicates":{"kernel":1}
,"blob":{"filena":1}
,"filena":{"kernel":1}
,"supported":{"board":1,"commands":1}
,"board":{"extlinux.conf.emmc":1,"data":1,"arrange":1,"execute":1,"mer":1,"erge":1,"power":1,"wait":1}
,"extlinux.conf.emmc":{"extlinux.conf.sdcard":1}
,"extlinux.conf.sdcard":{"extlinux.conf.usb":1}
,"extlinux.conf.usb":{"extlinux.conf.nfs":1}
,"extlinux.conf.nfs":{"during":1}
,"during":{"flashing":1,"time":1,"subsequ":1,"subsequent":1,"boot":1}
,"copies":{"appropriate":1}
,"variant":{"following":1}
,"ocation":{"target":1}
,"<rootfs>\u002Fboot\u002Fextlinux\u002Fextlinux.conf":{"extlinux.conf":1}
,"similar":{"except":1,"following":1}
,"except":{"different":1}
,"different":{"kernel":1}
,"lines":{"find":1,"containing":1}
,"bootloader\u002F<platform":{">\u002F<board":1,">\u002F<board_and_rev":1}
,">\u002F<board":{"\u002Fwhere":1}
,"\u002Fwhere":{"<platform>":1}
,"<board>":{"jetson":1}
,"optimizing":{"u-boot":1}
,"ncludes":{"default":1}
,"enables":{"upported":1,"out-of-the-box":1}
,"upported":{"hardware":1}
,"earches":{"available":1}
,"scripts":{"enables":1,"ontained":1,"execute":1,"valid":1,"configuration":1,"part":1,"constrained":1,"relate":1}
,"out-of-the-box":{"support":1}
,"widest":{"possible":1}
,"possible":{"variety":1}
,"variety":{"storage":1}
,"conf":{"igurations":1}
,"igurations":{"lexibility":1}
,"lexibility":{"delays":1}
,"delays":{"execution":1,"enumerating":1}
,"execution":{"final":1,"waits":1}
,"final":{"operating":1}
,"operating":{"system":1}
,"takes":{"time":1}
,"initialize":{"scanning":1}
,"scanning":{"attached":1}
,"attached":{"storage":1,"usb":1}
,"dev":{"ices":1,"<dir>":1}
,"ices":{"takes":1,"until":1}
,"constrained":{"pre-configured":1,"cases":1}
,"pre-configured":{"systems":1}
,"flexibility":{"may":1}
,"necessary":{"may":1}
,"know":{"ahead":1}
,"ahead":{"time":1}
,"orage":{"device":1}
,"requir":{"files":1}
,"certain":{"devices":1}
,"initi":{"lized":1,"alize":1}
,"lized":{"boot-loader":1}
,"boot-loader":{"optimize":1}
,"optimize":{"boot":1}
,"onfigure":{"u-boot":1}
,"allow":{"constraints":1}
,"constraints":{"reduce":1}
,"reduce":{"system":1,"boot":1}
,"changes":{"made":1}
,"made":{"kernel":1}
,"disabling":{"pcie":1,"aspm":1,"usb":1}
,"pcie":{"support":1,"vices":1,"device":1,"devices":1,"aspm":1}
,"enumerating":{"initializing":1}
,"initializing":{"pcie":1,"active":1,"usb":1}
,"vices":{"until":1}
,"until":{"user":1}
,"explicitly":{"attempts":1}
,"attempts":{"access":1,"initi":1}
,"access":{"pcie":1,"usb":1,"u-boot":1}
,"consequently":{"isabling":1,"dis":1}
,"isabling":{"pcie":1}
,"disable":{"pcie":1,"aspm":1,"usb":1}
,"remove":{"following":1,"include":1,"usb":1,"timeout":1,"extlinux.conf":1,"lines":1}
,"values":{"include\u002Fconfigs\u002F<board>":1,"configs\u002F<board":1,"variables":1,"include":1,"tha":1,"following":1,"appear":1,"<boot_targets>":1}
,"include\u002Fconfigs\u002F<board>":{"config_pci_ehci":1,"remove":1}
,"config_pci_ehci":{"config_pci_tegra":1}
,"config_pci_tegra":{"config_cmd_pci":1,"config_rtl8169":1}
,"config_cmd_pci":{"remove":1}
,"configs\u002F<board":{"_and_rev":1}
,"_and_rev":{">_defconfig":1,"_defconfig":1}
,"config_rtl8169":{"config_e1000":1}
,"config_e1000":{"<board>":1}
,"tx2i":{"p2771-0000":1,"p2771-0000\u002F500":1}
,"0-500":{"enabling\u002Fdisabling":1,"jetson":1}
,"enabling\u002Fdisabling":{"aspm":1}
,"aspm":{"support":1,"device":1}
,"active":{"state":1}
,"state":{"power":1}
,"power":{"management":1,"reset":1}
,"(aspm":{"pcie":1}
,"plicitly":{"attempts":1}
,"nsequently":{"disabling":1}
,"enable":{"aspm":1}
,"config_pcieaspm":{"add":1,"<board_and_rev>":1}
,"add":{"following":1,"xtra":1}
,"config_pcieaspm_powersave=y":{"<board_and_rev>":1,"add":1}
,"p2771-0000\u002F500":{"disable":1,"disabling":1,"<board_and_rev>":1,"environment":1,"jetson":1,"debugging":1}
,"dis":{"abling":1}
,"abling":{"usb":1}
,"_defconfig":{"config_cmd_usb":1}
,"config_cmd_usb":{"config_cmd_usb_mass_storage":1}
,"config_cmd_usb_mass_storage":{"config_usb":1}
,"config_usb":{"config_usb_gadget":1}
,"config_usb_gadget":{"config_usb_gadget_download":1}
,"config_usb_gadget_download":{"edit":1}
,"edit":{"include\u002Fconfigs\u002F<board>":1,"include\u002Fconfigs\u002Ftegra-common-post.h":1,"u-boot":1,"extlinux.conf":1}
,"tegra-common-usb-gadget.h":{"edit":1}
,"include\u002Fconfigs\u002Ftegra-common-post.h":{"remove":1,"value":1}
,"entry":{"boot_target_devices":1}
,"boot_target_devices":{"<board>":1,"determines":1}
,"runtime":{"behavior":1}
,"behavior":{"controlled":1}
,"controlled":{"scripts":1}
,"ontained":{"u-boot":1}
,"gins":{"execution":1}
,"waits":{"<bootdelay>":1}
,"<bootdelay>":{"seconds":1,"include\u002Fconfigs\u002Ftegra-common-post.h":1}
,"seconds":{"executing":1,"u-boot":1,"automatically":1}
,"automatic":{"boot":1}
,"seque":{"nce":1}
,"nce":{"during":1}
,"interrupt":{"boot":1,"u-boot":1,"automatic":1}
,"process":{"access":1,"u-boot":1,"write":1,"include\u002Fconfig":1,"send":1,"alternatively":1,"programs":1}
,"interrupted":{"u-boot":1}
,"executes":{"<bootcmd>":1,"system":1}
,"<bootcmd>":{"shell":1,"contains":1}
,"series":{"commands":1}
,"commands":{"search":1,"executed":1,"nothing":1,"hing":1,"modify":1,"u-boot":1,"similar":1,"usa":1,"\u2011boot":1}
,"search":{"storage":1,"unnecessary":1,"extlinux":1,"u-boot":1,"script":1}
,"evic":{"boot":1}
,"modifying":{"values":1,"manufacturing":1}
,"comp":{"ile":1}
,"manufacturing":{"time":1,"flashing":1,"flow":1,"process":1,"proce":1}
,"directed":{"boot":1}
,"devic":{"specific":1}
,"manner":{"thereby":1}
,"thereby":{"reducing":1}
,"reducing":{"boot":1}
,"identifies":{"variables":1}
,"modified":{"variable":1,"environment":1}
,"description":{"bootdelay":1}
,"bootdelay":{"contains":1}
,"number":{"seconds":1,"known":1}
,"pauses":{"determine":1}
,"determine":{"whether":1,"partition":1}
,"whether":{"user":1}
,"wishes":{"interrupt":1}
,"avoid":{"delay":1,"setting":1}
,"delay":{"note":1,"user":1,"less":1}
,"although":{"value":1}
,"avoids":{"delay":1}
,"requested":{"interrupt":1}
,"reached":{"request":1}
,"request":{"honored":1}
,"honored":{"delay":1}
,"less":{"tha":1}
,"tha":{"bootmenu":1,"built":1}
,"bootmenu":{"displayed":1}
,"displayed":{"autoboot":1}
,"autoboot":{"disabled":1}
,"disabled":{"bootcmd":1}
,"bootcmd":{"contains":1}
,"executed":{"automatically":1,"best":1}
,"completely":{"replaced":1}
,"replaced":{"however":1}
,"however":{"simple":1}
,"simple":{"customi":1}
,"customi":{"zations":1}
,"zations":{"selecting":1}
,"selecting":{"specific":1}
,"devi":{"booting":1}
,"require":{"editing":1}
,"editing":{"valu":1}
,"valu":{"boot_targets":1}
,"boot_targets":{"contains":1,"mmc0":1}
,"space-separated":{"list":1}
,"list":{"storag":1,"default":1,"filesystem":1,"u-boot":1,"setting":1,"supported":1,"directory":1,"contents":1,"device":1}
,"storag":{"devices":1}
,"protocols":{"u-boot":1}
,"valid":{"values":1}
,"mmc0":{"-the":1,"savee":1}
,"-the":{"built-in":1}
,"built-in":{"emmc":1,"copy":1,"default":1}
,"mmc1":{"card":1}
,"slot":{"usb0":1}
,"usb0":{"attached":1}
,"mass":{"storage":1}
,"pxe":{"network":1,"download":1}
,"receive":{"address":1}
,"syslinux":{"configuration":1}
,"tftp":{"download":1}
,"var":{"iable":1,"listing":1}
,"iable":{"single":1}
,"single":{"spe":1,"partition":1,"directory":1}
,"spe":{"cific":1}
,"cific":{"device":1}
,"restrictive":{"list":1}
,"scan_dev_for_boot_part":{"contains":1}
,"parse":{"device":1}
,"u-b":{"oot":1}
,"known":{"ahea":1,"extlinux":1,"u-boot":1,"ahead":1}
,"ahea":{"time":1}
,"simpler":{"script":1}
,"hard":{"code":1}
,"<devplist>":{"single":1}
,"umber":{"(represented":1}
,"(represented":{"hexadecimal)":1}
,"hexadecimal)":{"run":1}
,"scan_dev_for_extlinux":{"scan_dev_for_boot_scripts":1,"contains":1}
,"scan_dev_for_boot_scripts":{"boot_prefixes":1}
,"boot_prefixes":{"contains":1}
,"layouts":{"vary":1}
,"vary":{"installations":1}
,"installations":{"example":1}
,"separate":{"partit":1}
,"partit":{"ion":1}
,"ion":{"containing":1}
,"searches":{"locations":1}
,"locations":{"boo":1}
,"boo":{"scripts":1}
,"variab":{"single":1}
,"unnecessary":{"directories":1}
,"entries":{"variable":1}
,"leading":{"trailing":1}
,"trailing":{"scan_dev_for_extlinux":1}
,"extlinux":{"configura":1,"configu":1,"configurati":1,"5910248":1}
,"found":{"boots":1,"loads":1,"<dir>":1}
,"eir":{"content":1}
,"content":{"system":1}
,"configu":{"ration":1}
,"ration":{"files":1}
,"nothing":{"best":1}
,"best":{"results":1}
,"results":{"variable":1}
,"innocuou":{"value":1}
,"true":{"rather":1}
,"rather":{"leaving":1,"fault":1,"using":1,"referencing":1,"usin":1}
,"leaving":{"pty":1}
,"pty":{"u-boot":1}
,"complain":{"attempt":1}
,"attempt":{"execute":1}
,"empty":{"variable":1}
,"scan_dev_for_scripts":{"contains":1}
,"scri":{"pts":1}
,"pts":{"replace":1}
,"hing":{"note":1}
,"<scan_dev_for_ex":{"tlinux>":1}
,"tlinux>":{"prior":1}
,"prior":{"executing":1,"flashing":1}
,"<scan_dev_for_scripts>":{"therefore":1,"search":1}
,"therefore":{"difying":1}
,"difying":{"variable":1}
,"ffect":{"systems":1}
,"configurati":{"files":1}
,"boot_scripts":{"contain":1}
,"names":{"<scan_dev_for_scripts>":1}
,"thi":{"variable":1}
,"desired":{"value":1}
,"fault":{"list":1}
,"setting":{"environment":1,"<boot_targets>":1}
,"compile-time":{"manufacturing":1,"u-boot":1,"modify":1}
,"starts":{"executing":1}
,"alize":{"environment":1}
,"stored":{"flash":1}
,"memory":{"location":1,"built-in":1,"region":1}
,"determined":{"u-bo":1}
,"u-bo":{"configuration":1,"source":1}
,"missing":{"rrupted":1}
,"rrupted":{"u-boot":1}
,"write":{"data":1,"execute":1}
,"always":{"used":1}
,"initially":{"built-in":1}
,"places":{"u-bo":1}
,"include\u002Fconfig_distro_bootcmd.h":{"file":1,"avoid":1}
,"defines":{"variables":1}
,"relate":{"automatic":1}
,"include\u002Fconfig":{"\u002Fauto.conf":1}
,"\u002Fauto.conf":{"value":1}
,"config_bootdelay":{"determines":1}
,"determines":{"defau":1,"default":1}
,"defau":{"value":1}
,"<boot_targets>":{"legal":1,"modify":1,"board-spec":1,"manufacturing":1}
,"legal":{"values":1}
,"appear":{"<boot_t":1,"key":1}
,"<boot_t":{"argets>":1}
,"argets>":{"removing":1}
,"removing":{"entries":1}
,"prevents":{"tho":1}
,"tho":{"values":1}
,"board-spec":{"ific":1}
,"ific":{"configuration":1}
,"already":{"defined":1}
,"alue":{"modify":1}
,"include\u002Fconfig\u002F<board>":{"<boot_targets>":1}
,"flow":{"add":1,"flashing":1}
,"xtra":{"step":1}
,"step":{"writes":1}
,"writes":{"saved":1}
,"saved":{"copy":1,"environment":1,"modified":1}
,"environm":{"ent":1}
,"ent":{"variables":1,"flashing":1}
,"provides":{"alternatives":1}
,"alternatives":{"modifying":1}
,"arrange":{"board":1}
,"save":{"environment":1,"result":1,"modified":1}
,"reset":{"boa":1,"board":1}
,"boa":{"u-boot":1}
,"send":{"commands":1}
,"serial":{"console":1,"port":1,"save":1}
,"console":{"write":1,"output":1}
,"program":{"host":1}
,"detect":{"u-boot":1}
,"begins":{"executing":1}
,"env":{"default":1}
,"setenv":{"boot_targets":1,"<environment_variable>":1,"stdout":1}
,"savee":{"manually":1}
,"manually":{"edit":1}
,"interactively":{"save":1}
,"result":{"extract":1}
,"extract":{"appropriate":1}
,"fla":{"memory":1}
,"region":{"file":1}
,"xml":{"file":1}
,"written":{"flash":1}
,"subsequ":{"ent":1}
,"alternatively":{"apply":1}
,"apply":{"technique":1}
,"technique":{"manufacturing":1}
,"programs":{"flash":1}
,"chips":{"directly":1}
,"directly":{"rather":1}
,"tools":{"board":1}
,"mer":{"extracted":1}
,"referencing":{"l4t":1,"fro":1}
,"generate":{"saved":1}
,"fw_env":{"tool":1}
,"tool":{"located":1}
,"tools\u002Fenv":{"directory":1}
,"rtition":{"layou":1}
,"layou":{"xml":1}
,"writt":{"flash":1}
,"subsequent":{"flashing":1}
,"proce":{"programs":1,"ssing":1}
,"usin":{"l4t":1}
,"erge":{"extracted":1}
,"fro":{"l4t":1}
,"modi":{"ications":1}
,"ications":{"l4t":1}
,"tells":{"u-boot":1}
,"filenames":{"load":1}
,"load":{"includes":1}
,"configured":{"display":1}
,"display":{"boot":1}
,"menu":{"user":1,"edit":1,"installed":1}
,"ssing":{"time":1}
,"timeout":{"remove":1,"boot":1,"menu":1}
,"keywords":{"timeout":1}
,"cated":{"\u002Fboot":1}
,"\u002Fextlinux\u002Fextlinux.conf":{"prior":1}
,"directo":{"bootloader\u002F<platform":1}
,">\u002Fextlinux.conf.emmc":{"<platform>":1}
,"debugging":{"u-boot":1,"tips":1}
,"tips":{"help":1}
,"help":{"debug":1,"\u2011boot":1,"time":1,"text":1,"listing":1}
,"debug":{"u-boot":1}
,"examples":{"represent":1}
,"represent":{"comprehensive":1}
,"comprehensive":{"listing":1}
,"listing":{"u-boot":1,"directory":1,"contents":1}
,"usa":{"u-boot":1}
,"consult":{"u-boot":1}
,"documentation":{"sou":1}
,"sou":{"rce":1}
,"interrupting":{"u-boot":1}
,"terminal":{"application":1,"screen":1,"u-boot":1}
,"application":{"serial":1}
,"port":{"board":1}
,"wait":{"u-boot":1}
,"sign":{"message":1}
,"message":{"appear":1}
,"presses":{"point":1}
,"point":{"time":1}
,"ignored":{"press":1}
,"press":{"key":1}
,"proc":{"ess":1,"<dir>":1}
,"ess":{"getting":1}
,"getting":{"help":1}
,"screen":{"type":1}
,"text":{"u-boot":1,"enter":1}
,"mmand":{"help":1}
,"structure":{"list":1,"particul":1,"emmc":1}
,"particul":{"device":1}
,"tructure":{"list":1}
,"mmc":{"0:1":1}
,"0:1":{"command":1,"<directory>":1,"\u002Fboot":1}
,"functions":{"correctly":1}
,"correctly":{"ext":1}
,"ext":{"2\u002F3\u002F4":1}
,"2\u002F3\u002F4":{"fat":1}
,"fat":{"systems":1}
,"utput":{"follows":1}
,"<dir>":{"4096":1,"1024":1}
,"4096":{"<dir>":1,"bin":1,"boot":1,"dev":1,"home":1,"lib":1,"lost":1,"media":1,"mnt":1,"opt":1,"proc":1,"root":1,"sbin":1,"selinux":1,"srv":1,"sys":1,"tmp":1,"usr":1,"var":1}
,"home":{"<dir>":1}
,"lost":{"found":1}
,"mnt":{"<dir>":1}
,"opt":{"<dir>":1}
,"sbin":{"<dir>":1}
,"selinux":{"<dir>":1}
,"srv":{"<dir>":1}
,"sys":{"<dir>":1}
,"tmp":{"<dir>":1}
,"usr":{"<dir>":1}
,"contents":{"directory":1,"following":1,"\u002Fboot":1}
,"ist":{"ontents":1}
,"ontents":{"irectory":1}
,"irectory":{"list":1}
,"<directory>":{"<directory>":1,"path":1}
,"(as":{"shown":1}
,"shown":{"example":1}
,"output":{"below)":1,"execute":1,"follows":1,"ecute":1}
,"below)":{"llowing":1}
,"llowing":{"command":1}
,"ext2ls":{"mmc":1}
,"1024":{"<dir>":1,"908":1}
,"908":{"extlinux":1}
,"5910248":{"image":1}
,"printing":{"u-boot":1}
,"print":{"entire":1,"u-boot":1,"environment":1,"list":1}
,"entire":{"\u2011boot":1}
,"nvironment":{"execute":1}
,"printenv":{"printing\u002Fsetting":1,"<environment_variable>":1,"stdout":1}
,"printing\u002Fsetting":{"environment":1}
,"<environment_variable>":{"<environment_variable>":1,"refers":1,"<new_value>":1}
,"refers":{"environment":1}
,"sends":{"console":1}
,"stdout":{"output":1,"serial":1}
,"stdout=serial":{"environment":1}
,"<new_value>":{"<environment_variable>":1,"new":1}
,"ecute":{"setenv":1}
,"saveenv":{"saved":1}
,"preserved":{"cas":1}
,"cas":{"resets":1}
,"resets":{"reboots":1}
}
;Search.control.loadWordPairs(pairs);
