var pairs =
{
"clocks":{"nvidia":1,"peripheral":1,"software":1,"configure":1,"required":1,"driver":1,"soc\u002Ftegra\u002Fkernel-include\u002Fdt-bindings\u002Fclock\u002Ftegra21":1,"soc\u002Ft18x\u002Fkernel-include\u002Fdt-bindings\u002Fclock\u002Ftegra186":1,"controlled":1,"update":1,"general":1,"device":1,"declared":1,"=<&tegra_car":1}
,"nvidia":{"tegra":1}
,"tegra":{"board":1,"clocks":1,"clock":1,"technical":1,"specific":1,"custom":1}
,"board":{"support":1}
,"support":{"package":1}
,"package":{"(bsp)":1}
,"(bsp)":{"supports":1}
,"supports":{"configuring":1}
,"configuring":{"tegra":1,"clocks":1}
,"peripheral":{"clocks":1,"gate":1}
,"software":{"topic":1}
,"topic":{"describes":1}
,"describes":{"check":1,"clock":1}
,"check":{"clock":1}
,"clock":{"status":1,"sources":1,"source":1,"reset":1,"fram":1,"drivers":1,"drive":1,"sudo":1,"rate":1,"i.e":1,"rates":1,"divider":1,"configurations":1,"desir":1,"clk_set_parent":1,"clk_set_rate":1,"frequency":1,"clk_prepare":1,"operation":1}
,"status":{"maximum":1,"device":1}
,"maximum":{"rates":1}
,"rates":{"clocks":1,"found":1,"gbus":1,"following":1}
,"configure":{"clock":1}
,"sources":{"note":1,"ach":1,"clocks":1}
,"note":{"information":1,"modules":1}
,"information":{"available":1,"abo":1,"tegra":1}
,"available":{"tegra":1,"clock":1,"kernel-4.4\u002Fdrivers\u002Fclk\u002Ftegra\u002Fdirectory":1,"following":1,"divider":1}
,"source":{"capabilities":1,"multiplexers":1,"information":1,"register":1,"registers":1,"select":1,"using":1,"targe":1,"clk_round_rate":1,"clk_prepare_enable":1}
,"capabilities":{"clock":1}
,"reset":{"contr":1}
,"contr":{"oller":1}
,"oller":{"section":1}
,"section":{"tegra":1,"trm":1}
,"technical":{"reference":1}
,"reference":{"manual":1}
,"manual":{"(trm":1}
,"(trm":{"chip":1,"clock":1}
,"chip":{"section":1}
,"trm":{"describes":1}
,"multiplexers":{"prov":1}
,"prov":{"ides":1}
,"ides":{"descriptions":1}
,"descriptions":{"available":1}
,"ach":{"component":1}
,"component":{"kernel":1,"during":1}
,"kernel":{"4.4":1,"devic":1}
,"4.4":{"following":1}
,"following":{"common":1,"files":1,"command":1,"clocks":1,"commands":1}
,"common":{"clock":1}
,"fram":{"ework":1}
,"ework":{"(ccf)":1}
,"(ccf)":{"supported":1}
,"supported":{"result":1}
,"result":{"device":1}
,"device":{"drivers":1,"tree":1,"enter":1}
,"drivers":{"public":1,"including":1}
,"public":{"ccf":1}
,"ccf":{"apis":1}
,"apis":{"include\u002Flinux\u002Fclk.h":1,"clock":1}
,"include\u002Flinux\u002Fclk.h":{"include\u002Flinux\u002Fclk-provider.h":1}
,"include\u002Flinux\u002Fclk-provider.h":{"including":1}
,"including":{"functions":1,"tegra":1}
,"functions":{"clk_get":1,"ungate\u002Fenable":1}
,"clk_get":{"clk_enable":1}
,"clk_enable":{"devm_clk_get":1,"functions":1,"ungate":1}
,"devm_clk_get":{"clk_prepare_enable":1,"function":1}
,"clk_prepare_enable":{"clk_prepare_disable":1,"(or":1}
,"clk_prepare_disable":{"clk_disable":1}
,"clk_disable":{"others":1}
,"others":{"instead":1}
,"instead":{"tegra":1,"clk_enable":1}
,"specific":{"apis":1}
,"custom":{"clk":1,"clock":1}
,"clk":{"driver":1}
,"driver":{"implement":1,"file":1,"framework":1,"module":1}
,"implement":{"clk_ops":1}
,"clk_ops":{"clock":1}
,"required":{"devices":1}
,"devices":{"defined":1}
,"defined":{"device":1}
,"tree":{"tegra":1,"example":1}
,"drive":{"available":1}
,"kernel-4.4\u002Fdrivers\u002Fclk\u002Ftegra\u002Fdirectory":{"lock":1}
,"lock":{"rate":1,"source":1}
,"rate":{"clock":1,"default":1,"component":1,"fixed":1,"debugfs":1,"gpu":1,"following":1,"successful":1}
,"files":{"basic":1}
,"basic":{"clocks":1}
,"file":{"pll":1}
,"pll":{"pll_out":1}
,"pll_out":{"clk-pll.c":1}
,"clk-pll.c":{"clk-pll-out.c":1}
,"clk-pll-out.c":{"audio":1}
,"audio":{"sync":1}
,"sync":{"clk-audio-sync.c":1}
,"clk-audio-sync.c":{"divider":1}
,"divider":{"clk-divider.c":1,"control":1,"typically":1,"calculated":1,"modu":1}
,"clk-divider.c":{"peripheral":1}
,"gate":{"cclk-periph.c":1}
,"cclk-periph.c":{"clk-periph-fixed.c":1}
,"clk-periph-fixed.c":{"clk-periph-gate":1}
,"clk-periph-gate":{"clk-tegra-periph.c":1}
,"clk-tegra-periph.c":{"super":1}
,"super":{"clk-super.c":1}
,"clk-super.c":{"clk-tegra-super-gen4.c":1}
,"clk-tegra-super-gen4.c":{"fixed":1}
,"fixed":{"clk-tegra-fixed.c":1,"clock":1}
,"clk-tegra-fixed.c":{"shared":1}
,"shared":{"clk-tegra-shared.c":1}
,"clk-tegra-shared.c":{"dfll":1}
,"dfll":{"clk-dfll.c":1}
,"clk-dfll.c":{"cbus":1}
,"cbus":{"clk-cbus-shared.c":1}
,"clk-cbus-shared.c":{"emc":1}
,"emc":{"clk-emc.c":1,"host1x":1,"rate":1}
,"clk-emc.c":{"jetson":1}
,"jetson":{"clocks":1,"tx2":1}
,"soc\u002Ftegra\u002Fkernel-include\u002Fdt-bindings\u002Fclock\u002Ftegra21":{"0-car.h":1}
,"0-car.h":{"jetson":1}
,"tx2":{"clocks":1,"follows":1,"debugfs":1}
,"soc\u002Ft18x\u002Fkernel-include\u002Fdt-bindings\u002Fclock\u002Ftegra186":{"-clock.h":1}
,"-clock.h":{"check":1}
,"enter":{"following":1}
,"command":{"launch":1,"echo":1,"cat":1}
,"launch":{"debugfs":1}
,"debugfs":{"check":1,"output":1,"service":1,"bugging":1}
,"sudo":{"cat":1}
,"cat":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Fgbus\u002Fclk_possible_rates":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk":{"\u002Fclk_summary":1}
,"\u002Fclk_summary":{"example":1}
,"example":{"debugfs":1,"gpu":1,"find":1,"verride":1,"padctl-uphy":1}
,"output":{"tx1":1,"tx2":1}
,"tx1":{"follows":1,"contains":1}
,"follows":{"example":1,"overriding":1,"clocks":1}
,"overriding":{"default":1}
,"default":{"clock":1}
,"during":{"boot":1}
,"boot":{"updated":1}
,"updated":{"ntrol":1}
,"ntrol":{"driver":1}
,"framework":{"case":1}
,"case":{"bpmp":1,"tx2":1}
,"bpmp":{"case":1,"example":1}
,"service":{"provides":1}
,"provides":{"override":1}
,"override":{"default":1}
,"bugging":{"experimental":1}
,"experimental":{"purposes":1}
,"purposes":{"tx1":1}
,"contains":{"following":1}
,"controlled":{"arious":1,"bpmp":1}
,"arious":{"frameworks":1}
,"frameworks":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride":{"[ape":1}
,"[ape":{"c3bus":1}
,"c3bus":{"gbus":1}
,"gbus":{"mselect":1,"rate":1,"frequency":1,"following":1}
,"mselect":{"abus":1}
,"abus":{"c2b":1}
,"c2b":{"emc":1}
,"host1x":{"sclk]":1}
,"sclk]":{"example":1}
,"gpu":{"clock":1,"frequency":1}
,"i.e":{"gbus":1}
,"frequency":{"scaling":1,"target":1,"tings":1,"clock":1,"configured":1}
,"scaling":{"change":1,"following":1}
,"change":{"gbus":1,"clock":1}
,"commands":{"echo":1}
,"echo":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.gbus\u002Fclk_u":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.gbus\u002Fclk_s":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002F<module>":1,"\u002Fsys\u002Fkern":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.gbus\u002Fclk_u":{"pdate_rate":1}
,"pdate_rate":{"echo":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.gbus\u002Fclk_s":{"tate":1}
,"tate":{"e-enable":1,"valid":1}
,"e-enable":{"gbus":1}
,"valid":{"clock":1}
,"found":{"using":1}
,"using":{"clk_possible_rates":1,"clock-names":1}
,"clk_possible_rates":{"example":1}
,"find":{"rates":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Fgbus\u002Fclk_possible_rates":{"clocks":1}
,"update":{"clock":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002F<module>":{"\u002Fclk_update_rate":1}
,"\u002Fclk_update_rate":{"tx2":1}
,"verride":{"emc":1}
,"\u002Fsys\u002Fkern":{"el\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc":1}
,"el\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc":{"\u002Fmrq_rate_locked":1}
,"\u002Fmrq_rate_locked":{"echo":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fbpmp\u002Fdebug\u002Fclk\u002Femc":{"\u002Fstate":1,"\u002Frate":1}
,"\u002Fstate":{"echo":1}
,"\u002Frate":{"configuring":1}
,"general":{"block":1}
,"block":{"module":1}
,"module":{"dedicated":1,"divider":1,"declare":1}
,"dedicated":{"lock":1}
,"register":{"detailed":1,"clk_rst_controller_clk_source_<module_name>":1}
,"detailed":{"information":1}
,"abo":{"given":1}
,"given":{"register":1}
,"clk_rst_controller_clk_source_<module_name>":{"tegra":1}
,"registers":{"provide":1}
,"provide":{"clock":1}
,"select":{"ion":1,"specified":1}
,"ion":{"clock":1}
,"control":{"module":1}
,"typically":{"bits":1}
,"bits":{"integer":1,"fractional":1}
,"integer":{"bits":1}
,"fractional":{"bit":1}
,"bit":{"(u7.1)":1}
,"(u7.1)":{"change":1}
,"configurations":{"kernel":1}
,"devic":{"driver":1}
,"declare":{"clocks":1}
,"padctl-uphy":{"clocks":1}
,"declared":{"follows":1}
,"=<&tegra_car":{"tegra210_clk_hsic_trk>":1}
,"tegra210_clk_hsic_trk>":{"<&tegra_car":1}
,"<&tegra_car":{"tegra210_clk_usb2_trk>":1,"tegra210_clk_pll_e>":1}
,"tegra210_clk_usb2_trk>":{"<&tegra_car":1}
,"tegra210_clk_pll_e>":{"clock-names":1}
,"clock-names":{"hsic_trk":1,"clk_get_parent":1}
,"hsic_trk":{"usb2_trk":1}
,"usb2_trk":{"pll_e":1}
,"pll_e":{"devm_clk_get":1}
,"function":{"obtain":1,"select":1,"frequency":1,"exact":1,"used":1}
,"obtain":{"desired":1,"parent":1}
,"desired":{"clock":1}
,"clk_get_parent":{"function":1}
,"parent":{"clock":1}
,"desir":{"clock":1}
,"clk_set_parent":{"function":1}
,"specified":{"clock":1}
,"targe":{"clock":1}
,"clk_set_rate":{"function":1}
,"target":{"clock":1,"rate":1}
,"calculated":{"automatically":1}
,"automatically":{"according":1}
,"according":{"target":1}
,"successful":{"clock":1}
,"tings":{"meet":1}
,"meet":{"available":1}
,"modu":{"frequency":1}
,"clk_round_rate":{"function":1}
,"exact":{"clock":1}
,"configured":{"current":1}
,"current":{"clock":1}
,"(or":{"clk_prepare":1}
,"clk_prepare":{"clk_enable":1,"function":1}
,"ungate\u002Fenable":{"clock":1}
,"used":{"instead":1}
,"ungate":{"clock":1}
,"operation":{"may":1}
,"may":{"sleep":1,"additional":1}
,"sleep":{"note":1}
,"modules":{"may":1}
,"additional":{"dividers":1}
,"dividers":{"e.g":1}
,"e.g":{"dc_disp_disp_clock_control_0":1}
,"dc_disp_disp_clock_control_0":{"information":1}
}
;Search.control.loadWordPairs(pairs);
