var pairs =
{
"power":{"management":1,"mal":1,"gate":1,"state":1,"performance":1,"thermal":1,"saving":1,"extend":1,"states":1,"aud":1,"rails":1,"rail":1,"tree":1,"performanc":1,"savi":1,"(tdp)":1,"consumption":1,"monitor":1,"<n>":1,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F1":1,"input":1,"monitors":1,"execut":1,"follows":1}
,"management":{"tx1":1,"thermal":1,"electrical":1,"features":1,"however":1,"frequency":1,"tegra":1,"strategy":1,"tuned":1,"cpufreq":1,"cpuidle":1,"per-core":1,"essential":1,"provides":1,"performed":1,"clock":1,"requires":1,"using":1,"fan":1,"uses":1}
,"tx1":{"devices":1,"platform":1}
,"devices":{"nvidia":1,"comprising":1,"within":1,"additionally":1,"cor":1,"measure":1,"used":1,"cooling":1,"nct1008":1,"sense":1,"gpu_balanced":1,"provides":1}
,"nvidia":{"tegra":1,"tegra210-cpuidle":1,"tegra210-cpuidl":1}
,"tegra":{"system":1,"board":1,"implements":1,"dram":1,"maintains":1,"exiting":1,"bsp":1,"may":1,"uses":1,"handled":1,"devices":1,"cpu":1,"architecture":1,"hardware":1,"cpuidle":1,"chip":1,"thermal":1,"sensing":1,"several":1,"platform":1,"platforms":1,"enters":1,"exits":1,"performance":1}
,"system":{"-on-a-chip":1,"sc7":1,"stability":1,"keeps":1,"tuning":1,"rising":1,"save":1,"clock":1}
,"-on-a-chip":{"(soc)":1}
,"(soc)":{"nvidia":1}
,"board":{"support":1,"configuration":1,"design":1,"information":1,"tegra":1,"3-channel":1,"power":1,"supply":1,"3.3":1,"1.8":1}
,"support":{"package":1,"firmware":1,"idle":1}
,"package":{"(bsp)":1}
,"(bsp)":{"provides":1}
,"provides":{"feature":1,"uniformly":1,"abstract":1,"mechanism":1,"regula":1,"tegra-specific":1,"following":1,"generic":1,"knobs":1,"several":1,"example":1,"ifferent":1,"simple":1,"thermal":1,"fan":1,"veral":1,"jetson_clocks.sh":1}
,"feature":{"related":1,"example":1,"requires":1}
,"related":{"power":1,"frequ":1,"tools":1}
,"thermal":{"management":1,"electrical":1,"throttli":1,"reset":1,"manage":1,"action":1,"framework":1,"zone":1,"sensor":1,"zones":1,"rformance":1,"knobs":1,"sensing":1,"constraints":1,"capabilities":1,"events":1,"shutdown":1,"cooling":1,"throttling":1}
,"electrical":{"management":1,"problems":1,"man":1,"limits":1}
,"features":{"deliver":1,"power":1,"dynamicall":1,"present":1,"section":1,"tegra":1,"save":1,"implemented":1,"whose":1,"statically":1}
,"deliver":{"best":1,"equested":1}
,"best":{"user":1,"rformance":1,"possible":1}
,"user":{"experience":1,"-space":1,"example":1}
,"experience":{"possible":1,"ensures":1,"tegra":1,"device":1}
,"possible":{"given":1,"performance":1}
,"given":{"constraints":1,"tem":1}
,"constraints":{"particular":1,"vice":1}
,"particular":{"platform":1,"task":1}
,"platform":{"target":1,"nitialization":1,"power":1,"ensure":1,"avoids":1,"drivers":1,"driver":1,"kernel":1,"thermal":1,"specific":1,"includes":1}
,"target":{"user":1,"requency":1}
,"ensures":{"perception":1,"cpu":1}
,"perception":{"device":1}
,"device":{"provides":1,"tree":1,"cat":1,"trees":1,"drivers":1,"trip":1,"configuring":1,"becomes":1,"passive":1,"associated":1,"actually":1,"remove":1,"lock":1,"classified":1,"pwm-fan":1,"maps":1,"attached":1,"feels":1,"device":1,"heats":1,"sysfs":1}
,"uniformly":{"high":1}
,"high":{"performance":1,"temperature":1}
,"performance":{"excellent":1,"ther":1,"encompasses":1,"scenarios":1,"ecause":1,"user":1,"given":1,"tegra":1,"sett":1,"execute":1}
,"excellent":{"battery":1}
,"battery":{"life":1}
,"life":{"perfect":1,"features":1}
,"perfect":{"stability":1}
,"stability":{"omfortabl":1,"quality":1}
,"omfortabl":{"cool":1}
,"cool":{"touch":1,"ing":1}
,"touch":{"interacting":1}
,"interacting":{"features":1}
,"mal":{"electrical":1,"zones":1}
,"dynamicall":{"constrain":1}
,"constrain":{"knobs":1}
,"knobs":{"clock":1,"constrained":1,"tune":1,"available":1}
,"clock":{"gate":1,"frequencies":1,"voltage":1,"register":1,"tree":1,"framework":1,"adjustment":1,"speed":1,"cpu":1,"halted":1,"throttling":1,"lowered":1,"frequency":1,"information":1,"settings":1,"setting":1}
,"gate":{"settings":1,"(or":1}
,"settings":{"clock":1,"voltages":1,"boot":1,"store":1,"file":1,"--store":1,"execute":1}
,"frequencies":{"power":1,"require":1,"idle":1,"optimized":1,"system":1}
,"(or":{"regulator":1}
,"regulator":{"enable)":1,"framework":1,"consumer":1,"provider":1,"consumers":1}
,"enable)":{"settings":1}
,"voltages":{"processor":1,"vice":1}
,"processor":{"power":1}
,"state":{"(i.e":1,"elected":1,"selected":1,"availability":1,"extraordinarily":1,"range":1,"functionality":1,"state":1,"maintained":1,"via":1,"tegra":1,"pmc":1,"occurs":1,"software":1,"power":1,"mapping":1,"chipset":1,"comments":1,"clock":1,"description":1,"cluster":1,"stays":1,"idle":1,"meaning":1,"cpu":1,"core":1,"statistics":1,"read":1,"boot":1,"cc6":1,"con":1,"thermal":1,"fan":1,"operation":1,"per":1,"run":1}
,"(i.e":{"idle":1,"vdd_in)":1}
,"idle":{"state":1,"sabled":1,"power":1,"management":1,"states":1,"final":1,"tegra-specific":1,"tegra":1,"idle":1,"task":1,"offline":1}
,"elected":{"cpu)":1}
,"cpu)":{"peripheral":1}
,"peripheral":{"power":1,"devices":1}
,"selected":{"controller)":1,"runtime":1,"tuned":1}
,"controller)":{"chipset":1}
,"chipset":{"power":1}
,"availability":{"cpu":1}
,"cpu":{"cores":1,"adjusts":1,"frequency":1,"thermal":1,"may":1,"exposes":1,"via":1,"power":1,"ynamic":1,"tegra":1,"hardwar":1,"voltage":1,"frequencies":1,"core":1,"cluster":1,"idle":1,"last":1,"following":1,"-balanced":1,"gpu":1,"lower":1,"upper":1,"hot":1,"hotplug":1,"echo":1,"state":1}
,"cores":{"knobs":1}
,"constrained":{"feature":1}
,"example":{"cpufreq":1,"vdd_cpu":1,"higher":1,"final":1,"number":1,"thermal":1}
,"cpufreq":{"implements":1,"consequently":1,"tegra":1,"subsystem":1,"governor":1,"platform":1}
,"implements":{"load":1,"several":1,"cpu":1,"feedback":1}
,"load":{"based":1}
,"based":{"scaling":1,"busy":1,"pre-defined":1}
,"scaling":{"based":1,"closely":1,"example":1,"dynamic":1,"idle":1,"policies":1,"depends":1,"memory":1,"policy":1,"enabled":1,"run":1}
,"busy":{"cpu":1}
,"adjusts":{"cpu":1}
,"frequency":{"accordingly":1,"proportional":1,"scaling":1,"management":1,"change":1,"thereby":1,"direct":1,"cpu":1,"tables":1,"cap":1,"run":1,"value":1}
,"accordingly":{"cpu":1}
,"however":{"override":1}
,"override":{"target":1}
,"requency":{"cpufreq":1,"caling":1,"voltage":1}
,"consequently":{"efore":1}
,"efore":{"attempting":1}
,"attempting":{"debug":1}
,"debug":{"power":1}
,"ther":{"mal":1}
,"problems":{"familiarize":1}
,"familiarize":{"yourself":1}
,"yourself":{"power":1}
,"man":{"agement":1}
,"agement":{"features":1}
,"present":{"bsp":1,"sensor":1,"nodes":1}
,"bsp":{"kernel-space":1,"maps":1,"configures":1,"act":1,"new":1,"drivers":1,"implements":1,"mplements":1,"includes":1,"provides":1,"supports":1,"specific":1,"tuned":1,"reads":1,"provided":1,"nsors":1,"balanced":1,"performs":1,"defines":1}
,"kernel-space":{"power":1,"interfaces":1}
,"saving":{"features":1}
,"section":{"describes":1}
,"describes":{"features":1}
,"several":{"features":1,"thermal":1,"types":1,"drivers":1}
,"save":{"power":1,"state":1}
,"extend":{"battery":1,"ing":1}
,"implemented":{"linux":1}
,"linux":{"kernel":1,"tegra":1,"power":1,"common":1,"regulator":1,"cpufreq":1,"cpuidle":1,"thermal":1,"trip":1}
,"kernel":{"support":1,"linux":1,"driver":1,"ensures":1,"requested":1,"device":1,"software":1,"described":1}
,"firmware":{"hardware":1}
,"hardware":{"without":1,"wake":1,"power":1,"powe":1,"additionally":1,"reference":1,"clock":1,"throttling":1,"shutdown":1,"thermal":1,"tegra":1,"reset":1}
,"without":{"significant":1,"knowledge":1}
,"significant":{"involvement":1}
,"involvement":{"user":1}
,"-space":{"chipset":1}
,"states":{"supported":1,"listed":1,"follows":1,"devices":1,"onto":1,"cor":1,"cpu":1,"applicable":1,"extend":1,"tegra":1,"core":1,"denoted":1,"cluster":1,"ccplex":1,"table":1,"available":1,"clock-gat":1,"cc1":1,"status":1,"enabled":1,"pwm-rpm":1,"translate":1}
,"supported":{"power":1}
,"listed":{"order":1}
,"order":{"increasing":1}
,"increasing":{"flexibili":1}
,"flexibili":{"configurability":1}
,"configurability":{"system":1,"ample":1}
,"sc7":{"minimally":1,"software":1,"enters":1,"platforms":1,"state":1,"turned":1}
,"minimally":{"flexible":1}
,"flexible":{"deep":1,"terms":1}
,"deep":{"sleep":1}
,"sleep":{"(sc7":1,"software":1,"active":1,"supply":1}
,"(sc7":{"offers":1,"power":1}
,"offers":{"small":1}
,"small":{"amount":1,"ount":1}
,"amount":{"configurability":1}
,"ample":{"prior":1}
,"prior":{"entering":1}
,"entering":{"deep":1}
,"software":{"select":1,"actively":1,"initiate":1,"choose":1,"main":1,"runtime":1,"clock":1,"shutdown":1,"aotag.c":1,"nct1008.c":1,"cooldown":1,"throttling":1,"pwm_fan.c":1,"slowdown":1,"software":1,"hardware":1,"linux":1,"program":1,"thermal":1}
,"select":{"hardware":1}
,"wake":{"events":1,"chip":1}
,"events":{"allowed":1,"active":1,"thermal":1}
,"allowed":{"wake":1}
,"chip":{"deep":1,"unavailable":1,"include":1,"thermal":1}
,"active":{"state":1,"mode)":1,"mode":1,"power":1,"devices":1,"user":1,"core":1,"passive":1,"cooling":1}
,"extraordinarily":{"flexible":1}
,"terms":{"power":1,"accuracy":1}
,"encompasses":{"activity":1}
,"activity":{"levels":1}
,"levels":{"low":1}
,"low":{"power":1,"-power":1,"power-state":1}
,"aud":{"playback":1}
,"playback":{"peak":1}
,"peak":{"performance":1}
,"scenarios":{"wer":1}
,"wer":{"consumption":1}
,"consumption":{"active":1,"helps":1,"modeling":1}
,"range":{"tens":1,"degrees":1}
,"tens":{"milliwatts":1}
,"milliwatts":{"multiple":1}
,"multiple":{"watts":1}
,"watts":{"supported":1}
,"follows":{"power":1,"core":1,"thermal":1,"command":1,"isabl":1,"jetson-clocks.sh":1,"manually":1}
,"functionality":{"characteristics":1}
,"characteristics":{"power":1}
,"rails":{"none":1,"supplying":1,"vdd_rtc":1,"powered":1,"(inc":1}
,"none":{"power":1}
,"supplying":{"tegra":1}
,"dram":{"powered":1,"exiting":1,"power":1,"maintains":1,"self-refresh":1,"critical":1}
,"powered":{"state":1,"vdd_co":1,"power":1,"companion":1}
,"maintained":{"tegra":1}
,"exiting":{"exit":1,"software":1}
,"exit":{"state":1}
,"via":{"cold-boot":1,"linux":1,"fan":1,"software":1,"device":1,"oil":1}
,"cold-boot":{"(into":1}
,"(into":{"active":1}
,"mode)":{"deep":1}
,"vdd_rtc":{"vddio_ddr":1}
,"vddio_ddr":{"vddio_sys":1}
,"vddio_sys":{"dram":1,"vdd_core":1}
,"rail":{"powered":1,"powers":1,"name":1,"current":1,"voltage":1,"power":1,"names":1,"channel":1,"jetson":1}
,"vdd_co":{"vdd_cpu":1}
,"vdd_cpu":{"powered":1,"may":1}
,"maintains":{"small":1,"sta":1}
,"ount":{"state":1}
,"pmc":{"block":1}
,"block":{"dram":1}
,"sta":{"exiting":1,"nodes":1}
,"occurs":{"based":1,"cooling":1}
,"pre-defined":{"wake":1}
,"mode":{"active":1,"increase":1}
,"vdd_core":{"dram":1}
,"(inc":{"luding":1}
,"luding":{"vdd_c":1}
,"vdd_c":{"pu)":1,"cpu":1}
,"pu)":{"may":1}
,"may":{"state":1,"idle":1,"powered":1,"power-gated":1,"present":1,"due":1}
,"actively":{"manages":1}
,"manages":{"power":1}
,"comprising":{"tegra":1}
,"initiate":{"transition":1}
,"transition":{"active":1,"cpu":1,"dram":1}
,"mapping":{"linux":1,"various":1}
,"maps":{"hardware":1,"pwm":1}
,"onto":{"linux":1}
,"comments":{"-suspend":1}
,"-suspend":{"sc7":1}
,"choose":{"whether":1}
,"whether":{"enter":1}
,"enter":{"sc7":1,"specified":1}
,"enters":{"suspend":1,"sc7":1}
,"suspend":{"running\u002Fidle":1}
,"running\u002Fidle":{"(display":1}
,"(display":{"off)":1}
,"off)":{"active":1}
,"within":{"tegra":1,"cluster":1,"safe":1,"thermal":1,"recommended":1}
,"sabled":{"driver":1}
,"driver":{"control":1,"cpu":1,"provides":1,"called":1,"tegra":1,"reconciles":1,"plugs":1,"transition":1,"optionally":1,"cpuidle":1,"devices":1,"may":1}
,"control":{"example":1,"temperatures":1,"oling":1,"programming":1,"change":1,"during":1,"loo":1}
,"companion":{"cpu":1}
,"power-gated":{"note":1}
,"note":{"nvidia":1,"ascii":1,"ina":1,"terms":1}
,"uses":{"scy":1,"fll":1,"temperature":1,"fan":1,"current":1,"output":1}
,"scy":{"instead":1}
,"instead":{"lpx":1}
,"lpx":{"name":1}
,"name":{"chipset":1,"idx":1,"tegra":1,"cooling":1,"in_current":1,"description":1,"voltage":1,"(i.e":1}
,"voltage":{"management":1,"ynamic":1,"scaling":1,"current":1,"appropriate":1,"rail":1,"reduces":1,"in_power":1,"urrent":1}
,"proportional":{"voltage":1}
,"ynamic":{"voltage":1,"requency":1}
,"closely":{"related":1}
,"frequ":{"ency":1}
,"ency":{"scaling":1}
,"higher":{"frequencies":1,"voltages":1,"rpm":1,"temperature":1,"cooling":1}
,"require":{"higher":1}
,"vice":{"versa":1,"thermal":1}
,"versa":{"ost":1}
,"ost":{"clock":1}
,"register":{"manipulation":1}
,"manipulation":{"tegra":1}
,"handled":{"linux":1}
,"exposes":{"simplified":1,"two":1}
,"simplified":{"view":1}
,"view":{"physical":1}
,"physical":{"clock":1}
,"tree":{"software":1,"framework":1,"topology":1,"suc":1,"appro":1,"configured":1,"board":1,"node":1,"following":1,"file":1,"thermal":1,"sers":1,"programs":1,"binary":1}
,"main":{"cpu":1,"module":1}
,"common":{"clock":1}
,"framework":{"regulator":1,"linux":1,"provides":1,"connect":1,"enable":1,"thermal":1,"avai":1,"makes":1}
,"abstract":{"ion":1}
,"ion":{"allow":1}
,"allow":{"regulator":1,"software":1}
,"consumer":{"drivers":1,"api":1}
,"drivers":{"dynamically":1,"within":1,"peripheral":1,"registering":1,"implement":1,"policy":1,"(cpufreq":1,"usb":1,"provide":1,"temperature":1}
,"dynamically":{"adjust":1,"imposed":1}
,"adjust":{"voltage":1}
,"current":{"regulators":1,"temperature":1,"in_voltage":1,"power":1,"frequency":1,"clock":1,"clo":1,"settings":1}
,"regulators":{"runtime":1}
,"runtime":{"without":1,"details":1,"features":1,"entries":1}
,"knowledge":{"underlying":1}
,"underlying":{"hardware":1}
,"powe":{"tree":1}
,"mechanism":{"platform":1,"governors":1}
,"nitialization":{"code":1}
,"code":{"declare":1,"snippet":1}
,"declare":{"power":1}
,"topology":{"assign":1}
,"assign":{"driver":1}
,"regula":{"tors":1}
,"tors":{"node":1}
,"node":{"hardware":1,"enable":1,"status":1,"note":1,"cat":1,"value":1}
,"suc":{"driver":1}
,"called":{"regulator":1,"critical":1}
,"provider":{"driver":1}
,"configures":{"platform":1,"sensor":1}
,"appro":{"priately":1}
,"priately":{"tegra":1}
,"additionally":{"drivers":1,"ensure":1,"final":1,"tegra":1}
,"act":{"gulator":1}
,"gulator":{"consumers":1}
,"consumers":{"appropriate":1,"cause":1}
,"appropriate":{"porting":1,"fll":1,"node":1,"device":1,"core\u002Fcluster":1}
,"porting":{"tegra":1}
,"new":{"platform":1,"printed":1,"cooli":1}
,"ensure":{"hat":1,"drivers":1,"device":1}
,"hat":{"platform":1}
,"configured":{"correctl":1}
,"correctl":{"match":1}
,"match":{"underlying":1}
,"cor":{"rectly":1,"management":1}
,"rectly":{"regulator":1}
,"api":{"bsp":1}
,"registering":{"regulator":1}
,"cause":{"pads":1,"irreversible":1}
,"pads":{"chip":1,"cpu":1}
,"unavailable":{"functions":1}
,"functions":{"ensure":1,"using":1}
,"configuration":{"file":1,"table":1}
,"file":{"informati":1,"following":1,"disable":1,"emc":1,"restore":1,"script":1,"default":1,"l4t_dfs.conf":1}
,"informati":{"new":1}
,"avoids":{"conflicts":1}
,"conflicts":{"functions":1}
,"using":{"pads":1,"kconfig":1,"cpu":1,"fan":1,"active":1,"sysfs":1}
,"strategy":{"includes":1}
,"includes":{"dynam":1,"drivers":1,"several":1,"driver":1}
,"dynam":{"frequency":1}
,"dynamic":{"voltage":1,"frequency":1}
,"tuned":{"tegra":1,"achieve":1,"provide":1}
,"architecture":{"frequency":1}
,"caling":{"(dfs)":1,"frequency":1}
,"(dfs)":{"linux":1}
,"subsystem":{"cpufreq":1,"comprises":1}
,"comprises":{"platform":1}
,"implement":{"clock":1,"frequency":1}
,"adjustment":{"mechanism":1}
,"governors":{"implement":1,"platform":1,"thermal":1,"tegra":1}
,"policies":{"core":1}
,"core":{"framework":1,"puidle":1,"state":1,"clock-gated":1,"within":1,"transitioning":1,"puts":1,"cpu":1,"states":1,"power":1,"pathnames":1,"tates":1,"<x>":1,"enter":1,"spent":1,"entered":1,"number":1}
,"connect":{"governors":1}
,"policy":{"frequency":1,"following":1,"runtime":1}
,"depends":{"cpufreq":1}
,"governor":{"selected":1,"requests":1,"selects":1,"tegra":1,"progressively":1,"uses":1}
,"details":{"consult":1}
,"consult":{"information":1}
,"information":{"available":1,"linux":1,"thermal":1,"fan":1,"ina3221":1,"run":1}
,"available":{"<top":1,"210":1,"<top>\u002Fkernel\u002Fdocumentation\u002Fdevicetree\u002Fbindings\u002Fthermal.t":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fscaling_avail":1,"\u002Fsys\u002Fdevices\u002F57000000.g":1,"$home\u002Fjetson_clocks":1}
,"<top":{">\u002Fkernel\u002Fkernel\u002Fkernel-4.4\u002Fdocumentation\u002Fcpu-freq":1}
,">\u002Fkernel\u002Fkernel\u002Fkernel-4.4\u002Fdocumentation\u002Fcpu-freq":{"\u002Ffor":1}
,"\u002Ffor":{"tegra":1}
,"reference":{"design":1}
,"design":{"cpufreq":1,"calibration":1,"emc":1,"power":1}
,"achieve":{"balance":1}
,"balance":{"power":1}
,"performanc":{"governor":1}
,"requests":{"cpu":1,"made":1}
,"change":{"tegra-specific":1,"speed":1,"cpu":1,"gpu":1}
,"tegra-specific":{"cpufreq":1,"cpuidle":1}
,"reconciles":{"request":1}
,"request":{"limi":1}
,"limi":{"imposed":1}
,"imposed":{"thermal":1}
,"limits":{"iver":1,"dynamically":1,"cooling":1,"device":1,"software":1,"follows":1}
,"iver":{"updates":1}
,"updates":{"clock":1}
,"speed":{"cpu":1,"control":1,"fan":1}
,"fll":{"clock":1,"deliver":1}
,"hardwar":{"(with":1,"thermal":1}
,"(with":{"assistance":1}
,"assistance":{"linux":1}
,"equested":{"cpu":1}
,"cpuidle":{"linux":1,"infrastructure":1,"driver":1,"framework":1,"drive":1,"governor":1,"enable":1,"device":1,"{compatible":1,"boot":1}
,"infrastructure":{"supports":1,"<top>":1}
,"supports":{"implementation":1,"fan":1}
,"implementation":{"soc":1}
,"soc":{"-specific":1,"resources":1}
,"-specific":{"idle":1}
,"puidle":{"lacks":1}
,"lacks":{"direct":1}
,"direct":{"support":1,"mpact":1}
,"applicable":{"entire":1}
,"entire":{"cpu":1}
,"cluster":{"idle":1,"information":1,"transitions":1,"cluste":1,"state":1,"clock":1,"ransitions":1,"low":1,"states":1,"run":1}
,"ing":{"beyond":1,"power-gating":1,"non-cpu":1,"device":1,"tegra":1,"requency":1,"static":1}
,"beyond":{"cpu":1}
,"<top>":{"\u002Fkernel":1}
,"\u002Fkernel":{"\u002Fkernel\u002Fkernel-4.4":1}
,"\u002Fkernel\u002Fkernel-4.4":{"\u002Fdocumentation\u002Fcpuidle":1}
,"\u002Fdocumentation\u002Fcpuidle":{"\u002Fnvidia":1}
,"\u002Fnvidia":{"provides":1}
,"plugs":{"cpuidle":1}
,"enable":{"cpu":1,"cpuid":1,"cpuidle":1,"cpui":1}
,"per-core":{"cpu":1,"state":1}
,"drive":{"exposes":1}
,"two":{"per-core":1}
,"description":{"cpu":1,"cc1":1,"rail_name_<n>":1,"channel":1,"--show":1}
,"clock-gated":{"transition":1}
,"final":{"core":1,"cpu":1}
,"transitions":{"idle":1}
,"cluste":{"idle":1}
,"cc1":{"cpu":1,"auto":1}
,"halted":{"additionally":1}
,"ransitions":{"idle":1}
,"optionally":{"disables":1,"following":1}
,"disables":{"soc":1}
,"resources":{"cpu":1}
,"last":{"active":1}
,"transitioning":{"dle":1}
,"dle":{"optionally":1,"configuration":1}
,"following":{"transition":1,"option":1,"compatibility":1,"command":1,"node":1,"device":1,"factors":1,"capabili":1,"table":1,"compone":1,"code":1,"commands":1}
,"self-refresh":{"clock-gate":1}
,"clock-gate":{"mc\u002Femc":1}
,"mc\u002Femc":{"halt":1}
,"halt":{"various":1}
,"various":{"pll":1,"device":1,"clocks":1,"power":1,"ramp":1}
,"pll":{"cpu":1}
,"task":{"scheduled":1,"cpuidle":1,"puts":1}
,"scheduled":{"runna":1}
,"runna":{"ble":1}
,"ble":{"tasks":1,"<top>\u002Fkernel\u002Fdocumentation\u002Fthermal\u002Fsysfs-api.txt":1}
,"tasks":{"left":1}
,"left":{"runqueue":1}
,"runqueue":{"particular":1}
,"selects":{"core":1}
,"puts":{"low":1,"entire":1}
,"-power":{"state":1}
,"stays":{"until":1}
,"until":{"interrupt":1,"higher":1}
,"interrupt":{"kes":1}
,"kes":{"process":1}
,"process":{"work":1}
,"work":{"last":1}
,"offline":{"state":1}
,"power-state":{"ccplex":1}
,"ccplex":{"idle":1,"states":1}
,"denoted":{"states":1,"ccp":1}
,"ccp":{"states":1}
,"table":{"below":1,"(bct":1,"specific":1,"included":1,"average":1,"identifies":1,"thermal":1}
,"below":{"summarizes":1,"ccuracy":1}
,"summarizes":{"different":1}
,"different":{"states":1}
,"210":{"state":1}
,"meaning":{"core":1}
,"clock-gat":{"ing":1}
,"power-gating":{"cluster":1,"cc7":1}
,"auto":{"clock-gat":1}
,"non-cpu":{"power-gating":1}
,"cc7":{"rail-gating":1,"sc2":1}
,"rail-gating":{"using":1}
,"kconfig":{"device":1}
,"cpuid":{"kconfig":1}
,"cpui":{"dle":1}
,"option":{"config_cpu_idle=y":1}
,"config_cpu_idle=y":{"enable":1}
,"compatibility":{"string":1}
,"string":{"already":1,"nvidia":1}
,"already":{"enabled":1}
,"enabled":{"cpuidle":1,"a57":1,"--------------------------c7":1,"boot":1,"default":1}
,"{compatible":{"nvidia":1}
,"tegra210-cpuidle":{"status":1}
,"status":{"okay":1,"core":1,"write":1,"cluster":1}
,"okay":{"cpu\u2019s":1}
,"cpu\u2019s":{"core":1}
,"pathnames":{"nodes":1}
,"nodes":{"represent":1,"following":1,"naming":1,"follows":1,"modify":1,"read":1}
,"represent":{"core":1}
,"tates":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":{"<x>":1,"<x>\u002Fcpuidle\u002Fstate":1}
,"<x>":{"\u002Fcpuidle\u002Fstate":1,"read":1}
,"\u002Fcpuidle\u002Fstate":{"\u002F*\u2022":1}
,"\u002F*\u2022":{"status":1}
,"read":{"appropriate":1,"following":1,"using":1,"rail":1,"ina3221":1,"vdd_in":1}
,"write":{"ascii":1}
,"ascii":{"node":1,"corresponds":1}
,"corresponds":{"disabled":1}
,"disabled":{"enabl":1}
,"enabl":{"cluster":1}
,"a57":{"cluster":1,"core":1}
,"run":{"following":1}
,"command":{"cat":1,"description":1,"echo":1,"usage":1,"sudo":1,"turn":1}
,"cat":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle_t210\u002Ffast_cluster_st":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fcpuidle\u002Fstate":1,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F1":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Fclk_summary":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_m":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_c":1,"\u002Fsys\u002Fdevices\u002F57000000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fmin":1,"\u002Fsys\u002Fdevices\u002F57000":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Ftegra_bwmgr\u002Femc_min_rate":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Ftegra_bwmgr\u002Femc_max":1,"\u002Fsys\u002Fk":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fonline":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fcpuidle_t210\u002Ffast_cluster_st":{"ates_enable":1}
,"ates_enable":{"value":1}
,"value":{"returned":1,"modifying":1,"available":1,"emc_min_rate":1}
,"returned":{"name":1}
,"idx":{"enabled":1}
,"--------------------------c7":{"cc6":1}
,"cc6":{"cc7":1,"run":1}
,"sc2":{"sc3":1}
,"sc3":{"sc4":1}
,"sc4":{"per-core":1}
,"statistics":{"number":1}
,"number":{"times":1,"0-2":1,"print":1}
,"times":{"kernel":1,"a57":1}
,"requested":{"specified":1}
,"specified":{"core":1,"state":1}
,"<x>\u002Fcpuidle\u002Fstate":{"<y>\u002Fus":1,"<y>\u002Fti":1}
,"<y>\u002Fus":{"age":1}
,"age":{"total":1}
,"total":{"time":1}
,"time":{"microseconds":1,"remove":1}
,"microseconds":{"speci":1,"a57":1}
,"speci":{"fied":1}
,"fied":{"core":1}
,"spent":{"specified":1,"state":1}
,"boot":{"read":1,"time":1,"according":1,"configuration":1,"offset":1}
,"<y>\u002Fti":{"example":1}
,"entered":{"state":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpu2\u002Fcpuidle\u002Fstate":{"\u002Fusage":1,"\u002Ftime":1}
,"\u002Fusage":{"total":1}
,"\u002Ftime":{"disable":1}
,"disable":{"cpuidle":1,"compatibility":1,"core\u002Fcluster":1,"appropriate":1,"frequency":1}
,"remove":{"disable":1,"actual":1,"heat":1}
,"tegra210-cpuidl":{"appropriate":1}
,"core\u002Fcluster":{"power":1,"sta":1}
,"trees":{"tegra210-soc-base.dtsi":1}
,"tegra210-soc-base.dtsi":{"memory":1}
,"memory":{"power":1,"controlle":1,"bandwidth":1}
,"include":{"power":1,"bct":1}
,"whose":{"operation":1,"temperature":1}
,"operation":{"largely":1,"during":1,"cooling":1}
,"largely":{"invisible":1}
,"invisible":{"software":1}
,"statically":{"enabled":1}
,"according":{"settings":1}
,"(bct":{"additionally":1}
,"mplements":{"emc":1}
,"emc":{"frequency":1,"vfs":1,"table":1,"dvfs":1,"clocks":1,"lower":1}
,"controlle":{"(emc\u002Fmc)":1,"ramp-up":1}
,"(emc\u002Fmc)":{"dram":1}
,"critical":{"power":1,"writable":1,"triggers":1,"trip":1}
,"savi":{"feature":1}
,"requires":{"tuning":1,"form":1}
,"tuning":{"characterizati":1,"thermal":1,"limited":1,"remedy":1}
,"characterizati":{"new":1}
,"printed":{"circuit":1}
,"circuit":{"board":1}
,"calibration":{"results":1}
,"results":{"include":1,"higher":1,"cooling":1,"gher":1}
,"bct":{"emc":1}
,"vfs":{"table":1}
,"specific":{"board":1,"thermal":1}
,"included":{"platform":1}
,"factors":{"affect":1}
,"affect":{"emc":1}
,"entries":{"emc":1,"device":1}
,"dvfs":{"table":1,"capabilities":1}
,"average":{"memory":1}
,"bandwidth":{"used":1}
,"used":{"(as":1,"control":1,"communicate":1}
,"(as":{"measur":1}
,"measur":{"hardware)":1}
,"hardware)":{"requests":1}
,"made":{"various":1}
,"(cpufreq":{"graphics":1}
,"graphics":{"drivers":1}
,"usb":{"hdmi":1}
,"hdmi":{"display)":1}
,"display)":{"limits":1}
,"throttli":{"thermal":1}
,"essential":{"system":1}
,"quality":{"user":1}
,"capabili":{"ties":1}
,"ties":{"sensing":1}
,"sensing":{"temperature":1,"soctherm.c":1,"linux":1,"nct":1}
,"temperature":{"reporting":1,"devices":1,"monitored":1,"sensor":1,"limits":1,"sensors":1,"milli":1,"perform":1,"govern":1,"degrees":1,"sensing":1,"ell":1,"remote":1,"die":1,"board":1,"range":1,"tegra":1,"increases":1,"clock":1,"cooling":1,"ensor":1,"rates":1}
,"reporting":{"cooldown":1}
,"cooldown":{"removing":1,"software":1}
,"removing":{"heat":1,"ther":1}
,"heat":{"via":1,"fan":1,"linux":1}
,"fan":{"ntrolling":1,"clock":1,"cooling":1,"management":1,"ntrol":1,"control":1,"speed":1,"smoothly":1,"results":1,"whi":1,"first":1}
,"ntrolling":{"heat":1}
,"throttling":{"slowdown":1,"shutdown":1,"tegra_throttle.c":1,"soctherm.c":1,"performed":1,"cooling":1,"type":1,"governors":1,"needs":1,"various":1,"until":1,"tegra":1,"arious":1,"relies":1,"clocks":1}
,"slowdown":{"hardware":1}
,"shutdown":{"orderly":1,"hardwar":1,"thermal_core.c":1,"soctherm.c":1,"cooling":1,"correction":1,"thermal":1,"special":1,"hardware":1,"ermal":1,"occurs":1,"limits":1,"limit":1}
,"orderly":{"software":1,"shutdown":1}
,"reset":{"tegra":1,"high":1}
,"performed":{"software":1,"using":1}
,"identifies":{"thermal":1,"temperature":1}
,"manage":{"ment":1,"power":1,"cpu":1}
,"ment":{"action":1}
,"action":{"associated":1,"module":1,"trip":1,"balanced":1}
,"associated":{"module":1,"certain":1}
,"module":{"tegr":1,"name":1,"3-channel":1,"power":1}
,"tegr":{"chip":1}
,"soctherm.c":{"kernel":1,"aotag.c":1}
,"aotag.c":{"kernel":1}
,"nct1008.c":{"kernel":1}
,"tegra_throttle.c":{"kernel":1}
,"pwm_fan.c":{"kernel":1}
,"thermal_core.c":{"kernel":1}
,"generic":{"user-space":1}
,"user-space":{"kernel-space":1}
,"interfaces":{"working":1,"defined":1}
,"working":{"devices":1,"thermal":1}
,"measure":{"temperature":1}
,"temperatures":{"central":1}
,"central":{"component":1}
,"component":{"framework":1}
,"zone":{"information":1,"thermal":1,"virtual":1,"tegra-base":1,"via":1,"provides":1,"tegra":1,"following":1,"tx1":1,"monitors":1,"responsible":1,"trip":1,"uses":1,"provided":1,"users":1,"shutdown":1}
,"avai":{"ble":1}
,"<top>\u002Fkernel\u002Fdocumentation\u002Fthermal\u002Fsysfs-api.txt":{"thermal":1}
,"virtual":{"object":1}
,"object":{"represents":1,"following":1}
,"represents":{"area":1}
,"area":{"die":1}
,"die":{"whose":1,"board":1,"near":1,"within":1}
,"monitored":{"controlled":1}
,"controlled":{"essentially":1,"linux":1}
,"essentially":{"working":1}
,"sensor":{"acts":1,"cooling":1,"clock":1,"thermal":1,"controlled":1,"abi":1,"sensed":1,"temperature":1,"operate":1,"gated":1,"stopped":1,"counts":1,"hardware":1}
,"acts":{"object":1}
,"compone":{"nts":1}
,"nts":{"temperature":1}
,"cooling":{"device":1,"actions":1,"trigger":1,"map":1,"devices":1,"active":1,"dev":1,"action":1,"tegra":1,"form":1,"state":1,"throttling":1,"achieved":1,"states":1,"results":1,"strategies":1}
,"trip":{"points":1,"int":1,"point":1,"oint":1}
,"points":{"governor":1,"trip":1,"used":1,"classified":1,"tegra":1,"hardware":1}
,"provide":{"interfaces":1,"optimum":1,"best":1}
,"defined":{"components":1}
,"components":{"topic":1,"demonst":1}
,"topic":{"introduces":1}
,"introduces":{"components":1}
,"demonst":{"rates":1}
,"rates":{"form":1,"stored":1,"tegra":1}
,"form":{"thermal":1,"feedback":1,"fan":1,"orderly":1}
,"tegra-base":{"device":1}
,"configuring":{"thermal":1}
,"tune":{"therma":1}
,"therma":{"response":1}
,"response":{"zone":1}
,"zones":{"tuned":1,"mod":1,"platform":1,"provided":1,"guarantee":1,"define":1}
,"optimum":{"thermal":1}
,"rformance":{"provided":1,"within":1}
,"provided":{"thermal":1,"tegra":1,"using":1,"follow":1}
,"mod":{"ified":1}
,"ified":{"editing":1}
,"editing":{"entries":1}
,"sers":{"define":1}
,"define":{"sensors":1,"special":1}
,"sensors":{"temperature":1,"pread":1,"tegra":1,"setup":1,"generate":1,"allow":1}
,"actions":{"limits":1}
,"becomes":{"hot":1}
,"hot":{"cases":1,"writable":1,"plug":1}
,"cases":{"resolve":1}
,"resolve":{"tuning":1}
,"snippet":{"provides":1}
,"monitors":{"temperat":1,"i2c":1}
,"temperat":{"ure":1}
,"ure":{"thermal_zone_cpu":1}
,"thermal_zone_cpu":{"sensor":1,"cpu_balanced":1}
,"-balanced":{"cooling":1}
,"passive":{"trip":1,"writable":1,"ased":1,"cooling":1,"throttling":1}
,"int":{"cpu_throttle":1}
,"cpu_throttle":{"crossed":1,"{temperature":1}
,"crossed":{"degrees":1}
,"degrees":{"celsius":1}
,"celsius":{"cpu-therm":1,"191":1,"operation":1}
,"cpu-therm":{"{thermal-zone-params":1,"thermal_zone_cpu":1,"pu-therm":1}
,"{thermal-zone-params":{"{governor-name":1}
,"{governor-name":{"step_wise":1}
,"step_wise":{"trips":1}
,"trips":{"{cpu_critical":1}
,"{cpu_critical":{"{temperature":1}
,"{temperature":{"=<102000>":1,"=<100500>":1,"=<97000>":1}
,"=<102000>":{"hysteresis":1}
,"hysteresis":{"=<0>":1}
,"=<0>":{"type":1}
,"type":{"critical":1,"hot":1,"passive":1,"cooling":1,"coolin":1,"point":1}
,"writable":{"cpu_heavy":1,"cpu_throttle":1,"cooling-maps":1}
,"cpu_heavy":{"{temperature":1}
,"=<100500>":{"hysteresis":1}
,"=<97000>":{"hysteresis":1}
,"cooling-maps":{"{map0":1}
,"{map0":{"{trip":1}
,"{trip":{"=<&{\u002Fthermal-zones\u002Fcpu-therm\u002Ftrips\u002Fcpu_criti":1,"=<&{\u002Fthermal-zones\u002Fcpu-therm\u002Ftrips\u002Fcpu_heavy":1,"=<&{\u002Fthermal-zones\u002Fcpu-therm\u002Ftrips\u002Fcpu_throt":1}
,"=<&{\u002Fthermal-zones\u002Fcpu-therm\u002Ftrips\u002Fcpu_criti":{"cal}>":1}
,"cal}>":{"cdev-type":1}
,"cdev-type":{"tegra-shutdown":1,"tegra-heavy":1,"cpu-balanced":1}
,"tegra-shutdown":{"cooling-device":1}
,"cooling-device":{"=<&{\u002Fsoctherm@0x700e2000\u002Fthrottle@critical}":1,"=<&throttle_heavy":1,"=<&{\u002Fbthrot_cdev\u002Fcpu_balanced}":1}
,"=<&{\u002Fsoctherm@0x700e2000\u002Fthrottle@critical}":{"thermal_no_limit":1}
,"thermal_no_limit":{"thermal_no_limit>":1}
,"thermal_no_limit>":{"map1":1,"information":1}
,"map1":{"{trip":1}
,"=<&{\u002Fthermal-zones\u002Fcpu-therm\u002Ftrips\u002Fcpu_heavy":{"cdev-type":1}
,"tegra-heavy":{"cooling-device":1}
,"=<&throttle_heavy":{"map2":1}
,"map2":{"{trip":1}
,"=<&{\u002Fthermal-zones\u002Fcpu-therm\u002Ftrips\u002Fcpu_throt":{"tle}>":1}
,"tle}>":{"cdev-type":1}
,"cpu-balanced":{"cooling-device":1}
,"=<&{\u002Fbthrot_cdev\u002Fcpu_balanced}":{"thermal_no_limit":1}
,"<top>\u002Fkernel\u002Fdocumentation\u002Fdevicetree\u002Fbindings\u002Fthermal.t":{"temperature":1}
,"responsible":{"repor":1}
,"repor":{"ting":1}
,"ting":{"temperature":1}
,"milli":{"-celsius":1}
,"-celsius":{"tegra":1}
,"types":{"temperature":1}
,"pread":{"across":1}
,"across":{"die":1}
,"communicate":{"therm":1}
,"therm":{"zone":1,"throttling":1}
,"point":{"identifies":1,"clock":1,"called":1,"trigger":1,"ows":1,"per":1}
,"perform":{"thermal":1}
,"classified":{"active":1,"critical":1,"passive":1}
,"ased":{"type":1}
,"trigger":{"trip":1,"software":1}
,"oint":{"classified":1}
,"triggers":{"ermal":1}
,"ermal":{"shutdown":1,"design":1}
,"map":{"specifies":1}
,"specifies":{"cool":1}
,"certain":{"trip":1}
,"actually":{"remove":1}
,"actual":{"heat":1}
,"makes":{"distinction":1}
,"distinction":{"classi":1}
,"classi":{"fying":1}
,"fying":{"fan":1}
,"lock":{"throttling":1}
,"coolin":{"device":1}
,"dev":{"ice":1}
,"ice":{"information":1,"and\u002For":1}
,"feedback":{"ntrol":1,"ontrol":1,"control":1}
,"ntrol":{"system":1,"throttling":1}
,"keeps":{"devi":1}
,"devi":{"within":1}
,"safe":{"operating":1}
,"operating":{"temperature":1,"frequency":1,"system":1}
,"govern":{"implements":1}
,"ontrol":{"loop":1}
,"loop":{"linux":1}
,"ifferent":{"governors":1}
,"simple":{"oportional":1}
,"oportional":{"integral":1}
,"integral":{"derivative":1}
,"derivative":{"(pid)":1}
,"(pid)":{"controller":1}
,"controller":{"passive":1}
,"needs":{"tegra":1}
,"described":{"following":1}
,"abi":{"name":1}
,"balanced":{"throttle":1,"cooling":1}
,"throttle":{"temperature":1}
,"cpu_balanced":{"gpu-therm":1,"emergency_balanced":1}
,"gpu-therm":{"thermal_zone_gpu":1}
,"thermal_zone_gpu":{"gpu-balanced":1}
,"gpu-balanced":{"97.5":1}
,"97.5":{"pll-therm":1}
,"pll-therm":{"thermal_zone_pllx":1}
,"thermal_zone_pllx":{"--ao-therm":1}
,"--ao-therm":{"thermal_zone_ao":1}
,"thermal_zone_ao":{"--tboard_tegra":1}
,"--tboard_tegra":{"tmp451":1}
,"tmp451":{"tegra-dram":1,"shutdown_warning":1,"devices":1}
,"tegra-dram":{"tdiode_tegra":1}
,"tdiode_tegra":{"tmp451":1,"remote":1}
,"shutdown_warning":{"104":1}
,"104":{"thermal-fan-est":1}
,"thermal-fan-est":{"pwm_fan":1}
,"pwm_fan":{"51.0":1}
,"51.0":{"gains":1}
,"gains":{"achieved":1}
,"achieved":{"tuning":1,"reducing":1}
,"limited":{"ermal":1}
,"(tdp)":{"system":1}
,"remedy":{"faulty":1}
,"faulty":{"tdp":1}
,"tdp":{"removing":1}
,"guarantee":{"maximum":1}
,"maximum":{"performance":1,"llowable":1}
,"ecause":{"cause":1}
,"irreversible":{"damage":1}
,"damage":{"dev":1,"device":1}
,"and\u002For":{"resets":1}
,"resets":{"thermal":1}
,"nct":{"sensors":1}
,"nct1008":{"nct72":1}
,"nct72":{"tmp451":1}
,"sense":{"temperature":1}
,"ell":{"sensing":1}
,"remote":{"diode":1,"sensor":1}
,"diode":{"tegra":1}
,"platforms":{"sensors":1,"voltage":1}
,"setup":{"follow":1}
,"follow":{"thermal":1,"ing":1}
,"sensed":{"location":1}
,"location":{"tdiode_tegra":1}
,"near":{"gpu":1}
,"gpu":{"tboard_tegra":1,"emc":1,"power":1,"lower":1,"upper":1,"frequency":1}
,"tboard_tegra":{"local":1}
,"local":{"sensor":1}
,"operate":{"extended":1}
,"extended":{"mode":1}
,"increase":{"temperature":1}
,"191":{"degrees":1}
,"during":{"sc7":1,"various":1}
,"powers":{"sensor":1,"clock":1}
,"gated":{"tegra":1}
,"con":{"sequently":1}
,"sequently":{"sensor":1}
,"stopped":{"tegra":1}
,"turned":{"back":1}
,"back":{"tegra":1}
,"exits":{"sc7":1}
,"capabilities":{"nct":1,"clocks":1}
,"generate":{"thermal":1}
,"correction":{"offset":1}
,"offset":{"nct":1,"temperature":1,"fro":1,"reg":1,"calculated":1}
,"program":{"static":1}
,"static":{"offset":1,"cpu":1,"gpu":1,"emc":1,"max":1}
,"counts":{"inaccuracy":1}
,"inaccuracy":{"may":1}
,"reads":{"offset":1}
,"fro":{"device":1}
,"programs":{"offset":1}
,"reg":{"ister":1}
,"ister":{"boot":1}
,"calculated":{"valida":1}
,"valida":{"ted":1}
,"ted":{"via":1}
,"oil":{"bath":1}
,"bath":{"experiments":1}
,"experiments":{"thermal":1}
,"clocks":{"syst":1,"system":1,"reduce":1,"remedied":1,"frequencies":1,"part":1,"potenti":1,"maintain":1,"script":1}
,"syst":{"fan":1}
,"oling":{"device":1}
,"pwm-fan":{"provides":1,"cooling":1}
,"programming":{"pwm":1}
,"pwm":{"controlle":1,"values":1}
,"ramp-up":{"ramp-down":1}
,"ramp-down":{"control":1}
,"smoothly":{"fan":1}
,"pwm-rpm":{"mapping":1}
,"ramp":{"rates":1}
,"stored":{"part":1}
,"part":{"device":1}
,"binary":{"pwm-fan":1,"governor":1}
,"values":{"cooling":1,"result":1}
,"attached":{"monitor":1}
,"monitor":{"temperature":1,"i2c":1,"read":1}
,"nsors":{"temperature":1}
,"increases":{"governor":1}
,"progressively":{"picks":1}
,"picks":{"deeper":1,"higher":1}
,"deeper":{"cooling":1}
,"rpm":{"fan":1}
,"whi":{"results":1}
,"first":{"line":1}
,"line":{"defense":1}
,"defense":{"delay":1}
,"delay":{"clock":1}
,"arious":{"clocks":1}
,"rising":{"tempera":1}
,"tempera":{"ture":1}
,"ture":{"crosses":1}
,"crosses":{"trip":1}
,"relies":{"dvfs":1}
,"reduce":{"operating":1}
,"thereby":{"voltage":1}
,"lowered":{"requency":1}
,"reduces":{"power":1}
,"helps":{"controlling":1}
,"controlling":{"temperature":1}
,"reducing":{"clock":1}
,"mpact":{"performance":1}
,"feels":{"warm":1}
,"warm":{"seems":1}
,"seems":{"sluggish":1}
,"sluggish":{"may":1}
,"due":{"thermal":1}
,"remedied":{"tuning":1}
,"gpu_balanced":{"cpu_balanced":1}
,"emergency_balanced":{"balanced":1}
,"veral":{"cooling":1}
,"translate":{"maximum":1}
,"llowable":{"operating":1}
,"optimized":{"ovide":1}
,"ovide":{"best":1}
,"tem":{"perature":1}
,"perature":{"frequency":1}
,"tables":{"clocks":1}
,"ensor":{"input":1}
,"input":{"feedback":1,"channel":1}
,"loo":{"similarly":1}
,"similarly":{"governor":1}
,"output":{"new":1}
,"cooli":{"state":1}
,"heats":{"governor":1}
,"gher":{"frequency":1}
,"cap":{"clocks":1}
,"potenti":{"ally":1}
,"ally":{"higher":1}
,"performs":{"therm":1}
,"maintain":{"juncti":1}
,"juncti":{"temperature":1}
,"recommended":{"afe":1}
,"afe":{"limits":1}
,"special":{"type":1,"trip":1}
,"ows":{"operating":1}
,"per":{"form":1,"thermal":1}
,"defines":{"critical":1}
,"users":{"lower":1}
,"lower":{"limit":1,"bound":1}
,"limit":{"orderly":1,"degrees":1}
,"strategies":{"failed":1}
,"failed":{"considered":1}
,"considered":{"rare":1}
,"rare":{"ent":1}
,"ent":{"shutdown":1}
,"pu-therm":{"software-based":1}
,"software-based":{"power":1}
,"modeling":{"jetson":1}
,"jetson":{"module":1,"developer":1,"performance":1}
,"3-channel":{"ina3221":1}
,"ina3221":{"power":1,"0x4":1}
,"i2c":{"address":1,"addresses":1}
,"address":{"0x40":1,"0x42":1,"0x43":1}
,"0x40":{"information":1,"rail":1}
,"sysfs":{"nodes":1,"node":1}
,"naming":{"convention":1}
,"convention":{"sysfs":1}
,"rail_name_<n>":{"exports":1}
,"exports":{"rail":1}
,"in_current":{"<n>_input":1}
,"<n>_input":{"exports":1}
,"in_voltage":{"<n>_input":1}
,"in_power":{"<n>_input":1}
,"<n>":{"channel":1}
,"channel":{"number":1,"vdd_in":1,"vdd_gpu":1,"vdd_c":1,"vdd_mux":1,"vdd_5v_io_sys":1,"vdd_3v3_sys":1,"vdd_3v3_io_slp":1,"vdd_1v8_io":1,"vdd_3v3_sys_m2":1}
,"0-2":{"note":1}
,"ina":{"driver":1,"sysfs":1}
,"modify":{"ina":1}
,"modifying":{"values":1}
,"result":{"damage":1}
,"names":{"voltage":1,"i2c":1}
,"urrent":{"power":1}
,"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F1":{"-0040\u002Fiio:device0":1,"-0042\u002Fiio:device2":1,"-0043\u002Fiio:device3":1,"-004":1}
,"-0040\u002Fiio:device0":{"rail":1}
,"vdd_in":{"main":1,"voltage":1}
,"vdd_gpu":{"gpu":1}
,"developer":{"kit":1}
,"kit":{"carrier":1}
,"carrier":{"board":1}
,"addresses":{"0x42":1}
,"0x42":{"0x43":1,"rail":1}
,"0x43":{"sysfs":1,"rail":1}
,"-0042\u002Fiio:device2":{"\u002Fsys\u002Fbus\u002Fi2c\u002Fdrivers\u002Fina3221x\u002F1":1}
,"-0043\u002Fiio:device3":{"rail":1}
,"vdd_mux":{"carrier":1}
,"vdd_5v_io_sys":{"carrier":1}
,"supply":{"channel":1,"rail":1,"m.2":1}
,"vdd_3v3_sys":{"carrier":1}
,"3.3":{"supply":1,"sleep":1}
,"vdd_3v3_io_slp":{"carrier":1}
,"vdd_1v8_io":{"(name":1}
,"(name":{"schematic":1}
,"schematic":{"vdd_1v":1}
,"vdd_1v":{"carrier":1}
,"1.8":{"supply":1}
,"vdd_3v3_sys_m2":{"3.3":1}
,"m.2":{"key":1}
,"key":{"connector":1}
,"connector":{"examples":1}
,"examples":{"read":1}
,"0x4":{"channel-0":1}
,"channel-0":{"rail":1}
,"vdd_in)":{"execute":1}
,"execute":{"command":1}
,"-004":{"\u002Fiio:device1\u002Frail_name_0":1,"\u002Fiio:device1\u002Fin_current0_input":1,"\u002Fiio:device1\u002Fin_voltage0_input":1,"\u002Fiio:device1\u002Fin_power0_input":1}
,"\u002Fiio:device1\u002Frail_name_0":{"read":1}
,"execut":{"commands":1}
,"commands":{"cat":1}
,"\u002Fiio:device1\u002Fin_current0_input":{"cat":1}
,"\u002Fiio:device1\u002Fin_voltage0_input":{"cat":1}
,"\u002Fiio:device1\u002Fin_power0_input":{"note":1}
,"accuracy":{"assume":1}
,"assume":{"guard":1}
,"guard":{"band":1}
,"band":{"measurements":1}
,"measurements":{"greater":1}
,"greater":{"200":1}
,"200":{"below":1}
,"ccuracy":{"deviate":1}
,"deviate":{"related":1}
,"tools":{"techniques":1}
,"techniques":{"tools":1,"manage":1}
,"isabl":{"ing":1}
,"default":{"disable":1,"file":1}
,"echo":{"\u002Fsys\u002Fdevices\u002F57000000.gpu\u002Fenable_3d_scaling":1,"<cpu_freq>":1,"<gpu_freq>":1,"<emc_freq>":1,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.emc\u002Fclk_state":1,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fonline":1}
,"\u002Fsys\u002Fdevices\u002F57000000.gpu\u002Fenable_3d_scaling":{"able":1,"setting":1}
,"able":{"frequency":1}
,"setting":{"frequencies":1,"file":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Fclk_summary":{"print":1}
,"print":{"cpu":1,"gpu":1,"emc":1}
,"bound":{"upper":1,"current":1,"run":1}
,"upper":{"bound":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_m":{"in_freq":1,"ax_freq":1}
,"in_freq":{"cat":1}
,"ax_freq":{"cat":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fcpuinfo_c":{"ur_freq":1}
,"ur_freq":{"change":1}
,"<cpu_freq>":{"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpu":1,"frequency":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpu":{"freq\u002Fscaling_max":1,"freq\u002Fscaling_m":1,"freq\u002Fscaling_min_freq":1,"freq\u002Fscaling_max_freq":1}
,"freq\u002Fscaling_max":{"_freq":1}
,"_freq":{"change":1,"static":1,"cat":1,"echo":1,"<gpu_freq>":1}
,"freq\u002Fscaling_m":{"_freq":1}
,"freq\u002Fscaling_min_freq":{"echo":1}
,"freq\u002Fscaling_max_freq":{"<cpu_freq>":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fcpufreq\u002Fscaling_avail":{"able_frequencies":1}
,"able_frequencies":{"cpu":1}
,"\u002Fsys\u002Fdevices\u002F57000000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fmin":{"_freq":1}
,"\u002Fsys\u002Fdevices\u002F57000":{"000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fmax":1,"000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fcur":1}
,"000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fmax":{"_freq":1}
,"000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fcur":{"_freq":1}
,"<gpu_freq>":{"\u002Fsys\u002Fdevices\u002F57000":1,"\u002Fsys\u002Fdevices\u002F57000000.gpu\u002Fdevfreq\u002F57000000.gpu\u002Fmin":1,"value":1}
,"\u002Fsys\u002Fdevices\u002F57000000.g":{"pu\u002Fdevfreq\u002F57000000.gpu":1}
,"pu\u002Fdevfreq\u002F57000000.gpu":{"\u002Favailable_frequencies":1}
,"\u002Favailable_frequencies":{"print":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Ftegra_bwmgr\u002Femc_min_rate":{"cat":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Ftegra_bwmgr\u002Femc_max":{"_rate":1}
,"_rate":{"cat":1}
,"\u002Fsys\u002Fk":{"ernel\u002Fdebug\u002Ftegra_bwmgr\u002Femc_rate":1}
,"ernel\u002Fdebug\u002Ftegra_bwmgr\u002Femc_rate":{"static":1}
,"<emc_freq>":{"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.emc\u002Fclk_update_r":1,"frequency":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.emc\u002Fclk_update_r":{"ate":1}
,"ate":{"echo":1}
,"\u002Fsys\u002Fkernel\u002Fdebug\u002Fclk\u002Foverride.emc\u002Fclk_state":{"<emc_freq>":1}
,"emc_min_rate":{"emc_max_rate":1}
,"emc_max_rate":{"maximizing":1}
,"maximizing":{"tegra":1}
,"jetson_clocks.sh":{"script":1}
,"script":{"maximize":1,"show":1,"available":1}
,"maximize":{"jetson-tx1":1,"jetson":1}
,"jetson-tx1":{"performance":1}
,"sett":{"ing":1}
,"max":{"imum":1}
,"imum":{"frequency":1}
,"show":{"current":1}
,"store":{"current":1}
,"clo":{"settings":1}
,"restore":{"clock":1,"previous":1}
,"$home\u002Fjetson_clocks":{".sh":1}
,".sh":{"command":1}
,"usage":{"follows":1}
,"jetson-clocks.sh":{"[options":1}
,"[options":{"options":1}
,"options":{"description":1}
,"--show":{"displays":1,"store":1}
,"displays":{"current":1}
,"--store":{"[file]":1,"maximize":1}
,"[file]":{"stores":1,"restores":1}
,"stores":{"current":1}
,"l4t_dfs.conf":{"--restore":1,"show":1}
,"--restore":{"[file]":1,"using":1}
,"restores":{"saved":1}
,"saved":{"settings":1}
,"sudo":{"${home}\u002Fjetson_clocks.sh":1}
,"${home}\u002Fjetson_clocks.sh":{"--show":1,"--store":1,"restore":1,"--restore":1}
,"previous":{"settings":1}
,"plug":{"manage":1}
,"hotplug":{"follows":1}
,"manually":{"turn":1}
,"turn":{"on\u002Foff":1,"slave":1}
,"on\u002Foff":{"slave":1}
,"slave":{"cpus":1,"cpu":1}
,"cpus":{"run":1}
,"\u002Fsys\u002Fdevices\u002Fsystem\u002Fcpu\u002Fcpux\u002Fonline":{"run":1,"check":1,"cpu":1}
,"check":{"cpu":1}
}
;Search.control.loadWordPairs(pairs);
