var pairs =
{
"tx2":{"\u002Ftx2i":1,"vp9":1}
,"\u002Ftx2i":{"software":1}
,"software":{"features":1,"hardware":1}
,"features":{"nvidia":1,"provide":1,"boot":1,"lanes":1,"message":1,"dynamic":1,"include":1}
,"nvidia":{"tegra":1}
,"tegra":{"linux":1,"x2i":1,"specific":1,"low":1,"tx1":1,"watchdog":1}
,"linux":{"driver":1,"targeted":1,"kernel":1}
,"driver":{"package":1,"suspend\u002Fresume":1,"model":1,"provided":1,"release":1}
,"package":{"supports":1,"bring":1}
,"supports":{"software":1,"egl":1,"following":1}
,"provide":{"users":1}
,"users":{"complete":1}
,"complete":{"package":1}
,"bring":{"linux":1}
,"targeted":{"nvidia":1}
,"x2i":{"devices":1}
,"devices":{"note":1,"ina":1}
,"note":{"heck":1,"media-controller":1,"pcie":1,"gst-inspect-1.0":1}
,"heck":{"release":1}
,"release":{"notes":1,"soc_camera":1,"1.0.66":1,"consult":1,"supports":1}
,"notes":{"constraints":1,"nvtboot-bpmp":1,"aarch64":1,"dsi":1,"physical":1,"i\u002Fo":1,"speed":1,"speeds":1,"tegra":1,"opengl":1,"egl":1,"h.264":1,"i420":1,"gst-nvcamerasrc":1}
,"constraints":{"related":1}
,"related":{"features":1}
,"boot":{"loaders":1,"loader":1,"emmc":1,"downloaded":1,"max-q":1,"atf":1}
,"loaders":{"boot":1}
,"loader":{"feature":1,"version":1}
,"feature":{"notes":1,"tool":1,"ping":1,"power":1,"alarm":1,"system":1,"ucm1":1,"version":1,"details":1}
,"nvtboot-bpmp":{"execution":1}
,"execution":{"cpu":1}
,"cpu":{"bpmp":1,"ccplex":1,"hotplug":1,"load":1}
,"bpmp":{"storage":1}
,"storage":{"location":1,"device":1,"usb":1}
,"location":{"cold":1}
,"cold":{"boot":1}
,"emmc":{"rcm":1,"partition":1,"next":1,"card":1}
,"rcm":{"boot":1}
,"downloaded":{"usb":1}
,"usb":{"recovery":1,"n\u002Fa":1,"3.0":1,"2.0":1,"video":1,"camera":1}
,"recovery":{"port":1}
,"port":{"next":1,"pci-e":1,"cpi-e":1,"spi1":1,"spi2":1,"spi":1,"multiplier":1,"u1\u002Fu2\u002Fu3":1}
,"next":{"stage":1}
,"stage":{"storage":1,"cboot":1,"u-boot":1,"linux":1}
,"cboot":{"storage":1,"execution":1}
,"device":{"support":1,"life":1,"power":1,"mode":1,"port":1,"elpg":1}
,"support":{"emmc":1,"gpt":1,"none":1,"i2c":1,"ext2\u002F3\u002F4":1,"dsi":1,"hot-plug":1,"hdmi":1,"support":1,"driver":1,"edp":1,"multi":1,"normal\u002Fbyte":1,"jtag":1,"host":1,"(l0s":1,"(l1.1":1,"(csi":1,"current":1,"p3310-b00":1,"region":1,"default":1,"sdmmc1":1,"cbs":1,"-usb":1,"connector":1,"remote":1,"xotg":1,"xusb":1,"mass":1,"suspend":1,"nfs":1,"system":1,"shutdown":1,"sc7":1,"cpu":1,"notes":1,"egl":1}
,"partition":{"table":1}
,"table":{"support":1}
,"gpt":{"(with":1}
,"(with":{"protective":1}
,"protective":{"mbr)":1}
,"mbr)":{"filesystem":1,"dos":1}
,"filesystem":{"support":1}
,"none":{"i\u002Fo":1}
,"i\u002Fo":{"bus":1,"interfaces":1,"speeds":1}
,"bus":{"support":1,"clear":1,"speed":1}
,"i2c":{"console":1,"pcie":1,"dma":1}
,"console":{"uart":1}
,"uart":{"cboot":1,"u-boot":1,"feature":1,"controllers":1}
,"ccplex":{"storage":1}
,"u-boot":{"linux":1,"execution":1,"kernel":1}
,"kernel":{"storage":1,"userspace":1,"i\u002Fo":1}
,"card":{"partition":1}
,"dos":{"mbr":1}
,"mbr":{"filesystem":1}
,"ext2\u002F3\u002F4":{"fat":1}
,"fat":{"i\u002Fo":1}
,"pcie":{"toolchain":1,"physical":1,"link":1,"tegra":1,"pcie":1,"connec":1,"spi":1}
,"toolchain":{"feature":1}
,"tool":{"chains":1}
,"chains":{"notes":1}
,"aarch64":{"gcc-4.8":1}
,"gcc-4.8":{"-glibc-2.17":1}
,"-glibc-2.17":{"64-bit":1}
,"64-bit":{"kernel":1}
,"userspace":{"u-boot":1}
,"interfaces":{"interface":1}
,"interface":{"feature":1,"khronos":1,"(egl":1}
,"dsi":{"dsi":1,"display":1,"ganged":1}
,"display":{"support":1,"run":1,"multi":1,"hdmi":1,"compliance":1,"without":1,"outputs":1}
,"ganged":{"mode":1}
,"mode":{"pwm":1,"dual":1,"bus":1,"general":1,"(lp0)":1,"bcm":1,"enable":1,"sdmmc1":1,"1.3.1":1,"xusb":1,"support":1,"dma":1,"fifo":1,"system":1,"color":1,"edge":1}
,"pwm":{"backlight":1,"pwm":1,"operations":1,"registration":1}
,"backlight":{"continuous":1}
,"continuous":{"mode":1}
,"dual":{"display":1,"spi":1}
,"run":{"time":1}
,"time":{"power":1}
,"power":{"management":1,"support":1,"mode":1,"notification":1,"efficiency":1}
,"management":{"hdmi":1,"aspm":1,"sdmmc4":1,"states":1,"s.m.a.r.t":1,"surface\u002Fb":1}
,"hdmi":{"edid":1,"1.4":1,"primary":1,"1.4b":1,"2.0":1}
,"edid":{"support":1}
,"hot-plug":{"detection":1,"(using":1}
,"detection":{"mechanism":1}
,"mechanism":{"support":1}
,"1.4":{"(480p\u002F720p\u002F1080p\u002Frgb":1}
,"(480p\u002F720p\u002F1080p\u002Frgb":{"444":1}
,"444":{"@30hz)":1}
,"@30hz)":{"driver":1}
,"suspend\u002Fresume":{"low":1}
,"low":{"power":1}
,"primary":{"display":1}
,"multi":{"display":1,"master":1}
,"1.4b":{"compliance":1}
,"compliance":{"hdmi":1,"udio":1,"pwm":1}
,"2.0":{"compliance":1,"(4k":1,"support":1,"egl":1,"opengl":1}
,"udio":{"support":1}
,"(4k":{"@60":1}
,"@60":{"hz)":1}
,"hz)":{"edid":1}
,"edp":{"primary":1}
,"operations":{"pwm":1}
,"registration":{"framework":1}
,"framework":{"prod":1}
,"prod":{"setting":1}
,"setting":{"tegra":1}
,"specific":{"controller":1}
,"controller":{"configuration":1,"features":1}
,"configuration":{"clock":1}
,"clock":{"accuracy":1,"calculation":1,"power":1}
,"accuracy":{"calculation":1}
,"calculation":{"clock":1,"i2c":1}
,"dma":{"mode":1,"ngines":1}
,"clear":{"support":1}
,"master":{"support":1}
,"normal\u002Fbyte":{"mode":1}
,"general":{"support":1}
,"jtag":{"jtag":1,"attach":1,"halt\u002Fstep\u002Fgo":1}
,"attach":{"debugging":1}
,"debugging":{"capability":1}
,"capability":{"jtag":1,"pcie":1}
,"halt\u002Fstep\u002Fgo":{"debugging":1}
,"physical":{"port":1}
,"pci-e":{"speed":1}
,"speed":{"gen1\u002Fgen2":1,"mhz":1,"n\u002Fa":1,"mode":1,"gen1":1,"lp_iddq":1,"uart":1}
,"gen1\u002Fgen2":{"lane":1}
,"lane":{"width":1,"muxing":1}
,"width":{"physical":1}
,"cpi-e":{"speed":1,"general":1}
,"host":{"controller":1,"-auto":1,"mode":1,"port":1,"elpg":1}
,"lanes":{"xbar":1,"usb":1}
,"xbar":{"config":1}
,"config":{"(x4_x0_x1":1}
,"(x4_x0_x1":{"x2_x1_x1":1}
,"x2_x1_x1":{"x1_x1_x1)":1}
,"x1_x1_x1)":{"hot-plug":1}
,"(using":{"gpio)":1}
,"gpio)":{"pci":1}
,"pci":{"features":1,"usb":1}
,"message":{"signaled":1}
,"signaled":{"interrupts":1}
,"interrupts":{"pcie":1}
,"link":{"capabilities":1,"power":1}
,"capabilities":{"aspm":1,"advanced":1,"bluetooth":1}
,"aspm":{"support":1}
,"(l0s":{"l1)":1}
,"l1)":{"clock":1}
,"(l1.1":{"l1.2)":1}
,"l1.2)":{"root":1}
,"root":{"control":1}
,"control":{"pme":1,"sdmmc4":1,"debug":1}
,"pme":{"interrupt":1}
,"interrupt":{"enable":1}
,"enable":{"extended":1,"bit":1,"byte":1}
,"extended":{"capabilities":1}
,"advanced":{"error":1}
,"error":{"reporting":1}
,"reporting":{"(aer)":1,"technology":1}
,"(aer)":{"miscellaneous":1}
,"miscellaneous":{"features":1}
,"dynamic":{"voltage":1}
,"voltage":{"frequency":1,"switching":1}
,"frequency":{"(dvfs)":1,"tuning":1,"bit":1}
,"(dvfs)":{"tegra":1}
,"(lp0)":{"runtime":1}
,"runtime":{"substates":1,"time":1}
,"substates":{"rest":1}
,"rest":{"capabilities":1}
,"bluetooth":{"bluetooth":1,"4.0":1}
,"4.0":{"bcm4354":1}
,"bcm4354":{"ble":1,"(bluez":1}
,"ble":{"4.0":1}
,"(bluez":{"limitation)":1}
,"limitation)":{"camera":1}
,"camera":{"support":1,"formats":1}
,"(csi":{"input":1}
,"input":{"support)":1,"formats":1}
,"support)":{"v4l2":1}
,"v4l2":{"media-controller":1}
,"media-controller":{"(v4l2":1,"driver":1}
,"(v4l2":{"api":1}
,"api":{"bypasses":1,"support":1,"registry":1}
,"bypasses":{"isp)":1}
,"isp)":{"csi0":1}
,"csi0":{"csi1":1}
,"csi1":{"csi2":1}
,"csi2":{"csi3":1}
,"csi3":{"csi4":1}
,"csi4":{"csi5":1}
,"csi5":{"note":1}
,"model":{"adopted":1}
,"adopted":{"24.1":1}
,"24.1":{"release":1}
,"soc_camera":{"driver":1}
,"provided":{"deprecated":1}
,"deprecated":{"peripheral":1}
,"peripheral":{"devices":1}
,"ina":{"support":1}
,"current":{"monitoring":1}
,"monitoring":{"cpu\u002Fgpu\u002Fvdd_in":1}
,"cpu\u002Fgpu\u002Fvdd_in":{"platform":1}
,"platform":{"support":1,"window":1,"graphics":1}
,"p3310-b00":{"c03":1}
,"c03":{"multi-region":1}
,"multi-region":{"support":1}
,"region":{"support":1}
,"default":{"(lowest-common-denominator)":1}
,"(lowest-common-denominator)":{"dual-band":1}
,"dual-band":{"2.4":1}
,"2.4":{"ghz\u002F5":1}
,"ghz\u002F5":{"ghz":1}
,"ghz":{"bcm":1}
,"bcm":{"4354":1}
,"4354":{"sta":1,"hostap":1,"p2p":1,"wpa2":1,"note":1}
,"sta":{"mode":1}
,"hostap":{"mode":1}
,"p2p":{"mode":1}
,"wpa2":{"security":1}
,"security":{"bcm":1}
,"tx1":{"path":1}
,"path":{"ahb-dma":1}
,"ahb-dma":{"apb-dma":1,"apb":1}
,"apb-dma":{"engines":1}
,"engines":{"pcie":1,"cannot":1}
,"connec":{"ted":1}
,"ted":{"directly":1}
,"directly":{"mselect":1}
,"mselect":{"ahb-dma":1}
,"apb":{"dma":1,"buses":1,"engines":1}
,"ngines":{"interact":1}
,"interact":{"ips":1}
,"ips":{"connected":1}
,"connected":{"respective":1}
,"respective":{"ahb":1}
,"ahb":{"apb":1}
,"buses":{"consequently":1}
,"consequently":{"ahb":1}
,"cannot":{"used":1}
,"used":{"pcie":1,"uart2":1}
,"spi":{"feature":1,"0\u002F3":1,"spi":1,"miso\u002Fmosi":1,"transfer":1}
,"spi1":{"maximum":1}
,"maximum":{"bus":1}
,"mhz":{"physical":1,"sdmmc4":1,"hot":1}
,"spi2":{"maximum":1}
,"0\u002F3":{"maximum":1}
,"n\u002Fa":{"packed\u002Funpacked":1,"usb1":1}
,"packed\u002Funpacked":{"full":1}
,"full":{"duplex":1}
,"duplex":{"mode":1}
,"bit":{"enable":1,"least":1,"rate\u002Fframe":1}
,"byte":{"bi-directional":1,"first":1}
,"bi-directional":{"least":1}
,"least":{"significant":1}
,"significant":{"bit":1,"byte":1}
,"first":{"software":1}
,"hardware":{"chip":1,"flow":1}
,"chip":{"select":1}
,"select":{"polarity":1}
,"polarity":{"section":1}
,"section":{"supported":1}
,"supported":{"modes":1,"features":1}
,"modes":{"1\u002F2\u002F3\u002F4":1}
,"1\u002F2\u002F3\u002F4":{"dual":1}
,"miso\u002Fmosi":{"act":1}
,"act":{"multiple":1}
,"multiple":{"transfer":1,"spi":1}
,"transfer":{"request":1}
,"request":{"multiple":1,"single":1}
,"single":{"call":1}
,"call":{"sdmmc":1}
,"sdmmc":{"feature":1}
,"speeds":{"(clock":1,"usb0":1}
,"(clock":{"speed)":1}
,"speed)":{"sdmmc1":1}
,"sdmmc1":{"(sd":1}
,"(sd":{"card)":1}
,"card)":{"204":1,"high":1,"sdr50":1,"sdmmc4":1,"hs400":1,"frequency":1}
,"204":{"mhz":1}
,"sdmmc4":{"(emmc)":1}
,"(emmc)":{"200":1,"sdr104":1,"hs200":1,"ddr":1,"voltage":1,"packed":1,"cache":1,"discard":1,"sanitize":1,"rpmb":1,"hpi":1,"bkops":1,"power":1,"sleep":1,"field":1,"device":1,"pre":1,"sata":1}
,"200":{"mhz":1}
,"hot":{"plug":1}
,"plug":{"support":1}
,"high":{"speed":1}
,"sdr50":{"sdmmc1":1}
,"sdr104":{"sdmmc1":1}
,"hs400":{"sdmmc4":1}
,"hs200":{"sdmmc4":1}
,"ddr":{"mode":1}
,"switching":{"sdmmc1":1}
,"tuning":{"sdmmc1":1}
,"packed":{"commands":1}
,"commands":{"sdmmc4":1}
,"cache":{"control":1}
,"discard":{"sdmmc4":1}
,"sanitize":{"sdmmc4":1}
,"rpmb":{"sdmmc4":1}
,"hpi":{"sdmmc4":1}
,"bkops":{"sdmmc4":1}
,"notification":{"sdmmc4":1}
,"sleep":{"sdmmc4":1,"support":1,"cpuidle":1}
,"field":{"firmware":1}
,"firmware":{"upgrade":1}
,"upgrade":{"sdmmc4":1}
,"life":{"estimation":1}
,"estimation":{"type":1}
,"type":{"sdmmc4":1,"usb":1}
,"pre":{"eol":1}
,"eol":{"information":1}
,"information":{"sdmmc4":1,"opengl":1}
,"sata":{"feature":1,"specification":1}
,"gen1":{"gen2":1}
,"gen2":{"ahci":1}
,"ahci":{"mode":1}
,"1.3.1":{"sata":1}
,"specification":{"3.1":1,"khronos":1,"2.0":1}
,"3.1":{"hipm":1}
,"hipm":{"ncq":1}
,"ncq":{"port":1}
,"multiplier":{"support":1}
,"cbs":{"link":1}
,"states":{"partial":1,"runtime":1}
,"partial":{"slumber":1}
,"slumber":{"device":1}
,"s.m.a.r.t":{"self-monitoring":1}
,"self-monitoring":{"analysis":1}
,"analysis":{"reporting":1}
,"technology":{"dev":1}
,"dev":{"sleep":1}
,"-usb":{"3.0":1}
,"3.0":{"feature":1,"support":1}
,"usb0":{"hs\u002F480":1,"micro":1}
,"hs\u002F480":{"mbps":1}
,"mbps":{"usb1":1,"full-frame":1,"decode":1,"supported":1}
,"usb1":{"ss\u002F5":1,"lane":1,"type":1}
,"ss\u002F5":{"gps":1}
,"gps":{"lanes":1}
,"muxing":{"sharing":1}
,"sharing":{"pci":1}
,"connector":{"usb0":1}
,"micro":{"usb1":1}
,"remote":{"wakeup":1}
,"wakeup":{"support":1,"sc7":1}
,"-auto":{"suspend":1}
,"suspend":{"support":1,"resume":1}
,"xotg":{"support":1}
,"xusb":{"ss\u002Fhs\u002Ffs\u002Fls":1,"device":1,"host":1}
,"ss\u002Fhs\u002Ffs\u002Fls":{"host":1,"device":1}
,"u1\u002Fu2\u002Fu3":{"transition":1}
,"transition":{"xusb":1}
,"elpg":{"xusb":1,"class":1}
,"class":{"support":1,"hid":1,"mtp":1}
,"mass":{"storage":1}
,"video":{"class":1,"decoders":1,"decode":1,"encoders":1,"encode":1}
,"hid":{"usb":1}
,"mtp":{"ethernet":1}
,"ethernet":{"thumb\u002Fhard":1}
,"thumb\u002Fhard":{"drive":1}
,"drive":{"mouse":1}
,"mouse":{"cdc":1}
,"cdc":{"-ncm\u002Fecm":1}
,"-ncm\u002Fecm":{"eqos":1}
,"eqos":{"feature":1}
,"ping":{"speed":1}
,"lp_iddq":{"mode":1}
,"resume":{"nfs":1}
,"nfs":{"support":1,"boot":1}
,"max-q":{"max-p":1}
,"max-p":{"feature":1}
,"efficiency":{"nvpmodel":1}
,"nvpmodel":{"rtc":1}
,"rtc":{"feature":1}
,"alarm":{"wakeup":1}
,"sc7":{"watchdog":1,"wake":1}
,"watchdog":{"feature":1,"watchdog":1,"reboot":1,"kick":1}
,"reboot":{"hang":1,"support":1}
,"hang":{"tegra":1,"pmic":1}
,"kick":{"pmic":1,"gpio":1}
,"pmic":{"watchdog":1}
,"gpio":{"feature":1,"support":1,"timestamping":1,"uart":1}
,"system":{"programable":1,"feature":1,"boot":1,"handles":1}
,"programable":{"gpio":1,"pinmux":1}
,"pinmux":{"supportwakeable":1}
,"supportwakeable":{"gpio":1}
,"timestamping":{"gpio":1}
,"controllers":{"uart0":1}
,"uart0":{"(debug":1}
,"(debug":{"115200":1}
,"115200":{"uart1":1}
,"uart1":{"(camera\u002Fgpio":1}
,"(camera\u002Fgpio":{"expansion":1}
,"expansion":{"header)":1}
,"header)":{"used":1}
,"uart2":{"(m2":1}
,"(m2":{"connector)":1}
,"connector)":{"921600":1}
,"921600":{"uart3":1}
,"uart3":{"(bluetooth":1}
,"(bluetooth":{"only)":1}
,"only)":{"3000000":1}
,"3000000":{"hardware":1}
,"flow":{"control":1}
,"debug":{"pio":1}
,"pio":{"mode":1}
,"fifo":{"mode":1}
,"ucm1":{"4\u002F4\u002F16":1}
,"4\u002F4\u002F16":{"ucm2":1}
,"ucm2":{"24x7":1}
,"24x7":{"reboot":1}
,"shutdown":{"support":1}
,"wake":{"idle":1,"sleep":1}
,"idle":{"wake":1}
,"cpuidle":{"cpufreq":1}
,"cpufreq":{"dvfs":1}
,"dvfs":{"cpu":1}
,"hotplug":{"emc":1}
,"emc":{"scaling":1}
,"scaling":{"initrd":1,"rotation":1}
,"initrd":{"support":1}
,"load":{"behavior":1}
,"behavior":{"system":1}
,"atf":{"secure":1}
,"secure":{"monitor":1}
,"monitor":{"cuda":1}
,"cuda":{"feature":1,"version":1}
,"version":{"cuda":1,"9.0.252":1,"egl":1,"release":1}
,"9.0.252":{"graphics":1}
,"graphics":{"graphics":1,"apis":1,"context":1,"interface":1}
,"apis":{"notes":1,"opengl":1,"l4t":1}
,"opengl":{"4.5":1,"-es":1,"support":1,"underlying":1,"driver":1,"specifications":1,"common":1,"information":1,"khronos":1,"api":1}
,"4.5":{"opengl":1}
,"-es":{"vulkan":1}
,"vulkan":{"1.0":1,"loader":1}
,"1.0":{"egl":1}
,"egl":{"glx":1,"vendor":1,"stream":1,"egl":1,"without":1,"opengl":1,"interface":1,"enables":1,"specification":1,"producer":1}
,"glx":{"glvnd":1}
,"glvnd":{"version":1}
,"vendor":{"neutral":1}
,"neutral":{"functionality":1}
,"functionality":{"nvdc":1}
,"nvdc":{"-direct":1}
,"-direct":{"rendering":1}
,"rendering":{"manager":1,"apis":1,"synchronization":1,"using":1}
,"manager":{"(drm)":1}
,"(drm)":{"compatibility":1}
,"compatibility":{"drm":1}
,"drm":{"2.0":1}
,"stream":{"x11":1}
,"x11":{"abi-20":1,"content":1,"usage":1,"window":1}
,"abi-20":{"legacy":1}
,"legacy":{"24.2":1}
,"24.2":{"using":1}
,"using":{"ubuntu":1,"khronos":1}
,"ubuntu":{"16.04":1}
,"16.04":{"api":1}
,"without":{"x11":1}
,"content":{"display":1}
,"usage":{"vulkan":1}
,"1.0.66":{"verified":1}
,"verified":{"working":1}
,"working":{"properly":1}
,"properly":{"release":1}
,"consult":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fvulkan":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fvulkan":{"details":1}
,"details":{"egl":1,"example":1,"h.264":1}
,"khronos":{"rendering":1,"apis":1,"native":1,"opengl":1}
,"underlying":{"native":1}
,"native":{"platform":1}
,"window":{"system":1,"panel":1}
,"handles":{"graphics":1}
,"context":{"management":1}
,"surface\u002Fb":{"uffer":1}
,"uffer":{"binding":1}
,"binding":{"rendering":1}
,"synchronization":{"egl":1}
,"enables":{"high-performance":1}
,"high-performance":{"accelerated":1}
,"accelerated":{"mixed-mode":1}
,"mixed-mode":{"rendering":1}
,"l4t":{"supports":1}
,"(egl":{"specification)":1}
,"specification)":{"opengl":1}
,"following":{"opengl":1}
,"specifications":{"opengl":1}
,"common":{"profile":1}
,"profile":{"specification":1,"insert-aud":1}
,"registry":{"video":1}
,"decoders":{"video":1}
,"decode":{"output":1,"upport":1}
,"output":{"formats":1,"format":1}
,"formats":{"sampling":1,"input":1,"output":1,"notes":1}
,"sampling":{"frequency":1}
,"rate\u002Fframe":{"rate":1}
,"rate":{"notes":1}
,"h.264":{"nv12":1,"i420":1,"enc":1}
,"nv12":{"nvmm:nv12":1,"nvmm:1420":1,"nvmm:i420":1,"nv12":1,"flip-method":1,"whitebalance":1}
,"nvmm:nv12":{"3840":1,"nvmm:i420_10le":1,"nvmm:nv12":1,"flip-method":1}
,"3840":{"2160":1}
,"2160":{"fps":1}
,"fps":{"120":1,"160":1,"mbps":1,"100":1}
,"120":{"mbps":1}
,"full-frame":{"disable-dpb":1}
,"disable-dpb":{"skip-frames":1}
,"skip-frames":{"enable-error-check":1}
,"enable-error-check":{"enable-frame-type-reporting":1}
,"enable-frame-type-reporting":{"h.265":1,"jpeg":1,"vp9":1,"video":1}
,"h.265":{"nv12":1}
,"nvmm:i420_10le":{"3840":1,"nvmm:i420_10le":1,"nvmm:nv12":1}
,"160":{"mbps":1}
,"upport":{"gstreamer":1}
,"gstreamer":{"1.4.5":1}
,"1.4.5":{"later":1}
,"later":{"full-frame":1}
,"jpeg":{"i420":1}
,"i420":{"nvmm:i420":1,"nv12":1,"i420":1,"flip-method":1}
,"nvmm:i420":{"600":1,"nvmm:nv12":1,"nvmm:i420":1,"flip-method":1}
,"600":{"mp\u002Fsec":1}
,"mp\u002Fsec":{"-vp8":1,"-h.265":1}
,"-vp8":{"nv12":1}
,"vp9":{"nv12":1,"i420":1}
,"encoders":{"video":1}
,"encode":{"input":1}
,"nvmm:1420":{"nvmm:nv12":1}
,"include":{"control-rate":1}
,"control-rate":{"bitrate":1}
,"bitrate":{"peak-bitrate":1}
,"peak-bitrate":{"iframeinterval":1}
,"iframeinterval":{"sliceintrarefreshenable":1}
,"sliceintrarefreshenable":{"sliceintrarefreshinterval":1}
,"sliceintrarefreshinterval":{"bit-packetization":1}
,"bit-packetization":{"vbv-size":1}
,"vbv-size":{"temporal-tradeoff":1}
,"temporal-tradeoff":{"enablemvbuffermeta":1}
,"enablemvbuffermeta":{"qp-range":1}
,"qp-range":{"measureencoderlatency":1}
,"measureencoderlatency":{"enabletwopasscbr":1}
,"enabletwopasscbr":{"preset-level":1}
,"preset-level":{"enablestrimgentbitrate":1}
,"enablestrimgentbitrate":{"insert-sps-pps":1}
,"insert-sps-pps":{"num-b-frames":1}
,"num-b-frames":{"slice-header-spacing":1}
,"slice-header-spacing":{"profile":1}
,"insert-aud":{"insert-vui":1}
,"insert-vui":{"force-idr":1}
,"force-idr":{"jpeg":1,"vp8":1,"applies":1,"note":1}
,"-h.265":{"i420":1}
,"100":{"mbps":1}
,"vp8":{"i420":1}
,"applies":{"tx2":1}
,"gst-inspect-1.0":{"utility":1,"omxh264enc":1}
,"utility":{"understand":1}
,"understand":{"feat":1}
,"feat":{"ure":1}
,"ure":{"details":1}
,"example":{"gst-inspect-1.0":1}
,"omxh264enc":{"command":1}
,"command":{"provides":1}
,"provides":{"feature":1}
,"enc":{"oder":1}
,"oder":{"display":1}
,"outputs":{"nveglglessink":1}
,"nveglglessink":{"nvoverlaysink":1}
,"nvoverlaysink":{"x11":1}
,"panel":{"overlay":1}
,"overlay":{"-overlay":1}
,"-overlay":{"-overlay-depth":1}
,"-overlay-depth":{"-overlay-x":1}
,"-overlay-x":{"-overlay-y":1}
,"-overlay-y":{"-overlay-w":1}
,"-overlay-w":{"-overlay-h":1}
,"-overlay-h":{"conversion":1}
,"conversion":{"scaling":1,"uyvy":1,"yuy2":1}
,"rotation":{"formats":1}
,"flip-method":{"interpolation-method":1}
,"interpolation-method":{"crop":1}
,"crop":{"format":1}
,"format":{"conversion":1,"nversion":1,"options":1}
,"uyvy":{"uyvy":1,"flip-method":1}
,"yuy2":{"yuy2":1,"flip-method":1}
,"nversion":{"yvyu":1,"nv12":1,"gray8":1,"bgrx":1,"rgba":1,"nvmm:i420":1,"nvmm:i420_10le":1,"csi":1}
,"yvyu":{"yvyu":1,"flip-method":1}
,"gray8":{"gray8":1,"flip-method":1}
,"bgrx":{"bgrx":1,"flip-method":1}
,"rgba":{"rgba":1,"flip-method":1}
,"csi":{"usb":1}
,"options":{"notes":1}
,"gst-nvcamerasrc":{"nvmm":1}
,"nvmm":{"i420":1}
,"whitebalance":{"mode":1}
,"color":{"effect":1}
,"effect":{"auto-exposure":1}
,"auto-exposure":{"flicker":1}
,"flicker":{"contrast":1}
,"contrast":{"saturation":1}
,"saturation":{"tnr":1}
,"tnr":{"strength":1,"mode":1}
,"strength":{"tnr":1}
,"edge":{"enhancement":1}
,"enhancement":{"intent":1}
,"intent":{"still\u002Fvideo\u002Fvideo":1}
,"still\u002Fvideo\u002Fvideo":{"snapshot\u002Fpreview":1}
,"snapshot\u002Fpreview":{"sensor-id":1}
,"sensor-id":{"aeregion":1}
,"aeregion":{"wbregion":1}
,"wbregion":{"fpsrange":1}
,"fpsrange":{"exposure-time":1}
,"exposure-time":{"wbmanualmode":1}
,"wbmanualmode":{"wbgains":1}
,"wbgains":{"sensor":1}
,"sensor":{"orientation":1}
,"orientation":{"embedded":1}
,"embedded":{"metadata":1}
,"metadata":{"egl":1}
,"producer":{"simultaneous":1}
,"simultaneous":{"multi-camera":1}
}
;Search.control.loadWordPairs(pairs);
