var pairs =
{
"building":{"aarch":1,"toolchain":1,"script":1,"gcc":1,"glibc":1,"final":1}
,"aarch":{"toolchain":1}
,"toolchain":{"glibc":1,"information":1,"built":1,"binaries":1,"contains":1,"download":1,"available":1,"start":1,"toolchain":1,"build":1,"bui":1,"obtain":1,"scripts":1,"source":1,"make-aarch64-toolchain.sh":1,"patches":1,"building":1,"sources":1,"components":1}
,"glibc":{"nvidia":1,"version":1,"stage":1,"build_final_glibc.log":1}
,"nvidia":{"tegra":1,"uses":1,"developer":1}
,"tegra":{"linux":1}
,"linux":{"driver":1,"headers":1}
,"driver":{"package":1}
,"package":{"contains":1,"build":1,"described":1}
,"contains":{"script":1,"following":1}
,"script":{"patches":1,"builds":1,"build":1,"downloads":1,"troubleshooting":1,"prints":1}
,"patches":{"used":1,"provided":1,"folder":1,"toolcha":1,"apply_patches.log":1}
,"used":{"create":1}
,"create":{"oolchains":1}
,"oolchains":{"nvidia":1}
,"uses":{"produce":1}
,"produce":{"aarch64":1}
,"aarch64":{"l4t":1,"toolchain":1}
,"l4t":{"binaries":1}
,"binaries":{"topic":1,"statically":1,"embedded":1}
,"topic":{"describes":1}
,"describes":{"obtain":1}
,"obtain":{"build":1,"toolchain":1}
,"build":{"toolchains":1,"script":1,"toolchain":1,"products":1,"process":1,"binutils":1,"cceeds":1,"errors":1}
,"toolchains":{"toolchain":1}
,"information":{"aarch64":1}
,"built":{"aarch64-unknown-linux-gnu":1,"toolchain":1}
,"aarch64-unknown-linux-gnu":{"toolchain":1}
,"statically":{"built":1}
,"following":{"components":1,"required":1,"two":1,"commands":1}
,"components":{"gcc":1,"well-known":1,"provided":1}
,"gcc":{"version":1,"stage":1}
,"version":{"4.8":1,"2.17":1}
,"4.8":{"glibc":1}
,"2.17":{"downloading":1}
,"downloading":{"pre-built":1,"pre-b":1,"sources":1}
,"pre-built":{"toolchain":1}
,"download":{"pre-built":1,"center":1}
,"embedded":{"download":1}
,"center":{"nvidia":1}
,"developer":{"page":1}
,"page":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"aarch64":1}
,"available":{"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdlc\u002Fl4t-gcc-t":1}
,"http:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdlc\u002Fl4t-gcc-t":{"oolchain-64-bit-28-1":1}
,"oolchain-64-bit-28-1":{"copy":1}
,"copy":{"contents":1}
,"contents":{"tarball":1}
,"tarball":{"location":1,"contains":1,"sers":1,"users":1}
,"location":{"toolchain":1}
,"start":{"using":1}
,"using":{"building":1,"ubuntu":1}
,"provided":{"jetson":1,"tarball":1,"sepa":1}
,"jetson":{"toolchain":1}
,"bui":{"package":1}
,"scripts":{"package":1}
,"described":{"downloading":1}
,"pre-b":{"uilt":1}
,"uilt":{"toolchain":1}
,"source":{"tar":1,"tarball":1}
,"tar":{"file":1}
,"file":{"named":1,"downloading":1,"last":1}
,"named":{"src_aarch64_gcc-4.8.5.tar":1,"stage":1}
,"src_aarch64_gcc-4.8.5.tar":{"toolchain":1}
,"required":{"sources":1}
,"sources":{"build":1,"run":1,"require":1,"lso":1,"get_src.log":1,"toolcha":1}
,"make-aarch64-toolchain.sh":{"script":1}
,"builds":{"toolchain":1}
,"folder":{"containing":1}
,"containing":{"patches":1}
,"toolcha":{"sources":1,"components":1}
,"run":{"toolchain":1}
,"products":{"located":1}
,"located":{"install":1}
,"install":{"directory":1,"necessary":1,"gawk":1,"texinfo":1,"automake":1,"libtool":1,"build":1}
,"directory":{"get_src":1}
,"get_src":{"function":1}
,"function":{"make-aarch64-toolchain.sh":1,"up-to-date":1}
,"downloads":{"relevant":1,"sources":1}
,"relevant":{"sources":1}
,"require":{"building":1}
,"lso":{"provided":1}
,"sers":{"comment":1}
,"comment":{"get_src":1}
,"troubleshooting":{"step":1}
,"step":{"build":1,"log":1,"shown":1}
,"process":{"logs":1,"step":1}
,"logs":{"progress":1}
,"progress":{"errors":1}
,"errors":{"file":1,"using":1}
,"stage":{"build":1,"build_gcc_stage1.log":1,"build_glibc_stage1.log":1}
,"log":{"file":1}
,"get_src.log":{"applying":1}
,"applying":{"patches":1}
,"apply_patches.log":{"build":1}
,"binutils":{"build_binutils.log":1}
,"build_binutils.log":{"installing":1}
,"installing":{"linux":1}
,"headers":{"install_linux_headers.log":1}
,"install_linux_headers.log":{"building":1}
,"build_gcc_stage1.log":{"building":1}
,"build_glibc_stage1.log":{"building":1}
,"final":{"glibc":1}
,"build_final_glibc.log":{"build":1}
,"cceeds":{"script":1}
,"prints":{"success":1}
,"success":{"end":1}
,"end":{"otherwise":1}
,"otherwise":{"check":1}
,"check":{"log":1}
,"last":{"step":1}
,"shown":{"find":1}
,"find":{"error":1}
,"error":{"following":1}
,"two":{"common":1}
,"common":{"build":1}
,"ubuntu":{"14.04":1}
,"14.04":{"install":1}
,"necessary":{"packages":1}
,"packages":{"addition":1}
,"addition":{"ones":1}
,"ones":{"mentioned":1}
,"mentioned":{"readme":1}
,"readme":{"following":1}
,"commands":{"$sudo":1}
,"$sudo":{"apt-get":1}
,"apt-get":{"install":1}
,"gawk":{"$sudo":1}
,"texinfo":{"$sudo":1}
,"automake":{"$sudo":1}
,"libtool":{"$sudo":1}
,"well-known":{"locations":1}
,"locations":{"url":1}
,"url":{"may":1}
,"may":{"become":1}
,"become":{"outdated":1}
,"outdated":{"time":1}
,"time":{"verify":1}
,"verify":{"urls":1}
,"urls":{"get_src":1}
,"up-to-date":{"toolchain":1}
,"sepa":{"rate":1}
,"rate":{"tarball":1}
,"users":{"directly":1}
}
;Search.control.loadWordPairs(pairs);
