var pairs =
{
"setting":{"file":1,"root":1,"ldk_rootfs_dir":1}
,"file":{"system":1,"ystem":1,"home":1,"contains":1,"follows":1}
,"system":{"l4t":1,"create":1,"copy":1,"created":1,"provided":1,"sel":1,"booting":1,"(rootfs)":1,"procedure":1,"ldk_rootfs_dir":1,"rootfs":1,"extract":1,"$cd":1,"apply_binaries.sh":1,"tegra":1,"external":1,"device":1,"$sudo":1,"otfs":1}
,"l4t":{"requires":1,"comes":1,"root":1}
,"requires":{"root":1}
,"root":{"file":1,"system":1,"directory":1,"filesys":1,"filesystem":1}
,"create":{"linux":1,"ubuntu":1}
,"linux":{"host":1}
,"host":{"system":1}
,"copy":{"reference":1,"rootfs":1,"nvidia":1,"bina":1,"file":1}
,"reference":{"oard":1}
,"oard":{"sample":1}
,"sample":{"root":1,"file":1}
,"comes":{"pre-built":1}
,"pre-built":{"sample":1}
,"created":{"jetson":1}
,"jetson":{"tx1":1}
,"tx1":{"tx2":1}
,"tx2":{"developer":1}
,"developer":{"kit":1}
,"kit":{"wish":1}
,"wish":{"create":1,"file":1}
,"ubuntu":{"sample":1}
,"ystem":{"https:\u002F\u002Fwiki.ubuntu.com\u002Farm\u002Frootfsfromscratch":1}
,"https:\u002F\u002Fwiki.ubuntu.com\u002Farm\u002Frootfsfromscratch":{"disclaimer":1}
,"disclaimer":{"sample":1}
,"provided":{"conve":1,"nvidia":1}
,"conve":{"nience":1}
,"nience":{"nvidia":1}
,"nvidia":{"disclaims":1,"base":1,"driver":1,"user":1}
,"disclaims":{"obligations":1}
,"obligations":{"provid":1}
,"provid":{"support":1}
,"support":{"including":1,"setting":1}
,"including":{"bug":1}
,"bug":{"fixes":1}
,"fixes":{"security":1}
,"security":{"update":1}
,"update":{"provides":1}
,"provides":{"warranty":1}
,"warranty":{"software":1}
,"software":{"customers":1}
,"customers":{"responsible":1}
,"responsible":{"root":1}
,"sel":{"ection":1}
,"ection":{"support":1}
,"booting":{"target":1}
,"target":{"board":1,"file":1,"egra":1,"device":1}
,"board":{"configure":1}
,"configure":{"roo":1}
,"roo":{"file":1}
,"(rootfs)":{"rootfs":1}
,"rootfs":{"copy":1,"device":1,"skip":1,"download":1,"directory":1,"direc":1,"hav":1,"apply":1,"run":1,"onto":1,"using":1}
,"device":{"step":1,"procedures":1,"pick":1,"place":1,"prefer":1,"root":1,"host":1,"formatted":1,"mounted":1,"number":1,"attached":1,"following":1,"copy":1,"unmount":1,"proceed":1}
,"step":{"root":1,"copy":1}
,"procedure":{"sample":1,"copy":1}
,"base":{"wish":1}
,"ldk_rootfs_dir":{"environment":1,"execute":1}
,"environment":{"variable":1}
,"variable":{"point":1}
,"point":{"location":1,"rootfs":1,"host":1}
,"location":{"rootfs":1}
,"skip":{"steps":1,"ahead":1}
,"steps":{"setting":1}
,"download":{"following":1}
,"following":{"file":1,"procedure":1,"command":1,"mmand":1}
,"home":{"directory":1}
,"directory":{"tegra-linux-sampl":1,"extracted":1,"assumed":1,"extract":1,"included":1}
,"tegra-linux-sampl":{"e-root-filesystem_<release_type":1}
,"e-root-filesystem_<release_type":{".tbz2":1}
,".tbz2":{"file":1,"run":1}
,"contains":{"nvidia-provided":1}
,"nvidia-provided":{"sample":1}
,"extract":{"compressed":1,"sample":1}
,"compressed":{"file":1}
,"follows":{"navigate":1}
,"navigate":{"rootfs":1}
,"extracted":{"nvidia":1}
,"driver":{"package":1}
,"package":{"$cd":1}
,"$cd":{"<your_l4t_root>\u002Flinux_for_tegra\u002Frootfs":1,"$sudo":1,"${ldk_rootfs_dir}":1}
,"<your_l4t_root>\u002Flinux_for_tegra\u002Frootfs":{"<your_l4t_root":1,"$sudo":1}
,"<your_l4t_root":{"l4t":1}
,"assumed":{"home":1}
,"direc":{"tory":1}
,"tory":{"$sudo":1}
,"$sudo":{"tar":1,".\u002Fapply_binaries.sh":1,"mkfs.ext4":1,"mount":1,"*<mntpoint>":1}
,"tar":{"-jxpf":1,"tegra":1}
,"-jxpf":{".\u002Ftegra-linux-sample-root-fil":1}
,".\u002Ftegra-linux-sample-root-fil":{"esystem_<release_type":1}
,"esystem_<release_type":{".tbz2":1}
,"run":{"apply_binaries.sh":1,"script":1}
,"apply_binaries.sh":{"script":1}
,"script":{"copy":1,"shown":1,"installs":1,"success":1}
,"user":{"space":1}
,"space":{"libraries":1}
,"libraries":{"target":1,"setting":1}
,".\u002Fapply_binaries.sh":{"using":1}
,"using":{"different":1,"internal":1}
,"different":{"rootfs":1}
,"hav":{"already":1}
,"already":{"configured":1}
,"configured":{"rootfs":1}
,"apply":{"nvidia":1}
,"shown":{"above":1}
,"above":{"copy":1}
,"bina":{"ries":1}
,"ries":{"target":1}
,"installs":{"binaries":1}
,"binaries":{"correctly":1}
,"correctly":{"last":1}
,"last":{"message":1}
,"message":{"output":1}
,"output":{"script":1}
,"success":{"completed":1}
,"completed":{"setting":1}
,"filesys":{"tem":1}
,"tem":{"proceed":1}
,"proceed":{"flash":1,"flashing":1}
,"flash":{"rootfs":1}
,"onto":{"target":1}
,"egra":{"device":1}
,"procedures":{"copy":1}
,"tegra":{"device":1}
,"pick":{"device":1}
,"place":{"rootfs":1}
,"internal":{"emmc":1}
,"emmc":{"skip":1}
,"ahead":{"flashing":1}
,"flashing":{"booting":1}
,"prefer":{"external":1}
,"external":{"storage":1,"disk":1}
,"storage":{"device":1,"dev":1}
,"filesystem":{"following":1}
,"dev":{"ice":1}
,"ice":{"plug":1}
,"plug":{"rootfs":1}
,"formatted":{"ext4":1}
,"ext4":{"enter":1,"file":1}
,"enter":{"following":1}
,"command":{"format":1,"determine":1}
,"format":{"ext4":1}
,"mkfs.ext4":{"\u002Fdev\u002Fsd":1}
,"\u002Fdev\u002Fsd":{"<port>":1}
,"<port>":{"<device_number>":1,"port":1}
,"<device_number>":{"<port>":1,"device":1}
,"port":{"device":1,"dmesg":1,"needed":1}
,"mounted":{"<device_number>":1}
,"number":{"device":1}
,"attached":{"port":1}
,"dmesg":{"command":1}
,"determine":{"port":1}
,"needed":{"mount":1}
,"mount":{"device":1,"\u002Fdev\u002Fsdx1":1,"point":1}
,"mmand":{"$sudo":1}
,"\u002Fdev\u002Fsdx1":{"<mntpoint>":1}
,"<mntpoint>":{"<mntpoint>":1,"mount":1}
,"otfs":{"device":1}
,"execute":{"commands":1}
,"commands":{"$cd":1}
,"${ldk_rootfs_dir}":{"$sudo":1}
,"*<mntpoint>":{"&&sync":1}
,"&&sync":{"copy":1,"copying":1}
,"included":{"release":1}
,"release":{"executing":1}
,"executing":{"followi":1}
,"followi":{"commands":1}
,"copying":{"content":1}
,"content":{"external":1}
,"disk":{"device":1,"connect":1}
,"unmount":{"disk":1}
,"connect":{"tar":1}
}
;Search.control.loadWordPairs(pairs);
