var pairs =
{
"kernel":{"boot":1,"development":1,"includes":1,"reduce":1,"respect":1,"image":1,"version":1,"driver":1,"hack":1}
,"boot":{"time":1,"scrip":1,"configurations":1,"asynchronously":1,"hid":1}
,"time":{"optimization":1,"customize":1,"initialize":1,"scanning":1,"thereby":1,"storage":1,"configure":1,"enable":1,"disable":1,"modifying":1,"reduce":1,"remove":1,"u-boot":1,"filesystem":1,"modularize":1}
,"optimization":{"nvidia":1,"techniques":1}
,"nvidia":{"tegra":1,"tegra-rtc":1}
,"tegra":{"linux":1,"system":1,"soc":1,"rtc":1}
,"linux":{"driver":1}
,"driver":{"package":1,"thread":1,"follows":1,"reduce":1}
,"package":{"(l4t)":1}
,"(l4t)":{"provides":1}
,"provides":{"generic":1}
,"generic":{"boo":1}
,"boo":{"kernel":1}
,"development":{"product":1}
,"product":{"decre":1,"kernel":1}
,"decre":{"ase":1}
,"ase":{"kernel":1}
,"customize":{"provided":1}
,"provided":{"kerne":1}
,"kerne":{"based":1}
,"based":{"requirements":1,"developme":1}
,"requirements":{"product":1}
,"includes":{"default":1}
,"default":{"configuration":1,"tegra":1,"kernel":1}
,"configuration":{"enables":1,"takes":1,"tegra21_defconfig":1,"optimize":1,"root":1,"file":1,"reduce":1,"xamine":1,"example":1}
,"enables":{"supported":1,"out-of-the":1}
,"supported":{"hardware":1}
,"hardware":{"features":1,"support":1}
,"features":{"searches":1,"storage":1,"mostly":1}
,"searches":{"available":1}
,"available":{"devices":1,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002F<top>\u002Fhardware":1,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fquill\u002Fkernel-d":1,"following":1,"default":1}
,"devices":{"boot":1,"takes":1,"need":1}
,"scrip":{"enables":1}
,"out-of-the":{"box":1}
,"box":{"support":1}
,"support":{"dest":1,"takes":1}
,"dest":{"possible":1}
,"possible":{"variety":1}
,"variety":{"controllers":1}
,"controllers":{"features":1}
,"storage":{"devices":1,"network":1,"device":1}
,"configurations":{"flexibility":1,"required":1,"defined":1,"drivers":1,"verify":1,"modules":1,"follows":1}
,"flexibility":{"comes":1}
,"comes":{"cost":1}
,"cost":{"hardware":1}
,"takes":{"time":1,"second":1}
,"initialize":{"enabling":1,"liminate":1}
,"enabling":{"software":1}
,"software":{"features":1}
,"mostly":{"advanc":1}
,"advanc":{"peripheral":1}
,"peripheral":{"bus":1}
,"bus":{"(apb)":1}
,"(apb)":{"takes":1}
,"scanning":{"attached":1}
,"attached":{"storage":1}
,"network":{"devices":1}
,"thereby":{"delaying":1}
,"delaying":{"execution":1}
,"execution":{"final":1}
,"final":{"operating":1}
,"operating":{"system":1}
,"system":{"constrained":1,"designer":1,"boot":1,"running":1,"turned":1,"concerned":1,"disable":1,"ready":1,"decrease":1}
,"constrained":{"pre-configured":1}
,"pre-configured":{"systems":1}
,"systems":{"fle":1}
,"fle":{"xibility":1}
,"xibility":{"may":1}
,"may":{"necessary":1,"know":1}
,"necessary":{"system":1}
,"designer":{"may":1}
,"know":{"ahead":1}
,"ahead":{"time":1}
,"device":{"conta":1,"tree":1,"ree":1}
,"conta":{"ins":1}
,"ins":{"required":1}
,"required":{"files":1,"flashing":1,"once":1,"configurations":1,"during":1}
,"files":{"certain":1}
,"certain":{"devices":1}
,"need":{"initialized":1}
,"initialized":{"kernel":1}
,"reduce":{"system":1,"time":1,"compile-time":1,"boot":1}
,"configure":{"kernel":1,"whether":1}
,"respect":{"constraints":1}
,"constraints":{"jetson":1}
,"jetson":{"tegra":1}
,"running":{"l4t":1,"flash":1}
,"l4t":{"default":1}
,"second":{"cold":1}
,"cold":{"power-on":1}
,"power-on":{"begin":1}
,"begin":{"showing":1}
,"showing":{"login":1}
,"login":{"prompt":1}
,"prompt":{"following":1}
,"following":{"optimization":1,"differences":1,"configuration":1,"modifi":1,"running":1,"topics":1}
,"techniques":{"pplied":1}
,"pplied":{"process":1}
,"process":{"reduced":1}
,"reduced":{"approximate":1,"ram":1}
,"approximate":{"three":1}
,"three":{"seconds":1}
,"seconds":{"device":1}
,"tree":{"nodes":1,"directory":1}
,"nodes":{"using":1,"device":1}
,"using":{"controller":1}
,"controller":{"tegra":1}
,"soc":{"disable":1}
,"disable":{"device":1,"rtc":1,"console":1,"aud":1,"debugging":1}
,"ree":{"entries":1}
,"entries":{"device":1}
,"directory":{"available":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002F<top>\u002Fhardware":{"nvidia\u002Fsoc\u002Ft18x":1}
,"nvidia\u002Fsoc\u002Ft18x":{"dtb":1}
,"dtb":{"flashed":1}
,"flashed":{"available":1}
,"<top>\u002Fhardware\u002Fnvidia\u002Fplatform\u002Ft18x\u002Fquill\u002Fkernel-d":{"ts\u002Ftegra186-quill-p3310-1000-a00-00-base.dts":1}
,"ts\u002Ftegra186-quill-p3310-1000-a00-00-base.dts":{"real-time":1}
,"real-time":{"clock":1,"clocks":1}
,"clock":{"two":1}
,"two":{"real-time":1}
,"clocks":{"(rtc)":1}
,"(rtc)":{"enabled":1}
,"enabled":{"default":1}
,"rtc":{"rtc":1,"enable":1,"fastest":1,"system":1,"work":1,"however":1,"isabling":1,"speed":1,"remove":1,"disabled":1,"{compatible":1}
,"enable":{"none":1,"rtc":1}
,"none":{"based":1}
,"developme":{"needs":1}
,"needs":{"aware":1}
,"aware":{"following":1}
,"differences":{"tegra":1}
,"fastest":{"response":1}
,"response":{"cannot":1,"transfer":1}
,"cannot":{"ork":1}
,"ork":{"backup":1}
,"backup":{"rtc":1,"time":1}
,"turned":{"pmic":1}
,"pmic":{"rtc":1}
,"work":{"backup":1}
,"however":{"low":1}
,"low":{"response":1}
,"transfer":{"average":1}
,"average":{"i2c":1}
,"i2c":{"shutdown":1}
,"shutdown":{"system":1}
,"concerned":{"backup":1}
,"isabling":{"rtc":1}
,"speed":{"boot":1}
,"remove":{"following":1,"console=ttys0":1,"uboot":1,"boot":1}
,"tegra21_defconfig":{"file":1}
,"file":{"config_rtc":1,"config_rtc_hctosys":1,"ollows":1,"system":1,"once":1,"secondary":1,"<top>\u002Ftegra_for_linux\u002Fp2771-000.conf":1,"identif":1}
,"config_rtc":{"_drv_max77620=y":1}
,"_drv_max77620=y":{"add":1}
,"add":{"following":1,"probe_type":1}
,"config_rtc_hctosys":{"tegra":1}
,"disabled":{"dts":1,"environment":1}
,"dts":{"file":1}
,"ollows":{"rtc":1}
,"{compatible":{"nvidia":1}
,"tegra-rtc":{"reg":1}
,"reg":{"=<0x00000000":1}
,"=<0x00000000":{"0x00000003":1,"0x00000005":1}
,"0x00000003":{"0x00000002":1}
,"0x00000002":{"0000009b>":1}
,"0000009b>":{"interrupts":1}
,"interrupts":{"=<0x00000000":1}
,"0x00000005":{"0x0000":1}
,"0x0000":{"0002>":1}
,"0002>":{"status":1}
,"status":{"disabled":1}
,"environment":{"configuration":1,"variable":1}
,"optimize":{"boot":1}
,"modifying":{"environment":1}
,"root":{"file":1}
,"console":{"uart":1,"logs":1,"console":1,"log":1}
,"uart":{"prints":1,"major":1,"console":1}
,"prints":{"uart":1}
,"major":{"bottleneck":1}
,"bottleneck":{"kernel":1}
,"console=ttys0":{"extlinux.conf":1}
,"extlinux.conf":{"configuration":1}
,"once":{"system":1,"required":1}
,"ready":{"deployment":1}
,"deployment":{"emove":1}
,"emove":{"uart":1}
,"logs":{"review":1,"framebuffer":1}
,"review":{"console":1}
,"framebuffer":{"console":1}
,"log":{"console=tty1":1}
,"console=tty1":{"extlinux.conf":1}
,"secondary":{"bootloader":1}
,"bootloader":{"remove":1}
,"uboot":{"secondary":1}
,"u-boot":{"following":1,"either":1}
,"modifi":{"cations":1}
,"cations":{"required":1}
,"flashing":{"edit":1}
,"edit":{"common":1,"line":1}
,"common":{"configuration":1}
,"<top>\u002Ftegra_for_linux\u002Fp2771-000.conf":{"use_uboot":1}
,"use_uboot":{"configure":1,"edit":1,"[-z":1}
,"whether":{"u-boot":1}
,"either":{"following":1}
,"flash":{"environment":1}
,"variable":{"use_uboot":1}
,"line":{"below":1}
,"below":{"use_uboot":1}
,"[-z":{"\u0022${use_uboot}":1}
,"\u0022${use_uboot}":{"use_uboot=0":1}
,"use_uboot=0":{"compile-time":1}
,"compile-time":{"configuration":1}
,"xamine":{"generated":1}
,"generated":{"configuration":1}
,"identif":{"configurations":1}
,"defined":{"iden":1}
,"iden":{"tify":1}
,"tify":{"ones":1}
,"ones":{"boot":1}
,"asynchronously":{"configurations":1}
,"drivers":{"probe":1,"load":1,"loaded":1,"required":1}
,"probe":{"executed":1,"asynchronous":1,"feature":1}
,"executed":{"async":1}
,"async":{"hronously":1}
,"hronously":{"separate":1}
,"separate":{"thread":1}
,"thread":{"instead":1,"additionally":1,"add":1}
,"instead":{"main":1}
,"main":{"initial":1}
,"initial":{"thread":1}
,"additionally":{"examine":1}
,"examine":{"required":1}
,"verify":{"programmed":1}
,"programmed":{"modules":1}
,"modules":{"drivers":1,"config_fuse_fs=m":1}
,"load":{"called":1}
,"called":{"drivers":1}
,"loaded":{"kernel":1}
,"image":{"reduced":1}
,"ram":{"space":1}
,"space":{"available":1}
,"topics":{"provide":1}
,"provide":{"examples":1}
,"examples":{"hese":1}
,"hese":{"conditions":1}
,"conditions":{"asynchronous":1}
,"asynchronous":{"probe":1}
,"feature":{"available":1}
,"version":{"3.18":1}
,"3.18":{"https:\u002F\u002Flkml.org\u002Flkml\u002F2015\u002F1\u002F16\u002F576":1}
,"https:\u002F\u002Flkml.org\u002Flkml\u002F2015\u002F1\u002F16\u002F576":{"move":1}
,"move":{"driver":1}
,"probe_type":{"driver":1}
,"follows":{"static":1,"config_snd_soc_tegra_alt":1}
,"static":{"struct":1}
,"struct":{"platform_driver":1}
,"platform_driver":{"sdhci_tegra_driver":1}
,"sdhci_tegra_driver":{"={.driver":1}
,"={.driver":{"={.name":1}
,"={.name":{"sdhci-tegra":1}
,"sdhci-tegra":{".of_match_table":1}
,".of_match_table":{"=sdhci_tegra_dt_m":1}
,"=sdhci_tegra_dt_m":{"atch":1}
,"atch":{".pm":1}
,".pm":{"=sdhci_pltfm_pmops":1}
,"=sdhci_pltfm_pmops":{".probe_type":1}
,".probe_type":{"=probe_prefer_asynchr":1}
,"=probe_prefer_asynchr":{"onous":1}
,"onous":{".probe":1}
,".probe":{"=sdhci_tegra_probe":1}
,"=sdhci_tegra_probe":{".remove":1}
,".remove":{"=sdhci_tegra_remove":1}
,"=sdhci_tegra_remove":{".shutdown":1}
,".shutdown":{"=sdhci_tegra_shutdown":1}
,"=sdhci_tegra_shutdown":{"file":1}
,"decrease":{"boot":1}
,"filesystem":{"modify":1}
,"modify":{"ollowing":1}
,"ollowing":{"configurations":1}
,"config_fuse_fs=m":{"config_vfat_fs=m":1}
,"config_vfat_fs=m":{"config_ntfs_fs=m":1}
,"config_ntfs_fs=m":{"sound":1}
,"sound":{"audio":1}
,"audio":{"codec":1}
,"codec":{"requires":1}
,"requires":{"time":1}
,"liminate":{"initialization":1}
,"initialization":{"time":1}
,"aud":{"configurations":1}
,"config_snd_soc_tegra_alt":{"config_snd_soc_tegra_alt_force_card_reg":1}
,"config_snd_soc_tegra_alt_force_card_reg":{"config_snd_soc_tegra_t186ref_alt":1}
,"config_snd_soc_tegra_t186ref_alt":{"config_snd_soc_tegra_t186ref_mobile_alt":1}
,"config_snd_soc_tegra_t186ref_mobile_alt":{"modularize":1}
,"modularize":{"kernel":1,"drivers":1}
,"during":{"boot":1}
,"hid":{"net":1}
,"net":{"usb":1}
,"usb":{"disable":1}
,"debugging":{"reduce":1,"kernel":1}
,"hack":{"production":1}
,"production":{"configuration":1}
,"example":{"ftrace":1}
,"ftrace":{"tracer":1}
,"tracer":{"kmemleak":1}
}
;Search.control.loadWordPairs(pairs);
