var pairs =
{
"quick":{"start":1}
,"start":{"guide":1}
,"guide":{"jetpack":1,"note":1,"linux":1}
,"jetpack":{"installer":1}
,"installer":{"automates":1}
,"automates":{"installation":1}
,"installation":{"process":1}
,"process":{"tx1":1}
,"tx1":{"tx2":1,"tegra210_linux_r28.2_aarch64.tbz2":1}
,"tx2":{"tx2i":1,"\u002Ftx2i":1}
,"tx2i":{"devices":1,"carrier":1,"p2597-c00":1}
,"devices":{"prompts":1,"attached":1}
,"prompts":{"lash":1}
,"lash":{"jetson":1}
,"jetson":{"developer":1,"tx2i":1,"host":1,"usb":1,"appears":1,"configuration":1,"tx2":1,"tx1":1,"devel":1,"develope":1}
,"developer":{"latest":1,"tools":1,"kit":1,"zone":1}
,"latest":{"image":1,"release":1,"version":1}
,"image":{"nstall":1}
,"nstall":{"developer":1}
,"tools":{"ost":1}
,"ost":{"developer":1}
,"kit":{"install":1,"jetson":1,"note":1,"available":1,"force":1,"micro-usb":1,"executing":1,"automati":1,"serial":1,"wired":1,"obtain":1}
,"install":{"libraries":1,"ation":1,"additional":1,"package":1,"<ubuntu-desktop>":1,"reboo":1}
,"libraries":{"apis":1}
,"apis":{"samples":1}
,"samples":{"documentation":1}
,"documentation":{"needed":1}
,"needed":{"jumpsta":1}
,"jumpsta":{"deve":1}
,"deve":{"lopment":1}
,"lopment":{"environment":1}
,"environment":{"customize":1,"proceed":1}
,"customize":{"install":1}
,"ation":{"setup":1}
,"setup":{"development":1,"erial":1}
,"development":{"environment":1}
,"proceed":{"ith":1}
,"ith":{"quick":1}
,"note":{"up-to-date":1,"minimum":1,"security":1}
,"up-to-date":{"quick":1,"platform":1}
,"linux":{"tegra":1,"host":1}
,"tegra":{"board":1}
,"board":{"upport":1,"cabled":1,"ext":1,"rjetson":1,"flash":1}
,"upport":{"package":1}
,"package":{"available":1,"download":1,"sam":1,"using":1}
,"available":{"http:\u002F\u002Fdeveloper2.download.nvidia":1,"\u002Fopt\u002Fnvidia\u002Fl4t-usb-device-mode\u002Fnv-l4t-usb-device-mode.sh":1,"nvidia":1}
,"http:\u002F\u002Fdeveloper2.download.nvidia":{".com\u002Fembedded\u002Fl4t\u002Fr28_release_v2":1}
,".com\u002Fembedded\u002Fl4t\u002Fr28_release_v2":{".0\u002Fbsp\u002Fl4t_quick_start_guide.txt":1}
,".0\u002Fbsp\u002Fl4t_quick_start_guide.txt":{"prerequisites":1}
,"prerequisites":{"jetson":1}
,"carrier":{"board":1}
,"cabled":{"follows":1}
,"follows":{"serial":1,"press":1}
,"serial":{"cable":1,"port":1,"console":1}
,"cable":{"plugged":1,"connects":1,"acquire":1}
,"plugged":{"serial":1,"on-board":1}
,"port":{"target":1,"hdmi":1,"system":1,"nvidia":1,"operates":1,"usb":1}
,"target":{"connected":1}
,"connected":{"linux":1,"working":1,"etson":1}
,"host":{"directly":1,"ethernet":1,"system":1,"locate":1,"systems":1}
,"directly":{"thro":1}
,"thro":{"ugh":1}
,"ugh":{"serial-to-usb":1}
,"serial-to-usb":{"converter":1}
,"converter":{"required":1}
,"required":{"setup":1}
,"erial":{"console":1}
,"console":{"linux":1,"default":1}
,"ethernet":{"cable":1,"adapter":1}
,"on-board":{"eth":1}
,"eth":{"ernet":1}
,"ernet":{"port":1}
,"hdmi":{"cable":1,"display":1}
,"connects":{"carrier":1}
,"ext":{"ernal":1}
,"ernal":{"hdmi":1,"emmc":1}
,"display":{"connect":1,"devices":1}
,"connect":{"usb":1,"ion":1,"jetson":1}
,"usb":{"peripherals":1,"hub":1,"port":1,"lug":1,"cabl":1,"devi":1,"mass":1,"thumb":1,"ethernet":1,"serial":1,"device":1,"flashing":1,"readme":1,"recovery":1}
,"peripherals":{"keyboard":1}
,"keyboard":{"ouse":1}
,"ouse":{"usb\u002Fethernet":1}
,"usb\u002Fethernet":{"adapter":1}
,"adapter":{"network":1,"usb":1,"wired":1}
,"network":{"connect":1,"cable":1,"nnection":1}
,"ion":{"usb":1}
,"hub":{"connected":1}
,"working":{"usb":1}
,"system":{"included":1,"using":1,"conside":1,"attached":1,"host":1,"powered":1,"connected":1,"sudo":1}
,"included":{"developer":1}
,"minimum":{"version":1}
,"version":{"supported":1,"l4t":1}
,"supported":{"base":1}
,"base":{"board":1}
,"rjetson":{"tx2i":1}
,"p2597-c00":{"p2597-c02":1}
,"p2597-c02":{"board":1}
,"flash":{"usb":1,"rootfilesystem":1,"l4t":1}
,"lug":{"jetson":1}
,"using":{"usb":1,"network":1,"commands":1,"command":1}
,"cabl":{"host":1,"system":1}
,"conside":{"jetson":1}
,"devi":{"jetson":1}
,"appears":{"combination":1,"root":1}
,"combination":{"usb":1}
,"mass":{"storage":1,"stor":1}
,"storage":{"device":1}
,"device":{"similar":1,"mode":1,"ode":1,"path":1,"locate":1,"force":1}
,"similar":{"usb":1,"name":1}
,"thumb":{"drive":1}
,"drive":{"usb":1}
,"nvidia":{"provided":1,"embedded":1,"password":1,"note":1}
,"provided":{"usb":1}
,"mode":{"default":1,"system":1,"follows":1,"flash":1}
,"default":{"conf":1,"login":1,"password":1}
,"conf":{"iguration":1}
,"iguration":{"script":1}
,"script":{"associated":1,"available":1}
,"associated":{"readme":1}
,"readme":{"descri":1,"file":1}
,"descri":{"bes":1}
,"bes":{"usb":1}
,"flashing":{"port":1,"procedure":1}
,"operates":{"device":1}
,"ode":{"jetson":1}
,"configuration":{"script":1}
,"\u002Fopt\u002Fnvidia\u002Fl4t-usb-device-mode\u002Fnv-l4t-usb-device-mode.sh":{"host":1}
,"attached":{"jetson":1,"jetso":1}
,"file":{"appears":1,"anager":1,"download":1}
,"root":{"directory":1}
,"directory":{"jetson":1}
,"stor":{"age":1}
,"age":{"device":1}
,"path":{"dependent":1}
,"dependent":{"operating":1}
,"operating":{"system":1}
,"locate":{"readme":1}
,"anager":{"application":1}
,"application":{"navigate":1}
,"navigate":{"contents":1}
,"contents":{"jets":1}
,"jets":{"usb":1}
,"download":{"latest":1}
,"release":{"package":1,"reset":1,"recovery":1,"onto":1,"notes":1}
,"l4t":{"release":1}
,"sam":{"ple":1}
,"ple":{"filesystem":1}
,"filesystem":{"jetson":1}
,"embedded":{"developer":1}
,"zone":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Flinux-tegra":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Flinux-tegra":{"untar":1}
,"untar":{"files":1}
,"files":{"assemb":1}
,"assemb":{"rootfs":1}
,"rootfs":{"commands":1}
,"commands":{"sudo":1}
,"sudo":{"tar":1,".\u002Fapply_binaries.sh":1,".\u002Fflash.sh":1,"dhclient":1,"apt":1,"reboot":1}
,"tar":{"xpf":1}
,"xpf":{"$<l4t_release_package>":1,".\u002F$tegra_li":1}
,"$<l4t_release_package>":{"linux_for_tegra\u002Frootfs\u002Fsudo":1}
,"linux_for_tegra\u002Frootfs\u002Fsudo":{"tar":1}
,".\u002F$tegra_li":{"nux_sample-root-filesystem_r28.2":1}
,"nux_sample-root-filesystem_r28.2":{"_aarch64.tbz2":1}
,"_aarch64.tbz2":{"sudo":1,"jetson":1}
,".\u002Fapply_binaries.sh":{"<l4t_release_package":1}
,"<l4t_release_package":{"jetson":1}
,"\u002Ftx2i":{"tegra186_linux_r28":1}
,"tegra186_linux_r28":{"_aarch64.tbz2":1}
,"tegra210_linux_r28.2_aarch64.tbz2":{"place":1}
,"place":{"device":1,"jetson":1}
,"force":{"recovery":1,"usb":1,"button":1,"butt":1}
,"recovery":{"mode":1,"force":1}
,"powered":{"place":1}
,"devel":{"oper":1}
,"oper":{"kit":1}
,"press":{"hold":1,"release":1}
,"hold":{"recovery":1}
,"button":{"depressing":1,"press":1,"wait":1}
,"depressing":{"recovery":1}
,"reset":{"(rst)":1}
,"(rst)":{"button":1}
,"wait":{"seconds":1}
,"seconds":{"release":1}
,"butt":{"flash":1}
,"rootfilesystem":{"ernal":1}
,"emmc":{"ensure":1}
,"ensure":{"linux":1}
,"etson":{"developer":1}
,"micro-usb":{"port":1}
,"onto":{"jetson":1}
,"develope":{"kit":1}
,"executing":{"command":1}
,"command":{"linux":1,"prompt":1,"sudo":1,"link":1,"returns":1}
,".\u002Fflash.sh":{"$<platform>":1}
,"$<platform>":{"mmcblk0p1":1}
,"mmcblk0p1":{"<platform>":1}
,"<platform>":{"jetson-tx2":1}
,"jetson-tx2":{"jetson-tx2i":1}
,"jetson-tx2i":{"jetson-tx1":1}
,"jetson-tx1":{"flashing":1}
,"procedure":{"takes":1}
,"takes":{"approximately":1}
,"approximately":{"minu":1}
,"minu":{"tes":1}
,"tes":{"slower":1}
,"slower":{"host":1}
,"systems":{"upon":1}
,"upon":{"completion":1}
,"completion":{"jetson":1}
,"automati":{"cally":1}
,"cally":{"reboots":1}
,"reboots":{"command":1}
,"prompt":{"window":1}
,"window":{"opens":1}
,"opens":{"display":1}
,"jetso":{"developer":1}
,"login":{"credentials":1}
,"credentials":{"username":1}
,"username":{"nvidia":1}
,"password":{"nvidia":1,"install":1}
,"security":{"purposes":1}
,"purposes":{"best":1}
,"best":{"practices":1}
,"practices":{"nvid":1}
,"nvid":{"recommends":1}
,"recommends":{"changing":1}
,"changing":{"default":1}
,"additional":{"optional":1}
,"optional":{"ubuntu":1}
,"ubuntu":{"packages":1}
,"packages":{"connect":1,"wish":1}
,"wired":{"net":1,"ethernet":1,"jetson":1}
,"net":{"work":1}
,"work":{"using":1}
,"acquire":{"address":1}
,"address":{"running":1,"command":1}
,"running":{"graphical":1}
,"graphical":{"desktop":1}
,"desktop":{"environ":1}
,"environ":{"ment":1}
,"ment":{"automatically":1}
,"automatically":{"configures":1}
,"configures":{"network":1}
,"nnection":{"acquire":1}
,"dhclient":{"<interface>":1}
,"<interface>":{"<interface>":1,"name":1}
,"name":{"wired":1,"executing":1,"install":1,"packages":1}
,"obtain":{"name":1}
,"link":{"above":1}
,"above":{"command":1}
,"returns":{"eth0":1}
,"eth0":{"enx":1}
,"enx":{"<mac_address>":1}
,"<mac_address>":{"similar":1}
,"apt":{"update":1,"install":1}
,"update":{"sudo":1}
,"<ubuntu-desktop>":{"<ubuntu-desktop>":1,"name":1}
,"wish":{"install":1}
,"reboo":{"system":1}
,"reboot":{"consult":1}
,"consult":{"release":1}
,"notes":{"up-to-date":1}
,"platform":{"feature":1}
,"feature":{"usage":1}
,"usage":{"informa":1}
,"informa":{"tion":1}
}
;Search.control.loadWordPairs(pairs);
