var pairs =
{
"multimedia":{"tegra":1,"api":1,"playback":1,"framework":1,"player":1}
,"tegra":{"linux":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"includes":1}
,"includes":{"multim":1,"libargus":1}
,"multim":{"edia":1}
,"edia":{"framework":1}
,"framework":{"modules":1,"suc":1,"nvgstplayer":1,"information":1}
,"modules":{"testing":1}
,"testing":{"purposes":1,"multimedi":1}
,"purposes":{"gstreamer":1}
,"gstreamer":{"information":1,"user":1,"developers":1,"open":1,"downloand":1,"directly":1,"openmax":1,"consult":1,"directed":1}
,"information":{"consult":1,"nvgstplayer":1,"gstreamer":1}
,"consult":{"jetson":1,"http:\u002F\u002Fgstreamer.freedesktop.org":1,"readme":1}
,"jetson":{"tx1":1,"tx2":1}
,"tx1":{"accelerated":1}
,"accelerated":{"gstreamer":1,"nvidia":1}
,"user":{"guide":1}
,"guide":{"jetson":1,"multimedia":1}
,"tx2":{"accelerated":1}
,"api":{"multimedia":1,"collection":1,"includes":1,"encoding":1,"provides":1,"reference":1,"using":1}
,"collection":{"low-level":1}
,"low-level":{"support":1,"apis":1}
,"support":{"flexible":1}
,"flexible":{"application":1}
,"application":{"development":1,"velopment":1,"supports":1}
,"development":{"low-level":1}
,"apis":{"enable":1}
,"enable":{"flexibility":1}
,"flexibility":{"providi":1}
,"providi":{"better":1}
,"better":{"control":1}
,"control":{"underlying":1}
,"underlying":{"hardware":1}
,"hardware":{"blo":1}
,"blo":{"cks":1}
,"cks":{"multimedia":1}
,"libargus":{"imaging":1}
,"imaging":{"applications":1}
,"applications":{"v4l2":1,"provided":1,"omplete":1}
,"v4l2":{"api":1}
,"encoding":{"decoding":1}
,"decoding":{"scaling":1}
,"scaling":{"othe":1}
,"othe":{"media":1}
,"media":{"functions":1,"file":1}
,"functions":{"nvosd":1}
,"nvosd":{"on-screen":1}
,"on-screen":{"display":1}
,"display":{"buffer":1}
,"buffer":{"utility":1,"allocation":1}
,"utility":{"buffer":1,"testing":1}
,"allocation":{"management":1}
,"management":{"sharing":1}
,"sharing":{"transform":1}
,"transform":{"composition":1}
,"composition":{"blending":1,"object":1}
,"blending":{"example":1}
,"example":{"applications":1}
,"provided":{"demonstrate":1}
,"demonstrate":{"video":1}
,"video":{"decode":1,"encode":1,"convert":1,"data":1}
,"decode":{"video":1,"drm":1,"&jpeg":1}
,"encode":{"video":1,"image\u002Fvideo":1}
,"drm":{"based":1}
,"based":{"render":1}
,"render":{"video":1}
,"convert":{"jpeg":1}
,"jpeg":{"decode":1,"capture":1}
,"&jpeg":{"encode":1}
,"image\u002Fvideo":{"processing":1}
,"processing":{"cuda":1,"multicamera":1}
,"cuda":{"camera":1}
,"camera":{"jpeg":1,"capture":1}
,"capture":{"&video":1,"&cuda":1,"composition":1,"nvgstcapture":1,"appl":1}
,"&video":{"record":1}
,"record":{"camera":1}
,"&cuda":{"processing":1}
,"multicamera":{"capture":1}
,"object":{"detection":1}
,"detection":{"classification":1}
,"classification":{"cudnn":1}
,"cudnn":{"tensorrt":1}
,"tensorrt":{"opencv4tegra":1}
,"opencv4tegra":{"usage":1}
,"usage":{"multimedia":1}
,"provides":{"application":1}
,"velopment":{"path":1}
,"path":{"using":1}
,"using":{"framework":1,"nvgstplayer":1,"amera":1,"nvarguscamerasrc":1}
,"suc":{"gstreamer":1}
,"developers":{"leveraging":1}
,"leveraging":{"custo":1}
,"custo":{"frameworks":1}
,"frameworks":{"multimedia":1}
,"reference":{"available":1}
,"available":{"down":1,"nvgstplayer-1.0_readme.tx\u002Fnvgstcapture_readme.txt":1}
,"down":{"load":1}
,"load":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"gstreamer-based":1}
,"gstreamer-based":{"multimedia":1}
,"playback":{"gstreamer":1,"http\u002Frtsp":1,"cases":1,"playb":1}
,"open":{"source":1}
,"source":{"multimedia":1}
,"nvgstplayer":{"utility":1,"used":1,"applica":1,"multimedia":1,"nvgstcapture":1,"nvgstplayer":1,"command":1,"supports":1,"-1.0":1}
,"multimedi":{"local":1}
,"local":{"playback":1,"file":1}
,"http\u002Frtsp":{"streaming":1}
,"streaming":{"playback":1}
,"cases":{"nvgstplayer":1}
,"used":{"refere":1}
,"refere":{"nce":1}
,"nce":{"implementation":1}
,"implementation":{"information":1}
,"applica":{"tion":1}
,"tion":{"refer":1}
,"refer":{"readme":1}
,"readme":{"file":1,"nvgstplayer":1,"nvgst":1}
,"file":{"included":1,"available":1,"player":1,"playback":1,"information":1}
,"included":{"release":1}
,"release":{"installing":1}
,"installing":{"gstreamer":1}
,"downloand":{"nstall":1}
,"nstall":{"gstreamer":1}
,"directly":{"target":1}
,"target":{"wrapp":1}
,"wrapp":{"library":1}
,"library":{"gst-openmax":1}
,"gst-openmax":{"interface":1}
,"interface":{"gstreamer":1}
,"openmax":{"enables":1}
,"enables":{"accelerated":1}
,"nvidia":{"plug-ins":1}
,"plug-ins":{"gstre":1}
,"gstre":{"amer":1}
,"amer":{"framework":1}
,"http:\u002F\u002Fgstreamer.freedesktop.org":{"nvgstplayer":1}
,"player":{"test":1,"plays":1}
,"test":{"applicatio":1}
,"applicatio":{"running":1}
,"running":{"nvgstplayer":1}
,"nvgstcapture":{"applications":1,"command":1,"captures":1,"application":1}
,"omplete":{"prerequisite":1}
,"prerequisite":{"steps":1}
,"steps":{"install":1}
,"install":{"gstreamer":1}
,"directed":{"readme":1}
,"nvgstplayer-1.0_readme.tx\u002Fnvgstcapture_readme.txt":{"using":1}
,"command":{"line":1}
,"line":{"media":1,"camera":1}
,"plays":{"audio\u002Fvideo":1}
,"audio\u002Fvideo":{"files":1}
,"files":{"encapsulated":1}
,"encapsulated":{"mp4":1}
,"mp4":{"3gp":1}
,"3gp":{"avi":1}
,"avi":{"asf":1}
,"asf":{"wma":1}
,"wma":{"mkv":1}
,"mkv":{"m2ts":1}
,"m2ts":{"webm":1}
,"webm":{"mov":1}
,"mov":{"nvgstplayer":1}
,"supports":{"local":1,"argus":1}
,"playb":{"ack":1}
,"ack":{"rstp":1}
,"rstp":{"http":1}
,"http":{"udp":1}
,"udp":{"information":1}
,"-1.0":{"_readme.txt":1}
,"_readme.txt":{"treamer-based":1,"default":1}
,"treamer-based":{"camera":1}
,"appl":{"iation":1}
,"iation":{"nvgstcapture":1}
,"captures":{"video":1}
,"data":{"using":1,"ntainer":1}
,"amera":{"encapsulate":1}
,"encapsulate":{"encoded":1}
,"encoded":{"video":1}
,"ntainer":{"file":1}
,"nvgst":{"capture-1.0":1}
,"capture-1.0":{"_readme.txt":1}
,"default":{"nvgstcapture":1}
,"argus":{"api":1}
,"nvarguscamerasrc":{"plugin":1}
}
;Search.control.loadWordPairs(pairs);
