var pairs =
{
"related":{"documentation":1}
,"documentation":{"following":1,"included":1}
,"following":{"documentation":1}
,"included":{"nvidia":1}
,"nvidia":{"tegra":1,"jetson":1}
,"tegra":{"linux":1}
,"linux":{"driver":1}
,"driver":{"package":1}
,"package":{"(l4t)":1,"software":1,"tx1":1,"tx2":1,"multimedia":1}
,"(l4t)":{"tegra":1}
,"software":{"features":1}
,"features":{"accelerated":1}
,"accelerated":{"gstreamer":1}
,"gstreamer":{"user":1}
,"user":{"guide":1}
,"guide":{"jetson":1,"runtime":1,"tegra":1,"nvidia":1}
,"jetson":{"tx1":1,"tx1\u002Ftx":1}
,"tx1":{"developer":1,"tegra":1,"adaptation":1,"tx2":1}
,"developer":{"kit":1}
,"kit":{"user":1}
,"runtime":{"boot":1}
,"boot":{"loader":1}
,"loader":{"update":1}
,"update":{"process":1}
,"process":{"jetson":1}
,"adaptation":{"guide":1}
,"tx2":{"adaptation":1,"voltage":1}
,"tx1\u002Ftx":{"module":1}
,"module":{"eeprom":1}
,"eeprom":{"layout":1}
,"layout":{"nvidia":1}
,"voltage":{"current":1}
,"current":{"moni":1}
,"moni":{"tor":1}
,"tor":{"configuration":1}
,"configuration":{"application":1}
,"application":{"note":1}
,"note":{"tegra":1}
,"multimedia":{"api":1}
,"api":{"referenc":1}
,"referenc":{"available":1}
,"available":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1}
}
;Search.control.loadWordPairs(pairs);
