var pairs =
{
"secureboot":{"jetson":1,"follows":1,"process":1,"package":1,"download":1,"requires":1,"additio":1}
,"jetson":{"tx1":1,"tx2":1,"tk1":1,"target":1}
,"tx1":{"tx2":1,"fuse":1,"jetson":1,"0x21":1,"jetson-tx1":1,"sudo":1}
,"tx2":{"devices":1,"fuse":1,"0x18":1,"sets":1,"users":1,"jetson-tx2":1,"navigate":1,"sudo":1}
,"devices":{"nvidia":1,"fus":1,"contain":1,"security":1,"32-bit":1,"128-bit":1,"256-bit":1}
,"nvidia":{"tegra":1,"odm_lock":1,"jetson":1,"sets":1}
,"tegra":{"linux":1,"devices":1,"api":1,"fuses":1,"fuse":1,"device":1,"finds":1,"boar":1,"boards":1}
,"linux":{"driver":1,"host":1}
,"driver":{"package":1}
,"package":{"provides":1,"ecureboot":1,"necessary":1,"prerequisites":1,"openssl":1,"(bsp)":1,"prerequisite":1}
,"provides":{"boot":1,"means":1,"example":1}
,"boot":{"security":1,"codes":1,"programming":1,"key":1,"strap":1,"image":1,"installs":1,"files":1,"les":1,"stra":1,"file":1,"ready":1,"package":1}
,"security":{"using":1,"tegra":1,"boot":1,"applications":1,"application":1,"key":1,"module":1,"purposes":1}
,"using":{"ecureboot":1,"public":1,"private":1,"odmfuse.sh":1,"different":1,"user":1}
,"ecureboot":{"package":1,"prevents":1}
,"prevents":{"execution":1}
,"execution":{"unauthorized":1,"openssl":1}
,"unauthorized":{"boot":1}
,"codes":{"thro":1,"bct":1}
,"thro":{"ugh":1}
,"ugh":{"chain":1}
,"chain":{"trust":1}
,"trust":{"root-of-trust":1}
,"root-of-trust":{"on-di":1}
,"on-di":{"bootrom":1}
,"bootrom":{"code":1}
,"code":{"authenticate":1,"---a\u002Farch\u002Farm\u002Fcpu\u002Farm720t\u002Ftegra-common\u002Fcpu.c":1,"patch":1}
,"authenticate":{"boot":1}
,"bct":{"bootloader":1}
,"bootloader":{"warmboot":1,"directory":1,"note":1}
,"warmboot":{"vector":1}
,"vector":{"using":1}
,"public":{"key":1}
,"key":{"cryptography":1,"hash":1,"(sbk)":1,"security":1,"(dk)":1,"sec":1,"air":1,"file":1,"ensure":1,"conversion":1,"odm_production_mode":1,"used":1,"available":1,"encryption":1,"sed":1,"host":1}
,"cryptography":{"(pkc)":1}
,"(pkc)":{"stored":1}
,"stored":{"write-once-read-multiple":1,"file":1}
,"write-once-read-multiple":{"fuse":1}
,"fuse":{"devices":1,"changing":1,"bit":1,"value":1,"ite":1,"public_key_hash":1,"names":1,"specification":1,"name":1,"values":1,"burning":1,"without":1,"sign":1,"bits":1,"using":1,"pkc":1,"jtag":1,"field":1,"target":1,"sudo":1,"factory":1,"trusted":1,"blob":1,"command":1,"ost":1,"host":1,"burn":1,"put":1,"configurations":1}
,"fus":{"security":1,"blob":1}
,"contain":{"multiple":1}
,"multiple":{"fuses":1}
,"fuses":{"control":1,"writable":1,"users":1,"example":1,"fuse":1,"odm_production_mode":1,"without":1,"sets":1,"wish":1,"using":1,"navigate":1,"odmfuse.sh":1,"complete":1,"follows":1,"nvidia":1,"repeatedly":1,"target":1,"sudo":1,"actory":1,"generate":1}
,"control":{"different":1}
,"different":{"items":1,"security":1}
,"items":{"security":1}
,"programming":{"fuse":1}
,"changing":{"value":1}
,"value":{"fuse":1,"example":1,"(0x01)":1,"0x1":1,"bit":1,"odmfuse.sh":1,"quoted":1}
,"bit":{"non-reversible":1,"programmed":1,"already":1,"tegra":1,"disables":1,"diff":1,"burned":1,"locks":1,"[7-6]":1,"enable_watchdog":1,"enable_charger_detect":1,"ignore_dev_sel_straps":1,"[2-0]":1}
,"non-reversible":{"once":1}
,"once":{"fuse":1,"odm_production_mode":1,"fuseblob.tbz2":1}
,"programmed":{"ting":1,"once":1,"changing":1}
,"ting":{"cannot":1}
,"cannot":{"change":1}
,"change":{"fuse":1}
,"example":{"value":1,"uses":1,"0x2":1,"0xddccbbaa":1,"0x67452301efcdab8967452301efcdab89":1,"fuse":1,"setting":1,"<top>\u002Fout\u002Fl4t-ardbeg-release-hard\u002Fnvidia\u002Fu-boot":1,"burning":1,"reference":1,"flashing":1}
,"(0x01)":{"changed":1}
,"changed":{"(0x03)":1}
,"(0x03)":{"(0x05)":1}
,"(0x05)":{"(0x4)":1}
,"(0x4)":{"bit":1}
,"already":{"programmed":1}
,"odm_production_mode":{"fused":1,"example":1,"0x1":1,"sec":1,"sign":1,"flashes":1,"fuses":1}
,"fused":{"value":1,"values":1,"tegra":1}
,"0x1":{"further":1,"256":1,"-disable":1}
,"further":{"fuse":1}
,"ite":{"requests":1}
,"requests":{"blocked":1}
,"blocked":{"fused":1,"default":1,"specifying":1}
,"values":{"available":1,"generate":1}
,"available":{"provided":1,"option":1}
,"provided":{"tegra":1,"l4t":1,"source":1}
,"api":{"however":1}
,"however":{"odm_reserved":1,"msb":1}
,"odm_reserved":{"odm_lock":1,"programmable":1,"sec_boot_dev_cfg":1,"reservedodm":1,"example":1,"read":1,"field":1}
,"odm_lock":{"fields":1,"bit":1,"odmlock":1,"fuses":1}
,"fields":{"writable":1}
,"writable":{"until":1,"mfuse.sh":1}
,"until":{"odm_lock":1}
,"mfuse.sh":{"script":1}
,"script":{"perform":1,"example":1,"ubuntu@<target":1}
,"perform":{"fuse":1}
,"public_key_hash":{"pkc_disable":1,"rsa":1,"publickeyhash":1}
,"pkc_disable":{"secure_boot_key":1,"pkc":1,"pkcdisable":1}
,"secure_boot_key":{"odm_production_mode":1,"secure":1,"securebootkey":1}
,"uses":{"handled":1}
,"handled":{"l4t":1,"user":1}
,"l4t":{"secureboot":1,"secure":1,"release":1,"downloads":1,"board":1,"secu":1,"put":1,"sdk":1,"place":1,"execute":1,"bsp":1,"<your_local_l4t_path>":1,"installation":1}
,"follows":{"bitsize":1,"name":1,"burn":1,"option":1,"bit":1,"sudo":1,"jetson":1,"put":1}
,"bitsize":{"name":1}
,"name":{"default":1,"alias":1,"tegraflash":1,"description":1,"fuse":1}
,"default":{"value":1,"0xx":1,"odmfuse.sh":1,"uboot":1}
,"odmfuse.sh":{"odm_production_mode":1,"jtag_disable":1,"script":1,"extra":1,"pkc":1,"allows":1,"options":1,"--kek":1,"ript":1}
,"256":{"public_key_hash":1,"odm_reserved":1,"-bit":1}
,"rsa":{"public":1,"key-pair":1,"key":1}
,"hash":{"pkc_disable":1,".pem":1,"hex":1}
,"pkc":{"-0x1":1,"requires":1,"\u002Fodm_production":1,"flash":1,"encryptio":1,"[dk":1,"sbk":1,"fuses":1,"hash":1,"<key":1,"key":1,"protected":1,"signed":1,"<keyfile>":1,"ey.pem>":1,"<key.pem>":1,"<keyf":1,"<keyfi":1}
,"-0x1":{"-0x1":1,"128":1}
,"128":{"secure_boot_key":1}
,"secure":{"boot":1,"oot":1}
,"(sbk)":{"aes":1}
,"aes":{"encryption":1}
,"encryption":{"key":1,"keys":1}
,"applications":{"security":1,"used":1,"secureboot":1}
,"used":{"leave":1,"burn":1,"consult":1,"note":1,"high":1,"repeatedly":1,"repeated":1}
,"leave":{"untouched":1}
,"untouched":{"device_key":1,"uses":1}
,"device_key":{"device":1,"devicekey":1}
,"device":{"key":1,"erroneous":1,"connected":1,"depends":1,"expects":1,"forced":1,"force":1,"pkc":1,"clear":1,"recovery":1,"attached":1}
,"(dk)":{"device":1}
,"sec":{"urity":1}
,"urity":{"applications":1,"mode":1}
,"application":{"used":1,"da-08571-001_v2.0":1,"ote":1,"prepare":1,"name":1,"generate":1,"encrypt":1,"keys":1,"encr":1}
,"user":{"follows":1,"guide":1}
,"jtag_disable":{"0x1":1,"jtagdisable":1}
,"-disable":{"jtag":1}
,"jtag":{"256":1,"enabled":1,"disabled":1,"debugger":1,"access":1,"interface":1,"usage":1}
,"programmable":{"fuses":1}
,"users":{"direction":1,"skip":1}
,"direction":{"however":1}
,"msb":{"nvidia":1}
,"disables":{"write":1}
,"write":{"correspond":1}
,"correspond":{"ing":1}
,"ing":{"32-bit":1,"pkc":1}
,"32-bit":{"odm":1,"number":1,"big":1}
,"odm":{"fuses":1,"fuse":1,"production":1,"pro":1}
,"0x2":{"locks":1}
,"locks":{"b32-b63":1,"correspo":1,"first":1}
,"b32-b63":{"odm_reserved":1}
,"sec_boot_dev_cfg":{"depending":1,"secbootdeviceselect":1}
,"depending":{"sec_boot_dev_sel":1,"applicatio":1}
,"sec_boot_dev_sel":{"bit":1,"valid":1,"-0:emmc":1}
,"diff":{"erent":1}
,"erent":{"meaning":1}
,"meaning":{"sw_reserved":1,"follows":1}
,"sw_reserved":{"2-0":1,"swreserved":1}
,"2-0":{"sec_boot_dev_sel":1}
,"valid":{"ignore_dev_sel_straps":1}
,"ignore_dev_sel_straps":{"abled":1,"ignores":1,"-ignore":1}
,"abled":{"0=emmc":1}
,"0=emmc":{"1=spi":1}
,"1=spi":{"ignore_dev_sel_straps":1}
,"ignores":{"boot":1}
,"strap":{"enable_charger_detect":1}
,"enable_charger_detect":{"enable_watchdog":1,"bit":1}
,"enable_watchdog":{"7-6":1,"bit":1}
,"7-6":{"details":1}
,"details":{"hardware":1}
,"hardware":{"fuses":1,"security":1}
,"names":{"cons":1}
,"cons":{"ult":1}
,"ult":{"following":1}
,"following":{"documents":1,"workaround":1,"file":1,"<u-boot-built-path>\u002Fu-boot":1,"directory":1,"procedure":1}
,"documents":{"nvidia":1}
,"specification":{"application":1}
,"da-08571-001_v2.0":{"nvidia":1}
,"ote":{"da-08191-001_v04":1,"da-08415-001_v1.1":1}
,"da-08191-001_v04":{"nvidia":1}
,"da-08415-001_v1.1":{"fuse":1}
,"alias":{"recognized":1,"odm_production_mode":1}
,"recognized":{"tegraflash":1}
,"tegraflash":{"follows":1,"alias":1}
,"mode":{"public_key_hash":1,"burn":1,"0xxx":1,"flash":1,"fusing":1,"generate":1,"execute":1,"sign":1}
,"publickeyhash":{"pkc_disable":1}
,"pkcdisable":{"secure_boot_key":1}
,"securebootkey":{"device_key":1}
,"devicekey":{"jtag_disable":1}
,"jtagdisable":{"odm_reserved":1}
,"reservedodm":{"odm_lock":1}
,"odmlock":{"sec_boot_dev_cfg":1}
,"secbootdeviceselect":{"sw_reserved":1}
,"swreserved":{"overall":1}
,"overall":{"fusing":1}
,"fusing":{"signing":1,"accessing":1}
,"signing":{"binaries":1,"boot":1,"process":1,"host":1}
,"binaries":{"secureboot":1,"navigate":1,"execute":1,"exe":1,"without":1}
,"process":{"pkc":1,"protecting":1,"blocks":1,"integrated":1,"requirements":1}
,"requires":{"install":1,"2048-bit":1,"actual":1,"setup":1}
,"install":{"l4t":1,"secureboot":1}
,"necessary":{"prepare":1,"burns":1,"sign":1}
,"prepare":{"(kek)":1,"fus":1,"dk\u002Fkek\u002Fsbk\u002Fodm":1,"signed":1,"files":1}
,"(kek)":{"sbk":1,"\u002Fsbk\u002Fodm":1,"sbk]":1}
,"sbk":{"odm":1,"128-bit":1,"fuses":1}
,"generate":{"rsa":1,"key-pair":1,"applica":1,"fuse":1}
,"key-pair":{"burn":1,"generate":1,"xecute":1,"necessary":1}
,"burn":{"pkc":1,"fuse":1,"ing":1,"fuses":1}
,"\u002Fodm_production":{"fuses":1}
,"sign":{"boot":1,"oot":1,"binaries":1}
,"image":{"files":1,"blob":1,"signedimage.tbz2":1}
,"files":{"pkc":1,"process":1,"note":1,"boot":1,"preparing":1,"using":1}
,"flash":{"signed":1,"tegra":1,"host":1}
,"signed":{"boot":1,"prior":1,"binaries":1,"images":1,"image":1,"binary":1}
,"protecting":{"odm":1}
,"production":{"fuses":1,"fuse":1,"mode":1}
,"without":{"securing":1,"pkc":1,"actual":1}
,"securing":{"boot":1}
,"installs":{"l4t":1}
,"burns":{"odm":1}
,"sets":{"odm_production_mode":1,"jtag":1,"odm_lock=0xx":1,"odm_reserved=<value>":1,"production":1,"sw_reserved=0xxx":1,"device":1,"secure":1,"key":1,"256-bit":1}
,"flashes":{"clear":1}
,"clear":{"boot":1,"binaries":1}
,"note":{"process":1,"enerate":1,"hex":1,"ensure":1,"procedure":1,"security":1}
,"blocks":{"odm":1,"jtag":1}
,"burning":{"protects":1,"odm_reserved":1,"pkc":1,"fuse":1,"fuses":1}
,"protects":{"tegra":1}
,"erroneous":{"odm":1}
,"pro":{"duction":1}
,"duction":{"fuse":1}
,"burned":{"installing":1,"fuseblo":1,"fuseblob":1}
,"installing":{"l4t":1}
,"oot":{"package":1,"files":1}
,"prerequisites":{"x86":1}
,"x86":{"host":1,"linux":1}
,"host":{"running":1,"download":1,"type-b":1,"nec":1,"linux_for_tegra\u002Fdirectory":1,"once":1,"safe":1,"pla":1,"add":1,"system":1,"require":1,"command":1,"fab=c04":1,"separate":1,"flash":1,"factory":1}
,"running":{"ubuntu":1}
,"ubuntu":{"14.04":1}
,"14.04":{"lts":1}
,"lts":{"libftdi-dev":1}
,"libftdi-dev":{"usb":1}
,"usb":{"debug":1,"cable":1}
,"debug":{"port":1,"serial":1,"clock_enable_coresight":1}
,"port":{"support":1,"connected":1}
,"support":{"openssh-server":1,"package":1,"lp0":1}
,"openssh-server":{"package":1}
,"openssl":{"full":1,"genrsa":1,"generates":1,"utilities":1}
,"full":{"installation":1}
,"installation":{"latest":1,"download":1}
,"latest":{"l4t":1}
,"release":{"host":1,"ttps:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Flinux-tegra-a":1,"notes":1}
,"download":{"latest":1,"secureboot_<release_version>":1,"fuseblob.tbz2":1,"signedimage.tbz2":1}
,"ttps:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Flinux-tegra-a":{"rchive":1}
,"rchive":{"tegra":1}
,"connected":{"host":1}
,"type-b":{"micro":1}
,"micro":{"usb":1}
,"cable":{"debug":1}
,"serial":{"port":1}
,"nec":{"essary":1}
,"essary":{"install":1}
,"secureboot_<release_version>":{".tbz2":1}
,".tbz2":{"tarball":1,"navigate":1}
,"tarball":{"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":1,"includes":1}
,"https:\u002F\u002Fdeveloper.nvidia.com\u002Fembedded\u002Fdownloads":{"<release_version":1}
,"<release_version":{"identified":1}
,"identified":{"release":1}
,"notes":{"ntar":1}
,"ntar":{"file":1}
,"file":{"executing":1,"secureboot.tbz2":1,"named":1,"ename":1,"securely":1,"used":1,"restrict":1,"big":1,"steps":1,"pem":1,"jtag":1,"signing":1,"<u-boot-built-path>\u002Fu-boot-dtb-tegra.bin":1,"<u-boot-built-path>\u002Fspl\u002Fu-boot-spl":1,"binaries":1}
,"executing":{"command":1}
,"command":{"tar":1,"openssl":1,"patch":1,"tmp":1,"sudo":1,"requires":1}
,"tar":{"xvjf":1,"cvjf":1}
,"xvjf":{"secureboot_<release_version>":1,"secureboot.tbz2":1,"<download":1}
,"includes":{"secureboot.tbz2":1}
,"secureboot.tbz2":{"readme.secureboot.txt":1,"overlaying":1,"onto":1,"generating":1}
,"readme.secureboot.txt":{"provided":1}
,"downloads":{"site":1}
,"site":{"untar":1}
,"untar":{"secureboot.tbz2":1}
,"overlaying":{"l4t":1}
,"board":{"support":1,"boots":1,"copy":1,"ogin":1,"display":1}
,"(bsp)":{"extract":1}
,"extract":{"file":1}
,"onto":{"directory":1}
,"directory":{"level":1,"linux_for_tegra\u002Fdirectory":1,"installed":1,"factory":1,"fusecmd.sh":1,"used":1,"<top>":1,"following":1,"flash":1}
,"level":{"linux_for_tegra\u002Fdirectory":1,"security":1}
,"linux_for_tegra\u002Fdirectory":{"linux":1,"present":1,"located":1}
,"present":{"installing":1}
,"prerequisite":{"directory":1}
,"located":{"executing":1}
,"generating":{"rsa":1}
,"air":{"wish":1}
,"wish":{"lock":1,"security":1}
,"lock":{"fuse":1}
,"encryptio":{"skip":1}
,"skip":{"topic":1,"topi":1}
,"topic":{"l4t":1,"plan":1,"provide":1,"provides":1}
,"2048-bit":{"rsa":1}
,"xecute":{"command":1}
,"genrsa":{"-out":1}
,"-out":{"rsa_priv.pem":1}
,"rsa_priv.pem":{"2048":1,"file":1}
,"2048":{"upon":1}
,"upon":{"successful":1}
,"successful":{"execution":1}
,"generates":{"key":1,"<l4t":1}
,"named":{"rsa_priv.pem":1}
,"ename":{"save":1}
,"save":{"key":1}
,"securely":{"safely":1,"keep":1}
,"safely":{"key":1}
,"les":{"tegra":1}
,"depends":{"securely":1}
,"keep":{"key":1}
,"ensure":{"security":1,"recovery":1}
,"restrict":{"access":1}
,"access":{"permission":1,"additionally":1,"fuses":1,"fuse":1,"target\u2019s":1}
,"permission":{"minimum":1}
,"minimum":{"number":1}
,"number":{"personnel":1,"hardware":1,"stored":1,"0x00000000":1}
,"personnel":{"note":1}
,"enerate":{"truly":1,"signed":1}
,"truly":{"random":1}
,"random":{"number":1}
,"module":{"(hsm)":1,"user":1}
,"(hsm)":{"consult":1}
,"consult":{"hardware":1,"user":1}
,"guide":{"output":1,"securit":1,"appli":1,"pplication":1}
,"output":{"format":1,"bigendian":1}
,"format":{"private":1,"preparing":1,"example":1,"kek256":1,"leading":1,"tegra":1,"follows":1,"<sbk_file>":1,"--no-burn":1,"signing":1}
,"private":{"key":1}
,"conversion":{"pem":1}
,"pem":{"format":1}
,"preparing":{"(kek)":1,"uboot":1}
,"\u002Fsbk\u002Fodm":{"fuses":1}
,"bits":{"described":1,"applications":1,"may":1}
,"described":{"user":1}
,"securit":{"application":1}
,"description":{"applies":1,"0xxxxx":1}
,"applies":{"jetson":1}
,"tk1":{"devices":1,"0x40":1,"sets":1,"uboot":1,"flashing":1,"jetson-tk1":1,"navigate":1,"sudo":1}
,"big":{"endian":1}
,"endian":{"hex":1,"format":1,"hash":1}
,"hex":{"format":1,"numbers":1,"form":1,"number":1,"mat":1}
,"0xddccbbaa":{"kek":1}
,"kek":{"[0-2]":1}
,"[0-2]":{"applies":1,"<kek":1,"file>":1}
,"128-bit":{"number":1,"big":1}
,"kek256":{"applies":1}
,"256-bit":{"number":1,"key":1}
,"0x67452301efcdab8967452301efcdab89":{"sbk":1,"odm":1}
,"additio":{"nal":1}
,"nal":{"odm":1}
,"may":{"required":1}
,"required":{"specific":1}
,"specific":{"information":1,"fuse":1}
,"information":{"differs":1}
,"differs":{"depending":1}
,"applicatio":{"used":1,"keys":1}
,"appli":{"cation":1}
,"cation":{"used":1}
,"numbers":{"presented":1,"0xxxxxxxxx":1}
,"presented":{"bigendian":1}
,"bigendian":{"format":1,"hex":1,"rmat":1}
,"leading":{"omitted":1}
,"omitted":{"l4t":1}
,"secu":{"reboot":1}
,"reboot":{"software":1}
,"software":{"converts":1}
,"converts":{"bigendian":1}
,"form":{"format":1}
,"expects":{"standard":1}
,"standard":{"openssl":1,"jetson":1}
,"utilities":{"output":1}
,"rmat":{"burning":1}
,"[dk":{"(kek)":1}
,"sbk]":{"fuses":1}
,"steps":{"burn":1}
,"navigate":{"directory":1,"<top":1,"following":1,"bootloader":1}
,"installed":{"l4t":1}
,"put":{"tegra":1}
,"forced":{"recovery":1}
,"recovery":{"mode":1,"button":1}
,".pem":{"file":1,"[-d":1}
,"enabled":{"sudo":1,"unless":1}
,"sudo":{".\u002Fodmfuse.sh":1,".\u002Fflash.sh":1,".\u002Ftegrafuse.sh":1,"fab=c04":1,"tar":1,".\u002Ffusecmd.sh":1,"bootloader\u002Fflashcmd.txt":1,"noflash=1":1,"bootloader\u002F*.raw":1,"bash":1}
,".\u002Fodmfuse.sh":{"<chip_id>":1,"--noburn":1,"follows":1}
,"<chip_id>":{"pkc":1,"protect":1,"<chip_id>":1,"jetson":1}
,"<key":{".pem":1,"file>":1}
,"[-d":{"<dk_file>":1,"<dk":1}
,"<dk_file>":{"--kek":1,"applies":1,"mus":1}
,"--kek":{"{0-2}":1,"[0-2]":1}
,"{0-2}":{"<kek":1}
,"<kek":{"file>]":1,"[0-2]":1}
,"file>]":{"[-s":1,"jetson-tx2":1,"burning":1}
,"[-s":{"<sbk_file>]":1}
,"<sbk_file>]":{"fuse":1,"protect":1}
,"disabled":{"sudo":1}
,"protect":{"odm":1}
,"0x40":{"jetson":1,"pkc":1}
,"0x21":{"jetson":1,"pkc":1}
,"0x18":{"odmfuse.sh":1,"pkc":1}
,"extra":{"options":1}
,"options":{"odmfuse.sh":1,"blow":1}
,"allows":{"program":1}
,"program":{"odm":1}
,"complete":{"discretion":1}
,"discretion":{"skip":1}
,"plan":{"modify":1}
,"modify":{"fuses":1}
,"blow":{"odm":1}
,"option":{"description":1,"specified":1,"generates":1}
,"0xxxxx":{"ets":1}
,"ets":{"sec_boot_dev_cfg=<value>&0x3fff":1}
,"sec_boot_dev_cfg=<value>&0x3fff":{"detail":1}
,"detail":{"efer":1}
,"efer":{"trm":1}
,"trm":{"sets":1}
,"unless":{"option":1}
,"specified":{"usage":1}
,"usage":{"jtag":1,"blocked":1,"blocke":1}
,"debugger":{"blocked":1}
,"0xx":{"sets":1}
,"odm_lock=0xx":{"setting":1}
,"setting":{"bit":1,"odmlock=0x1":1}
,"correspo":{"nding":1}
,"nding":{"-bits":1}
,"-bits":{"odm_reserved":1}
,"odmlock=0x1":{"locks":1}
,"first":{"-bit":1,"third":1}
,"-bit":{"odm_reserved":1,"hex":1,"big":1}
,"read":{"etting":1,"<value>":1}
,"etting":{"odmlock=0x5":1}
,"odmlock=0x5":{"locks":1}
,"third":{"-bits":1}
,"field":{"read":1,"confusing":1}
,"<value>":{"sets":1}
,"odm_reserved=<value>":{"value":1}
,"quoted":{"series":1}
,"series":{"-bit":1}
,"0xxxxxxxxx":{"0xxxxxxxxx":1,"0xxxx":1,"0x00000000":1}
,"0xxxx":{"xxxxx":1}
,"xxxxx":{"0xxxxxxxxx":1}
,"0x00000000":{"last":1,"fuses":1}
,"last":{"-bit":1}
,"0xxx":{"sets":1}
,"sw_reserved=0xxx":{"name":1}
,"confusing":{"meaning":1}
,"[7-6]":{"bit":1}
,"-ignore":{"boot":1}
,"stra":{"bit":1}
,"[2-0]":{"sec_boot_dev_sel":1}
,"-0:emmc":{"2:spi":1}
,"2:spi":{"<dk_file>":1}
,"high":{"level":1}
,"applica":{"tion":1}
,"tion":{"encryption":1,"tegra":1}
,"keys":{"content":1}
,"content":{"<dk_file>":1,"<sbk_file>":1,"<kek":1,"<kek256":1,"inside":1}
,"mus":{"single":1}
,"single":{"32-bit":1,"128-bit":1,"256":1}
,"<sbk_file>":{"sets":1,"single":1}
,"encrypt":{"app":1,"application":1}
,"app":{"lication":1}
,"lication":{"keys":1}
,"--no-burn":{"prepare":1}
,"blob":{"used":1,"factory":1,"fuseblob.tbz2":1,"without":1,"prepare":1,"navigate":1}
,"repeatedly":{"factory":1,"instead":1}
,"factory":{"floor":1,"host":1,"environment":1,"fuse":1,"flash":1}
,"floor":{"ivate":1}
,"ivate":{"pkc":1}
,"<l4t":{"path>":1}
,"path>":{".\u002Flinux_for_teg":1,".\u002Flinux_for":1,".\u002Ffuseblob.tbz2":1,".\u002Fsignedimage":1}
,".\u002Flinux_for_teg":{"ra\u002Ffuseblob.tbz2":1}
,"ra\u002Ffuseblob.tbz2":{"downloaded":1}
,"downloaded":{"untarred":1}
,"untarred":{"<l4t":1,"linux_for_te":1}
,".\u002Flinux_for":{"_tegra":1}
,"_tegra":{"directory":1}
,"fuseblob.tbz2":{"untarred":1,"jetson":1,"factory":1}
,"linux_for_te":{"gra":1}
,"gra":{"directory":1}
,"fusecmd.sh":{"linux_for_teg":1}
,"linux_for_teg":{"ra\u002Fbooloader":1}
,"ra\u002Fbooloader":{"directory":1}
,"instead":{"stand":1}
,"stand":{"ard":1}
,"ard":{"odmfuse.sh":1}
,"file>":{"applies":1,"ust":1,"single":1,"u-boot":1,"--kek1":1,"--k":1,"--kek256":1,"<sbk":1}
,"ust":{"single":1}
,"mat":{"--kek256":1}
,"--kek256":{"<kek256":1}
,"<kek256":{"file>":1}
,"sed":{"high":1}
,"encr":{"ypt":1}
,"ypt":{"applicatio":1}
,"integrated":{"flashing":1}
,"flashing":{"process":1,"signed":1}
,"requirements":{"necessary":1}
,"uboot":{"jetson":1,"initializes":1,"jtag":1,"following":1,"rebuilt":1,"signed":1,"l4t":1,"build":1}
,"topi":{"default":1}
,"ript":{"blocks":1}
,"additionally":{"default":1}
,"initializes":{"jtag":1}
,"interface":{"even":1}
,"even":{"jtag":1}
,"specifying":{"tion":1}
,"finds":{"activity":1}
,"activity":{"illegal":1}
,"illegal":{"quietly":1}
,"quietly":{"halts":1}
,"halts":{"properly":1}
,"properly":{"enable":1,"fused":1}
,"enable":{"uboot":1,"lp0":1}
,"blocke":{"rebuild":1}
,"rebuild":{"uboot":1}
,"workaround":{"applie":1}
,"applie":{"source":1}
,"source":{"code":1,"tree>":1}
,"---a\u002Farch\u002Farm\u002Fcpu\u002Farm720t\u002Ftegra-common\u002Fcpu.c":{"b\u002Farch\u002Farm\u002Fcpu\u002Farm720t\u002Ftegra-common\u002Fcpu.c":1}
,"b\u002Farch\u002Farm\u002Fcpu\u002Farm720t\u002Ftegra-common\u002Fcpu.c":{"@@-348,6":1}
,"@@-348,6":{"348,7":1}
,"348,7":{"@@void":1}
,"@@void":{"reset_a9_cpu":1,"clock_enable_coresight":1}
,"reset_a9_cpu":{"(int":1}
,"(int":{"reset)":1,"enable)":1}
,"reset)":{"void":1}
,"void":{"clock_enable_coresight":1}
,"clock_enable_coresight":{"(int":1,"entry\u005Cn":1,"(in":1}
,"enable)":{"ifdef":1,"writel":1}
,"ifdef":{"config_enable_coresight":1}
,"config_enable_coresight":{"u32":1}
,"u32":{"rst":1}
,"rst":{"src":1}
,"src":{"debug":1}
,"entry\u005Cn":{"@@-373,6":1}
,"@@-373,6":{"374,7":1}
,"374,7":{"@@void":1}
,"(in":{"enable)":1}
,"writel":{"(rst":1}
,"(rst":{"csite_cpu_dbg3_lar)":1}
,"csite_cpu_dbg3_lar)":{"endif":1}
,"endif":{"\u002F*config_enable_coresight":1}
,"\u002F*config_enable_coresight":{"*\u002F}":1}
,"*\u002F}":{"enable":1}
,"lp0":{"sleep\u002Fwakeup":1,"pkc":1}
,"sleep\u002Fwakeup":{"enable":1}
,"protected":{"jetson":1}
,"rebuilt":{"provided":1}
,"patch":{"wb0":1,"-p1":1}
,"wb0":{"portion":1}
,"portion":{"uboot":1}
,"prior":{"lashing":1}
,"lashing":{"copy":1}
,"copy":{"0001-warmboot-change-wb-prepare-code-for-t1x4.patc":1,"following":1,"<top>":1}
,"0001-warmboot-change-wb-prepare-code-for-t1x4.patc":{"<top":1}
,"<top":{"u-boot":1}
,"u-boot":{"source":1,"u-bo":1}
,"tree>":{"<top>":1,"execute":1}
,"<top>":{".\u002Flinux_for_tegra\u002Fpkc":1,".\u002Flinux_for_tegra\u002Fbootloader\u002Fardbeg\u002Fu-boot":1,".\u002Flinux_for_tegra\u002Fbootloader\u002Fardbeg":1,".\u002Flinux_for_tegra\u002Fpkc\u002Ftegrafuse.sh":1}
,".\u002Flinux_for_tegra\u002Fpkc":{"navigate":1}
,"execute":{"command":1,"sudo":1}
,"-p1":{"<0001-warmboot-change-wb-prepare-code-f":1}
,"<0001-warmboot-change-wb-prepare-code-f":{"or-t1x4.patch":1}
,"or-t1x4.patch":{"build":1}
,"build":{"uboot":1,"path":1}
,"sdk":{"command":1}
,"tmp":{"locate":1}
,"locate":{"uboot":1}
,"path":{"example":1}
,"<top>\u002Fout\u002Fl4t-ardbeg-release-hard\u002Fnvidia\u002Fu-boot":{"copy":1}
,"<u-boot-built-path>\u002Fu-boot-dtb-tegra.bin":{"<top>":1}
,".\u002Flinux_for_tegra\u002Fbootloader\u002Fardbeg\u002Fu-boot":{"bin":1}
,"bin":{"copy":1}
,"<u-boot-built-path>\u002Fu-boot":{"<top>":1}
,".\u002Flinux_for_tegra\u002Fbootloader\u002Fardbeg":{"copy":1,"navigate":1,".\u002Fwb_sign.sh":1}
,"<u-boot-built-path>\u002Fspl\u002Fu-boot-spl":{"<top>":1}
,".\u002Fwb_sign.sh":{"u-boot.bin":1}
,"u-boot.bin":{"<key":1}
,"u-bo":{"ot-spl":1}
,"ot-spl":{"boot":1}
,"ready":{"support":1}
,"place":{"tegra":1}
,"force":{"recovery":1}
,".\u002Fflash.sh":{"<chipid>":1,"<device":1,"--no-flash":1,"follows":1,"--no-fla":1,"0x40":1}
,"<chipid>":{"pkc":1}
,"<keyfile>":{"evice":1,"jetson-tx2":1}
,"evice":{"name>":1}
,"name>":{"mmcblk0p1":1,"jetson":1,"<fuse":1}
,"mmcblk0p1":{"flash":1,"<device":1,"standard":1,"jetson":1,"sudo":1}
,"exe":{"cute":1}
,"cute":{"sudo":1}
,"<device":{"name>":1}
,"jetson-tk1":{"jetson":1,"mmcblk0p1":1}
,"jetson-tx1":{"jetson":1,"mmcblk0p1":1}
,"jetson-tx2":{"note":1,"standard":1,"jetson":1,"mmcblk0p1":1,"mmcblk0p":1}
,"button":{"pressed":1}
,"pressed":{"reset":1}
,"reset":{"ven":1}
,"ven":{"tegra":1}
,"accessing":{"fuse":1}
,"target":{"l4t":1,"board":1,"device":1}
,"means":{"access":1}
,"boots":{"access":1}
,".\u002Flinux_for_tegra\u002Fpkc\u002Ftegrafuse.sh":{"script":1}
,"ubuntu@<target":{"address>":1}
,"address>":{"access":1}
,"target\u2019s":{"fuses":1}
,"ogin":{"target":1}
,"display":{"fuses":1}
,".\u002Ftegrafuse.sh":{"amend":1,"<fuse":1}
,"amend":{"specific":1}
,"<fuse":{"name>":1,"value>":1}
,"value>":{"example":1}
,"environment":{"topic":1,"building":1,"requ":1,"burning":1,"req":1,"requires":1,"setup":1}
,"provide":{"example":1}
,"reference":{"implementation":1,"implement":1}
,"implementation":{"burning":1}
,"actory":{"environment":1}
,"building":{"fuse":1}
,"trusted":{"environment":1}
,"requ":{"ires":1}
,"ires":{"preparation":1}
,"preparation":{"key":1}
,"safe":{"ocation":1,"location":1}
,"ocation":{"generate":1}
,"dk\u002Fkek\u002Fsbk\u002Fodm":{"fuses":1}
,"--noburn":{"0x18":1,"<chipid>":1}
,"ey.pem>":{"[--kek0":1}
,"[--kek0":{"<kek0":1}
,"<kek0":{"file>":1}
,"--kek1":{"<kek1":1}
,"<kek1":{"file>":1,"ile>":1}
,"--k":{"ek2":1}
,"ek2":{"<kek2":1}
,"<kek2":{"file>":1}
,"<sbk":{"fil":1,"file>]":1}
,"fil":{"e>]":1}
,"e>]":{"jetson-tx2":1}
,"actual":{"target":1,"jetson":1}
,"pla":{"ced":1}
,"ced":{"force":1}
,"attached":{"host":1}
,"add":{"fab=c04":1}
,"fab=c04":{"front":1,".\u002Fodmfuse.sh":1,"fuselevel":1,"fuselevel=fuselevel_production":1}
,"front":{".\u002Fodmfuse.sh":1,".\u002Fflash.sh":1}
,"<key.pem>":{"[--kek0":1,"[-d":1}
,"ile>":{"--kek2":1,"jetson-tx2":1,"jetson-tx1":1}
,"--kek2":{"<kek2":1}
,"<dk":{"file>":1}
,"req":{"uires":1}
,"uires":{"x86":1}
,"system":{"factory":1}
,"ost":{"factory":1}
,"require":{"l4t":1}
,"bsp":{"installation":1}
,"<download":{"path>":1}
,".\u002Ffuseblob.tbz2":{"navigate":1}
,"procedure":{"burn":1,"used":1,"repare":1}
,".\u002Ffusecmd.sh":{"note":1}
,"repeated":{"multipl":1}
,"multipl":{"tegra":1,"properly":1}
,"boar":{"boards":1}
,"boards":{"burned":1,"boards":1}
,"fuseblo":{"exactly":1}
,"exactly":{"fuse":1,"signed":1}
,"configurations":{"example":1}
,"images":{"factory":1,"follows":1,"flashed":1}
,"implement":{"ation":1}
,"ation":{"flashing":1}
,"setup":{"signing":1,"x86":1}
,"location":{"following":1}
,"repare":{"signed":1}
,"<your_local_l4t_path>":{".\u002Flinux_for_tegra":1}
,".\u002Flinux_for_tegra":{"using":1}
,"pplication":{"clean":1}
,"clean":{"stale":1}
,"stale":{"unwanted":1}
,"unwanted":{"content":1}
,"inside":{"flashcmd.txt":1}
,"flashcmd.txt":{"sudo":1,"note":1}
,"bootloader\u002Fflashcmd.txt":{"enerate":1}
,"binary":{"image":1}
,"signedimage.tbz2":{"follows":1,"bootloader":1,"factory":1}
,"--no-flash":{"0x18":1,"0x21":1}
,"<keyf":{"ile>":1}
,"fuselevel":{"=fuselevel_production":1}
,"=fuselevel_production":{"front":1}
,"fuselevel=fuselevel_production":{".\u002Fflash.sh":1}
,"--no-fla":{"0x18":1}
,"mmcblk0p":{"jetson":1}
,"noflash=1":{".\u002Fflash.sh":1}
,"<keyfi":{"le>":1}
,"le>":{"jetson-tk1":1}
,"bootloader\u002F*.raw":{"sudo":1}
,"cvjf":{"signedimage.tbz2":1}
,"purposes":{"signing":1}
,"separate":{"machine":1}
,"machine":{"key":1}
,".\u002Fsignedimage":{".tbz2":1}
,"bash":{"flashcmd.txt":1}
,"fuseblob":{"exactly":1}
}
;Search.control.loadWordPairs(pairs);
