var pairs =
{
"atchdog":{"timer":1}
,"timer":{"application":1,"eventually":1,"starts":1,"used":1,"int":1}
,"application":{"terminates":1}
,"terminates":{"hangs":1}
,"hangs":{"watchdog":1}
,"watchdog":{"timer":1,"imers":1,"timers":1,"periodically":1,"cpus":1,"device":1,"timeout":1,"failed":1}
,"eventually":{"expires":1}
,"expires":{"triggering":1}
,"triggering":{"cpu":1}
,"cpu":{"reset":1,"causes":1}
,"reset":{"enabling":1,"signal":1,"enable":1}
,"enabling":{"system":1,"wdt0":1,"obtaining":1}
,"system":{"recover":1,"calls":1,"monitoring":1}
,"recover":{"without":1}
,"without":{"user":1}
,"user":{"tervention":1,"space":1}
,"tervention":{"note":1}
,"note":{"information":1}
,"information":{"available":1,"sample":1}
,"available":{"tegra":1}
,"tegra":{"watchdog":1,"technical":1,"(l4t)":1}
,"imers":{"configurations":1}
,"configurations":{"watchdog":1}
,"timers":{"(wdts)":1}
,"(wdts)":{"section":1}
,"section":{"tegra":1}
,"technical":{"reference":1}
,"reference":{"manual":1}
,"manual":{"(trm":1}
,"(trm":{"chip":1}
,"chip":{"wdt0":1}
,"wdt0":{"enabled":1,"linux":1,"user":1,"configured":1,"kernel":1,"driver":1,"enablement":1,"timeout":1,"device":1,"running":1}
,"enabled":{"linux":1,"kernel":1,"default":1}
,"linux":{"kernel":1,"tegra":1,"system":1}
,"kernel":{"default":1,"enable":1,"user":1,"uring":1,"boot":1,"loads":1,"pplication":1,"kernel":1,"configuration":1,"driver":1}
,"default":{"enable":1,"timeout":1,"wdt0":1,"value":1}
,"enable":{"enable":1,"wdt0":1,"watchdog":1}
,"space":{"hardware":1,"wdt0":1,"need":1,"using":1,"normally":1,"kernel":1}
,"hardware":{"turned":1,"sends":1}
,"turned":{"timer":1}
,"starts":{"decrementing":1,"resetting":1}
,"decrementing":{"default":1}
,"timeout":{"value":1,"condition":1,"\u002F*open":1}
,"value":{"120":1,"wdt":1,"default":1,"seconds":1,"kicking":1,"*\u002Fret":1,"failed":1,"d\u005Cn":1,"60s":1,"within":1}
,"120":{"seconds":1}
,"seconds":{"linux":1,"example":1,"-static":1}
,"(l4t)":{"wdt0":1}
,"configured":{"timer7":1}
,"timer7":{"therefore":1}
,"therefore":{"timer":1}
,"used":{"purpose":1}
,"purpose":{"timeout":1}
,"condition":{"occurs":1}
,"occurs":{"wdt":1}
,"wdt":{"hardware":1,"driver":1,"prevents":1,"alternatively":1,"kernel":1}
,"sends":{"reset":1}
,"signal":{"cpu":1}
,"causes":{"reset":1}
,"uring":{"kernel":1}
,"boot":{"kernel":1}
,"loads":{"wdt":1}
,"driver":{"starts":1,"linux":1,"enable":1,"drivers\u002Fwatchdog\u002Ftegra_wdt.c":1}
,"resetting":{"kicking":1}
,"kicking":{"wdt":1,"watchdog":1}
,"prevents":{"device":1}
,"device":{"restart":1,"node":1,"(wdt0":1,"failed":1}
,"restart":{"ing":1}
,"ing":{"normal":1,"enabling":1}
,"normal":{"operation":1}
,"operation":{"already":1}
,"already":{"enabled":1}
,"pplication":{"user":1}
,"need":{"kick":1,"enable":1}
,"kick":{"wdt":1,"watchdog":1}
,"alternatively":{"applications":1}
,"applications":{"manually":1}
,"manually":{"enable":1}
,"using":{"standard":1}
,"standard":{"linux":1}
,"calls":{"kicking":1}
,"periodically":{"information":1,"*\u002Fret":1}
,"sample":{"code":1}
,"code":{"enable":1,"shows":1}
,"normally":{"enabling":1}
,"enablement":{"sufficient":1}
,"sufficient":{"system":1}
,"monitoring":{"need":1}
,"cpus":{"modify":1}
,"modify":{"wdt":1,"wdt0":1,"heartbeat":1}
,"configuration":{"file":1}
,"file":{"arch\u002Farm\u002Fconfigs\u002Ftegra":1,"arch\u002Farm\u002Fconfigs\u002Ftegra12_defconfig":1}
,"arch\u002Farm\u002Fconfigs\u002Ftegra":{"21\u002F18_defconfig":1}
,"21\u002F18_defconfig":{"add":1}
,"add":{"following":1}
,"following":{"lines":1,"line":1,"user-space":1}
,"lines":{"config_watchdog_nowayout=y":1}
,"config_watchdog_nowayout=y":{"config_tegra_watchdog=y":1}
,"config_tegra_watchdog=y":{"config_tegra_watchdog_enable_on_probe=y":1,"wdt0":1}
,"config_tegra_watchdog_enable_on_probe=y":{"modify":1}
,"drivers\u002Fwatchdog\u002Ftegra_wdt.c":{"modify":1}
,"heartbeat":{"value":1,"=120":1,"=60":1}
,"example":{"below":1}
,"below":{"changes":1}
,"changes":{"timeout":1}
,"-static":{"int":1}
,"int":{"heartbeat":1,"ret":1,"timeout":1}
,"=120":{"static":1}
,"static":{"int":1}
,"=60":{"enable":1,"ret":1}
,"arch\u002Farm\u002Fconfigs\u002Ftegra12_defconfig":{"add":1}
,"line":{"config_watchdog_nowayout=y":1}
,"node":{"\u002Fdev\u002Fwatchdog0":1}
,"\u002Fdev\u002Fwatchdog0":{"following":1}
,"user-space":{"sample":1}
,"shows":{"open":1}
,"open":{"ing":1,"watchdog":1}
,"obtaining":{"specifiying":1}
,"specifiying":{"timeout":1}
,"ret":{"int":1,"=ioctl":1}
,"\u002F*open":{"wdt0":1}
,"(wdt0":{"enables":1}
,"enables":{"itself":1}
,"itself":{"automatic":1}
,"automatic":{"ally)":1}
,"ally)":{"*\u002Ffd":1}
,"*\u002Ffd":{"=open":1}
,"=open":{"(\u0022\u002Fdev\u002Fwatchdog0":1}
,"(\u0022\u002Fdev\u002Fwatchdog0":{"o_rdwr)":1}
,"o_rdwr)":{"(fd":1}
,"(fd":{"<0)":1,"wdioc_gettimeout":1,"wdioc_settimeout":1,"wdioc_keepalive":1}
,"<0)":{"{fprintf":1}
,"{fprintf":{"(stderr":1}
,"(stderr":{"open":1,"watchdog":1,"kick":1}
,"failed":{"!\u005Cn":1}
,"!\u005Cn":{"return":1}
,"return":{"\u002F*wdt0":1,"fprintf":1}
,"\u002F*wdt0":{"counting":1}
,"counting":{"check":1}
,"check":{"default":1}
,"*\u002Fret":{"=ioctl":1}
,"=ioctl":{"(fd":1}
,"wdioc_gettimeout":{"&timeout)":1}
,"&timeout)":{"(ret)":1}
,"(ret)":{"{fprintf":1}
,"fprintf":{"(stdout":1}
,"(stdout":{"watchdog":1,"new":1}
,"d\u005Cn":{"meout)":1,"timeout)":1}
,"meout)":{"\u002F*set":1}
,"\u002F*set":{"new":1}
,"new":{"timeout":1,"watchdog":1}
,"60s":{"*\u002F\u002F*note":1}
,"*\u002F\u002F*note":{"value":1}
,"within":{"1000]":1}
,"1000]":{"*\u002Ftimeout":1}
,"*\u002Ftimeout":{"=60":1}
,"wdioc_settimeout":{"&timeout)":1}
,"timeout)":{"\u002F*kick":1}
,"\u002F*kick":{"wdt0":1}
,"running":{"periodically":1}
,"wdioc_keepalive":{"null)":1}
,"null)":{"(ret)":1}
}
;Search.control.loadWordPairs(pairs);
